### ISSUE TITLE
[Feature] Customizeable expansion factor for ArrayList

### ISSUE THREAD

**Issue by austinoneil** [dotnet/coreclr#10046]
Currently, the expansion factor is 2.  That is a good expansion factor (in fact, I'd bet that it's used in most languages), but there are languages/runtimes with an expansion factor of 1.5 (e.g. Sun's JDK 6).  This may be useful to give the programmer more direct control over an ArrayList that grows rather quickly (or slowly, but memory is a constraint).

**Comment by mikedn** [comment]
This might be nice but it comes at a cost: the expansion factor needs to be stored in the list object so the list object becomes bigger (by 8 bytes on 64 bit).

And while It's true that there are implementations that use 1.5 instead of 2 I'm not sure there are any implementations that make the expansion factor customizable. Not even C++`s `std::vector` despite the fact that C++ has means to implement this without increasing the object size.

**Comment by gkhanna79** [comment]
CC @danmosemsft

**Comment by jkotas** [comment]
Related to https://github.com/dotnet/corefx/issues/23954. We can use the corefx issue to discuss whether customization of collection growth policies makes sense.

**Comment by jkotas** [comment]
BTW: The process for proposing new APIs is described here: https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/adding-api-guidelines.md
