### ISSUE TITLE
[Question] What's function set_new_pin_info used for?

### ISSUE THREAD

**Issue by 303248153** [dotnet/coreclr#10137]
Hello, I'm reading gc's plan_phase in coreclr,
There one thing I don't understandard,
I saw a function named set_new_pin_info which has following code
```
inline
void set_new_pin_info (mark* m, uint8_t* pin_free_space_start)
{
    m->len = pinned_plug (m) - pin_free_space_start;
#ifdef SHORT_PLUGS
    m->allocation_context_start_region = pin_free_space_start;
#endif //SHORT_PLUGS
}
```
This function is called by
```
set_new_pin_info (pinned_plug_entry, generation_allocation_pointer (gen));
```

If I understand correct, mark_stack_array store pinned plug's start address and len(`ps = plug_end - plug_start`), and `generation_allocation_pointer (gen)` increase in `allocate_in_condemned_generations` by each plug's size.
But this `set_new_pin_info` really confuse me, if the length of plug needed recalculate, it should be `some address - m.first`, what's the meaning of `m.first - generation_allocation_pointer (gen)`?

![1](https://cloud.githubusercontent.com/assets/16222094/23841320/4e8d9642-07e7-11e7-9ffe-d8eac37a5d67.jpg)

cc @swgillespie

**Comment by swgillespie** [comment]
> If I understand correct, mark_stack_array store pinned plug's start address and len(ps = plug_end - plug_start), and generation_allocation_pointer generation_allocation_pointer (gen) increase in allocate_in_condemned_generations by each plug's size.

Yes, this is correct. The generation allocator pointer is set to the end of the plug, so that we can continue allocating. We can't allocate over a pinned object and we can't move it, so the allocation pointer has to skip it.

> what's the meaning of m.first - generation_allocation_pointer (gen)?

Later on in the plan phase, we will add all[1] of the free spaces around plugs to the generation allocator's free list so that we can use it in the future to service allocations into that generation. To do this, we have to keep track of the free spaces that we observe when traversing a segment. `set_new_pin_info` is what records this information: `m->len` is set to the length of the free space between the allocation pointer and the start of the pinned plug (as you observed), while `m->start` remains as the start of the pinned plug. Together, these two bits of information allow us tor recover the location of the start of the free space preceding the pinned plug: `m->start - m->len`.

The code for this is in `seg_free_spaces::add` if you'd like to check it out.

[1]: We won't add to the free list if the free list size bucket for the size of the plug free space already has enough entries.

**Comment by 303248153** [comment]
Thank you! I see the reason now.
if pinned plug still in queue (mark_stack_bos ~ mark_stack_tos), m.len mean the plug size,
if pinned plug is dequeued (0 ~ mark_stack_bos). m.len mean the free space size just before the plug.
Also function `generation_fragmentation` will add these size to `frag`.
I'll check `seg_free_spaces::add` later, I'm still learning how `plan_phase` work.
