### ISSUE TITLE
Support calling into managed code multiple times

### ISSUE THREAD

**Issue by mspeterhon** [dotnet/coreclr#1016]
It would be useful to be able to call into managed code multiple times, with different assemblies.

Example:
call function a() in assembly A
call function b() in assembly B

But all within the same CLR execution environment.

This would be an alignment feature with .net hosting on Windows.

**Comment by ellismg** [comment]
This is about changing the hosting interfaces on Unix to be more like windows where you could created and run multiple delegates before shutting the runtime down.

**Comment by kangaroo** [comment]
CorHost2::ExecuteInDefaultAppDomain ?

**Comment by ellismg** [comment]
I think the basic problem is that we tried to provide a nice C API over the COM gunk responsible for booting the CLR, creating the App-Domain and Delegate, Running it and then shutting the runtime down, so folks didn't need to pull in corhost.h and all the associated stuff from the PAL.  If it's easy enough to enable just using corhost.h directly from a library without having to pull in a bunch of other typedefs and such, that's great, otherwise we might just consider augmenting unixinterface.cpp and have it expose some nicer flat C APIs.

**Comment by janvorli** [comment]
It seems that providing a C API instead of exposing the corhost.h interfaces would be preferable. The corhost.h refers to a lot of windows types, includes other headers, etc. When I was implementing the corerun for Linux, I have considered using the interfaces, but decided against that because of the mess it would create.

**Comment by mspeterhon** [comment]
I can agree, the more simple the better. Exposing any of the internal CoreCLR headers will not work, as those are not portable to any 3rd party application.

The best two options would be:
- expose an interface similar to the one right now (dlopen/function signature)
- expose a very simple C API (not like the COM API! :-))

**Comment by ellismg** [comment]
This was resolved with #1245.  Thanks @janvorli for doing the work!
