### ISSUE TITLE
Why does HttpClient dispose HttpContent?

### ISSUE THREAD

**Issue by aensidhe** [dotnet/coreclr#1018]
Hi.

I'm trying to write some tests on our custom protocol over http. So, I passed a fake message handler to client, like this (we don't use C#6 yet, so):

````
    public class CachingRequestsHandler : DelegatingHandler
    {
        public CachingRequestsHandler()
        {
            this.Requests = new List<HttpRequestMessage>();
        }

        public List<HttpRequestMessage> Requests { get; private set; }

        protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        {
            this.Requests.Add(request);
            return Task.FromResult(new HttpResponseMessage(HttpStatusCode.OK));
        }
    }
````

When in test I'm trying to inspect request's ````Content````, I'm getting an ````ObjectDisposedException````. As I found ```HttpClient``` [unconditionally disposes](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/HttpClient.cs#L360) ```Content```.

I have two questions:
- will this behavior change in future to give user some control over Content?
- how should I work around this issue, because I want to assert and test all parts of request: headers and content? Is there a fast and easy way to clone ````HttpRequestMessage````?

**Comment by SidharthNabar** [comment]
Hi @aensidhe ,

Thanks for reporting this.

Can you please create this issue to the corefx repo instead? the CoreCLR repo is for the CLR and HttpClient isn't a part of the CLR. It's a .NET framework library and is part of the corefx repo. Opening the issue there will ensure that it hits the radar of the right folks and the right searches :) 

Let's continue the discussion there so that the right audience gets to see it. Thanks!

Sid.

**Comment by aensidhe** [comment]
Oh, I'm so sorry. It seems I posted it to wrong tab. https://github.com/dotnet/corefx/issues/1794
