### ISSUE TITLE
Math.Tan does not return the expected output for `Math.Tan(Math.Atan(double.PositiveInfinity))`

### ISSUE THREAD

**Issue by tannergooding** [dotnet/coreclr#10276]
`Math.Tan` is the inverse operation of `Math.Atan` (and vice-versa). However, `Math.Tan(Math.Atan(double.PositiveInfinity))` (or `tan(π / 2)`) returns an extremely large value rather than `double.PositiveInfinity` (it returns `16331778728383844`).

It could be argued that this is "correct" with regards to the input, since the output of `Math.Atan(double.PositiveInfinity)` is not "exact". However, I believe special-casing this input (as is done with other 'upper-limits') is reasonable.

**Comment by tannergooding** [comment]
Also:
* `Math.Tan(+π)` returns a denormal value, rather than `+0.0`
* `Math.Tan(-π)` returns a denormal value, rather than `-0.0`
* `Math.Sin(+π` returns a denormal value, rather than `+0.0`
* `Math.Sin(-π` returns a denormal value, rather than `-0.0`
* `Math.Cos(+π/2)` returns a denormal value rather than `+0.0`
* `Math.Cos(-π/2)` returns a denormal value rather than `+0.0`

**Comment by dcwuser** [comment]
This behavior is not a bug, and the proposed change is not an improvement. There is, however, a way to address the issue raised here that is more in line with floating point standards.

### Precedent
The basic principle being suggested here is that inverse functions should be exact. But this is not the case even for the most tried-and-true implementations of the most basic floating point functions. For example,

```
double x = Math.Sqrt(2.0);
double y = x * x; 
```

results in y = 2.0000000000000004, not y = 2.0.

### The 1/2-ulp Gold Standard
The [IEEE754](https://www.csee.umbc.edu/~tsimo1/CMSC455/IEEE-754-2008.pdf) standard sets forth the gold standard for FP operations as follows in section 5.1:

> Each of the computational operations that return a numeric result specified by this standard shall be performed as if it first produced an intermediate result correct to infinite precision and with unbounded range, and then rounded that intermediate result, if necessary, to fit in the destination’s format.

What this is generally taken to mean is a 1/2-ulp standard. Regard the input as an exact value (which will be an integer times two-to-a-power; for Math.PI, it's 884279719003555 X 2^(-48)). Your function likely can't return the true mathematical value for that input, because that number likely isn't representable in the FP space. But it should return the representable value that is closest to it, which means it will always be within 1/2 an ulp of the true answer.

IEEE754 actually only requires this gold standard for the basic arithmetic operations and sqrt, not for trig functions. But by enunciating it as the requirement for these most basic functions, it is saying that this is what we should be striving for.

### This violates the gold standard
The reason Math.Sqrt(2.0) returns the result it does is that that number is as close as a double can get to sqrt(2), and the reason the square of that number is 2.0000000000000004 is that that number is as close as a double can get to the square of 6369051672525773 X 2^(-52), which is the value returned by Math.Sqrt(2.0). If we were to recognize 6369051672525773 X 2^(-52) as probably-trying-to-be sqrt(2) and return 2.0 instead, that would violate the gold standard.

The same logic applies to trig functions. Mathematica says Sin[884279719003555 X 2^(-48)] is actually about 1.224647E-16. We give Math.Sin(Math.PI) as about 1.224606E-16. If we were to instead recognize 884279719003555 X 2^(-48) as probably-intending-to-be-pi, and have Math.Sin return 0.0 instead of 1.224606E-16, we would actually be moving further away from the 1/2-ulp gold standard.

It's actually @tannergooding, by the way, who moved the .NET trig functions much closer to the 1/2-ulp gold standard by replacing the FSIN and FCOS calls by calls to a library which produces much-closer-to-gold-standard results.

### It's a Sisyphean task
If we were to adopt this principal of trying to recognize numbers probably-intended-to-be-constants, we would set ourselves up for an impossible task. Suppose we limit ourselves to the trig functions and inputs that are multiples of pi. Once we have made Sin(PI) right, what about Sin(2.0 * PI)? We start to have to check for an awful lot of special cases. And once we do, what about Sin(10000000.0 * PI)? 10000000.0 * PI is actually off from 10000000 pi in about the last half of its digits. If we set the result to zero, we would be off from the gold standard answer by many orders of magnitude.

### It breaks expectations
It's actually a well-known little tidbit among numericists that one should take Sin(PI) in order to discover how accurate PI is as a representation of pi. So the fact that we currently return 1.224606E-16 (which is, by the way, still very far above subnormal) is telling me that our PI is accurate to 16 digits. If you return 0.0, those of us who know and use this trick will be confused.

### There is an alternative
The problem of computing trig functions near multiple of pi has a long and storied history. The solution to this problem are the functions sinPi and cosPi, recommended in section 9.2 of the IEEE754 spec. These functions are supposed to return sin(pi * x) and cos(pi * x), where pi is the mathematical constant, not the FP constant PI. As a bonus, it's actually easier to implement sinPi and cosPi than sin and cos, because one does not have to do high-precision range reduction to find the multiple of pi that the argument represents. I think it would be great if we were to offer Math.SinPi and Math.CosPi.

**Comment by tannergooding** [comment]
👍 for `SinPi` and `CosPi` (`AtanPi` and `Atan2Pi` are also specified by the spec). It is worth noting that, since these methods are not covered by the CRT, they would need to be implemented manually.

**Comment by dcwuser** [comment]
I have opened #17353 to suggest implementing SinPi and CosPi. It contains a sample implementation that shows the implementation to be quite straightforward.

**Comment by tannergooding** [comment]
👍. I'll close this in favor of your issue.
