### ISSUE TITLE
[Question] Understanding demotion

### ISSUE THREAD

**Issue by 303248153** [dotnet/coreclr#10305]
Hello, I have a question, what's `demotion` in gc actually do?

Here is what I known:

- Demotion only occurs when plan_phase choose compact
- demotion_low is set to the **oldest pinned plug in queue** after **x >= gen 0 start** or **all plugs allocated in condemned gen**
	- See the picture
- demotion_high is set to heap_segment_allocated (ephemeral_heap_segment)

![demotion_low](https://cloud.githubusercontent.com/assets/16222094/24094672/ad210a1a-0d94-11e7-9f9b-0f9cbed6b23e.jpg)

But I can't see `settings.demotion` made any changes to `generation_plan_allocation_start`, when demotion is true, it just update card table and demote gc handlers.
For example, is possible that object in gen 1 demote to gen 0, how?

cc @swgillespie

**Comment by swgillespie** [comment]
> when demotion is true, it just update card table and demote gc handlers.

That's true, that's pretty much all it does. If a plug is pinned in Gen 1, the mechanism by which it is demoted is adjusting the bounds of Gen 0 so that plugs that were formerly in Gen 1 are now located within the boundaries of Gen 0. By recording the pins to be demoted using the generation's allocation pointer (`demotion_high` and `demotion_low`), the GC knows how to reshape its generational bounds so that our demoted plugs end up in the intended generation. (See `gc_heap::advance_pins_for_demotion` and `gc_heap::process_ephemeral_boundaries` for the code)

Updating the card table is done because the act of demoting an object may have introduced new cross-generational pointers. We don't have a way of knowing without walking the heap again whether or not cross-generational pointers exist to these demoted objects, so we just always set the cards for demoted objects. Future GCs will sort out whether or not they are necessary.

**Comment by 303248153** [comment]
Thank you again for your speedy reply!
Now I understand, update demotion_low is just reflect the truth that compact demote some pinned objects.
