### ISSUE TITLE
JIT\Directed\lifetime\lifetime2 fails

### ISSUE THREAD

**Issue by mmitche** [dotnet/coreclr#1037]
Currently failing (missed due to issue in test build script). Remove exclusion from issues.targets to repro

/cc @jkotas @CarolEidt @pgavlin 

See below for test and failure point.  It seems that either WaitForPendingFinalizers or GC.Collect isn’t doing what we expect it to do in this case.  The console output indicates that the finalizer is called after the WaitForPendingFinalizers call completes, which either means that GC.Collect did not pend the finalizer (and no collection happened) or WaitForPendingFinalizers did not do what it was supposed to.  Alternatively, it could mean there is a bug in the JIT lifetime reporting, but I’m inclined to think this is not the case unless we’re not running this test on Desktop.

Output:
“B.F

testcase f1-1

testcase f1-2
f1-2 failed
~B

Test Case:

    public static int aExists;
    public static int bExists;
    private abstract class A
    {
    }
    private class B : A
    {
        public B()
        {
            aExists++;
        }
        ~B()
        {
            aExists--;
            Console.WriteLine("~B");
        }

        public void F()
        {
            Console.WriteLine("B.F");
        }
    }
    private class C : B
    {
        public C()
        {
            bExists++;
        }
        ~C()
        {
            bExists--;
            Console.WriteLine("~C");
        }

        public void G()
        {
            Console.WriteLine("C.G");
        }
    }
    private static int f1()
    {
        B a = new B();
        a.F();

        Console.WriteLine();
        Console.WriteLine("testcase f1-1");
        if (aExists != 1)
        {
            Console.WriteLine("f1-1 failed");
            return -1;
        }

        GC.KeepAlive(a);
        a = null;
        GC.Collect();
        GC.WaitForPendingFinalizers();

        Console.WriteLine();
        Console.WriteLine("testcase f1-2");
        if (aExists != 0)
        {
            Console.WriteLine("f1-2 failed");
            return -1; // ~B is printed after above line, so collection/finalization looks late
        }

        C b = new C();
        b.G();
…

**Comment by cmckinsey** [comment]
This is known to be a bad test case that takes an illegal dependence on lifetime reporting. (You can reference VSTF 1176647 for details). I'll include some from my analysis a few months back:

"
Chris McKinsey changed Sub Status from 'Investigating' to 'Bug Understood' and made 1 other change.
This is a bad test - it does not work correctly under JitMinOpts=1. It basically tries to create an array, inserts object references into the array, goes back and null out each object reference in the array, induce GC, expect that the finalizers for each object then reserruct the object back into the array, and then checks that all the objects still exist live through a reference in the array.

 

The problem is that during the creation of the array objects, the JIT held live on the stack the last object stored into the array and reports it live through-out the method. Therefore it's never collected and finalizer never invoked, so one of the objects in the array is null when it should have been resurrected. Confirmed this behavior in the debugger - it is the last element of the array that was not resurrected and this is the same object that is held live on the stack by the JIT.

Fri, 2/6/2015 1:18 PM (show all changes)
"

**Comment by mmitche** [comment]
@cmckinsey Yeah after some discussion with @CarolEidt, we decided that it's best to either cut the test case or rewrite it so that we know that the object cannot be live at the time of the count check (meaning outside of f1's stack frame.
