### ISSUE TITLE
Some exports of mscoree.dll missing

### ISSUE THREAD

**Issue by zgxnet** [dotnet/coreclr#106]
Some methods in Marshal, such as ReadByte, ReadInt16, ReadInt32, needs some export functions from mscoree, e.g.
[DllImport(Win32Native.SHIM, EntryPoint="ND_RU1")]
public static extern byte ReadByte([MarshalAs(UnmanagedType.AsAny), In] Object ptr, int ofs)
However, such ND_ functions cannot found.
Does such function only support windows? I think linux/Mac also need them

**Comment by jkotas** [comment]
These methods (Marshal.Read/Write methods with Object argument ) are not part of the refactored .NET Core System.Runtime.InteropServices contract. They are not going to be available on Linux/Mac.

They should be marked with Condition="FEATURE_LEGACYSURFACE" in src\mcorlib\model.txt. It will get them physically excluded from mscorlib.dll on Linux/Mac. src\mcorlib\model.txt is used during mscorlib build to reduce it down to only what is actually needed for given platform.

**Comment by zgxnet** [comment]
I think the ND_ functions are just simple memory read/write. Why not support them on linux?
It is just a few lines of code

**Comment by jkotas** [comment]
We spent a lot of time on cleaning up and layering the .NET Core profiles to make it a lean foundation of .NET for future. .NET Core profile has many rarely used methods with questionable behavior removed.

The problem with Marshal Read/Write methods with Object argument is that they are very slow because of they need to marshal the Object argument. The marshalling of the Object argument has other questionable characteristics as well. These methods can be certainly implemented, but they are not good methods to have in .NET Core.

**Comment by zgxnet** [comment]
It seems that System.Drawing uses a lot of those functions. It will be great if coreclr can run winforms and wpf, and we can build .net core into desktop apps.

**Comment by zgxnet** [comment]
I think it is reasonable to remove these obsolete methods in coreclr. But I really hope that all the references can be removed in other parts of .net. In this way, .net core can run all the standard libraries.

**Comment by zgxnet** [comment]
An important use case of core clr is to publish portable desktop .net apps. And winforms and wpf are also required. So it is very important for core clr to support all the common assemblies.

**Comment by japj** [comment]
So, just checking if I understand it correctly.

This would mean modifying src\mscorlib\model.xml to add Condition="FEATURE_LEGACYSURFACE" to the Marshall Read/Writexxxx Members that have a System.Object argument? 
Is that all or is there more involved here?

And is there a way to test the correctness of this change on Windows? Or do I need to setup a Linux box to verify this?

**Comment by jkotas** [comment]
Yes, it is all that is required for the Marshal Read/Write methods.

Running "build.cmd unixmscorlib" on Windows, and verifying using ildasm that the methods are not in Unix mscorlib.dll anymore should be sufficient.

**Comment by japj** [comment]
It seems I have been hit with a missing DIA SDK issue, so I cannot even compile the project correctly atm.

It unfortunately seems I unstalled VS2012 at some point after installing VS2013 and a repair of VS2013/Update4 did not bring back the missing DIA SDK files so I can not continue due to a compile error with missing dia2.h.

**Comment by japj** [comment]
I got a bit further, however some functions still end up in the unixmscorlib and I don't really know where to solve that.

The BclRewriter\mscorlib.implClosure.xml for these entries shows:

    <Member Status="ImplClosure" VO="internal" Name="ReadInt64(System.Object,System.Int32)" />
    <Member Status="ImplClosure" VO="internal" Name="WriteInt16(System.Object,System.Int32,System.Int16)" />
    <Member Status="ImplClosure" VO="internal" Name="WriteInt64(System.Object,System.Int32,System.Int64)" />

Any idea what might be causing this so I can look into it more?

**Comment by jkotas** [comment]
Thanks for doing the due-diligence to verify that the issue is actually fixed! Here is how to get to the bottom of this problem:

Run "ildasm.exe mscorlib.dll /out:mscorlib.il" and then search for where these methods are referenced. ildasm.exe is part of Windows SDK - it should be on your path in VS Developer Command Prompt.

It looks like some of the references are caused by overload resolution picking up the generic Object overload instead of the more specific one - adding an explicit cast of the argument to pick the specific overload should fix it.

**Comment by japj** [comment]
It seems there was a WriteInt16(Object, Int32, Char) call I missed and the Read/WriteInt64(Object) were due to Read/WriteIntPtr(Object)
