### ISSUE TITLE
Performance issues and execution time instability using dnx with CoreCLR

### ISSUE THREAD

**Issue by hpaiemen** [dotnet/coreclr#1060]
Hi,
I'm doing small bench tests to test the execution time stability for a given image processing algorithm. The goal is to port a full industrial image processing software from Windows (.net framework 4.5) to Linux (Ubuntu 14.04 LTS is the OS I use for my tests) and it needs to be efficient enough to do real time image processing. 

My tests :
I use a single algorithm from a C++ coded image processing library (with a C# wrapper, essentially pinvoke functions) in a loop and I compare every loop execution times to the overall average. I tested my code with Mono runtime and compiler and I got pretty good results except for some garbage collector issues in some loops. That being said, I decided to test it with the CoreCLR runtime expecting same good results but with less (or no) gc issues. Instead, the code running on the CoreCLR was unstable and gave some really impressive slow peaks. For example, on my linux machine, I get an average of 4 msec for one loop execution and I registered peak of more then 300 msec on some loops.

I use dnx to compile and execute my test program. My C# testing program is set to be high priority for the scheduler. I used system tap to monitor context switches on my dual core machine and I figured out that the main dnx thread is not bumped by another process while executing a abnormally long loop. The time lost does not come from the image processing library. I've tested it on a Windows 7 Embedded OS machine as well and got about the same results.

Is there a way to know what dnx is doing on those long loops (like a call stack or something like that) and am I the only one who observed those performance issues?

Thx.

**Comment by jkotas** [comment]
@brianrob Do you have a recommendation how to investigate this issue on Linux, with the tools that are available currently?

> I've tested it on a Windows 7 Embedded OS machine as well and got about the same results.

If you are able to reproduce the problem on Windows, I would recommend using [PerfView](http://www.microsoft.com/en-us/download/details.aspx?id=28567) to investigate it. Check the tutorial at http://channel9.msdn.com/Series/PerfView-Tutorial

**Comment by brianrob** [comment]
As @jkotas recommends, if you can reproduce this on Windows, then PerfView is the right tool to use to investigate further.

If it only repros on Linux, then you can capture a trace on Linux using the Linux profiler "Perf".  Perf can be installed on Debian/Ubuntu by installing the linux-tools-common package.

Then, follow these instructions:

1. Run "perf record -a -g -F 999" to start collecting CPU samples.  The shell will hang until you CTRL-C to stop collection.
2. In the shell that you're going to run the repro in, run "export COMPlus_PerfMapEnabled=1".  This will allow Perf to resolve managed code stack frames.
3. Run the repro (e.g. ./corerun <foo.exe>).  You should need just enough to trace to capture a repro - hopefully not more than 10-20 seconds.  If you need more, you can let the repro run for a while and then run the Perf command in step 1 once the problem repros.
4. Stop collection by hitting CTRL-C in the shell running Perf.
5. Run "perf report" and you'll be presented with an ncurses viewer for the perf data.

Note that this will only collect CPU samples, so if the problem is related to blocked time, it won't show up.  However, perf can also collect context switches (see man perf record).

Hope that helps.

**Comment by hpaiemen** [comment]
I used PerfView on Windows and figured out that it was still a garbage collector problem, something to do with a very too large gen1 collect... Anyway, I will continue investigating the gc process to find a way to optimize my program and avoid long loop over time.

Thx for your answers, it has been helpful.

**Comment by brianrob** [comment]
Great.  You may find that the GCStats view in PerfView will be helpful - it will give you details about each individual GC.
