### ISSUE TITLE
Array.Copy doesn't handle pointer-objref conversions

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/coreclr#10646]
This should probably throw a `ArrayTypeMismatchException` like e.g. the `IntPtr[]` and `int*[]` case does, but it does something horrible instead:

```csharp
using System;

unsafe class Program
{
    static int Main()
    {
        int*[] inarr = new int*[] { (int*)1, (int*)2 };
        object[] oarr = new object[inarr.Length];
        Array.Copy(inarr, oarr, inarr.Length);
        Array.Copy(oarr, inarr, inarr.Length);
        return 100;
    }
}
```

Neither of these `Array.Copy` should succeed.

**Comment by danmosemsft** [comment]
@MichalStrehovsky @gkhanna79 should this be fixed in the VM side? The copying seems to be done there.

**Comment by MichalStrehovsky** [comment]
I assume it should do the check/throw from the same place that the "copy IntPtr[]` to `int*[]`" throws.

My guess is somewhere in `src\classlibnative\bcltype\arraynative.cpp` (i.e. not VM) but I'm not a CoreCLR dev and I didn't step through it.

**Comment by gkhanna79** [comment]
@MichalStrehovsky is possibly right about where the fix might be but someone should debug it to ensure the right thing happens. Do you have someone to look into this? If not, I can see if someone on my team can help.

**Comment by rartemev** [comment]
According to https://msdn.microsoft.com/en-us/library/t2yzs44b.aspx
>If you use unsafe code, it is your responsibility to ensure that your code does not introduce security risks or pointer errors.

You should guarantee that unsafe code is correct. `int*[] inarr = new int*[] { (int*)1, (int*)2 };` does not seem like this even for C/C++.

As I can see the code is getting failed with
>!CREATE_CHECK_STRING(!"Detected use of a corrupted OBJECTREF. Possible GC hole.")

which in this case means runtime (especially GC) finds incorrect object pointer in the object array. At the same time the Array.Copy works correct because int* is inherited from object and it is possible to copy from int*[] to object[]. 

So I do not think that is a real bug. According to ECMA-335 behavior is by design and runtime performs all required checks.

**Comment by danmosemsft** [comment]
@gkhanna79 I think it might be better if one of your devs took a look given we rarely venture into the VM side..

**Comment by tarekgh** [comment]
To mention: 

```C#
Array.Copy(inarr, oarr, inarr.Length);
```

Doesn't throw on the desktop. so we need to decide if we need to be compatible here or not. 

```C#
Array.Copy(oarr, inarr, inarr.Length);
``` 
does throw the following exception (with no stack trace) as I see it in VS: 

```
FatalExecutionEngineError occurred
  HResult=-2146233082
  Message=Exception of type 'System.ExecutionEngineException' was thrown.
  InnerException: 
```

**Comment by jkotas** [comment]
Both of these are bugs in desktop. We do not want to be compatible with the bug in neither of these two cases.

**Comment by tarekgh** [comment]
I can see copying from object[] to int*[] shouldn't be allowed. but why Copying int*[] to object[] shouldn't be allowed?

**Comment by jkotas** [comment]
`int*` and `object` are not castable, convertible or boxable in either direction.

**Comment by tarekgh** [comment]
Thanks, I didn't know we cannot cast int* to object. thanks for clarification. Why we don't allow copying `int*[]` to `IntPtr[]` while we can cast `int*` to `IntPtr`?

**Comment by jkotas** [comment]
> Thanks, I didn't know we cannot cast int* to object. thanks for clarification

BTW: You can try this today that's pretty bad:

```
static unsafe void Main() {
        int*[] inarr = new int*[] { (int*)0x12345678, (int*)0x23456789 };
        object[] oarr = new object[inarr.Length];
        Array.Copy(inarr, oarr, inarr.Length);
        Console.WriteLine(oarr[0].ToString()); // This line will cause bad AV
}
```

> Why we don't allow copying `int*[]` to `IntPtr[]`

No good reason. There are other cases that are disallowed in Array.Copy for no good reason. The one  discussed in https://github.com/dotnet/corefx/issues/13816 is around enums:

```
var a1 = new MyEnum[1];
var a2 = new int[1];

Array.Copy(a1, a2, 1); // works today
Array.Copy(a2, a1, 1); // fails today, we want to make it work
```

**Comment by tarekgh** [comment]
@gkhanna79 I have tried to take a look and it is better to get someone from the type system team to look at it. here is what I am seeing for example when copying int*[]  to Object[]:

'ArrayNative::ArrayCopy' will call 'ArrayNative::CanAssignArrayTypeNoGC' which will call 'TypeHandle::CanCastToNoGC' to check if can cast int* to object. int* has type descriptor which will make  'TypeHandle::CanCastToNoGC' to call 'TypeDesc::CanCastToNoGC' which will call 'MethodTable::CanCastToClassOrInterfaceNoGC' which will check the target type "Object" and find it as class then it calls 'MethodTable::CanCastToClassNoGC'. this method will return true (which is not correct according to the discussion in this issue). The reason 'MethodTable::CanCastToClassNoGC' return true is it gets the method table of int* and its hierarchy and check them against the method table of the Object. that eventually find a match and then return true. 

```C#
   // If there are no variant type parameters, just chase the hierarchy
    else
    {
        PTR_VOID pMT = this;

        do {
            if (pMT == pTargetMT)
                return TypeHandle::CanCast;

            pMT = MethodTable::GetParentMethodTableOrIndirection(pMT);
        } while (pMT);
```

We can fix this in `ArrayNative::CanAssignArrayTypeNoGC` before we do the casting check by checking the TypeHandle of both types but I think this is not the right fix as I think `TypeHandle::CanCastToNoGC` should do the right thing an return false.

here is the stack if this can help:

```
00 00000074`0a37a1e0 00007ffb`0f89d1c8 coreclr!MethodTable::CanCastToClassNoGC+0x609 [f:\oss\coreclr\src\vm\methodtable.cpp @ 1774] 
01 00000074`0a37a4a0 00007ffb`0faef49e coreclr!MethodTable::CanCastToClassOrInterfaceNoGC+0x518 [f:\oss\coreclr\src\vm\methodtable.inl @ 1691] 
02 00000074`0a37a710 00007ffb`0faa6e9d coreclr!TypeDesc::CanCastToNoGC+0x3be [f:\oss\coreclr\src\vm\typedesc.cpp @ 622] 
03 00000074`0a37a8c0 00007ffb`1016ea54 coreclr!TypeHandle::CanCastToNoGC+0x4d [f:\oss\coreclr\src\vm\typehandle.cpp @ 751] 
04 00000074`0a37a900 00007ffb`1016bfcf coreclr!ArrayNative::CanAssignArrayTypeNoGC+0x634 [f:\oss\coreclr\src\classlibnative\bcltype\arraynative.cpp @ 337] 
05 00000074`0a37aaf0 00007ffb`0e578062 coreclr!ArrayNative::ArrayCopy+0x6ef
```

side question: do we really need to fix this for v2? I am not sure how risky the fix is.

**Comment by gkhanna79** [comment]
CC @janvorli

**Comment by jkotas** [comment]
https://github.com/dotnet/coreclr/issues/10646
