### ISSUE TITLE
PInvoke with Reference Return throws MarshalDirectiveException

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/coreclr#10687]
Using the files below:

Native (C):
```c
static int shared = 4;
int* test() {
    return &shared;
}
```

Managed (C#)
```csharp
using System.Runtime.InteropServices;
public class Program {

    [DllImport("Library Name", EntryPoint="Entry Point")]
    private static extern ref int test();

    public static void Main(string[] args) {
           ref int a = ref test(); // Throws MarshalDirectiveException
    }
}
```

Now that ref returns are supported in C#7, I had expected that the marshaler would have marshaled the return value back as a reference, just as the marshaler marshals a reference to a pointer for the method parameters.

I am willing to help contribute this feature if the CoreCLR team would be interested.

@jkotas

**Comment by jkotas** [comment]
cc @yizhang82 

This looks like another case that may be best handled by the marshalling code generators.

**Comment by yizhang82** [comment]
Personally I think allowing a p/invoke returning ref int is unsafe, since the ref int could be pointing to invalid memory, and people would only see AV when they access the ref return. It turns out that C# actually allow you to return a pointer as byref return which is rather surprising to me:

```csharp
using System;

namespace RefTest
{
    class UnsafeClass
    {
        public unsafe static ref int GetValue()
        {
            int *p = (int *)0x12345678;
            return ref *p;
        }
    }
    class Program
    {
        static void Main(string[] args)
        {
            ref int val = ref UnsafeClass.GetValue();
            Console.WriteLine("Value is: ");
            Console.WriteLine(val);
        }
    }
}
```
We would AV when you try to access val. From runtime perspective byref locals are simply managed pointers, so it's not surprising that it could lead to an AV. However, from C# developer perspective, the behavior is surprising because they expect C# compiler to make sure a ref local is safe, and it usually is. 

@jaredpar @jkotas Thoughts?

**Comment by jkotas** [comment]
> It turns out that C# actually allow you to return a pointer as byref return 

Right, unmanaged pointer can be converted converted to `ref`. It is not new - it was possible even before byref returns. For example, the following was possible since like C# 1.0:

```
static void foo(ref int x) {
    Console.WriteLine(x); // bad AV
}

static unsafe void Main() {
    foo(ref *(int*)0x1234578);
}
```

If you use unsafe code, you have to know what you are doing. If you get it wrong, you can get bad AV in different part of your program. That's by design.

>  I think allowing a p/invoke returning ref int is unsafe

I agree. It is not clear for how long is the returned unmanaged pointer going to be valid. Requiring `unsafe` and explicit unmanaged pointer conversion to `ref` in this situation seems good because of it makes it more obvious what is going on. It works fine today:

```
[DllImport("Library Name", EntryPoint="Entry Point")]
private static extern int* test();

public static unsafe void Main() {
       ref int a = ref *test();
}
```
