### ISSUE TITLE
First chance NullRef exception in EventProvider.GetDataFromController

### ISSUE THREAD

**Issue by benaadams** [dotnet/coreclr#10991]
During debugging startup from `AspNetCore.Hosting`; it gets unconditionally swallowed so doesn't break anything - but probably should avoid throwing exception in first place?

> System.Diagnostics.Tracing.EventProvider.GetDataFromController(Int32 etwSessionId, EVENT_FILTER_DESCRIPTOR* filterData, ControllerCommand& command, Byte[]& data, Int32& dataStart)
> at System.Diagnostics.Tracing.EventProvider.EtwEnableCallBack(Guid& sourceId, Int32 controlCode, Byte setLevel, Int64 anyKeyword, Int64 allKeyword, EVENT_FILTER_DESCRIPTOR* filterData, Void* callbackContext)
> at Microsoft.Win32.UnsafeNativeMethods.ManifestEtw.EventRegister(Guid& providerId, EtwEnableCallback enableCallback, Void* callbackContext, Int64& registrationHandle)
> at Microsoft.Win32.UnsafeNativeMethods.ManifestEtw.EventRegister(Guid& providerId, EtwEnableCallback enableCallback, Void* callbackContext, Int64& registrationHandle)
> at System.Diagnostics.Tracing.EventProvider.Register(Guid providerGuid)
> at System.Diagnostics.Tracing.EventSource.Initialize(Guid eventSourceGuid, String eventSourceName, String[] traits)
> at System.Diagnostics.Tracing.EventSource..ctor(EventSourceSettings settings, String[] traits)
> at System.Diagnostics.DiagnosticSourceEventSource..cctor()
> at System.Diagnostics.DiagnosticListener..ctor(String name)
> at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
> at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
> at TransportChoiceApp.Startup.Main(String[] args)

/cc @vancem @glennc @lmolkova

**Comment by vancem** [comment]
The stack trace is code that gets called when ETW providers are turned on, but before (or after) a particular provider is notified that it is enabled.     I did a simple test to try to repro, but was unsuccessful.   It is likely that particular providers need to be enabled, and it is may be that this is an issue for only some builds of .NET Core (although I don't believe much has changed in this particular point in the code).

What would be VERY helpful is the source code line where the exception occurs.   If the .NET Runtime involved is a standard shipped one, having a process dump, should be very helpful.   

If PerfView was on, using more or less standard options, it should also be collecting the exceptions being thrown.  Again, if the runtime being used is a shipped on, we can map that back to the source line.

Otherwise more details instructions on created the repro will be needed.  

Thanks

Vance

**Comment by benaadams** [comment]
sdk 2.0.0-preview1-005783 with changing VS MSBuildSdksPath environment as per https://github.com/aspnet/Announcements/issues/231

It seems its a VS 2017 listener issue as it also happens when attaching the debugger to a running process.

Have to build a coreclr to look into a different issue so will see if it reoccurs with a more recent build

**Comment by lmolkova** [comment]
According to the stack trace, this (or similar) issue was fixed in https://github.com/dotnet/corefx/issues/17492 about 3 weeks ago. Please let me know if it still reproduces with some recent build.

**Comment by benaadams** [comment]
I can't recreate this anymore using later build; may have been transitory
