### ISSUE TITLE
Path.GetFileName does not correctly handle file names with : character

### ISSUE THREAD

**Issue by Haacked** [dotnet/coreclr#1104]
On my machine, I added the following line to [this test](https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Extensions/tests/System/IO/Path.cs#L48).

``` csharp
Assert.Equal("file:name.exe", Path.GetFileName(Path.Combine("bar", "baz", "file:name.exe")));
```

That test fails because `Path.GetFileName(Path.Combine("bar", "baz", "file:name.exe"))` returns "name.exe".

That doesn't seem to be the correct behavior on any platform.

I'd expect this to either throw an exception (as it would in the case of "file|name.exe") OR I'd expect this to return "file:name.exe" since `:` is an allowed character in file names on Unix systems. Given the cross-platform goals of CoreFx, I assume the latter behavior is correct?

Of course, there's the tricky aspect of HFS+ supporting `:` as a path separator, but from my understanding, that's a legacy detail. APIs are supposed to accept `/` as a directory separator and the underlying system translates it to `:`, so I _think_ that assuming `:` is not a directory separator is fine.

_As an aside, I originally opened this over at https://github.com/dotnet/corefx/issues/1934. I couldn't find any unit tests of `Path.cs` in this project. I'm not sure what I'm doing wrong._

**Comment by jasonwilliams200OK** [comment]
Steps to repro on Windows from scratch:

```cmd
git clone https://github.com/dotnet/coreclr
cd coreclr
.\build.cmd
:: build spew.. will take some time to compile the whole thing
md experiments
copy bin\Product\Windows_NT.x64.Release\coreclr.dll .\experiments
copy bin\Product\Windows_NT.x64.Release\CoreRun.exe .\experiments
copy bin\Product\Windows_NT.x64.Release\mscorlib.dll .\experiments
cd experiments
notepad PathTest.cs
```

Paste the following

**Comment by jasonwilliams200OK** [comment]
Steps to repro on Windows from scratch:

```cmd
git clone https://github.com/dotnet/coreclr
cd coreclr
.\build.cmd
:: build spew.. will take some time to compile the whole thing
md experiments
copy bin\Product\Windows_NT.x64.Release\coreclr.dll .\experiments
copy bin\Product\Windows_NT.x64.Release\CoreRun.exe .\experiments
copy bin\Product\Windows_NT.x64.Release\mscorlib.dll .\experiments
cd experiments
notepad PathTest.cs
```

Paste the following

```c#
using System;
using System.IO;

public class Program
{
    public static void Main (string[] args)
    {
        var path = Path.Combine("bar", "baz", "file:name.exe");
        Console.WriteLine(path);
        Console.WriteLine(Path.GetFileName(path));
    }
}
```

Compile:

```c#
csc /nostdlib /noconfig /r:mscorlib.dll /out:PathTest.exe PathTest.cs
```

Run:

```cmd
.\CoreRun PathTest
```

Actual Result:

> bar\baz\file:name.exe
name.exe

Expected Result:

> bar\baz\file:name.exe
file:name.exe

Actual Result on Mono (using online compiler: http://www.tutorialspoint.com/compile_csharp_online.php):

> bar\baz\file:name.exe
file:name.exe



copy @stephentoub, @akoeplinger

**Comment by masonwheeler** [comment]
I know that `:` was the file separator in Mac OS Classic, but that shouldn't have any bearing on modern systems.

**Comment by Haacked** [comment]
> I know that : was the directory separator in Mac OS Classic, but that shouldn't have any bearing on modern systems.

So I won't be able to run the next gen ASP.NET on my Mac classic? Microsoft still doesn't get it, does it. :stuck_out_tongue: :wink: :trollface:

![image](https://cloud.githubusercontent.com/assets/19977/8094528/8b9c826a-0f7c-11e5-8bed-fbed33468787.png)

> On Windows, though, `:` separates the drive from the directory path, so it's not a valid character in a filename. Given the framework's Windows roots, that's most likely what you're tripping over here.

Yeah, that's exactly what's tripping up the current code. It first validates for invalid path characters. Well `:` is a valid path character on Windows, but _only_ as the drive separator.

Then the code works backwards finding the first path separator _or_ the volume separator (aka `:`). I think the validation of the path probably needs to be a bit more sophisticated on Windows.

If it helps, the way I ran into this is we're enumerating changes in a Git repository (via LibGit2Sharp via LibGit2) which presents us with a list of file paths. We then try to get the file name for the changed file. Our assumption was that if `Path.GetFileName` does not throw an exception, it would return us the correct file name.

The repository I happened to be working with was created on a Unix machine. This file was _not_ cloned to my machine (since it can't be created), but the git status still reports the path. I was expecting this situation to throw, but instead we simply get the wrong file name. :smile: 

It's easy enough for me to workaround, but it was very unexpected behavior and others could be bitten by this assumption. For example, if this code was run on a Mac or Unix machine, I would expect it to not throw, but return the correct and full file name.

**Comment by stephentoub** [comment]
> if this code was run on a Mac or Unix machine, I would expect it to not throw, but return the correct and full file name

Are you seeing otherwise on Linux or OSX?  I'd expect that to work with the code in mscorlib/corefx today.  (That's separate from the improper results you're seeing on Windows.)

**Comment by Haacked** [comment]
> Are you seeing otherwise on Linux or OSX?

@stephentoub Sorry, I'm not set up to test this particular code on Linux or OSX. I was just stating my expectation without any knowledge of whether my expectation is met or not on those systems. :smile: I only know what happens on Windows.

**Comment by stephentoub** [comment]
Ok :smile:

**Comment by hadibrais** [comment]
@Haacked Thanks for opening this subtle issue. The reason that **Path.GetFileName** is returning **name.exe** rather than throwing an exception or returning **file:name.exe** is that's how it was specified. The spec of this function says "throw an exception when the **path** argument contains one or more invalid *path* characters." Note that it doesn't say anything about invalid file name characters, which means anything can happen when an invalid file name character is present. So the behavior you have seen is, technically with respect to the spec, correct. Of course, this doesn't make sense. What should happen is that an exception should be thrown when an invalid file name or path character is present. That is, the **path** argument should be validated against a regular expression which in turn is platform dependent so that an exception is not thrown on Unix-based systems. This issue exists in both the .NET framework and .NET Core. Changing the implementation of GetFileName would be a breaking change, so I'm not sure what do at this point.

**Comment by Haacked** [comment]
> This issue exists in both the .NET framework and .NET Core. Changing the implementation of GetFileName would be a breaking change, so I'm not sure what to do at this point.

`Path.GetFileName2(...)` :trollface: 

I wasn't aware that .NET Core isn't open to breaking changes.

At the very least, it might be nice to have a public method that properly returns whether a path is valid. Or a method that splits a path into path segments.

**Comment by jasonwilliams200OK** [comment]
>  Path.GetFileName2(...)  :trollface: 

Or `Path.GetFileName(..., bool generousMode = false)` :smiley_cat:

**Comment by hadibrais** [comment]
Most probably GetFileName has to be deprecated along with other Path APIs. We'll have to determine how the Path APIs are typical used and then design a new set of APIs that are efficient, portable and make sense.

**Comment by stephentoub** [comment]
@weshaggard, thoughts on whether such a change would be an acceptable bug fix?

**Comment by weshaggard** [comment]
@Haacked the code in this coreclr repo is shared between the .NET Framework and .NET Core so we do have to be very cautious about making changes that break things on the .NET Framework. I've not looked deeply into the code but I do suspect that this would be a breaking change and so we would have to figure out how to mitigate that somehow. I do think we will be spending some time working on our path APIs in general in the face of x-plat so this is something we should look into figuring out how to fix.

@JeremyKuhne @eriicstj do you guys have any thoughts on this issue?

**Comment by ericstj** [comment]
I think quirking it on desktop would be reasonable if the behavior is wrong on Windows and needs to be fixed.  
That said, I think the Path APIs in general should be doing the right thing for the platform they are running on.  I don't think we should be trying to create a single path implementation that is diluted to permit the intersection of platform behaviors.  If Windows doesn't allow something it's ok for the Path API to prevent that rather than letting it hit win32.  If Unix allows that, it's ok for the implementation to be different.
In the case of the colon there is another wrinkle in that it is used to specify NTFS alternate streams. Some of the IO APIs explicitly try to block this.  Not sure if that is completely relevant here, but it'd be something that we'd have to look into if we made a change on Windows.

**Comment by JeremyKuhne** [comment]
I agree with @ericstj.

I would add that we're not terribly great at determining/handling "rooted paths" and should probably take a pass for correctness/consistency with this- if nothing more than to fully document corner cases. (For example "C:\foo" is not the same thing as "C:foo"- the second is relative to the current working directory on "C:")

**Comment by stephentoub** [comment]
> I think quirking it on desktop would be reasonable if the behavior is wrong on Windows and needs to be fixed.

We already plan to use the Path.cs implementation in corefx (with fixes), rather than using the one in mscorlib.  If we're ok with different behavior for a bug fix like this between what's in System.Runtime.Extensions.dll and in mscorlib, than we could just make the change for the .NET Core version and not have to worry about quirking it in mscorlib.

I plan to take a look at enabling the Path.cs in corefx soon.

**Comment by JeremyKuhne** [comment]
This now behaves as it should. We only consider colons as drive separators on Windows if they have a valid drive letter [A-Z,a-z].

``` C#
            // Now "bar\\baz\\file:name.exe"
            string combine = Path.Combine("bar", "baz", "file:name.exe");
            // Now "file:name.exe"
            string fileName = Path.GetFileName(combine);
```

Note that the Path code is in CoreCLR to ensure that we keep the implementation consistent. Tests are in CoreFX and that is where we track work as Path is surfaced in the CoreFX reference libraries.
