### ISSUE TITLE
[Arm64/Unix] Crossgen triggering LSRA assert 'farthestRefPhysRegRecord != nullptr'

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#11141]
On version c111a57, It is affecting these files during crossgen

```
Microsoft.VisualBasic.dll
System.Private.Xml.dll
```

System.Private.Xml.dll
```
Assertion failed 'farthestRefPhysRegRecord != nullptr' in 'System.Xml.Xsl.IlGen.XmlILOptimizerVisitor:FoldArithmetic(int,ref,ref):ref:this' (IL size 792)

    File: /home/vmjenkins/workspace/Dotnet/build_and_test/src/jit/lsra.cpp Line: 5928
    Image: /home/vmjenkins/workspace/Dotnet/build_and_test/bin/tests/pr1/Tests/coreoverlay/crossgen
```

Microsoft.VisualBasic.dll
```
Assert failure(PID 9690 [0x000025da], Thread: 9690 [0x25da]): Assertion failed 'farthestRefPhysRegRecord != nullptr' in 'Microsoft.VisualBasic.CompilerServices.Utils:CopyArray(ref,ref):ref' (IL size 232)

    File: /home/vmjenkins/workspace/Dotnet/build_and_test/src/jit/lsra.cpp Line: 5928
    Image: /home/vmjenkins/workspace/Dotnet/build_and_test/bin/tests/pr1/Tests/coreoverlay/crossgen
```

**Comment by sdmaclea** [comment]
@pgavlin Noted that this is a different issue than #10622

**Comment by sdmaclea** [comment]
Here is the ngendump from Microsoft.VisualBasic.CompilerServices.Utils:CopyArray.
[Microsoft.VisualBasic.ngen.dump.zip](https://github.com/dotnet/coreclr/files/953077/Microsoft.VisualBasic.ngen.dump.zip)

I am not an expert, but the register allocation looks wide open.  When running in the debugger the failing node appeared to be asking for X8 which appears wide open.  

@pgavlin @CarolEidt PTAL since you have been looking at the similar issue.  Let me know if I can provide any additional help.

**Comment by CarolEidt** [comment]
I'm looking into this. Just from looking at the dump, I see an issue with the following node:
```
N399 (  9,  8) [000187] ---X---------             *  *_ovfl    int    REG NA $117
```
Its parent (consuming) node wants the result in x3. This node (the multiply) requires an internal register that is distinct from its target. This is indicated by setting the `isInternalRegDelayFree` field on the `gtLsraInfo`. However, this is not working correctly because it has allocated x3 to the internal register, even though that is the required register for the result.
I'll look further into why this is happening.

**Comment by CarolEidt** [comment]
@sdmaclea can you help me figure out how to repro this? I've never crossgen'd anything other than System.Private.CoreLib and I'm not sure that I am 1) using the correct Microsoft.VisualBasic.dll or 2) getting the dependencies right.
It's failing with:
```
Error: Could not load file or assembly 'System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. (Exception from HRESULT: 0x80070002 (COR_E_FILENOTFOUND))
```

**Comment by BruceForstall** [comment]
Is this a recent regression?

> This node (the multiply) requires an internal register that is distinct from its target. This is indicated by setting the isInternalRegDelayFree field on the gtLsraInfo. However, this is not working correctly because it has allocated x3 to the internal register, even though that is the required register for the result.

Note that I recently changed arm64/arm32 to use isInternalRegDelayFree for overflow multiply, whereas previously it allocated 2 temps and used whichever was not the target register, if any. See https://github.com/dotnet/coreclr/pull/11025.

**Comment by sdmaclea** [comment]
@BruceForstall Yes this is a recent regression.  In the last week or so.

**Comment by CarolEidt** [comment]
@sdmaclea @dotnet/jit-contrib - I would like to work on this, but can't figure out how to repro it. Could someone clue me in?

**Comment by BruceForstall** [comment]
@CarolEidt One way: on Windows, build x64, then set:
```
complus_altjitname=protononjit.dll
complus_altjitngen=Microsoft.VisualBasic.CompilerServices.Utils:CopyArray(ref,ref):ref
complus_ngendump=*
complus_ngendisasm=*
```
then run:
```
E:\gh\coreclr2\bin\tests\Windows_NT.x64.Debug\Tests\Core_Root>.\crossgen.exe /Platform_Assemblies_Paths E:\gh\coreclr2\bin\tests\Windows_NT.x64.Debug\Tests\Core_Root Microsoft.VisualBasic.dll
```
(with appropriate paths and current directory)

**Comment by CarolEidt** [comment]
@BruceForstall - Thanks! (Double thanks, as I believe you're the one that enabled the protononjit!)

**Comment by sdmaclea** [comment]
@CarolEidt Sorry  I was not in my office when I replied the first time and could not remember the syntax.  Bruce's answer is probably best for you

I ran 
```
export COMPlus_NgenDump=Microsoft.VisualBasic.CompilerServices.Utils:CopyArray
~/overlay.stable.debug/crossgen /Platform_Assemblies_Paths $HOME/overlay.stable.debug ~/overlay.stable.debug/Microsoft.VisualBasic.dll
```

**Comment by CarolEidt** [comment]
I believe that I understand the problem, and am working on a fix. The issue is that the `RefTypeFixedReg` `RefPosition` for the r3 target on the multiply is only set at the use, not the def. This means that, when the `RefPosition` with the `isInternalRegDelayFree` property is looking at the next time the register has a fixed reference, it thinks it is free at the time the multiply is defined. This is because the reconciling of the def/use requirements on tree nodes is done after the def `RefPosition` has been created, at which point LSRA has already decided it doesn't require an associated `RefTypeFixedReg` at the def location.
