### ISSUE TITLE
Deal with Shutdown issues for EventSource on CoreCLR 

### ISSUE THREAD

**Issue by vancem** [dotnet/coreclr#11404]
The CLR has a general problem with callbacks from managed code on shutdown.   The issue is that when the CLR shuts down it tears down EE structures needed to run managed code but it does NOT necessarily call the destructors of managed objects.  

This is a problem if you have a native callback (that can happen at any time) because that native code could call that callaback during shutdown when it is illegal to call managed code.

The short term solution is to use the 

                   AppDomain.CurrentDomain.ProcessExit += DisposeOnShutdown;
                    AppDomain.CurrentDomain.DomainUnload += DisposeOnShutdown;

APIs to insure that these callbacks are shut down before CLR shutdown happens.   This was done on the Desktop framework but (I think because these events did not exist in Core 1.0 it was pulled from .NET Core.   These APIs I believe are back, so we can do this.   This issue is a reminder to do this.

The DisposeOnShutdown method is already present in EventSource, so pretty much you just need to put the APIs above back in.

-----------

As extra credit, we should consider fixing this in a generic way (this problem is a 'gotcha' that can occur in most uses of native->managed callbacks.   Ideally it is fixed in a generic way.

**Comment by jkotas** [comment]
> the native code is throwing exception (for some reason) before even reaching the code calling back the managed side

Yes, you are right that it looks like to be the case looking at stacktrace in detail. The exception is most likely thrown because of the process is shutting down and the runtime rejects callbacks. It is same problem as that Vance described here: https://github.com/dotnet/coreclr/issues/11404#issue-226404085. It would be nice to solve it generically. cc @janvorli 

However, there is another possible problem here: if the managed callback throws exception, nothing will catch and it will hit the unmanaged code. It will hit the unmanaged code and we will fail fast because of there is no exception interop on Unix. We may want to protect the callback with try/catch similar to how it is done for the callbacks on Windows. 

> Also is there anyway we know what exception is thrown here and why?

We do not have good logging for fail fasts right now. Tracked by
https://github.com/dotnet/coreclr/issues/11114
