### ISSUE TITLE
Notifying Windows of stack frames for kernel stackwalk is enabled only after verbose etw event logging is enabled

### ISSUE THREAD

**Issue by mjsabby** [dotnet/coreclr#11402]
The runtime does not notify the OS via RtlAddGrowableFunctionTable about the jitted code stack frames until we have at least turned on the verbose events for methods.

The current workaround we use is to turn on verbose events and then turn them off. This fixes it for the duration of the process since a static variable controls this.

The fix I would prefer is to completely remove this and always send information to the OS, but I'd be fine with if we make the setting just not be verbose to minimize the risk.

Also I'd like this ported to the Desktop runtime.

**Comment by mjsabby** [comment]
@vancem

**Comment by vancem** [comment]
This has been fixed with PR #11257.   

Please open a bug in (https://devdiv.visualstudio.com/DevDiv/_workitems) and assign it to @brianrob  to have it ported to desktop.    You should use the NET vNext release and the 'NET 4.7.1' the target.  (you can use [bug 428951](https://devdiv.visualstudio.com/DevDiv/_workitems?id=428951&_a=edit) as a template). 





 Bug 428951 Make EventSource Activity Tracking work with EventListeners on Desktop runtime
