### ISSUE TITLE
crossgen crashes / core dumps in most corefx Unix CI legs

### ISSUE THREAD

**Issue by stephentoub** [dotnet/coreclr#11438]
In pretty much all of the legs, I see errors like this (though the legs still pass):
```
Tools/crossgen.sh: line 55:  2953 Bus error               (core dumped) $__crossgen /Platform_Assemblies_Paths $__sharedFxDir:$__toolsDir /nologo /MissingDependenciesOK /ReadyToRun $__file > /dev/null
Unable to successfully compile /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_rhel7.2_debug/Tools/Microsoft.CodeAnalysis.VisualBasic.dll
/mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_rhel7.2_debug/Tools/System.Private.CoreLib.dll -> /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_rhel7.2_debug/Tools/System.Private.CoreLib.ni.dll
Tools/crossgen.sh: line 55:  2943 Bus error               (core dumped) $__crossgen /Platform_Assemblies_Paths $__sharedFxDir:$__toolsDir /nologo /MissingDependenciesOK /ReadyToRun $__file > /dev/null
Unable to successfully compile /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_netcoreapp_rhel7.2_debug/Tools/Microsoft.CodeAnalysis.CSharp.dll
```
Is this expected?  Even if a failure is expected, seems like there should be a better failure mode than a bus error.

e.g.
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_rhel7.2_debug/38/consoleText
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_centos7.1_debug/38/consoleText
https://ci.dot.net/job/dotnet_corefx/job/master/job/debian8.4_debug/2299/consoleText
https://ci.dot.net/job/dotnet_corefx/job/master/job/opensuse42.1_debug/2345/consoleText
https://ci.dot.net/job/dotnet_corefx/job/master/job/ubuntu14.04_debug/2618/consoleText

**Comment by ellismg** [comment]
One thing to note (not sure if it matters) is that these crossgen commands are running in parallel and from the log it looks like there are cases where we are crossgening System.Private.CoreLib.dll into System.Private.CoreLib.ni.dll (likely an issue in itself, because the NI should already be there) while crossgenning other stuff, and maybe that causes an issues with concurrent crossgens.

**Comment by weshaggard** [comment]
@gkhanna79 any idea what a bus error is in context of crossgen? 

Also it looks like we may need to filter out System.Private.CoreLib.dll after the rename

**Comment by gkhanna79** [comment]
@janvorli may know about bus error. And yes, given that SPC.dll now represents the NI renamed, it should not be recompiled.

**Comment by gkhanna79** [comment]
CC @wtgodbe

**Comment by janvorli** [comment]
I've found these details on what can cause a SIGBUS on x64 on stackoverflow:
http://stackoverflow.com/questions/35010654/when-does-memory-load-cause-bus-error-on-x86-64-linux.
Since we have recently modified code around loading of crossgen-ed binaries, I guess it could be one of these:
* exec of non-exec mapping
* access to mmaped file where the file contents doesn't exist (past the end of the file or a hole).
* access to mmaped file where the file contents should exist, but doesn't (I/O errors).

**Comment by gkhanna79** [comment]
Where does this crossgen script live and is anyone looking into it? We have crossgen runs in Helix and Core-Setup does R2R compile of SharedFX and they do not exhibit this issue.

**Comment by weshaggard** [comment]
>Where does this crossgen script live and is anyone looking into it

The script lives in buildtools (https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/PackageFiles/crossgen.sh) but is ran as part of init-tools in corefx (https://github.com/dotnet/corefx/blob/master/init-tools.sh#L110).

I'm not aware of anyone looking into it.

**Comment by gkhanna79** [comment]
@wtgodbe Can you take a look at this?

**Comment by gkhanna79** [comment]
@ellismg Is fixing crossgen.sh something you can help with since @wtgodbe is heads down with other engineering fixes for CoreCLR?

**Comment by gkhanna79** [comment]
CC @chcosta incase he can help fix this as well.

**Comment by ellismg** [comment]
> @ellismg Is fixing crossgen.sh something you can help with since @wtgodbe is heads down with other engineering fixes for CoreCLR?

I can try to find cycles to fix up my PR in buildtools to handle the additional cases, but I won't be able to proactively push another update of buildtools everywhere (which is to say, I'd rather just wait until we think buildtools is "done" and then move everyone forward).

FWIW, I don't believe this represents a product problem, so if it was not fixed in 2.0 it would not be the ned of the world.

**Comment by gkhanna79** [comment]
Is the fix for this in BuildTools? If so, can we get it fixed there so that when the final build is identified, it comes through?

**Comment by ellismg** [comment]
> Is the fix for this in BuildTools? If so, can we get it fixed there so that when the final build is identified, it comes through?

Yes.  Yes.

**Comment by danmosemsft** [comment]
Is this the same issue? (No "bus error"). This is what they typically look like to me.
```
Tools/crossgen.sh: line 54:   890 Segmentation fault      (core dumped) $__crossgen /Platform_Assemblies_Paths $__sharedFxDir:$__toolsDir /nologo /MissingDependenciesOK /ReadyToRun $__file > /dev/null
```
eg https://ci.dot.net/job/dotnet_corefx/job/master/job/ubuntu14.04_arm_cross_release_prtest/3153/consoleFull#-16758747638101fac1-935e-4556-95f9-7a0e25ca0b52

Can someone suggest what the issue is, for my education?

**Comment by RussKeldorph** [comment]
Does this still happen?

**Comment by RussKeldorph** [comment]
I looked through some of the above listed corefx jobs and couldn't find "Bus error" or "Segmentation fault" so I'm going to close.  If I'm wrong, please just reopen and we will investigate.
