### ISSUE TITLE
EqualityComparer<T>.Default  property should use beforefieldinited  field

### ISSUE THREAD

**Issue by omariom** [dotnet/coreclr#1157]
I have two questions  on  [EqualityComparer<T>.Default ](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Collections/Generic/EqualityComparer.cs#L25) 
1. Why is it stored in a volatile field?
2. Why  isn't the field  beforefieldinit'ialized?

Volatile fields are fast but they lose ability to be optimized by the compiler and JIT. Furthermore on ARM platform each reading and writing of a volatile field still incurs full memory barrier.

Currently  the property body is fully inlined into call sites. Not beforefieldinited means fatter loops, more branches to predict, etc.

Compare how EACH call site looks now:
```ASM
 mov         rdi,126357A8h                                  
 mov         rdi,qword ptr [rdi]  

 test        rdi,rdi  
 jne         000007FE962C088C  
 call        000007FEF46CE780  
 mov         rdi,rax  
 mov         rdx,rdi  
 mov         rcx,126357A8h  
 call        JIT_WriteBarrier (07FEF58E12B0h)  
```

to how it would look if it  were beforefiledinited:

```ASM
 mov         rcx,121E5780h  
 mov         rcx,qword ptr [rcx] 
```

I suggest the following:
```C#
private static readonly EqualityComparer<T> defaultComparer = CreateComparer(); 

public static EqualityComparer<T> Default { return defaultComparer ; } 
```

**Comment by sharwell** [comment]
Here's what I would use:

```csharp
static EqualityComparer<T> defaultComparer;

public static EqualityComparer<T> Default
{
  get
  {
    EqualityComparer<T> comparer = defaultComparer;
    if (comparer == null)
    {
      comparer = CreateComparer();
      comparer = Interlocked.CompareExchange(ref defaultComparer, comparer, null) ?? comparer;
    }

    return comparer;
  }
}
```

**Comment by omariom** [comment]
Hmm..  but beforefieldinit already guarantees that every thread will see the same instance.

**Comment by sharwell** [comment]
@omariom I tried to clarify in an edit. My code addresses two of the outstanding concerns of the original code (volatile read and the unexpected concurrency behavior) while otherwise retaining the exact same lazy initialization semantics. Your code is even better for the JIT, but if there is some reason why it won't work then mine would provide an alternative.

**Comment by omariom** [comment]
> but if there is some reason why it won't work then mine would provide an alternative
:+1:

**Comment by steveharter** [comment]
The most straightforward implementation is the one mentioned by omariom (static field initializer without volatile) as it avoids any lower-level synchronization calls.

Using the Lazy<T> pattern (which doesn't use volatile) would also be an improvement in performance over the existing code, especially on ARM. The advantage of Lazy<T> over static field initializer is that it supports lazy semantics (create object on first read) but since the overhead of creating an EqualityComparer is low I prefer the static field initializer option.

**Comment by omariom** [comment]
[Look at this] (https://github.com/dotnet/roslyn/blob/54b0912b7cb3f5b68dd6d562a1930af53b6d41d0/docs/features/ValueTuples.cs#L144).  It is `ValueTuple` struct from `tuples` branch of Roslyn.
If `EqualityComparer.Default` were a simple property wrapping a field `ValueTuple` wouldn't need to declare a separate static field.
Furthermore, if  [static dispatch for static readonly fields](https://github.com/dotnet/coreclr/issues/4108) is implemented it would greatly increase perf in every place where default equality comparers are used.
