### ISSUE TITLE
Finally block not called on unhandled exception on Linux

### ISSUE THREAD

**Issue by nickwalkmsft** [dotnet/coreclr#11695]
See http://stackoverflow.com/questions/44032931/net-core-unhandled-exception-in-using-does-not-call-dispose-on-linux

On Linux, finally{} blocks do not appear to be executed on exceptions that go completely uncaught. On Windows, the finally{} runs, but not for ~20 seconds after the exception text is written to the console.

**Comment by janvorli** [comment]
@nickwalkmsft this is an expected behavior. On Windows, it really depends on how you have Watson set up. You can get the same behavior as on Linux there as well.
If you care about finallys being run in case of unhandled exception, you can always add try / catch at the topmost level of your app / thread to ensure that.

**Comment by nickwalkmsft** [comment]
Interesting, thanks!
