### ISSUE TITLE
EventPipe: new data request

### ISSUE THREAD

**Issue by northtyphoon** [dotnet/coreclr#11725]
The following data is collected in ETW. They are useful diagnostics information. 

1. Process id
2. Process name
3. OS arch (x64 vs x86)
4. OS version
5. CPU frequency
6. Number of processors

**Comment by vancem** [comment]
Also add  the list of 'easy' things that should be in the file 

1. Machine name
2. PointerSize (e.g. 4 or 8 bytes).   
3. Expected CPU sampling rate. 
4. UTC offset (Time Zone).
5. Session Start time (all times should be FileTime (UTC)).

**Comment by brianrob** [comment]
Moving this to 2.1.  @adamsitnik, are you handling this in your current work on EventPipe?

**Comment by adamsitnik** [comment]
@brianrob yes, I do

**Comment by brianrob** [comment]
@adamsitnik, great, thanks.

**Comment by adamsitnik** [comment]
In #16107 I took the opportunity and with V3 of Event Pipe file added all the things that were available in PAL.

What was added:

- Process id
- Pointer size / OS arch (x64 vs x86)
- CPU frequency
- Number of processors
- Expected CPU sampling rate.

What is missing:

- Process name
- OS version
- Machine name
- UTC offset (Time Zone).

What was already there:
- Session Start time (all times should be FileTime (UTC)). [code](https://github.com/dotnet/coreclr/blob/f6ba335278bb966e8e5f9cd33f51818c6fac44fa/src/vm/eventpipefile.cpp#L40)

Question: do we need this data and the issue should remain opened or should I close it?

@vancem @brianrob

**Comment by vancem** [comment]
I could live without UTC offset or even OS version and Machine name, but I would like ProcessName unless it is really problematic, and it seems like MachineName is also handy.     Why are those hard?

I think it would also be pretty handy to have Runtime Version number (we have needed this and often did not have it with ETW).    That should also be easy (since it is a burned in constant.

**Comment by vancem** [comment]
I just thought of something else that is pretty useful: the command line arguments to the process (if available).

**Comment by adamsitnik** [comment]
> Why are those hard?

I was supposed to add `pointer size` only but decided to also add everything that was available in PAL. I just don't know if they are hard to implement or not (I lack the knowledge to tell).

**Comment by brianrob** [comment]
OS version will be difficult for Linux - we could potentially get kernel version, but beyond that how you detect the version is distro specific.  If it is easy to get kernel version I think that could be useful.

Command line args are worth looking at, but I don't believe that they are currently available anywhere but Windows.  I think the PAL isn't able to get them from process state because they aren't passed up from the host, but perhaps this could be changed by pulling them in from procfs.

**Comment by danmosemsft** [comment]
Kernel version is something like `uname -srv`...the uname API reforms the same value. It would take some parsing to get a number, and you may want the build date anyway.

**Comment by vancem** [comment]
We should do the easy ones.    I would have expected the command line args to be easy because Environment.CommandLine already exists, so we had to plumb it through somehow. 

ProcessName is very useful because without it is seriously hard to determine by just looking at a trace what it is a trace of.   (That is also why Command Line Args are useful).

**Comment by brianrob** [comment]
@adamsitnik is this something that you can finish up?  Thanks.

**Comment by adamsitnik** [comment]
@brianrob Currently not. I am working on the serializers/real-world web app benchmarks. Btw could you review #16316?
