### ISSUE TITLE
System.Text.StringBuilder is missing object.Equals(object) override

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/coreclr#11763]
Applies to both netfx and corefx.
Netfx: https://referencesource.microsoft.com/#mscorlib/system/text/stringbuilder.cs,1490
Core: https://github.com/dotnet/coreclr/blob/master/src/mscorlib/shared/System/Text/StringBuilder.cs#L1756

It is also not implementing `IEquatable<StringBuilder>` BUT containing its implementation: https://msdn.microsoft.com/en-us/library/ccth01t4(v=vs.110).aspx

Is this by design?

## Repro
```csharp
var a = new StringBuilder();
var b = new StringBuilder();

Console.WriteLine(Object.Equals(a, b)); // False
Console.WriteLine(a.Equals(b)); // True
```

cc @danmosemsft

**Comment by ViktorHofer** [comment]
cc @stephentoub

**Comment by stephentoub** [comment]
@vancem would know if it's by design.

**Comment by vancem** [comment]
Semantically it is reasonable for  StringBuilder.Equals(object), to do the 'standard' thing and try to cast its argument to StringBuilder and call StringBuilder.Equals(StringBuilder).    It is also reasonable for it to implement IEquatable<StringBuilder> (since it implements its functionality).  

Having said this, the value of these new things is basically to have a table with a 'Key' which is a StringBuilder.   This would be a decidedly unusual thing to do because the value of a StringBuilder is that it can be mutated in place, but that is exactly what you would NOT want for a table.   Moreover a StringBuilder's equality requires that the Capacity and MaxCapacity be the same, which seems like a pointless semantics to have (it is not just the value of the string within the StringBuilder).     I suspect it was done this way because it was useful for testing (which may be the only value for StringBuilder.Equals.  

If we had it to do over again, I would define Equals to be just the string value (but that is a breaking change), and I would override Object.Equals and implement IEquatable<T>.

I would not push back on overriding Object.Equals and implementing IEquatable<StringBuilder> (but I also don't think it adds much value (mostly it just adds consistency).

**Comment by ViIvanov** [comment]
Since `StringBuilder` is not immutable, implementing comparison via overriding `GetHashCode` (and `Equals`) in it is not a good idea.

May be, the better way is providing specialized `IEqualityComparer<StringBuilder>` and `IComparer<StringBuilder>` (why not?), that can be implemented internally in `StringBuilder` as nested types for access a private implementation details:

```cs
sealed class StringBuilder
{
  public static IEqualityComparer<StringBuilder> EqualityComparer { get; } = new StringBuilderEqualityComparer();
  public static IComparer<StringBuilder> Comparer { get; } = new StringBuilderComparer();

  // Types of properties above can by EqualityComparer<StringBuilder> and Comparer<StringBuilder>

  private sealed class StringBuilderEqualityComparer : EqualityComparer<Stringbuilder>
  {
    // …
  }

  private sealed class StringBuilderComparer : Comparer<Stringbuilder>
  {
    // …
  }
}
```

**Comment by vancem** [comment]
We should be doing as little as possible here.    The default answer really should be 'do nothing (close the issue).   I don't believe there is an actual user scenario here (that is someone needs Stringbuilder equality, it is just that @ViktorHofer  noticed that we don't follow standard pattern.   This is a worthy discussion, but now we have had it, and I that might be all we need to do.  

Personally I think we should just close the issue until such time as someone has a real user-scenario.

**Comment by ViktorHofer** [comment]
I agree!
