### ISSUE TITLE
Include opcode in EventPipe/EventSource metadata

### ISSUE THREAD

**Issue by northtyphoon** [dotnet/coreclr#11934]
Is it possible to include opcode in the metadata? The opcode is useful to track EventSource Activity.

https://github.com/dotnet/coreclr/blob/master/src/mscorlib/shared/System/Diagnostics/Tracing/EventSource.cs#L708

@brianrob @vancem 

#11725 

Another suggestion for metadata blob. The metadata blob is included in EventPipeEvent payload which is serialized by FastSerializer. So it's better to use the same format as FastSerializer in the metadata blob. For example, the string field should have a pre-appended length field.

**Comment by brianrob** [comment]
Per conversation with @northtyphoon, marking this as future.

**Comment by northtyphoon** [comment]
A small suggestion, it will be helpful to put a version field on the top the metadata blob. So the parser can support different schema. If the plan is just using EventPipe.Version, it probably also works.

**Comment by vancem** [comment]
I would like to close this issue.     There were two suggestions

1. Include opcode in the meta-data 
2. Use a length prefixed string instead of a null terminated string when encoding strings.

I would like to keep both the way they are.    First not including opcode:  First, it is rather painful change because the definition of an event changes, and this 'leaks' out in reasonably far (it can probably be done, but we have to ask ourselves what the value is.  

Opcode actually CAN have negative value because it is CONFUSING, and no other logging system supports the concept.   Instead they use naming conventions (Start and Stop).    We should be strongly biased toward this simplicity until we really get in a jamb.  I think we are not there yet (but who know maybe we will be).   In short, there are enough negatives that we should wait.

On the issue of length prefixed strings.  Again this comes back to an issue of the fact that these meta-data descriptions are public (perhaps more public than FastSerialization), and so asking them to change is painful at best and problematic (because we want to work well with ETW which uses this format, and our event data format for strings is also null terminated uncode).   It makes more sense to fix FastSerialziation to allow for these strings than it does to conform to FastSerialization convetions. (I have added this to the library).
