### ISSUE TITLE
About Unsupported gcConservative mode

### ISSUE THREAD

**Issue by xoofx** [dotnet/coreclr#11969]
Hi,

This is a question about the runtime knobs that are prefixed by `Unsupported`.

For prototyping Unity running on CoreCLR last week, I have used the conservative mode to be able to get on board more easily. This is mostly a workaround on our side, as we will have to update quite a large code base to support correct cooperative/preemptive transitions... but in the meantime, this mode could help in the transition (this is what is used currently with Mono in Unity)

So specifically, for [`gcConservative`](https://github.com/dotnet/coreclr/blob/dd4d0dad2cb9485518056cab7ec75949db082805/src/inc/clrconfigvalues.h#L306) mode, which is tagged as `Unsupported`, but among the following level of support, where does it fit roughly?

1) We don't try to maintain it, if it is broken, it is broken, we won't fix it (likely to be deprecated, and then removed)
2) We try to maintain it, but we cannot guarantee that it will work for all situations, and if there is a bug, we will be glad to help but you will have to fix it so we won't provide strong support for it
3) We maintain it, it is used internally, but we don't provide an official support for it

I have the feeling that it is between 2) and 3). Could you confirm or infirm?

Thanks!

cc: @Maoni0, @jkotas

**Comment by jkotas** [comment]
I am aware of these issues:
- It does not work for dynamic methods or collectible types. The conservative stack walking does not root these correctly. 
- People sometimes write code (tests in particular) that assumes precise GC reporting. The conservative reporting breaks it.
- It adds measurable steady state overhead because of the root tracking is slower and there are false survivors.

We use it internally to bring up new platforms, but it has never been a shipping or supported config.

**Comment by Maoni0** [comment]
as @jkotas mentioned we internally mostly just use it to bring up new platforms before folks could report preciously. we really try to keep the usage down due to the perf problems Jan mentioned and that conservative roots are reported as pinned. we've spent a lot of time to work on reducing pinning problems and conservative reporting is directly working against that.

**Comment by xoofx** [comment]
Thanks for the feedback!

For the perf problem and pinning issue, I don't have much concern as these side effects are usually expected for a conservative GC scan (even though, on x64, I would expect a lot less pinning issue than x86...)

Mostly wanted to know that this conservative mode will be kept around and would not disappear in the coming 1-2 years, the time that could require for us to switch entirely to CoreCLR with correct handling of GC stack roots... but we could work in this transition time with this conservative stack solution...

**Comment by sdmaclea** [comment]
@Maoni0 I also just noticed it also does not work with gcServer=1.  It is triggering asserts.

In `gc_heap::find_object()` it triggers this assert
```
assert (interior < heap_segment_allocated (seg));
```

**Comment by Maoni0** [comment]
Thanks @sdmaclea. I will keep that in mind. Are you seeing this on arm64?

**Comment by sdmaclea** [comment]
@Maoni0  Yes, I see it on arm64.  I was going to open a defect, but when I saw this I decided it was not necessary.
