### ISSUE TITLE
Assertion in jit LSRA

### ISSUE THREAD

**Issue by erozenfeld** [dotnet/coreclr#12037]
Compile Program.cs below:

.\Tools\dotnetcli\dotnet.exe Tools\csc.exe /o+ out:Program.exe Program.cs /r:.\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\System.Private.CoreLib.dll /r:.\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\System.Console.dll /r:.\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\System.Runtime.dll

```
using System;
using System.Diagnostics;
using System.Runtime.CompilerServices;

namespace omg
{
    public class TestRyujitBug
    {
        public static void Main()
        {
            TopFunction(new object(), 0L, 0xBEEF, new TypedDouble(1.0), new TypedDouble(2.0), new TypedDouble(3.0), false, true);
        }

        public static void TopFunction(object parameters, long? nullable,
            double doubleArg, TypedDouble typedDouble1, TypedDouble typedDouble2, TypedDouble typedDouble3, bool shortCircuit, bool toggle)
        {
            if (shortCircuit)
            {
                return;
            }
            double param = toggle ? 19.0 : 17.0;

            InlinedFunction(doubleArg, param, typedDouble1.Value, typedDouble2.Value, typedDouble3.Value);
        }

        public static void InlinedFunction(double doubleArg, double param, double typedDoubleArg1, double typedDoubleArg2, double typedDoubleArg3)
        {
            Console.WriteLine("{0} {1} {2} {3} {4}", doubleArg, param, typedDoubleArg1, typedDoubleArg2, typedDoubleArg3);
        }

        public struct TypedDouble
        {
            public TypedDouble(double value)
            {
                Value = value;
            }
            public readonly double Value;
        }
    }
}
```
The run the resulting program:

.\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\CoreRun.exe Program.exe

Assert failure(PID 8592 [0x00002190], Thread: 11128 [0x2b78]): Assertion failed '!interval->isLocalVar' in 'omg.TestRyujitBug:TopFunction(ref,struct,double,struct,struct,struct,bool,bool)' (IL size 58)

    File: c:\coreclr\src\jit\lsra.cpp Line: 531
    Image: c:\coreclr\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\CoreRun.exe

Running with release coreclr results in silent bad codegen. The output is 

`48879 19 1 48879 3`
instead of
`48879 19 1 2 3`

**Comment by erozenfeld** [comment]
@dotnet/jit-contrib

**Comment by CarolEidt** [comment]
I presume it’s hitting that assert in LinearScan::resolveConflictingDefAndUse(). That’s kind of a tricky situation – where the def and use don’t agree on the requirements.

The `hasConflictingDefUse` flag is presumably being set on the `Interval` in `LinearScan::buildRefPositionsForNode()` near line 3976:
```
            i->hasConflictingDefUse = true;
```
I suspect that there should be an assert here that the use is not a lclVar interval (rather than delaying until the call above). And it shouldn’t be because locals should either be always accessed as the same type, OR they should be marked as `lvDoNotEnregister`. So the question would be why that’s not happening here.
