### ISSUE TITLE
'index.m_dwIndex != 0' assert failure on GCStress=3

### ISSUE THREAD

**Issue by parjong** [dotnet/coreclr#12075]
CLR hits this assert failure even for simple "Hello, World" application. Both x86 and x64 CLR hit the same assert failure:
```
Assert failure(PID 149 [0x00000095], Thread: 149 [0x0095]): index.m_dwIndex != 0
    File: /home2/parjong/projects/dotnet/coreclr/src/vm/object.cpp Line: 866
    Image: /home2/parjong/projects/dotnet/dotnet-overlay/Linux.x86.Debug.Debug/corerun
```
```
Assert failure(PID 2069 [0x00000815], Thread: 2069 [0x0815]): index.m_dwIndex != 0
    File: /home2/parjong/projects/dotnet/coreclr/src/vm/object.cpp Line: 866
    Image: /home2/parjong/projects/dotnet/dotnet-overlay/Linux.x64.Debug.Debug/corerun
```

**Comment by parjong** [comment]
08344258134  seems to cause this issue.

**Comment by janvorli** [comment]
cc: @swgillespie

**Comment by swgillespie** [comment]
Taking a look today.

**Comment by swgillespie** [comment]
cc @jkotas @Maoni0 

This crash is because the config option `AppDomainLeaks` is set when using GCStress on debug builds (https://github.com/dotnet/coreclr/blob/master/src/vm/eeconfig.cpp#L783-L784). As a part of https://github.com/dotnet/coreclr/pull/11379 I removed some code in the GC for `AppDomainLeaks` under the assumption that it was dead code and not used, but apparently *is* used here.

Per Jan's comment on #11379 it sounds like `AppDomainsLeaks` is expensive and not useful. To fix this issue in the short term, I can back out of the changes to the GC that removed code that enabled `AppDomainLeaks`, though it sounds like we might also want to consider removing the configuration option outright from the entire codebase.

**Comment by jkotas** [comment]
> To fix this issue in the short term

You can just make `AppDomainLeaks()` to return false unconditionally as a quick fix.

> we might also want to consider removing the configuration option outright from the entire codebase.

Agree.
