### ISSUE TITLE
Spin Count in GC

### ISSUE THREAD

**Issue by helloguo** [dotnet/coreclr#12169]
In gc.cpp, there are a few places using the number of processor to get the spin count. e.g.

```
                int spin_count = 4096 * g_num_processors;
                for (int j = 0; j < spin_count; j++)
                {
                    if (color != join_struct.lock_color)
                    {
                        break;
                    }
                    YieldProcessor();           // indicate to the processor that we are spinning
                }
```

Since the number of processors are not necessarily same as the number of GC threads (e.g. https://github.com/dotnet/coreclr/pull/6104 adds System.GC.HeapCount to specify GC thread counts by config), it makes more sense for me use the number of GC threads to calculate spin count.

Should I fix it?

**Comment by helloguo** [comment]
cc @Maoni0

**Comment by Maoni0** [comment]
That's intentional. There can be threads running on other processors too. We don't assume only GC threads are running.

**Comment by helloguo** [comment]
@Maoni0 `g_num_processors `has different values on Windows v.s. Ubuntu. On my machine (2 sockets, 88 logic cores in total), `g_num_processors  `is 44 for Windows Server 2012 R2 but 88 for Ubuntu 14.04.

**Comment by swgillespie** [comment]
That number should come straight from the PAL: https://github.com/dotnet/coreclr/blob/master/src/vm/gcenv.os.cpp#L687.

**Comment by helloguo** [comment]
Windows and Ubuntu should return same value (88 in this case), right?

**Comment by swgillespie** [comment]
I would think so, yeah; if they aren't that would imply that something has gone awry in PAL's GetSystemInfo: https://github.com/dotnet/coreclr/blob/master/src/pal/src/misc/sysinfo.cpp#L100

**Comment by helloguo** [comment]
PAL works well for Ubuntu, which gives 88. I would suspect Windows `GetSystemInfo` does something unexpected.

**Comment by swgillespie** [comment]
hmm... @janvorli, do you have any thoughts on this?

**Comment by janvorli** [comment]
MSDN doc on the `SYSTEM_INFO::dwNumberOfProcessors` says:
The number of logical processors **in the current group**.  A processor group can have max 64 processors and all processors in the group need to be in the same NUMA node (or maybe a NUMA node cannot span multiple groups, this is not 100% clear to me). That explains why the g_num_processors is 44 - it comes directly from the `SYSTEM_INFO::dwNumberOfProcessors`. On Unix, the NUMA support is still not enabled and tested and so we set this value to `sysconf(_SC_NPROCESSORS_ONLN);`.

**Comment by janvorli** [comment]
@swgillespie, @Maoni0  now the question is whether the g_num_processors when NUMA is enabled on Windows should reflect the number of processors in all groups or still just the number of processors in the current group.

**Comment by swgillespie** [comment]
Ah, makes sense! Thank you @janvorli ! I'll defer to Maoni's judgement on that.

**Comment by helloguo** [comment]
@janvorli Thank you. 
@Maoni0 One more question: in GC, `g_num_processors ` is used in different places. For example, it can be used to handle some memory related stuff. In this case, it makes sense to return the number of all the processors which are available for this process. In other scenario, it is used to decide spin count(e.g `t_join::join()`). Let's just look at `t_join::join()` , which is for GC threads only to join if I understand correctly.  In this case, why don't use the number of GC threads to decide spin count?

**Comment by Maoni0** [comment]
Sorry, I didn't really read your first post carefully. For the spin count in t_join you are right - it should be # of heaps - or actually, I took a look at all the places where we are calculating spin counts and I think we should make it consistent. And the rule I derived is the # we use here should be the # of threads that are waiting to acquire the spin lock (and subsequently wait on an event). Of course if we are running on one proc, we should make sure we are not spinning. So in the t_join case we should use (# of heaps - 1) instead; in gc_thread_function we should change (# of processors - 1) to (# of heaps - 1); but in places like enter_spin_lock it's the user threads that are waiting and it's hard to say how many. Without some perf investigation, I would just leave these alone for now. You are welcome to change all the places that are not questionable like enter_spin_lock (and make a note in comments about why you are not changing some). In reality it really doesn't matter much if we make it (# of heaps - 1) or just (# of heaps) (except in single proc case but I think most of these places are only applicable in Server GC which means we have more than one) but I like the consistency and it makes a clear guideline for later if someone needs to add another spin count.

I would actually love to get rid of the CPU group presence in gc.cpp because CPU group is only an OS concept and only exists in Windows (as you've noticed that # of processors we are getting on Windows only covers the ones in the current CPU group which is not what we want if you have CPU group enabled). We need to care about NUMA because we want to make different perf decisions if it's in the same or remote NUMA node but we really don't care about CPU groups. So it would be great if the GC code was oblivious to it. But that can be done separately, of course.

**Comment by helloguo** [comment]
@Maoni0 Thanks for explanation. I will make the change then.

One more question about ` int spin_count = 4096 * g_num_processors;`. I assume the factor `4096 ` came from some experimental data. Do you happen to know which benchmarks were used? I'm curious about the spin count for a server with a large amount of processors.
