### ISSUE TITLE
[RyuJIT/armel] Support passing double type register args

### ISSUE THREAD

**Issue by wateret** [dotnet/coreclr#12293]
Parent Issue: #11822

`float` type variables were covered by #12005, but we don't have a trivial solution for `double` types. Since that there is no multi-reg support for GT_PUTARG_REG and GT_COPY. I'm going to implement this according to https://github.com/dotnet/coreclr/pull/12005#pullrequestreview-41574710.

**Comment by wateret** [comment]
@CarolEidt 
At https://github.com/dotnet/coreclr/blob/release/2.0.0/src/jit/lsraarmarch.cpp#L393,
putarg_reg does `setSrcCandidates` to its Op1. But `setSrcCandidates` makes more sense to me. Could I ask why it sets src candidates? (I don't think it is wrong since the file is for both ARM/ARM64 and there is the same code for XARCH version though.)

**Comment by CarolEidt** [comment]
> At https://github.com/dotnet/coreclr/blob/release/2.0.0/src/jit/lsraarmarch.cpp#L393,
putarg_reg does setSrcCandidates to its Op1. But setSrcCandidates makes more sense to me. Could I ask why it sets src candidates? (I don't think it is wrong since the file is for both ARM/ARM64 and there is the same code for XARCH version though.)

These names have always been confusing (and I'm afraid I'm to blame), but I don't really have a better idea for naming them. I'm not sure I understand the question, but the reason it's calling `setSrcCandidates` is that the src candidates are the candidates that the register should be in when it is used as a src (i.e. by its parent or consumer). So in this case the consumer is the putarg_reg.  In the time since this code was written, we've often used producer and consumer, so perhaps `setConsumerCandidates` would be better, but I'm not really sure it would be an improvement.
Did I understand the question correctly?

**Comment by wateret** [comment]
@CarolEidt Sorry I was not clear. Even worse, there was a typo :( I edited the previous comment.

Let me give you more details. In CodeGenBringUpTest/FPAdd.cs, The `Main` function calls `FPAdd(1.0, 1.0);`.

```
003 ( 18, 14) [000008] -------------             *  il_offset void   IL offset: 0x0 REG NA
    +<TreeNodeInfo @  3 0=0 0i 0f src=[allInt] int=[allInt] dst=[allInt] I>
N005 (  1,  1) [000001] -------------             *  dconst    float  1.0000000000000000 REG NA $41
    +<TreeNodeInfo @  5 1=0 1i 0f src=[allFloat] int=[allInt] dst=[allFloat] I>
N007 (???,???) [000035] -------------             *  copy      int    REG NA
    +<TreeNodeInfo @  7 1=1 0i 0f src=[r0] int=[allInt] dst=[allInt] I>
N009 (???,???) [000036] -------------             *  putarg_reg int    REG NA
    +<TreeNodeInfo @  9 1=1 0i 0f src=[r0] int=[allInt] dst=[r0] I>
N011 (  1,  1) [000002] -------------             *  dconst    float  1.0000000000000000 REG NA $41
    +<TreeNodeInfo @ 11 1=0 1i 0f src=[allFloat] int=[allInt] dst=[allFloat] I>
N013 (???,???) [000037] -------------             *  copy      int    REG NA
    +<TreeNodeInfo @ 13 1=1 0i 0f src=[r1] int=[allInt] dst=[allInt] I>
N015 (???,???) [000038] -------------             *  putarg_reg int    REG NA
    +<TreeNodeInfo @ 15 1=1 0i 0f src=[r1] int=[allInt] dst=[r1] I>
N017 (  3,  7) [000039] -------------             *  const(h)  int    0xD1FFAB1E ftn REG NA
    +<TreeNodeInfo @ 17 1=0 0i 0f src=[allInt] int=[allInt] dst=[allInt] I>
N019 (  6,  9) [000040] -------------             *  indir     int    REG NA
    +<TreeNodeInfo @ 19 1=1 0i 0f src=[allInt] int=[allInt] dst=[allInt] I>
N021 ( 18, 14) [000003] --C-G--------             *  call      float  BringUpTest.FPAdd $142
    +<TreeNodeInfo @ 21 1=3 0i 0f src=[allFloat] int=[allInt] dst=[f0] I>
```

The N007(copy node)' src is [r0], but what I thought was [r0] should be dst since we are copying from float reg to int reg. Am I getting something wrong here?
