### ISSUE TITLE
CompareInfo.Version is not initialized correctly

### ISSUE THREAD

**Issue by krwq** [dotnet/coreclr#12312]
Currently CompareInfo.Version is showing invalid info (zeros) - this is happening because we don't set `vdwNLSVersionInfoSize` on the `NlsVersionInfoEx` struct as on Desktop: http://referencesource.microsoft.com/#mscorlib/system/globalization/compareinfo.cs,1328

cc: @tarekgh

**Comment by tarekgh** [comment]
@krwq I assume you work on the fix. right?

**Comment by krwq** [comment]
@tarekgh unfortunatelly not currently, need to finish on serialization tests.

**Comment by danmosemsft** [comment]
@tarekgh do you believe this would meet the escrow bar?

**Comment by tarekgh** [comment]
> do you believe this would meet the escrow bar?

Basically CompareInfo.Version is returning wrong version. it is not big deal but the returned value will not reflect the actual version from the OS. I would say it will be good to fix it before the release, otherwise we'll have discrepancy with the desktop and anyone using this Version property for sure will not be happy for the returned value. but to be fair, not many people really using this property.

**Comment by tarekgh** [comment]
@danmosemsft I have submitted a PR dotnet/coreclr#12330 to fix this. I hope we can consider this for v2.0 if possible.

**Comment by danmosemsft** [comment]
@tarekgh As you mention, usage is low in fact we see none at all: https://apisof.net/catalog/System.Globalization.CompareInfo.Version (unless perhaps it's used indirectly somehow?)

However the fix is low risk and it's clearly bad to return random memory so I support taking it to shiproom. I'll let you do the email and PR etc. thanks
