### ISSUE TITLE
Funclet stack frames

### ISSUE THREAD

**Issue by JosephTremoulet** [dotnet/coreclr#1233]
I'm looking at the frame setup code for EH funclets.  I see that the frame that is created upon entry to a funclet is just a small thing that holds callee-saves, the PSPSym, and outgoing args; for all other purposes, funclets use the frame of the main function, and the funclet prolog sequence sets up the frame pointer to point to that main function frame.

This poses a problem for LLILC, because LLVM isn't equipped to handle that kind of frame sharing (in particular, the size of space needed for e.g. register spills in the funclet isn't known when the frame for the main function is finalized).  So on the compiler side, it would be preferable for each funclet to use its own frame for spills and the like (and thus use a normal prolog that sets up the frame pointer to point to that frame); locals would still be homed in the main function's frame, and the funclets would access them indirectly off the PSPSym (and they'd be reported to the GC from the main function, not the funclet(s)).

This raises a few questions:
1) Can the GC tolerate funclets that have their own frames?  From my reading of code/comments, it sounds like I'd definitely want WantsReportOnlyLeaf to be false, but it's not clear to me if that would be enough.  For nested funclets, does !WantsReportOnlyLeaf imply calling back for all funclets, or just the leaf funclet and the main function (skipping over intermediate funclets)?
2) Can the debugger and debug info handle having the frame pointer set to a different address in funclets than it is in the main function?
3) Does anywhere else come to mind that the runtime would assume a shared frame pointer?
4) For things that wouldn't just work, would it require large or small changes to make them work?

**Comment by noahfalk** [comment]
Hi Joseph, sorry for a slow response. I'm afraid I don't have a complete answer for you though I know pieces of it. Likely the best way to get the complete answer is a bunch of code review and testing. Once these invariants get created implicit dependencies tend to drift around the codebase. I suspect making this change would carry non-trivial compat risk if it integrated into the desktop codebase, but I don't know what the latest thinking is on how we handle those issues. I can probably hunt down someone better suited for that part of the discussion if you need me to.

As for what needs to change... in the debugger/profiler space there are a number of places you might need to touch, though no guarantee its exhaustive:
a) ICorDebugNativeFrame2::IsMatchingParentFrame/IsChild - this is the public face of funclets in the debugger API. It says whether a given frame is a funclet for another frame
b) ICorDebugILFrame::GetLocalVariable/EnumerateLocalVariable - in the implementation of this (probably nested a few layers) we need to determine where on the stack locals variables live, which does some calculations based on various stack pointers. The calculation probably would have to change.
c) In various functions inside debug\ee\debugger.cpp and controller.cpp there is some stepping logic that handles what it means to step-in/over/out. This algorithm has to distinguish stepping into funclets vs. stepping into top-level methods because only the latter counts as a step-in from the developer's POV. Also in general stepping in/out use the stack pointer to calculate stack depth where the step operation starts/currently is/finishes. Its been years since I last looked at this code but a good starting point for stepping in general would be Debugger::HandleIPCEvent, look for the cases that handle DB_IPCE_STEP and DB_IPCE_STEP_OUT
d) Debugger is another consumer of stackwalking in general and you could search around for other parts of the debugger code that uses it. In the Debug\EE directory you can search for ControllerStackInfo and FramePointer. In debug\daccess there is also a second implementation of the stackwalker that runs from out-of-process - check out dacdbiimplstackwalk.cpp and stack.cpp.
e) The ICorDebug API exposes register contexts, so its always possible that external tools have taken there own dependencies on the framepointers. I think its unlikely, but its a risk we should consider.
f) The profiler API also exposes frame pointers, via APIs like DoStackSnapshot and GetNotifiedExceptionClauseInfo. Similar to the debugger, profilers could have taken dependencies about the meaning of the frame pointer.

**Comment by JosephTremoulet** [comment]
Thanks for the pointers, Noah.

I'm wondering if there's a middle-ground where funclets still point the frame pointer to the parent frame (that seems to be the most pervasive assumption) and still home locals in the parent frame (that matches their scope anyway), but where funclet-local temps could be spilled to funclet frames (accessed off the stack pointer) and we could free up some of the other cross-frame dependencies.  It seems like any such approach would require changing the interface with the GC, though (is that a non-starter?), to allow reporting per-funclet rather than per-method.  In particular it would be nice if funclets could have GC pointer spilled temps and the slots didn't have to line up, and if the PSPSymbol didn't need to be placed somewhere that forces (on x64) each funclet's frame to have the same amount of outgoing argument space.  I'd naively hope that the result would be a simplification in the GC scanning code, since I think what I'm wanting is for funclet frames to be treated similarly to regular frames there (though the burden of supporting different conventions for different jits might outweigh that?).  I'd also think it would be nice not to require the main/hot path to allocate stack space for presumably-cold funclets.

Thoughts?

**Comment by jkotas** [comment]
> PSPSymbol

What you are describing is close to where we have been going with exception handling for ARM and ARM64, but we have not gotten quite there. 

On the VM side, the PSP is only needed in one place: `EECodeManager::GetExactGenericsToken`. It should be possible to fix this one place to not depend on PSP, e.g. change the code to assume that the generics token offset is encoded against frame pointer if there is no PSP and you are in a funclet. It is the place that the following comment in JIT refers to: https://github.com/dotnet/coreclr/blob/master/src/jit/compiler.h#L1597-L1599

The other piece of the puzzle would be to set the frame pointer to the right value before calling the funclet on the VM side so that the funclet code can find the parent frame without PSP. We are doing it for non-filter funclets on ARM/ARM64 already (we actually restore all non-volatile registers), but not on AMD64. You would need to modify the code that calls funclets on AMD64 to be like what we do on ARM/ARM64 - look for `CallEHFunclet`. For filter funclets, you would also need to add code that figures out the frame pointer to use.

As far as I can tell, these changes are extending the contract between JIT and VM in natural way, so you would not need to explicitly special case them for RyuJIT vs. LLILC.

> same amount of outgoing argument space

I am not aware of anything fundamental in the VM that assumes that all funclets have same amount of the outgoing argument space. It was just a simplification used by the JITs to make PSP work.

**Comment by JosephTremoulet** [comment]
Circling back to this, sorry for the dealy.

I think there are three aspects of this that need to be considered:
 1. Funclets will need to refer to their own dynamic frame and also the root method's frame.  Which ones need to use specific frame pointers?  I think on the one hand we have a variety of tools (including all the ones that @noahfalk pointed out) that grew up on Windows and expect the frame pointer to point to the parent frame, while on the other hand we're porting to platforms that aren't used to funclets and have tools that expect frame chaining and such.  Maybe if we keep the funclet frames empty enough we can always report them as frame-pointer-omitted and reference their frames exclusively off the stack pointer?  This is an interesting point, but I don't expect it to be a blocker for LLILC either way since we ought to be able to implement whichever scheme.  /cc @LLITCHEV and @janvorli as I think you've been working though the implications here for RyuJit on Linux.
 2. The specific way in which the PSPSymbol is reported imposes some restrictions on funclet frames' outgoing call argument areas which will be difficult for LLILC to honor.  @jkotas addressed this one, getting rid of the PSPSymbol sounds like a good change that would eliminate this issue.
 3. The GC info reporting format only allows the JIT to report one stack layout description per MSIL method, not one per funclet.  This again imposes some restrictions that will be awkward to honor in LLILC (though we have a possible workaround, at the cost of some CQ loss in exception handlers, which involves inserting explicit reloads of all GC pointers after safepoints in handlers so that nothing in any funclet frame need be reported to the GC).  I don't think anyone has spoken to this point -- **I'm curious to know if there's wiggle room here and if we can/should be considering adjusting the GC reporting to allow reporting funclet stack frames independently of their parents.**

Thanks.

**Comment by jkotas** [comment]
For #3, you are asking for GC info to have more flexibility than what it has today. I do not think there is anything fundamentally impossible - of course, it is work to make it happen.

The problem in this case may be limited to (GCInfoEncoder)[https://github.com/dotnet/coreclr/blob/master/src/inc/gcinfoencoder.h]. I believe that the GC info encoding and GC info decoder should be flexible enough for this case already.

BTW: https://github.com/dotnet/llilc/issues/781 is very similar problem - it also asks for more GC info encoding flexibility.

**Comment by BruceForstall** [comment]
@JosephTremoulet Do you want to keep this open?

**Comment by JosephTremoulet** [comment]
Ok, I'll close this since it's been idle for so long; it can always be reopened if/when dotnet/llilc#711 is picked back up.
