### ISSUE TITLE
Double.ToString("N2", CultureInfo) then Double.TryParse(numIn, NumberFormat.Any, CultureInfo, numOut) fails for 5 cultures

### ISSUE THREAD

**Issue by HoboRobo123** [dotnet/coreclr#12340]
I asked this [question on StackOverflow](https://stackoverflow.com/questions/44559594/net-double-tryparsenum-format-cultureinfo-out-error) a few days ago.

Short version.
Doing something like:
Double num = 15000.05
String numString = num.ToString("N2", CultureInfo)

Then doing
Double numParsed
Double.TryParse(numString, NumberFormat.Any, CultureInfo, numParsed)
num == numParsed

Doesn't function as expected for the following cultures:
- prs
- prs-AF
- tzm
- tzm-Latn
- tzm-Latn-DZ

The StackOverflow question goes into much more detail but I haven't been able to dive back in and diagnose the issue further yet.

edit: This is running in an en-US locale. 
For the StackOverflow question the numbers are assumed to be stored in en-US in the database at the moment instead of Invariant.

edit2: Forgot to mention that changing the Double.TryParse() to a Double.Parse() appears to fix the issue and interpret the string correctly.

**Comment by jkotas** [comment]
cc @tarekgh

**Comment by tarekgh** [comment]
@HoboRobo123 I'll take a look and get back to you. thanks for reporting this issue.

**Comment by tarekgh** [comment]
@HoboRobo123 

The problem here is the cultures failing for you has the following:

```
Decimal separator is ","
Group Separator is "."
Currency Decimal separator is "."
Currency Group Separator is ","
```

Notice that the decimal separators is same as the currency group separator. Also the group separator is same as the currency decimal separator.

Now when you format the number with such culture, you'll get the string "15.000,05". when you are trying to parse it back you are passing NumberStyles.Any which means the string can be a currency number or it can be decimal number. This confuse the parser when trying to parse the character "." as it can be treated as currency decimal separator or it can be treated as group separator. The parser decide to treat it as currency decimal separator. Then the parser will continue till hitting "," and again will treat this as group separator. because the group separator cannot come after the decimal separator, the parser will fail to parse the string and will return false from TryParse (or throw exception from Parse).

The way to fix this, remove the currency parsing from passed NumberStyles. i.e.

```C#
            Double.TryParse(numString, NumberStyles.Any & (~NumberStyles.AllowCurrencySymbol), ci, out numParsed);
```

I am going to close the issue but feel free to respond back with any more questions if you have any.

**Comment by HoboRobo123** [comment]
@tarekgh thank you so much! I'll add in some logic to differentiate between decimal numbers and currency.
