### ISSUE TITLE
[Question][JIT] Why "(cond)?0:1" can convert to "cond"? Confuse about then node and else node in qmark.

### ISSUE THREAD

**Issue by 303248153** [dotnet/coreclr#12383]
I'm really confuse with this code:
https://github.com/dotnet/coreclr/blob/v2.0.0-preview1/src/jit/morph.cpp#L12539

``` c++
                // If we have (cond)?0:1, then we just return "cond" for TYP_INTs
                //
                // Don't do this optimization for ARM: we always require assignment
                // to boolean to remain ?:, since we don't have any way to generate
                // this with straight-line code, like x86 does using setcc (at least
                // after the IT instruction is deprecated).

                if (genActualType(op1->gtOp.gtOp1->gtType) == TYP_INT && genActualType(typ) == TYP_INT &&
                    thenNode->gtOper == GT_CNS_INT && elseNode->gtOper == GT_CNS_INT)
                {
                    ival1 = thenNode->gtIntCon.gtIconVal;
                    ival2 = elseNode->gtIntCon.gtIconVal;

                    // Is one constant 0 and the other 1?
                    if ((ival1 | ival2) == 1 && (ival1 & ival2) == 0)
                    {
                        // If the constants are {1, 0}, reverse the condition
                        if (ival1 == 1)
                        {
                            gtReverseCond(op1);
                        }

                        // Unmark GTF_RELOP_JMP_USED on the condition node so it knows that it
                        // needs to materialize the result as a 0 or 1.
                        noway_assert(op1->gtFlags & (GTF_RELOP_QMARK | GTF_RELOP_JMP_USED));
                        op1->gtFlags &= ~(GTF_RELOP_QMARK | GTF_RELOP_JMP_USED);

                        DEBUG_DESTROY_NODE(tree);
                        DEBUG_DESTROY_NODE(op2);

                        return op1;
                    }
```

This code will convert "cond ? 0 : 1" to "cond", and "cond ? 1 : 0" to "!cond", which I think it should be opposite, why?

**Comment by mikedn** [comment]
Hmm, this code does appear to be broken but I don't think it ever runs in RyuJIT. Qmarks are only generated when importing certain code sequences and they won't match this pattern. This code should probably be ifdefed out, only when LEGACY_BACKEND is defined you're likely to encounter this pattern.

**Comment by 303248153** [comment]
Is it really appear to be broken?
Because I just saw the comment about ThenNode and ElseNode, I'm not so sure what's this code actually mean.

**Comment by mikedn** [comment]
> Because I just saw the comment about ThenNode and ElseNode, I'm not so sure what's this code actually mean.

Yes, there is some confusion around "then" and "else" but look at the code that's above `case GT_QMARK:` - it converts `cond` into `cond ? 1 : 0`. And despite the slightly confusing reordering in `GenTreeColon` constructor it's easy to see that 1 becomes "then" and 0 is "else", the opposite of what the code you're looking at does.

The only way to be really sure is to check what code is generated for `GT_QMARK` in codegenlegacy.cpp. Not a useful use of your time probably because it's legacy code. Though it's interesting that this code is likely used in the old JIT32 and the current RyuJIT ARM32.

As far as non-legacy RyuJIT is concerned all this code is pretty much dead. You can ifdef out the entire `case GT_QMARK:` and the `if` from the previous case and there would be no changes in the generated code. Hmm, maybe I should do just that, it's a lot of dead code. And the liveness sets in `GenTreeQmark` may be dead as well and just waste space.

**Comment by 303248153** [comment]
Yeah, and I think the comment `If we are entering the "then" part of a Qmark-Colon we must` in morph.cpp is incorrect because all other places see op1 as else part, so the code I was asking should be wrong.
As my question is solved and you opened a new issue, I'll close this one.
