### ISSUE TITLE
Random occurrences of high cpu usage

### ISSUE THREAD

**Issue by tomekpr** [dotnet/coreclr#12410]
hello,

Apologies if that's not the right place to ask this question.

I was hoping that someone can help me out with a little conundrum. From time to time my process goes into a weird state i.e.
100% cpu usage. I ran a performance profiler and I'm not sure if I fully understand what is going on:

Stack trace indicates that hot section is around :
- System.Threading.ThreadPoolWorkerQueue.Dispatch()
----System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem ()
 ---------System.Threading.TimerQueueTimer.Fire () 

Fire() method is apparently responsible for 62.299% cpu time with children, (hit count 1)

https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Threading/Timer.cs

Tells me that the method in question could be blocked trying to acquire lock on (TimerQueue.Instance).
I took a memory dump and it tells me about 1,337,910 live instances of type System.Threading.QueueUserWorkItemCallback
also System-Context-Switches is very high.

That indicates partly that something is blocked within the application and no progress can be made. Unfortunately I'm running out of ideas what could that be. I enabled enough logging but I failed to determine root cause. Only restart of the app helps resolve the issue which is not ideal solution for a production software.

It is worth to mention that I have a couple of instances of the same process, same version runnning in production and they are all fine.

Runtime: .net framework 4.5.2 / x64, physical host with 28 cores
happy to provide more info

Any suggestions? 

Thank you!

**Comment by janvorli** [comment]
Sounds like #10292
cc: @kouvel

**Comment by kouvel** [comment]
The lock in TimerQueueTimer.Fire is held for very short durations with just a few instructions inside each lock. Contention here usually means that there are too many repeating timers that the system is not able to keep up with the work, along with whatever else is happening on the machine. This could be the result of a timer leak or having too many short-period repeating timers. The inherent spinning in the monitor is somewhat excessive and can make the issue worse, but it's typically not the main problem. I would suggest to take a dump of the process while the issue is occurring and first see how many timers there are and look for a leak. If it's not a leak and you expect to have that many short-period repeating timers, then a solution may be to make them non-repeating and reschedule each timer upon completion of its callback to ensure that the number of callback requests does not explode when the system is not able to keep up.

**Comment by tomekpr** [comment]
hi,

Thank you for clarification. Just before @kouvel replied I was looking at memory dump file. It turns out that there were 1.3 million undisposed objects from System.Threading.Timer, so in other words timer  leak. I changed the code such that the timer is not needed at all and we're going to release in subsequent weeks.

Thanks!

**Comment by kouvel** [comment]
Great!
