### ISSUE TITLE
Several jit64 tests fail in Helix on ARM

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/coreclr#12492]
https://mc.dot.net/#/product/netcore/master/source/official~2Fcoreclr~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170626.03/workItem/JIT.jit64.XUnitWrapper

Most error messages are non-descriptive:

> Expected: 100\r\nActual: -532462766

Same error code as in https://github.com/dotnet/coreclr/issues/12488, so maybe related.

@russellhadley can you route this to the right person?

**Comment by wtgodbe** [comment]
https://mc.dot.net/#/product/netcore/master/source/official~2Fcoreclr~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170713.02 These tests are now passing

**Comment by Jiayili1** [comment]
This issue is repro, detail: https://mc.dot.net/#/product/netcore/master/source/official~2Fcoreclr~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20170716.01/workItem/JIT.jit64.XUnitWrapper/analysis/xunit/JIT_jit64._hfa_main_testE_hfa_nd0E_d_hfa_nd0E_d_~2F_hfa_main_testE_hfa_nd0E_d_hfa_nd0E_d_cmd

**Comment by RussKeldorph** [comment]
Passing for a while.
