### ISSUE TITLE
[Arm64] Optimize GCServer=1 scalability on arm64

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#12640]
While testing aspnet/benchmarks `coreoverlay/corerun Benchmarks.dll --scenarios "Plaintext"`

`COMPlus_gcServer=0` is able to 10x request/sec than `COMPlus_gcServer=1`

**Comment by sdmaclea** [comment]
@swgillespie @Maoni0 @jkotas 
cc @dotnet/arm64-contrib

**Comment by sdmaclea** [comment]
On x64.  gcServer=1 is ~10% faster than gcServer=0.

**Comment by sdmaclea** [comment]
Profile shows most of the time being spent spinning in `SVR::t_join::join()`

**Comment by sdmaclea** [comment]
Reducing spin_count to 0 in `SVR::t_join::join()` improve performance 3x over gcServer=1 baseline.  
Reducing spin_count to 0 everywhere in gc.cpp improved performance 6x over gcServer=1 baseline.

**Comment by jkotas** [comment]
cc @vancem since he has been looking into how much spinning we do in various places

**Comment by vancem** [comment]
@PeterSolMS  @brianrob  and @kouvel as well.  I have not looked at spins inside the GC (in particular t_join::join(), because they have not had a history of being a hot spot.   

How many processors are we talking about during these tests?   Also what exactly is the benchmark doing?   The normal, TechEmpower 'plaintext' benchmark was very network bound, not GC bound.   The ASP.NET pipeline is designed to not allocate very much so GC time should not be dominating.  

This is all very surprising, which raised the suspicion that we are not measuring what we think we are measuring...

**Comment by Maoni0** [comment]
On machines with lots of processors actually join can be a hot spot but I've never seen a case as bad as "most of the time being spent in join". Something we wanted to look at was to see if we could make join more performant on many proc machines (eg, make it NUMA aware). Of course the perf is also drastically dependent on the workload - how distributed the work is on each proc? If you have say a single threaded workload of course Server GC would degrade perf by design. If you could provide some profiles for us to look at it would be very much appreciated as we have no hardware to try this on (at least I personally don't).

**Comment by sdmaclea** [comment]
@vancem The GC spin time is proportional to the number of processors in the system.  In `SVR::t_join::join()`  `int spin_count = 4096 * g_num_processors;`  So total cpu time spent spinning is propotional to cpu^2.  There are 48 cores running on the system I am measuring.   47 of them are not last, so must spin.  

When I did the measurements, **I added an instruction barrier to `YieldProcessor()` to slow down each yield spinning which may have dramatically increased spin measured elapsed time.**  

Based on discussion with our local Java expert, there has been no observation of OpenJDK spinning in user space during his performance optimization studies.  In general spinning in user space seems to be a bad idea.  FEATURE_NOSPIN should seriously be considered.  In any case, the spin_count probably needs to be tuned per system. as spin cost and `YieldProcessor()` is very different on different platforms.

**Comment by sdmaclea** [comment]
Without modification on general test cases.  I was seeing gcServer=1 20% slower than gcServer=0.

I will remake measurements w/o changes to YieldProcessor().

**Comment by vancem** [comment]
As @jkotas  mentions I am looking at spinning in other parts of the system (notably the 'lock' statement), and I believe we are doing it way to much there.    As @sdmaclea indicates, arguably spinning is something that low level constructs of the OS should do, and we (the higher levels of the stack) should simply call the OS functionality.     For locks we could not quite get to that point because we also had the goal of not even creating the OS primitive construct until we first block.   Thus we would like to spin (and thus avoid creating the OS primitive) as long as we don't do it too much (many locks are either uncontested, or have very short hold time so you NEVER need to block (and thus create an OS lock) which is a nice optimization).  

However in places where you think it will be common to have to block (thus you will have to allocate the OS structure eventually anyway, we probably should not spin.

Also I have yet to find a coherent rationale for spinning that is proportional to the number of processors.   This only makes sense if you really believe that the CPU can't be put to other uses.  

------------

Finally I note that in the case that the GC is an unusual case in that while spinning make consume much more CPU time, it should not affect throughput OF THAT PROCESS since all other work is suspended (it will however affect other processes on the machine which don't get to share that CPU).

**Comment by sdmaclea** [comment]
I reran w/o the YieldProcessor() modifications.  Performance of gcServer=1 increased by 2x.  So it only represents a 5x performance impact.  The revised profile shows `t_join::join()` as in the most significant backtraces (122 of top 168  (all back traces which represent > 0.1% of elapsed time)) (14 of top 20) (9 of top 10).

@Maoni0 I will see if I can get permission to share a profile.

> it should not affect throughput OF THAT PROCESS
@vancem 
Unless it block another garbage collector thread on the same CPU ie. if GC threads are not locked to a particular thread and are waiting to run or thread migration to an idle processor.

Also consider how unnecessary power dissipation can negatively affect CPU clock speed.

**Comment by vancem** [comment]
> Unless it block another garbage collector thread on the same CPU ie. if GC threads are not locked to a particular thread and are waiting to run or thread migration to an idle processor.

Indeed.  The GC goes to some trouble to affinitize a thread per core.     Note that I am not arguing that spinning is OK for the GC, only that IT SHOULD NOT AFFECT GC PERFORMANCE (how fast apps run) just CPU consumption during the GC.   Is this what you see?   

The argument for spinning is that the value of other work you do does will not exceed the time you spend context switching, and switching back (and warming up the cache again), if the time you are spinning is small (somewhere between from 1us to 1 msec).  If you believe your wait time is small, spinning makes sense.   In a balanced GC heap, you certainly hope for this, but imbalances can happen, so it is unclear what is best.

**Comment by sdmaclea** [comment]
The stimulus is being generated on the same machine as that creates the highest request/sec on x64 and arm64.  Performance is best when `wrk` uses 2 threads (x64 and arm64).  So there are a few busy CPUs on the system.

Performance is definitely still improved by not spinning.

It should be noted that the underlying pthread/kernel implementation may also be spinning to achieve the same hot wakeup goal.

**Comment by sdmaclea** [comment]
Setting `COMPlus_GCHeapCount` <= 8 substantially helps..  Performance is pretty flat between 2 and 8 GCHeaps.  

With that setting and various other changes it looks like performance of gcServer=1 is slightly better than gcServer=0. (~10%).

I will clean up my tip, and make more formal measurements.  I will get a before and after trace for default config vs. best config.

**Comment by sdmaclea** [comment]
I rebased this morning and the results are very different.  I suspect #12486 substantially improved the issue.

If I set `COMPlus_GCNoAffinitize`, the performance degrades much more than it did yesterday.

**Comment by Maoni0** [comment]
@sdmaclea, what are the current results?

**Comment by sdmaclea** [comment]
I haven't run a profile yet.  Best performance I have found so far is 

With default configuration, COMPlus_gcServer=1 is 50% better than COMPlus_gcServer=0.

Best performance I have found so far is this configuration:
```
COMPlus_ThreadPool_ForceMinWorkerThreads=4
COMPlus_gcServer=1
corerun ~/Benchmark/Benchmarks.dll --scenarios "Plaintext" --threadCount=7
wrk -c 384 -t 2 -d 100 http://localhost:5000/plaintext
```

With that configuration performance is about 60% better than the same w/ COMPlus_gcServer=0.

**Comment by sdmaclea** [comment]
@Maoni0 
Here is a brief profile of that configuration.
It includes only samples which occurred while running the test.
It includes all samples running in user space which accounted for 1% of total CPU runtime.
It only includes one extra level of backtrace.

```
Samples | Percent | State | Backtrace... |  
305206 | 4.98364% | R | 263860 SVR::t_join::join | 255b2c SVR::gc_heap::relocate_phase
239134 | 3.90477% | R | 263860 SVR::t_join::join | 250f68 SVR::gc_heap::scan_dependent_handles
173665 | 2.83573% | R | 263860 SVR::t_join::join | 2446b4 SVR::gc_heap::gc1
158836 | 2.59359% | R | 263860 SVR::t_join::join | 246994 SVR::gc_heap::mark_phase
155798 | 2.54399% | R | 263860 SVR::t_join::join | 248860 SVR::gc_heap::plan_phase
155737 | 2.543% | R | 263860 SVR::t_join::join | 248110 SVR::gc_heap::plan_phase
153382 | 2.50453% | R | 263860 SVR::t_join::join | 24692c SVR::gc_heap::mark_phase
152184 | 2.48498% | R | 263860 SVR::t_join::join | 2559c0 SVR::gc_heap::relocate_phase
148736 | 2.42868% | R | 263860 SVR::t_join::join | 250f68 SVR::gc_heap::scan_dependent_handles
141283 | 2.30697% | R | 263860 SVR::t_join::join | 24689c SVR::gc_heap::mark_phase
124738 | 2.03682% | R | 263860 SVR::t_join::join | 246798 SVR::gc_heap::mark_phase
69304.4 | 1.13166% | R | 2638f4 SVR::t_join::join | 248110 SVR::gc_heap::plan_phase
65768.9 | 1.07392% | R | 2638f4 SVR::t_join::join | 255b2c SVR::gc_heap::relocate_phase
64314.9 | 1.05018% | R | 2638f4 SVR::t_join::join | 246994 SVR::gc_heap::mark_phase
63520.6 | 1.03721% | R | 2638f4 SVR::t_join::join | 250f68 SVR::gc_heap::scan_dependent_handles
63439.1 | 1.03588% | R | 2638f4 SVR::t_join::join | 248860 SVR::gc_heap::plan_phase
62758.8 | 1.02477% | R | 2638f4 SVR::t_join::join | 24692c SVR::gc_heap::mark_phase
62272.2 | 1.01683% | R | 2638f4 SVR::t_join::join | 246798 SVR::gc_heap::mark_phase
61992.5 | 1.01226% | R | 2638f4 SVR::t_join::join | 24689c SVR::gc_heap::mark_phase



```

**Comment by sdmaclea** [comment]
The root cause of this issue was that Gen0 heap was 1/100 th of the size used for AMD64 platform of similar performance.  This caused GC to run hundreds of times per second.

Pinning GC threads made a substantial impact because GC was running so often.  I am still slightly concerned with over constraining the GC threads to be only able to run on a single processor.  I have yet to observe an issue.

Join is using roughly half of time spent in GC in GCServer mode.  When properly configured GC should only consume <1% of total CPU, so join inefficiency is acceptable to me.  If someone wanted to optimize, a work queue structure could be created.

In GCServer=1 mode it does appear there is an absence of time based tuning.  GCServer=0 mode seems to aim gen0 collections at about 1Hz.

#12771 #12772 and #12773 are related PR which are related to this work.

**Comment by sdmaclea** [comment]
Also there are 11 joins per GC.  If any of these could be eliminated it would save spin time.  See JOIN_STATS in comment in #12773.  `elapsed_total` represents useful work.  `in_join` represents time spinning and/or waiting in the scheduler.  Intuitively w/o any analysis one would hope joins could be reduced to 3-6 per GC.

This comment is purely for historical reference, as I do not intend to address this.

I will close this as the open PRs will solve ARM64 issues.
