### ISSUE TITLE
How to embed CoreCLR on Linux and OSX?

### ISSUE THREAD

**Issue by amerkoleci** [dotnet/coreclr#1271]
I would like to know how would I embed CoreCLR and distribuite my application on Linux and OSX without need of dnx.
Basically I would have something like coreclr run that will execute my C# application, but the user should not be aware about the CoreCLR part.

Sorry if the question is generic.

http://www.mono-project.com/docs/advanced/embedding/

**Comment by benpye** [comment]
You can use coreconsole for this purpose. You take your application, rename it from application.exe to application.dll, yourself get the coreclr and corefx binaries you need and then rename coreconsole to application.exe on Windows or just application on other platforms. Then your users just run application without worrying that it's .NET. You will need different distributions for OSX, Linux etc because of differences in CoreFX.

**Comment by amerkoleci** [comment]
Thank you very much, very appreciated.
