### ISSUE TITLE
isinst uint[] returns true for a int[]

### ISSUE THREAD

**Issue by ColoradoNate** [dotnet/coreclr#12818]
Version Used: VS2015, VS2017

Steps to Reproduce:

1. Create a ushort[]
2. Test if the ushort[] 'is' a short[]

Expected Behavior: 'is' claims signed arrays are not unsigned arrays, and unsigned arrays are not signed arrays

Actual Behavior: 'is' claims signed arrays are both signed and unsigned arrays.

NOTE: This issue shows up with short/ushort, int/uint, and long/ulong arrays (but it works as expected for non-arrays of these types)

NOTE: The new C#7 switch syntax ("case ushort[] ua:") exhibits the same issue (it emits the same IL). The first signed/unsigned case in the source wins.  

NOTE:  See [SwitchOnType.zip](https://github.com/dotnet/coreclr/files/1149642/SwitchOnType.zip) for an example

NOTE:  originally submitted to the Roslyn team - they suggested submitting it here.  See https://github.com/dotnet/roslyn/issues/20874 to see the Roslyn team's comments.

**Comment by jkotas** [comment]
The short answer is: This behavior is by design - it was speced this way. It is one of the cases where .NET Runtime is more permissive than C# language that tends to surprise people.

You can find many discussion of this question, e.g. here: https://stackoverflow.com/questions/593730/why-does-int-is-uint-true-in-c-sharp
