### ISSUE TITLE
[Question] TypeHandle relocations

### ISSUE THREAD

**Issue by gbalykov** [dotnet/coreclr#12957]
We propose to move m_ElementTypeHnd out of MethodTable by allocating additional space for it after MethodTable and storing RelativePointer to type handle in MethodTable itself. In native image, type handle will be stored in a separate section, which will allow to reduce the number of dirty page, and, thus, make more pages shareable.

The same idea could be applied to m_Arg type handle in ParamTypeDesc.

What do you think about this?

cc @Dmitri-Botcharnikov @ruben-ayrapetyan

**Comment by BruceForstall** [comment]
cc @jkotas @janvorli

**Comment by jkotas** [comment]
What's the problem with making `m_ElementTypeHnd` to be a relative pointer directly?

**Comment by gbalykov** [comment]
`Instantiation` wrapper uses pointer to `TypeHandle` in different places and also in JIT code. `RelativePointer` doesn't allow to use address to absolute pointer. To reduce amount of changes, we propose to allocate `TypeHandle` outside of the `MethodTable` and store `RelativePointer` to `TypeHandle` in `MethodTable` itself. So, in JIT code, `TypeHandle` will be accessed through pointer to memory outside of the `MethodTable` (without additional indirection) and `RelativePointer` field in `MethodTable` itself will be a cold field. In native image this `TypeHandles` will be stored densely and amount of relocations on pages with `MethodTables` will be reduced.

The side effect of this is allocation of additional memory for non-fragile mode. By using tagged pointer to `TypeHandle` in `MethodTable`, this could be enabled only for cross generation of fragile images, and for non-fragile mode `TypeHandle` will remain in `MethodTable`.

**Comment by jkotas** [comment]
Instantiation made out of the array is used just in SigTypeContext. It is not widespread.

Another side-effect is that it would make setting element of an array slower that is pretty frequent operation:

https://github.com/dotnet/coreclr/blob/4a0a82a8dabaabb1e9a82af944d70aed210838a3/src/vm/amd64/jithelpers_fast.S#L429

Do you have a list of all changes that you would like to make before you declare your effort done so that we can see them more holistically instead of one at a time?

**Comment by ruben-ayrapetyan** [comment]
> Instantiation made out of the array is used just in SigTypeContext. It is not widespread.

As we understood the comment https://github.com/dotnet/coreclr/issues/11961#issuecomment-304680525, pointers to `TypeHandle`, which are provided by `Instantiation`, were also accessed from JIT-compiled code, so are frequently accessible. This is the reason why we propose to move the field out of structures, instead of replacing it with `RelativePointer<TypeHandle>`.

> Do you have a list of all changes that you would like to make before you declare your effort done so that we can see them more holistically instead of one at a time?

Currently, the change with `TypeHandle` and changes in `SECTION_ReadOnly` are the last in series of changes related to removal of relocated fields, which we would like to propose.

Among other areas, we would like to propose the following:
- delayed application of relocations (apply relocations only for those pages, which are accessed at least once);
- GC-related optimizations under a define or runtime configuration key.

This is not full list, currently we are constantly in search of possible ways to reduce memory consumption of CoreCLR. Could you, please, suggest what could we do to make results of the search and our proposals more convenient to review and more suitable from view point of direction of CoreCLR development?

**Comment by ruben-ayrapetyan** [comment]
> Currently, the change with `TypeHandle` and changes in `SECTION_ReadOnly` are the last in series of changes related to removal of relocated fields, which we would like to propose.

More precisely, the change for `TypeHandle` is a part of changes for `SECTION_Class` and `SECTION_ReadOnly`, which we didn't include into those pull requests, because weren't sure about complexity of the related changes. Now, we would like to add the changes for `TypeHandle` too.

**Comment by jkotas** [comment]
> pointers to TypeHandle, which are provided by Instantiation, were also accessed from JIT-compiled code, so are frequently accessible.

This is general statement about Instantion. The specific Instantiation created from `m_ElementTypeHnd` is not accessed from JIT-compiled code, etc. It is only used in SigTypeContext.

> delayed application of relocations

How would you trigger the application of the relocations?

**Comment by ruben-ayrapetyan** [comment]
> This is general statement about Instantion. The specific Instantiation created from m_ElementTypeHnd is not accessed from JIT-compiled code, etc. It is only used in SigTypeContext.

Now, I see. Thank you.

> How would you trigger the application of the relocations?

Idea is to `mprotect` the pages, which need relocations, with `PROT_NONE`, and apply relocations upon first access to such a page.

**Comment by jkotas** [comment]
> Idea is to `mprotect` the pages, which need relocations, with PROT_NONE, and apply relocations upon first access to such a page.

We have done experiments with similar schemes in the past. The problem is that these faults make things impossible to debug, and they are not cheap either. If you think it is a good tradeoff for Tizen, it would been to be under ifdef.

**Comment by ruben-ayrapetyan** [comment]
> We have done experiments with similar schemes in the past. The problem is that these faults make things impossible to debug, and they are not cheap either. If you think it is a good tradeoff for Tizen, it would been to be under ifdef.

Yes, sure, we were thinking of adding it under a runtime configuration option or under ifdef.
Our preliminary estimation is about 1 milliseconds per 10 delayed-relocated pages.
Also, we were thinking of saving per-application  profile information for this, to apply most of necessary relocations during initialization as it is now - this should make the performance overhead unnoticeable.

> The problem is that these faults make things impossible to debug

Could you, please, clarify what kind of issues the faults caused?
Is it about debugging complexity of the solution, or about inconvenience to use debugger because of frequent fault signals?

**Comment by jkotas** [comment]
inconvenience to use debugger because of frequent fault signals

**Comment by ruben-ayrapetyan** [comment]
Yes, this can be an issue. However, debugger can be configured to skip such signals, even not printing them - instead breakpoint to a right place in handler of `SIGSEGV` can be placed to catch actual faults. In this case, the frequent signals will not be visible during debug.
