### ISSUE TITLE
Proposal - GC.HeapStat() for garbage collector heap statistics

### ISSUE THREAD

**Issue by dduerner-ycwang** [dotnet/coreclr#12969]
It seems as though it'd be helpful for us developer's to have an easy way to obtain heap statistics programmatically at runtime. It might be somewhat helpful to assist us in making logic decisions at runtime, such as when to initiate a Large Object Heap compaction programmatically at runtime. We don't know if there are technical reasons this wouldn't be possible or whether it's simply not feasible technically. However, it seems like it might be handy to have and possibly make our developer lives a little easier.

It would be very similar to Windbg's !heapstat command, only we could get the stat info programmatically at runtime in production code.

Not sure what the API would look like, but here's a possible example just to start thinking about it and exploring:

`Hashtable heapinfo = GC.HeapStat(HeapStatEnum.LOHFrag);`

Psuedocode example of how to possibly use at runtime:

```
private void timer_Tick()
{
   if (GC.HeapStat(HeapStatEnum.LOHFrag)["AvgAllHeaps"] > .80)
   {
      GCSettings.LargeObjectHeapCompactionMode = GCLargeObjectHeapCompactionMode.CompactOnce;
      GC.Collect();    
   }
}
```

"HeapStatEnum" could keep expanding with new metrics over time as necessary.

Example of what "HeapStatEnum" might possibly look like:

```
public enum HeapStatEnum
{
   LOHFrag,
   LOHFreeSpace,
   LOHUsedSpace,
   LOHGeneral,
   ...
   SOHFrag,
   SOHFreeSpace,
   SOHUsedSpace,
   SOHGeneral
   ...
}
```

Each new metric added to enum would be responsible to define what's returned in "heapinfo" for that new metric.

For example "LOHFrag" might hypothetically return a hashtable containing:

```
Key              Value
============     ============
"AvgAllHeaps"    .25
"Heap0"          .10
"Heap1"          .50
"Heap2"          .30
"Heap3"          .10
```

For example "LOHUsedSpace" might hypothetically return a hashtable containing:

```
Key              Value
============     ============
"Heap0"          the used bytes in heap0
"Heap1"          the used bytes in heap1
"Heap2"          the used bytes in heap2
"Heap3"          the used bytes in heap3
```

For example "LOHGeneral" might hypothetically return a hashtable containing:

```
Key              Value
============     ============
"Heap0"          general info about heap0 (similar to !dumpheap)
"Heap1"          general info about heap1 (similar to !dumpheap)
"Heap2"          general info about heap2 (similar to !dumpheap)
"Heap3"          general info about heap3 (similar to !dumpheap)
```

We're not really sure if this is a good idea or not, or if the necessary information's even readily available in the GC at runtime, or whether it's even technically feasible to obtain this information at runtime. We were just thinking it might make our developer lives a little easier, if we were able to obtain this stat info programmatically in code at runtime, especially as new configuration and tuning related features continue to be added over time to the GC in the future, it might help assist us in using the new features properly...

**Comment by swgillespie** [comment]
cc @Maoni0 

Proposals for new APIs generally live in the CoreFX repo; can you move this proposal over there? ([Here](https://github.com/dotnet/corefx/blob/e276a7cd9cfb4ff84c57109e25fc682f9403118e/Documentation/project-docs/api-review-process.md) is the general guidelines for API proposals, if you're interested.

Some prior art in this area is what the [Go runtime provides](https://golang.org/pkg/runtime/#ReadMemStats). Having used this API in Go, in my opinion it doesn't really fit well into the "pit of success" model that CoreFX goes for; the runtime needs to suspend in order to collect accurate numbers, and so calling this API has a tremendous non-obvious action-at-a-distance cost on all threads/goroutines running in the process.

**Comment by jkotas** [comment]
cc @vancem 

We have been exposing this sort of data via tracing (ETW on Windows, ...). The tracing is designed for the case where you are getting to the data from the outside of the process. It is not particularly easy for the process to self-monitor itself. Perhaps we need to make the self-monitoring easier to setup.

**Comment by vancem** [comment]
@brianrob 

We have a plan to expose events that we currently log with ETW as if it came from an EventSource (thus you can subscribe to it with EventListener in managed code.   Note that the delivery of these events will be asynchronous 'fire and forget' (that is the system has moved on by the time you see the event).   This is required for GC events since you can't run managed code while the GC is in progress.  

I like this 'event' style model (you don't get to know values any time you choose, but you get values when we actually know something (e.g. just after a GC).  

Brian is out for a week or so, but he can comment when he gets back.  

Note that when the logic that uses this starts doing more than just logging but tries to react (e.g. provoking GCs), things get VERY worrisome.    It would be very easy to do more harm than good with such logic...

**Comment by ygc369** [comment]
@vancem 
Excellent! I want GC events quite a long time.
An event should be triggered every time after GC.
