### ISSUE TITLE
Server background GC does not compact at >50% generation 2 fragmentation

### ISSUE THREAD

**Issue by liorss18** [dotnet/coreclr#12987]
We have a service application running in IIS on Windows Server 2012, .NET 4.6.1, x64, 8 logical processors, 48GB RAM, pagefile disabled, server concurrent GC. Over the course of multiple days, its generation 2 size grows from ~5GB to ~13GB and more, up to a point where Windows kills the process because of the "low virtual memory" notification. During this period, there are approximately 200 gen 2 collections per day. These collections do not bring the gen 2 size down. However, forcing a GC with `GC.Collect(2, GCCollectionMode.Forced)` brings gen 2 down to ~5GB immediately.

It appears that the background GCs that happen 200 times a day do not compact gen 2. Looking at a dump file of the process prior to inducing a compacting collection, we can see heap fragmentation of over 50% across all 8 heaps. After the induced collection, gen 2 shrinks considerably and there is less than 2% fragmentation in gen 2. As far as we can tell, [`decide_on_compacting` in gc.cpp](https://raw.githubusercontent.com/dotnet/coreclr/master/src/gc/gc.cpp) should "decide" to perform a compacting collection when fragmentation in gen 2 is greater than 25%, which is definitely true in our case. We might be able to provide the dump files if necessary (~30GB each).

Our questions:

* Is there something else we should be doing to get our gen 2 compacted automatically, without resorting to induced GCs?

* The heap growth would not concern us in general, but it eventually brings the process down (exhausting physical memory) if we don't force a compacting GC -- could it be that even in face of an OS low memory notification the GC still decides to perform a non-compacting collection?

/cc @Maoni0 @goldshtn

**Comment by Maoni0** [comment]
Weird, I did not get a notification in email for this issue at all - I just noticed it when I was browsing the issues... apologies for the delay.

Background GC does not compact so it doesn't call decide_on_compacting. But your process should not go down because when the memory load is high we will do a compacting gen2. If you actually observed the process gets OOM even though your live data is much smaller than the physical memory you have, that's certainly something we'd like to look at. If you could capture an ETW trace with this PerfView commandline that includes the time before it gets to OOM and when it gets OOM (in other words, we want to see the history that was leading up the OOM), that would be most helpful:

perfview /GCCollectOnly /nogui /accepteula /NoV2Rundown /NoNGENRundown /NoRundown /merge:true /zip:true collect

This is very lightweight so can be kept on for hours. Please let us know if you need help doing this. also CC-ing @swgillespie.

**Comment by Maoni0** [comment]
since we haven't heard back on this I will close it for now. please reopen if you believe you still need help.
