### ISSUE TITLE
[Arm64 Windows] Use portable MP optimized new/alloc

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#13053]
#12333 "[Arm64 / Windows] Use portable MP optimized new/alloc" did not include Windows due to a Contract violation.  Debug contract violation and enable for Windows

category:cq
theme:helpers
skill-level:intermediate
cost:small

**Comment by AndyAyersMS** [comment]
Do we still want this for 3.0? 

Also, we should probably reclassify this as a runtime issue.

**Comment by jkotas** [comment]
Note that this is ARM64 Windows-specific issue. Is .NET Core 3.0 going to be officially supported on Windows ARM64?

In any case, the fix is just about removing an ifdef TODO and see whether the tests pass. I would expect that it will just work.

**Comment by jkotas** [comment]
Submitted https://github.com/dotnet/coreclr/pull/22283 to see whether there is anything real left to fix.

**Comment by jkotas** [comment]
The problem is still there. Somebody with Windows ARM64 box needs to debug it.

**Comment by jkotas** [comment]
@adityamandaleeka Do you happen to have Windows ARM64 box around to debug this?

**Comment by adityamandaleeka** [comment]
Yes, I do. I'll take a look at this soon.

**Comment by AndyAyersMS** [comment]
Can you also look at #13590? It may already be fixed.

**Comment by adityamandaleeka** [comment]
@jkotas I had a chance to look into this today.

The portable alloc fast paths are marked `FCALL_CONTRACT` which is GC_NOTRIGGER. The problem here is that `JIT_NewArr1OBJ_MP_FastPortable` calls `SetArrayMethodTable` which, in debug, calls `ArrayBase::AssertArrayTypeDescLoaded` to ensure that the type of the array is loaded.

`LoadArrayTypeThrowing` is GC_TRIGGERS unless `FORBIDGC_LOADER_USE_ENABLED` is true.

I'm not an expert in this area, but based on what I see, I think it may be okay to stick an `ENABLE_FORBID_GC_LOADER_USE_IN_THIS_SCOPE` in `ArrayBase::AssertArrayTypeDescLoaded` since we believe that the type is already loaded if that function is being called. Does that sound right, or am I missing something?

**Comment by adityamandaleeka** [comment]
@AndyAyersMS I think you're right.

**Comment by jkotas** [comment]
> stick an `ENABLE_FORBID_GC_LOADER_USE_IN_THIS_SCOPE` in `ArrayBase::AssertArrayTypeDescLoaded`

Yes, that should work. Could you please try to do that?

**Comment by adityamandaleeka** [comment]
Yup, just opened a PR.
