### ISSUE TITLE
The profiler cannot disable ConcurrentGC because the GC Caches configuration information from EEConfig

### ISSUE THREAD

**Issue by davmason** [dotnet/coreclr#13153]
In `ProfilingAPIUtility::LoadProfiler` we call `g_pConfig->SetGCconcurrent(0);` to disable concurrent GC if the profiler is subscribed to any GC events.

Currently the configuration is cached and since the profiler initializes after the GC, this value is never read by the GC, so concurrent GC is left enabled. This causes the profiler to behave unexpectedly - such as not being able to iterate through the GC heap.

I believe #11379 added caching of configuration.

**Comment by swgillespie** [comment]
Thanks David! cc @Maoni0 . The problem is that we are caching configuration on startup that a profiler may invalidate.

I figure that we can either not cache select configuration values, ones that we know have the potential to change underneath us (e.g. concurrent GC), or provider the profiler with a hook to invalidate our config cache. The latter sounds kludgy so I think I'm inclined towards the first solution. Maoni, do you have any thoughts?

**Comment by Maoni0** [comment]
That's weird - AFAIK the profiler was using TemporaryDisableConcurrentGC/TemporaryEnableConcurrentGC to temporarily disable/enable concurrent GC as needed. It should never change the default one which is only read at startup (and it's always been this way). But we do check temp_disable_concurrent_p every time we need to decide whether we can do concurrent GC and this is modified by the 2 APIs. Has this changed?

**Comment by davmason** [comment]
There are two different code paths - on profiler attach it runs as you described, where it calls TemporaryDisableConcurrentGC, but when a profiler is loaded at startup it calls SetGCConcurrent.

This hasn't changed in CoreCLR at any point - I assume it's been that way for a long time in desktop too.

**Comment by Maoni0** [comment]
@davmason Ahh I see. you are referring to the startup path. @swgillespie since it's at startup, can't we just include that decision when this config is returned to the GC side? This must've happened between EE configs changing iGCconcurrent and GC reading it 'cause GC has never read iGCconcurrent except during init.

**Comment by swgillespie** [comment]
@davmason An update, I plan on looking at this bug this week.

**Comment by swgillespie** [comment]
So the problem is that we have (yet another) cycle in the initialization dependency graph. The GC is initialized well before the profiling service and so by the time the profiling service turns off concurrent GC, it is too late since the GC has initialized already and cached the result of `EEConfig::GetGCconcurrent`.

The straightforward approach is to not cache `EEConfig::GetGCconcurrent`. This is unfortunate for GC performance since we will now need to do a potentially-indirect call to the EE (`GCToEEInterface::GetBoolConfigValue`) and further do some string-comparisons. 

Another approach is to have a way for the EE to inform the GC that it needs to flush its configuration cache. This is also not good because of the added complexity and general ugliness.

I don't think that we'll be able to move profiling initialization to be before
before the GC. I will give it a try today but I am not optimistic - there are 11 services that initialize after the GC but before the profiler and I'm sure the profiler has a dependency on at least one of them.

I'm not really sure what the best approach is here - @davmason any thoughts from a profiler perspective? @Maoni0 is out for the week but she'll probably have some thoughts when she comes back.

**Comment by swgillespie** [comment]
Another thought - is it possible that we could use TemporaryDisableConcurrentGC/TemporaryEnableConcurrentGC exclusively instead of relying on the current startup behavior? (e.g. not using SetGCconcurrent at all)

**Comment by swgillespie** [comment]
cc @sergiy-k

**Comment by davmason** [comment]
I don't have any strong opinions, as long as the profiler can disable concurrent GC. Is there going to be any difference in behavior between the two?

@noahfalk in case he has thoughts

**Comment by swgillespie** [comment]
According to Maoni (and looking at the code) we do check the status of `temp_disable_concurrent_p` in the GC whenever we need to figure out whether we can do a concurrent GC. At least from my perspective I don't think there should be a difference between disabling concurrent GC at startup vs. calling `TemporaryDisableConcurrentGC` on startup and never re-enabling it.

**Comment by noahfalk** [comment]
I haven't checked the code, but just reading the thread I came to the same conclusion as @swgillespie ... we shouldn't need two different mechanisms to disable concurrent GC and if temp_disable_concurrent_p works we could simply standardize on it. Probably the reason we have two mechanisms now is historical. 

FWIW I think the odds are reasonable that we could init profiling earlier and it would work, but I'd explore using TemporaryDisableConcurrentGC first.

**Comment by swgillespie** [comment]
Whoops... sorry!

Anyway, I was looking at the code this morning and I found at least one place in the GC that doesn't look at `temp_disable_concurrent_p` when reasoning about concurrent GC. I think it's easily fixable, though, so I'll fix it and give `TemporaryDisableConcurrentGC` a shot on the profiler tests.

**Comment by swgillespie** [comment]
Hmm, this is unfortunately not going to be as straightforward as I'd hoped. There are a number of code paths that only check `gc_can_use_concurrent` (obtained from config only and not influenced by `temp_disable_concurrent_p` so there will be different code paths taken if we only use `TemporaryDisableConcurrentGC`. Maoni is OOF for the week but I think we'll need her thoughts from a GC perspective on this.

**Comment by noahfalk** [comment]
Happy to wait until she gets back. As far as I know from the profiler perspective disabling concurrent GC on attach is intended to be as effective as disabling it up-front. If some of the code paths aren't honoring the disable on attach mechanism that might represent bugs in the attach case that need to be fixed.

**Comment by Maoni0** [comment]
Not all the codepaths that check for gc_can_use_concurrent should be checking for temp_disable_concurent_p - this is by design. For example, we still want to allocate memory to support concurrent GC (and fail if we can't) because concurrent GC might be enabled again. Of course if you want to use temp_disable_concurent_p to actually permanently disable concurrent GC, it would still work functionally, ie, concurrent GC would still not run, but we'd be less efficient 'cause we are still allocating datastructures that are specifically for concurrent GC. 

We could just expose an additional API on the GC interface for profiling to change the value of gc_can_use_concurrent during the start up path? You could name it something like DisableConcurrentGCOnStartup to make sure it's only meant to be called on start up so it doesn't get changed randomly while the process is running (which would cause problems).

**Comment by noahfalk** [comment]
>we'd be less efficient 'cause we are still allocating datastructures that are specifically for concurrent GC.

Is this a significant perf difference we think the profiler developer would care about? If not (or its unclear) I'm happy to start simple and have everything be controlled by temp_disable_concurrent_p. We could always improve the implementation by adding a new startup specific API if we find that perf difference mattered in the future.

**Comment by Maoni0** [comment]
It's not too bad; I would say let's just use temp_disable_concurrent_p for now to keep it simple.

**Comment by davmason** [comment]
Fixed in #16314
