### ISSUE TITLE
gtCloneExpr allows to clone RET_EXPR  ref   (inl return from call [000054])

### ISSUE THREAD

**Issue by sandreenko** [dotnet/coreclr#13435]
Fox example we have call(1) , that result(2) is used in another call(3) as argument (4).
Then we call gtCloneExpr for call(3) and get call(5), that has argument (6)  `RET_EXPR  ref   (inl return from call [001])`
```
[001] call smth
```
***
```
[003] --CXG-------               /--*  CALL ind nullcheck int
[004] --C--------- arg1         |  +--*  RET_EXPR  ref   (inl return from call [001])
```
***
```
[005] --CXG-------               /--*  CALL ind nullcheck int
[006] --C--------- arg1         |  +--*  RET_EXPR  ref   (inl return from call [001])
```
***

Do we consider such sequence as correct? There are no nodes with same ID, but if inlining happens, then we do "Replacing the return expression placeholder " for 6 and 4 with the same tree.
```
[003] --CXG-------               /--*  CALL ind nullcheck int
[100] --C--------- arg1         |  +--*  inlined call[001] tree
```
***
```
[005] --CXG-------               /--*  CALL ind nullcheck int
[100] --C--------- arg1         |  +--*  inlined call[001] tree
```
***

For now It only happens with CoreRT and fat call transformation dotnet/corert#4251. This issue will be fixed with #9422. However, it is possible to meet this problem again in the future. It would be nice to forbid such cloning or force "Replacing the return expression placeholder " to create clone.

**Comment by sandreenko** [comment]
cc @dotnet/jit-contrib

**Comment by AndyAyersMS** [comment]
In general it is unwise to clone a RET_EXPR, since the subtree it stands for can be quite large. It is also, as you have discovered, unsafe, as we simply clobber the RET_EXPR with the replacement tree when we remove it.

We could fix this case by cloning the replacement before overwriting the RET_EXPR node (cloning if and only if the RET_EXPR node it itself a clone), but we probably want to be more thoughtful about code duplication.

So likely the fat calli transformer should look at its call address node, and if it is complex or a RET_EXPR, evaluate it into a temp (and spill as needed), instead of always cloning it like it does now. You can either call or use `impCloneExpr` as a model for what to do here.

**Comment by sandreenko** [comment]
If such code is already incorrect:
```
[003] --CXG-------               /--*  CALL ind nullcheck int
[004] --C--------- arg1         |  +--*  RET_EXPR  ref   (inl return from call [001])

[005] --CXG-------               /--*  CALL ind nullcheck int
[006] --C--------- arg1         |  +--*  RET_EXPR  ref   (inl return from call [001])
```
then we should forbid it, it means we should change gtCloneExpr and forbid gtNewInlineCandidateReturnExpr. What did this function stand for?

**Comment by AndyAyersMS** [comment]
I agree in principle, yeah. You can clone it but you need to make sure only one copy ends up live.

There are a few operators like this where cloning is problematic. Would be interesting to assert that we never clone these and see what happens.

**Comment by sandreenko** [comment]
I add NO_WAY assert and we don't meet it in CoreCLR or spmi tests.

**Comment by AndyAyersMS** [comment]
Not surprising, so the case you introduced with the CALLI transform is the only one that tries cloning a GT_RET_EXPR. As I've said elsewhere, using `impCloneExpr` should fix this.
