### ISSUE TITLE
[osx] [linux] corerun ExecuteAssembly failed - status: 0x80004005

### ISSUE THREAD

**Issue by Piot** [dotnet/coreclr#135]
```
$ ./build.sh
$ cd binaries/Product/amd64/debug
$ touch fake_file.txt
$ ./corerun  -c . fake_file.txt 
ExecuteAssembly failed - status: 0x80004005
```

Same error even if a valid executable assembly is referenced.

osx: 10.10.2
clang: 600.0.56
cmake: 3.1.1

**Comment by shahid-pk** [comment]
@Piot 
Currently this is the most you can get on UNIX based systems. You will have to hack a bit to actually run an assembly.If you are interested the wiki has an article.
[Here in the wiki](https://github.com/dotnet/coreclr/wiki/Building-and-Running-CoreCLR-on-Linux)

**Comment by ellismg** [comment]
At a minimum, you need to get a copy of mscorlib.dll (and likely also System.Console.dll) in order to do anything useful.  The ones compiled for Unix may very well work or there might be some work that needs to be done both here and in CoreFx to get things to work (e.g. System.Console.dll parses terminfo files, I'm not sure if they are present in the same place on Mac).

PR's are welcome to get more stuff working on OSX.

**Comment by Piot** [comment]
The mscorlib.dll was not built correctly, so the issue is not valid.
