### ISSUE TITLE
Investigate throughput impact of 020337d

### ISSUE THREAD

**Issue by adiaaida** [dotnet/coreclr#13551]
We see an over all 1.5% regression in x64 windows throughput with this change, with throughput regressions of median values of individual assemblies of up to 3.5% in larger assemblies (System.Linq.Expressions, for example). A change that reverted a prior version of this change (361a81b which reverted 0d390cc) saw an overall win of almost 3% across our throughput benchmarks, suggesting that this change has a serious throughput impact. This impact needs to be investigated.

Throughput Regression: https://benchview/compare?jobid=48846&resulttypeid=956&archid=9&testid=63319&configid=2839&machinepoolid=1292&comparejobids=[48830]&

Throughput results of the change that reverted a prior version of this change: https://benchview/compare?jobid=48597&resulttypeid=956&archid=9&testid=63322&configid=2839&machinepoolid=1292&comparejobids=[48580]&

**Comment by briansull** [comment]
This changeset make a small change to the hot code path for the JIT memory allocation.

It adds in the required round up to the next pointer sized allocation amount.

Since all the allocations in the JIT  (except one) were already properly aligned we still allocate the same number of bytes and the extra cost of aligning the request size is one or two simple ALU instructions, so that also should not slow down the Jit measurably.

What will happen though is that the PGO data will indicate that the hot method is "different" so it will prevent the PGO optimizations from fully optimizing and in-lining through this method.

I would expect to see the perf losses regained as soon as the new updated PGO training data is used.
I also would only expect to only see regressions for the Windows platforms that use PGO optimizations.

That is in fact what we see here.

**Comment by adiaaida** [comment]
Brian and I talked about this regression a bit this morning, and I have confirmed that with new pgo data, we get about a 3% overall win, reversing the regression of this change. This confirms that the regression from this change was indeed due to stale PGO data.
