### ISSUE TITLE
Changing internal interface breaks public base class even though it doesn't derive from interface

### ISSUE THREAD

**Issue by jabbera** [dotnet/coreclr#13564]
Referred from https://github.com/dotnet/roslyn/issues/21677

**Version Used**: 
Microsoft (R) Visual C# Compiler version 2.3.2.62019 (b7354608)
Whatever dotnet build does with the 2.0.0 SDK

**Steps to Reproduce**:

Clone: https://github.com/jabbera/InterfaceBug/tree/dotnetcore
Run build.bat

Build.bat 
  compiles version with property on interface
  runs the app
  compiles new BaseClasses.dll with non breaking changes
  copies it over the running app
  runs the app

**Expected Behavior**:

Application should run fine. I've only modified an internal interface in a non derived class.

**Actual Behavior**:

Application crashes with an error in a class that does not derive from the interface directly or indirectly.

I know the subject of this issue sounds crazy, but it's true. If I make a change to an internal interface in an assembly it causes classes derived in **another** library to break even through **it does not, directly or indirectly, derive off the interface in any way**. There is no public api change! Not only that, but it fails with a very strange error. See: https://github.com/jabbera/InterfaceBug for a demo in 4.7 and https://github.com/jabbera/InterfaceBug/tree/dotnetcore for a core 2.0 demo.

You can clearly see that: [ITroubleInterface](https://github.com/jabbera/InterfaceBug/blob/dotnetcore/BaseClasses/ITroubleInterface.cs) is internal and is only implemented by: [TroubleClass](https://github.com/jabbera/InterfaceBug/blob/dotnetcore/BaseClasses/TroubleClass.cs) which is also internal. The assembly does not expose internals. 

Note: [ITroubleInterface](https://github.com/jabbera/InterfaceBug/blob/dotnetcore/BaseClasses/ITroubleInterface.cs) is not Implemented by [TestBase](https://github.com/jabbera/InterfaceBug/blob/dotnetcore/BaseClasses/TestBase.cs)

In my derived assembly there is a class [UnrelatedClass](https://github.com/jabbera/InterfaceBug/blob/dotnetcore/DerivedClasses/UnrelatedClass.cs) that derives from [TestBase](https://github.com/jabbera/InterfaceBug/blob/dotnetcore/BaseClasses/TestBase.cs) Note again: This does not implement [ITroubleInterface](https://github.com/jabbera/InterfaceBug/blob/dotnetcore/BaseClasses/ITroubleInterface.cs). It does however have another interface [IUnrelatedInterface](https://github.com/jabbera/InterfaceBug/blob/dotnetcore/DerivedClasses/IUnrelatedInterface.cs) that has a mirror property of [ITroubleInterface](https://github.com/jabbera/InterfaceBug/blob/dotnetcore/BaseClasses/ITroubleInterface.cs)

If I rebuild my base assembly but comment out the [IToubleInterface:QueryContext](https://github.com/jabbera/InterfaceBug/blob/dotnetcore/BaseClasses/ITroubleInterface.cs#L5) property, my [UnrelatedClass](https://github.com/jabbera/InterfaceBug/blob/dotnetcore/DerivedClasses/UnrelatedClass.cs) fails to load with the following exception

```
Unhandled Exception: System.TypeLoadException: Method 'get_QueryContext' in type 'DerivedClasses.UnrelatedClass' from assembly 'derivedclasses, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at ConsoleDriver.Program.Main()
```

This exception makes no sense. [UnrelatedClass](https://github.com/jabbera/InterfaceBug/blob/dotnetcore/DerivedClasses/UnrelatedClass.cs) clearly implements [IUnrelatedInterface:QueryContext](https://github.com/jabbera/InterfaceBug/blob/dotnetcore/DerivedClasses/IUnrelatedInterface.cs#L7) since it derives from [TestBase](https://github.com/jabbera/InterfaceBug/blob/dotnetcore/BaseClasses/TestBase.cs) which has an implementation [here](https://github.com/jabbera/InterfaceBug/blob/dotnetcore/BaseClasses/TestBase.cs#L7).

My understanding is [this change](https://github.com/jabbera/InterfaceBug/blob/dotnetcore/BaseClasses/ITroubleInterface.cs#L5) should be ABI compatible. It certainly is source compatible as rebuilding my derived classes fixes the problem. I'm sure this has something to do with having duplicate interfaces with the same property, and that may seem like an anti-pattern, but this is part of a code generator so it's not as crazy as it sounds.

On a side note, if I comment out the property here: https://github.com/jabbera/InterfaceBug/blob/dotnetcore/DerivedClasses/IUnrelatedInterface.cs#L7 the app no longer breaks either way. Also renaming this to QueryContext1 and adding an implementation in the base class also avoids the issue.

Windows 7/10/2008 R2 .NET 4.6.2., 4.7, 4.5.2, core 2.0.0

I've reported this already here: https://github.com/Microsoft/dotnet/issues/457 under 4.7 only, but I'm hoping I can get some traction here?

**Comment by shanselman** [comment]
This is interesting @petermarcu

**Comment by Petermarcu** [comment]
@davidwrighton @fadimounir any thoughts?

**Comment by davidwrighton** [comment]
The issue here is a subtle one where the runtime is behaving as designed, but there is an unfortunate interaction with longstanding behavior of the C# compiler that can cause problems. Jared may be able to comment on future thoughts around problems like this. @jaredpar 

The binary breaking change difference between those two copies of baseclasses.dll is that the get_QueryContext method is changing from a virtual method to a non-virtual method. While this isn't being caused by a change in the source code of that method, it is affected by changing the set of 
interfaces that BaseClasses derives from. The root of this problem is a specification difference between C# and the specification of the .NET runtime.

1. The C# standard allows any public method to implicitly implement an interface method.
2. The CLI requires that all methods which implement interfaces must be virtual.
3. The C# compiler converts methods from public to public virtual sealed when it detects a conflict between those two rules.
4. With your change, code which previously had required the C# compiler to generate a sealed virtual method changed to generating only a non-virtual method.
5. Then the runtime was unable to find an implementation for the interface method ITroubleInterface.get_QueryContext in the derived class as the implementation it had previously relied upon had changed from virtual to non-virtual.

Solutions to this problem are quite awkward, and mostly involve building tools which examine the binary output of the compiler to ensure that breaking changes have not occurred at the binary level. The CoreFX repository may have tooling available which can do this. I am not certain, and don't actually know who to ask.

**Comment by jaredpar** [comment]
> The root of this problem is a specification difference between C# and the specification of the .NET runtime.

Correct. C#, as well as F# and VB.NET, have their own set of rules about how interface implementations are accomplished. None of the languages has a true 1:1 mapping with the CLI specification. 

> The CLI requires that all methods which implement interfaces must be virtual.

It's a little more specific than that. The type must specify it implements the interface **and** the method must be public virtual. This is important for class hierarchies. Simply deriving a new type and adding a public virtual method is not enough to implement an interface. This rule exists for CLI and C# (with the exception that methods don't need to be marked virtual). 

For the truly curious: [CLI Partition 2 Section 12.2](https://download.microsoft.com/download/D/C/1/DC1B219F-3B11-4A05-9DA3-2D0F98B20917/Partition%20II%20Metadata.doc) 

> The C# compiler converts methods from public to public virtual sealed when it detects a conflict between those two rules.

There are actually two cases where C# will alter / inject code in order to make a public non-virtual method satisfy the CLI rules for implementation. 

1. If the method is defined in source then C# will mark the method as sealed virtual. 
1. Else C# will generate an explicit interface implementation, that is virtual, which just calls the non-virtual definition. Generally referred to as a bridge method.

Note that (1) is true even if the method is defined on a type that doesn't implement the interface. That causes some other interesting effects. Consider:

``` C#
class Person { 
  public string GetName() => "Jared";
}
```

Is the method `GetName` defined here virtual or not? The answer is that you can't know unless you see all the rest of the code being compiled into the assembly. It's very possible a snippet like the following exists:

``` C#
interface IStudent { 
  string GetName();
}
class Student : Person, IStudent { }
```

If that snippet does exist then C# will happily mark Person.GetName as a sealed virtual method. That effect isn't really observable in C# but you can view it via IL tools like reflection. 

Getting back to the original report though

> Application should run fine. I've only modified an internal interface in a non derived class.

Chatted with a couple of team members and we believe this behavior isn't intended by the compiler. 

It's seemingly fairly straight forward to guard against as well. The compiler should never rely on the `sealed virtual` trick for implementing interfaces when it occurs across assembly boundaries. Instead we should generate a bridge method as it's more version resilient. 

Still need to dig around a bit more though. Interface implementation can be tricky and possible a subtle case we're missing.

**Comment by jabbera** [comment]
Thanks for the information!!! This is super interesting stuff. I've been looking for an answer to this since [January 2015 on connect](https://connect.microsoft.com/VisualStudio/feedback/details/1082073/removing-a-property-from-a-unrelated-interface-causes-type-load-exception). 

The breaking rules specify [adding an interface is explicitly allowed](https://github.com/dotnet/corefx/blame/master/Documentation/coding-guidelines/breaking-change-rules.md#L125). However making an [existing member virtual is not allowed](https://github.com/dotnet/corefx/blame/master/Documentation/coding-guidelines/breaking-change-rules.md#L180). Doesn't this mean that adding an interface off a derived class as described above with IStudent would be at odds with both of those rules? IE: It should be okay because an interface is being added, but under the hood it's making an old non-virtual method virtual. I can imagine the only reason this is okay is because the compiler is adding is both as virtual and as sealed so any previous calls using just a ```call``` instruction would continue to work fine? Some confirmation here would be great. 

As for resolving my issue. Aside from having all of my downstream consumers recompile if the guard option being suggested pans out, what are my options? I can't seem to add a sealed virtual signature as the compiler does not allow that. Adding virtual at the base class seems to work on the surface but in this case it sounds like this is actually removing the sealed keyword? That's got to be officially breaking (although I can "guarantee" that no one is overriding this as it's only being used from in house code generators). Any other ideas? 

Thanks for all of your help. I really appreciate it.

PS: The below quote is the scariest thing I've heard all year:-)

> Is the method GetName defined here virtual or not? The answer is that you can't know unless you see all the rest of the code being compiled into the assembly.

**Comment by jabbera** [comment]
Forgot to mention that a less complete version of this issue was already opened here. https://github.com/dotnet/roslyn/issues/21677

**Comment by richlander** [comment]
Have you been able to move forward with this issue?

**Comment by jabbera** [comment]
Not really. I’m still waiting on an answer to what my best course of action is. In the post above I’ve come up with two ideas only one of which is within my power to implement. I’m waiting for someone to tell me I can make the method virtual (thereby removing the sealed added by the compiler) and I won’t break backwards compatibility.

**Comment by jaredpar** [comment]
Making the method virtual is the best approach here.

**Comment by jabbera** [comment]
Thanks. I’m good then.
