### ISSUE TITLE
The change of priority of performance projects was imcomplete.

### ISSUE THREAD

**Issue by jorive** [dotnet/coreclr#13697]
https://github.com/dotnet/coreclr/pull/13411 changed the priority of the performance projects while the `perf.groovy` was not modified, and this translated into not running all the performance tests in the lab.

JitBench leg is broken
IlLink leg is broken
Not all CQ microbenchmarks are running

**Comment by jorive** [comment]
Can we revert the change of priorities in the performance projects? I feel they should all be PRIO=0

**Comment by jorive** [comment]
The @dotnet/rap-team might have different opinions here.

**Comment by pgavlin** [comment]
> perf.groovy was not modified, and this translated into not running all the performance tests in the lab.
>
> JitBench leg is broken
> IlLink leg is broken
> Not all CQ microbenchmarks are running
> ...
> I feel they should all be PRIO=0

Why? The Pri0 tests were chosen to better balance the chance of finding issues in the CI inner loop with the time spent building and executing tests in said inner loop. It may be expedient to make these tests Pri0 simply to unblock these legs, but if they are executed infrequently they could also just build the Pri1 tests.

**Comment by brianrob** [comment]
I don't think I fully understand how the test priority is used, so I can't comment on what a fix should be or if we even need one.  What I would like to do is state what our goals are as far as running performance tests, and then we can discuss how we make that happen.

Our goal is to make sure that all existing performance jobs (prior to this change) run, and that they run the full set of performance tests that they were running before.  That means that from the perspective of performance jobs, we don't care about priority, we just want to run all of the tests.

Based on @jorive's comments above, it sounds like there are a couple of broken test runs and some tests are now being skipped - so this is what we'd want to fix.

I can imagine that there is benefit to the functional test runs to specifying the priority of these tests, so I don't believe that it's absolutely required to change the priority back to 0, but I would ask what the right way to ignore priority on perf runs is so that the broken test runs above can be fixed, and they will run all perf tests regardless of priority.

**Comment by AndyAyersMS** [comment]
AFAIK priority controls which tests are built, and the runner doesn't know about priority and just runs all the tests it can find.

Both building and running are slow and I can understand wanting to pare this back some, but I agree we want to run the full set of current perf tests on each change.

Also historically perf tests have not been very robust at handling and reporting failure and there is some benefit to running these tests as correctness tests too, to ensure they're generally not broken and that if they do break there is a reasonable reporting mechanism. At least that's been my argument for why we run the jit perf tests as correctness tests too.

If perf tests running in correctness mode take too long, we can fix that.

**Comment by pgavlin** [comment]
@AndyAyersMS:

> AFAIK priority controls which tests are built, and the runner doesn't know about priority and just runs all the tests it can find.

This is correct.

> Both building and running are slow and I can understand wanting to pare this back some, but I agree we want to run the full set of current perf tests on each change.

When you say "on each change" do you mean "in inner loop CI" or "on every commit"? I certainly agree with the latter, but I'm not sure about the former.

@brianrob:

> I can imagine that there is benefit to the functional test runs to specifying the priority of these tests, so I don't believe that it's absolutely required to change the priority back to 0, but I would ask what the right way to ignore priority on perf runs is so that the broken test runs above can be fixed, and they will run all perf tests regardless of priority.

The most straightforward way to acheive this would be to change the perf jobs to build both the pri0 and pri1 tests. I can put together a PR if that sounds acceptable.

**Comment by AndyAyersMS** [comment]
If we defer running perf tests until some post-commit trigger fires them off, then the feedback loop for fixing broken perf tests gets longer and (historically at least) it takes us quite a while to realize things are broken and get a fix in place.

Running the perf tests up front per PR doesn't guarantee 100% uptime for perf tests but it will prevent some classes of errors. It seems to have worked well for the jit unit tests at least.

**Comment by pgavlin** [comment]
> Running the perf tests up front per PR doesn't guarantee 100% uptime for perf tests but it will prevent some classes of errors. It seems to have worked well for the jit unit tests at least.

That seems reasonable. FWIW, the only perf tests that would have been moved to Pri1 are those that have never failed in CI for a non-infrastructural reason.

**Comment by brianrob** [comment]
@AndyAyersMS, agreed that running the perf tests up front is a good thing.  That's why we run "perf correctness runs" right now for each PR to make sure that even though we aren't getting perf results, we know that the tests will run and that the infra won't be broken by the PR.  Soon, we'll replace these correctness runs for each PR with real perf runs on physical hardware.

In terms of running the tests themselves as functional tests under the functional harness vs. in perf/perf correctness test runs, I've not seen any difference in detection of failures (in practice so far), but that's just been my experience.  We should definitely do at least one.  We picked the perf correctness runs because they also test the harness and other infra mechanisms that validate the end-to-end flow.

From the latest status here, it looks like we're going with moving the tests back to priority 0.  Thanks @pgavlin.
