### ISSUE TITLE
Expected cordbee_wks debug build to output to Windows_NT.x64.Checked

### ISSUE THREAD

**Issue by kingces95** [dotnet/coreclr#13771]
Expected `cordbee_wks` `debug` build to output to `Windows_NT.x64.Debug` but actually outputs to `Windows_NT.x64.Checked`. Does anyone edit\build\debug debug builds from VS? The build instructions don't seem to have instructions about that loop using VS of any flavor and projects don't seem to be setup to support it. Is enabling that an up-for-grabs thing or am I missing something?

![image](https://user-images.githubusercontent.com/4120386/30010157-ba37154c-90fb-11e7-88d7-09c152b7b771.png)

**Comment by mikedn** [comment]
> Does anyone edit\build\debug debug builds from VS?

I do that all the time and it works just fine. It seems to me that you loaded the "checked" solution but did not switch the configuration to "checked". You are using the "debug" configuration which VS defaults to when loading a solution for the first time. This can be a bit annoying at times but once you switch to the proper configuration it works fine.

**Comment by kingces95** [comment]
@mikedn Ah, I see. Thanks. 

When I build `coreclr` the binary does not end up in the `\bin\Product\Windows_NT.x64.Debug\`. I'm trying to get it there so the work flow is as described in the console build instructions. Then I launch VS from the same command shell those instructions created. I also add the following to my solution so I can launch my test project directly from VS. It's what `devenv /debugexe` created. 

Is that what you do?

````
Project("{911E67C6-3D85-4FCE-B560-20A9C3E3FF48}") = "corerun", "corerun.exe", "{035A3532-43AE-4273-A358-2C378DDAD0F8}"
	ProjectSection(DebuggerProjectSystem) = preProject
		PortSupplier = 00000000-0000-0000-0000-000000000000
		Executable = c:\git\coreclr\bin\product\windows_nt.x64.debug\corerun.exe
		RemoteMachine = CHRISKING6D70
		StartingDirectory = C:\proj
		Arguments = C:\proj\bin\Debug\netcoreapp2.0\win7-x64\publish\proj.dll
		Environment = Default
		LaunchingEngine = 00000000-0000-0000-0000-000000000000
		UseLegacyDebugEngines = No
		LaunchSQLEngine = No
		AttachLaunchAction = No
	EndProjectSection
EndProject
````

**Comment by mikedn** [comment]
> When I build coreclr the binary does not end up in the \bin\Product\Windows_NT.x64.Debug\

The `INSTALL` project is supposed to copy binaries to the `Product` directory. You have to explicitly build `INSTALL` which will also build `coreclr` and everything else due to dependencies. Also note that `INSTALL` is excluded from build in the solution configuration so building the solution won't build `INSTALL`.

However, the last time I tried building `INSTALL` from VS it failed to work properly, it copied all binaries to the root of my D drive. I haven't figured out what's wrong with it and I don't use it anyway. 

I tend to use a little cmd script that copies the binaries I'm usually interested in (`clrjit.dll` and `clrjit.pdb`), compiles a little `test.cs` file that contains the code I want to test and then runs `corerun.exe`. If things don't work properly then I use the VS debugger using debug settings similar to the ones you have in your post.

If `INSTALL` works fine for you then you should be able to set it as "startup project" and change its debug settings to run `corerun.exe`.

**Comment by kingces95** [comment]
Ah, ok. Install isn't working for me either so I build from the console to binplace everything.
