### ISSUE TITLE
Can't convert c# List<List<int>> to RT type IVector<IVector<int>>

### ISSUE THREAD

**Issue by leishi1** [dotnet/coreclr#1396]
First I created a c++ WindowsRuntimeComponent project and defined a class like below:
`     public ref class Foo sealed`
`    {`
`    public:`
`		int Add1(IVector<IVector<int>^>^ v);`
`    };`

Then I added a c# UWP project, in MainPage's constructor if I call the RT API with
`var f = new WindowsRuntimeComponent1.Foo();`
`var l = new List<int> { 1,2,3};`
`var ll = new List<List<int>>() { l, l };`
`f.Add1(ll);`
I'll get a compile error:
cannot convert from `'System.Collections.Generic.List<System.Collections.Generic.List<int>>' to 'System.Collections.Generic.IList<System.Collections.Generic.IList<int>>'`

If I change the inner List to IList, it compiles/runs fine -
`var ll = new List<IList<int>>() { l, l };`

Expect no compile error for `List<List<int>>` in this case.

**Comment by Janiels** [comment]
The example would break type safety. Consider:
```cs
List<List<int>> test = ...;
IList<IList<int>> test2 = test;

test2.Add(new int[] { 1, 2, 3, 4 });
```
What is test.Last()? It is not a `List<int>`, since we added an int array (which also implement `IList<int>`).

The conversion you are looking for it only allowed if the interface uses T only in output positions (i.e. if it is covariant); this is the case for IEnumerable. Thus this conversion is actually allowed:
`IEnumerable<IEnumerable<int>> test3 = test;`

**Comment by RyanByi** [comment]
Closing this. @Janiels is correct. You can read more about variance here: https://msdn.microsoft.com/en-us/library/ee207183.aspx.
