### ISSUE TITLE
missing symbols in Linux perf report

### ISSUE THREAD

**Issue by sillyousu** [dotnet/coreclr#14186]
I'm profiling a dotnet core program on Centos with Linux perf.

Everything works fine except some unresolved symbols from `System.Private.CoreLib.dll` and `System.Net.Sockets.dll`.
Did I miss any instructions?

stack:
![pasted graphic](https://user-images.githubusercontent.com/1446131/30848017-33282ea6-a2d0-11e7-87e5-8bcf4cc0b949.png)

env info:
```bash
Linux localhost.localdomain 3.10.0-514.2.2.el7.x86_64 #1 SMP Tue Dec 6 23:06:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

```bash
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     centos
 OS Version:  7
 OS Platform: Linux
 RID:         centos.7-x64
 Base Path:   /home/sandbox/dotnet/sdk/2.0.0/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

**Comment by jkotas** [comment]
cc @brianrob

**Comment by brianrob** [comment]
@sillyousu, in order to get symbols for these assemblies, you will need to do a few things:

1. Copy crossgen into the same location as libcoreclr.so (inside the shared directory).  Crossgen is part of the CoreCLR nuget package.
2. Re-collect the trace.
3. Open the resulting trace file with PerfView (on Windows).  You can get it at https://github.com/Microsoft/perfview/releases.

The reason these assemblies are different is because they are pre-compiled and perf does not have support for pre-compiled code that is not in a native (ELF) format.  Thus, perf cannot natively resolve these symbols.

Hope this helps.

**Comment by sillyousu** [comment]
@brianrob 
> Crossgen is part of the CoreCLR nuget package.

Do you mean [runtime.linux-x64.Microsoft.NETCore.Runtime.CoreCLR ](https://www.nuget.org/packages/runtime.linux-x64.Microsoft.NETCore.Runtime.CoreCLR/) ?

**Comment by brianrob** [comment]
Yes.  If you extract the package you'll find crossgen in the tools directory.  If you put it next to libcoreclr.so and then re-run perfcollect that should do it.  Note that you must have the matching version of the package - crossgen strongly tied to libcoreclr.so.

**Comment by brianrob** [comment]
@sillyousu, I've updated perfcollect to warn you if crossgen is not present.  It will now direct you to instructions on how to resolve framework symbols.  #14194.

**Comment by sillyousu** [comment]
<img width="765" alt="perfview" src="https://user-images.githubusercontent.com/1446131/30910905-3233cf5c-a3b9-11e7-8874-71ba7cb42c8d.png">

**Comment by chlowell** [comment]
@brianrob I'm seeing similar results with the latest perfcollect, no warnings but framework symbols aren't resolved in the traces.

**Comment by brianrob** [comment]
@sillyousu can you please try this again with the latest coreclr and PerfView?  There were some bugs that @chlowell helped me to uncover which are now fixed.  Thanks.

**Comment by sillyousu** [comment]
Sure. I will do it in next few day.
