### ISSUE TITLE
Add GetBuffer method to System.Collections.Generic.List<T> 

### ISSUE THREAD

**Issue by Albeoris** [dotnet/coreclr#1426]
This method will be a convenient way for integration with an unsafe context and marshaling without unnecessary copying list items into the new array.

```CSharp
public virtual bool TryGetBuffer(out ArraySegment<T> buffer)
{
    T[] items = _items;
    if (ReferenceEquals(items, _emptyArray))
        items = new T[0];

    buffer = new ArraySegment<T>(items, 0, _size);
    return true;
}
```

**Comment by Albeoris** [comment]
Simplified mechanism, similar to an existing method System.IO.MemoryStream.GetBuffer()

**Comment by omariom** [comment]
MemoryStream.GetBuffer() is a bad example. Since .NET 1.0 I saw numerous times it was used incorrectly. Even  in [BCL itself](http://referencesource.microsoft.com/#System.Data/System/Data/DataSet.cs,299).

**Comment by Albeoris** [comment]
Yes, you are right. Corrected.

**Comment by stas-sultanov** [comment]
Bad idea,
what would happen when `List<T>.Add(T item)` will cause internall buffer to be replaced with bigger one?

**Comment by ayende** [comment]
The same thing that happens today with MemoryStream under the same
condition.

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by stas-sultanov** [comment]
Before using a MemoryStream as an example, i suggest You to get know how exactly it does work.
GetBuffer() might be used to get underlying buffer, only if MemoryStream was constructed using explicit reference to the byte array. As a fact GetBuffer() just return the bare same ref and nothing more.
In other case method will throw UnauthorizedAccessException

**Comment by Albeoris** [comment]
I agree with ayende. This is not an enumerator that is often used. There is no need to protect the man from the shot oneself in the foot. He knows that using and why.

**Comment by Albeoris** [comment]
You're wrong:
```C#
    public MemoryStream(int capacity)
    {
...
      this._exposable = true; // Is exposable 
...

    public virtual byte[] GetBuffer()
    {
      if (!this._exposable)
        throw new UnauthorizedAccessException(Environment.GetResourceString("UnauthorizedAccess_MemStreamBuffer"));
      return this._buffer; // Is available
    }
```

**Comment by ayende** [comment]
That isn't the case, see the docs:
https://msdn.microsoft.com/en-us/library/system.io.memorystream.getbuffer(v=vs.110).aspx

To create a MemoryStream instance with a publicly visible buffer, use
> MemoryStream
> <https://msdn.microsoft.com/en-us/library/system.io.memorystream.memorystream(v=vs.110).aspx>
> ,MemoryStream(Byte[], Int32, Int32, Boolean, Boolean)
> <https://msdn.microsoft.com/en-us/library/7y0t45kk(v=vs.110).aspx>, or
> MemoryStream(Int32)
> <https://msdn.microsoft.com/en-us/library/bx3c0489(v=vs.110).aspx>. *If
> the current stream is resizable,* two calls to this method do not return
> the same array if the underlying byte array is resized between calls. For
> additional information, see Capacity
> <https://msdn.microsoft.com/en-us/library/system.io.memorystream.capacity(v=vs.110).aspx>
> .


In the code, you have this:
http://referencesource.microsoft.com/#mscorlib/system/io/memorystream.cs,70

So if you specify any capacity for the stream, you can get the buffer.
Note that the new MemoryStream() will call the new MemoryStream(0);

The only case where you _can't_ call GetBuffer() is if you passed your own
buffer, amusingly enough, and didn't explicitly authorized it.

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by stas-sultanov** [comment]
my bad,
however Getting underlying buffer of the `List` does not looks like a good idea
much better solution could be the following method.

```
public ArraySegment<T> Evict()
{
    var result = new ArraySegment<T>(_items, 0, _size);

   _items = _empteArray;
   _size = 0;

  return result;
}
```

**Comment by Albeoris** [comment]
1) Check for _items isn't equals to _empteArray befor return.
2) It is can be as the second way, but not a replacement of simple TryGetBuffer.

**Comment by ayende** [comment]
Why?
Consider this code:

     var list = new List<int>{ 1, 3, 5, 7);
     var sum = SumArrayUsingSSe(list.GetBuffer(), list.Count);
     list.Add(sum);

Why not allow this?


*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by omariom** [comment]
I needed once access to the underlying array. Without [Move or Copy methods in List](https://github.com/dotnet/coreclr/issues/1165) I had to do it myself. In what other scenarios  could one benefit from direct access to the storage?

**Comment by stas-sultanov** [comment]
@omariom,  it looks like guys wants to use underlying array for some interop methods

@Albeoris  it is better to check if _size == 0, cause there is no guaranty that _items was not modified before.

@ ayende because when getting underlying buffer you must guaranty that it's values will not be changed, because if you will look at the implementation of 'List<T>' you'll see the following

```
       public T this[int index] {
            set {
                if ((uint) index >= (uint)_size) {
                    ThrowHelper.ThrowArgumentOutOfRangeException();
                }
                Contract.EndContractBlock();
                _items[index] = value;
                _version++;
            }
        }
```
 
version is incremented on any change of the element

**Comment by JonHanna** [comment]
I think this purpose would be better served by a different class.

**Comment by Albeoris** [comment]
@stas-sultanov no matter, the main thing is not to return a static buffer because it can be changed by unsafe code (size or type of the elements).

**Comment by ianhays** [comment]
I agree with JonHanna that this is better suited as its own class. Opening up the internal array opens up a wide range of possible issues that I'd prefer to not unleash on a class as general as List<T>. That's not to say that I don't see the value of being able to get at the internal array, but I'm not convinced List is the place for it.

Issues off the top of my head (some of which have already been mentioned):
- Modifications to the internal array returned by GetBuffer will not update the version number of the List<T>. 
- Allows weird behavior around the size of the list. Say you get the internal array of a list with 2 items. That array may be 4 elements long, so you decide to put something at array[2]. But List doesn't know that element exists - it still thinks it only has 2 elements. When resizing occurs any values beyond the size will be lost. I can envision cases similar to this where confusion arises over how tied-in the array and the list are.
- Allows breaking of the enumeration unmodified-from-creation check
- Resizing the List will detach it from any returned arrays.

>This method will be a convenient way for integration with an unsafe context and marshaling without unnecessary copying list items into the new array.

Personally, I would rather see a separate List implementation with a constructor that takes in an array that it then wraps around. That would circumvent all of the issues mentioned because it would be built with the expectation that the internal array may be modified outside of the Collection.

**Comment by Albeoris** [comment]
>I think this purpose would be better served by a different class.
Unfortunately this will not work with existing and third-party solutions.
This will lead to reflection (as now).

>Personally, I would rather see a separate List implementation with a constructor that takes in an array that it then wraps around. That would circumvent all of the issues mentioned because it would be built with the expectation that the internal array may be modified outside of the Collection.
All these problems (except version) already exist in the MemoryStream.
The chance to initiate IndexOutOfRange when working with a list from the fixed-length array greater than the mistake when using GetBuffer. It is also a negative impact on memory usage (overprovision).

**Comment by JonHanna** [comment]
Those problems don't exist with `MemoryStream` because it is part of the documented behaviour of `MemoryStream` that its buffer can be accessed in that way. Opening up `List` in this way blows away most of the invariants that can be used to reason about its behaviour, and makes it a completely different class. If you want a completely different class, create a completely different class.
