### ISSUE TITLE
How to get stripped debug symbol for native binary ?

### ISSUE THREAD

**Issue by sillyousu** [dotnet/coreclr#14361]
eg libcoreclr.so:
```
$ objdump -t  libcoreclr.so

libcoreclr.so:     file format elf64-x86-64

SYMBOL TABLE:
no symbols
```

**Comment by janvorli** [comment]
If you are using the 2.0.0 release runtime, you can use the nuget packages with the stripped symbols on myget:
https://dotnet.myget.org/feed/dotnet-core/package/nuget/runtime.linux-x64.Microsoft.NETCore.Runtime.CoreCLR/2.0.0
There is a link to "Download symbols". It gets you a nuget package, which can be renamed to .zip and unzipped to get the symbol files. Please note that the unzip on Linux for some reason sets access rights wrong on the files, so that they are not accessible even for read, so you'd need to chmod them.

If you are using a preview version of the runtime downloaded from `https://github.com/dotnet/core-setup`, then there are links to tarballs with symbols on that page next to the corresponding runtime links.

**Comment by sillyousu** [comment]
@janvorli  Thank you for your detailed instruction.
