### ISSUE TITLE
Garbage collector doesn't release RAM

### ISSUE THREAD

**Issue by cicciopage** [dotnet/coreclr#14387]
I noted that my .net core 2.0 web app needs a lot of RAM. The query are complex I know, but what I don't understand is that the allocated RAM is cleaned after a **lot of time (minutes)** from my requests. So the allocated RAM grows up very soon, reaching the limit of application pool and the application pool has restarted pushing my logged user out. 
My hosting server is Smarterasp.net (premium plan). My database is MSSQL.

**Comment by swgillespie** [comment]
@cicciopage Can you provide some more information about your environment? These things would be helpful to provide:
* Your OS - flavor, version, architecture (e.g. Windows Server 2016 x86, Ubuntu 16.04 x64)
* Your machine - number of cores, amount of memory
* Your GC flavor - Server or Workstation GC
* Details on what's running your application pool - IIS? Docker? What's your memory recycle limit and how does it compare to how much memory your machine has?
* If using windows, an ETW trace using PerfView. I often use this command to troubleshoot performance issues (this collects GC ETW events):

```
PerfView.exe /GCCollectOnly /nogui /NoV2Rundown /NoNGENRundown /NoRundown /merge:true /zip:true collect
```

You can get started with PerfView [here](https://github.com/Microsoft/perfview) if you've never used it before.

It's difficult for us to provide guidance without this sort of information since the GC has a number of heuristics that will cause it to do very different things depending on the environment in which it is running.

**Comment by Maoni0** [comment]
@cicciopage haven't heard from you in a while. I will close the issue for now. if you still need help please re-open it.
