### ISSUE TITLE
Support unique nuget package ids for build options: x64/x86/arm debug/release

### ISSUE THREAD

**Issue by ww898** [dotnet/coreclr#1444]
And, as bonus, ability to generate all nuget packages into one directory.

**Comment by jkotas** [comment]
cc @ericstj

**Comment by ericstj** [comment]
Which packages is this talking about?  We already have unique packages per architecture and OS.

What is the scenario for debug/release?

/cc @chcosta

**Comment by ericstj** [comment]
http://myget.org/gallery/dotnet-core contains
```
runtime.win7-x86.Microsoft.NETCore.Runtime.CoreCLR 
runtime.win7-x64.Microsoft.NETCore.Runtime.CoreCLR 
runtime.win8-arm.Microsoft.NETCore.Runtime.CoreCLR
runtime.ubuntu.14.04-x64.Microsoft.NETCore.Runtime.CoreCLR
etc...
```

**Comment by ericstj** [comment]
Also /cc @dagood since Debug/Release would have additional publishing implications.

**Comment by dagood** [comment]
Thanks, I'm also wondering if this would mean we could combine http://myget.org/gallery/dotnet-core and http://myget.org/gallery/dotnet-core-rel. Currently their packages come out of different branches but are otherwise identical: naming them by their branch would let us keep them on the same feed. (I'm still not sure if it would be a net positive to keep them on the same feed, but it would be good to know if this issue is related.)

**Comment by ericstj** [comment]
@ww898 can correct me, but I think Debug/Release here is more about the flavor of the build itself (not "release" vs "dev" branch).  Debug bits are more useful for native components due to the heavy optimization done by c++ compiler in release bits.

**Comment by gkhanna79** [comment]
@ww898 Can you please elaborate on the scenario, given uponhttps://github.com/dotnet/coreclr/issues/1444#issuecomment-152256610?
