### ISSUE TITLE
Fix the Scalability problem in System.Threading.TimerQueueTimer

### ISSUE THREAD

**Issue by vancem** [dotnet/coreclr#14462]
There is a hot lock in System.Threading.TimerQueueTimer that shows up when people use alot of timeouts or Task.Delays.      Below is a simple program  that causes 10000 Tasks to be each delaying 5 seconds in 100 msec.  The program keeps 8 cores at 60% CPU and over half of that is in contention on the one lock in System.Threading.TimerQueueTimer (in the Change, Close and Fire methods)

Name
--
module coreclr <<coreclr!JIT_MonEnterWorker_InlineGetThread_GetThread_PatchLabel>>
+ system.private.corelib!TimerQueueTimer.Change
+ system.private.corelib!System.Threading.TimerQueueTimer.Close()
+ system.private.corelib!System.Threading.TimerQueueTimer.Fire()

Thus this lock can get hot (We have seen this in a variety of scenarios, mostly in cases where we have many CPUs (e.g 32 or 64), and thus have many outstanding delays.  

Note that we don't actually have  problem with the data structure (It is O(n) where every time a timer fires (but not when it is canceled)).  The problem is simply the scalability (the fact that we have one lock).  

```
using System;
using System.Threading.Tasks;

namespace TimerScalability
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Starting, running 10000 tasks that each delay 5 second 100 msec at a time.");
            Task[] tasks = new Task[10000];
            for(int i = 0; i < tasks.Length; i++)
                tasks[i] = Task.Factory.StartNew(TaskBody);

            Console.WriteLine("Waiting");
            Task.WhenAll(tasks).Wait();
            Console.WriteLine("Done");
        }


        static async Task TaskBody()
        {
            // Console.WriteLine("Task {0} Starting", Task.CurrentId);
            for (int i = 0; i < 50; i++)
                await Task.Delay(100);
            // Console.WriteLine("Task {0} Done", Task.CurrentId);
        }
    }
}
```

**Comment by vancem** [comment]
@stephentoub  @jkotas  @kouvel  @benaadams 

Note that if others have other scenarios besides the 'Task delay' scenario, we should mention them at the least and ideally have a small microbenchmark to see how bad it is.

We could change the timer to be heap rather than an unordered list, but it is not clear that what is important (that only matters if the time we currently spend in 'fire' adds up in some scenarios (you have many short-lived timers that do go off).  Right now that does not seem to be our problem.  (so please add it if you know of that scenario).

The fix for this is presumably something that cools the lock.  Either by using low lock techniques, or more simply by splitting the lock (e.g. making it per CPU (or at least more than 1)).    Making N queues is not so bad since Fire() is already an O(N) operation.   

Note that if Firing is an actual important feature, we need to think more carefully, about affinizing the dispatch CPU to prefer the CPU that the delay was scheduled on (at least review the scenarios), but for now I am assuming we can save that for another time.   

Thus the implementation to beat is simply to have NumProcs lists, prefer the one on your CPU when scheduling or canceling and use interlocks to update the 'nextToFire' value.

**Comment by benaadams** [comment]
Related issues:
* Lock convoy on TimerQueueTimer https://github.com/dotnet/coreclr/issues/13083
* Cancelled Task.Delay not scalable  https://github.com/dotnet/coreclr/issues/6155

I originally thought using the `PriorityQueue<T>` https://github.com/dotnet/corefx/issues/574 to this may be a solution to make Firing O(1)ish and queuing <= O(log n); but that's been more than 2 years in discussion so far, so maybe not :)

**Comment by benaadams** [comment]
Heap and Per core locks would be complimentary solutions and could be done seperately

Were you thinking to use [`Enviorment.CurrentExecutionId`](https://github.com/dotnet/coreclr/blob/8ecde0f47827e148c2d19ed07e163523b6f555e3/src/mscorlib/src/System/Environment.cs#L438-L449) as per [`TlsOverPerCoreLockedStacksArrayPool`](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/shared/System/Buffers/TlsOverPerCoreLockedStacksArrayPool.cs#L224-L254) to get the current core estimation?

**Comment by vancem** [comment]
> I originally thought using the PriorityQueue<T> dotnet/corefx#574 to this may be a solution to make Firing O(1)ish and queuing <= O(log n); but that's been more than 2 years in discussion so far, so maybe not :)

If someone shows me a clear real world case where we spend too much time in 'FireNextTimers, then we should just improve the data structure as you suggest.    It seems however that at least the more common problem is that we create and destroy timers (as timeouts), and form the hot lock (and Fixing the data structure won't help (and may hurt)).    

Having multiple timer queues with independent locks seems to be the solution for the hot lock.  We may end up doing both.

**Comment by vancem** [comment]
> Were you thinking to use Enviorment.CurrentExecutionId as per TlsOverPerCoreLockedStacksArrayPool to get the current core estimation?

Yes, that is the idea.   

As you say the two fixes are pretty independent.   We will do each part as needed.

**Comment by benaadams** [comment]
Lock contention would definitely be the first problem to solve; as you can't get to the `FireNextTimers` being an issue without getting passed creating the timers being an issue 😄 

My general approach to "things happening in X" is to have one timer or event loops, then have that check heaps of events rather than lots of timers. However that isn't a general solution for inbuilts like `Task.Delay` or `Cancellation` timeouts and probably isn't what a user would expect to be doing.

Proposal sounds good to me.

**Comment by stephentoub** [comment]
In my experience the comment at the beginning of Timer.cs is right, and creating/destroying timers is significantly more common than timers actually firing. This the lock contention for add/remove is the primary concern, and we should start just by partitioning to reduce lock contention.

**Comment by dudzcom** [comment]
Running into this issue for high frequency trading application.  Rewriting significant parts of the application to work around, however the solution is imperfect.  Would love to see a solution.

**Comment by benaadams** [comment]
@dudzcom resolved by https://github.com/dotnet/coreclr/pull/14527 ? (Core v 2.1)

**Comment by dudzcom** [comment]
Encountered this issue again with the same software.  It's a problem that continues to exist in 2019 when Task.Delay() is being fired by > 1000 tasks.  I forgot about this comment thread, and I was reading through the replies, and amazed to see my own comment here from more than a year ago.

**Comment by benaadams** [comment]
>  when Task.Delay() is being fired by > 1000 tasks
 
Concurrent/simultaneous firing vs number of timers? 

2.1 should have improved the number of timers (creation and destruction) with https://github.com/dotnet/coreclr/pull/14527

3.0 should improve timer firing when there are large numbers of timers with https://github.com/dotnet/coreclr/pull/20302

If https://github.com/dotnet/coreclr/pull/20302 in 3.0 doesn't resolve your issue; I'd recommend opening a new coreclr issue with a short repo demonstrating it so it can be tracked and resolved.

**Comment by dudzcom** [comment]
I've solved the problem for myself, but this remains an outstanding issue with the .NET framework.

I have a screenshot of an application dump that I performed yesterday....

Details about the situation:
- .NET 4.7.2, C# 7.3, VS 2019
- About 2000-2500 tasks launched at various times via Task.Run() that are essentially infinitely-lived.  
- Most are launched with Task.Factory.StartNew([func], TaskCreationOptions.LongRunning);
- All are essentially independent, not synchronously firing.
- Most are constantly issuing short await Task.Delay(10) statements between doing a few microseconds of work.
- Occasionally, every few minutes... sometimes every 10 minutes the application which normally uses 10% CPU on a 32-core machine, jumps to 100% CPU usage, and maintains 100% usage for 60-100 seconds. <- THIS IS WHAT I HAD TO FIX.

I've solved this by writing a custom scheduler for repeated tasks, rather than trusting the .net scheduler anymore.  If anyone wants that code, let me know and I'll see what I can do about open-sourcing it.

Last night, I grabbed a application-dump during one of the incidents before restarting the software...
![TimerQueueTimer](https://user-images.githubusercontent.com/6777107/60390287-34eefb00-9aa1-11e9-8cf0-bed76391c03f.jpg)

**Comment by gizmoabhinav** [comment]
@dudzcom Can we have your workaround opensourced? Will be a great help to me and others facing this issue.

**Comment by kouvel** [comment]
@dudzcom, I'm not sure what would cause such high CPU usage from timers, but it's possible with a large number of repeating timers or if there's a leak. In .NET Framework there is an opt-in to use .NET Core's timer implementation containing the fixes mentioned above. See info about the fix for timers in https://support.microsoft.com/help/4527212, maybe you can try the fix and see if it helps.
