### ISSUE TITLE
API Proposal: generic Type variants

### ISSUE THREAD

**Issue by Horusiath** [dotnet/coreclr#14517]
## Motivation

A .NET `Type` class is often used to configure some of the system properties at runtime. However you may often find them lacking of static type safety features. This often leads to runtime checks like `typeof(T).IsAssignableFrom(configuredType)` that may end in runtime exceptions.

To show this better, lets talk on an example. Say, we have a library which allows to configure user-defined serializer for custom type via attribute like `UseSerializerAttribute(Type serializerType)`. Naturally we may expect that `serializerType` param should represent a type with a particular constraints i.e. implementing some sort of `ISerializer` interface. However, even thou this param will be specified by user at compile time and could be checked by the compiler, we cannot validate it until runtime.

## Proposal

**The idea here is to add a generic `Type<>` class, which inherits from original `Type`**, but can specify the type it's actually working on, which then can be used to make a static type checks. **`typeof(T)` could return a `Type<T>` instance, that would be covariant on T** and still inherit from `Type`.

This would allow to specify specialized parameters - like from the example above, `UserSerializerAttribute(Type<ISerializer> serializerType)` which could be used to detect any type param mismatches at compile time instead of runtime.

This should also allow to replace checks like `typeof(T).IsAssignableFrom(configuredType)` with simpler `configuredType is Type<T>`.

**Comment by mikedn** [comment]
> which inherits from original `Type`

That won't fly. There are internal types that inherit from `Type`, `RuntimeType` in particular. The instance you get from something like `typeof(string)` is actually a `RuntimeType`, not `Type`.

**Comment by svick** [comment]
[All API addition proposals belong to the CoreFX repo](https://github.com/dotnet/coreclr/blob/027180/Documentation/workflow/IssuesFeedbackEngagement.md), so this issue should be moved there.

---

My main issue with this is that I don't see any advantage of `UserSerializerAttribute(Type<ISerializer> serializerType)` over using generic parameter with constraints: `UserSerializerAttribute<TSerializer>() where TSerializer : ISerializer`. Do you see any advantages?

This proposal sounds very similar to Java's `Class<T>`. I believe Java needs that because of type erasure (so in Java, `UserSerializerAttribute<TSerializer>()` would not be able to access the equivalent of `typeof(TSerializer)`). But C# does not have generic type erasure, so this solution is not necessary.

**Comment by Joe4evr** [comment]
@svick The main problem with `UserSerializerAttribute<TSerializer>()` is that attributes can't be generic (at this time).

**Comment by svick** [comment]
@Joe4evr Then I think this proposal is a very big hammer for such a small nail, especially since https://github.com/dotnet/csharplang/issues/124 is a championed issue, so there's a decent chance it's going to be implemented.

**Comment by Joe4evr** [comment]
Yep, that's why I said "at this time", because I have the same use-case as here posted in that issue. ;)

**Comment by jkotas** [comment]
> Then I think this proposal is a very big hammer for such a small nail

Agree.
