### ISSUE TITLE
ARM64 BUILD BREAK: Assertion failed 'info->dstCount == (tree->OperIs(GT_LOCKADD) ? 0 : 1)'

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/coreclr#14539]
**Repro:**
build arm64 checked -toolset_dir <dir>

```
Assert failure(PID 6664 [0x00001a08], Thread: 1828 [0x0724]): Assertion failed 'info->dstCount == (tree->OperIs(GT_LOCKADD) ? 0 : 1)' in 'System.Threading.SpinLock:Exit():this' (IL size 37)

    File: c:\git\corecl2\src\jit\lsraarm64.cpp Line: 404
    Image: C:\git\corecl2\bin\Product\Windows_NT.arm64.Checked\x64\crossgen.exe
```

**Comment by RussKeldorph** [comment]
@CarolEidt @dotnet/jit-contrib @dotnet/arm64-contrib

**Comment by sdmaclea** [comment]
My local bisect info...
Exists on d5f7e467d0 
Did not exist on 5bf81284d08

**Comment by sdmaclea** [comment]
git bisect leads to this being introduced by #14350

**Comment by sdmaclea** [comment]
The assert could now be bogus.  
It was based on the old assumption that GT_LOCKADD never produced a value.
@CarolEidt Your commit has this comment indicates this may no longer be true:
```
    - Any node that can be assigned a register should return true for IsValue() (e.g. GT_LOCKADD).
```

**Comment by sdmaclea** [comment]
Producing an unused useless value will require an extra register allocation for `GT_LOCKADD`.  Probably will not impact performance significantly

**Comment by CarolEidt** [comment]
> Producing an unused useless value will require an extra register allocation for GT_LOCKADD. Probably will not impact performance significantly

So we should either have the type of `GT_LOCKADD` by `TYP_VOID` on ARM64, or define it to be `GTK_NOVALUE` on that target.

**Comment by sdmaclea** [comment]
> So we should either have the type of GT_LOCKADD by TYP_VOID on ARM64

Wasn't it TYP_VOID on all targets.  when I was writing the code, it was functionally equivalent to GT_XADD, except the result was not used.  Otherwise it is not clear to me why we have two nodes which do the same thing.

@CarolEidt Let me know if you are not planning on fixing this.  I can look at it.

**Comment by CarolEidt** [comment]
Interestingly, this code: https://github.com/dotnet/coreclr/blob/master/src/jit/gentree.cpp#L15294 is #ifdef'd out for arm64. I'm not sure why.

**Comment by sdmaclea** [comment]
I added the `#ifdef` because I needed the sizeof the pointer, which seems to be destroyed by that assignment.

Other codegen is using the addend to guess the sizeof the pointer.  On ARM64 it was not matching.

**Comment by CarolEidt** [comment]
> Other codegen is using the addend to guess the sizeof the pointer. On ARM64 it was not matching.

Why is it not matching? That's problematic if we don't want the `GT_LOCKADD` to define a register.

**Comment by sdmaclea** [comment]
This line is depending on the type of the node rather than the type of op2 in other code generators.

https://github.com/dotnet/coreclr/blob/6741b800cce8663f4fb9995f21398915c6c7397f/src/jit/codegenarm64.cpp#L2725 

> Why is it not matching? That's problematic if we don't want the GT_LOCKADD to define a register.

I'm not sure, it could be a function of the call signature for the intrinsic.  It is possible the importer should be changing the type of the constants.

The LOCKADD intrinsics are coming from two operand sizes in import (32/64).  I think the const addend was not that size, so the INS_ldaxr was not the correct instruction.  I could have supported INS_ldaxrh & INS_ldaxrb, but that felt wrong given the import conditions.

I wanted to use the sizeof the target of the op1 pointer, but I could find the info.  It looked like it was not in the tree.  For normal LS ops the node type carries that info.  So clearing the type for this store operation seemed wrong.  So I added the #ifdef.

I can add an assert and find the failing test/tests.

**Comment by danmosemsft** [comment]
@sdmaclea @RussKeldorph Is there a way to temporarily unblock the build meantime -- eg direct submit a change to comment out the assert? That way we can get a corelib built and into corefx, eg.,

**Comment by danmosemsft** [comment]
cc @stephentoub @ViktorHofer

**Comment by RussKeldorph** [comment]
@danmosemsft @CarolEidt will have to comment on whether there is a good option to unblock the build.  We could also back out the offending change, but that may not be without risk.

@CarolEidt, do you think your fix will be merged tonight?  If not, we should consider backing out #14350.

**Comment by CarolEidt** [comment]
> @CarolEidt, do you think your fix will be merged tonight? If not, we should consider backing out #14350.

I am hoping that it will be merged tonight. I think it would be better to disable the assert than to back out #14350.

I have verified that the arm64 cross Checked build succeeds with my fix.

**Comment by CarolEidt** [comment]
@dotnet/jit-contrib ping - it would be good to get this build break fixed today.
Also, FYI, I have opened #14557 because I think the implementation of the interlocked operations would be cleaner and less error-prone if they took an indirection as their op1.

**Comment by danmosemsft** [comment]
Thanks @CarolEidt !
