### ISSUE TITLE
Exception handling broken on CentOS

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#14581]
Many tests in CI are failing with:

```
terminate called after throwing an instance of 'PAL_SEHException'
               ./TestAPIs.sh: line 243:  9819 Aborted                 (core dumped) $_DebuggerFullPath "$CORE_ROOT/corerun" $ExePath $CLRTestExecutionArguments
               Expected: 100
               Actual: 134
```

**Comment by janvorli** [comment]
I guess that likely some of the EH functions in PAL marked with __attribute__((noinline) __attribute__((optnone)) got optimized / inlined due to the PGO.

**Comment by janvorli** [comment]
I was able to repro it locally in a centos 7 VM. I am looking into it to see what causes the trouble. It looks like it has broken even the software exceptions handling. Since it occurs on CentOS 7 only and not on other Linuxes, I wonder if our own build of clang 3.9 that we use there is resulting in this issue.

**Comment by janvorli** [comment]
So, the issue is that there is no unwind info for our function RtlpRaiseException, which is the one that throws exceptions in the runtime. The exception unwinder starts in __cxa_throw frame, then unwinds to our RtlpRaiseException that's next on the stack. Since there is no unwind info, the unwinder decides that it is an end of stack - and so no handler was found and the app aborts with unhandled exception message.
I don't know yet if the unwind info is missing for some functions only or for everything in libcoreclr.so.

**Comment by janvorli** [comment]
Ok, so it seems that with PGO enabled, it is missing almost all the EH info, See the "Size" column:
```
With PGO disabled:
Sections:
Idx Name          Size      VMA               LMA               File off  Algn
 16 .eh_frame_hdr 00020604  0000000000630b28  0000000000630b28  00630b28  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
 17 .eh_frame     0008c02c  0000000000651130  0000000000651130  00651130  2**3
                  CONTENTS, ALLOC, LOAD, READONLY, DATA

With PGO enabled:
Sections:
Idx Name          Size      VMA               LMA               File off  Algn
 17 .eh_frame     000003b0  00000000006c7518  00000000006c7518  006c7518  2**3
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
 18 .eh_frame_hdr 000000cc  00000000006c78c8  00000000006c78c8  006c78c8  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA

```

**Comment by janvorli** [comment]
@adiaaida - since the issue is clearly related to the PGO, could you please revert the change #14554 that has re-enabled PGO until we figure out why the clang 3.9 compiler that we build ourselves is misbehaving? Otherwise I believe all official builds will be broken (and the lab tests will be failing) since we build them all with this clang 3.9 compiler on CentOS 7.

**Comment by adiaaida** [comment]
I can, yes.

**Comment by adiaaida** [comment]
Also note that the changes to revert #14554 isn't going to change anything for official builds. It only applies to ci builds/testing.

**Comment by benaadams** [comment]
https://github.com/dotnet/coreclr/pull/14622

**Comment by benaadams** [comment]
Don't think its PGO, reversed for Centos, the reversed the whole PR and Centos still fails in the same way https://github.com/dotnet/coreclr/pull/14622

> 16:36:00                terminate called after throwing an instance of 'PAL_SEHException'

**Comment by jkotas** [comment]
The change was in the CI script. Changes in the CI scripts are not picked up for the PR that contains them ...

**Comment by benaadams** [comment]
> The change was in the CI script. Changes in the CI scripts are not picked up for the PR that contains them ...

:-o 

Well is a PR waiting then; can back out last commit that moved from Centos to all linuxes?

**Comment by jkotas** [comment]
Let's see whether the full revert will fix the problem. We can then tweak the conditions to be more specific.

**Comment by janvorli** [comment]
I've experimentally installed clang 3.9 from an unofficial source and the unwind info was present even with PGO enabled. So it is clearly a problem of how we build the clang 3.9 compiler for CentOS 7. I suspect the `LLVM_ENABLE_EH` build option that we don't explicitly set and it is set to false by default, but it is just a quick idea. I'm still looking into it.

**Comment by janvorli** [comment]
That was a red herring. The clang 3.9 I got from the unofficial source doesn't support PGO and so that's the reason why it "worked".
But I have finally found the real reason. The ld.gold linker version installed on the CentOS 7 was outdated. Updating it fixed the problem. So I will update the CentOS 7 docker image to fix the issue.

**Comment by janvorli** [comment]
@mikem8361, @mmitche we need to update the binutils on the CentOS 7.1 that we use for building coreclr in CI. I have first thought we use the docker image I have created, but that one seems to already have the more recent binutils 2.25.1 that work fine. So I assume that we are using a CentOS 7.1 VM in the CI, right?

**Comment by mmitche** [comment]
@janvorli Not for coreclr.  For corefx, the docker container is used.

**Comment by mikem8361** [comment]
Point me at a Centos 7.1 VM and I’ll update it.

**Comment by mikem8361** [comment]
@janvorli, I did a "yum install binutils.x86_64" which installed version "2.25.1-32.base.el7_4.1". Is that good enough?

**Comment by janvorli** [comment]
@mikem8361 thank you! Yes, that's enough.

**Comment by janvorli** [comment]
@adiaaida it seems we can enable the PGO now, the CentOS 7 issue should be gone after @mikem8361 updated the binutils on the build VM.

**Comment by adiaaida** [comment]
Pgo has been reenabled.
