### ISSUE TITLE
[RyuJIT/arm64] Determine treatment of special regs

### ISSUE THREAD

**Issue by CarolEidt** [dotnet/coreclr#14607]
Issue #14591 was caused by an inconsistency in the register sets used by LSRA. In particular, the "special" registers IP0, IP1, PR, FP, andLR. In PR #14606 I have added IP0 and IP1 to the set of registers in `REG_VAR_ORDER`, and excluded the others in `availableIntRegs`. This needs to be revisited by someone more intimately familiar with the ABI to ensure that this is the correct treatment.

**Comment by sdmaclea** [comment]
The ABI suggests the platform independent code should treat the platform register as if it does not exist.  

It is therefore not included in `RBM_ALLINT`  and should not be in the VAR ORDER.

**Comment by sdmaclea** [comment]
`IP0` and `IP1` are intended to be used by to help linkers.  They are allowed to be trashed by any call or linkage branch, but are otherwise treated as temporaries.  

The CoreCLR arm64 assembly sometimes use these registers without preserving them.  GCWriteBarrier for instance.  I would hesitate before allowing them to be allocated w/o understanding the allocator lifetime rules.  They are in the CALLEE_TRASH list so it should be OK to use them.

However the trampolines would freely use these.  So expect calls to JIT helpers to trash these.

If you want to be able to allocate these they may also both need to be added to RBM_CALLEE_TRASH_NOGC, because the long jump to the the routine could trash either.

**Comment by sdmaclea** [comment]
LR is the link return register.  It is trashed by the `bl` branch and link assembly instruction.  It needs to be caller preserved so caller can return to its parent.

arm32 includes it in var order., but It is best to keep it as the LR register to simplify debugging.  Or it could be added to the end of the order.

**Comment by sdmaclea** [comment]
FP is not included in ALLINT.  It is preserved by the callee.  But lsra should never allocate

**Comment by CarolEidt** [comment]
@sdmaclea also commented on #14606:
> Given the current definition of RBM_CALLEE_TRASH_NOGC it seems VAR ORDER should be
CALLEE_TRASH & ~ CALLEE_TRASH_NOGC
CALLEE_TRASH_NOGC
RBM_CALLEE_SAVED

**Comment by sdmaclea** [comment]
`emit_R_S()` & `emit_S_R()` definitely use `IP1` (reserved register) when the frame size exceeds the range of the immediate encoding within the the LD/ST immediate forms.

These are not reserved via LSRA.
