### ISSUE TITLE
[Jit x86] Strange property inlining (Desktop CLR v4.7.2053.00)

### ISSUE THREAD

**Issue by benaadams** [dotnet/coreclr#14615]
Moving the property `Value` below the method `RaiseValue` stops it being inlined

Live example available on [sharplab.io](https://sharplab.io/#v2:C4LghgzgtgPglgO2AUwE4LAGwAQAEBM2AsssABYD2AJgELKYUDuAsAFADeb232ADqnABuYFNioUArgCNMybAH1hmCcgDcbLj1wBmYqUq16TABTjps7EoCUm7p1Y9H2cnAgA6AGpYV2ALyWsdQceAF8NYO4dMUkZOS9lZFtseyceAHNSPwA+BSUVINTuCEzfHMVvOX88tSSw1iSo3AAWbAAlMFdkeJVTGIteNABjZCQwDJsI5KTHF3duuQBqf3nsACpsYwHUYdGM7AB6bABGAAYTqwLQtjq2RBR0LDxCEnJqAEEpCkFEjiT+IREcjMsVyFSCDV0LwMHy+yF65jk1iSKUKs08FT8AUwl24N0mjRa7U683hIK2O2AY2QE0cKNSaJWS2wK3WmyGI0pe0Op3OOOweMcUWBFnmyOm6RKZWqfMcxWA2VBCUx0tq1zYQA===)

Program
```csharp
internal class MethodBelow
{
    private double _value;

    public MethodBelow(double val)
    {
        this.Value = val;
    }

    public double Value
    {
        get => _value;
        set => _value = value;
    }

    public void RaiseValue(double percentage)
    {
        this.Value += Value * (percentage / 100);
    }
}

internal class MethodAbove
{
    private double _value;

    public MethodAbove(double val)
    {
        this.Value = val;
    }

    public void RaiseValue(double percentage)
    {
        this.Value += Value * (percentage / 100);
    }

    public double Value
    {
        get => _value;
        set => _value = value;
    }
}
```
Output
```asm
MethodAbove.RaiseValue(Double)
    L0000: fld qword [ecx+0x4]
    L0003: fld st0
    L0005: fld qword [esp+0x4]
    L0009: fdiv dword [0x1b3126cc]
    L000f: fmulp st1, st0
    L0011: faddp st1, st0
    L0013: fstp qword [ecx+0x4]
    L0016: ret 0x8

MethodBelow.RaiseValue(Double)
    L0000: push ebp
    L0001: mov ebp, esp
    L0003: push esi
    L0004: sub esp, 0x8
    L0007: mov esi, ecx
    L0009: mov ecx, esi
    L000b: call MethodBelow.get_Value()
    L0010: mov ecx, esi
    L0012: fstp qword [ebp-0xc]
    L0015: call MethodBelow.get_Value()
    L001a: fld qword [ebp-0xc]
    L001d: fld qword [ebp+0x8]
    L0020: fdiv dword [0x1b312678]
    L0026: fmulp st2, st0
    L0028: faddp st1, st0
    L002a: sub esp, 0x8
    L002d: fstp qword [esp]
    L0030: mov ecx, esi
    L0032: call MethodBelow.set_Value(Double)
    L0037: lea esp, [ebp-0x4]
    L003a: pop esi
    L003b: pop ebp
    L003c: ret 0x8
```

Noticed by @sonnemaf in https://github.com/szehetner/InliningAnalyzer/issues/2

**Comment by BruceForstall** [comment]
@dotnet/jit-contrib

**Comment by alexandrnikitin** [comment]
It seems it's not actual for the latest CoreCLR x86 and x64 (checked  85819d322a72636eb65128aa2e5dfedc8843e073). I got the following asm code for both classes:
```
G_M58179_IG01:
       55           push     ebp
       8BEC         mov      ebp, esp
       C5F877       vzeroupper 
       C4E17B104508 vmovsd   xmm0, qword ptr [ebp+08H]

G_M58179_IG02:
       C4E17B104904 vmovsd   xmm1, qword ptr [ecx+4]
       C4E17828D1   vmovaps  xmm2, xmm1
       C4E17B5E05580D2105 vdivsd   xmm0, qword ptr [@RWD00]
       C4E17359C8   vmulsd   xmm1, xmm0
       C4E17828C1   vmovaps  xmm0, xmm1
       C4E17B58C2   vaddsd   xmm0, xmm2
       C4E17B114104 vmovsd   qword ptr [ecx+4], xmm0

G_M58179_IG03:
       5D           pop      ebp
       C20800       ret      8
```
I posted full JIT Dumps of x86 and x64 [to this gist](https://gist.github.com/alexandrnikitin/2a1a8d345c68d6557330b186c0a326cb)

**Comment by AndyAyersMS** [comment]
First impression is that this is probably related to the use of `PrepareMethod` to force jitting. Let me dig in a bit more.

**Comment by AndyAyersMS** [comment]
Invoking `PrepareMethod` on a given method marks that method as not inlinable. So the results of jit codegen when using `PrepareMethod` are highly order-dependent. If you jit callees before callers, no inlining will happen; if you jit callers before callees, the jit will use its inlining heuristics.

Method enumeration order seen via reflection likely reflects declaration order or something similar, which is why reordering the methods in the source leads to jit codegen changes in this case.

`PrepareMethod` is a desktop-only feature that was intended to address a very specific problem (prejitting virtual call targets for preparing constrained execution regions). It was not intended to serve a general mechanism for jitting code. It has various quirks, this being one.

Unfortunately there is no reliable way of seeing what code the jit will generate for a method short of actually calling that method.

Prejitting via ngen or crossgen can provide a reasonable approximation for jit codegen. However, the code produced will be different in some key areas (class init, handle access, etc) and cross-assembly inlines may be inhibited.

FWIW some of this is what led the jit team to the development of [SuperPMI](../blob/master/src/ToolBox/superpmi/readme.txt), but that is a record-replay mechanism, and so one still needs to execute the code to get the initial recording.

**Comment by benaadams** [comment]
So its from the observation rather than what would happen at runtime?

**Comment by szehetner** [comment]
That's bad news for an analysis tool that can't actually run the code.

If I remember correctly ngen places the native assembly into the global Native Image Cache (which I wouldn't touch for that purpose) and crossgen is CoreCLR only. 

If I use PrepareMethod for a single method only, which would then always be the caller and guaranteed to be the first method jitted, I shouldn't hit this ordering issue, right? Are there any other issues with PrepareMethod that would somehow invalidate the observed inlining behaviour compared to jitting from a normal call?

**Comment by AndyAyersMS** [comment]
`PrepareMethod` tunnels down into the runtime, and the in runtime marks the method being prepared as noinline before invoking the jit. So it's an artifact of how `PrepareMethod` is implemented.

Why the method is marked this way by `PrepareMethod` is less obvious. There is this comment in the code. My guess is that in a CER, if we end up jitting, we prefer not to inline a method if it's already been jitted, to minimize the amount of resources the jit uses.
```C++
    // Prevent inlining of the root method (otherwise it's hard to tell where ThreadAbort exceptions should be delayed). Note that
    // MethodDesc::SetNotInline is thread safe.
    m_pRootMD->SetNotInline(true);
```

**Comment by AndyAyersMS** [comment]
@szehetner I don't know of any other downsides to `PrepareMethod` as far as jitted code is concerned, though there may be some.

A couple of thoughts on how you can get reasonable results:

First, if you're willing to do a two-pass algorithm you can prescan all method IL in your target method range and build up a call graph fragment for those methods. Then call `PrepareMethod` in a top-down fashion over the graph. The graph may contain cycles , so you may end up in a bind where there is no safe total order. If so, you should break ties, first perhaps ordering the tied methods by IL size since larger methods (more IL) are much less likely to be inlined, and then perhaps by something semi-stable like method name.

Second, you may be able to fake up argument values and call the methods via reflection in a try. The jit never looks at the actual argument values so whether or not the method runs to completion or blows up with an exception, you should get the same jit codegen. You might also need to try and bound the execution time somehow, in case your arg values lead to infinite loops or some such. This might be simpler than the first approach, if the exception traffic coming from these invocations is not visible to your end users.

**Comment by szehetner** [comment]
I would like to avoid calling the methods, as they could contain any number of unwanted side effects. E.g. a DeleteCurrentDirectory() helper method doesn't sound safe to invoke for analysis and the user may not even be aware that his code is executed.

The call graph sounds like a good compromise though. I anyway build such a graph from the jit ETW events, i could use that for a second pass in a new process or search the IL first. Although I should somehow warn the user that the result may be different than the runtime version if I encounter a cycle.

For now I think i will go with the single method approach and let the user select a method to be analysed instead of just doing the whole assembly. That is easier to implement and should cover the main use case of the tool, i.e. optimizing one or just a few methods on your hot path.

**Comment by weltkante** [comment]
Just a random thought: would it work to dynamically generate a method (via DynamicAssembly) which calls the to-be-analyzed method and then do `PrepareMethod` on that instead, to avoid marking the actual target method as no-inline?

**Comment by jkotas** [comment]
.NET Framework specific, not actionable in CoreCLR.
