### ISSUE TITLE
[RyuJIT/ARM32] Assertion failed '(op2 == idx) || (op2->gtEffectiveVal() == idx)'

### ISSUE THREAD

**Issue by YongseopKim** [dotnet/coreclr#14665]
tests
- System.Numerics.Vectors.Tests

env
```
export COMPlus_AltJit="*"
export COMPlus_AltJitNgen="*"
export COMPlus_ContinueOnAssert=0
export COMPlus_AltJitAssertOnNYI=1
```

```
Assert failure(PID 16637 [0x000040fd], Thread: 16650 [0x410a]): Assertion failed '(op2 == idx) || (op2->gtEffectiveVal() == idx)' in 'System.Numerics.Vector:Narrow(struct,struct):struct' (IL size 84)

    File: /home/dragon/dotnet/arm32-dotnet/coreclr/src/jit/gentree.cpp Line: 3954
    Image: /home/dragon/dotnet/arm32-dotnet/tmp/coreoverlay-ARM-CHE-REL-10241504/overlay/dotnet
```

**Comment by YongseopKim** [comment]
@BruceForstall could you assign this to me?

**Comment by BruceForstall** [comment]
@YongseopKim Have you investigated this yet? Do you expect to investigate soon?

**Comment by YongseopKim** [comment]
@BruceForstall Sorry for delaying. I've started something different work. Anyone can take this instead of me.

**Comment by CarolEidt** [comment]
I am unable to reproduce this in the arm altjit on Windows. When/if we are able to repro this, it would be good to get a sense of why not.

**Comment by BruceForstall** [comment]
It appears in a few recent Windows ARM native tests (run on 11/3):

https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm_cross_checked_windows_nt_jitstressregs1_prtest/5/
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm_cross_checked_windows_nt_jitstressregs4_prtest/6/
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm_cross_checked_windows_nt_jitstressregs8_prtest/5/

and I see the periodic trigger jobs failed this today:

https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm_cross_checked_windows_nt_jitstressregs8/7/

**Comment by CarolEidt** [comment]
What should have been obvious to me is that this is asserting in a method that is an intrinsic on x86/x64, so when running these tests with the altjit they are not compiled.
I was able to repro the failure with `COMPlus_FeatureSIMD=0`

**Comment by CarolEidt** [comment]
This assert is happening in `gtSetEvalOrder()` which is being called after a statement is remorphed following constant propagation. It calls `gtWalkOp()` 3 times, with different arguments, which marks inner nodes with `GTF_ADDRMODE_NO_CSE` and modifies its arguments. It has a function header that ends with:
```
 *  TODO-Cleanup: It is essentially impossible to determine
 *  what it is supposed to do, or to write a reasonable specification comment
 *  for it that describes what it is supposed to do. There are obviously some
 *  very specific tree patterns that it expects to see, but those are not documented.
 *  The fact that it writes back to its op1WB and op2WB arguments, and traverses
 *  down both op1 and op2 trees, but op2 is only related to op1 in the (!constOnly)
 *  case (which really seems like a bug) is very confusing.
```
Which doesn't inspire confidence, especially since it is an old-style C comment, so it must have been around a while.
What's happening is that we have two `ADD` nodes due to the transformation of `ADD(y,LSH(ADD(x,2),2))` into `ADD(y,ADD(LSH(x,2),8))` and `gtWalkOp` is returning the `LSH` as op2, which is unexpected.
I will continue to look into this, but if anyone has more familiarity with this code than I do, I'd appreciate your insight.

**Comment by BruceForstall** [comment]
😄 I wrote that comment in January 2012 -- so obviously _I_ don't like this function!

Did you see why arm32 is different from x86?

**Comment by CarolEidt** [comment]
> Did you see why arm32 is different from x86?

I haven't gone down that path yet, but I believe the issue is that `genCreateAddrMode()` does different things for ARM.

**Comment by CarolEidt** [comment]
It is indeed the fact that on x86, `genCreateAddrMode()` behaves differently. Specifically, it folds the adds into its virtual address mode. It doesn't do this on ARM because not all addressing modes are supported.
I think there are two ways to fix this:
1. Disable the morphing of LSH(ADD(x,2),2) into ADD(LSH(x,2),8) (the `GT_LSH` case in `fgMorphSmpOpOptional`), or
2. Try to fix `gtWalkOp()`.

I'm going to attempt option 2, as option 1 is just fixing the symptom not the cause, (i.e. I don't think that would guarantee that we don't have other similar tree patterns).

**Comment by BruceForstall** [comment]
These asserts are now showing up with the normal (non-stress) run for:
```
JIT\SIMD\VectorConvert_r\VectorConvert_r.cmd
JIT\SIMD\VectorConvert_ro\VectorConvert_ro.cmd
```

**Comment by BruceForstall** [comment]
These VectorConvert tests are now disabled (with https://github.com/dotnet/coreclr/pull/15013).

Please re-enable them (and verify they don't assert) before closing this bug.
