### ISSUE TITLE
Environment.CurrentDirectory,OSVersion,ProcessorCount does not work on Linux

### ISSUE THREAD

**Issue by linquize** [dotnet/coreclr#147]
Environment.CurrentDirectory, OSVersion, ProcessorCount work on Windows, but do not work on Linux.

**Comment by jkotas** [comment]
Environment.CurrentDirectory and other methods are not in the .NET Core contracts. It is expected that they do not work. They were moved to other places. E.g. System.IO.Directory.GetCurrentDirectory().

@weshaggard @AlexGhiondea I would be useful to get the sources for .NET Core contracts published in fxcore repo so that it is clear what the supported .NET Core public surface looks like. It does not even need to be hooked up with the build for now.

**Comment by weshaggard** [comment]
@linquize @jkotas Yes getting the contract source into the CoreFX repo is on our list I've created a issue https://github.com/dotnet/corefx/issues/701 tracking that work. However I think we can close this one.

**Comment by jeremysimmons** [comment]
@jkotas  where's the master rosetta stone to translate the old api to the .net core equivalent?

**Comment by jkotas** [comment]
http://github.com/microsoft/dotnet-apiport .  It generates reports like http://dotnet.github.io/port-to-core/Moq4_ApiPortabilityAnalysis.htm with the replacement APIs.

Most of these APIs are added back in .NET Core 2.0. https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/dogfooding.md has instruction for consuming nightly builds if it is an option for your project.
