### ISSUE TITLE
Issue in implementation of collection versioning

### ISSUE THREAD

**Issue by speshuric** [dotnet/coreclr#1473]
Several collection classes implement similar logic to catch changes of the underlying collection while Enumerator reads it. They are `System.Collections.Generic.List`, `System.Collections.BitArray` and other.
Simplified code looks like this:
```
public class Sample
    {
        private int version;
        private int[] data;
        public Sample() { version = 0; }
        public UpdateMethods()
        {
            SomeImplementation();
            version++;
        }
        public struct Enumerator
        {
            private Sample s;
            private int version;
            private int current;
            private int index;
            //... other methods
            public bool MoveNext()
            {
                if (version == s._version && index < s.data.Count)
                {
                    current = s.data[index];
                    index++;
                    return true;
                }
                ...
            }
        }
```
Documentaion of the class `List` warns:
> An enumerator remains valid as long as the collection remains unchanged. 
> If changes are made to the collection, such as adding, modifying, or deleting elements, 
> the enumerator is irrecoverably invalidated and its behavior is undefined.

Note some details:
* `version` is int32
* `version` changes deterministically

Current computer performance allows to pass 2^32 simple operations in 2-8 seconds or so. This leads to the possibility of change collection without enumerator invalidation. 

Example:

```
static void Repro()
{
    const int size = 10;
    var l = new List<int>(size);

    // just fill with some values
    for (int i = 0; i < size; i++) l.Add(i);

    // walk through the collection
    // expected, that collection does not change, or InvalidOperationException is throwed
    int countdown = size / 2;
    foreach (var v in l)
    {
        Console.WriteLine("Current value: {0}, size {1}", v, l.Count);
        countdown--;
        if (countdown == 0)
        {
            // here we break behavior

            uint breakingOpCount = size + 1; // how many "breaking operations" we will do
            uint limit = uint.MaxValue - breakingOpCount + 1; 
            for (; limit > 0; limit--)
            {
                l[0] = 42; // just any value
            }
            for (int i = 0; i < size; i++) l[i] = i + 1000;
            l.Add(42);
        }

    }

}
```
We can expect that output is:

```
Current value: 0, size 10
Current value: 1, size 10
Current value: 2, size 10
Current value: 3, size 10
Current value: 4, size 10
...and here is unhandled exception
```
In fact output is following  
```
Current value: 0, size 10
Current value: 1, size 10
Current value: 2, size 10
Current value: 3, size 10
Current value: 4, size 10
Current value: 1005, size 11
Current value: 1006, size 11
Current value: 1007, size 11
Current value: 1008, size 11
Current value: 1009, size 11
Current value: 42, size 11
```
The enumerator has not invalidated. Potentially this behavior can lead to security issues.

There are several ways to solve it:

1. Change type of `version` to `long` 
  * pros
    * simple to do
    * signature of classes public API does not change
    * fast in execution
  * cons
    * serialization can be affected 

2. Non-deterministic change of `version`
  * pros
    * serialization does not change
    * classes API does not change
  * cons
    * it can be difficult to make fast non-deterministic changes in some environments

3. Significantly reorganize implementation (can be discussed)
  * pros and cons are not clear at the moment

At the least this issue affects `System.Collections.BitArray`, `System.Collections.Generic.List`, `System.Collections.ArrayList`, `System.Collections.Stack`, `System.Collections.Generic.Dictionary`, `System.Collections.SortedList`, `System.Collections.Hashtable` (I could miss some of them)

**Comment by mikedn** [comment]
> Current computer performance allows to pass 2^32 simple operations in 2-8 seconds or so. This leads to the possibility of change collection without enumerator invalidation. 

Is this something that you encountered in practice or are you simply considering the possibility?

> The enumerator has not invalidated. Potentially this behavior can lead to security issues.

It's unlikely that this can lead to security issues. You'd need to pass the enumerator through a security boundary and expect that the receiving code will be prevented from using the enumerator if the collection changes. But it's very uncommon to pass enumerators around, pretty much everyone passes enumerables.

> Change type of  version  to  long - fast in execution

It isn't so fast on 32 bit architectures. It also increases the size of collection and enumerator objects.

**Comment by ayende** [comment]
Also, in order to trigger this issue, you'll need to have _exact_ number of
operations.
In things like lists, most operations are actually add/remove, and you'll
need to make close to 2 billions of them to have an effect.
Other things will happen first to change that.

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by speshuric** [comment]
to @mikedn
>Is this something that you encountered in practice or are you simply considering the possibility?
Shown example demonstrates that change collection without enumerator invalidation is possiblle

MSDN sais in the description of `IEnumerator` Interface:
> An enumerator remains valid as long as the collection remains unchanged. If changes are made to the collection, such as adding, modifying, or deleting elements, the enumerator is irrecoverably invalidated and the next call to MoveNext or Reset throws an InvalidOperationException. If the collection is modified between MoveNext and Current, Current returns the element that it is set to, even if the enumerator is already invalidated.

Current implementation of аlmost all .NET collections (core clr and core fx) does not follow this behavior (at the least in this synthetic case). Of course, I am aware that is almost impossible to get this case accidentally. But someone can do it intentionally (so that can be one of the steps to broken security). 

> It isn't so fast on 32 bit architectures

32 bit architecture does not mean that 64 bit arithmetic is slower than in 64 bit architecture (mmx presented in 1997 actually is 64 arithmetic). Usually it means that pointers are 64 bit. But I agree that some architectures can be affected more than modern x86/x64.

I'll try to make more representative example, but it can take a few days.

@ayende 

If you mean that we need number of previous operation then you are mistaken. We just need to do exact 2^32 ~ *4* billions of operations. If there is `foreach` then collection is relatively stable (otherwise `foreach` is worthless). If we can pause `foreach` for a few seconds then there is not a problem to do any reasonable exact number of operations.

**Comment by mikedn** [comment]
> MSDN sais in the description of  IEnumerator  Interface:

I know what the documentation says but as far as I'm concerned this behavior is nothing more than a developer aid to help find bugs. From this perspective the current implementation is IMO a reasonable compromise between effectiveness and performance.

> Of course, I am aware that is almost impossible to get this case accidentally. But someone can do it intentionally (so that can be one of the steps to broken security).

If you mean that someone can write such code intentionally then that has nothing to do with security. The same person can also use reflection or unsafe code to extract list elements that wouldn't otherwise be available via an invalidated enumerator.

If you mean that an attacker finds that an application contains such a bug and attempts to take advantage of it then that's more interesting but there's so many things that need to happen first that you'll likely have a hard time convincing anyone without a realistic example:
* Someone has to accidentally write code that uses an invalidated enumerator.
* The bug isn't discovered during testing either because no testing is done or because you're so unlucky that all the tests hit the "exactly 2^32 operations" case and fail to find the bug.
* The attacker has to be able to exactly control the number of collection operations that are performed. One more/less than 2^32 operations and the attack fails.
* The attacker has to find a way to take advantage of all this. That's not going to be easy as there are many cases where the collection modification won't actually affect the enumerator.

And even if all of the above happens it all revolves around the existing application bug. That bug may be a security bug but that doesn't make enumerator's failure to catch all invalidation cases a security bug as well.

If you take the stance that enumerators must detect all possible invalidations then you also must make all collections thread safe. Otherwise accidental use of a collection in a thread unsafe manner will have the same consequences.

> 32 bit architecture does not mean that 64 bit arithmetic is slower than in 64 bit architecture (mmx presented in 1997 actually is 64 arithmetic).

MMX doesn't do any 64 bit arithmetic, it only operates on packed 32/16/8 bit integers. SSE2 did add some instructions that can do 64 bit arithmetic on 32 bit architectures and I've yet to see a compiler using them. 32 bit architecture generally means that you have 32 bit registers and a 32 bit ALU. That generally leads to 64 bit operations being slower.

**Comment by ianhays** [comment]
>There are several ways to solve it:
>Change type of version to long
>Non-deterministic change of version
>Significantly reorganize implementation (can be discussed)

These are significant changes to be made to harden against such a specific scenario. As mikedn has mentioned, without a specific real-world example of how this could be used maliciously I can't imagine it has a large enough effect to justify the work involved in implementing it (as well as tradeoffs accepted in doing so).

It is an interesting edge case, though. I'm going to close this issue until we can find a better example of how it negatively impacts real-world use.
