### ISSUE TITLE
Allow enabling Globalization invarinat mode using environment variable

### ISSUE THREAD

**Issue by tarekgh** [dotnet/coreclr#14927]
Currently, we support enabling the globalization invariant mode through app config switch. we need to have a way to enable this globally to use it in the Alpine docker image. The way we are going to support that is by allowing enabling the mode through a global environment variable.

The way this will work is:

- if the application declared the app config switch ```System.Globalization.Invariant```, we'll honor that setting and will not read the environment variable
- if the app didn't declare the config switch we'll try to read the environment variable ```DOTNET_SYSTEM_GLOBALIZATION_INVARIANT``` and honor it if it is declared
- Otherwise, if the config switch nor the environment variable is declared, we'll assume the Invariant mode is off and the app required to run with full globalization and ICU would be required on Linux based platforms.

**Comment by Petermarcu** [comment]
Its still important that the application setting wins over the environment and a proper error is displayed if an application author explicitly said they do or don't want invariant mode. In the case that nothing was specified (which is the default case) then the environment should be able to select the default.

**Comment by tarekgh** [comment]
@Petermarcu I was thinking in a scenario if the app set the switch in the app with invalid value and in same time the environment variable is defined. in general, I agree with what you said the app settings should be superior to the environment variable.

**Comment by Petermarcu** [comment]
Sounds good. If the setting in the app is invalid, are you just going to treat it as unset? Error?

**Comment by tarekgh** [comment]
> Sounds good. If the setting in the app is invalid, are you just going to treat it as unset? Error?

That what I wanted to think more about it and that is why I  mentioned "More details will be added for how the environment variable is going to play with the app switch" in the issue description. 

I am inclining to not treat this as an error because I believe we didn't use to do that before for other switches. And instead will ignore this switch and have the environment variable win. The apps run into this case would see that wrong behavior right away and can fix the switch. I am open to any other suggestions if it is more logical.

**Comment by jkotas** [comment]
>  a way to enable this globally to use it in the Alpine docker image

If we expect this to be pretty much always set on Alpine Linux, why not make it the default on Alpine (and use the env variable to override the default)?

**Comment by tarekgh** [comment]
> If we expect this to be pretty much always set on Alpine Linux, why not make it the default on Alpine (and use the env variable to override the default)?

This will require detecting the OS/image during the runtime and force the behavior. if we are going to have environment variable anyway, why we don't just use that and set it by default to our Alpin image. I think this would be cleaner and easy to control moving forward.

**Comment by jkotas** [comment]
> This will require detecting the OS/image during the runtime and force the behavior.

No. Alpine is a special beast that we are producing a special build for. That special build can have the different default baked in.

> why we don't just use that and set it by default to our Alpin image

Because of it will work in *our* Alpine images only. It will not work for other folks Alpine images. It is a poor out-of-box experience. I hate "make it work" environment variables that has to be always set.

**Comment by tarekgh** [comment]
@jkotas I am preparing the support for the environment variable. I'll send a PR today. then I'll look at defaulting Alpine to the Invariant mode by default. 

@Petermarcu what you think about what @jkotas suggested?

**Comment by Petermarcu** [comment]
Our general instructions are that libicu is required and that people that want to run without libicu should specify that in their application. For applications that say they don't need libicu, they will work just fine without installing it. The conversation right now is more about what we put in our default containers for Alpine because it is more size focused distro. What we're saying is that for those images it may make sense to flip the default to be that apps that don't specify will run without libicu but only in containers where we have chosen to omit it. If they specify that they need it, we should fail in these containers even if the environment variable is set.

My hope is that the build we're doing for Alpine will turn into the build for all musl c based distros and not just be for Alpine.

**Comment by tarekgh** [comment]
@MichaelSimons This is merged now. Please try it and let me know if you have any issue with it or any question. 

@richlander do you want to update the Invariant Mode document to reflect the environment variable support too? I have updated this issue description to reflect how we behave. let me know if you have any question.

**Comment by MichaelSimons** [comment]
@tarekgh  - FYI, the changes need to flow to Core-Setup before they will be picked up by our Docker images.
