### ISSUE TITLE
Hosting, Cannot Reinitialize CLR after it has been shutdown

### ISSUE THREAD

**Issue by TheLastRar** [dotnet/coreclr#15119]
I'm writing a plugin for another program, In my plugin I'm using CoreCLR to call into a managed library.

My plugin can be unloaded and reloaded during the runtime, however CoreCLR dosen't support this yet, with the second call to coreclr_initialize raising the assert ``ASSERT [LOADER ] at /home/air/git/coreclr/src/pal/src/loader/module.cpp.862: Expression: exe_module.prev == nullptr``

This is using a self build of CoreCLR for Linux x86 Debug.

**Comment by janvorli** [comment]
@TheLastRar coreclr doesn't support reinitialization due to the same reason it doesn't support unloading of libcoreclr as mentioned here https://github.com/dotnet/coreclr/issues/12266#issuecomment-325029644.

**Comment by jkotas** [comment]
It would be nice to fail gracefully without asserting or crashing when somebody calls `coreclr_initialize` twice.

**Comment by janvorli** [comment]
I got back to check how we can prevent this issue, but it is strange - the failing code is executed only if the init_count is set to 0 in the `Initialize` function in pal.cpp. So multiple calls to PAL_Initialize are protected and if coreclr_shutdown is called, which leads to PAL_Shutdown call, the current process is shut down.
@TheLastRar what was the sequence of actions that lead to the assert you were seeing?

**Comment by TheLastRar** [comment]
The code that calls coreclr_initialize and coreclr_shutdown (along with any calls to managed code) is contained within a library/plugin. (the program using my plugin does not use coreclr directly)

The issue occurs when a program unloads and then reloads the plugin.

**Comment by TheLastRar** [comment]
Is that enough information for you to reproduce the issue?

**Comment by janvorli** [comment]
@TheLastRar 
As for the plugin - so if I understand you correctly, your app loads a plugin (a shared library) using dlopen that in turn loads libcoreclr.so using dlopen. Then it calls coreclr_initialize, executes some managed assembly, after that you execute coreclr_shutdown and unload the plugin?

And do you really call the coreclr_shutdown? It would be strange if you did, since it would cause the process to exit.

**Comment by TheLastRar** [comment]
A test case for plugin reloading is located here https://github.com/TheLastRar/CLR-DEV9/blob/master/CLR_EMBED_TEST/main.cpp

Which calls this function in the plugin https://github.com/TheLastRar/CLR-DEV9/blob/master/CLR_DEV9_LINUX/PSE.cpp#L57

Which calls LoadCoreCLR located here https://github.com/TheLastRar/CLR-DEV9/blob/master/CLR_DEV9_LINUX/PSE.cpp#L289

And then calls CloseCoreCLR https://github.com/TheLastRar/CLR-DEV9/blob/master/CLR_DEV9_LINUX/PSE.cpp#L407

The testcase does not call into any managed code as it only exists to test reloading issues.

At no point have I seen coreclr_shutdown close the native hosting application (I assume it would only shutdown execution of managed code), If it did I would consider it a bug.

**Comment by janvorli** [comment]
@TheLastRar ah, right, I've forgotten that the `PAL_Shutdown` that is called from the coreclr_shutdown implementation doesn't terminate the current process. 
Then it is clear why it fails in a bad manner. The PAL_Shutdown clears the init_count, so the PAL_Initialize thinks it is the first time initialization. I'll fix it to make sure that calls to coreclr_initialize after coreclr_shutdown was called always fail gracefully.

**Comment by janvorli** [comment]
I've created issue #16504 to track the issue.

**Comment by NextTurn** [comment]
Since CoreCLR can't be reinitialized, why I have to save the host handle and domain id returned by `coreclr_initialize` myself?

**Comment by janvorli** [comment]
@NextTurn the hosting API was created during the porting of CoreCLR to Unix and at that point, it was not clear yet that we won't support reinitialization and multiple domains. So I have followed the way the original Windows hosting API was working.
Given the current state, it is true that we could keep both the host handle and domain id inside the hosting interface implementation. Also, the domain id is useless now that support for multiple domains is completely removed from the runtime.
However, we would need to create a new version of the hosting API if we wanted to remove these parameters so that we won't break existing users of the hosting API. I am not sure if it is worth it.
