### ISSUE TITLE
RedisTimeoutException on Linux related to threadpool

### ISSUE THREAD

**Issue by jeremymeng** [dotnet/coreclr#15148]
@kouvel did some investigation in an offline email thread.  This is likely due to the lack of IO completion ports on Linux so the response of an async request is handled in a thread pool work thread. However, when all thread pool worker threads are busy, it could take 500-1000ms for a new thread to be added to handle the response => Redis library throws timeout.

@kouvel has ideas for potential improvements.

Repro:
```
git clone https://github.com/jeremymeng/redis-timeout.git
cd redis-timeout
dotnet restore -s .
dotnet run -f netcoreapp2.0 some-valid-redis-server-endpoint 20
```
Code works fine on Windows, but throws RedisTimeoutExceptions on Linux.

**Comment by kouvel** [comment]
Closing in favor of https://github.com/dotnet/coreclr/issues/15232. The issue was that work running on thread pool worker threads was queuing and blocking on other thread pool work. Once all worker threads are used up with such work items, the dependency work cannot run until threads are added, which is very slow. It's only by chance that it works on Windows, as the async completions for the dependency work ran on thread pool I/O completion port threads, which aren't there on Unixes since there are no I/O completion ports. It was suggested to avoid blocking in thread pool worker threads by using async APIs or separate threads, and the issue above tracks reducing the negative impact in those cases. The best solution to this problem though for scalability is to use the async APIs.
