### ISSUE TITLE
RuntimeHelpers.PrepareDelegate/PrepareMethod should JIT the given method

### ISSUE THREAD

**Issue by tmds** [dotnet/coreclr#15522]
There is a comment here:

https://github.com/dotnet/coreclr/blob/b9affb49f79ed8319923c2f5b07b4aeeb04efe36/src/mscorlib/src/System/Runtime/CompilerServices/RuntimeHelpers.cs#L147-L149

But I can't figure out if it is supported or not.

In case it isn't supported, is there another way to ensure certain methods in a call graph are jitted? Or to jit a method without calling it?

**Comment by jkotas** [comment]
PrepareConstrainedRegions is no-op in .NET Core.

**Comment by jkotas** [comment]
> ensure certain methods in a call graph are jitted? 

There is not such method today. I think it may be reasonable to fix RuntimeHelpers.PrepareDelegate / PrepareMethod to JIT the method given to it (just the single method - without the complicated limited call-graph walk done by full .NET Framework implementation).

**Comment by 4creators** [comment]
> I think it may be reasonable to fix RuntimeHelpers.PrepareDelegate / PrepareMethod to JIT the method given to it (just the single method

This could be very useful for hardware intrinsics in R2R scenarios.

**Comment by jkotas** [comment]
@4creators Could you please elaborate why you think it would be helpful?

**Comment by 4creators** [comment]
@jkotas  maybe we can move discussion on how to use it in hardware intrinsics to #15427 as it will fit the scope of that issue

**Comment by mattwarren** [comment]
> I think it may be reasonable to fix RuntimeHelpers.PrepareDelegate / PrepareMethod to JIT the method given to it (just the single method - without the complicated limited call-graph walk done by full .NET Framework implementation).

Yes, this would be nice, based on [this comment](https://github.com/dotnet/coreclr/issues/14615#issuecomment-339097951) from @AndyAyersMS it currently has some limitations and [the workaround](https://github.com/dotnet/coreclr/issues/14615#issuecomment-339121183) is tricky. 

Although I assume from your comment that you're not proposing to also JIT the entire call-graph, just a single method, is that correct? 

Would `PrepareMethod` ever be extended to do this, i.e. ensure the entire call-graph of a method is also JITted, or is that not something you think the run-time should provide?

**Comment by jkotas** [comment]
> the entire call-graph, just a single method, is that correct?

The problem is with finding the entire call-graph is. Static non-virtual calls are easy, but the transitive closure can be very large. In full .NET Framework, this method also consults ReliabilityContract attributes to constraint the call graph to reasonable size.

Virtual calls, generics and every other runtime feature are hard. It would basically have to do same kind of global analysis as full AOT pre-compilation does (slow and complex).

We prefer to describe behavior in terms of what guarantees are provided. Not in terms of how the guarantees are implemented. The guarantees that the `PrepareMethod` provides in .NET Framework are that the runtime will not introduce exceptions in the part of the callgraph that is annotated as reliable (ie the only exceptions thrown during execution of the code are the ones caused by the user code). These guarantees have been implemented by JITing a bunch of stuff upfront and pre-initializing all sorts of other stuff that can lead to runtime-thrown exceptions. That implementation was not the only way to implement the guarantees.

This feature was originally implemented for SQL CLR. It was a super hard to test and use.

> it currently has some limitations

This applies to .NET Framework. 

My though above was that we can improve .NET Core compatibility for cases where folks take advantage of PrepareMethod side-effects in .NET Framework.

**Comment by tmds** [comment]
@jkotas I'm fine with this issue being closed or re-purposed to track support for `PrepareMethod`.

**Comment by jkotas** [comment]
> For my own edification, in what situations are these guarantees (JIT target only) valuable?

The side-effects of `RuntimeHelpers.PrepareMethod` are frequently used for custom implementations of background JIT. There are many articles out there about that:

https://stackoverflow.com/questions/26590809/disadvantages-of-runtimehelpers-preparemethod-in-a-windows-service
https://stackoverflow.com/questions/13435641/questions-about-pre-jit-ing-using-runtimehelpers-preparemethod

The JIT target only implementation is meant to make these kind of uses work. 

I do not think it make sense to try to bring CERs and the partial call-graph preparation to .NET Core. I think that killing the process is much simpler and more robust way to deal with hard to recover from errors. https://github.com/dotnet/coreclr/issues/15522#issuecomment-352031215 has some more context.

**Comment by tmds** [comment]
Thank you for implementing @jkotas!
