### ISSUE TITLE
[RyuJIT/arm32] ReadyToRun test failures

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#15552]
Newly added R2R test jobs in Jenkins show many failures.

e.g.:
1. Basic R2R run (pri-0; probably should be pri-1): https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm_cross_checked_windows_nt_r2r_tst_prtest/1/. 414 failures, 1526 pass.
2. R2R minopts, pri-1. https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm_cross_checked_windows_nt_r2r_jitminopts_tst_prtest/1/. 688 fail, 10492 pass.
3. R2R jitstress=1. https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm_cross_checked_windows_nt_r2r_jitstress1_tst_prtest/1/. 663 fail, 10517 pass.
4. R2R jitstress=2. https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm_cross_checked_windows_nt_r2r_jitstress2_tst_prtest/1/. 651 fail, 10529 pass.

A spot check of failures shows everything is an access violation.

**Comment by BruceForstall** [comment]
@dotnet/arm32-contrib

**Comment by BredPet** [comment]
@BruceForstall 
As I see, @sandreenko is already working on this. What progress? Maybe I can help?

**Comment by sandreenko** [comment]
@BredPet The issue happens when we have a call to R2R helper that is marked as 'IsDelayLoadHelper' and it also needs a null check.  The null-check is generated as a simple load of the call address and can be loaded on r4. At the same moment r4 is `REG_R2R_INDIRECT_PARAM` that must be kept alive until the call. Our IR doesn't reflect this calling convention. 

The fix is to add this `REG_R2R_INDIRECT_PARAM` as an additional argument for such calls, but it is not straightforward.

**Comment by BruceForstall** [comment]
@sandreenko Can you either (1) update this issue with the current status, if there are still many failures, or (2) close this issue and open individual issues for the remaining failures, if there are not too many?

Option (2) is preferable.

**Comment by sandreenko** [comment]
@BruceForstall Yes, I am planning to do it today or tomorrow.

**Comment by sandreenko** [comment]
The issue was cut into smaller issues:
#16589, #16587, #16573.
