### ISSUE TITLE
Q: Does Span<T>(new T[0]) work correctly?

### ISSUE THREAD

**Issue by mikedn** [dotnet/coreclr#15564]
This produces a byref that points to the end of the object. I think I read somewhere that GC doesn't like such pointers. Maybe I misunderstood but seems like it's worth a question because it's a rather unusual case.

**Comment by jkotas** [comment]
Byrefs like these are explicitly allowed in ECMA II.14.4.2 Managed pointers: "..., or the address where an element just past the end of an array would be stored (for pointer indexes into managed arrays).". They have been used in managed C++ for example.

A related issue is whether Span with zero length should be normalized. E.g. whether any two Spans of zero length should be equal, or whether Span should be a literal `<pointer, length>` pair – and two spans are equal only when both pointer and length are equal. It came up during early Span design discussions because of the original Span implementation was inconsistent – it normalized in some places, but not in others. The decision made was that zero length Spans should not be normalized (majority of people in the room felt that it is the right choice).

**Comment by mikedn** [comment]
Thanks for refreshing my memory! I now remember reading that ECMA section a long time ago...

The equality issue is interesting. Not normalizing does sound like the right choice, if only because you can't do much with an empty span anyway.

**Comment by mikedn** [comment]
> I think I read somewhere that GC doesn't like such pointers.

That somewhere is this comment: https://github.com/dotnet/coreclr/issues/4331#issuecomment-313179155

> To cite just one example: the CLRs GC currently cannot tolerate managed pointers that point off the end of objects.

It's possible that my English is failing me and "managed pointers that point off the end of objects" doesn't mean what I think it means.

**Comment by jkotas** [comment]
That comment is trying to say that it is not ok for the code generator to transform this:

```
int[] a = new a[16];

for (int i = -10; i < -5; i++)
{
    a[i + 20] = 42;
}
```

into this:

```
int[] a = new a[16];

ref int base = &a[20]; // this points into the middle of unrelated object

for (int i = -10; i < -5; i++)
{
    base[i] = 42;
}
```

A similar transformation is fine in non-garbage collected languages, and C/C++ code generators will happily do this. (BTW: These are the same cases that tend to break with Boehm GC.)

It is not a problem of the GC itself. It is just a limitation of the current per-method GCInfo encoding. The current encoding does not have a way to describe base for a pointer. It was not needed so far. There is nothing fundamental preventing CLR GCInfo encoding from supporting it. It would be "just work" to add the base/derived paired reporting mechanism to the CLR GCInfo.
