### ISSUE TITLE
CI reporting two git revisions

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#15613]
@jashook @jkotas @weshaggard 
Recent builds have started reporting two git revisions 
`https://ci.dot.net/job/dotnet_coreclr/job/master/job/checked_windows_nt_bld/lastSuccessfulBuild/git/`
```
Build #20902 of Revision 5faf753afddb1fa26337f2a1d82a3f31f887782b (origin/master)
Build #20948 of Revision 8431239c35e118ab7733f16c07bc27c1f7ab0348 (refs/remotes/origin/master)
```
20902 was last one to report only a single revision (12/19/2017)
`https://ci.dot.net/job/dotnet_coreclr/job/master/job/checked_windows_nt_bld/20902/git/`
```
Build #20902 of Revision 5faf753afddb1fa26337f2a1d82a3f31f887782b (origin/master)
```

**Comment by sdmaclea** [comment]
@BruceForstall FYI

**Comment by BruceForstall** [comment]
@dotnet/dnceng @mmitche @RussKeldorph Anyone know what would cause this?

**Comment by mmitche** [comment]
It's because we changed the branch name to be specific so that */release/2.0.0 doesn't overlap between dev/release/2.0.0 and release/2.0.0.

I think you may be misunderstanding what this page is telling you.  It's saying that this job built two branches, refs/origin/master and origin/master.  This is not saying the build itself built two branches.  It's indicating the last hash built on origin/master was 5faf753afddb1fa26337f2a1d82a3f31f887782b and the last one on refs/remotes/origin/master was 8431239c35e118ab7733f16c07bc27c1f7ab0348.  Jenkins doesn't know that these branches are actually identical behind the scenes.  The actual built revision for this build is:

Revision: 845da035a50199f53ae805840c92845d0a3573c7
refs/remotes/origin/master

I think the other build revision will go away as the retention policy runs.

@sdmaclea How is this breaking things?  You're not parsing this page are you?

**Comment by sdmaclea** [comment]
> It's because we changed the branch name to be specific so that */release/2.0.0 doesn't overlap between dev/release/2.0.0 and release/2.0.0.

OK thanks.  Other unintentinal changes broke CI so that priority 1 tests were not building/running.  Just wanted to be sure this was intentional.

> I think you may be misunderstanding what this page is telling you

I think you are right.

> You're not parsing this page are you?

@mmitche I am parsing the git page to associate artifacts with a specific git revision.  I was looking for the old branch name.

**Comment by mmitche** [comment]
@sdmaclea There is a REST API.   Parsing the HTML is risky.

**Comment by sdmaclea** [comment]
@mmitche Switched to using the rest xml api.  Thanks.
