### ISSUE TITLE
Path.GetDirectoryName missing/excess quotation mark?

### ISSUE THREAD

**Issue by Budenniy** [dotnet/coreclr#15625]
Ran into an issue with System.IO.Path.GetDirectoryName(string path):
If 'path' is enclosed in (double) quotation marks, the result still contains quotation mark at 0 position, but no the trailing one.

Code:

```c#
using System;
using System.IO;

namespace Path_with_spaces
{
	class Program
	{
		static void Main(string[] args)
		{
			Console.WriteLine(Environment.CommandLine);
			Console.WriteLine(Path.GetDirectoryName(Environment.CommandLine));
		}
	}
}
```
Output:
```
C:\Development\Temp\Path with spaces>dotnet run
"C:\Development\Temp\Path with spaces\bin\Debug\netcoreapp2.0\Path with spaces.dll"
"C:\Development\Temp\Path with spaces\bin\Debug\netcoreapp2.0
```
Version: 
Assembly netstandard 2.0.0.0

Expected result: 
Either both or no quotation marks - or - an ArgumentException mentioning 'path' format not being supported.

Am I missing anything?

[edited by @danmosemsft for formatting only]

**Comment by jkotas** [comment]
cc @JeremyKuhne @pjanotti

**Comment by danmosemsft** [comment]
.NET Framework would throw for the "invalid character" so it never gets this far.

**Comment by JeremyKuhne** [comment]
Sorry that this didn't hit my radar- I was out when this was opened. This is by design- you'll need to strip the quotes yourself.

As @danmosemsft mentioned, this would throw in .NET Framework as we would check for "invalid" chars. In .NET Core this didn't as `"` is actually a valid wildcard character (along with `*`, `?`, `>`, `<`). .NET Framework only recognizes `*` and `?`.

In .NET Core 2.1 we no longer preemptively check characters anywhere as we can't know for sure if they are valid. You can see more on this here https://blogs.msdn.microsoft.com/jeremykuhne/2018/03/08/system-io-in-net-core-2-1-sneak-peek/. (You can have a Unix filesystem mounted where `"foo\bar\foo"` is the actual path. It is practically impossible for .NET to know this without actually trying to open the file.)
