### ISSUE TITLE
Provide a build switch to improve the inner loop experience

### ISSUE THREAD

**Issue by tannergooding** [dotnet/coreclr#15670]
Currently, `build.cmd` will build the product, build the tests, and create `CORE_ROOT` directory for running the tests.

There exists a switch for building just the product and a switch for building tests and creating the CORE_ROOT directory, but I cannot find a switch which will create the CORE_ROOT directory without building the tests as well.

I propose such a switch should be added. This would help cut down the inner loop time for the scenario where you are iterating on the product and have already built all the tests (which can still take a significant time for the "up-to-date" check, given the sheer number)

**Comment by mikedn** [comment]
Hmm, doesn't `runtest.cmd generatelayoutonly` do what you need? I use that all the time and it seems to work fine.

**Comment by tannergooding** [comment]
Ah, I expected a switch to exist in `build.cmd` or `build-test.cmd`. I'll try it out.

**Comment by AndyAyersMS** [comment]
AFAIK `GenerateLayoutOnly` only works after you've built the tests at least once. 

What I generally do to get a minimal setup going is something like the following (from repo root):
```
build.cmd x64 checked skiptests skipbuildpackages

run.cmd build -Project="tests\build.proj" -BuildOS=Windows_NT -BuildType=Checked -BuildArch=x64 -BatchRestorePackages

tests\runtest.cmd x64 checked GenerateLayoutOnly

;; build just the test cases of interest, eg
msbuild /p:Configuration=Checked tests\src\performance\Scenario\JitBench\JitBench.csproj
```
The package restoration is the only part of the test build you actually need for the layout.

Then to iterate on jit/vm/corelib development, after an edit, simply do:
```
build.cmd x64 checked skiptests skipbuildpackages

tests\runtest.cmd x64 checked GenerateLayoutOnly
```

**Comment by tannergooding** [comment]
`runtest.cmd generatelayoutonly` does eactly what I need (glad to know it exists now, thanks @mikedn).

It would be great if it was accessible from `build.cmd` and if it was better documented.

I think, ideally, the process should be:
* clone repo
* create feature branch
* run `build.cmd`
* make changes
* run `build.cmd skiptests generatelayout` (or something similar)

**Comment by mikedn** [comment]
> I think, ideally, the process should be:

Eh, the ideal process depends on who's working on what :smile:.

FWIW I do something about more involved, mostly because I tend to stick do doing JIT stuff and the JIT has special needs (jit diffs, throughput measurements etc.)

* I pretty much always run `build.cmd` in a clean and up to date `master`. In fact I have a `snap.cmd` script that runs `build.cmd -skiptests -nopgooptimize -skipbuildpackages` and `runtest.cmd generatelayoutonly` for x86/x64 and checked/release.
* The same `snap.cmd` script also create "snapshots" of some binaries - it copies clrjit.dll, coreclr.dll, corerun.exe and a few others to "base" directories (e.g. Windows_NT.x64.Checked_base)
* I start making JIT source code changes in VS. Due to the way git works I don't bother with creating a branch at this time, this can be done at a later time when I have a useful set of source changes.
* The changed JIT is pretty much always built in VS, building only the clrjit project is a bit faster then running build.cmd. It also ensures that no other binaries change.
* To test the changes I run a test.cmd script that replaces the clrjit.dll originally built by build.cmd with the one built by VS. Then it compiles a test.cs file containing whatever test code I have and uses corerun to run test.exe. This makes use of the directory created by `generatelayoutonly`. This script also sets `COMPLUS_JitDisasm` to Test so I put my test code in a method called Test and immediately get the disassembly output.
* The VS clrjit project is also setup to run `corerun test.exe` when you start debugging
* Likewise, the crossgen project is setup to run `crossgen IL\System.Private.CoreLib.dll`
* There's a `diff.cmd` script that runs jit-diff (using the clrjit.dll from the "base" directory)
* There are 2 other scripts that do JIT throughput measurements using PIN and ETW. These too use the clrjit.dll from the "base" directory (of release builds, of course). This is why I build master with `-nopgooptimize`, I can't update the PGO data after making changes so throughout measurements would not be comparable if PGO is used.
* Tests are built from time to time, as needed. Test build takes a long time and fortunately they don't change that often.

It probably sounds a bit exotic but it works pretty well for me. In particular, it's fast.

But everyone has a different idea in this area. If you find some of these ideas useful, good. If you have better ideas, that's good too.

**Comment by tannergooding** [comment]
I created a PR (https://github.com/dotnet/coreclr/pull/15673) so that you can specify `build.cmd skiptests generatelayout`.
