### ISSUE TITLE
#15596 Corrupted lsra.h linendings

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#15701]
@CarolEidt lsra.h linendings were changed to crlf by #15596

This is probably only an issue for Linux users.

**Comment by CarolEidt** [comment]
Now if only I could recall which system I was working on, so that I can fix my configuration ...

Thanks for noticing and fixing!

**Comment by sdmaclea** [comment]
I was wondering if the JIT formatting jobs could catch this

**Comment by CarolEidt** [comment]
@adiaaida - Could the JIT formatting jobs catch bad line-endings?

**Comment by tannergooding** [comment]
Why wasn't this caught by auto-normalization in the first place?

Users have a `core.autocrlf` setting, but this is overridden by the explicit setting in a `.gitattributes` file. The CoreCLR `.gitattributes` file is currently set to `* text=auto`, so files (by default) should be normalized to `\n` on checkin, provided they were not explicitly checked in otherwise.

**Comment by sdmaclea** [comment]
> Why wasn't this caught by auto-normalization in the first place?

Not clear.  Since this is the only time I saw the issue in the last year, maybe it is not worth worrying about.

**Comment by adiaaida** [comment]
@CarolEidt I can't exactly remember, but I think the jit formatting jobs only run on the cpp files.
