### ISSUE TITLE
[OSX] Clean up mach port interaction with lldb

### ISSUE THREAD

**Issue by kangaroo** [dotnet/coreclr#158]
Currently the mach ports don't play nice with lldb.  A breakpoint in libcoreclr.dylib will raise an identity exception, and is flagged as handled in IsHandledException, due to this check:

```
 1366     // Was the exception raised from within the CoreCLR binary itself?
 1367     if (IsWithinCoreCLR(ip))
 1368     {
 1369         NONPAL_TRACE("    IP (%p) is in CoreCLR.\n", ip);
 1370         return true;
 1371     }
 1372 
```

Does anyone know the history behind this?  It makes debugging the coreclr itself painful.  What specific regions in the shared object need to be handled by the machinery?  Is there a plan for debugging coreclr itself and not breaking future debugger integration with SOS?

I'm happy to do some of the work but I'd like to understand the current plan before taking a path orthogonal to the goals.

**Comment by kangaroo** [comment]
For the sake of others notes, changing the referenced return true; to return false; is not sufficient to appease lldb.  Considering coreclr only registers a thread port, and lldb supposedly registers a task port, you would think it would work.

The first breakpoint hit will succeed, but any subsequent step, or next will hang lldb and the target.  I haven't dug into that piece of this yet.

**Comment by jkotas** [comment]
We used to do the following to debug under gdb back in the Silverlight days:

export PAL_MachExceptionMode=2   This disables PAL handling of breakpoint exceptions, allowing GDB to use them transparently.  Otherwise GDB will appear to hang after continuing from a breakpoint. This means you will not be able to do managed debugging of the process (VS / MDbg) since this relies on the CLR being able to see the breakpoint exceptions.

or

gdb command "thread dont-suspend-while-stepping (on|off) (ThreadNum | -port Expression)" and to specify our Mach exception thread handler's thread number or port. "info thread" should list the threads. You can set a breakpoint on SEHExceptionThread in CoreCLR, and when it breaks, use "info thread" to get the thread number. Then our handler will not get suspended during single-step operations and we won't hang gdb. Not sure whether there is equivalent command in lldb.


I think it should be ok to change the default for PAL_MachExceptionMode to 2, at least for now, so that the debugging under lldb just works. Once we get to enable managed debugger, it would be nice to override the debug port only when it is really necessary.

**Comment by kangaroo** [comment]
@jkotas Thanks for the pointer, that at the least seems to work much better with LLDB, so I've submitted https://github.com/dotnet/coreclr/pull/160 until we can consider a managed debugger.

Once merged we can likely close this out until a managed debugger exists.
