### ISSUE TITLE
Windows7SP1 Fonts problem after installing Update for Microsoft .NET Framework 4.7.1 (KB4055002)

### ISSUE THREAD

**Issue by pavrosa** [dotnet/coreclr#15810]
After installing the update we are experiencing problems accessing System.Windows.Media.Fonts type:

    class Program
    {
        static void Main(string[] args)
        {
            try
            {
                var cnt = Fonts.SystemFontFamilies.Count;

                Console.WriteLine("ok");                
            }
            catch (Exception e)
            {
                Console.WriteLine(e); 
            }
            Console.ReadLine();
        }
    }

Uninstall of the update solves the problem.

**Comment by 0xd4d** [comment]
This is a bug in the update. The update removed Windows 7 SP1 support and it only supports Windows 8.1 and later.

`C:\Windows\Microsoft.NET\Framework\v4.0.30319\WPF\Fonts\GlobalUserInterface.COMPOSITEFONT` has been modified. Old one is 182KB, new one is 115KB. What changed? They removed WindowsXPSP2 support and replaced it with Windows8Point1 support (i.e., there's no Windows7SP1 support anymore).

**Comment by billwert** [comment]
Hi,
Thanks for the report. We're currently investigating and will have an update soon.

**Comment by daykun** [comment]
From what I have seen, this issue can be remediated by using the old C:\Windows\Microsoft.NET\Framework\v4.0.30319\WPF\Fonts\GlobalUserInterface.COMPOSITEFONT and C:\Windows\Microsoft.NET\Framework64\v4.0.30319\WPF\Fonts\GlobalUserInterface.COMPOSITEFONT from before the update.

Alternatively, a complete uninstall of KB4055002 will also work as the file has been changed by this update. Install KB4054183 instead.

Even Visual Studio 2010 will crash because of this bug if you start a WPF-Application (newer versions don't seem directly affected)

**Comment by RussKeldorph** [comment]
Please refer to dotnet/announcements#53 and/or Microsoft/dotnet#599 for more information.
