### ISSUE TITLE
Ubuntu x64 GCStress=C failure: ArrayWithThread_o

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#15886]
```
20:15:45                BEGIN EXECUTION
20:15:45                /mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_gcstress0xc_tst_prtest/bin/tests/Linux.x64.Checked/Tests/Core_Root/corerun ArrayWithThread_o.exe
20:15:45                Test 1 Failed
20:15:45                Test 2 Passed
20:15:45                Expected: 100
20:15:45                Actual: 1
20:15:45                END EXECUTION - FAILED
```

Seen:
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_ubuntu_gcstress0xc_tst_prtest/23/consoleText
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_ubuntu_gcstress0xc_jitstress1_tst_prtest/5/consoleText
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_ubuntu_gcstress0xc_jitstress2_tst_prtest/5/consoleText

**Comment by RussKeldorph** [comment]
@CarolEidt Can you take a look?

**Comment by CarolEidt** [comment]
This dies while executing `System.AppDomain:SetupDomain()`, and doesn't appear to hit any of the GC stress handling code, AFAICT (I set breakpoints on `OnGcCoverageInterrupt()` as well as `IsGcMarker()` and neither were hit. I tried setting breakpoints on general exception handling code, but may not have the right method.
It dies without the usual GC stress assert, and a relatively random sampling of tests that reference `System.Threading` in their source all fail in the same way - i.e. with `COMPlus_ZapDisable=1` they only JIT `System.AppDomain:SetupDomain()` and then die quietly with an error code of 1.
I strongly suspect some interaction between threading and GC stress.

**Comment by CarolEidt** [comment]
My previous post was based on attempting to run GC stress under Windows Subsystem for Linux - as it turns out, *all* GC stress tests fail under WSL.
Additional attempts to repro this were unsuccessful, and recent runs do not show this as failing:
- https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_ubuntu_gcstress0xc_flow/78/
- https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_ubuntu_gcstress0xc_jitstress1_flow/71/
- https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_ubuntu_gcstress0xc_jitstress2_flow/75/

So, I'm closing this.
