### ISSUE TITLE
"Plugin" style apps often need to recursively implement assembly load policies

### ISSUE THREAD

**Issue by agocke** [dotnet/coreclr#15982]
The problem is as follows: you write some shared framework .NET Core app and deploy it with `dotnet.exe`. You want to provide a plugin model where people can provide custom assemblies for you to load. Those assemblies will have their own dependencies. However, there's no mechanism to have a secondary, recursive *.deps.json for the plugin's dependencies. This means that every plugin is responsible for hooking assembly resolve and doing their own resolution, which gets overwhelmingly complicated very quickly.

CoreCLR should probably provide some functionality, perhaps in AssemblyLoadContext, to support recursive nesting of shared framework loading.

**Comment by jkotas** [comment]
`*.deps.json` handling is part of the runtime / CoreCLR. It is intentionally separate component from the runtime so that all policies involved in handling `*.deps.json` are in a central place and do not spread everywhere.

Have you looked at `Microsoft.Extensions.DependencyModel`? It is managed assembly to work with `*.deps.json`. I think it may be doing a lot of what you need to build your plugin scenarios. If it does not do what you need exactly, https://github.com/dotnet/core-setup repo where it lives is the place to open issues about it.

**Comment by jkotas** [comment]
> This means that every plugin is responsible for hooking assembly resolve and doing their own resolution

This is not how it should be. The provider of the plugin model should take care resolving the assemblies for the plugins. The individual plugins should not need to worry about it.

**Comment by swaroop-sridhar** [comment]
I discussed this bug with @agocke. Microsoft.Extensions.DependencyModel is the intended solution for this issue, so resolving this bug. If there's a problem with it, a bug can be filed in the core-setup repo.
