### ISSUE TITLE
ThreadPool.SetMinThreads() MIA

### ISSUE THREAD

**Issue by GuardRex** [dotnet/coreclr#1606]
Asked here originally by @tugberkugurlu: https://github.com/aspnet/Home/issues/614

According to @Daniel15, it should be in `System.Threading.ThreadPool` and I [see it in source](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Threading/ThreadPool.cs#L1375), but it's not available for some reason. I need it for my dnxcore50 project.
```
dnx-coreclr-win-x64.1.0.0-beta7
"System.Threading.ThreadPool": "4.0.10-beta-23302"
```

![capture](https://cloud.githubusercontent.com/assets/1622880/10037579/d24f4e2e-617d-11e5-8f3c-13d8c30b6fb7.PNG)

**Comment by ericeil** [comment]
Why do you need this in your project?

**Comment by GuardRex** [comment]
It's an experimental web server ... trying to stop the built-in algorithm from dropping below a minimum number of threads to speed things up when a spike of requests arrives. Is there any other way for me to do that from managed code?

**Comment by ericeil** [comment]
ASP.net may offer some configuration of this.  I know they did in previous versions, on the full CLR.

**Comment by ayende** [comment]
Eric,
SetMinThreads is useful if you have to start with a lot of work on the
thread pool.
The thread pool would increase the available threads, but too slowly at
startup.

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by Janiels** [comment]
The thread pool is only slow at starting new threads when it has already scheduled all CPU cores. Also the thread pool is supposed to be CPU bound - you should not block thread pool threads.
AFAIK, this is why it is so slow to start new threads - if you are using it as intended (for CPU bound work), then starting a new thread will not improve anything, as the new thread will just be competing with the rest of the threads for CPU time.

If you can refactor to the asynchronous pattern with the TPL then this will not be a problem. Easier said than done if you have a big system, though.

**Comment by ayende** [comment]
The problem is that I might have a set of sync tasks that do blocking I/O.
I want to have a lot of threads available for that, but the thread pool
increase them very slowly at start.

That isn't a good design, sure, but it is very common.

For example, in ASP.Net, calling sqlCommand.ExecuteReader() inside an async
controller is going to block. And if you have a lot of concurrent requests
at startup, they are going to effectively hang until the thread pool is
spawning enough threads.
And we can't change all the calls to ExecuteReaderAsync easily in big
codebases.

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by Janiels** [comment]
You're definitely right that the thread pool is slow at creating new threads - 1 second between each additional thread it starts, last I checked.

If this API exists it should be purely for compatibility purposes. Back in .NET 1.1 when there was no TPL, this API solved a real problem, but that problem is solved better today with the TPL. So it makes sense that it is not in the CoreCLR (a clean slate). But it would also be unfortunate if big systems migrate to the CoreCLR by creating their own thread pool classes to work around this, so maybe some kind of configuration switch is needed.

**Comment by ayende** [comment]
Anyone moving their code to the CoreCLR would need it, though.

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by zabulus** [comment]
Why don't use the LongRunning option for a blocking thread? It always starts a new thread.

**Comment by ayende** [comment]
I don't control that, this is done by ASP.Net.


*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by ayende** [comment]
I also don't want to do that, I just want to have a pool large enough

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811

**Comment by Janiels** [comment]
@ayende Just systems that have not updated to the TPL and that rely on this fact on start up. Fiddling with the thread pool has always been discouraged. This is just another motivator to switch to the even faster and better asynchronous design.

@zabulus Starting a new thread has a lot of overhead and takes a long time. It would not be feasible to do for each request coming into a web application. So you would have to manage your threads by yourself, but then you are just reimplementing the thread pool.

**Comment by davidfowl** [comment]
@ericeil Without this API (and I'm not saying we need it per se) ASP.NET can't set anything. We write code against the contracts as well.

**Comment by ericeil** [comment]
@davidfowl this would be done in the DNX native host; I believe CoreCLR has an API hosts can use to configure the thread pool.  For me, this is preferable to the managed API, for a couple of reasons:

1. This is a very CLR-ThreadPool-specific feature.  A runtime that does not use the CLR thread pool (such as .NET Native) may not be able to implement SetMinThreads.  The host knows exactly which runtime it's dealing with, so it's an appropriate place for runtime-specific decisions to be made.

2. This is a global setting, affecting the whole AppDomain (in this case, the whole process).  Host configuration seems like a better place to put global logic like this.

**Comment by davidfowl** [comment]
@ericeil Did we ever add this back? We're going to need a way to control this for server applications.

**Comment by gkhanna79** [comment]
@sergiy-k should comment on adding the support for it in the host/FX.

**Comment by sergiy-k** [comment]
Based on @ericeil comments, adding the SetMinThreads managed API does not seem to be an option because we will not be able to support it on top of the .NET Native runtime. 
So exposing this option through hosting APIs looks much more viable.

@kouvel, could you please take a look? There is also a similar issue in dotnet/cli: https://github.com/dotnet/cli/issues/889
