### ISSUE TITLE
EventPipe Metadata Produced By EventSource Can't Express Parameter Type GUID

### ISSUE THREAD

**Issue by brianrob** [dotnet/coreclr#16105]
When an event has a parameter of type GUID, the existing metadata blob is not capable of expressing it as GUID is not a valid TypeCode.

When EventSource writes to ETW, it uses a TypeCode of object, but the type name is written into the manifest which allows TraceEvent to override the TypeCode and read 16 bytes instead of treating it the parameter as an objectref.

If there's a nice way to solve this in TraceEvent, that would be preferrable, but I suspect that we may need to modify the metadata blob or add a new TypeCode (GUID).

I found this issue by collecting a trace for this app:  https://github.com/brianrob/tests/blob/master/managed/activityid/Program.cs.  Setting the activity ID causes the TplEtwProvider.SetActivityId event to be fired whose parameter is a GUID: https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Threading/Tasks/TPLETWProvider.cs#L524.

@vancem do you have an opinion on this?  Is there any reason that TypeCode can't be extended to include GUID?

**Comment by vancem** [comment]
I don't have a problem adding a TypeCode value (we don't actually own the TypeCode enum), for Guid (17 seems to be free).   Note that there may be a similar issue with IntPtr and UIntPtr.   We may wish to add typecodes for those as well.

**Comment by brianrob** [comment]
Yeah, I saw IntPtr has a workaround as well.

I will follow-up on whether or not we can modify TypeCode - it occurs to me that we'd really need to do this on desktop too to support TraceEvent and that's where things start to fall apart.  We may be better off using a different enum (cloning), but let me check first.

**Comment by vancem** [comment]
While it may be useful to simply change TypeCode, I don't think it is a big deal to create static constant variables of type TypeCode that we assign to unique values 
```
class TypeCodeEx {
   public const TypeCode Guid = (TypeCode) 17;
} 
```
And then we use them like 

  if (typecode == TypeCodeEx.Guid) 

Ideally we also change TypeCode, but this way we don't need an updated CoreLib to get the new values.

Vance

**Comment by adamsitnik** [comment]
I can see that TraceEvent is using different enum to identify types: [TdhInputType](https://github.com/Microsoft/perfview/blob/3e25f59f2960ea41b35aba043b4c55c331a9a3cf/src/TraceEvent/RegisteredTraceEventParser.cs#L1189)

```cs
internal enum TdhInputType : ushort
{
    Null,
    UnicodeString,
    AnsiString,
    Int8,
    UInt8,
    Int16,
    UInt16,
    Int32,
    UInt32,
    Int64,
    UInt64,
    Float,
    Double,
    Boolean,
    Binary,
    GUID,
    Pointer,
    FILETIME,
    SYSTEMTIME,
    SID,
    HexInt32,
    HexInt64,                   // End of winmeta intypes 21
    CountedUtf16String = 22,    // new for TraceLogging
    CountedMbcsString = 23,
    Struct = 24,

    CountedString = 300,        // Start of TDH intypes for WBEM
    CountedAnsiString,
    ReversedCountedString,
    ReversedCountedAnsiString,
    NonNullTerminatedString,
    NonNullTerminatedAnsiString,
    UnicodeChar,
    AnsiChar,
    SizeT,
    HexDump,
    WbemSID
};
```

Moreover, it has [the code](https://github.com/Microsoft/perfview/blob/284fc21001ca942da3b17a649db1ae8f3f2b572a/src/TraceEvent/DynamicTraceEventParser.cs#L1136) that could do the [parsing job](https://github.com/Microsoft/perfview/blob/c8d540fef3b345f4714ca60be2e78eb53120c2c2/src/TraceEvent/EventPipe/EventPipeTraceEventParser.cs#L39) for us.  And as far as I can see it also takes care of few other things (other types like mentioned here `IntPtr`).

My idea for solving this issue:

1. copy the `TdhInputType ` enum definition to CoreCLR
2. change the metadata generator to use the new enum
3. keep the old code for backward compatibility in EventPipeTraceEventParser, reuse the existing code from TraceEvent to support the cloned type 

I think that this change could still be a part of V3 Event Pipe file format. (the CoreCLR PR has not been merged, the consumer library has not been yet published)

@brianrob @vancem what do you think?

**Comment by vancem** [comment]
I would rather we stick with the current code and tweek it, than move over to TdhInputType.   You can see that TdhInputType is actually internal, and in fact is derived from a C++ enum used in ETW.   I consider it part of the 'ETW serialization infrastructure).   To pluck out a piece of it like this (and just that piece), is not likely to be super useful.   It also comes with extra 'junk' (many ways of encoding strings, SIDs SYSTEMTIME), that we really don't want.      It also has no synergy with .NET (this is the very first use of it, and it is unlikely the fact that it is used in ETW will ever be helpful).  

On the other hand TypeCode IS a .NET Concept and there is a useful methods (converting to and from system.type) that are useful.  Also TypeCode has almost no 'junk' (DBNull is arguably Junk for us), and frankly it WAS an oversight that it did not include IntPtr UIntPtr and Guid (it really should be fixed), because these types ARE valuable in the scenarios where TypeCode is used (which is the passing of 'primitive' types).  

Thus if I want to pick which enum I want to be 'near' it is TypeCode.   Now because of versioning issues even if we add the new values type Typecode, TraceEvent can't count them (since it may be running on an older runtime).   That is not really a problem (define the new values using const as I mentioned above).  

The other alternative I could imagine is to immediately make EventPipe support user defined types and then we can define Guid as 4 ints (or whatever).    This idea is OK to me because we will have to do this eventually anyway (to fully support EventSource events), and it will solve our current problem.  But that is enough work that I think the more tactical solution (of adding a couple more TypeCode (that the owners of TypeCode really should not mind), is a fine, simple, solution.  (and thus what I recommend).  

Note adding new Enum values to TypeCode will have to go through API review.   If that becomes a stumbling block, we should simply put in some COMMENTS in the code do indicate how we have reserved the values (we actually only need TypeCodes currently in native code so we need to make a clone of the definition anyway, and as mentioned TraceEvent has to make its own definition as well because it runs on older runtimes).

**Comment by adamsitnik** [comment]
@brianrob @vancem 

I created two PRs https://github.com/Microsoft/perfview/pull/560 and https://github.com/dotnet/coreclr/pull/16316

I did not extend the TypeCode enum. Please let me know if you would like me to start the process of extending the TypeCode enum (API change approval + PRs to corefx and coreclr)

**Comment by vancem** [comment]
@adamsitnik   Please add a comment to src\mscorlib\shared\System\TypeCode.cs claiming this enum value (you don't have to add the value just put it in as a comment) and indicate we did not add it for real simply because we don't care enough to go through the API review.

**Comment by adamsitnik** [comment]
@vancem good idea! Done
