### ISSUE TITLE
ThreadAbortException not re-thrown by the runtime

### ISSUE THREAD

**Issue by hmanner** [dotnet/coreclr#16122]
It looks like the ThreadAbortException is not always re-thrown by the runtime. See below for a sample program that reproduces the issue, causing an infinite thread loop.

I have reproduced this on two 64-bit systems running .NET Framework 4.6.1 and 4.7.1 respectively.
I can not reproduce on .NET Framework 4.5.2.

The issue goes away if forcing usage of the legacy jit compiler with the following config:

```
  <runtime>
    <useLegacyJit enabled="1" />
  </runtime>
```

I have reproduced with the following program built using Visual Studio Enterprise 2017, Version 15.5.2, targeting .NET Framework 4, Any CPU, Release build:

```
using System;
using System.Threading;

namespace ConsoleApp {
    class Program {

        static bool started = false;

        static void Main(string[] args) {
            // Start thread
            var thread = new Thread(ThreadLoop);
            thread.Start();
            while (!started);

            // Abort thread
            Console.WriteLine($"Aborting thread");
            thread.Abort();
        }

        private static void ThreadLoop() {
            Console.WriteLine($"Thread started");
            int cnt = 0;
            while (true) {
                try {
                    if (!started) {
                        Console.WriteLine($"Thread loop");
                        started = true;
                    }
                }
                catch (ThreadAbortException) {
                    Console.WriteLine($"ThreadAbortException #{cnt++}");
                }
            }
        }
    }
}

```
The output when reproducing:

```
Thread started
Thread loop
Aborting thread
ThreadAbortException #0
ThreadAbortException #1
ThreadAbortException #2
ThreadAbortException #3
ThreadAbortException #4
ThreadAbortException #5
ThreadAbortException #6
ThreadAbortException #7
ThreadAbortException #8
ThreadAbortException #9
ThreadAbortException #10
ThreadAbortException #11
ThreadAbortException #12
ThreadAbortException #13
ThreadAbortException #14
ThreadAbortException #15
ThreadAbortException #16
ThreadAbortException #17
ThreadAbortException #18
ThreadAbortException #19

(continuing forever)

```
I am aware of issue https://github.com/dotnet/coreclr/issues/3155, but it does not sound like the exact same issue.

Any thoughts on this?

**Comment by RussKeldorph** [comment]
@hmanner Thanks for reporting this.  As you're probably aware, Thread.Abort is not part of .NET Core, so we may have to find a more appropriate place to track this.  @richlander Is this appropriate for [Microsoft/dotnet](https://github.com/Microsoft/dotnet)?

Assuming CodeGen until proven otherwise since LegacyJit doesn't repro.

@dotnet/jit-contrib @dotnet/coreclr-contrib

**Comment by hmanner** [comment]
@RussKeldorph Sorry, I was a bit uncertain where to post this. A similar issue had been posted on the Connect site, which I believe was retired very recently. A reference to that report can be found [here](http://labs.criteo.com/2017/04/ryujit-never-ending-threadabortexception).  I'll be happy to post somewhere else if you can point me in the right direction.

I am aware of `Thread.Abort` not being in the core, and I am using it just to reproduce the issue in the test program. In real life we get the thread abort exceptions as a result of application restarts under the IIS, which trigger AppDomain unloads within the running w3wp process. We have not yet figured out what triggers the application restarts (no files are modified in the app directory), but that is another issue.

**Comment by hmanner** [comment]
@RussKeldorph, @briansull: Is anyone looking into this, or did you mean that I should post this elsewhere? 

I believe this is a major issue. It very often causes infinite loops, e.g. during app domain recycling when running under the IIS. The following is a very common pattern for long running background threads. 

```
// Thread loop that should never exit until app domain/process dies
while (true) {
    try {
        // Do important work in a long running thread
    }
    catch (Exception) {
        // Log error
    }
}

```
If the thread abort exception is not re-thrown automatically, this will cause an infinite loop when the app domain is meant to be shut down. We have had to go through all code and explicitly add the following to work around the issue. The alternative would be to force usage of the old jit compiler.

```
catch (ThreadAbortException) {
    throw;
}

```

**Comment by RussKeldorph** [comment]
@hmanner: We will investigate.  BTW, thanks for the original Connect report link.  Unfortunately the original was misrouted, so we didn't find it until I searched for it based on your comment.  (Lost/misrouted bugs is one of the reasons cited for retiring Connect.)

Ideally there would be a place to report bugs in .NET that don't apply to .NET Core, but I don't yet have the guidance.  I suspect things are still evolving...  For now, what you did is probably best.

@karelz FYI

**Comment by karelz** [comment]
For Desktop bugs, the right new route is to report them on [VS Developer Community portal](https://developercommunity.visualstudio.com/) - see also [CoreFX repo main page[(https://github.com/dotnet/corefx#how-to-engage-contribute-and-provide-feedback) for that info.
Either way, it is the same set of people, so I let it up to @RussKeldorph to decide if he wants to move it there or keep discussing here ...

**Comment by briansull** [comment]
This looks like a Roslyn C# bug from my initial investigation:
Using a slightly modified repro case:
YOu can comp;ile it with the latest Roslyn compiler and get the incorrect behavior and
using the older C# 5 version (which doesn't support the $ syntax) you get correct behavior:

```
csc /?
Microsoft (R) Visual C# Compiler version 4.7.3106.0
for C# 5
```

```
using System;
using System.Threading;

namespace ConsoleApp {
    class Program {

        static bool started = false;

        static void Main(string[] args) {
            // Start thread
            var thread = new Thread(ThreadLoop);
            thread.Start();
            while (!started);

            // Abort thread
            Console.WriteLine("Aborting thread");
            thread.Abort();
        }

        private static void ThreadLoop() {
            Console.WriteLine("Thread started");
            int cnt = 0;
            while (true) {
                try {
                    if (!started) {
                        Console.WriteLine("Thread loop");
                        started = true;
                    }
                }
                catch (ThreadAbortException)
                {
                    cnt++;
                    Console.WriteLine("ThreadAbortException #" + cnt);
                }
            }
        }
    }
}
```
This issue seems to be the IL code generated for the while(true) and the leave at the end of the catch:
 
The older good IL has a nop at IL offset 6 outside the try region
The new Roslyn code doesn't have the nop.

The IL for the catch in both bases ends with a leave.s IL instruction to IL offset 6.
Which is the older code was the nop which was outside of the loop.
With the new Roslyn compiler IL offset 6 is now inside the loop so we infinitely loop throwing the exception.

**Comment by BruceForstall** [comment]
@VSadov

**Comment by briansull** [comment]
Well setting COMPLUS_UseLegacyJit=1 also corrects the bad behavior, so it probably not caused by Roslyn.
I will continue to investigate this issue.

**Comment by VSadov** [comment]
What I see is 

Roslyn:
```IL
.method private hidebysig static void  ThreadLoop() cil managed
{
  // Code size       66 (0x42)
  .maxstack  2
  .locals init (int32 V_0)
  IL_0000:  ldstr      "Thread started"
  IL_0005:  call       void [mscorlib]System.Console::WriteLine(string)
  IL_000a:  ldc.i4.0
  IL_000b:  stloc.0
  IL_000c:  nop
  .try
  {
    IL_000d:  ldsfld     bool ConsoleApp.Program::started
    IL_0012:  brtrue.s   IL_0024
    IL_0014:  ldstr      "Thread loop"
    IL_0019:  call       void [mscorlib]System.Console::WriteLine(string)
    IL_001e:  ldc.i4.1
    IL_001f:  stsfld     bool ConsoleApp.Program::started
    IL_0024:  leave.s    IL_000c
  }  // end .try
  catch [mscorlib]System.Threading.ThreadAbortException 
  {
    IL_0026:  pop
    IL_0027:  ldloc.0
    IL_0028:  ldc.i4.1
    IL_0029:  add
    IL_002a:  stloc.0
    IL_002b:  ldstr      "ThreadAbortException #"
    IL_0030:  ldloc.0
    IL_0031:  box        [mscorlib]System.Int32
    IL_0036:  call       string [mscorlib]System.String::Concat(object,
                                                                object)
    IL_003b:  call       void [mscorlib]System.Console::WriteLine(string)
    IL_0040:  leave.s    IL_000c
  }  // end handler
} // end of method Program::ThreadLoop
```

Legacy csc

```IL
.method private hidebysig static void  ThreadLoop() cil managed
{
  // Code size       65 (0x41)
  .maxstack  2
  .locals init (int32 V_0)
  IL_0000:  ldstr      "Thread started"
  IL_0005:  call       void [mscorlib]System.Console::WriteLine(string)
  IL_000a:  ldc.i4.0
  IL_000b:  stloc.0
  .try
  {
    IL_000c:  ldsfld     bool ConsoleApp.Program::started
    IL_0011:  brtrue.s   IL_0023
    IL_0013:  ldstr      "Thread loop"
    IL_0018:  call       void [mscorlib]System.Console::WriteLine(string)
    IL_001d:  ldc.i4.1
    IL_001e:  stsfld     bool ConsoleApp.Program::started
    IL_0023:  leave.s    IL_000c
  }  // end .try
  catch [mscorlib]System.Threading.ThreadAbortException 
  {
    IL_0025:  pop
    IL_0026:  ldloc.0
    IL_0027:  ldc.i4.1
    IL_0028:  add
    IL_0029:  stloc.0
    IL_002a:  ldstr      "ThreadAbortException #"
    IL_002f:  ldloc.0
    IL_0030:  box        [mscorlib]System.Int32
    IL_0035:  call       string [mscorlib]System.String::Concat(object,
                                                                object)
    IL_003a:  call       void [mscorlib]System.Console::WriteLine(string)
    IL_003f:  leave.s    IL_000c
  }  // end handler
} // end of method Program::ThreadLoop
```

**Comment by VSadov** [comment]
If I add `finally`, the code loops forever regardless what compiler I use.

Try:

```C#
using System;
using System.Threading;

namespace ConsoleApp {
    class Program {

        static bool started = false;

        static void Main(string[] args) {
            // Start thread
            var thread = new Thread(ThreadLoop);
            thread.Start();
            while (!started);

            // Abort thread
            Console.WriteLine("Aborting thread");
            thread.Abort();
        }

        private static void ThreadLoop() {
            Console.WriteLine("Thread started");
            int cnt = 0;

            while (true)
            {
                try {
                    if (!started) {
                        Console.WriteLine("Thread loop");
                        started = true;
                    }
                }
                catch (ThreadAbortException)
                {
                    cnt++;
                    Console.WriteLine("ThreadAbortException #" + cnt);
                }
		finally
		{
                    Console.WriteLine("finally");
		}
             }
        }
    }
}
```

**Comment by briansull** [comment]
I have a fix available

**Comment by BruceForstall** [comment]
This bug is occurring due to an unfortunate interaction between a workaround for an ancient bug, and code generated by the current C# and RyuJIT compilers.

When the VM goes to raise a Thread Abort, it checks to make sure that a thread is in a "good" place to do so. It doesn't want to raise a Thread Abort if the thread is currently executing a "finally" (or "fault") exception handling clause. So, `ReadyForAbort()` does a stack walk, and `TAStackCrawlCallBackWorker` looks to see if the current frame is within a finally or fault. I'm not sure what happens if it is not in a "good" location; perhaps wait and try again later?

However, `TAStackCrawlCallBackWorker` on amd64 also checks for a peculiar case of NOPs preceding a `try`, described later.

Long ago, before .NET 4, the C# compiler, when generating a `lock` construct, would generate something like this:
```
lock (thisLock)
{
    ... work ...
}

=>

Monitor.Enter(thisLock);
try
{
    ... work ...
}
finally
{
   Monitor.Exit(thisLock);
}
```

On AMD64, there is a rule (see [here](https://github.com/dotnet/coreclr/blob/master/Documentation/botr/clr-abi.md#amd64-padding-info)) that a `call` instruction immediately preceding a `try` region must have a `NOP` inserted, such that the return address of the `call` is in the same EH region as the `call` itself. So when the above generated `lock` construct was translated to native code on AMD64, it looks like this:

```
Monitor.Enter(thisLock);
NOP  // inserted by JIT to enforce above rule
try
{
    ... work ...
}
finally
{
   Monitor.Exit(thisLock);
}
```

Now, if a Thread Abort happens asynchronously, and is raised when this thread's instruction pointer is at the NOP, then the lock has already been taken, but the NOP isn't protected by the following `try`, so the exception handler will not invoke the `finally`. Thus, the lock can "leak" -- it won't be unlocked.

To work around that, code was added in `TAStackCrawlCallBackWorker` to check if a single NOP precedes a `try` region, and if so, don't allow a Thread Abort to be raised when the IP is at that NOP. Instead, let execution continue and try again later. This check isn't very precise, e.g.: (1) it doesn't know if the NOP follows a call to Monitor.Enter(), (2) it doesn't check that the EH region is a try/finally (or fault), (3) it doesn't know if there's a Monitor.Exit() in the finally.

Another thing to consider is that for a `try/catch`, where the `catch` catches a `ThreadAbortException`, but doesn't suppress it, the VM will automatically re-raise that exception after the `catch` has executed. To do so, the VM needs to choose an address to use as the "re-raise address" -- the address in the managed code where the exception will be considered to originate. This is important for determining which `try` regions get to handle the re-raised exception. The address used for this purpose is the "continuation" or "return" address from the `catch` clause. Thus, it is important that the exception region where this address lives be correct. Much more detail is given [here](https://github.com/dotnet/coreclr/blob/master/Documentation/botr/clr-abi.md#threadabortexception-considerations).

With the failing test case here, there is a very tight loop. The `catch` clause continuation address ends up being either the first instruction of the `try` region, for the older C# compiler, or a NOP immediately preceding the `try` region, for the current Roslyn C# compiler.

For the older C# compiler, the continuation address is within the `try`. You would think that would cause the raised exception to be caught again by the `catch`. However, there is logic in the VM to try and make forward progress on Thread Abort reraises (in `ExceptionTracker::ProcessManagedCallFrame`). So, it notices that this EH clause has already been processed, and skips it. In the CLR log:
```
TID 14d0: ..  considering typed clause [20,3f], ControlPc is inside clause (offset 20)
TID 14d0: ..  skipping the evaluation of EH clause (index=0) since we cannot process an exception in a handler
TID 14d0: ..  that exists prior to the one (index=1) after which ThreadAbort was [re]raised.
```

In the Roslyn case, the continuation address is a generated NOP before the `try`. The special NOP logic in `TAStackCrawlCallBackWorker` kicks in (unintentionally), and says not to reraise. It appears at this point that the thread abort is attempted again but at offset 0x28, which is the 2nd instruction within the `try`. It also appears that the CLR has "forgotten" that it is attempting to do a reraise. Thus, the make "forward progress" logic doesn't kick in, and we go ahead and reraise within the `try`. This leads to an infinite loop.

Note that the "lock" construct is not generated this way anymore. Currently, the generated IL looks something like:
```
bool lockTaken = false;
try
{
   Monitor.Enter(thisLock, ref lockTaken);
   ... work ...
}
finally
{
   if (lockTaken) {
      Monitor.Exit(thisLock);
   }
}
```

**Comment by BruceForstall** [comment]
Note the legacy Jit (JIT64) passes both the old C# and Roslyn C# tests because it optimized away the NOP. So it kind-of passes by accident.

Also note that while the C# compilers now (and for a long time) have used the new lock generation pattern, the old Monitor.Enter API exists, and in fact the documentation for it gives many examples of the bad pattern that could lead to a lock leak in the async Thread Abort at NOP case.

**Comment by VSadov** [comment]
One thing worth mentioning - C# compiler is still technically capable to emit pre-4.0 lock pattern.
See: https://github.com/dotnet/roslyn/blob/47280ccb9e7f781210cae5ce29694ac3411582c8/src/Compilers/CSharp/Portable/Lowering/LocalRewriter/LocalRewriter_LockStatement.cs#L135

That would happen when compiling against runtime that does not have the required `Monitor.Enter` API with the `lockTaken` parameter. 
That is mostly done for compat reasons - what if we compile for very old FX or something like that? Old pattern is better than crashing or failing with an error.

Practically, this situation is very unlikely to arise though.

**Comment by briansull** [comment]
We have decided not to make any changes in the ThreadAbort logic  for the Desktop
