### ISSUE TITLE
[Arm64] Lower Unsigned Vector Compare LT/GE Zero discards side effects

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#16176]
Side effects of vector `a` are discarded when `T` is unsigned

`Intrinsics.Arm.Arm64.Simd.CompareLessThanZero<Vector*<T>(a);`
`Intrinsics.Arm.Arm64.Simd.CompareGreaterThanOrEqualZero<Vector*<T>(a);`

Per @CarolEidt this is generally something we want to avoid.

In this case these are forms which should not be used.  They are non-sensical returning always `false` or `true` respectively.  An analyzer module is recommended to detect these useless forms.

Lowering is replacing these with a const vector.  Removing the tree `a`.

If `a` has side effects lowering could be changed to either 
+ actually do a compare against an const zero vector (slower)
+ add a comma operator to maintain the side effect.

**Comment by sdmaclea** [comment]
My initial reaction would not be to prevent Lowering from eliminating side effects for intrinsics, which are only function calls by syntax, but are actually (~always) inlined operators.

Personally, I would close this as won't fix

cc @mikedn @tannergooding

**Comment by tannergooding** [comment]
For most intrinsics, we are providing a contract to emit a particular instruction, and to pass the inputs and return the outputs unmodified. There are a few exceptions, such as the "helper" intrinsics, which are providing a contract of functionality, rather than a contract of a particular instruction.

I believe that, for hardware intrinsics, we should emit exactly the instruction sequence the user has requested. It is essentially just a mechanism for writing type-safe inline assembly in managed code and should generally be treated as if the user knows what they are doing and as if they have already hand-optimized the algorithm.

Providing analyzers that help identify cases where the user could improve there code is probably the best way to catch places where the user is doing something that may be undesirable (such as a comparison which will always return true/false).

**Comment by mikedn** [comment]
> Lowering is replacing these with a const vector. Removing the tree a.

Replacing with a const vector is fine (provided that the way the const vector is generated is not slower than actually executing the compare operation). Removing the tree `a` when it has side effects is a bug and should be fixed.

> I believe that, for hardware intrinsics, we should emit exactly the instruction sequence the user has requested. It is essentially just a mechanism for writing type-safe inline assembly in managed code.

I'm not sure on what this belief is founded, that's not what native compilers are doing. Also, it's not type safe and it's not really inline assembly, at least because intrinsic based code still requires register allocation.

> Providing analyzers that help identify cases where the user could improve there code is probably the best way to catch places where the user is doing something that may be undesirable (such as a comparison which will always return true/false).

Indeed. Here's it worth noting that C# doesn't emit any warning if you do `x < 0` where x is `uint`. So I don't see why would one bother too much with such an issue, an analyzer would be more than enough. Perhaps even a bit overkill.

**Comment by CarolEidt** [comment]
> Removing the tree a when it has side effects is a bug and should be fixed.

Is this currently being done? If so, then indeed it should be fixed. It should simply evaluate a, and then generate the const vector.

Regarding the specific case of these operands with unsigned, there are two reasons to support these cases:

- First, it makes the API a bit cleaner when it is simply supported against all types. I suppose that one could have an "understood" contract that certain Foo<T> methods only support signed types, but when the semantic provides a reasonable interpretation, I think it makes sense to support them.

- Second, it may be the case that a generic algorithm could be written that would "just work" for both signed and unsigned generic arguments - and it seems unfortunate to disallow that.

**Comment by sdmaclea** [comment]
> Is this currently being done? If so, then indeed it should be fixed

I think so.  Unless Block.Remove() handles it automatically.

https://github.com/dotnet/coreclr/blob/master/src/jit/lowerarmarch.cpp#L539-L543
https://github.com/dotnet/coreclr/blob/master/src/jit/lowerarmarch.cpp#L558-L562

I assume I need to insert a `GT_COMMA` with the previously discarded op  as `GT_COMMA.op1`, and the new const as `GT_COMMA.op2`

**Comment by sdmaclea** [comment]
> I believe that, for hardware intrinsics, we should emit exactly the instruction sequence the user has requested

> Providing analyzers that help identify cases where the user could improve there code

This is not a lowering optimization.  The instruction(s) simply does not exist for ARM64.  It must be replaced with something.  Constant is as good as any other.

Also this seems to be a double standard.  You are pushing containment patches for X86 w/o user being explicitly required to mark contain.

**Comment by tannergooding** [comment]
>  The instruction(s) simply does not exist for ARM64. It must be replaced with something. Constant is as good as any other.

Ah, I did not realize there was no underlying instruction here.

> Also this seems to be a double standard. You are pushing containment patches for X86 w/o user being explicitly required to mark contain.

The `Load`, `LoadAligned`, and `LoadScalar` are, realistically, part of the "helper" functions. The provide a contract that we will emit an unaligned load, an aligned load, or a scalar load (respectively), and are not (strictly speaking) guaranteed to emit `movups`, `movaps`, or `movss`. This was required in order to keep the API surface small while still allowing the user to emit the `INS reg, [mem]` encoding. The current containment code is being carefully done to ensure that we don't fold when it would cause a difference in behavior (for example, `LoadAligned` is folded on non-VEX machines and `Load` is not, while the opposite is true for machines which support the VEX encoding -- `Load` is folded and `LoadAligned` is not).

**Comment by sdmaclea** [comment]
> This was required in order to keep the API surface small 

Exactly.  Containment is done in part to keep API surface small.

**Comment by mikedn** [comment]
> Exactly. Containment is done in part to keep API surface small.

It has nothing to do with the API surface being small. It's simply the only sensible way to do things and it's also the way it's done in C/C++. That @tannergooding discovered "containment" over night and insists in making things appear a certain way it's a completely unrelated issue.

**Comment by CarolEidt** [comment]
`LIR::Range::Remove()` doesn't eliminate side-effects. In fact, the code that you linked to is calling it with the default second parameter of `markOperandsUnused` set to false. So it won't even cause the operands (if any) of `origOp1` to be marked as unused (which I think it should; the default is for the case where the operands are going to be used by a new/different node). To check for side-effects, and delete the range if there are none, you would have to do something like what is done here: https://github.com/dotnet/coreclr/blob/master/src/jit/rationalize.cpp#L744, but I think that is overkill for this.
