### ISSUE TITLE
[Linux/arm32] eventpipesmoke test failure

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#16488]
```
FAILED   - tracing/eventpipesmoke/eventpipesmoke/eventpipesmoke.sh
               BEGIN EXECUTION
               /home/ubuntu/gh/coreclr/bin/tests/Linux.arm.Checked/Tests/Core_Root/corerun eventpipesmoke.exe
                Start: Enable tracing.
                End: Enable tracing.

                Start: Allocation.
                End: Allocation.

                Start: Disable tracing.
                End: Disable tracing.

                Expecting at least 1048576 bytes of data
                Created 181694 bytes of data
               Expected: 100
               Actual: 0
               END EXECUTION - FAILED
```

In a Linux/arm32 by-hand test run.

**Comment by nategraf** [comment]
If all of the expected events are in the file, then we can lower the threshold for what the size we expect it. I don't have any ARM32 hardware at the moment. Would it be too much trouble to generate a .netperf file form this test and and send it to us? If you supply a filename for the first argument it will save the file as that name (rather than to tmp and deleting it)

**Comment by BruceForstall** [comment]
Closing, since eventpipesmoke was deleted with https://github.com/dotnet/coreclr/pull/16667
