### ISSUE TITLE
[linux x64 tizen armel]  the test objmonhelper hangs forever with GCStress=0x3

### ISSUE THREAD

**Issue by sergign60** [dotnet/coreclr#16564]
The test ```baseservices/threading/regressions/269336/objmonhelper``` hangs forever with the environment variable ```COMPlus_GCStress=0x3```. The checked platforms - ubuntu-x64 and tizen-armel. The test is performed very quickly without ```GCStress```. I've checked ```Debug```, ```Checked``` and ```Release``` versions of CoreCLR.

**Comment by sergign60** [comment]
@dotnet/arm32-contrib

**Comment by sergign60** [comment]
https://github.com/dotnet/coreclr/issues/15309

**Comment by kouvel** [comment]
There are many tests that take an unreasonably long time under GCStress, this may just be one of those cases where it should be disabled for GCStress runs.

**Comment by sergign60** [comment]
@RussKeldorph @janvorli @jkotas @BruceForstall 
Could you explain how  coreclr works when the ```GCStress``` environment variable is set. I didn't find any description in documentation. All that I see now, so is explosive growth of numbers of allocation of memory at increasing array dimension in this test ```var arr = new object[...];``` (I used values 16, 32 and so on) when ```GCStress``` is set. I'm very novice in this subject, so any hints will be helpful. Thanks in advance.

**Comment by janvorli** [comment]
@sergign60 COMPlus_GCStress induces GC to happen at certain points. There are several modes of the stress which can be combined:
* Mode 1 - GC is induced on every allocation 
* Mode 2 - GC is induced on every transition to preemptive GC
* Mode 4 - GC is induced after every allowable machine code instruction executed in the jitted code. 
* Mode 8 - GC is induced after every allowable machine code instruction executed in the crossgened code. 

See https://github.com/dotnet/coreclr/blob/master/src/vm/eeconfig.h#L627-L634 for the GC stress mode constants.

So, e.g. GCStress 3 means GCStress 1 and 2, GCStress C means 4 and 8.

The purpose of the GCStress is to reveal GC holes, which means places where a managed reference is missed by GC due to a bug in the GC info generated by the JIT or a bug in the runtime. If GC relocates an object referenced by such reference, it doesn't update the reference in the location of the GC hole and such reference becomes stale. Later on when such an object is referenced, the runtime usually crashes or can even cause much more subtle effects in case there is a new object allocated at the address to which the stale location was pointing.
Such a hole can go unnoticed for a long time and strike only very rarely without the GC stress, since it may exist in just a very small range of code and cause trouble only when GC happens when executing that piece of code.

Thanks,

Jan

**Comment by sergign60** [comment]
@dotnet/arm32-contrib  @RussKeldorph @janvorli @jkotas @kouvel
I've counted calls of ```GCHeapUtilities::GetGCHeap()->Alloc``` in the function ```src/vm/gchelpers.cpp: Object* Alloc``` depending on the array size ```	var arr = new object[Size*Size]```

```
Size  GCStress   Allocs  Exec Time 
16      0                233      0.08s user 0.00s system 108% cpu 0.077 total
16      1                520      0.12s user 0.04s system 100% cpu 0.168 total
32      0                237      0.07s user 0.02s system 107% cpu 0.078 total
32      1              1288      0.21s user 0.03s system 100% cpu 0.239 total
64      0                246      0.07s user 0.02s system 108% cpu 0.078 total
64      1              4360      0.57s user 0.08s system 99% cpu 0.649 total
128    0                282      0.08s user 0.01s system 104% cpu 0.084 total
128    1            16648      4.24s user 0.22s system 99% cpu 4.461 total
256    0                426      0.10s user 0.01s system 107% cpu 0.104 total
256    1            65800      56.88s user 0.92s system 99% cpu 58.006 total
512    0              1004      0.14s user 0.04s system 104% cpu 0.165 total
512    1          262408      944.67s user 6.36s system 99% cpu 15:51.11 total
 ```

**Comment by sergign60** [comment]
@janvorli many thanks!

**Comment by RussKeldorph** [comment]
@sergign60 Thanks for finding and looking into this.  You can disable the test under GCStress by setting the `GCStressIncompatible` attribute in the project file (like [this](https://github.com/dotnet/coreclr/blob/25dbd547bc7372906357699a24d7cf76786a50c8/tests/src/GC/Scenarios/FinalizeTimeout/FinalizeTimeout.csproj#L10).

Note that the project file already sets COMPlus_FastGCStress=1 when running the test.  I'm not familiar with that setting, so I don't know how interesting it is, but I wanted to point it out in case others do.

**Comment by sergign60** [comment]
https://github.com/dotnet/coreclr/pull/17091
