### ISSUE TITLE
[Perf] Investigate CscBench Regression between release/2.0.0 and release/2.1

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/coreclr#16601]
We saw a regression of 5% between 2.0 and 2.1

**Comment by AndyAyersMS** [comment]
Any progress?

**Comment by AndyAyersMS** [comment]
Looking at history there is perhaps a small regression in 2.1 in both the CompileTest and DataflowTest.

Let's look at the CompileTest since it shows a slightly larger slowdown.

2.0 performance is around 298.

![image](https://user-images.githubusercontent.com/10121823/37430779-7e0d5e92-2790-11e8-9be2-eedb92cc3f79.png)

2.1 is around 308, so that would be maybe a 2-3% regression.

![image](https://user-images.githubusercontent.com/10121823/37430748-585a5100-2790-11e8-9c43-bf1724ece1fb.png)

master shows the slight regression seems to have happened in stages with the first part before Nov (I can't seem to look back further right now) and some recent further slowdown. Pinpointing a recent cause is going to be hard, given how noisy the results are.

![image](https://user-images.githubusercontent.com/10121823/37430925-f43462dc-2790-11e8-9b32-bd6fb3a27659.png)

Dataflow goes from ~433 to ~437, so perhaps a 1% regression, but we may not have enough data for 2.1 to say this with any confidence. Data from master suggests the regression, if any, was from fairly recent changes

![image](https://user-images.githubusercontent.com/10121823/37431210-d904a5d4-2791-11e8-819e-d3d6afffdbad.png)

**Comment by AndyAyersMS** [comment]
I'm going to try and trace perf farther back in master to see what might have lead to the initial slowdown in the CompileTest. It may take a few days. So for now leaving this open in 2.1.

**Comment by AndyAyersMS** [comment]
@jorive please ping me when you have a benchview setup that will let me look back over longer time spans.

**Comment by AndyAyersMS** [comment]
Finally able to look back further, and there was about a 2% regression from #13291.

Suspect it may be affinity related too, as CSC is multi-tasking. I've added this test to the ones that we should no longer affinitize (#16801).

Note it appears that affinity helps the CompileTest quite a bit, so if/when we disable it we may see a perf drop.

![image](https://user-images.githubusercontent.com/10121823/37803227-e417c370-2dea-11e8-9c19-55713709a438.png)

I believe that closes out the 2.1 investigation, as the affinity/spinning issue is known (#16807).
