### ISSUE TITLE
Unix: Interop does not handle invalid UTF8 characters correctly

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#16786]
Repro:

```
using System;
using System.Text;
using System.Runtime.InteropServices;

unsafe struct UnmanagedStruct
{
    public fixed byte psz[8];
}

[StructLayout(LayoutKind.Sequential, CharSet = CharSet.Ansi)]
struct ManagedStruct
{
    [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 8)]
    public string str;
}

class Program
{
    static unsafe void Main(string[] args)
    {
        UnmanagedStruct ums;
        ums.psz[0] = 0xFF;
        ums.psz[1] = (byte)'a';
        ums.psz[2] = (byte)'b';
        ums.psz[3] = (byte)'c';
        ums.psz[4] = (byte)'d';
        ums.psz[5] = 0;

        IntPtr ptr = (IntPtr)(&ums);
        ManagedStruct ms = Marshal.PtrToStructure<ManagedStruct>(ptr);

        foreach (char c in ms.str)
            Console.WriteLine((int)c);

        Console.WriteLine("Done");
    }
}
```

Actual result (bogus string with 0 in the middle):
```
97
98
99
100
0
46627
Done
```

Expected result (same as what Encoding.UTF8.GetString returns):
```
65533
97
98
99
100
Done
```

**Comment by jkotas** [comment]
cc @jeffschwMSFT

**Comment by jkotas** [comment]
This bug seems to be in the C/C++ UTF8 encoder/decoder. This repro is just one example where it surfaces.

I have found this while doing test coverage inspection for https://github.com/dotnet/coreclr/pull/16749 .

**Comment by janvorli** [comment]
@luqunl please let me know if you need any help with this - the C/C++ UTF8 encoder/decoder code is in PAL (https://github.com/dotnet/coreclr/blob/master/src/pal/src/locale/utf8.cpp) and I have reviewed / helped with the implementation in the past.

**Comment by luqunl** [comment]
@janvorli , Thanks a lot. I will take a look this issue soon. just one question: do you know why we implement UTF8Encoding logic twice-- one in utf8.cpp and the other in UTF8Encoding.cs?

**Comment by janvorli** [comment]
@luqunl Yes, I do. The implementation in PAL implements the WideCharToMultiByte and MultiByteToWideChar Windows APIs that we need in the PAL itself and the native part of the runtime.

**Comment by luqunl** [comment]
@janvorli , such as for UTF8 support, the PAL implementation for MultiByteToWideChar in linux could be call back to UTF8Encoding.cs instead of reimplement itself in native code, see following two functions(also other functions) are very similar..

https://github.com/dotnet/coreclr/blob/32f0f9721afb584b4a14d69135bea7ddc129f755/src/pal/src/locale/utf8.cpp#L1603

https://github.com/dotnet/coreclr/blob/57ee22e6086af5dfc06651dc002e24a71c3999ee/src/mscorlib/shared/System/Text/UTF8Encoding.cs#L1716

**Comment by janvorli** [comment]
@luqunl PAL cannot call managed code. It needs to be available even before anything managed can be even executed. Even before the native runtime is initialized. 
The reason why they are similar is because the native version was created by taking the managed source code and just modifying it to be compilable as native. Besides the native / managed differences, the code should be "the same".

**Comment by luqunl** [comment]
@janvorli , if PAL cannot call managed code. then Can managed code calls PAL instead(such as OS == Linux, call ...) ? just want to reduce services surface. it is easier for people to update one version and forget another one.

**Comment by janvorli** [comment]
@luqunl That would mean that we would use the managed implementation only on windows. That is not desirable. We really want to have the two versions. The one in PAL used to be different from the managed one and we've reimplemented it so that it matches the windows version to enable easy comparison of the two versions or porting fixes to the native one.

**Comment by jkotas** [comment]
Yes, I agree with @janvorli . We really want to have two versions.

**Comment by jkotas** [comment]
Also, this bug is likely in the glue code that connects WideCharToMultiByte/MultiByteToWideChar to the worker method, not in the worker method itself.
