### ISSUE TITLE
Attach/Detach support in profiler

### ISSUE THREAD

**Issue by ww898** [dotnet/coreclr#16796]
Hi there,

is there plans to enable `FEATURE_PROFAPI_ATTACH_DETACH` in CoreCLR? Do you have any plans? Will you did it separately on Linux and Windows?

**Comment by mfilippov** [comment]
We want to attach and detach dotTrace profiler to running .NET Core processes such as ASP .NET Core, Console Application, UWP, etc...  on all supported platforms. If it possible only windows now let's do it on Windows.

**Comment by jkotas** [comment]
cc @noahfalk

**Comment by lt72** [comment]
We are working on it, on both Windows and Linux, but there is no set date yet to deliver this. It will not be in 2.1 for sure, maybe in 2.2.

**Comment by KKatsnel** [comment]
Hi,

Any updates on it? How about 3.0?

**Comment by noahfalk** [comment]
This is still something we intend to do, but I don't have a specific date or release yet where I can commit it will be done. If anyone is interested in working on it to ensure it is ready faster we're always glad for the help.

But to provide something a little more informative than that, right now we are building a generic xplat IPC channel that multiple tools could use to ask the runtime to do things. The current debugger IPC mechanism isn't very flexible because it only allows one tool to be connected whereas we've shifted our focus to Unix Domain Sockets which support multiple clients. The first use-case we wanted the new IPC mechanism for was to [enable runtime telemetry and tracing streams](https://github.com/dotnet/coreclr/issues/21027) and then the second thing we had in mind was this issue, attaching an in-proc profiler. @jorive is actively working on the first part, and although its not PR ready yet, there are [some fragments of work in progress visible](https://github.com/jorive/coreclr/commits/dev/eventpipe-ipc-proto). Once @jorive's work is done and the IPC channel is in place, using it to initiate the load of an in-proc profiler seems like a relatively small addition.

HTH!
 -Noah

**Comment by lucaspimentel** [comment]
Looks like profiler attach support on Windows was added in #18762.

**Comment by davmason** [comment]
Windows only support was added in #18762, yesterday I checked in #24670 which removes the windows only attach mechanism and replaces it with one that works on windows and linux. 

I am leaving this issue open for now until I get documentation on how to consume it. The short answer is to use the code I added to Microsoft.Diagnostics.Tools.RuntimeClient here https://github.com/dotnet/diagnostics/pull/274. The long answer will come as a howto guide I'll add and then post to the profiler announcement issue.

**Comment by ww898** [comment]
Hi, have just implemented attaching to CoreCLR `v3.0.0.-preview5` through `CreateCLRProfiling`. Everything works properly at first look. I don't see any documentation for that. Could you please publish the document with correct attaching procedure in it? I am not sure that my way is absolutely correct.

**Comment by davmason** [comment]
@ww898 I am in the process of creating documentation for profiler attach. I hope to have it done soon.

Unfortunately `CreateCLRProfiling` is being removed in Preview6 and replaced with a new attach mechanism so it will no longer be an option. The transition to the new attach mechanism should hopefully not be too much code churn.

> And the important question: how to detect that the process with pid # has coreclr available for attach on different OS?

The new attach mechanism is built on the EventPipe protocol, so the process with that would be trying to attach, and then an error HR would indicate it does not support attach

**Comment by ww898** [comment]
@davmason Thanks a lot.

However, I need show the list of process to attach in UI with CoreCLR version if possible. So, I need test the process without trying to attach to it. I think that `Microsoft.Diagnostics.Tools.RuntimeClient.DiagnosticHelpers.AttachProfiler()` is not allow that. I expect something like `Microsoft.Diagnostics.Tools.RuntimeClient.DiagnosticHelpers.CanAttachProfilerPossible(int pid)`.

The important question about protocol between C# client and coreclr? It will be open or proprietary?

**Comment by tommcdon** [comment]
@ww898 the IPC Event Pipe protocol is documented here: https://github.com/dotnet/diagnostics/blob/master/documentation/design-docs/ipc-protocol.md.  We are also planning on creating an IPC Event Pipe client library, tracked on https://github.com/dotnet/diagnostics/issues/191.

**Comment by ww898** [comment]
@tommcdon Thanks a lot. I already connected it to our code and slitely adapted it for .NET Framework 4.6.1. Unfortunately, I can't test it with preview5 because the pipe protocol is different. So, we are waiting preview6.

**Comment by noahfalk** [comment]
> will it be open or proprietary?

I think this was implied by Tom's answer, but just to be certain for anyone else seeing it, that documentation isn't just internal documentation for us. We fully intend for third parties to be able to write their own implementations of the remote client and communicate with the runtime over that protocol. If our managed implementation of the client library suits your needs (once we ship it) we hope that makes many use cases easier, but if for whatever reason it does not the protocol is an open and supported option : )

**Comment by davmason** [comment]
Fixed in #24670. Documentation for how to use it is available at https://github.com/dotnet/coreclr/blob/master/Documentation/Profiling/Profiler%20Attach%20on%20CoreCLR.md
