### ISSUE TITLE
Bundle libsos with coreclr builds for the dotnet cli

### ISSUE THREAD

**Issue by TyOverby** [dotnet/coreclr#16922]
I'm trying to use lldb/libsos to debug a dotnet core application, but the [instructions](https://github.com/dotnet/coreclr/blob/master/Documentation/building/debugging-instructions.md) ask me to build llvm, lldb, and presumably coreclr from scratch.

Would it be possible to package the correct version of libsos with dotnet cli installations?

**Comment by mikem8361** [comment]
Are you talking about MacOS? Because that is the only platform that requires building lldb so libsosplugin.dylib can be built in the coreclr repo.  libsos.dylib (the actual/core part of sos) is already built. 

If it is a Linux platform, then the cli installs contain the libsosplugin.so that works with lldb 3.9 and of course libsos.so is also include. 

The problem on MacOS is that libs/include files necessary to build the libsosplugin.dylib that works with the lldb that comes with MacOS are not available.

**Comment by mikem8361** [comment]
Issue moved to [dotnet/diagnostics #46](https://github.com/dotnet/diagnostics/issues/46) via [**ZenHub**](https://www.zenhub.com/)
