### ISSUE TITLE
Different behavior between windows and linux - Date to String or Razor Issue

### ISSUE THREAD

**Issue by jonatanrinckus** [dotnet/coreclr#16960]
Hello guys.

I don't know if here is the right place, but I will put here.

I had a web server on windows, I develop on windows, I sent my asp.net core web site to the windows server and everything work's fine. So I deploy now a linux server and for my surprise, the behavior of a little piece of code is not the same as windows.

What is wrong? This code: 

`data-account-issue-date="@bill.IssueDate"`

the behavior:

Windows: data-account-issue-date="31/07/2017 00:00:00"
Linux: data-account-issue-date="31/07/17 00:00:00"

expected:

Windows: data-account-issue-date="31/07/2017 00:00:00"
Linux: data-account-issue-date="31/07/2017 00:00:00"

Almost nothing, just the year :)
 
But, what more we have different between them, the end result should be the same on both.

Workaround:

`data-account-issue-date='@bill.IssueDate.ToString("dd/MM/yyyy")'`

Thanks

**Comment by RussKeldorph** [comment]
@tarekgh Please change area if this isn't correct.

**Comment by tarekgh** [comment]
@jonatanrinckus this is by design for the framework. in general, the framework just pick the default date format from the system which depends on the default locale/culture of the user and the default date/time format pattern on that locale/culture. 

we recommend if the app wants to ensure specific format will have to explicity specify this format to ensure consistent results across OS's.

Feel free to send any more questions as needed. 

CC @krwq

**Comment by jonatanrinckus** [comment]
For me, it's is wrong, the framework sould have the same final behavior, it can have differents behavior internally, but the final result should be the same or it will have some problem when using with another framework.

**Comment by jonatanrinckus** [comment]
It has a different result with the decimal.ToString("N"), in windows is 1.00 and on linux is 1.000

**Comment by tarekgh** [comment]
> For me, it's is wrong, the framework sould have the same final behavior

We have looked at that deeply before and decided it is better to get parity with the system you are running on. another thing you have to consider, globalization data can change anytime as it is tied to locales and countries so it is wrong to take a hard dependency on something that can change. our guidelines are if you need very specific behavior, then you need to specify this specific format explicitly. otherwise, you'll need to the invariant culture which is stable and we don't change it.
