### ISSUE TITLE
[Arm/Arm64/Linux] Support running corefx tests

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#17020]
@debayang & I are starting to look at this.

@BruceForstall We would like to ask for you to help by helping us understand the [Arm/Windows] workflow.  And also for consultation on Linux specific issues.

**Comment by BruceForstall** [comment]
I'd be happy to answer questions and explain what I know.

The original change to enable Windows arm32 corefx testing was https://github.com/dotnet/coreclr/pull/16006.

A relevant follow-up change, applicable to all architectures corefx testing in coreclr repro is https://github.com/dotnet/coreclr/pull/16263.

Related issue for doing "the right thing" is https://github.com/dotnet/corefx/issues/26944.

Summary: to test corefx in coreclr repo, we build coreclr, then clone the live corefx repo, build it to generate the tests as well as a "layout" / setup, then copy over the built coreclr into this "layout", and run the corefx tests. Ideally, we would just copy the corefx tests (and "layout"?) from some corefx branch build, and go from there.

There is still a big problem with how to do appropriate test disabling so that breaking changes don't cause the CI test jobs to go "red" (start failing). Namely, we need a way to (temporarily) disable a minimum (or small) number of tests, in a form (like a failure list) stored in the coreclr repo, that can be updated with a breaking change that goes into coreclr. If we had this, we could conceivably add the corefx_baseline job for some architectures as a default-triggered PR job.

**Comment by BruceForstall** [comment]
cc @RussKeldorph @jkotas

**Comment by sdmaclea** [comment]
Arm failures are documented in #16001

**Comment by sdmaclea** [comment]
@BruceForstall Thanks
@debayang has made some progress on this.  He has been able to run at least one test using a coreoverlay

**Comment by debayang** [comment]
Proposed PR #17090 with initial failed tests seen on arm64 Ubuntu

**Comment by debayang** [comment]
Some details on the failed tests:

Many of the failing tests (listed below) are seen failing due to OutofMemoryException :
**System.Composition.Tests**, **System.Linq.Expressions.Tests** , **System.Linq.Queryable.Tests**, **System.Dynamic.Runtime.Tests**, **System.Numerics.Vectors.Tests**, **System.Xml.Xsl.XslCompiledTransformApi.Tests**

Some examples:
```
System.Composition.UnitTests.ExportFactoryTests.ExportFactoryCanBeComposedWithImportManyAndNames [FAIL]
       System.OutOfMemoryException : Insufficient memory within specified address space range to continue the execution of the program.
       Stack Trace:
             at System.Runtime.CompilerServices.RuntimeHelpers._CompileMethod(IRuntimeMethodInfo method)
             at System.Reflection.Emit.DynamicMethod.CreateDelegate(Type delegateType, Object target)
```
```
System.Linq.Tests.SumTests.Sum19 [FAIL]
      System.OutOfMemoryException : Insufficient memory within specified address space range to continue the execution of the program.
      Stack Trace:
            at System.Runtime.CompilerServices.RuntimeHelpers._CompileMethod(IRuntimeMethodInfo method)
            at System.Reflection.Emit.DynamicMethod.CreateDelegate(Type delegateType, Object target)
         /home/debayan/coreclr/_/fx/src/System.Linq.Expressions/src/System/Linq/Expressions/Compiler/LambdaCompiler.cs(185,0): at System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda)
```

 **Other failures:**

         
 **Invariant.Tests**
```
   System.Globalization.Tests.InvariantModeTests.TestIndexOf(source: \"Hi\", value: \"I\", startIndex: 0, count: 2, options: IgnoreCase, result: 1) [FAIL]
      Assert.Equal() Failure
      Expected: 1
      Actual:   -1
      Stack Trace:
         /home/debayan/coreclr/_/fx/src/System.Globalization/tests/Invariant/InvariantMode.cs(656,0): at System.Globalization.Tests.InvariantModeTests.TestIndexOf(String source, String value, Int32 startIndex, Int32 count, CompareOptions options, Int32 result)
```

 **System.Reflection.Emit.ILGeneration.Tests**
```
0
emitWriteLine
False
   System.Reflection.Emit.Tests.ILGeneratorEmit4.TestEmitCalliNonBlittable [FAIL]
      Assert.Equal() Failure
      Expected: !gnirts tseT
      Actual:   Test string!
      Stack Trace:
         /home/debayan/coreclr/_/fx/src/System.Reflection.Emit.ILGeneration/tests/ILGenerator/Emit4Tests.cs(107,0): at System.Reflection.Emit.Tests.ILGeneratorEmit4.TestEmitCalliNonBlittable()
   System.Reflection.Emit.Tests.ILGeneratorEmit4.TestDynamicMethodEmitCalliNonBlittable [FAIL]
      Assert.Equal() Failure
      Expected: !gnirts tseT
      Actual:   Test string!
```

**System.Runtime.Extensions.Tests**
 ```
System.Tests.MathTests.Pow(x: 0, y: -3, expectedResult: -∞, allowedVariance: 0) [FAIL]
      Assert.Equal() Failure
      Expected:                   -∞
      Actual:                     +∞
      Stack Trace:
         /home/debayan/coreclr/_/fx/src/System.Runtime.Extensions/tests/System/Math.cs(69,0): at System.Tests.MathTests.AssertEqual(Double expected, Double actual, Double variance)
```
**System.Net.Requests.Tests**
 ```
System.Net.Tests.HttpWebRequestTest.KeepAlive_CorrectConnectionHeaderSent(keepAlive: False) [FAIL]
      Assert.Contains() Failure
      Not found: "Connection": "close"
      In value:  {"Method":"GET","Url":"/Echo.ashx","Headers": {
          "Connection": "Keep-Alive",
          "Via": "1.1 10.38.1.213 (McAfee Web Gateway 7.6.2.8.0.22994)",
          "Host": "corefx-net.cloudapp.net",
          "X-Forwarded-For": "10.228.199.76"
        },
        "Cookies": {},
        "BodyContent": "",
        "BodyLength": 0,
        "SecureConnection": false,
        "ClientCertificatePresent": false,
        "ClientCertificate": null
      }
      Stack Trace:
         /home/debayan/coreclr/_/fx/src/System.Net.Requests/tests/HttpWebRequestTest.cs(457,0): at System.Net.Tests.HttpWebRequestTest.KeepAlive_CorrectConnectionHeaderSent(Nullable`1 keepAlive)

```

**Comment by BruceForstall** [comment]
With https://github.com/dotnet/coreclr/pull/17090 merged, what are the next steps? Can you run the corefx tests manually, and simply? What is left to do to add corefx testing to the CI?

**Comment by sdmaclea** [comment]
@BruceForstall 

> What are the next steps?

Personally my next steps are to triage and fix broken tests.  I would like to fix as many as possible before Release_2.1 permanently locks down for arm64 changes.

>  Can you run the corefx tests manually, and simply?
I am running corefx tests locally.  It is not too bad.

@debayang's instruction in https://github.com/dotnet/coreclr/pull/17090#issue-176407389 are pretty close.

I think the arguments have changed during the review.  (Drop -ci_arch argument from instructions?)

> What is left to do to add corefx testing to the CI?

Someone would need to write/modify the netci.groovy / buildpipeline scripts to run corefx tests.
Probably need to initially configure trigger as manual 
Timeouts would have to be adjusted.  `System.IO.FileSystem.Tests` in particular is really long.  `System.Linq.Expressions.Tests` and `System.Xml.RW.XmlConvert.Tests` are also long.
There are several failing arm64 tests so an arm64 exclusion list would be needed to make CI green.

arm32 would be similar

**Comment by BruceForstall** [comment]
I'm going to close this issue; we have corefx testing on all platforms in the CI (and have for a while).
