### ISSUE TITLE
Tizen armel Cross Checked Innerloop Build and Test failing pretty much every PR

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/coreclr#17028]
https://ci.dot.net/job/dotnet_coreclr/job/master/job/armel_cross_checked_tizen_innerloop_prtest/

We need to remove the default trigger for this job unless/until it is made reliable.

**Comment by AndyAyersMS** [comment]
Not only always failing but usually taking 4 hours (plus up-front queue delay) to do so...

![image](https://user-images.githubusercontent.com/10121823/37626715-4abf4508-2b8e-11e8-95b1-5092a7b62991.png)

**Comment by 4creators** [comment]
The problem seems to be a test bug with incorrect builds coordination where next job before finishing waits for previous job checkpoint creating an infinite waiting chain:

Here the job https://ci.dot.net/job/dotnet_coreclr/job/master/job/armel_cross_checked_tizen_innerloop_prtest/2146/ waits for checkpoint from job 2145
```
for a checkpoint on dotnet_coreclr » master » armel_cross_checked_tizen_innerloop_prtest #2145
```

Wait in queue takes currently roughly 20 min to 2 hours while build and test run takes ~ 22 min. In the case of 2146 wait was 21 min, build and test 22 min and wait for checkpoint took at the moment I am writing this > 3 hours.

```
00:22:06.204 =======================
00:22:06.204      Test Results
00:22:06.204 =======================
00:22:06.205 # CoreCLR Bin Dir  : /home/coreclr/bin/Product/Linux.armel.Checked
00:22:06.205 # Tests Discovered : 23
00:22:06.206 # Passed           : 22
00:22:06.206 # Failed           : 1
00:22:06.206 # Skipped          : 0
00:22:06.206 =======================
00:22:07.717 4 minutes and 38 seconds taken to run CoreCLR tests.
00:22:09.283 + handle_exit
00:22:09.283 + set +x
00:22:09.283 The script is exited. Cleaning environment..
00:22:09.291 Build step 'Execute shell' marked build as failure
00:22:09.500 Perform an action if the job was performed on an Azure VM Agent. is waiting for a checkpoint on dotnet_coreclr » master » armel_cross_checked_tizen_innerloop_prtest #2145
```
