### ISSUE TITLE
Porting AppDomain to AssemblyLoadContext issue with ApplicationBase and PrivateBinPath

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#17156]
_From @Eilon on March 23, 2018 18:22_

_From @DomZZ on March 23, 2018 9:10_

I'm aware that AppDomain is deprecated and replaced partially by AssemblyLoadContext.
But I'm facing to a new problem that I'm not able to resolve  :

I have this code in .Net Framework 4.6.2 :
```
            var childDomain = AppDomain.CreateDomain("app", null, new AppDomainSetup() { ApplicationBase = Path.Combine(adminPath, "bin"), PrivateBinPath = Path.Combine(adminPath, "bin"), LoaderOptimization = LoaderOptimization.SingleDomain });
            AppDomainHelper.RunInAppDomain(childDomain, "Alcuin.Admin.Configuration.Services", "Alcuin.Admin.Configuration.Services.Application.HttpHandlerService", "CreateOrUpdateAppConfig", new object[] { tenantName, publicDbConnectionString, adminDbConnectionString, provider, dialect, driver, true });
```

I've replaced this by that :
```
            var assemblyFile = Path.Combine(versionDir, "admin", "bin", "Alcuin.Admin.Configuration.Services.dll");
            (string status, string log) = _runner.RunInThread<Tuple<string, string>>(assemblyFile, "Alcuin.Admin.Configuration.Services", "Alcuin.Admin.Configuration.Services.Application.HttpHandlerService", "CreateOrUpdateAppConfig", data);
```

RunInThread method call an override of AssemblyLoadContext and proper instanciate method and load dependencies, this is working well.

But the invoked code use AppDomain.CurrentDomain.BaseDirectory internally to load some files (related to the assembly we load), this is why we used :
```
new AppDomainSetup() 
{ 
ApplicationBase = Path.Combine(adminPath, "bin"), 
PrivateBinPath = Path.Combine(adminPath, "bin"), 
LoaderOptimization = LoaderOptimization.SingleDomain
}
```

to make sure invoked code can work without any change.

Do you know how can I port that into .NET Core with AssemblyLoadContext ?

Thanks

_Copied from original issue: aspnet/Home#2996_

_Copied from original issue: dotnet/corefx#28419_

**Comment by jkotas** [comment]
_From @Eilon on March 23, 2018 18:22_

_From @natemcmaster on March 23, 2018 16:30_

Hey @DomZZ, it looks like this issue belongs on https://github.com/dotnet/corefx. I don't see anything specific in this about ASP.NET Core. We can move the issue for you, or you can re-open it yourself it you'd like.

**Comment by jkotas** [comment]
cc @swaroop-sridhar

**Comment by jkotas** [comment]
The code in Alcuin.Admin.Configuration.Services.Application.HttpHandlerService.dll can get access files that are next to it using `Assembly.GetExecutingAssembly().Location`. Does this option work for you?

**Comment by DomZZ** [comment]
@jkotas, thanks for your help, I can easily fix that on my own code, but what if a nuget package or another thrid assembly is using AppDomain.CurrentDomain.BaseDirectory internally ?

I don't know, if it is related but I've reach another annoying issue, loaded assembly is built against full .net framework 4.6.2 and is using NInject and I get this error :
`             Message :
               Could not load type 'System.Runtime.Remoting.RemotingServices' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
              
              Stacktrace :
                at Ninject.Activation.InstanceReference.Is[T]()
                at Ninject.Activation.InstanceReference.IfInstanceIs[T](Action`1 action)
                at Ninject.Infrastructure.Language.ExtensionsForIEnumerableOfT.Map[T](IEnumerable`1 series, Action`1 action)
                at Ninject.Activation.Context.ResolveInternal(Object scope)
                at Ninject.Activation.Context.Resolve()
                at Ninject.KernelBase.Resolve(IRequest request, Boolean handleMissingBindings)
                at Ninject.ResolutionExtensions.Get[T](IResolutionRoot root, IParameter[] parameters)
                at Alcuin.DI.Common.NinjectDependencyResolver.GetService[TService]()
                at Alcuin.Admin.Configuration.Services.Application.HttpHandlerService.get_CurrentStorage()
                at Alcuin.Admin.Configuration.Services.Application.HttpHandlerService.CreateOrUpdateAppConfig(String name, String publicConnString, String adminConnString, String provider, String dialect, String driver, Boolean runFromAppDomain)`

This is not clear for me if .NET Core can load assemblies built with Full .NET Framework and if there is some limitations (can those be added to the documentation).

Should I understand that since Remoting is not part of .NET Core implementation, I can't load the assembly that use NInject ?

Thanks

**Comment by jkotas** [comment]
I agree that AppDomain.CurrentDomain.BaseDirectory starts to fall apart when files are spread over multiple directories. This is not really specific to AppDomains - this problem exists with single AppDomain too. One way to make these work is to dump everything into a single directory...

> This is not clear for me if .NET Core can load assemblies built with Full .NET Framework

It can load them, but they will work only if they avoid features that are not in .NET Core.

**Comment by DomZZ** [comment]
Unfortunatly, I need to load the same assemblies in different versions then the same directory is not an option for me, it seems I am in a corner now and have to switch back to Full .Net Framework.
It was our 1st try to switch some code to .Net Core, but I think we didn't choose the right code to port since it used a lot of abandonned technologies.

I will have a look on how .Net Core evolve in the future, and how it handles this situation.

Thanks for your help.
