### ISSUE TITLE
[Arm64/Linux] Crosscomponent

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#17349]
@janvorli  I have been wotking on adding support for crosscomponent when cross building from x64 for arm64.

The issue I am having is that when building for crosscomponent, it assumes I have to be crosscompiling.

My workaround is to populate the cross/x64 directory, so I can "cross" compile with `ROOTFS_DIR="/"`

Any better suggestions.

**Comment by janvorli** [comment]
@sdmaclea You just need to make sure that the `CROSSCOMPILE` is unset (not just set to 0 since the src/pal/tools/gen-buildsys-clang.sh uses the "-n" test to determine whether the cross compile is on or off) in the build.sh in the `build_cross_arch_component` for the case of x64 crosscomponents targeting arm64. The following seems to work:

```diff
diff --git a/build.sh b/build.sh
index 1cb0d7e..9666461 100755
--- a/build.sh
+++ b/build.sh
@@ -341,6 +341,9 @@ build_cross_arch_component()
         if [ "$__HostArch" == "x64" ]; then
             export CROSSCOMPILE=1
         fi
+    elif  [[ "$__BuildArch" == "arm64" && "$__CrossArch" == "x64" ]]; then
+        unset CROSSCOMPILE
+        __SkipCrossArchBuild=0
     else
         # not supported
         return
```

**Comment by sdmaclea** [comment]
Thanks that works
