### ISSUE TITLE
unable to run after upgrading to .net 2.0 => 2.1 [terminating with uncaught exception of type EEFileLoadException*]

### ISSUE THREAD

**Issue by davidparker** [dotnet/coreclr#17529]
# terminating with uncaught exception of type EEFileLoadException*

when in ( visual studio code [mac os x] ) I go debug -->  run
It never runs, everything fails with:  terminating with uncaught exception of type EEFileLoadException*

All I have done is upgraded 2.0 -> 2.1   changed launch.json  to the following:

"program": "${workspaceFolder}/bin/Debug/netcoreapp2.1/NetSo.dll",

Update nuget

removed DotNetCliToolReference  as they are no longer needed   ( now part of SDK )

Run  dotnet build  ( success )

and then run  

# General

dotnet --version
2.1.300-preview2-008530

I get no other output, as this seems to be more of a fail to launch issue, than a code issue
especially as no code changes have taken place,  and no code exceptions are thrown.   This seems more like that MACOS  wont run the new core framework.

I have attached the output from OSX  for clarity.  Any advice would be much appreciated.

[core-crash.mac.txt](https://github.com/dotnet/coreclr/files/1903405/core-crash.mac.txt)

**Comment by janvorli** [comment]
This looks like the #16438. Does your app happen to open a large number of file handles (which can also mean large number of network connections)? Can you try to run `lsof -r 1` in a console and watch if it dumps a huge number of file descriptors for your process when you attempt to start the app?
If you can publicly share your app, I could try to debug it for you.

**Comment by janvorli** [comment]
By public I have really meant if you can share it with me. So if you are ok with that, you can share the zip. You can send it or just a link to it to janvorli at Microsoft dot com.

**Comment by davidparker** [comment]
:-)   yep of course  sorry.    I have sent that through.   Just to update the thread.  the permissions was a separate issue, and fixing that does not resolve the bug.

**Comment by davidparker** [comment]
I found the issue.    So i add added SSL url to my launch.  and did everything step by step.   it is at SSL that it broke.   Sp Created a new dotnet new razor  to check files for changes and spotted this:

`services.AddMvc()..SetCompatibilityVersion(CompatibilityVersion.Version_2_1)`

once I added this extra nuget to my startup, it run and resolved the issue.

However this is of course a un-managed bug.   however i understand that this is actually coming from a runtime that is not the version i want to run.    I.E   I tell it I run .netcore2.1   but on launch it seems to run as netcore2.0      I could be wrong,    but adding that line solves the issue.

I must say though, with the new preview 2 of ef core on top of all this.   it runs so fast now it looks like its cached :-)    great work.

as a note:   VSCode   has no intellisense for the compatibility stuff,  but that's just a case of waiting for the plugins to be updated.   but thought I would mention, incase someone adds this fix, but wonders why it is underlined in red.

**Comment by janvorli** [comment]
Using the code you've sent me, I can repro the issue. Although you have found a fix, I want to understand the real culprit. I am looking into it.

**Comment by davidparker** [comment]
Yeah feel free.   You would expect it to default to highest version if no
compatibility versiOn is specified.  Or.   Run the version I have set in
startup.

**Comment by janvorli** [comment]
So the real culprit due to which it fails is an error:
FUSION_E_REF_DEF_MISMATCH for file "Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed". 
The error means that the runtime tried to load a different version of the assembly than the version of the reference assembly that was used during the build.

This looked strange since your NetSo.csproj doesn't reference the Newtonsoft.Json directly. I've looked closely at your NetSo.csproj and I was able to get rid of the issue by changing versions of Microsoft.AspNetCore.All and Microsoft.EntityFrameworkCore.Tools to 2.1.0-preview**2**-final. 
So it looks like there was some problem building towards preview2 2.1.0 and referencing preview1 packages.

**Comment by davidparker** [comment]
Nice find.   Yeah newtonsoft is build in now I think.   Just like with
azure functions etc.  It actually plays Havok all over the ms stack.  It
would probably be good to just add this to the release paper.  Mainly for
people using vscode etc  could you tell me how you got vscode.  To output
that error.   So in future I can better debug issues like this myself?
Really loving how much cross platform has matured now so will be doing
everything in core from now on and understanding how to pull debuts like
that would really help


Many thanks


Dave

**Comment by janvorli** [comment]
To get this error, one needs to go really low level. Since the issue comes from the native part of the runtime, you need to use lldb. I have actually rebuilt the runtime in debug version so that I can see all the parameters and locals in the native code that are otherwise optimized out.
This exception would normally surface in your managed code, but unfortunately, the exception handling needed to have access to types in the newtonsoft.json assembly since there is likely a catch of one of their exceptions on the call stack and it needed to load the exception type. And then it failed again, unable to handle the exception and so it aborted.

As discussed in the #16438, we'll need to try to do something to report the exception at least in some way that is meaningful to the user.

**Comment by davidparker** [comment]
Argh okay no probs.   As a site note though.   Kinda passing thought.
Shouldn’t the new.  Be able to run the old  or is 2.1 a breaking change?
