### ISSUE TITLE
[x86/Windows] Failure in jitstress=2 jitstressregs=3 job

### ISSUE THREAD

**Issue by erozenfeld** [dotnet/coreclr#17634]
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86/job/jitstress/job/x86_checked_windows_nt_jitstress2_jitstressregs3/473/consoleText

BEGIN EXECUTION
         "D:\j\workspace\x86_checked_w---508bfa85\tests\..\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\corerun.exe" MaskMove_r.exe 
        Expected: 100
        Actual: 73294136
        END EXECUTION - FAILED
        FAILED
        Test Harness Exitcode is : 1
        
  To run the test:
  > set CORE_ROOT=D:\j\workspace\x86_checked_w---508bfa85\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root
  > D:\j\workspace\x86_checked_w---508bfa85\bin\tests\Windows_NT.x86.Checked\JIT\HardwareIntrinsics\X86\Sse2\MaskMove_r\MaskMove_r.cmd
  
        Expected: True
        Actual:   False

**Comment by RussKeldorph** [comment]
@fiigii

**Comment by fiigii** [comment]
It may be a GC info or RA issue. I looked that the codgen and encoding is correct.
`vmaskmovdqu` uses `edi` as the **implicit dst register** that may not be properly recognized by GC or RA
```asm
vmaskmovdqu xmm0,xmm1
```

@CarolEidt @AndyAyersMS How can investigate this kind of issue?

**Comment by CarolEidt** [comment]
> maskmovdqu uses edi as the implicit dst register that may not be properly recognized by GC or RA

Yes that looks like it might be the case. I am investigating this, and in `Main`, the return value is in `edi` and it is getting trashed by the maskmov.

**Comment by CarolEidt** [comment]
To answer your question about how to investigate this kind of issue, there's not great documentation on debugging JitStress, and the stress modes can really make the code difficult to navigate, not to mention that not all the `COMPlus` variables related to stress work properly. I usually set `COMPlus_JitStressModeNamesNot=STRESS_EMITTER` since that rarely seems to cause issues, and it makes the dumps and disassembly even harder to read. You can also add stress modes to that "not" list (the ones you see in the jitdump) to narrow it down.
In this case, since it also included `COMPlus_JitStressRegs`, I was able to determine (by enabling the ifdef'd out code here: https://github.com/dotnet/coreclr/blob/master/src/jit/lsra.cpp#L676) which method was failing with `COMPlus_JitStressRegs`. Then I just debugged my way through the code. I knew that the return value in `edi` was bad, but I hadn't realized that `edi` was killed by the `maskmovdqu` until I stepped through it, and *then* I saw your post.

**Comment by AndyAyersMS** [comment]
We should think about investing in some automated "bisect" tools for failures like these that reliably repro. I have bits and pieces of this lying around from a former project that I can perhaps contribute.

For jitstress you can try and debug the failure but sometimes it can be more effective to first isolate the bad method by selectively enabling stress. That is something we should be able to automate. Then we can start disabling individual stress modes for that method until we pin down the one that causes trouble. Etc.
