### ISSUE TITLE
Updating coreclr toolset

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#17684]
For non-Windows builds, we generally build with clang 3.9, though for arm32 we build with clang 5.0, and at least in the CI, arm64 builds with clang 3.8.

Should these all be updated to something consistent and newer, e.g., clang 6.0?

What is the process for making this decision and making it happen?

@RussKeldorph @janvorli @jkotas

**Comment by kasper3** [comment]
> Clang6.0 is still not a stable branch

This is incorrect.

https://packages.ubuntu.com/bionic/clang-6.0

Clang 6.0 is a released product since March 8. Ubuntu 18's default repo has Clang 6.0 toolchain: http://llvm.org/ (see the information on right hand side)

If you are referring to http://apt.llvm.org/, that is not considered official package by debian-devel or ubntu-devel. I have confirmed this information from their official IRC channels. Thei

LLVM roadmap as the authentic source of truth.

**Comment by janvorli** [comment]
@kasper3 yes, I was getting that information from http://apt.llvm.org/. I was thinking that "released" and "stable" are different things. But clearly I was wrong.

**Comment by kasper3** [comment]
http://apt.llvm.org/ is also updated with fixed labels: v6 is now under "stable" branch and `apt install liblldb-6.0-dev` installs LLDB.h and other API headers (tested on artful).

**Comment by Daniel-Svensson** [comment]
Any current plan to update clang version? I have some new code which seems to crash clang 3.9.1 but works in newer releases.

**Comment by janvorli** [comment]
You can also use clang 4.0, 5.0 or 6.0 for building coreclr if you want. For official builds, we use clang 3.9.1 on x64 since we didn't hit any issues with it. We did hit some issues on ARM in 3.9.1 (incorrectly compiled synchronization intrinsics in non-optimized builds), and so we use clang 5.0.2 for arm builds.

**Comment by jashook** [comment]
I am considering this complete as we are now standardized on one version of clang.
