### ISSUE TITLE
ICorProfiler retrieve function arguments in JitCompilationStarted

### ISSUE THREAD

**Issue by bobuva** [dotnet/coreclr#17741]
I've seen this done before but for the life of me, I'm having trouble finding a function's arguments when my ICorProfiler profiler's JitCompilationStarted event is called. I've got the `PCCOR_SIGNATURE` from `IMetaDataImport->GetMethodProps` but I don't have the actual arguments being passed in the function.

Is there an interface method I can call to get them?

thanks.

**Comment by RussKeldorph** [comment]
@dotnet/dotnet-diag

**Comment by davmason** [comment]
@bobuva Once you have the `PCCOR_SIGNATURE` you have to decompress it to read it. It's not code I'm super familiar with, but you can see how we do it in the DAC at https://github.com/dotnet/coreclr/blob/30b07e10fbb477a0d08d0d2ec022f51d8bd3a9a9/src/ToolBox/SOS/Strike/metadata.cpp#L605 

If you have specific questions about what's happening there I can answer them, but hopefully this is enough to follow along and figure out what you need.

**Comment by noahfalk** [comment]
I think @bobuva wanted the argument values rather than parameter types? The parameter types come from the signature as David described. If you want the arguments check out https://docs.microsoft.com/en-us/dotnet/framework/unmanaged-api/profiling/functionenter3withinfo-function

The JitCompilationStarted callback only triggers the first time a method is invoked whereas the enter, leave, tailcall callbacks will be invoked on every invocation of the function - optionally with arguments that were passed in that invocation.

**Comment by bobuva** [comment]
@noahfalk I have to use JitCompilationStarted as I'm injecting prolog and epilog calls into selected methods. The Enter/Leave hooks would add too much overhead. I may have come up with a way to do this from JitCompilationStarted. Does this seem right to you?

1. Figure out how many parameters the function takes (get that from the signature)
2. Create an object array that will contain them.
3. For each parameter, find where it is located <-- THIS is my hangup right now.
        a) add that parameter into the object array (boxing if necessary)
        b) add a DUP instruction for the array to put the modified version on top of stack.

**Comment by noahfalk** [comment]
If you are worried about the overhead of getting EnterLeaveTailcall (ELT) callbacks on all functions, https://docs.microsoft.com/en-us/dotnet/framework/unmanaged-api/profiling/icorprofilerinfo3-setfunctionidmapper2-method provides you the capability to only instrument functions of your choosing. 

It sounds like the path you are pursuing now is IL instrumentation. Both are perfectly viable, though IL instrumentation tends to be both more powerful and correspondingly more complicated to use. 

In terms of figuring out where parameters are located, presumably the 'location' that is useful here is the parameter index within the signature. Once you know that index you can load the argument with the 'ldarg' IL instruction. In order to determine the index I'm guessing you start with some piece of information that says what parameters are interesting to you, for example a particular parameter name or parameter type. Then you parse the signature (the CLI ECMA spec describes the format) to decode the parameter list and determine which indices have the names/types you are interested in. Not sure if that answered the question?

**Comment by bobuva** [comment]
Thanks @noahfalk. I'm not that familiar with `SetFunctionIDMapper2` but will look at it.

What you described for getting parameter index to do a `ldarg` makes sense. I think I'll stick with this approach for now. Maybe look at the enter/leave option later.
Thanks!

**Comment by bobuva** [comment]
@noahfalk I've made some progress, but I'm continuing to get an invalid program exception thrown when I try using my IL injection method to pass function parameters to my (injected) managed method. I've written it up [here](https://social.msdn.microsoft.com/Forums/en-US/3161143d-8ab0-48fa-a41f-a3ada20bbfc1/create-and-populate-array-with-function-arguments-in-il?forum=clr) and I was wondering if you had any insight into what I might be doing wrong. By the way, I need to use this technique rather than the Entry/Leave because I want my managed agent injected into the app.

**Comment by noahfalk** [comment]
For this general class of issue there are a few things you can try:
1) Write an example of conceptually what the instrumented code would look like in C#, then carefully compare the compiler output to what you generated using ildasm.
2) Try to write your instrumented version of the assembly to disk and then use peverify. The profiler APIs don't give you a good way to do this directly, but you might be able to replicate the instrumentation using ref.emit, CCI, Cecil, or any other IL binary generating library.
3) Now that CoreCLR is open source, you can get symbols/source for the runtime (or build your own) and then look at the runtime logic that threw the InvalidProgramException

For your specific case - its suspicious to me that your function to add a local didn't take any parameter that indicates the type of the local but I only gave it a cursory look.

**Comment by bobuva** [comment]
Thanks @noahfalk . Makes sense. I should try emitting with one of those other options and compare. I haven't built the CoreCLR yet but this is a good time to start that too.

My AddNewLocal method, by the way, has ELEMENT_TYPE_SZARRAY and a mdTypeRef token for it that I defined since it was not already in the TypeRef table, hard-coded for now since that's the only local I'm currently adding.

**Comment by bobuva** [comment]
@noahfalk Thanks very much for the direction you've provided me with this problem. I'm going to try saving an assembly from the ModuleLoadFinished profiler handler after rewriting a function from that handler, and then running it against ILVerify once I've got that building. One problem: there's no easy way to write out an assembly using an API from within a profiler event handler that I can see. Can you suggest a way forward with that?

**Comment by bobuva** [comment]
Guess I had a brain fart -- there's IMetaDataAssemblyEmit. I guess I have to emit everything all over again, instead of just changing one method.

**Comment by bobuva** [comment]
I'm closing this issue after many months as I figured out how to get the function arguments to be passed to  a function I created in IL. There is a bit of nuance required, in particular knowing that CEE_DUP needs to appear between operations when adding the arguments to an array.
