### ISSUE TITLE
Move Concurrent collections into shared

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/coreclr#17751]
These seem like they can be reconciled 
```
C:\git\coreclr\src\mscorlib\src\System\Collections\Concurrent\ConcurrentDictionary.cs
C:\git\coreclr\src\mscorlib\src\System\Collections\Concurrent\ConcurrentQueue.cs
C:\git\coreclr\src\mscorlib\src\System\Collections\Concurrent\ConcurrentStack.cs
C:\git\coreclr\src\mscorlib\src\System\Collections\Concurrent\IProducerConsumerCollection.cs
```
with their CoreFX cousins:
```
C:\git\corefx\src\System.Collections.Concurrent\src\System\Collections\Concurrent\ConcurrentDictionary.cs
C:\git\corefx\src\System.Collections.Concurrent\src\System\Collections\Concurrent\ConcurrentQueue.cs
C:\git\corefx\src\System.Collections.Concurrent\src\System\Collections\Concurrent\ConcurrentStack.cs
C:\git\corefx\src\System.Collections.Concurrent\src\System\Collections\Concurrent\IProducerConsumerCollection.cs
```

Usual procedure is 
1. Upgrade CoreCLR versions to have functionality of CoreFX ones. This may mean just copying over the CoreFX ones. Move to C:\git\coreclr\src\mscorlib\shared\System\Collections\Concurrent
1. Prepare a PR in CoreFX that deletes the 4 files there and instead pulls them from C:\git\corefx\src\Common\src\CoreLib\System\Collections\Concurrent
1. When mirror brings those files, merge the PR.

@maryamariyan

**Comment by jkotas** [comment]
> Prepare a PR in CoreFX that deletes the 4 files there and instead pulls them from C:\git\corefx\src\Common\src\CoreLib\System\Collections\Concurrent

This step should either delete the files from System.Collections.Concurrent, or the files in step 1 has to be ifdefed out so that the implementation in mscorlib remains internal.

We do not want to have two public types with the same name in the implementation. It breaks scenarios like scripting. Verification added in https://github.com/dotnet/corefx/pull/19800 should fail the build if you introduce duplicate public types.

**Comment by danmosemsft** [comment]
Ah, interesting. OK, that is easily done.
