### ISSUE TITLE
Show unmanaged stack frames in exception stack trace

### ISSUE THREAD

**Issue by Rohansi** [dotnet/coreclr#17871]
Is it possible to list unmanaged stack frames with the transitions in exceptions, similar to how VS displays the call stack when mixed mode debugging is being used? In our application there are lots of transitions between C# and C++ and with the current behavior the stack traces sent to our logs get cut off at the most recent transition.

It doesn't have to specifically be shown with `ToString` or be included in `StackTrace` I'm just wondering if there's any way to do this, or if not, how would we accomplish this?

**Comment by RussKeldorph** [comment]
@dotnet/dotnet-diag

**Comment by noahfalk** [comment]
There isn't any functionality built into the runtime to do this and I'm not aware of any libraries offhand that that bundle all this up to make it easy (if you do find one I'd love to know). You could build something to do it but I'd guess its going to take some non-trivial time to do so.  There would be a few elements to it:
1) Decoding native stack frames - The native stack trace APIs are all OS specific (for example RtlVirtualUnwind on windows, libunwind on Linux). Assuming you want named methods and not raw addresses then you also need to load symbols, and the various symbol formats and libraries to parse those formats are also OS specific. On windows you probably want DIA (https://msdn.microsoft.com/en-us/library/x93ctkx8.aspx) and on Linux libdwarf (https://www.prevanders.net/dwarf.html). 
2) Capturing the stack at the right point in execution - Conceptually I'm guessing your control flow looks like this:

    ```
    void OuterManaged()
    {
       int err = NativeCode1();
       if(err != Success)
       {
           throw new Exception();
        }
    }

    int NativeCode1()
    {
        return NativeCode2();
    }

    NativeCode2()
    {
        return InnerManaged();
    }

    int InnerManaged()
    {
        try
        {
             DoSomeWork();
             return Success;
        }
        catch(Exception e)
        {
             return Failure;
        }
    }
    ```

Depending on exactly how you are doing your interop the try/catch may not be directly in your code, but I'm assuming they are there somewhere. To capture the native frames you would need to invoke the stackwalk code at some point while NativeCode2 was still on the stack, perhaps by modifying that frame or perhaps running within InnerManaged(). To capture the managed frames you would need to save off the various exception objects that are being thrown and caught.

3) Stiching it all together - Somehow you would need to aggregate all the exception/stack trace data you are collecting and get it associated with a single exception object. One possibility might be to use some thead static storage, and then copy the results to the Data property on the exception. The managed stack trace regions won't overlap, but the native ones will unless you take care to filter then based on specific stack ranges. You could look at the current stack pointer around the transition boundaries, or you might be able to infer where the native - managed boundaries are by looking at the code pointers for each frame and checking if they resolve back to loaded modules or jitted code. There is some added complication in that route because AOT compiled managed code will look like native code to a first approximation and you would need to more closely scrutinize the image to determine the difference.

Admitedly I've given a pretty cursory overview and there is a lot of detail in there left to be filled in, but hopefully this helps a bit if you are still feeling determined to forge ahead. There is also a more scoped option where you would only chain the managed exceptions together but ignore the native parts. That would at least save you from the most complicated bits and reduce the problem to saving/recovering some managed exception objects.

HTH,
 -Noah

**Comment by Rohansi** [comment]
It's like that but we don't have exceptions going through. So if an exception was thrown and caught in `InnerManaged` the runtime-generated stack trace wouldn't show frames below `InnerManaged` because it seems to stop as soon as it hits some native code.

Stitching the exceptions together without listing unmanaged frames, while showing a transition, would be perfect in my opinion. There's enough information there to get an idea of what happened.

**Comment by noahfalk** [comment]
Exception stack traces only contain the frames that the exception unwound through. It sounds like you want to throw/catch exceptions within InnerManaged that contain frames from OuterManaged even though control flow never unwinds back to OuterManaged? If you use System.Diagnostics.StackTrace you can get a stack trace that should include all managed code frames on the thread, but it would be up to your app to synthesize that stack with the unwind frames that are captured in the Exception. Is that what you are looking for?

```
using System;

namespace ConsoleApp3
{
    class Program
    {
        static void Main(string[] args)
        {
            DoWork();
        }

        static void DoWork()
        {
            try
            {
                Throw();
            }
            catch(Exception e)
            {
                Console.WriteLine("Exception stack:\n" + e.StackTrace);
                Console.WriteLine("Full stack:\n" + new System.Diagnostics.StackTrace());
            }
        }

        static void Throw()
        {
            throw new Exception();
        }
    }
}
```
