### ISSUE TITLE
[RyuJIT] Sse2.Extract with sign-extension not working properly

### ISSUE THREAD

**Issue by gdkchan** [dotnet/coreclr#17957]
I was trying the new X86 intrinsics and noticed that when casting a signed type extracted from a vector to a larger signed type, the value is not sign-extended, it is zero-extended.

The following program demonstrates the issue:
```csharp
using System;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;

namespace SseTest
{
    class Program
    {
        static void Main(string[] args)
        {
            Vector128<short> test = Sse2.SetVector128(0, 0, 0, 0, 0, 0, 0, -1);

            Console.WriteLine(ExtractShortLow(test));
            Console.WriteLine(ExtractShortLow2(test));
        }

        private static int ExtractShortLow(Vector128<short> Vector)
        {
            return Sse2.Extract(Vector, 0);
        }

        private static int ExtractShortLow2(Vector128<short> Vector)
        {
            short tmp = Sse2.Extract(Vector, 0);
            return tmp;
        }
    }
}
```

On debug mode, the output is:
```
65535
-1
```

On release, it is:
```
65535
65535
```

The expected output is:
```
-1
-1
```

dotnet version: `2.1.300-rc1-008673`.
Sorry if it was already reported elsewhere.

**Edit:** The issue also happens with sbyte, but not with int -> long.

**Comment by fiigii** [comment]
Thanks for capturing this issue.

Looks like this problem is caused by the zero-extension semantics of `pextrw` instruction, which extracts 16-bit data and puts it into a 32-bit GP register with zeroed 31th-16th bits.

@CarolEidt @mikedn shall we change the APIs of extracting small integers to only return unsigned scalar types?

**Comment by CarolEidt** [comment]
IMO, the API should closely reflect the target hardware, so it would seem we should change the API to only return unsigned types. However, I could be convinced otherwise.

**Comment by mikedn** [comment]
Hmm, the fact that the API supplies an overload taking `Vector128<short>` is a convenience since neither the instruction nor the C intrinsic care about the sign. Thus we could drop the `short` overload and call it a day, those who need it can resort to `StaticCast`.

But I'm not sure that zero extending is the real problem. Can't speak for @gdkchan but to me it looks like this:
* The `PEXTRW` documentation clearly states that bits 16-32 are zeroed - "Extract the word specified by imm8 from mm and move it to reg, bits 15-0. The upper bits of r32 or r64 is zeroed."
* The `PEXTRW` documentation shows that a 32 bit value is produced but `Extract` method returns `short`/`ushort`
* Since the return is `short` I do expect the bit pattern `0xFFFF` to be converted to `int` as -1. The fact that `PEXTRW` doesn't sign extend is irrelevant here and the fact that you don't get -1 is really a JIT bug introduced by the wrong return type of the method.

So I'd just change the return type of those methods to `int`. Incidentally, that's exactly what the C/C++ intrinsic does.

**Comment by fiigii** [comment]
> So I'd just change the return type of those methods to int. Incidentally, that's exactly what the C/C++ intrinsic does.

Good point, this makes sense.

**Comment by gdkchan** [comment]
IMO, the best solutions are:

- Implementing the sbyte/short overloads of Extract as helper methods similar to other methods (like the Set*Vector128 methods), so this particular method could be implemented as:
```csharp
public static short Extract(Vector128<short> value, byte index)
{
    return (short)Extract(Sse.StaticCast<short, ushort>(value), index);
}
```
- Removing the sbyte/short overloads, since they map to the same instructions as their unsigned counterparts, we could just use the unsigned overload instead (by using a StaticCast). Assuming that the signed overloads were changed to either return a ushort or a int, the only advantage of using it over the unsigned one is that we wouldn't need to use the StaticCast but that's it.

I personally prefer the first solution.

**Comment by fiigii** [comment]
> Implementing the sbyte/short overloads of Extract as helper methods similar to other methods (like the Set*Vector128 methods), so this particular method could be implemented as:

I am not sure if it is worth to have these “official” helpers with managed implementation. Users can write them easily. Meanwhile, this solution would complicate JIT implementation because an intrinsic method can be true intrinsic or managed helper on different overloads, so we have to check the return type to reject expanding the short/ushort versions and always to expand the int version in the JIT.

BTW, the current Set*Vector128 implementation was a temporary solution to catch the 2.1 deadline. I will move them into JIT for better codegen quality.
