### ISSUE TITLE
CoreCLR failed when build with MSVC on Windows

### ISSUE THREAD

**Issue by shanshan0309** [dotnet/coreclr#18042]
Hello,

I tried to build CoreCLR on Windows with VS2017 Update2. It failed to build due to the error CS2001: Source file 'D:\CoreCLR\src\bin\obj\Windows_NT.x86.Release\System.Private.CoreLib\..\eventing\DotNETRuntimeEventSource.cs' could not be found. This issue is caused by master branch revision [0fbd0f5](https://github.com/dotnet/coreclr/commit/0fbd0f535e566bcde591701adc2de51ee0f020af). Could you please help take a look at this? Thank you!

**You can repro this issue as the steps below:**
1. git clone https://github.com/dotnet/coreclr D:\CoreCLR\src
2. Open a clean x86 prompt (C:\windows\syswow64\cmd.exe) and browse to D:\CoreCLR\src
3. build x86 release -Rebuild -- /clp:ShowCommandLine

**Error info:**
CSC : error CS2001: Source file 'D:\CoreCLR\src\bin\obj\Windows_NT.x86.Release\System.Private.CoreLib\..\eventing\DotNETRuntimeEventSource.cs' could not be found. [D:\CoreCLR\src\src\System.Private.CoreLib\System.Private.CoreLib.csproj]

**Comment by jkotas** [comment]
cc @brianrob

**Comment by brianrob** [comment]
It looks like this failure occurs because -Rebuild causes /t:rebuild to be passed to every invocation of msbuild.  This results in any msbuild command that operates on build.proj attempting to do a compile of System.Private.CoreLib.  I would have expected  ```build x86 release -Rebuild windowsmscorlib``` to cause multiple builds of System.Private.CoreLib just because there are multiple calls to msbuild build.proj that now get /t:rebuild applied to them, but instead this just fails with an error that the dev workflow has changed.

@jkotas, @wtgodbe do you know if the intention of -Rebuild is just to pass /t:rebuild to the managed components build, or is it something else?  I can attempt to fix the script, but I would like to make sure that I understand the expected behavior here.

**Comment by jkotas** [comment]
The `rebuild` option was added as part of the grand dev workflow unification. As far as I know, it never worked well. I never use it myself. I would not mind deleting it to avoid confusion and maintenance burden.

cc @markwilkie

**Comment by brianrob** [comment]
Thanks @jkotas.

@markwilkie, do you have any concerns with this?  If not, I will remove -Rebuild.

**Comment by brianrob** [comment]
@shanshan0309, just to confirm, if you don't use -Rebuild, do things work OK?

**Comment by shanshan0309** [comment]
Thanks Brian for looking into this issue. It works well when I don't use -Rebuild.

**Comment by brianrob** [comment]
Thanks @shanshan0309 for confirming.  I will work on a PR to remove -Rebuild.

**Comment by brianrob** [comment]
@jkotas, it looks like -Rebuild is consumed by run.exe and not directly by build.cmd/sh.  I can remove it from the usage info for the scripts, and from docs, but that obviously won't affect run.exe.  Do you think it's worth catching uses of -Rebuild and failing the build with a message that -Rebuild isn't supported?  I doubt that we want to remove -Rebuild from run.exe for all repos.

**Comment by jkotas** [comment]
Sounds reasonable to me.

**Comment by shanshan0309** [comment]
Thank you @brianrob and @jkotas!

**Comment by brianrob** [comment]
Thanks @shanshan0309 for reporting this.
