### ISSUE TITLE
Security-Transparent Code?

### ISSUE THREAD

**Issue by eriohl** [dotnet/coreclr#1807]
I'm aware that CAS is pretty much dropped but what about [security transparent code](https://msdn.microsoft.com/en-us/library/dd233102(v=vs.110).aspx)? The attributes are all there (SecurityTransparent, SecurityCritical etc.) but CoreCLR doesn't seem to actually care about them. Is this something that is suppose to work in CoreCLR (now or in future)?

**Comment by ellismg** [comment]
I believe the story here is that CoreClr no longer enforces any of these attributes.  IIRC, Shortly before open-sourcing @jkotas removed the code that did the stackwalking to enforce this stuff.

I can't recall if the long term plan was to continue to keep mscorlib.dll attributed correctly (which would imply we should open source our internal tools that validate these attributes) or just remove them.  Jan would know for sure.

I think we were in agreement that we would remove the attributes from CoreFX, but I don't know if anyone has done a pass yet.

**Comment by jkotas** [comment]
The enforcement of security transparency was disabled by default by: https://github.com/dotnet/coreclr/commit/725d6a91fffdf4603c8a9c74e15cbc83ebf0e3d6

We do plan to keep the enforcement code in CoreCLR (disabled by default) - in case somebody wants to experiment with it, in case it is needed in future, etc. We do not plan to maintain the annotations in CoreFX because of it is expensive to do, and it is not required for any scenario targeted by .NET Core today.

**Comment by eriohl** [comment]
Ok. That pretty clear then. Thank you.
