### ISSUE TITLE
NgenR2R fails on WinRT apps with references to .winmd files

### ISSUE THREAD

**Issue by rido-min** [dotnet/coreclr#18166]
moved from [dotnet/issues/758](https://github.com/Microsoft/dotnet/issues/758)

Using NgenR2R with a desktop app referencing UWP APIs as described in https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-enhance leads to errors during AOT compilation.
This may be fixed by setting Copy Local on the .winmd files (as recommended in the above link).
The NgenR2R failure needs to be understood. I heard that it may have something to do with coreclr assemblies being included in the input. If this is the case, we should fix it. If it's just the copy local setting, the error may be expected, but we could still provide a better experience by excluding .winmd files.

**Comment by sbomer** [comment]
There are two failure modes here causing this:

1. Due to the WinRT reference assemblies: NgenR2R package passes `@(ReferenceCopyLocalPaths)` as platform assemblies paths, with higher priority than the special ref assemblies that ship with the package. It ends up trying to load mscorlib.dll from `C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETCore\v4.5`. This fails because it can't load reference assemblies (which have a special attribute preventing them from being loaded by the runtime).
A simple workaround is to set CopyLocal to true on any reference assemblies.

2. Due to references to .winmd files: NgenR2R tries to AOT-compile everything in `@(ReferenceCopyLocalPaths)`, but it can't compile .winmd fails so it fails. The fix is to set CopyLocal on .winmd files (which was recommended in the article linked above anyway).

@rido-min I suggest we recommend setting CopyLocal to true. If that's not feasible for some reason, we can discuss other options. Thoughts?

**Comment by jkotas** [comment]
NgenR2R is .NET Framework specific tool. CoreCLR repo is not for tracing .NET Framework specific issues.
