### ISSUE TITLE
JIT: Eliminate RegTracker

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#18179]
Now that `LEGACY_BACKEND` is gone, do we still need RegTracker?

**Comment by BruceForstall** [comment]
cc @CarolEidt @dotnet/jit-contrib

**Comment by CarolEidt** [comment]
I believe that the `RegTracker` is not longer useful. It was used by the legacy backend to avoid reloading local variables or setting a register to a constant if it was already available in a register. Some constant reuse has been implemented in the register allocator, and future work to support reuse of (memory-based) locals or constants would be done elsewhere (e.g. see issue #6131).

Currently the `RegTracker` methods only call `regSet->rsSetRegsModified()`, however the register allocator should already be doing this for any registers it allocates, as well as any registers killed by an instruction. Furthermore, the code generator should already be doing this for any additional registers used, for example, in prolog or epilog code.

Calls to these methods should be replaced with methods on `RegSet` that simply verify that the register is in the modified set, and assert otherwise (and would be a no-op in retail builds), e.g.:

- `RegSet::verifyRegUsed(regNumber reg)`
  - this would replace calls to `RegTracker::rsTrackRegTrash()`, `RegTracker::rsTrackRegIntCns()`, `RegTracker::rsTrackRegLclVar()` and RegTracker::rsTrackRegCopy().
- `RegSet::verifyRegistersUsed(regMaskTP regMask)`
  - this would replace calls to `RegTracker::rsTrashRegSet()`

**Comment by CarolEidt** [comment]
@BruceForstall - I thought this might be an easy-ish issue for the Hackathon. What do you think?

**Comment by BruceForstall** [comment]
Sure, seems reasonable. Doing the removal/replacement as you've spec'ed would be straightforward. I'd hope full asm diffs could be run to verify it's a no-diff change.

**Comment by CarolEidt** [comment]
@BruceForstall - good suggestion.

**Comment by CarolEidt** [comment]
This issue would be a good "getting started" project for someone wanting to gain familiarity with the JIT. In preparation for working on this:
- Clone and build coreclr on your chosen target
- Read the JIT overview and tutorial documents:
  - https://github.com/dotnet/coreclr/blob/master/Documentation/botr/ryujit-overview.md and 
  - https://github.com/dotnet/coreclr/blob/master/Documentation/botr/ryujit-tutorial.md.
- Clone and build jit-utils (https://github.com/dotnet/jitutils). There are instructions there for how to run jit-diffs.
