### ISSUE TITLE
Transition from .Net Framework to Coreclr : Moving from GACed Dlls

### ISSUE THREAD

**Issue by ashishnegi** [dotnet/coreclr#18405]
We are porting our SDK from .NET Framework to Coreclr.

As a platform, we have SDK and runtime c# dlls. Most of them are nicely segregated. However, the bridge library between SDK and Runtime: A.dll is GACed in .Net Framework. Apps from SDK version X can run on cluster version Y where Y >=X. So, we get latest (Y) version of Dlls A always on cluster’s platform.

Problem:
There are classes in sdk dlls like SDK_A.dll which inherit from types in A.dll. So, before even Main method is called, A.dll is searched and found in GAC in .Net Framework. Since there is no GAC in coreclr, we get FileNotFoundException for A.dll in coreclr. 

What we have tried:
1. We have tried adding AssemblyResolver to load these A.dll from Runtime folder. That does not help as exception is thrown before any code (Program’s Main) is executed.
2. We have looked at `dotnet strore` but it looks more complicated than GAC and it seems it was not designed as cross platform GAC. For e.g. we can't ask users to run `dotnet publish` with specific `manifest.xml`. It breaks development and packaging workflow for many developers.

What are the guidelines for library and platform writers to move there Dlls from GAC when transitioning form .Net Framework to CoreClr?

**Comment by jkotas** [comment]
Could you please tell us more about your platform so that we can understand the problem better:
- Does the problem you are describing exist for the applications built using your platform as well; or is there something special about your SDK that makes it fundamentally different from applications?
- Do applications built using your platform depend on just the runtime .dlls? How are you planning to distribute the runtime .dlls for .NET Core – NuGet packages or something else?

cc @jeffschwMSFT
