### ISSUE TITLE
Consider using a buffer cache with P/Invoke

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/coreclr#1845]
When allocating native buffers for P/Invoke we should consider pulling from a cache.

In the scenario of calling I/O related methods many thousands of calls can be made in quick succession which currently can cause a ton of native alloc/free calls.

**Comment by JeremyKuhne** [comment]
@stephentoub, @vancem

**Comment by yizhang82** [comment]
@JeremyKuhne  Can you explain your scenario a bit more? I would imagine that in intensive I/O related methods you probably want to avoid allocation/deallocation as much as possible, whether they are cached/pooled or not.

**Comment by JeremyKuhne** [comment]
@yizhang82 Avoiding if possible is the first priority, yes. What I'm looking at is getting a string out of Windows- take `GetFullPathName()` for example. It is pretty typical that you don't know exactly what size string you're going to get back. Many will tell you if you have an insufficient buffer and give you the correct size (some will just tell you "not enough"). With the ones that will give you a specific size you can call with a zero size buffer, but there is a penalty- it is better to make an educated guess first on the hopes you can avoid a costly second call.

We suggest StringBuilder for these sort of P/Invokes but it has allocation issues that prompted me to open this. Biggest is that it doesn't pin when it can in theory (see #1842). If it did _that_ would make the biggest difference. But suppose it can't pin or be updated to pin in most cases: Instead of allocating a temporary buffer every time and tossing it perhaps it might improve things to keep a small cache to satisfy the need for a "small" buffer. (And anywhere else we need to do so when interacting with the OS)

In this specific case (StringBuilder), however, I think we'd be much better off with something like `StringBuilder.DeChunk()` :arrow_right: Pin whenever we're `[Out]`. That would likely improve the vast majority of usages and reduce the need for anything more complicated. I'm presuming that _just_ `[In]` with a chunked StringBuilder is _not_ common.

**Comment by yizhang82** [comment]
@JeremyKuhne Thanks for opening the StringBuilder pinning issue. Looks like supporting pinning StringBuilder (or another type like MutableString/StringBuffer) would solve majority of your problems with strings. We can take the discussion of pinning StringBuilder over there. 
As for allocation/deallocation, in our marshalling implementation we do use stack allocation (more specifically, localloc instruction) to allocate temporary buffer and it is *very* fast. And we do use it in the unicode StringBuilder marshalling case (see ILWSTRBufferMarshaler::EmitConvertSpaceCLRToNative). However, there are cases where an allocation/deallocation can't be avoided because it is part of the ABI contract we have in the ref case.  
Having said that, I do agree that having a first-class customizable interop marshalling layer that can customize various aspects of data marshalling, including pinning / allocation, would be really nice.
