### ISSUE TITLE
Linux performance problem

### ISSUE THREAD

**Issue by Extred** [dotnet/coreclr#18465]
Hello.

I've spotted a performance drop on "Linux s4-srv 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux" compared to Windows/MacOS.

Flame graphs:
![image](https://user-images.githubusercontent.com/3522038/41411837-de9a3232-6fe6-11e8-84f5-d340475951d4.png)

Debian PerfView view:
[deb.perfView.xml.zip](https://github.com/dotnet/coreclr/files/2102298/deb.perfView.xml.zip)

It looks like locale/encoding problem, but changing system locale settings (as suggested in https://github.com/dotnet/coreclr/issues/5612) helps not.

Tried on .NET Core runtimes 2.0.7 and 2.1.0.

**Comment by danmosemsft** [comment]
Is it possible to resolve CLR symbols? Generally they should be on the public symbol server.

**Comment by danmosemsft** [comment]
@mikem8361 can remind us how to do that for Linux.

**Comment by Extred** [comment]
If you mean [that](https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/linux-performance-tracing.md#resolving-framework-symbols) part then it's done already.
Perfcollect log:
Collection started. Press CTRL+C to stop.
^C
...STOPPED.
Starting post-processing. This may take some time.
Generating native image symbol files
...FINISHED
Saving native symbols
...FINISHED
Exporting perf.data file
...FINISHED
Compressing trace files
...FINISHED
Cleaning up artifacts
...FINISHED

Clicking 'resolve symbols' in PerfView does not makes any effect.

**Comment by mikem8361** [comment]
@vancem might know more about this if this is perfview related.

**Comment by mikem8361** [comment]
I’ll you know when this symbol downloader is ready.  It should soon 😊.

**Comment by Extred** [comment]
@vancem I've tried EventPipe feature, but it does not create any .netperf files both on my project and helloworld sample.

Host (useful for support):
  Version: 2.1.0
  Commit:  caa7b7e2ba
.NET Core SDKs installed:
  2.1.300 [/usr/share/dotnet/sdk]

As for repro project: I'm trying to make one, but it's still unclear what's the cause of performance drop, so I can't reproduce it with simple app yet.

**Comment by vancem** [comment]
Hmm, I tried those instructions (setting the two environment variables (be careful with capitalization, it matters!)  locally on what seems to be the same version  Here is the complete output of 'dotnet --info'
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300
 Commit:    adab45bf0c

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.300/

Host (useful for support):
  Version: 2.1.0
  Commit:  caa7b7e2ba

.NET Core SDKs installed:
  2.1.300 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```
The important part is the 2.1.0 version of Microsoft.NETCore.App because that is the part that has the new EventPipe code.  

I would start with the simplest case.   Create a hello-world app and do
```
export COMPlus_EventPipeEnable=1
dotnet run 
```
And look for a *.netperf file.

**Comment by brianrob** [comment]
I missed this in my first read - the first environment variable is close, but not quite correct.  You should use:

```
export COMPlus_EnableEventPipe=1
export COMPlus_EventPipeConfig=Microsoft-DotNETCore-SampleProfiler:1:5
```

The first environment variable is corrected to EnableEventPipe from EventPipeEnable.

Note that ```dotnet run``` is likely to give you at least two netperf files because it will run multiple dotnet processes - one for the SDK to ensure that the built app is up-to-date and one for your app.  If compilation is required, I believe you may get more.  If you want to guarantee that you only get one, you can build your app first and then run ```dotnet path/to/dll```.

**Comment by Extred** [comment]
That worked!

[netperfs.zip](https://github.com/dotnet/coreclr/files/2120658/netperfs.zip)

Both perfs are for 3-minute app worktime.
There is a heavy startup in that app so first 30s can be ignored.

**Comment by vancem** [comment]
OK I have decoded the files.  Brian for you information they re in my public clrmain area under users\vancem\issue18465.   There is a linux.netperf and a win.netperf 

One big difference I see right away is that the Linux trace has a bunch of EventSource logging overhead that is coming from the network and task library instrumentation.   This is not present in the windows trace.   There is alot of overhead in System.Diagnostics.Tracing.EventSource.DispatchToAllListener which is the path to send things to an EventListener.    We should not be going down this path for EventPipe correct?   

@Extred  : another possibility is something has turned on more logging (e.g. some monitoring system).  Are there any monitoring systems that you know about on your Linux run?

I need to look at this trace a bit and do some experiments myself.   Right now the problem is clearly excessive logging (I have conformed that the netperf file does NOT have any events but the Thread Sampling, so it does not seem to be EventPipe itself that is causing the additional events.

**Comment by vancem** [comment]
In the Linux trace I also see System.IO.FileSsytem.Watcher running in the Linux trace but not in the Windows trace at all.   @Extred  it would be useful to see what is going on in a debugger with this (set a breakpoint on its constructors).   My guess is that again there is a code difference on Linux.

**Comment by vancem** [comment]
I have confirmed that in a sample MVC app that when you turn on EventPipe 
1. There is NOT alot of EventSource overhead.  Thus it is NOT something inherent in ASP.NET or EventPipe but something specific to @Extred  scenario.   

2. There IS however a bunch of FileSystem.Watcher overhead.  Thus this seems to be something built into ASP.NET.   Investigating...

To dig into (1) above you can place a breakpoint at System.Diagnostics.Tracing.EventSource.DoCommand.  This routine is called any time a EventSource provider is enabled or disabled (or other commands sent to it).  We need to find out who is turning on EventSources.

**Comment by vancem** [comment]
Ignore the issue with FileSystem.Watcher  I am forgetting that this is thread time, not CPU time.  You expect alot of blocked time just waiting around for a file system change.

**Comment by Extred** [comment]
@vancem 

> Are there any monitoring systems that you know about on your Linux run?
No, that's a fresh linux installation 

> To dig into (1) above you can place a breakpoint at System.Diagnostics.Tracing.EventSource.DoCommand
How do I do that?

> My guess is that again there is a code difference on Linux
Code is the same, I've copied the publish directory to Windows from Linux

**Comment by brianrob** [comment]
@vancem, the difference in EventSource events coming to EventPipe is expected for .NET Core 2.1 as the fix to enable these for Windows was made in a post 2.1 change.  You are also correct that EventPipe should not cause anything to go down the EventListener path - it goes down the platform logger (ETW) path.

**Comment by brianrob** [comment]
It sounds like there is an EventListener being turned on somewhere, as that would explain the time spent in System.Diagnostics.Tracing.EventSource.DispatchToAllListener.

**Comment by danmosemsft** [comment]
I've rolled this into https://github.com/dotnet/coreclr/issues/5612 as it seems the same issue.
