### ISSUE TITLE
macOS Mojave: Support for Hardened Runtime

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#18617]
From https://github.com/xamarin/xamarin-macios/issues/4288 / https://github.com/mono/mono/issues/9210 :

In macOS Mojave, Apple has introduced support for Hardened Runtime. (This is fully explained somewhere in the WWDC 2018 slides, but I cannot right now find exactly where.) One of the hardening mechanisms is a limitation on JIT techniques. It is still fully possible and supported, but the MAP_JIT flag must be passed to mmap() calls, and a specific entitlement must also be present in the code signature. 

https://developer.apple.com/videos/play/wwdc2018/702/ 20 minute mark has details.

**Comment by jkotas** [comment]
cc @morganbr

**Comment by kasper3** [comment]
I think CoreCLR is already supporting hardened kernel for grsec Linux kernel (introduced around 2001), is Apple's "Hardened Runtime" something different?

**Comment by jkotas** [comment]
Yes. They have invented a new `MAP_JIT` flag for `mmap` and binary capabilities to mark the program with to mark this flag work. The talk has more details.

**Comment by jkotas** [comment]
Mono PR: https://github.com/mono/mono/pull/9419

**Comment by odhanson** [comment]
cc: @danmosemsft @preethikurup @jingsunsql 

This is going to be an issue on our project also. We are required to be Mojave compliant.

**Comment by danmosemsft** [comment]
cc @RussKeldorph fyi seems @odhanson may have to ask for this in 2.2.

**Comment by RussKeldorph** [comment]
@jeffschwMSFT Is this on your radar?

**Comment by AaronRobinsonMSFT** [comment]
@janvorli and @jkotas Is there a specific plan for 3.0?

cc @jeffschwMSFT @GrabYourPitchforks

**Comment by GrabYourPitchforks** [comment]
There's no 3.0 work scheduled in this area.

**Comment by jkotas** [comment]
Note that this is internal partner impacting.

@odhanson You have asked for this earlier. Is it ok with you that this won't get done in 3.0?

**Comment by odhanson** [comment]
@jkotas right now we have worked around this issue by adding a bunch of exclusions which practically disables MHR. Its not optimal at all. 
We would really like, from a security perspective to be able to enable this eventually. If it won't be in 3.0, then when would we be able to get it done ?

**Comment by jkotas** [comment]
If this does not get done for 3.0 release, the next opportunity to do this will be .NET 5 release that will be second part 2020 (ie more than one year from now). Are you going to be able to live without this till end of 2020?

**Comment by odhanson** [comment]
@jkotas, Its hard to predict. Apple might harden their requirements and then it will cause our app to fail to meet the apple store requirements. Right now, this is not a hard requirement.
Having said that, if it does become a blocker, we would have a few months heads up. Would we then be able to release a 3.1 (or something similar) that adds this capability ?
IIRC, @janvorli worked on this, and although it wasn't that simple, it also wasn't that a big change. Definitely something that can be implemented in a few months time frame

**Comment by jkotas** [comment]
> Apple might harden their requirements

If I am reading this correctly, Apple announced that they will required this for 10.15. From https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution?language=objc:  Beginning in macOS 10.15, notarization is required by default for all software.

> Would we then be able to release a 3.1

We do not add new features in servicing. The exceptions have to be approved by .NET directors and most of the requests are rejected. If you think you will need this before end of 2020, you better scream now.

**Comment by janvorli** [comment]
Yes, I've started to work on enabling that in December last year and still have a local branch with that work in progress. I remember I've hit a couple of problematic things, but I'll have to refresh my memory on that.

**Comment by odhanson** [comment]
@jkotas we are ok for 10.15. We have MHR enabled and our app is already notorized.  The thing is that we are using an exclusion to disable page signing protections.  Once MHR is supported by the runtime we would be able to remove this exclusion and only allow the specific pages marked with JIT by the runtime to be unsigned. 
While this exclusion is fine right now,  we can't anticipate what will change in 10.16. Apple might decide to prevent us from using this exclusion. 
10.16 will release in September 2020 so this would have to be done by then including porting our product to 5.0. 
This definitely sounds like a big riak to me.

**Comment by AaronRobinsonMSFT** [comment]
@odhanson Thanks for the context. I am going to move this back to 3.0 for right now. @janvorli Please update as appropriate.

**Comment by odhanson** [comment]
> Yes, I've started to work on enabling that in December last year and still have a local branch with that work in progress. I remember I've hit a couple of problematic things, but I'll have to refresh my memory on that.

@janvorli let me know if I can assist in anyway.

**Comment by janvorli** [comment]
I have looked at the changes and I don't think I can finish and test it in the remaining time we have for adding new 3.0 features. What I have done so far is just a small part of the support in PAL.
The biggest trouble is that the MAP_JIT flag has to be applied at the time we obtain a virtual memory range (when we reserve the memory). We have many places in the code where we reserve memory with PAGE_NOACCESS and later on create various kinds of mappings in it, including RWX (e.g. the PEDecoder to load PE files, loader heap, host code heap). 
Another issue is that the MAP_JIT cannot be applied to regions mapped to fixed addresses. We attempt to allocated JIT jumpstubs near to the jitted code, which basically scans virtual memory ranges and tries to reserve virtual memory at specific addresses.
There are also few places in the code where we switch from RX to RWX and back portions of executable files. Like the s_gsCookie variable location, the GC write barrier code or in the code versioning when we update the jumpstamp helper. So that code would have to be refactored so that we don't touch the mapping in the memory mapped from the executable.

All of the above would need to be fixed to make it compliant with the hardening requirements.

**Comment by MarcWils** [comment]
#25716 is open for bringing support in .NET 5.

Any chance this will make the 3.0 milestone?

**Comment by lpereira** [comment]
> 
> All of the above would need to be fixed to make it compliant with the hardening requirements.
>

Opening a parenthesis here, since this will touch an area that I was looking into the other day: `LoaderHeap` makes successive calls to `mprotect()`, with pointers increasing by `0x1000`, page size `0x1000`, and same protection (usually `PROT_READ|PROT_WRITE`, sometimes `PROT_EXEC` is thrown in there).  Although each of these calls are just a few dozen microseconds each, many of them could be coalesced into just a few calls ([something like this](https://gist.github.com/lpereira/7e16ef403dff718907fd3e8aa9f07f2c)).   @janvorli, if you're going to work in this, could you please keep me in the loop?

**Comment by janvorli** [comment]
@lpereira I've actually already merged in a PR implementing support for the Mojave hardened runtime, but I had to revert it a week ago as I've found one issue with GC write barriers in it and I was just about to leave for my vacation. 
As for the LoaderHeap making successive calls to mprotect, this would need to be changed in the LoaderHeap itself where it calls VirtualAlloc to perform these mappings. But it is possible though that coalescing these mappings will not be possible as they could be coming from separate requests to allocate from the LoaderHeap.

**Comment by danmosemsft** [comment]
@odhanson higher up, you had mentioned this was important to your product. Is that still the case -- I'm guessing yes, but Apple has given us a little extra time? If this is needed pre-5.0 I'd like to make sure we know.

**Comment by jkotas** [comment]
@danmosemsft The runtime work for this was ported to release/3.1 : https://github.com/dotnet/coreclr/pull/26803

@janvorli I believe there is nothing left to do. Can this be closed now?

**Comment by danmosemsft** [comment]
OK good. I'm going around closing partner loose ends today..

**Comment by janvorli** [comment]
I am not aware of any additional runtime work needed.
