### ISSUE TITLE
Misuse of optPrepareTreeForReplacement leads to incorrect exception thrown in release

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/coreclr#18648]
This example incorrectly throws an exception in release:
```csharp
// Generated by Fuzzlyn on 2018-06-26 16:32:41
// Seed: 3807292053929899503
// Reduced from 119.1 KiB to 0.2 KiB
// Debug: Runs successfully
// Release: Throws 'System.NullReferenceException'
public class Program
{
    static ushort[, ] s_1 = new ushort[, ]{{0}};
    public static void Main()
    {
        bool vr5 = 0 == ((0 % ((0 & s_1[0, 0]) | 1)) * s_1[0, 0]);
    }
}
```

@mikedn has analyzed the cause [here](https://github.com/dotnet/coreclr/pull/18257#issuecomment-400360920):
> Uh oh, it's a different issue but in the same area. This PR basically fixes `optPrepareTreeForReplacement` (by fixing `gtExtractSideEffList`) but then it turns out that there are cases where `optPrepareTreeForReplacement` is misused.
> 
> It's really baffling, optVNConstantPropOnTree calls optPrepareTreeForReplacement(tree, tree) and then changes tree to a constant. In this case
> 
> * `tree` is `MOD` so itself ends up as a side effect
> * `tree` is changed to a constant so the entire side effect subtree simply vanishes
> * `newTree` is a COMMA where both op1 and op2 point to the same constant node
> 
> I'm surprised that this doesn't blow up more often and more spectacularly!

**Comment by mikedn** [comment]
I'm starting to think that this is actually a consequence of my fix and not a real bug. Without my fix it's unlikely that `tree` will ever have side effects, it's been evaluated to a constant after all. So what that code is doing is rather clever - `optPrepareTreeForReplacement` will return a comma where op1 has the side effects from `tree`'s children and op2 is `tree` that then becomes a constant.

My fix broke the assumption that `tree` itself does not have side effects - MOD has an exception side effect. Well, not really since it's really a constant but gtNodeHasSideEffects can't figure it out. Scratching head...

**Comment by jakobbotsch** [comment]
Let me know if I should close this one. The examples here does throw in .NET core 2.1 as well, although I presume that is just because they invoke the same behavior as #18232.

**Comment by briansull** [comment]
> optPrepareTreeForReplacement will return a comma where op1 has the side effects from tree's children and op2 is tree that then becomes a constant.

Yes, This is what we do when replacing constant Value-numbered trees with Comma nodes.  Evalutate the side effects and save them as op1, and return the constant value using op2 of the Comma node.

**Comment by mikedn** [comment]
> The example here does throw in .NET core 2.1 as well, although I presume that is just because it invokes the same behavior as #18232.

Indeed, without my fix side effects get dropped because `gtExtractSideEffList` fails to handle `ARR_ELEM`. With my fix side effects get dropped because `optVNConstantPropOnTree` wasn't expecting that a constant tree has side effects. Either way, an assignment that initializes a CSE variable is lost so you get a null ref exception.

I think it's safe to close this one, I'll need to figure out how to fix my fix :smile:

Thanks for finding this!

**Comment by jakobbotsch** [comment]
> Thanks for finding this!

No worries. I've been following development for a long time and have always wanted to get more familiar and more involved. It has been pretty amazing to see your contributions over the years. 👍 
I am happy to finally be able to contribute.

Closing since the underlying issue was in #18257.
