### ISSUE TITLE
Provide an Out-of-Process Control Mechanism for EventPipe

### ISSUE THREAD

**Issue by brianrob** [dotnet/coreclr#18658]
Right now, EventPipe is only controllable via environment variables and private reflection.  We should add an out-of-process control mechanism to significantly improve usability.

**Comment by noahfalk** [comment]
This likely goes together with #18659 so that process A can register itself to receive an event stream sent by process B.

**Comment by jorive** [comment]
We can now control: `Start` writing events to file, start `Streaming` events through IPC, and `Disable` EventPipe from out-of-proc.
https://github.com/dotnet/coreclr/pull/23106
https://github.com/dotnet/coreclr/pull/23448

**Comment by brianrob** [comment]
This is super-exciting!  How does one give this a try?

**Comment by noahfalk** [comment]
I don't know if we want to close this just yet? I think of this as having a public API/public protocol whereas right now we are still at private API/private protocol.

**Comment by jorive** [comment]
@brianrob We are working on [dotnet-trace](https://github.com/dotnet/diagnostics/tree/master/src/Tools/dotnet-trace) and a library [Microsoft.Diagnostics.Tools.RuntimeClient](https://github.com/dotnet/diagnostics/tree/master/src/Microsoft.Diagnostics.Tools.RuntimeClient) in order to achieve this. It's a working prototype, and I'm working on improving it and making it up to spec.

**Comment by jorive** [comment]
@noahfalk We have `dotnet-trace` (still work in progress), but this issue does not say anything about a Public API. Please feel free to open a new issue with more information.

**Comment by noahfalk** [comment]
Done. #23780
