### ISSUE TITLE
Proposal to add classification info to area-CodeGen issues

### ISSUE THREAD

**Issue by erozenfeld** [dotnet/coreclr#18719]
There are currently 652 open are-CodeGen issues. To help with triage the jit team went through the issues and compiled classification info for each issue: category, theme, skill-level, and cost. Each issue got one tag from each of the following sets:

category: {cq, correctness, implementation, throughput, proposal, reach, design. documentation, testing, engsys, usability, security, portability}

theme: {basic-cq, register-allocator, arm64, jit-coding-style, testing, inlining, optimization, benchmarks, ir, loop-opt, vector-codegen, hw-intrinsics, x86, importer, first-class-structs, arm32, throughput, jit-stress, intrinsics, sysV, helpers, bounds-checks, runtime, flowgraph, promotion, gc-stress, emitter, gc-info, big-bets, large-methods, value-numbering, debug-dumps, ilasm, assertion-prop, devirtualization, block-opts, ref-counts, profile-feedback, barriers, msil, cse, eh, ildasm, tail-call, super-pmi, div-mod-rem, zero-init, stack-allocation, type-intrinsics, structs, morph, span<t>, jit-ee-interface, lower, md-arrays, invalid-il, spmi, ssa, block-layout, alignment, range-check, liveness, copy-prop, volatile, delegates, web-assembly, pinning, interpreter, generics, build, class-init, linux}

skill-level: {beginner, intermediate, expert}

cost: {small, medium, large, extra-large}

This info is currently in an excel spreadsheet and we would like to propagate it to the issues.
We think adding a label for each of the tags above would be excessive. The proposal is to append this information to the end of the issue description, e.g.
```
category:correctness
theme:interpreper
skill-level:intermediate
cost:small
```
Any feedback on this plan is appreciated.

@dotnet/jit-contrib @karelz

**Comment by CarolEidt** [comment]
Thanks @erozenfeld for posting this.
I have heard before that adding labels for all of these would be too much, but it would be good to understand that issue more fully.
@karelz - can you comment?

**Comment by jakobbotsch** [comment]
It sounds great for some of us who want to participate, but aren't exactly sure where to start.

Since the GitHub search looks inside the issue text I don't think it matters a lot how the info is added -- the labels are nice, but it is easy enough to search for `skill-level:beginner` and GitHub seems to have no problem finding this. Though it does make it harder to get a quick overview when looking over the issues.

Another option is to add labels for everything except themes, and then modify the titles of issues to indicate the theme. For example an issue like #18235 could be renamed to `Value-numbering: Wrong integer promotion in release`. Or appending both theme and category, to cut down even more, for example: `Wrong integer promotion in release [correctness, value-numbering]`.

**Comment by erozenfeld** [comment]
The info has been propagated to the issues. There is a number of new issues that haven't been triaged yet.
