### ISSUE TITLE
Regression in arm64 r2r jobs.  'defList.IsEmpty()' 

### ISSUE THREAD

**Issue by sandreenko** [dotnet/coreclr#18765]
Many x64_arm64_altjit_checked_windows_nt_r2r test are failing with:

```
Assertion failed 'defList.IsEmpty()' in 'Gen:Target():this' (IL size 33)

    File: c:\git\coreclr\src\jit\lsrabuild.cpp Line: 2094.
```

The regression is caused by #18130, [ci example](https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_arm64_altjit_checked_windows_nt_r2r_prtest/13/testReport/baseservices_threading/_generics_threadstart_GThread18_GThread18_/_generics_threadstart_GThread18_GThread18_cmd/).

**Comment by sandreenko** [comment]
PTAL @dotnet/jit-contrib

**Comment by CarolEidt** [comment]
I believe that the problem is that #18130 caused the uses not to be built in the case where `compiler->compSupports(InstructionSet_Atomics)` returns true, e.g.:
https://github.com/dotnet/coreclr/blob/master/src/jit/lsraarm64.cpp#L442 and https://github.com/dotnet/coreclr/blob/master/src/jit/lsraarm64.cpp#L472
