### ISSUE TITLE
Add EndOfStream property to BinaryReader

### ISSUE THREAD

**Issue by scls19fr** [dotnet/coreclr#18823]
Hello,

I'm comparing saving/reading data using either `StreamWriter`/`StreamReader` and `BinaryWriter/BinaryReader`.

With `StreamReader`, to read data we can do:

```vb
Imports System.IO

ioReader = New StreamReader(fname)

Do While Not ioReader.EndOfStream

        Dim substrings() As String = chaine.Split(";")
        ...
Loop

ioReader.Close()
```

but with `BinaryReader` it's a bit more complicated with

```vb
ioReader = New BinaryReader(File.Open(fname, FileMode.Open))

Do While ioReader.BaseStream.Position <> ioReader.BaseStream.Length
    t = ioReader.ReadSingle()
    y = ioReader.ReadSingle()
    ...
Loop

ioReader.Close()
```

I wonder if an `EndOfStream` property couldn't be added to `BinaryReader`

Kind regards

**Comment by AaronRobinsonMSFT** [comment]
@stephentoub do you know of any reason this would be a bad idea or wasn't provided? I can't imagine there is much appetite for altering the API surface of `BinaryReader` - especially if there is a way to accomplish the same thing.

**Comment by stephentoub** [comment]
> especially if there is a way to accomplish the same thing.

As long as the encoding used isn't Encoding.Unicode, you should be able to accomplish this with `binaryReader.PeekChar() == -1`, though that might have more overhead than you want.

> Do While ioReader.BaseStream.Position <> ioReader.BaseStream.Length

I'm not sure that's always going to do what you want.  I'd need to review the code to know for sure, but since BinaryReader has its own internal buffer, it seems likely that it could read the data from the stream, causing the stream to be at the end, but there would still be buffered data left to read from the BinaryReader's buffer.

> do you know of any reason this would be a bad idea or wasn't provided?

I assume simply no one's had a strong enough need for it.

**Comment by jkotas** [comment]
> I assume simply no one's had a strong enough need for it.

BinaryReader is not really a general purpose reader for arbitrary binary files. It is geared towards reading .NET-specific binary files, like managed resources. The encoding of these kind of files has explicit sizes upfront and "read till end of file" kind of operation is not needed for those.

**Comment by mikedn** [comment]
And `EndOfStream` would be rather confusing on `BinaryReader` due to the fact it reads values of different fixed sizes - `Int32`, `Double` etc. This means that you can end up in a situation where `EndOfStream` returns `false` but a call to `ReadDouble` throws `EndOfStreamException` because there are only 7 bytes available.

Such functionality may be useful but likely in a different shape (e.g. `TryReadInt32`, `TryReadSingle`).

**Comment by jkotas** [comment]
CoreFX has a number of related API proposals:

https://github.com/dotnet/corefx/issues/4596
https://github.com/dotnet/corefx/issues/24144
https://github.com/dotnet/corefx/issues/24180

If you still believe there are APIs needed on BinaryReader for your scenario, please file an issue in CoreFX repo using a template linked from  https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md
