### ISSUE TITLE
HW intrinsics - PopCount() returns int/long, while Leading/TrailingZeroCount() returns uint/ulong

### ISSUE THREAD

**Issue by voinokin** [dotnet/coreclr#18831]
Is this difference in return type by design?
Also, `MoveMask()` returns `int` which may be less convenient than `uint` when one has to shift the result obtained from 256-bit vector right for some reason

**Comment by voinokin** [comment]
@tannergooding
My concern here is to confirm HW intrinsics API is consistent at these specific points, before it's too late
Thank you for answering and/or excuse me for disturbing if you're not the right person :-)

**Comment by tannergooding** [comment]
Thanks @voinokin. Myself and @eerhardt are the primary people to tag on HWIntrinsic related API requests.

@CarolEidt, @fiigii, and @RussKeldorph are also part of the larger "working group" and are good to tag as well.

@fiigii, specifically, might be able to provide more insight as to why `uint` was used here, instead of `int`. 

It looks like the native signatures take `uint` parameters and return `int` results; So I'm wondering if this was just oversight and the return type was made to match the parameter type by accident.

**Comment by fiigii** [comment]
> It looks like the native signatures take uint parameters and return int results; 

Right, we just followed the C/C++ intrinsic design. But I see no harm in being consistent in the return type (I would choose unsigned since they can never be negative).
