### ISSUE TITLE
Hardware Intrinsics: Reading out SSE vector values without unsafe or Sse4.1?

### ISSUE THREAD

**Issue by Zhentar** [dotnet/coreclr#18926]
Loading values into a Vector128<> is easy enough, lots of safe options there. But my options seem rather limited when it comes to reading them back out again... the only choices I've found are `Sse41.Extract` or `Sse.Store` with an `unsafe` pointer parameter. Is there any safe option that doesn't affect minimum hardware requirements?

**Comment by tannergooding** [comment]
@Zhentar, could you elaborate as to what "safe" options you are using and why using the `unsafe` option isn't "viable"?

**Comment by Tornhoof** [comment]
There is a similar request here:
https://github.com/dotnet/corefx/issues/30968

**Comment by Zhentar** [comment]
`SetVector128`, `SetAllVector128`, `MemoryMarshal.Cast<T,Vector128<T>>` work great for loading values (I imagine MemoryMarshal.Cast can be used for storing as well but it would be more awkward).

`unsafe` isn't entirely non-viable, but it increases the risk of a serious failure; I will face a much higher burden during design, development, and testing if I want to deploy it to production. I'd much rather `Sse.Set` to a Span<T> and incur the cost a bounds check (particularly since the JIT will often be able to elide it).

It also seems like a strange API design for something coming right after a major feature that dramatically reduced the need for `unsafe`.

**Comment by jakobbotsch** [comment]
Maybe the explicitly sized vector types should have indexers similarly to the SIMD `Vector<T>` type?

**Comment by tannergooding** [comment]
> Maybe the explicitly sized vector types should have indexers similarly to the SIMD Vector<T> type?

I don't think this is a good idea. The Hardware Intrinsics types were explicitly designed to be opaque types (other than size) and only interacted with using the HWIntrinsic APIs. This simplifies a number of other issues/concerns that could arise given that these are platform specific types/APIs and not all platforms/APIs treat them the same.

**Comment by EgorBo** [comment]
@Zhentar inner `DisplayString` property is an example of how to read the values "safely" 😄 
```csharp
var vector = Sse.SetVector128(1.1f, 2.2f, 3.3f, 4.4f);
var items = new float[4];
Unsafe.WriteUnaligned(ref Unsafe.As<float, byte>(ref items[0]), vector);
```

**Comment by tannergooding** [comment]
> It also seems like a strange API design for something coming right after a major feature that dramatically reduced the need for unsafe.

**NOTE:** This is my personal view on the subject, so take it with a grain of salt :smile:

One of the main differences here is the use-cases the various APIs are geared towards and the level of performance oriented code they are meant to drive.

Things like `Span<T>` are geared towards use in the public API surface area of high-performance code. They can be easily sprinkled about and help improve perf due to reducing the number of copies/allocations done.

The HWIntrinsic APIs, however, are meant to be used internally and are for building up other types/algorithms. They are for fine-tuned high-performance code where you may care about things like cache locality, prefetching, and instruction pipelining.

For HWIntrinsics, using `ref`, `Span<T>`, etc just can't provide the same guarantees that `pinning` and working with raw pointers can and in the type of scenarios that `HWIntrinsics` are meant to drive, that often matters (e.g. ensuring code is aligned so that read/writes don't cross a cache line boundary; ensuring that the GC doesn't relocate the underlying array so that cache-locality and prefetching work, etc; carefully selecting the underlying assembly instructions for optimal throughput, etc).

**Comment by Zhentar** [comment]
While those are fair points (and I do think good justification for having the pointer API options available), I'm worrying about them for the 500,000 iterations of my inner loop. I've only got one store at the end, and I can easily spare a few extra cycles for bounds checking a write to my stack.

**Comment by tannergooding** [comment]
@Zhentar, my question then would be, is there enough justification to cover making such an option part of the official API -- or -- is it already sufficiently covered by the existing APIs and a simple helper method (which can take a `(Span<T> span, int index)` and do the required bounds checks)?

From the discussions so far (on other threads where this was proposed), if new overloads were added, they would likely just take a `ref` (which should cover `Span<T>` using its `ref returning indexer` API -- which itself does bounds checking etc). Do you feel like that would sufficiently cover your scenario?

**Comment by saucecontrol** [comment]
A sample might be helpful to understand your request.  It seems like if you don't mind a perf hit, you can just `stackalloc` a buffer to store the vector into and then wrap that in a `Span<T>` or copy it to an array to keep working on it.

Unless your objection is to using the `unsafe` keyword at all...  The thing is, there's nothing unsafe about safely-written `unsafe` code.  Perhaps it's better to thing of `unsafe` as a synonym for "I know what I'm doing" rather than a synonym for "fragile".

**Comment by Zhentar** [comment]
@saucecontrol My coworkers will not find a `\\trust me, I know what I'm doing` preceding my write to the stack without bounds checking very comforting. If I screw it up, the worst case could be a remote code execution vulnerability, so the bar for establishing that my `unsafe` code is safely-written is going to be pretty damn high.

@tannergooding  I'd like helpers along the lines of this:
```cs
		public static void Store(Span<uint> dest, Vector128<uint> source)
		{
			if (dest.Length < 4) throw new IndexOutOfBoundsException();
			Sse2.Store((uint*)Unsafe.AsPointer(ref MemoryMarshal.GetReference(dest)));
		}
```
Then I can trivially consume it efficiently, without `unsafe`
```cs
Span<uint> dest = stackalloc uint[4];
Sse2.Store(dest, myVector);
```
And then JIT will inline the helper and I think eliminate the bounds check; effectively no runtime cost and no one has to establish whether or not I can be trusted not to clobber the stack.

**Comment by tannergooding** [comment]
> I'd like helpers along the lines of this:

@Zhentar, the question, however, is: Why can't you write that helper (with the bounds checking) yourself?

> If I screw it up, the worst case could be a remote code execution vulnerability, so the bar for establishing that my unsafe code is safely-written is going to be pretty damn high.

Right, but abstracting the unsafe code behind a helper method with a clear bounds check (as you indicated the BCL should provide) should be a reasonable intermediate.

If we did provide additional overloads (that don't require `unsafe`), my advocate would be for `ref` overloads (not `Span<T>` overloads). This is because they work for `Span<T>` and other ref-like APIs/types, in general.

This would allow the code to be "safe", while still being "performant" by keeping the error-checking burden on the user (which often time, for the types of algorithms using these APIs, is more desirable).

> `Unsafe.AsPointer(ref MemoryMarshal.GetReference(dest))`

I don't believe the above is safe without pinning the span first. @jkotas might be able to confirm, as I'm not aware if `Unsafe.AsPointer` will still track the `ref` it receives as in use...

**Comment by saucecontrol** [comment]
> I don't believe the above is safe without pinning the span first. @jkotas might be able to confirm, as I'm not aware if Unsafe.AsPointer will still track the ref it receives as in use...

I was chastised for writing similar code [here](https://github.com/dotnet/coreclr/issues/17818#issuecomment-395999541) 😆 

In theory, the GC could move the referenced memory between the dereference of the managed pointer and the use of the address.  In practice, the JIT marks the method Partially Interruptable, so it works out.  But with no guarantee that behavior will continue, it's no good.  The `ref T` overloads on the Load/Store methods still seems a good compromise to me.

> My coworkers will not find a \\trust me, I know what I'm doing preceding my write to the stack without bounds checking very comforting

That sounds like more of an education issue.  You can clobber the stack just as easily without using the `unsafe` keyword (or the `Unsafe` class).

**Comment by jkotas** [comment]
> In practice, the JIT marks the method Partially Interruptable

There are many cases where it is not going to be the case. A few examples:
- Debuggable code is fully interruptible by default, so this code would crash intermittently under debugger.
- Methods with exception handling are fully interruptible. If this code gets inlined into a method exception handling, you have a problem again.
(This list is not complete.)

**Comment by saucecontrol** [comment]
Good to know.  Thanks @jkotas!

**Comment by Zhentar** [comment]
I was under the impression that it was the safe & appropriate way to do that. If that is incorrect, then it's a great example of why I would much rather have a CLR provided helper for it 😁 

Can you expand on what you have in mind with `ref` overloads? If it's for the entire vector, I don't understand how it would provide memory safety, and if it's for single items, I don't understand how it would work efficiently when SSE 4.1 is not available (aside from `short`)

**Comment by saucecontrol** [comment]
You'd be responsible for your own bounds checking.  Those checks would be undesirable to most HWIntrinsics users, but you could roll your own checked wrappers without `unsafe` if you have the `ref` overloads.

```C#
public static void Store(Span<uint> dest, Vector128<uint> source)
{
    if (dest.Length < 4) ThrowHelper.Nope();
    Sse2.Store(ref dest[0], source);
}
```

**Comment by Zhentar** [comment]
In that case, not only would it not address my concerns, I would be opposed to it existing as an option at all; it does not eliminate any danger (if anything, increases it by violating peoples expectations of C#/.NET), just hides the"WARNING" signs. And I don't even think it buys any meaningful capability or efficiency; we can already wrap arbitrary refs with Span<T>.

For example,
```cs
	public class SpanTest
	{
		private struct Data { public int a, b, c, d; }
		private static Data _data = default;

		public void IncrementA() => IncrementWrapper(MemoryMarshal.CreateSpan(ref _data.a, 4));
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static void IncrementWrapper(Span<int> span)
		{
			if ((uint)span.Length < 4) throw new IndexOutOfRangeException();
			Increment(ref span[0]);
		}
		private static void Increment(ref int val) => val++;

		public void IncrementB() => _data.a++;
	}
```

JITs down to this:
```asm
TestHarness.SpanTest.IncrementA()
	mov     rcx,7FFBF8E206B0h
	mov     edx,5
	call    coreclr!coreclr_shutdown_2+0x10560
	mov     rax,1A0E5407108h
	mov     rax,qword ptr [rax]
	add     rax,8
	mov     edx,4
	cmp     edx,0
	jbe     00007ffb`f8d627da
	inc     dword ptr [rax]
	add     rsp,28h
	ret


TestHarness.SpanTest.IncrementB()
	mov     rcx,7FFBF8E106B0h
	mov     edx,5
	call    coreclr!coreclr_shutdown_2+0x10560
	mov     rax,26810007108h
	mov     rax,qword ptr [rax]
	add     rax,8
	inc     dword ptr [rax]
	add     rsp,28h
	ret
```

I think the public API of the HW Intrinsics should be designed under the assumption that the JIT emitting
```asm
	mov     edx,4
	cmp     edx,0
	jbe     00007ffb`f8d627da
```
is a temporary flaw rather than an intractable problem (and that the `unsafe` pointer option will still exist to offer a workaround when necessary).

**Comment by tannergooding** [comment]
@Zhentar, Going through this again, I think I misunderstood your original request.

It looks like you are just wanting a way to extract a particular element out of the array without calling `Sse41.Extract`, is that correct?

If so, the "traditional" way to do this is to get the element into index 0 (generally using a permute -- this is emulated on non-AVX hardware using `Shuffle` where both vectors are the same) and then calling the `ConvertTo` method (e.g. `Sse.ConvertToSingle` or `Sse2.ConvertToInt32`).

**Comment by Zhentar** [comment]
For my current, immediate purposes, this works just fine:
```cs
				uint v1 = Sse41.Extract(vals, 0);
				uint v2 = Sse41.Extract(vals, 1);
				uint v3 = Sse41.Extract(vals, 2);
				uint v4 = Sse41.Extract(vals, 3);
```
I'm already using `Sse41.MultiplyLow` and regardless I don't care whether a CPU without SSE4.1 can run my code at all.

But for people like me who are dabbling in the newly accessible hardware intrinsics, I want the API to be "pit of success" compliant - the *easiest* way to consume the API should be correct, or at least safe, and for the punishment for gaps in my understanding to be exceptions or hobbled performance rather than memory corruption; if that is not the case then I cannot make use of it professionally.

Even if we aren't the target audience, using comprehensible names like "MultiplyLow" instead of "mm_mullo_epi32" creates an attractive nuisance, and if the guardrails we normally expect & rely on are absent we're going to hurt ourselves.

**Comment by Zhentar** [comment]
> The first part of this is very hard. HWIntrinsics, by nature, require profiling, investigation, etc. There are a number of different ways to do any given operation and the "correct/safe" way requires some in-depth knowledge of how the underlying assembly instruction works (this extends to the HWIntrinsic APIs as well, since they are basically a 1-to-1 mapping, just without the ability to choose explicit registers).

No, using them *optimally* is hard. With the exception of the loads and stores, I think it quite reasonably fulfills "correct/safe";  I've never worked with the underlying instructions before and I was able to vectorize my algorithm and get the right answer out on the first test ("okay, now I multiply, `Sse2.Multiply`... uh, that returns `ulong` instead of `uint`? I must need a different instruction then")

> That is, users wanted things like more control, more flexibility, more perf, and more precision.

Adding Span<T> options for Loads & Stores doesn't take any of that from us, though, and having a safe & easy default naive approach would help us get to a correct & measurable implementation faster. Having only the pointer options encourages bad choices (My initial attempt was *exactly* the same as @saucecontrol had in the other issue, which as noted is somewhat less than ideal in both speed and correctness); we would have been better off starting with a safe Span<> API, and in many common cases the JIT will optimize away most or all of the overhead costs, leaving us more time to spend on the rest of code.

**Comment by saucecontrol** [comment]
One problem with that strategy is that certain Intrinsics can't be made safe without negating their purpose for existing.  Take the Aligned Load/Store methods, for example.  If you call those with an unaligned pointer, you get an insta-crash.  If the runtime were to check pointer alignment to make it safe, the benefit of using the aligned variant is more than cancelled out.  At the end of the day, there's no way to make everything in HWIntrinsics both safe and performant.  If you ask me (and I don't recall that anybody did, but whatevs…) I'd much rather have the performance because I can add the safety where I need it.  That's preferable to having the runtime inject the safety in places I know it's not needed.  I've had to work around that issue with `System.Numerics.Vectors`, and it's been painful.

I do agree with the argument about the pointer trap, though.  It's far too tempting, when you have a ref and need a pointer, to assume you can convert it in-place.  Even knowing that it's not supposed to be done, if you check the generated assembly, you're likely to find that a dereference and load gets compiled to a single instruction, and there's no way the GC can move your cheese in the middle of an instruction.  Problem is, that's only true when the method is Partially Interruptable, and @jkotas has kindly pointed out places where that wouldn't be the case.

As for whether `Span<T>` overloads should be there, that's not my place to say at all, but there's nothing stopping you from building your own if they're not baked into the runtime.  I'd rather see priority given to the parts I _can't_ build myself.

**Comment by Zhentar** [comment]
Only the easiest way has to be safe 😄 I don't care if `LoadVector128Aligned(uint*)` segfaults with the wrong pointer if there's a `LoadVector128(Span<uint>)`; it's quite obvious which one is the special option for people that know what they are doing and I'm not likely to accidentally pick wrong.

As for `Span<T>` overloads, they're apparently not something *I* can build myself, since my proposed implementation is broken 😅

**Comment by jkotas** [comment]
> As for Span<T> overloads, they're apparently not something I can build myself, 

You should be able to build them using the `fixed` keyword.

**Comment by tannergooding** [comment]
Closing this. We now expose some common "helper" methods on the `Vector64<T>`, `Vector128<T>`, and `Vector256<T>` types.

This includes the `GetElement` and `WithElement` methods (these were exposed, rather than an indexer, since the types themselves are `immutable`).
