### ISSUE TITLE
Temporary path being defined as C:\Windows.

### ISSUE THREAD

**Issue by Elycin** [dotnet/coreclr#19159]
Oddly today while working me and a co-worker experienced a strange encounter where our lockfile was attempting to be created in C:\Windows while running the application as the current logged on user.

We expected this to be a problem with my environment variables, however they appear to be set properly.

![image](https://user-images.githubusercontent.com/33913289/43299462-537f9544-9128-11e8-89e6-a534ccea902a.png)

This is the logs from our ASP.NET Core Application.
```csharp
Unhandled Exception: System.UnauthorizedAccessException: Access to the path 'C:\WINDOWS\spectero-startup-2018-7-27-4' is denied.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.IO.File.Create(String path)
```

And the code we are utilizing to generate the path programamtically:
```csharp
        public static string GetCurrentStartupMarker()
        {
            var currentTIme = DateTime.UtcNow;
            var minuteMarker = currentTIme.Minute.ToString()[0];

            return Path.Combine(Path.GetTempPath(),
                $"spectero-startup-{currentTIme.Year}-{currentTIme.Month}-{currentTIme.Day}-{minuteMarker}");
        }

        public static bool ManageStartupMarker(bool delete = false)
        {
            var marker = GetCurrentStartupMarker();

            if (delete)
            {
                if (File.Exists(marker))
                    File.Delete(marker);
                else
                    return false;
            }
            else
            {
                File.Create(marker).Dispose();
            }

            return true;
        }
```
---

Environment Information:
Windows 10 (10.0.17134 Build 17134)
Dotnet Core/ASP Version: 2.1.2

---

If there's any more information @Wintereise or I can provide, we would be glad to help out in solving this issue.

**Comment by AaronRobinsonMSFT** [comment]
@Elycin Thanks for reporting this because the root cause is going to be important to document. This is an interesting problem, but I think it has to do with the environment in some way. The implementation of `Path.GetTempPath()` on Windows forwards to the Win32 [`GetTempPath()`](https://docs.microsoft.com/en-us/windows/desktop/api/fileapi/nf-fileapi-gettemppathw) API - you can see that here:

https://github.com/dotnet/coreclr/blob/85374ceaed177f71472cc4c23c69daf7402e5048/src/System.Private.CoreLib/shared/System/IO/Path.Windows.cs#L144

The documentation for Win32 `GetTempPath()` states that the final fallback for the path will be `C:\Windows`, which seems to be the case here.

>The GetTempPath function checks for the existence of environment variables in the following order and uses the first path found:
>  1. The path specified by the TMP environment variable.
>  2. The path specified by the TEMP environment variable.
>  3. The path specified by the USERPROFILE environment variable.
>  4. The Windows directory.

I think we need some more details on how your application may be running. Is it elevated? Is this something that can be reproduced in a simple Hello World type of example?

**Comment by Elycin** [comment]
Hi @AaronRobinsonMSFT,
There is no elevation and the code is being executed inside of Jetbrain's Rider IDE.
The only environment variables I am overriding is ASPNETCORE_ENVIRONMENT=Development and assume the rest are taking control from the user defined environments.

**Comment by Elycin** [comment]
I may have overlooked this, and I'm glad I just found it.  
There's a checkbox to inherit apparently.
![image](https://user-images.githubusercontent.com/33913289/43301568-0ddcf46c-9134-11e8-9b28-bfbbbfa16ae3.png)

This solved it!

**Comment by Elycin** [comment]
Thank you for the quick replies and assistance!

**Comment by AaronRobinsonMSFT** [comment]
Awesome - yep, the Visual Studio debugger has that exact same option 😄
