### ISSUE TITLE
Finalizer is called on live object

### ISSUE THREAD

**Issue by buybackoff** [dotnet/coreclr#19161]
[This test](https://github.com/Spreads/Spreads/blob/d5a9239cbea0df292c14abaac783ecd63efed9d7/tests/Spreads.Core.Tests/Cursors/AsyncCursorTests.cs#L452-L530) fails not always but reliably when [run multiple times in a loop](https://github.com/Spreads/Spreads/blob/d5a9239cbea0df292c14abaac783ecd63efed9d7/tests/Spreads.Core.Run/Program.cs#L10-L17).

The [problem I observe](https://github.com/Spreads/Spreads/blob/d5a9239cbea0df292c14abaac783ecd63efed9d7/tests/Spreads.Core.Tests/Cursors/AsyncCursorTests.cs#L499) is that an object is finalized (and GCed if I comment the finalizer away) when there are strong references to it from within async task that is being awaited later. [Here](https://github.com/Spreads/Spreads/blob/d5a9239cbea0df292c14abaac783ecd63efed9d7/tests/Spreads.Core.Tests/Cursors/AsyncCursorTests.cs#L512) and [here](https://github.com/Spreads/Spreads/blob/d5a9239cbea0df292c14abaac783ecd63efed9d7/tests/Spreads.Core.Tests/Cursors/AsyncCursorTests.cs#L514) there are references that cause side effects (`Console.Write`) and dereference the object to return a value outside the task. Optimizer should not be allowed to kill the object earlier that this, but the behavior remains even in debug build with F5. The [async loop](https://github.com/Spreads/Spreads/blob/d5a9239cbea0df292c14abaac783ecd63efed9d7/tests/Spreads.Core.Tests/Cursors/AsyncCursorTests.cs#L503-L510) hangs, I see that the cursor is finalized [here](https://github.com/Spreads/Spreads/blob/d5a9239cbea0df292c14abaac783ecd63efed9d7/src/Spreads.Core/AsyncCursor.cs#L905) (even breakpoint is hit in debug mode in the finalizer).

This behavior is visible only when I explicitly call `GC.Collect(0+, GCCollectionMode.Default, false/true);` from another thread than the object is referenced from (the more aggressive GC.Collect params the earlier it happens). However, the code is optimized for allocations (the object in question is `IValueTaskSource`) and probably I just do not see normal GCs during small tests. Also I often do call GC0 explicitly in real code to avoid GC1 and keep memory low, [my experiments showed](https://github.com/aspnet/KestrelHttpServer/issues/2620#issuecomment-393009892) that pauses are much shorter and GC1 is much rarer with explicit calls to GC0. -so the scenario is quite real in production code.

 If I declare the cursor outside a task like [here](https://github.com/Spreads/Spreads/blob/d5a9239cbea0df292c14abaac783ecd63efed9d7/tests/Spreads.Core.Tests/Cursors/AsyncCursorTests.cs#L490) the problem disappears.

There is [a place where I create a `WeakReference`](https://github.com/Spreads/Spreads/blob/d5a9239cbea0df292c14abaac783ecd63efed9d7/src/Spreads.Core/Series'2%20(Base).cs#L1088) to that object if that may be relevant, maybe it somehow affects GC.

To reproduce, clone the repo with submodules and hit F5 to run `Spreads.Core.Run` project. Expected behavior is that it prints `Finished, press enter to exit...`, but now it prints `Called AsyncCursor finalizer` and hangs after several iterations.

Is this a bug in GC or some weird feature?

Tested with `netcoreapp2.1` (`both with 2.1.300` and `2.1.400-preview-009063` set via global.json on Windows and Linux in Docker) and with `net462`. 

```
[Test]
public async Task CouldReadDataStreamWhileWritingFromManyThreads()
{
    var map = new SortedMap<int, int>();

    var count = 10_000;
    var rounds = 100;

    var writeTask = Task.Run(async () =>
    {
        for (int j = 0; j < rounds; j++)
        {
            var t1 = Task.Run(async () =>
            {
                //using (Benchmark.Run("Write", count, true))
                {
                    for (int i = j * count; i < (j + 1) * count; i++)
                    {
                        await map.TryAddLast(i, i);
                    }
                }
                
                // even with 0 and false AsyncCursor it is finalized, but needs more iterations. With Optimized works OK
                GC.Collect(1, GCCollectionMode.Default, true);

                // `using (Benchmark.Run...` does this, found it during benchmarking
                //GC.Collect(2, GCCollectionMode.Forced, true);
                // GC.WaitForPendingFinalizers();
                //GC.Collect(2, GCCollectionMode.Forced, true);
                //GC.WaitForPendingFinalizers();
            });
            await t1;
        }
    });

    var cnt = 0L;

    // if we put it here everything works as expected
    // ICursor<int, int> cursor;

    var readTask = Task.Run(async () =>
    {
        var lastKey1 = 0;
        for (int r = 0; r < 1; r++)
        {
            // using (Benchmark.Run("Read", count, true))
            {
                // PROBLEM: cursor is collected and finalized before async loop finishes
                ICursor<int, int> cursor;
                using (cursor = map.GetCursor())
                {
                    while (await cursor.MoveNextAsync())
                    {
                        Interlocked.Increment(ref cnt);
                        if (cnt == count * rounds)
                        {
                            Console.WriteLine("Reader reached the end, waiting for complete signal");
                        }
                    }
                    // here is a strong reference to cursor with side effects of printing to console
                    Console.WriteLine("Last value: " + cursor.Current.Key);
                    // another strong reference after while loop, we dereference it's value and return from task
                    lastKey1 = cursor.CurrentKey;
                }
            }
        }

        return lastKey1;
    });

    writeTask.Wait();
    await map.Complete();
    Console.WriteLine("Read after complete:" + Interlocked.Read(ref cnt));
    var lastKey = await readTask;
    Console.WriteLine("Last key: " + lastKey);
    // Benchmark.Dump();
    map.Dispose();
}

```

**Comment by AaronRobinsonMSFT** [comment]
cc @tommcdon

**Comment by buybackoff** [comment]
Investigating further, I found this is a known gotcha. Yet ignoring side effects from continuations feels like too much of optimization that makes programs incorrect.

https://stackoverflow.com/questions/26957311/why-does-gc-collects-my-object-when-i-have-a-reference-to-it
https://stackoverflow.com/questions/18091002/what-gotchas-exist-with-tasks-and-garbage-collection
https://stackoverflow.com/questions/22268569/async-await-custom-awaiter-and-garbage-collector
https://blogs.msdn.microsoft.com/pfxteam/2011/10/02/keeping-async-methods-alive/

The solution is to [allocate GCHandle from `OnCompleted` method of `IValueTaskSource`](https://github.com/Spreads/Spreads/blob/ae55c1c02c21cbd5edab6936ea247555c48038ef/src/Spreads.Core/AsyncCursor.cs#L477) and free it on [completion](https://github.com/Spreads/Spreads/blob/ae55c1c02c21cbd5edab6936ea247555c48038ef/src/Spreads.Core/AsyncCursor.cs#L522) and [`Dispose`](https://github.com/Spreads/Spreads/blob/ae55c1c02c21cbd5edab6936ea247555c48038ef/src/Spreads.Core/AsyncCursor.cs#L850). Performance degrades quite visibly by c.10-20%.

Now I understand what is going on and maybe it makes some weird sense to move responsibility of keeping completion rooted on programmer from compiler. Like in this perfectly worded [quote](https://blogs.msdn.microsoft.com/pfxteam/2011/10/02/keeping-async-methods-alive/) by @stephentoub :)

> when you await something, it’s that something which needs to keep the async method’s execution alive via a reference to the continuation object that’s provided by ‘await’ to the awaited awaitable’s awaiter

Maybe there are some other techniques to keep the object alive?

**Comment by svick** [comment]
The "known gotcha" is that objects related to code that is guaranteed to never be executed can be garbage collected (and that includes code that is only referenced though a weak reference and some incorrect uses of PInvoke).

Otherwise, when you `await` a task, all necessary local state becomes referenced by that task. And the code that will complete the task in the future has a strong reference to that task (and is in turn referenced by objects that are alive), so your local state won't be collected.

If you think your code does not fall within this gotcha, can you produce short sample that demonstrates the issue, independent of your project? That makes it much easier to investigate.

I certainly find it hard to imagine that using `GCHandle.Alloc` would be the right solution.

I haven't looked at your code in detail, but could this be caused by the weak reference doing exactly what it's supposed to do?

**Comment by buybackoff** [comment]
@svick 
> when you await a task, all necessary local state becomes referenced by that task. 

From what I have read on the issue even an awaited task does not reference the continuation (`Action` passed to `OnCompleted`) and objects are stored locally in a state machine.

> And the code that will complete the task in the future has a strong reference to that task (and is in turn referenced by objects that are alive), so your local state won't be collected.

I'm working not with `Task` but with a custom implementation of `IAsyncEnumerable` whose `enumerator` is `IValueTaskSource` and `IAsynStateMachine`. The object being finalized is this enumerator.

> I certainly find it hard to imagine that using GCHandle.Alloc would be the right solution.

One of the linked SO question shows similar example with `TaskCompleteionSource` that requires GCHandle.

> could this be caused by the weak reference doing exactly what it's supposed to do

WeakReference + Finalizer are for cleaning if I forget to dispose an object, I believe WR does not affects this issue. Making it a strong one makes the problem disappear, as expected, but will leak undisposed objects in my case.

> can you produce short sample that demonstrates the issue, independent of your project?

Unfortunately unlikely in the next two weeks, `GCHandle` unblocked me for now for other things due to this delay. My `IAsyncEnumerable` is inspired by [ManualResetValueTaskSourceTests](https://github.com/dotnet/corefx/blob/master/src/System.Threading.Tasks.Extensions/tests/ManualResetValueTaskSourceTests.cs) and Channels implementation by @stephentoub. Maybe later I could tweak that sample to the same condition with finalization.

**Comment by stephentoub** [comment]
I've not looked at the large repro, but generally if you find a need to use a gchandle in this situation, something else is wrong (that's of course not 100%, but it's generally true). Someone must be responsible for calling SetResult/Exception to complete the operation... what code is that and what's triggering it? At the end of that chain, that thing should almost invariably be rooted. And in part because of that it doesn't make sense for the compiler or runtime to artificially root the state machine object, which is not only expensive to do when it's not truly needed (almost never, since it should be rooted elsewhere), but it's also a massive leak waiting to happen... there's no requirement that an await complete, in which case the compiler/runtime would leak the state machine object and everything it references. This should not / will not change.

> From what I have read on the issue even an awaited task does not reference the continuation (Action passed to OnCompleted) and objects are stored locally in a state machine.

I do not understand this statement. An awaited Task contains a strong reference to the Action (or in .NET Core 2.1, the state machine itself to avoid needing to allocate the delegate) given to it by the awaiter, either directly in the common case or indirectly via an intermediate object in less common cases, like if there are multiple continuations registered, if there's a synchronization context, etc.

**Comment by stephentoub** [comment]
> Making weak reference strong fixes the problem, but if a subscriber is no longer interested in updates and is referenced only from publisher than it will leak.

By using a GCHandle in your awaiter, in this scheme you're effectively creating a strong reference, but in a really expensive way, working around the further expense of using a weak reference. Sounds like you should allow for your publisher to support strong references either instead of or in addition to the current weak reference support.

> What I did not understand is why continuation having a reference to the object doesn't keep it alive.

But you do now, right? It doesn't matter if the continuation references the object if the continuation itself isn't being kept alive, and so on all the way back to a root.

**Comment by stephentoub** [comment]
> is there some additional work done on ManualResetValueTaskSourceTests and IAsyncEnumerable implemented as IAsyncStateMachine/IValueTaskSource<bool> since your prototype in May

Yes, e.g. https://github.com/dotnet/roslyn/pull/28218.
