### ISSUE TITLE
[Question] Strange behavior when loading assemblies and its dependencies programatically

### ISSUE THREAD

**Issue by FDUdannychen** [dotnet/coreclr#19374]
Not sure if it's a bug, I asked on SO but it seems no one has idea on it. [Question](https://stackoverflow.com/questions/51738633/strange-behavior-when-loading-assemblies-and-its-dependencies-programatically)

**Comment by vitek-karas** [comment]
Kind of unfortunately all of the behavior you describe is currently as designed. That doesn't mean it's intuitive (which it's totally not). Let me try to explain.

Assembly binding happens based on AssemblyLoadContext (ALC). Each ALC can have only one version of any given assembly loaded (so only one assembly of a given simple name, ignoring versions, culture, keys and so on). You can create a new ALC which then can have any assemblies loaded again, with same or different versions. So ALCs provide binding isolation.

Your .exe and related assemblies are loaded into a Default ALC - one which is created at the start of the runtime.

Assembly.LoadFrom will try to load the specified file into the Default ALC - always. Let me stress the "try" word here. If the Default ALC already loaded assembly with the same name, and the already loaded assembly is equal or higher version, then the LoadFrom will succeed, but it will use the already loaded assembly (effectively ignoring the path you specified). If on the other hand the already loaded assembly is of a lower version then the one you're trying to load - this will fail (we can't load the same assembly for the second time into the same ALC).

Assembly.LoadFile will load the specified file into a new ALC - always creates a new ALC. So the load will effectively always succeed (there's no way this can collide with anything since it's in its own ALC).

So now to your scenarios:

### Test1
This works because your ResolveAssembly event handler loads the two assemblies into separate ALCs (LoadFile will create a new one, so the first assembly goes to the default ALC, and the second one goes into its own).

### Test2
This fails because LoadFrom tries to load the assembly into the Default ALC. The failure actually occurs in the AssemblyResolve handler when it calls the second LoadFrom. First time it loaded v1 into Default, the second time it tries to load v2 into Default - which fails because Default already has v1 loaded.

### Test3
This fails the same way because it internally does basically exactly what Test2 does. [Assembly.LoadFrom](https://github.com/dotnet/coreclr/blob/d485659348af3528b688ac5b7e4c58dacba6de58/src/System.Private.CoreLib/src/System/Reflection/Assembly.CoreCLR.cs#L85) also registers event handler for AssemblyResolve and that makes sure that dependent assemblies can be loaded from the same folder. So in your case v1\Wrapper.V1.dll will resolve its dependency to v1\ThirdPartyDependency.dll because it's next to it on the disk. Then for v2 it will try to do the same, but v1 is already loaded, so it fails just like in Test2. Remember that LoadFrom loads everything into the Default ALC, so collisions are possible.

Your questions:

### Question1
LoadFile works because it loads the assembly into its own ALC, which provides full isolation and thus there are never any conflicts. LoadFrom loads the assembly into the Default ALC, so if that already has assembly with the same name loaded, there might be conflicts.

### Question2
The version is actually not ignored. The version is honored which is why Test2 and Test3 fail. But I might not understand this question correctly - it's not clear to me in which context you're asking it.

### CLR binding order
The order of Rules you describe is different.
It's basically:
- Rule2 - if it's already loaded - use it (including if higher version is already loaded, then use that)
- Rule1 - if everything fails - as a last resort - call AppDomain.AssemblyResolve

Rule 3 actually doesn't exist. .NET Core doesn't have a notion of probing paths or code base. It sort of does for the assemblies which are statically referenced by the app, but for dynamically loaded assemblies no probing is performed (with the exception of LoadFrom loading dependent assemblies from the same folder as the parent as described above).

### Solutions
To make this fully work, you would need to do either:
- Use the LoadFile along with your AssemblyResolve handler. But the problem here is that if you LoadFile an assembly which itself has other dependencies, you will need to handle those in your handler as well (you lose the "nice" behavior of LoadFrom which loads dependencies from the same folder)
- Implement your own ALC which handles all dependencies. This is technically the cleaner solution, but potentially more work. And it's similar in that regard that you still have to implement the loading from the same folder if needed.

We are actively working on making scenarios like this easy. Today they are doable, but pretty hard. The plan is to have something which solves this for .NET Core 3. We're also very aware of the lack of documentation/guidance in this area. And last but not least, we are working on improving the error messages, which are currently very confusing.

**Comment by FDUdannychen** [comment]
@vitek-karas Thanks for your great answer, very clear and detailed explanations and thanks for the solutions.

**Comment by vitek-karas** [comment]
@richlander has a good description and some source here https://github.com/richlander/dotnet-core-assembly-loading. The "gutenapp" contains implementations of ALC which can load "plugins" and a like.

Then there is also this blog post along with the code: https://natemcmaster.com/blog/2018/07/25/netcore-plugins/
This can be easily used to load plugins and alike.

I know the current state of things is not ideal as lot of these APIs are not intuitive and sometimes require non-trivial amount of code to get them to do what you want. All I can say is - we're working on it :-). Hopefully we'll have some designs to discuss soon.

**Comment by ritchxu** [comment]
@vitek-karas I bumped into this issue while posting https://github.com/PowerShell/PowerShell/issues/11571, I know it's PowerShell Core, but I would suspect the underlying cause might be the same, and I was trying workaround you mentioned in this issue. Could you point out if I missed anything there?

**Comment by vitek-karas** [comment]
This is a design problem in PowerShell Core - it loads all modules into the default ALC. Default ALC is special in that it doesn't allow overwriting the AssemblyLoadContext.Load which normally handles resolution before any default logic kicks in. (This is necessary, overwriting default Load can lead to really nasty situations). The even you register a handler for only fires if the default resolution logic can't find the assembly.

In this case it did find the assembly, but of a different version. Only one version of an assembly can be loaded into an ALC, so it fails. In fact it's a bit more complicated, if the already loaded assembly is higher version, it would simply return that, but if it's lower version, it would need to load a higher version somehow, which it can't - so it fails.

There's no easy workaround I know of today (theoretically you could write a wrapper around your module, which would load the real module in a secondary ALC and forward all the calls - this would let you implement the actual isolation yourself).

There are several internal discussion currently about this problem, but it all boils down to the fact the PSCore will have to start loading modules into isolated ALCs - which is definitely a non-trivial change.

**Comment by ritchxu** [comment]
Thank you very much for your prompt response. Some follow-up questions:

> The even you register a handler for only fires if the default resolution logic can't find the assembly.

I suppose this is why my registered handler won't fire?

> if the already loaded assembly is higher version, it would simply return that

In fact, the already-loaded version was higher, and the later-imported version was lower, why would it still fail?

> which would load the real module in a secondary ALC and forward all the calls

Is there any sample code you have in hand?

**Comment by vitek-karas** [comment]
> In fact, the already-loaded version was higher, and the later-imported version was lower, why would it still fail?
Interesting - I would have to investigate this in detail... but for this particular problem I don't think it's worth it - mainly because it would be enough that one order doesn't work (even if the other does) - I assume you need this to be reasonably robust (as in order independent).

Sample - we only have a generic "How to write an app with plugins sample":
https://docs.microsoft.com/en-us/dotnet/core/tutorials/creating-app-with-plugin-support
And a full solution which you can download an play with: https://github.com/dotnet/samples/tree/master/core/extensions/AppWithPlugin

This doesn't show how to do the "wrapper" approach.
