### ISSUE TITLE
Assertion failed 'op1->OperGet() == GT_LONG || op1->OperGet() == GT_MUL_LONG'

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#19397]
x86 Checked Windows CoreFX JitStressRegs=8

https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86/job/jitstress/job/x86_checked_windows_nt_corefx_jitstressregs8/554/consoleText

hundreds of instances of:
```
  Assert failure(PID 2868 [0x00000b34], Thread: 2232 [0x08b8]): Assertion failed 'op1->OperGet() == GT_LONG || op1->OperGet() == GT_MUL_LONG' in 'System.Text.OSEncoding:GetMaxByteCount(int):int:this' (IL size 55)
  
      File: d:\j\workspace\x86_checked_w---fb0ba759\src\jit\codegenxarch.cpp Line: 8653
      Image: D:\j\workspace\x86_checked_w---fb0ba759\_\fx\bin\testhost\netcoreapp-Windows_NT-Release-x86\dotnet.exe
```

This has been failing for a while.

@dotnet/jit-contrib

**Comment by sandreenko** [comment]
The issues was introduced/appeared after #18941.

**Comment by CarolEidt** [comment]
> Note that JitStressRegs=8 seems to be fundamentally broken

This is true because #18941, in the process of fixing a bug, caused more `COPY`s to be inserted in stress mode, particularly JitStressRegs=8 where we reverse the caller/callee preference and wind up with many more cases that look like codegen requires a register from a specific set - so we require a copy to convey the actual register assigned. As it happens, there seem to be a number of places where we're not handling the copy correctly - particularly involving multiple registers.
