### ISSUE TITLE
ICU 52 requirement not documented

### ISSUE THREAD

**Issue by Marqin** [dotnet/coreclr#1941]
I've installed DNX SDK and some parts of coreCLR were not working for me. It was because my distro (Arch Linux) have ICU 55, and coreCLR from this site is build for ICU 52 ( so I had to rebuild coreCLR, or put ICU 52 in linker path ).

There should be mention about ICU 52 on DNX SDK instruction for Linux.

**Comment by blackdwarf** [comment]
In PR.

**Comment by Marqin** [comment]
Why it's closed? It's not fixed in #2386

**Comment by blackdwarf** [comment]
@Marqin sorry, I closed it because with the new toolset (dotnet cli) you will not use DNX anymore and all of the needed dependencies will come down with the native installers (this is at least true for Ubuntu). So, the following line:
>There should be mention about ICU 52 on DNX SDK instruction for Linux.

is not valid anymore. Do you feel we should reopen the issue?

**Comment by kangaroo** [comment]
@blackdwarf ICU 52 is still required.  Try to build corert on ubuntu 15.10, and it will fail since the current runtime packages System.Globalization.Native.so dynamically links against icu52.  Ubuntu has moved to icu55.

This is something that we probably don't want to address with documentation, but in some other fashion (bundling icu).  The current situation is against the plan of 'drop in runtime and play'

**Comment by Marqin** [comment]
You should statically link libicu52, or move to 55 like most distros.

2016-01-22 20:54 GMT+01:00 Geoff Norton <notifications@github.com>:

**Comment by Marqin** [comment]
@kangaroo made #2834 for that.

**Comment by kangaroo** [comment]
@Marqin :+1:
