### ISSUE TITLE
Create New Minimal Start From Scratch CoreClr

### ISSUE THREAD

**Issue by zero0000zero** [dotnet/coreclr#19529]
How to create new minimal start from scratch CoreClr?

**Comment by mattwarren** [comment]
Why, for what reason? Is there something missing from the existing CoreCLR?

Is this because you want to go into production with a replacement CoreCLR? As a learning exercise? Or something else?

If you want to learn about creating a minimal .NET runtime you should take a look at a [write-up I did on DotNetAnywhere](http://mattwarren.org/2017/10/19/DotNetAnywhere-an-Alternative-.NET-Runtime/), it's **not** fully compatible with .NET, has some missing functionality, but it's certainly minimal and the code is easy to follow. Also this talk by the author of DotNetAnywhere is pretty interesting [So you want to create your own .NET runtime?](https://www.youtube.com/watch?v=jK8jYQ3ZKiI)

**Comment by AaronRobinsonMSFT** [comment]
More details on this question: dotnet/cli#9779

**Comment by zero0000zero** [comment]
I tried DotNetAnywhere. I built it but it cannnot run demo game. It has good structure though.

**Comment by mattwarren** [comment]
Yeah, it's far from production ready and it's no longer maintained, so that won't change. 

But, it is a really useful learning resource and it was the .NET runtime for the [initial version of Blazor](http://blog.stevensanderson.com/2017/11/05/blazor-on-mono/), so it's served it's purpose!
