### ISSUE TITLE
Avx2.Permute8x32 and Avx.PermuteVar - wrong mask base type for Single and Double overloads

### ISSUE THREAD

**Issue by 4creators** [dotnet/coreclr#19579]
Definition of Avx2.Permute8x32 has wrong type of second parameter:
```C#
        /// <summary>
        /// __m256 _mm256_permutevar8x32_ps (__m256 a, __m256i idx)
        ///   VPERMPS ymm, ymm/m256, imm8
        /// </summary>
        public static Vector256<float> PermuteVar8x32(Vector256<float> left, Vector256<float> mask) => PermuteVar8x32(left, mask);
```
Intel intrinsics single overload has the following signature:

```C
    __m256 _mm256_permutevar8x32_ps (__m256 a, __m256i idx)
```

The reason for second parameter (third instruction operand) being integral type is that it is used to express index values used during permutation where 3 first bits of each integer are used to encode destination location. Trying to express that pattern using single floats could be mind boggling.

**Comment by saucecontrol** [comment]
Avx.PermuteVar is set up the same way, as are Avx.MaskStore and Avx.MaskLoad.  I'd think those should also have the same-sized integral type for the mask

**Comment by fiigii** [comment]
> Avx.PermuteVar is set up the same way, 

Right, the second parameter of `Avx.PermuteVar` is a "control" vector rather than "mask". @4creators could you please fix this one as well in your PR.

> Avx.MaskStore and Avx.MaskLoad.

No, `Avx.MaskStore` and `Avx.MaskLoad` is different whose parameters are "mask" (not "control" or "index"). We have decided that mask vectors should have the same base type as data vectors because usually mask vectors are generated from previous intrinsics (e.g., `Compare`) that operate over the same data vectors.

**Comment by saucecontrol** [comment]
Makes sense.  Thanks @fiigii

**Comment by 4creators** [comment]
@fiigii Will do

**Comment by saucecontrol** [comment]
> vector operands used for instruction are type agnostic

That's true, and the codegen is agnostic.  I'm only confused by the Intrinsic mappings in hwintrinsiclistxarch.h since they have those type columns.  I don't follow how they're used or how a method with two different vector base types would be mapped.  I also don't see any existing methods that mix vector types
