### ISSUE TITLE
Running corefx tests on debug coreclr bits fails with invalid assertion.

### ISSUE THREAD

**Issue by Priya91** [dotnet/coreclr#1962]
Discovering: System.Runtime.InteropServices.RuntimeInformation.Tests

Assert failure(PID 41229 [0x0000a10d], Thread: 41229 [0xa10d]): Assertion failed 'lvRefCnt' in 'System.Threading.EventWaitHandle:.ctor(bool,int,ref):this' (IL size 178)

    File: /home/matell/git-release/coreclr/src/jit/compiler.hpp Line: 1799
    Image: /home/lasekar/Documents/linuxlibs/bin/com/corerun

**** MessageBox invoked, title 'corerun - Assert Failure (PID 41229, Thread 41229/0xa10d)' ****
  Assertion failed 'lvRefCnt' in 'System.Threading.EventWaitHandle:.ctor(bool,int,ref):this' (IL size 178)

**Comment by LLITCHEV** [comment]
@Priya91 Priya, could you please retest this? I suspect this is a packaging issue. I just pulled and rebuilt the coreclr and corefx (had to revert the commit # c60913a91853a2c6b9f9ac46e81ca91aac775e8d per ellismg and stephentoub suggestion - it turns out theSystem.Console.dll that is posted in Nuget right now is not compatible with this changes and trying to use it thrown MissingEntryPointException. I was told the right dll will be included in tomorrows build) and run both sets of tests. They all passed.
=== TEST EXECUTION SUMMARY ===
   System.Runtime.InteropServices.RuntimeInformation.Tests  Total: 2, Errors: 0, Failed: 0, Skipped: 0, Time: 11.475s

**Comment by LLITCHEV** [comment]
Seems to work fine with the latest corefx bits.
