### ISSUE TITLE
Memory Corruption using System.Numerics.Vector3

### ISSUE THREAD

**Issue by daeken** [dotnet/coreclr#19674]
I've discovered a memory corruption bug which seems to affect `Vector3`s passed to functions.  This minimal test case crashes consistently for me on Windows 10 (x64 running on a Ryden CPU) using .NET Core 2.1.301.  The same test does not crash for me on MacOS with the same version of .NET Core.

```cs
using System.Numerics;
namespace NumericCorruption {
  class Program {
    static void Main(string[] args) {
      var vec0 = new Vector3(0, 0, 0);
      Test(vec0);
    }
    static void Test(Vector3 vec0) {
      //vec0.X = -vec0.X; // Uncommenting this line will cause an access violation on the `new` line
      vec0.X = 0; // Uncommenting this line will cause a null reference exception (?!) on the `new` line
      new Vector3(vec0.X, vec0.Y, vec0.Z);
    }
  }
}
```

As indicated, some degree of control is possible so this may have security implications in some regard.  It also only appears to occur when the Vector3 is passed to another function; if you perform the same operations inside a given function, everything works as expected.  Also, this only seems to occur when you *assign* one of the vector components; accessing components is fine, as is assigning whole vectors.

**Comment by daeken** [comment]
Thanks for digging into this so quickly!  For what it's worth, both debug and release builds seem to fail on Windows for me, in the same ways (access violation if I uncomment out that first line, null ref if I uncomment the second).  Neither causes a crash on MacOS.  Bit puzzling as to why it's not crashing there as well.

**Comment by saucecontrol** [comment]
Ah yeah, I guess if you get past the asserts you just end up with an uninitialized local.  It works fine for me in release mode on Windows, but I can get it to fail every time by adding `[MethodImpl(MethodImplOptions.NoInlining)]` to the method.  I happened to be debugging the JIT trying to figure out how the magic works with the SIMD types and figured I'd look at it.  I'm otherwise in over my head.  I'm sure somebody on the JIT team can figure it out.

Oh, and my apologies if it was inappropriate to tag the contrib group.  I didn't realize how many people were on that list 😮

**Comment by jakobbotsch** [comment]
> Not sure why it wouldn't fail the same on MacOS unless you're doing a release build there and debug on Windows.

Like @mikedn said, structs > 8 bytes are passed by ref on Windows (dictated by the calling convention there). OS X follows the SysV ABI which passes such structs by value instead. Considering the analysis by @mikedn above it seems likely to be the reason in this case.

**Comment by AndyAyersMS** [comment]
cc @dotnet/jit-contrib
