### ISSUE TITLE
Update NetPerf File ThreadID to 64-bits

### ISSUE THREAD

**Issue by brianrob** [dotnet/coreclr#19688]
The current value is 32-bits which will truncate the full value on OSX.

**Comment by noahfalk** [comment]
The core support to capture the id, serialize it in a nettrace file, and then parse it in TraceEvent has been implemented (#24853 in coreclr, https://github.com/microsoft/perfview/pull/948 in perfview). There is no higher level support in the TraceEvent API or Perfview to actually expose that 64 bit ID so for now it gets to the profiler and then immediately gets truncated back to 32 bits.

@josalem - Can you give this a try on Mac to confirm that the 64 bit ID is correctly crossing the wire? You'll have to use a debugger on TraceEvent because the ID just gets truncated internally and is exposed 32 bit in the API.

**Comment by josalem** [comment]
Just validated that the format does indeed encode and decode a 64 bit value (it gets truncated to 32 bits after being decoded when exposed via API).
