### ISSUE TITLE
An Action registered at CancellationToken is always called in netcoreapp2.1 and never in netcoreapp2.0 or net471

### ISSUE THREAD

**Issue by Tragetaschen** [dotnet/coreclr#19839]
I'm running this code on `netcoreapp2.1`, `netcoreapp2.0`, and `net471`:
```cs
public static async Task Main()
{
    async Task work(CancellationToken token)
    {
        using (token.Register(() => Console.WriteLine("called!")))
            await Task.Delay(10000, token);
    }

    var cts = new CancellationTokenSource();
    var task = Task.Run(() => work(cts.Token));
    await Task.Delay(1000);
    cts.Cancel();
    try
    {
        await task;
    }
    catch (OperationCanceledException)
    {
    }
    Console.WriteLine("done");
}
```
On `netcoreapp2.0` and `net471`, the Console output in the `CancellationToken.Register` call is never present, while on `netcoreapp2.1`, it's always there.

Looking through the commits, I would assume that a4094d24956f4a03542317d7c2f84642a36ba93d from @stephentoub is the reason. Skimming through the changes, it looks like the list of registered cancellation callbacks is now snapshotted and then iterated over where before, disposing a registration (as part of the continuation) live-changes the callbacks that are going to be executed.

I personally don't have any code that depends on the older behavior and my mental model is absolutely in line with the `netcoreapp2.1` implementation, but it took some time to figure out why my mental model didn't apply: I publish for `net471` and run on Mono where there is the older behavior (and the callback didn't run to my surprise), but my test application was running as `netcoreapp2.1` initially and showed the behavior I expected.

**Comment by kouvel** [comment]
CC @tarekgh

**Comment by stephentoub** [comment]
Thanks for reporting this.  This is a real problem.  More specifically, the issue I'm most concerned about isn't exactly what you highlighted, but a follow-on ramification of it: it's possible now that CancellationTokenRegistration.Dispose might return and after it returns the associated registration could still be invoked.  That's really bad, because the whole point of that Dispose guarantee (that once it returns either the registration has fully run or will never run) is that code can then know that mutations performed by that registration won't happen after Dispose.  That guarantee is now broken in the situation where cancellation callbacks have started running but it hasn't yet gotten to invoke the callback in question; if it's disposed then, Dispose will return immediately and the callback will still run after that.

Repro:
```C#
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

class Program
{
    public static void Main()
    {
        var ctr2blocked = new ManualResetEventSlim();
        var ctr2running = new ManualResetEventSlim();
        var cts = new CancellationTokenSource();

        var ctr1 = cts.Token.Register(() => Console.WriteLine("Should never see this"));

        var ctr2 = cts.Token.Register(() =>
        {
            Console.WriteLine("ctr2 starting");
            ctr2running.Set();
            ctr2blocked.Wait();
            Console.WriteLine("ctr2 finishing");
        });

        // Cancel.  This will trigger ctr2 to run, as callbacks run in reverse registration order.
        Task.Run(() => cts.Cancel());
        ctr2running.Wait(); // wait for ctr2 to start running

        // Now that ctr2 is running, dispose of ctr1.  The contract
        // for Dispose is that once Dispose returns, you're guaranteed
        // that the registration has other finished running or will
        // never run.
        Console.WriteLine("Disposing ctr1");
        ctr1.Dispose(); // bug: guarantee not holding... ctr1 will still run after this

        Console.WriteLine("Unblocking ctr2");
        ctr2blocked.Set();

        // We end up seeing "Should never see this" :-(

        Console.ReadLine();
    }
}
```
