### ISSUE TITLE
[Continued] Support new Japanese era name

### ISSUE THREAD

**Issue by bendono** [dotnet/coreclr#19859]
#18209 introduced support for the upcoming new Japanese era name. Since then, Unicode has [announced](http://blog.unicode.org/2018/09/new-japanese-era.html) that the precomposed character has been reserved as `U+32FF`. Also, ICU later this year will introduce support as well.

1. Should CoreCLR be updated with the precomposed code point `U+32FF` in advance?
2. As CoreCLR has a dependency on ICU, are there plans to incorporate the upcoming version in advance?

**Comment by bendono** [comment]
FYI @tarekgh

**Comment by tarekgh** [comment]
> Should CoreCLR be updated with the precomposed code point U+32FF in advance?

Could you clarify that more? .Net Core just gets the era name from the OS. the OS will pass us the U+32FF and .NET Core doesn't really do any operations on the name. it just returned to the caller or include it in the formatted date. The OS will support adding fonts to support this code point. in summary, nothing really needs to be done in the .NETCore to support U+32FF.


> As CoreCLR has a dependency on ICU, are there plans to incorporate the upcoming version in advance?

We are waiting for ICU to release any build for testing we can test with. ICU will not be able to release any official build before Feb next year because the era name will not be released before then. after ICU have teh official build, it is up to the systems to upgrade their ICU packages to the latest and .NET core should just work by then. 

Let me know if you have any more questions.
