### ISSUE TITLE
Support New OS

### ISSUE THREAD

**Issue by alanking10105555** [dotnet/coreclr#19877]
The OS runs a new kind of assembly code. This kind of assembly code has a format that is minimal and portable.

### Assembly Format
multiple **instruction**

### Instruction Format
[**label**:] **operation** **source1** **source2** **destination**

**label** is location of the instruction.
**operation** is the do of the instruction.
**source1**, **source2**, **destination** are variable.

**variable**
is one of the type in this list:
Bool
Int
String
Array

**operation** is one of the do in this list:
new
and
or
not
add
subtract
multiply
divide
equal
bigger
smaller
append
index
count
call
return
goto
in
out

In this assembly format, .NET do file operation with the in and out operations.

**Comment by alanking10105555** [comment]
The assembly format is minimal and complete.

**Comment by tannergooding** [comment]
As a pointer...

In the case of the above "assembly format", there is not enough information to be actionable (even for a 3rd party to fork the codebase and add support).

You need to add information on the various encodings for the instructions (how each one is recognized by the CPU, how source and destination operands are specified, etc). You also need to define things like how data is passed around, how instructions are executed (in order, out of order, speculatively, etc), how memory access works, how parallelism works, etc.

Most CPU "Architecture Manuals" are several thousand pages long, because they specify all of this information and all of this information **is** needed for any compiler backend to successfully meet the requirements of any higher language specification (such as C#, CIL, C/C++, LLVM, etc)
