### ISSUE TITLE
Question about async with fibers (like java project Loom)

### ISSUE THREAD

**Issue by valeriob** [dotnet/coreclr#19937]
Hi,
i've looked briefly at Java project Loom : https://www.youtube.com/watch?v=J31o0ZMQEnI
If i understand correctly the project is exploring the application of using fiber to schedule computations instead of the threadpool, this would make all code automatically "async" optimized, because no thread would be stuck waiting, but just a fiber.
Is this concept been investigated on clr as an alternative to TPL/async-await ?

**Comment by svick** [comment]
What would be the advantage of having two different ways of achieving the same goal?

**Comment by svick** [comment]
@valeriob Right, that's the advantage of fibers, but that's not what I'm asking.

At this point, pretty much all libraries and presumably most applications that would benefit from this have already been converted to `async`-`await`. How does it make sense to introduce fibers at this point, especially since it would probably mean we would be stuck with having to deal with both kinds of dealing with asynchony (or all 4, if you count APM and EAP)?

**Comment by jkotas** [comment]
> Is this concept been investigated on clr as an alternative to TPL/async-await ?

Yes, this concept has been investigated in depth when the Task APIs were introduced originally and discussed number of times since then.

Some of the challenges with fibers are:
- OS fibers (as they exist on Windows OS) have regular stacks that makes them too expensive.
- The performant implementations need to use special stacks (segmented stacks or stack copying).
- The special stacks need to be switched to regular stack for interop that the Loom talk touches on it towards the end. This switching is not free. It basically just moves costs around. YMMV. Here is write up on Rust experience with segmented stack that has details about the trade-offs: https://mail.mozilla.org/pipermail/rust-dev/2013-November/006314.html.

It would be certainly be nice in some cases to not worry about whether to make method async or not. For better or worse, .NET choose to have explicit annotations for what needs to be async.

Our current thinking is keep improving efficiency async methods . For example, one async method cannot really be inlined into another async method today by the JIT. It is something we would like to fix.

**Comment by valeriob** [comment]
Thanks @jkotas ! I was asking exactly about the trade of that was chosen if fibers where investigated/prototyped 😄 
Do you know of any language that has implemented it ? I though that those where solved problem, at least for the BEAM vm.

**Comment by valeriob** [comment]
> golang

Thanks i did know that, that explains a lot 😄
