### ISSUE TITLE
PLinq .Distinct() almost-deadlocks even under very light load

### ISSUE THREAD

**Issue by EamonNerbonne** [dotnet/coreclr#20060]
The combination of `Task.Run` (or otherwise scheduling on a thread-pool e.g. via asp.net core controller) and PLinq `.Distinct()` causes thread pool starvation even under lightly loaded circumstances.  Many factors can contribute, but a simple and real-world case is simply when two requests happen to occur approximately simultaneously.

Once the threadpool is thus starved, if additional load comes in, even at a very, very low rate, the server will never recover while exhibiting no CPU load.

Repro code for a console app:
```C#
var FakeCpuCount = 32;//normally Environment.ProcessorCount, but core-heavy servers appear to suffer more.
const int NumberOfRequests = 10; //in a realistic scenario this would be much greater/unbounded, and the program would simply not terminate
const int SimultaneousRequestEvery = 4;
const int MillisecondsBetweenRequests = 300;
const int NumberOfDelays = NumberOfRequests*(SimultaneousRequestEvery-1)/SimultaneousRequestEvery;

ThreadPool.SetMinThreads(FakeCpuCount, FakeCpuCount);
//ThreadPool.SetMinThreads(FakeCpuCount*2, FakeCpuCount); // <--higher minthreads reduces likelihood of pseudo-deadlock, eliminating it in this example

var requests = new List<Task>();
var sw=Stopwatch.StartNew();
Task.Run(() => Thread.Sleep(2000));//some other threadpool load; need not be this constant in practice
foreach (var requestNumber in Enumerable.Range(0, NumberOfRequests)) {
    if (requestNumber % SimultaneousRequestEvery ==0) {
        Console.WriteLine("Starting request " + requestNumber + " WITHOUT DELAY");
    } else {
        Thread.Sleep(MillisecondsBetweenRequests);
        Console.WriteLine("Starting request " + requestNumber);
    }
    requests.Add(Task.Run(
        () => Enumerable.Range(0, 345).AsParallel()
            .WithDegreeOfParallelism(FakeCpuCount)
            .Distinct()//Not all PLinq operators exhibit pseudo-deadlock; e.g. .Where(n=>n%37!=0) is fine
            .ToArray() //normally: around 0.1ms, i.e. negligible compared to MillisecondsBetweenRequests
    ).ContinueWith(
        _=>Console.WriteLine("completed "+requestNumber)
    ));
}
var timeToStart = sw.ElapsedMilliseconds;
sw.Restart();
Console.WriteLine($"All requests started in {timeToStart}ms, i.e. with {timeToStart - MillisecondsBetweenRequests*NumberOfDelays}ms overhead");
Task.WaitAll(requests.ToArray());
Console.WriteLine($"All requests completed with {sw.ElapsedMilliseconds}ms additional overhead");
```

Expected output, achievable e.g. by raising the minimum thread-pool size:
```
Starting request 0 WITHOUT DELAY
completed 0
Starting request 1
completed 1
Starting request 2
completed 2
Starting request 3
Starting request 4 WITHOUT DELAY
completed 3
completed 4
Starting request 5
completed 5
Starting request 6
completed 6
Starting request 7
Starting request 8 WITHOUT DELAY
completed 7
completed 8
Starting request 9
All requests started in 2148ms, i.e. with 48ms overhead
completed 9
All requests completed with 0ms additional overhead
```

Actual output:
```
Starting request 0 WITHOUT DELAY
Starting request 1
Starting request 2
Starting request 3
Starting request 4 WITHOUT DELAY
completed 0
Starting request 5
Starting request 6
Starting request 7
Starting request 8 WITHOUT DELAY
Starting request 9
All requests started in 2110ms, i.e. with 10ms overhead
completed 1
completed 2
completed 3
completed 4
completed 5
completed 9
completed 7
completed 6
completed 8
All requests completed with 66901ms additional overhead
```

Behavior appears to be the same regardless of x64 vs. x86, and in both net472 and netcoreapp2.1

**Comment by EamonNerbonne** [comment]
A much shorter example of the same problem without the realism would be something like this:

```C#
Task StartIt() => Task.Run(() => Enumerable.Range(1, 100).AsParallel().Distinct().Sum());
Console.WriteLine("start");
Task.WaitAll(StartIt(), StartIt(), StartIt(), StartIt(), StartIt());
Console.WriteLine("end");
```

You'd expect that to run quickly, but it doesn't.

**Comment by jkotas** [comment]
cc @stephentoub

**Comment by EamonNerbonne** [comment]
Somewhat similar: https://github.com/dotnet/coreclr/issues/10292

**Comment by stephentoub** [comment]
PLINQ achieves parallelism by partitioning the work and processing those partitions on multiple queued work items, defaulting to using Environment.ProcessorCount workers. In many situations, these workers can effectively run independently, e.g. if you just have a Where and a Select, the data can be partitioned and handed off to each worker, and each worker can run independently, with the only additional synchronization being the merging of the results, and that can itself often happen in a streaming manner that doesn't require blocking one worker while another does processing. However, there are some operators (including Distinct) that require barriers during the processing, which means that all of the workers need to meet up at a particular location, do some work in tandem, and then can proceed independently.  As a result, PLINQ in general, but specifically when such operators are being used, assumes there will be at least Environment.ProcessorCount threads available to it in the thread pool, and as such is not a good fit when being used as part of processing an individual request if multiple requests may be processed in parallel.

This is inherent to the implementation design that's been in use in PLINQ since its initial release, and changing that to be one that doesn't require such barriers for those operators is a huge piece of work, if even feasible, and no one on the .NET team currently has any plans to take that on.

Changing the thread pool to have a faster rate of thread injection really isn't going to help in general here, and could often significantly hurt.  If you have an app serving requests, and each such request requires Environment.ProcessorCount threads in the pool, if the thread pool were changed to quickly inject additional threads, you could easily end up in a situation where a few thousand requests arrive to a 32-core box, the processing of each of those would require 32 threads, and you'd quickly exhaust all available resources to the app.  If you know your workload will end up only a certain number of requests being processed at any one time, you can size the ThreadPool appropriately to your needs via a mechanism like ThreadPool.SetMinThreads.  You can also limit the number of workers each PLINQ query uses via its WithDegreeOfParallelism operator.  And you can of course either choose not to use PLINQ at all in these situations, or avoid using operators requiring such barriers, falling back to sequential execution for them, e.g. `.AsParallel().Where(...).Select(...).AsSequential().Distinct(...)...`

**Comment by EamonNerbonne** [comment]
Yeah, this answer is kind of what I expected; it's a design issue that isn't easy to overcome.  Thanks for the detailed answers!

Some ideas:

 - Querying the number of "really available" threadpool threads (= min + available - max) is fairly cheap (on the order of 20ns) and could possibly be cheaper if the api changes.  We're considering that as a mitigation: if it's below procCount, use a serial path, or increase thread-pool size.  Obviously that leaves a small race condition - but one that is many orders of magnitude better than without the mitigation.
 - We tried increasing the threadpool size; that seems to have no negative consequences in our case, even with 10000 threads "running" (beyond a few hundred MB extra working set and a startup delay of around .2ms per thread) - what's the danger in doing that? This is equivalent to a faster rate of injection in some sense, and the reason it's still a speed up in our workload and I suspect most others is that even with async it's just very, very easy to have some amount of blocking somewhere deep in the stack; and furthermore you "waste" parallelism only in the unlikely event that you actually have two simultaneous parallel executions.
 - If a fix or workaround is off the menu it would be nice if `AsParallel()` and/or PLinq+async docs mentioned that they cannot be safely used together, in general.
 - perhaps something could throw instead of blocking?  Perhaps that's easier than a complete implementation rework?  A quick and analyzable crash tends to be much cheaper to deal with than a no-warning lockup.
 - Not sure about the threadpool implementation, but perhaps it would be easier to leave the barrier implementation in PLinq, and instead extend the ThreadPool api to allow block-allocation of threads?  If PLinq could ensure that either all N or none were allocated, you wouldn't get this nasty starvation behavior, and you could possibly get both decent parallelism, and fairly efficient (low-thread) concurrency with a threadpool of size 2*procCount.

You mention there's a risk of resource starvation if the threadpool were to more aggressively ramp up - and while that's definitely an unfortunate risk, it's *much* less likely and much less serious than the risk currently, at least as it pertains to PLinq.  Right now, you get resource (namely: threadpool) exhaustion even if just 2 barrier-using PLinq operations happen to execute concurrently, and in the server scenario you mention the app will *never* recover.  As the demo program shows, it takes many seconds to recover from a *single* collision, and during those seconds, any additional PLinq attempts can cause additional waiting.  We observed servers locking up even with loads of far below 1% - even that low load is enough for an additional request to occur during a period of lockup, thus magnifying the problem.

In any case: I understand it's not exactly a very tractable problem, and thanks for the analysis even if a complete solution may never happen.

**Comment by benaadams** [comment]
> even with 10000 threads "running" (beyond a few hundred MB extra working set and a startup delay of around .2ms per thread) - what's the danger in doing that? 

With the default OS thread stack sizes 10000 threads requires 80 GB of RAM on Ubuntu and 10GB of RAM on Windows (10000 x 8MB and 1000 x 1MB respectively)

**Comment by svick** [comment]
@stephentoub While I understand that PLINQ wasn't designed to work well in this kind of situation, it was also designed to look as a "magically make my code faster" button, so I think it should avoid such pathological behavior, at least with default settings.

While I don't understand the implementation of PLINQ very well, here are some ideas on how to improve this:

* As has been mentioned by @EamonNerbonne above, use some heuristic based on the number of available threadpool threads to decide the actual default degree of parallelism.
* Decrease the default degree of parallelism when other PLINQ queries are already executing. Since PLINQ is primarily meant for CPU-bound operations, this should not decrease performance in the common case by much.
* A combination of the two heuristics above.
* Instead of blocking the thread while it's waiting on the barrier, execute the work of a thread that hasn't started yet until it signals the barrier, kind of similar to what task inlining in `Task.Wait()` does.
* Use `async`-`await` for waiting on the barrier asynchronously. I think the big issue with this is that it would likely require changing almost all parts of PLINQ implementation to `async` (which would be a lot of work and could risk introducing bugs). Though with `ValueTask`, the performance penalty of this might be acceptable.
* Dynamically increase the degree of parallelism as new threads become available. This is probably not very realistic option, but since most operations are largely independent, maybe it could work? Specifically for hash-partitioned operations like `Distinct`, maybe [consistent hashing](https://en.wikipedia.org/wiki/Consistent_hashing) could decrease the cost of rehashing?

**Comment by stephentoub** [comment]
> what's the danger in doing that?

It's not just about memory consumption.  Oversubscription, especially that degree of oversubscription, often leads to significant slowdowns in real workloads.  Caches get thrashed.  A disproportionate period of time gets spent on thread swapping.  Paging often increases significantly.  Plus the work being done by the workload often incurs its own issues, e.g. it becomes much more likely for threads holding spin locks to be swapped out resulting in lots of live locking.  And work items often have their own resources, e.g. if a work item "rents" a 1MB buffer from a pool, does some work with it, and then returns the buffer to the pool, it's very likely that lots of large buffers will end up getting allocated and thrown away, increasing memory consumption, increasing LOH collections, and so on.  There are a myriad of deleterious effects that come from this kind of oversubscription.  That's why implementing a good thread pool is so hard.

> Querying the number of "really available" threadpool threads (= min + available - max) is fairly cheap (on the order of 20ns) and could possibly be cheaper if the api changes. We're considering that as a mitigation...
> As has been mentioned by @EamonNerbonne above, use some heuristic based on the number of available threadpool threads to decide the actual default degree of parallelism.

If that's appropriate for your own workload, go for it.  It's unlikely to be appropriate as a general heuristic built into PLINQ.  Consider a basic heuristic that set the degree of parallelism to `Max(1, Min(Environment.ProcessorCount, AvailableWorkerThreads))`.  Now consider a situation where the thread pool is idle, and on a 32-core machine, 32 work items are queued, each of which runs a query that requires this kind of blocking.  The first thread in the pool picks off the first work item, sees that there are 31 available threads, and queues another 31 work items.  The next thread in the pool picks off a work item, sees that there are 30 available threads, and queues another 30 work items.  And so on.  You still end up with most of the PLINQ queries end up blocking, requiring O(N^2) threads.  Or consider the opposite case, where the thread pool is fully busy and then the last work item to arrive is a PLINQ query that could benefit from full parallelization... it checks available threads, sees that it should run serially, but then all of the other threads become idle, and now you've got your query running serially when it would have benefited from parallelism.

> Decrease the default degree of parallelism when other PLINQ queries are already executing. Since PLINQ is primarily meant for CPU-bound operations, this should not decrease performance in the common case by much.

It could absolutely decrease performance in the "common case". In general, heuristics like this are really hard to get right.  You need to have a fully representative set of workloads, environments, etc., in order to be confident that the heuristic is actually helping rather than hurting.  And both of the heuristics you're talking about could be implemented in some form fairly easily by a consuming app if it cared to.

> We tried increasing the threadpool size; that seems to have no negative consequences in our case

You probably already know this, but commenting just in case... ThreadPool.SetMinThreads doesn't actually change the number of threads currently in the pool, i.e. calling it doesn't force that many threads to be injected immediately as part of the call.  Rather, it simply changes the level to which the thread pool will aggressively inject threads if any work item is waiting.  So, if you call SetMinThreads with 10,000 on an idle pool and then queue 50 work items, you'll likely end up with 50 threads, not 10,000.  Once those threads are done processing work items, those threads will stick around for a while, and then at some point the thread pool will decide to terminate them.

> If a fix or workaround is off the menu it would be nice if AsParallel() and/or PLinq+async docs mentioned that they cannot be safely used together, in general.

I'm not sure what this has to do with async.  This has to do with a PLINQ query essentially assuming it has full access to the machine's resources, which means if you're parallelizing at a higher level (e.g. handling multiple requests in parallel), you likely shouldn't be using PLINQ at the lower level (e.g. within the processing of a request), and if you do, you need to be careful about how you do it (e.g. explicitly controlling degree of parallelism, avoiding use of certain operators, etc.)

There's a page of potential PLINQ pitfalls in the docs:
https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/potential-pitfalls-with-plinq
Please feel free to submit a PR to the docs repo if there's important information missing.

> perhaps something could throw instead of blocking?

The threads need to all meet up in order to perform an exchange of information: there's pretty much always going to be some blocking in normal operation.  The specific case that's problematic is when one or more of the work items is delayed in getting to the join point, and a heuristic that sometimes throws in such a case would be very non-deterministic and IMHO much worse than the current status quo, nevermind being a significant breaking change.

> Not sure about the threadpool implementation, but perhaps it would be easier to leave the barrier implementation in PLinq, and instead extend the ThreadPool api to allow block-allocation of threads? If PLinq could ensure that either all N or none were allocated, you wouldn't get this nasty starvation behavior, and you could possibly get both decent parallelism, and fairly efficient (low-thread) concurrency with a threadpool of size 2*procCount.

See some of the discussion at https://github.com/dotnet/coreclr/issues/2184.

> Instead of blocking the thread while it's waiting on the barrier, execute the work of a thread that hasn't started yet until it signals the barrier, kind of similar to what task inlining in Task.Wait() does.
> Use async-await for waiting on the barrier asynchronously.

Both of these are valid, have been talked about in the past, and are some of what I refer to when saying that improving this would be a huge amount of work.
