### ISSUE TITLE
Question: Would Project Snowflake be merged into next version of CLR/C#?

### ISSUE THREAD

**Issue by ygc369** [dotnet/coreclr#20074]
Project Snowflake: http://www.microsoft.com/en-us/research/publication/project-snowflake-non-blocking-safe-manual-memory-management-net/

**Comment by jkotas** [comment]
We do not have plan to merge project Snowflake into mainline .NET Core. We have done analysis of the performance benefits on real world workloads. The benefits were not enough to justify the cost and complexity of the programming model.

BTW: One of the workload that showed the most promising improvements turned out to be hitting a GC bug. Once the bug got fixed, the promising improvements disappeared.
