### ISSUE TITLE
Concurrentqueue Performance Issues

### ISSUE THREAD

**Issue by DrDao** [dotnet/coreclr#20110]
I used some of the concurrentqueue to save the request, and when I measured it, I found that TPS dropped from 17000 to 3000.

When the test cycle was added to 50000, the Concurrentqueue had taken 1 points.

In applications where high throughput is required, concurrentqueue cannot be used at all.

![tim 20180924125445](https://user-images.githubusercontent.com/11530204/45938119-49c1ce00-bff9-11e8-9e24-05ad12a36404.jpg)
![tim 20180924125456](https://user-images.githubusercontent.com/11530204/45938120-4a5a6480-bff9-11e8-8cf7-0db550100f79.jpg)
![tim 20180924125504](https://user-images.githubusercontent.com/11530204/45938121-4a5a6480-bff9-11e8-8477-de22a86ffc28.jpg)

**Comment by Mr-Daomi** [comment]
Performance is similar to single write

![tim 20180924125702](https://user-images.githubusercontent.com/11530204/45938130-6f4ed780-bff9-11e8-8e96-aa7dfee86272.jpg)
![tim 20180924125712](https://user-images.githubusercontent.com/11530204/45938131-6f4ed780-bff9-11e8-967c-48a9b530d389.jpg)

**Comment by MarcoRossignoli** [comment]
> In applications where high throughput is required, concurrentqueue cannot be used at all.

I think you should test with some kind of "lock" on `Queue<int>` to compare...i mean if you want to use "concurrent" structure i think you'are in concurrent environment so you need to syncronize access to "non thread safe" `Queue<T>` https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.queue-1?view=netcore-2.1#thread-safety.
Another advice...you should do test "isolated"(but maybe you did it), if you test all in one console app i think you could incur in false positive due to garbage collector triggers etc....you could use tool like https://benchmarkdotnet.org/articles/guides/getting-started.html to obtain numbers.

I did simple single threaded test and ConcurrentQueue works better than Queue(with lock)
``` ini

BenchmarkDotNet=v0.11.1, OS=Windows 10.0.17134.285 (1803/April2018Update/Redstone4)
Intel Core i7 CPU 860 2.80GHz (Nehalem), 1 CPU, 8 logical and 4 physical cores
Frequency=2727540 Hz, Resolution=366.6307 ns, Timer=TSC
.NET Core SDK=2.1.402
  [Host]     : .NET Core 2.1.4 (CoreCLR 4.6.26814.03, CoreFX 4.6.26814.02), 64bit RyuJIT
  DefaultJob : .NET Core 2.1.4 (CoreCLR 4.6.26814.03, CoreFX 4.6.26814.02), 64bit RyuJIT


```
|          Method | Items |       Mean |     Error |    StdDev |   Gen 0 |  Gen 1 | Allocated |
|---------------- |------ |-----------:|----------:|----------:|--------:|-------:|----------:|
|           **Queue** |  **1000** |   **7.867 us** | **0.0359 us** | **0.0300 us** |  **1.9989** |      **-** |   **8.24 KB** |
|       SyncQueue |  1000 |  22.655 us | 0.7471 us | 0.6988 us |  1.9836 |      - |   8.24 KB |
| ConcurrentQueue |  1000 |  21.463 us | 0.4615 us | 0.4938 us |  4.4861 |      - |  18.44 KB |
|           **Queue** |  **5000** |  **43.167 us** | **0.8411 us** | **1.5591 us** | **15.5640** |      **-** |  **64.31 KB** |
|       SyncQueue |  5000 | 117.803 us | 2.3455 us | 3.5818 us | 15.5029 |      - |  64.31 KB |
| ConcurrentQueue |  5000 | 100.014 us | 1.9746 us | 3.0743 us | 16.3574 |      - |  67.31 KB |
|           **Queue** | **10000** |  **84.630 us** | **1.6893 us** | **3.5262 us** | **31.1279** |      **-** | **128.34 KB** |
|       SyncQueue | 10000 | 230.723 us | 4.5633 us | 5.4322 us | 31.0059 |      - | 128.34 KB |
| ConcurrentQueue | 10000 | 192.521 us | 1.0902 us | 0.9103 us | 31.9824 | 0.4883 | 131.75 KB |

[QueueBenchmark.zip](https://github.com/dotnet/coreclr/files/2410332/QueueBenchmark.zip)

**Comment by DrDao** [comment]
The issues has been transferred to Corefx.

https://github.com/dotnet/corefx/issues
