### ISSUE TITLE
New implementation for ICLRRuntimeHost::ExecuteInDefaultAppDomain  for .NetCore 3.0

### ISSUE THREAD

**Issue by chabiss** [dotnet/coreclr#20131]
XAML Visual Diagnostics and Edit-N-Continue need a mechanism for bootstrapping Microsoft.VisualStudio.DesignTools.WpfTap.dll into a running application for Visual Diagnostics to work

Here is how I think the injection may work in .NET Core 3.0:

1.	Find coreclr.dll instance that you like. It can be as simple as calling GetModuleHandle(“coreclr.dll”). Having multiple coreclr instances in the one process is not really a scenario today, and designing this for it would make us rathole and never get done. If multiple coreclr instances in a single process become a mainstream scenario, this code will need to change.
2.	Call coreclr!GetCLRRuntimeHost (existing API in coreclr.dll) to get ICLRRuntimeHost interface
3.	Call ICLRRuntimeHost::ExecuteInDefaultAppDomain like you are doing today. This method exists in CoreCLR, but it returns E_NOTIMPL. This would be work item for CoreCLR to get implementation of this method filled in.

**Comment by sdmaclea** [comment]
@jkotas @vitek-karas I started looking at this.  When looking at implementing 

```
HRESULT ICLRRuntimeHost::ExecuteInDefaultAppDomain (  
    [in] LPCWSTR pwzAssemblyPath,  
    [in] LPCWSTR pwzTypeName,   
    [in] LPCWSTR pwzMethodName,  
    [in] LPCWSTR pwzArgument,  
    [out] DWORD *pReturnValue  
);  
```

I need to get the `MethodDesc` for the `<Assembly>.<pwzTypeName>.<pwzMethodName>`.  I started wading through the vm code, but it is not immediately obvious.  I will continue to look at the code, but hints would be appreciated.

I will also need to check the Method signature.  Some of the checking done on the assembly entry point during app startup will provide useful clues.  Are the other examples?

I assume the call is synchronous.  It will execute in its own thread rather than creating a thread or using a worker thread.  It will `SetupThreadNoThrow()` if needed so the GC is aware of it.  Does it need to be torn down on return?  If so how?  Does it need to wait for the threads it spawns or anything like that?

I need to write a suitable unit test.  If someone can suggest a good baseline test that will save me some time.

Should we consider adding an extra argument to get an error string?

**Comment by jkotas** [comment]
Take a look what the original implementation for `!FEATURE_CORECLR` was: https://github.com/dotnet/coreclr/blob/cb3773542726fda1267e81596bd37654f418cff4/src/vm/corhost.cpp . It should be pretty close to what it needs to do - I am not sure why was it ifdefed out in the first place.

**Comment by sdmaclea** [comment]
@AaronRobinsonMSFT FYI
