### ISSUE TITLE
Formalize the IStateMachineBoxAwareAwaiter pattern so that custom IValueTaskSource implementations can be allocation free

### ISSUE THREAD

**Issue by davidfowl** [dotnet/coreclr#20200]
This change https://github.com/dotnet/coreclr/commit/03ead514a3aa414b26246a4160d0593811fd1044 made it so that Task can resume state machine execution in an allocation free way. If we combine this change with https://github.com/dotnet/corefx/issues/32485 then we can expose a public version of IStateMachineBoxAwareAwaiter so that IValueTaskSource implementations can avoid the QUWI allocation.

cc @stephentoub

**Comment by stephentoub** [comment]
> so that IValueTaskSource implementations can avoid the QUWI allocation

I'm reading between the lines, but presumably you mean if the IValueTaskSource wants to force the continuation to be asynchronous (since IValueTaskSource can already be allocation-free for the most common case of synchronous completion).

What would `IStateMachineBoxAwareAwaiter` look like?  How would it integrate with the rest of the system?  How would the IValueTaskSource implementation get ahold of the relevant instance?

I'm going to assign this issue to you, since there's design work here and it's your idea :)

**Comment by stephentoub** [comment]
Thanks.

My primary concerns here are that it a) exposes the inner workings of how async state machines are implemented, and b) exposes a non-trivial amount of complexity.  (a) is the bigger worry, as it can limit our ability to innovate in how this is implemented in the future; after all, up until .NET Core 2.1, none of that IAsyncStateMachineBox stuff even existed, with it overhauling how it was all implemented internally... if more details of the previous implementation had been exposed, we would not have been able to do that and achieve the associated gains.

I would rather focus on, for example, making it so that in general thread pool work items can be done allocation free, e.g. by changing the ThreadPool's concurrent queue to contain structs rather than classes directly, such as:
```C#
private struct ThreadPoolQueueEntry
{
    private Action<object> _action; // null if _state is IThreadPoolWorkItem
    private object _state;
}
```
Then the invocation logic would be something like:
```C#
ThreadPoolQueueEntry entry = ...;
if (entry._action == null) ((IThreadPoolWorkItem)_state).Invoke();
else if (context == null) _action(_state);
```
Then the existing `UnsafeQueueUserWorkItem` would be allocation-free (`QueueUserWorkItem` would also be allocation-free if flow was suppressed, though that's not common), and `UnsafeQueueCustomWorkItem` would continue to be allocation-free beyond the IThreadPoolWorkItem instance that the call site allocates but can reuse, etc. The generic `{Unsafe}QueueUserWorkItem` would still need to allocate, though we could type-test the T and avoid the allocation for the `Unsafe` flavor if `T` == `object`.

That should be fairly straightforward to do for the global queue, though measurement would be needed to determine whether it's a net win.  It might be harder for the local queues; I don't have the implementation in my head enough to know what challenges we might face around synchronization.

Or something along those lines.  I don't want to significantly increase the complexity of the interfaces exposed in this area and lock us in to a particular implementation approach for all time simply to avoid an allocation that's arguably an implementation detail of ThreadPool.

**Comment by davidfowl** [comment]
> I would rather focus on, for example, making it so that in general thread pool work items can be done allocation free, e.g. by changing the ThreadPool's concurrent queue to contain structs rather than classes directly, such as:

That would be great in general and could improve more than just the await scenario. On that same thought process, can't we do something pretty evilish here? We could say that if the state object passed into `QueueUserWorkItem` or `UnsafeQueueUserWorkItem` is an  `IThreadPoolWorkItem` then delegate to QueueCustomWorkItem instead? That would avoid exposing any of the interfaces you're worried about (though I still think it might be worth it to at least understand what a design might look like).

**Comment by stephentoub** [comment]
> We could say that if the state object passed into QueueUserWorkItem or UnsafeQueueUserWorkItem is an IThreadPoolWorkItem then delegate to QueueCustomWorkItem instead?

I'm not following.  Can you clarify?  If you have an IThreadPoolWorkItem, why would you pass it as the state object rather than just calling UnsafeQueueCustomWorkItem?  And in doing so ignore the delegate that's provided?

**Comment by stephentoub** [comment]
> It's the backdoor way of making existing calls allocation free for free.

I think I'm missing something.  Are you talking about a situation where we publicly expose `IThreadPoolWorkItem` but not `UnsafeQueueCustomWorkItem(IThreadPoolWorkItem)`?

**Comment by kouvel** [comment]
cc @tarekgh

**Comment by stephentoub** [comment]
Ah, I understand, thanks for clarifying.  You're talking about using a sentinel action delegate, and then when it comes time to doing the invocation, comparing that sentinel and ignoring it and just invoking the work item state object.  As an internal implementation detail (ThreadPoolWorkItemDefaultAction would be internal to corelib), we could certainly look at doing that.  It would probably come down to a perf measurement and judgement call as to whether the cost to _all_ work items going through the thread pool of the additional comparison would be worth avoiding an allocation for the subset from this and similar code paths.  That said, presumably the code path you highlighted could go through ThreadPool.UnsafeQueueUserWorkItem, not QueueUserWorkItem (since this is for the AwaitUnsafeOnCompleted case that's generally used by async methods), if the IValueTaskSource wanted to force asynchronous completion, in which case it would be covered by the allocation-free code path approach I previously mentioned.

**Comment by davidfowl** [comment]
@stephentoub right. Agreed on the perf hit (I'd be surprised if it mattered but we should measure)

**Comment by benaadams** [comment]
Could `IAsyncStateMachine` inherit from `IThreadPoolWorkItem` or would that be problematic?

**Comment by benaadams** [comment]
Oh nvm, method is a different one :)

**Comment by benaadams** [comment]
Isn't there a problem with the struct route because one is a `WaitCallback` and other `Action<object>`; or would you unsafe cast `WaitCallback` to `Action<object>` because they are sort of the same?

**Comment by davidfowl** [comment]
@stephentoub Re-thinking a bit about your concerns, I'm thinking we could just elevate the IAsyncStateMachine to be more first class across the board. That's an already public interface and it shouldn't tie our hands by exposing it (hopefully 😄).

 We could expose the `IAsyncStateMachine` interface directly to awaitable objects via another interface.

```C#
public interface IAsyncStateMachineAwaiter
{
    void AwaitUnsafeOnCompleted(IAsyncStateMachine stateMachine);
}
```

Instead of queuing continuations, you can just hold onto the state machine and call `MoveNext()`.

On the consuming side, we can check if `IAsyncStateMachine` implements `IThreadPoolWorkItem` and then call QueueCustomWorkItem to schedule the callback.

We could also consider teaching the thread pool about the IAsyncStateMachine directly and allow it to queue directly but that would add more public API.

Thoughts?

**Comment by benaadams** [comment]
Doing a horrible hack just to see https://github.com/dotnet/coreclr/compare/master...benaadams:threadpool-hack?expand=1 with for the global queue
```csharp
readonly struct ThreadPoolQueueEntry
{
    public readonly Action<object, object> _converter;
    public readonly object _action; // null if _state is IThreadPoolWorkItem
    public readonly object _state;
    public readonly ExecutionContext _context;
}
```
and a queue local `ReusableQueueUserWorkItemCallback` that gets initalized when an item is removed from the global queue; so it can follow the local queues logic

Does definitely reduce allocations 😄 

![image](https://user-images.githubusercontent.com/1142958/48297888-ad6d6100-e4aa-11e8-8912-590e6233c3ba.png)

**Comment by benaadams** [comment]
Run times were similar(ish)
![image](https://user-images.githubusercontent.com/1142958/48298300-2ec8f180-e4b3-11e8-8dea-4f2f0801b342.png)
Though the non-allocating version hit a LOH GC as its structs are so large (so therefore is the array); and it had more "CLR Worker" threads not sure what they were doing.

**Comment by davidfowl** [comment]
❤️
