### ISSUE TITLE
2 tests in x86_checked_windows_nt_gcstress0xc_zapdisable_heapverify1 failed with Assert failure: candidate < tree

### ISSUE THREAD

**Issue by jiangzeng** [dotnet/coreclr#20533]
**Job:**
jitstress » x86_checked_windows_nt_gcstress0xc_zapdisable_heapverify1
[https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86/job/jitstress/job/x86_checked_windows_nt_gcstress0xc_zapdisable_heapverify1/104](https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86/job/jitstress/job/x86_checked_windows_nt_gcstress0xc_zapdisable_heapverify1/104)

**Affected tests:**
```
JIT_Regression._JitBlue_GitHub_18362_GitHub_18362_GitHub_18362_._JitBlue_GitHub_18362_GitHub_18362_GitHub_18362_cmd
JIT_Regression._JitBlue_GitHub_18884_GitHub_18884_GitHub_18884_._JitBlue_GitHub_18884_GitHub_18884_GitHub_18884_cmd
```

**Log:**
```
        Assert failure(PID 1892 [0x00000764], Thread: 5764 [0x1684]): candidate < tree
        CORECLR! WKS::gc_heap::relocate_address + 0x81 (0x71bc0c71)
        CORECLR! WKS::GCHeap::Relocate + 0x45 (0x71ba9e45)
        CORECLR! PromoteCarefully + 0x83 (0x71908823)
        CORECLR! GcEnumObject + 0x4B (0x71aebe1b)
        CORECLR! EECodeManager::EnumGcRefs + 0xE72 (0x71935512)
        CORECLR! GcStackCrawlCallBack + 0x169 (0x71aec089)
        CORECLR! Thread::MakeStackwalkerCallback + 0x3A (0x71797dd8)
        CORECLR! Thread::StackWalkFramesEx + 0x16E (0x71799409)
        CORECLR! Thread::StackWalkFrames + 0x159 (0x7179921b)
        CORECLR! ScanStackRoots + 0x18C (0x71bf3852)
            File: d:\j\workspace\x86_checked_w---41e3110e\src\gc\gc.cpp Line: 23367
            Image: D:\j\workspace\x86_checked_w---41e3110e\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\CoreRun.exe
```

**Comment by Maoni0** [comment]
can you please give a bit more info? I don't see any changes we made recently that would cause any internals of the GC to change. when did you start to observe this? or is this a new test? it would really help to know if this starts to happen after some certain build. also CC-ing @sywhang.

**Comment by BruceForstall** [comment]
The tests were added in June and July of this year. We probably haven't paid much attention to the GC stress runs in the CI runs, and the CI unfortunately doesn't keep much history, so it's hard to see if these fail regularly this way or not. It appears this job as a whole hasn't passed since March (https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86/job/jitstress/job/x86_checked_windows_nt_gcstress0xc_zapdisable_heapverify1/).

You can see the set of changes made between the last run and this one. There are 45: https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86/job/jitstress/job/x86_checked_windows_nt_gcstress0xc_zapdisable_heapverify1/104/

(I think this job only runs weekly)

**Comment by Maoni0** [comment]
thank Bruce. we'll try to see if we can get a local repro of these tests.

**Comment by Maoni0** [comment]
so I've been running these 2 tests in the following fashion for the past hour with no repro - 
```
corerun.exe GitHub_18362.exe
corerun.exe GitHub_18884.exe
```

with these env vars set:
```
D:\coreclr2\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root>set complus
complus_gcstress=c
complus_heapverify=1
complus_zapdisable=1
```
and with an x86 checked build (although this is a build with latest commit
```
commit 209bca9c6caf59bc60bffd16a8da5c67c6d6138b (HEAD -> temp_build_tool_revert)
Author: dotnet-maestro-bot <dotnet-maestro-bot@microsoft.com>
Date:   Wed Oct 3 19:38:12 2018 -0700
```
because after that I can no longer built due to #20320 that's still not fixed. 

I wasn't sure what you meant by "You can see the set of changes made between the last run and this one.". did you mean "last run" as in "last run when these tests passed"? if so then there's no changes in GC that could affect this at all - the only GC change is this:
```
43 Local GC - Fix GCToOSInterface::GetPhysicalMemoryLimit (#20495) 
```

which does not even affect the embedded GC scenario (which these tests are run with).

my suggestion would be we need to get a local repro otherwise there's really no efficient way to make progress on this.

**Comment by BruceForstall** [comment]
> I wasn't sure what you meant by "You can see the set of changes made between the last run and this one.". did you mean "last run" as in "last run when these tests passed"?

No, I believe the list of changes displayed in the link (https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86/job/jitstress/job/x86_checked_windows_nt_gcstress0xc_zapdisable_heapverify1/104/) is between this run of the job, and the previous run of the job (which also failed, but with a different set of issues).

The tests have failed in the same way in the two more recent job runs:
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86/job/jitstress/job/x86_checked_windows_nt_gcstress0xc_zapdisable_heapverify1/105
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86/job/jitstress/job/x86_checked_windows_nt_gcstress0xc_zapdisable_heapverify1/106

(note this failure mode and these failing tests aren't the only failures in the runs)

**Comment by Maoni0** [comment]
I see. well, I still can't get a repro. it's difficult to make progress without a repro.

**Comment by BruceForstall** [comment]
@Maoni0 This script repros reliably for me:
```
setlocal

set COMPlus_TieredCompilation=0
set COMPlus_GCStress=c
set COMPlus_ZapDisable=1
set COMPlus_HeapVerify=1

call F:\gh\coreclr12\bin\tests\Windows_NT.x86.Checked\JIT\Regression\JitBlue\GitHub_18362\GitHub_18362\GitHub_18362.cmd -coreroot F:\gh\coreclr12\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root
echo %errorlevel%
```

Note that if I just use "corerun GitHub_18362.exe" directly, no using the wrapper script, it doesn't repro. I didn't investigate farther.

**Comment by sywhang** [comment]
@Maoni0  I have a repro for this on my machine. I can take a look and see if this is a GC issue.

**Comment by Maoni0** [comment]
@sywhang great! let me know if you need help.

**Comment by BruceForstall** [comment]
That indicates that minopts (unoptimized) generated code doesn't exhibit the issue. So yes, it seems there is probably some characteristic of the generated code causing this.

**Comment by AndyAyersMS** [comment]
These have both passed in the last 4 CI runs (we've purged any history older than that).

Let me try and repro, and if so, I'll investigate.

**Comment by AndyAyersMS** [comment]
Can't get 18884 to fail even with sideloaded CPU stress (2000x runs). 18362 still going, but no repro there yet either.

**Comment by AndyAyersMS** [comment]
18362 no repro after 1000x runs with sideloaded CPU stress. So will close this as no repro.
