### ISSUE TITLE
Address Thread Scalability in EventPipe Traces

### ISSUE THREAD

**Issue by vancem** [dotnet/coreclr#20555]
Currently the way EventPipe's StackSampler works is that every millisecond it stops each thread and takes a stack trace.  

This works well when there are a modest number of threads (say < 100), but comes excessive in both collection overhead and file size overhead when the number of threads is large (e.g. > 500).

I don't have the example handy anymore but it is not hard to replicate (simply have a app that has say 500 sleeping threads among other activities).     It is a real-world problem because it is not uncommon for users to have at least 100s of threads in a process.   

The rough solution is to avoid crawling threads that are blocked since the last sample, at least most of the time.   This could be done by modifying the TransitionFrame that has a bit that starts out 0 when it is initialized, that we can later set.   Thus we set it when we track the thread, and if it remains set we know it was not popped .   This allows us to skip threads that are no 'moving' quickly (and not log them).    This cuts both cost and (more importantly) file size.  We now only log threads that are not blocked.  

@noahfalk  @brianrob @jorive

**Comment by noahfalk** [comment]
Pr #24853 attempts to mitigate this issue by making each event smaller rather than trying to do anything fancy and eliminate events. By using stack interning + header compression in the new NetTrace format, the size of a stack sample event should be around ~10 bytes (when the stack has been previously observed) vs  75-875 bytes per stack sample emitted in the NetPerf format. This means at modest numbers of threads (<50) at 1000Hz we produce 500KB/sec of sampling data. Could be better, but this feels good enough that we can stop here for now and use feedback to determine if another iteration of performance improvements is necessary.
