### ISSUE TITLE
Optimize the size of the EventPipe buffer

### ISSUE THREAD

**Issue by vancem** [dotnet/coreclr#20751]
Currently we don't try to do any size optimization on the events put in the EventPipe.   In particular we allocate 16 byte entries for related activity IDs (which are almost always 0), and (more importantly) we store stacks as list of 64 byte quantities.   

Today we use a fair bit of memory (1GB), for this and we could cut this substantially (e.g. by half or more), if we did even modest optimizations (Delta compress stacks, omit unused related activity IDs etc.    This would both save memory and be more cache friendly.   

For stacks, ideally we could 'intern' them (giving stacks IDs and reusing the 'tails' of the stacks),  This will have a DRAMATIC effect on size, and it is what ETW does (so we kind of know the tradeoff is worth it).  

@noahfalk

**Comment by noahfalk** [comment]
cc @jorive

**Comment by tommcdon** [comment]
@jorive is this related to @sywhang work to reduce the buffer size for perf counters?

**Comment by sywhang** [comment]
I believe this is unrelated. My work flushes the buffer of events more often. This issue is to optimize the event size itself.

**Comment by noahfalk** [comment]
I have slightly retargeted this issue. As written it refers to the size of data when buffered in memory, but I assume the primary concern was the size of the file format on disk or serialized to an IPC/network stream.
PR #24853 in coreclr and https://github.com/microsoft/perfview/pull/948 in Perfview added the new NetTrace format which does several things to improve file sizes:
a) Stack interning - When multiple events refer to the same stack each event only encodes a 4 byte stackId. The contents of all the stack frames is written once and shared.
b) Header compression - Using some basic variable length encoding and delta encoding we can substantially compress headers. In NetPerf a header was 56 bytes, in NetTrace uncompressed it would be 76 bytes, and when adjacent events have highly similar headers we can compress down to ~3 bytes.
c) Events are ordered so that long runs of events on the same thread are far more likely which substantially increases the odds the deltas observed in part (b) will be small.

Although scenario dependent, in a few scenarios I tried even modest event payloads (~50 bytes per event) occupied 80+% of the total trace size on disk. Even though every event in the trace has a header and most events had stacks, the compression reduced the costs of all that data to < 20% of the file size.

In the future if we do decide that we need to reduce the in-memory buffer size independent of the final size on disk, we could apply some of these file size optimizations earlier in the pipeline. Its not entirely trivial though (or I would have done it already) because header compression depends on the order of the events and stack interning depends on the cache management for interning dictionary. Neither of these is going to be identical working with per-thread buffers as it is when working with the final file emitter. There is also a really easy optimization that still hasn't been done - every event reserved a fixed size 100 pointer buffer to store its stack regardless of how big the stack actually is. Encoding the stack as a variable size array would probably net a 2-4x win on its own.

**Comment by mjsabby** [comment]
These are substantial improvements. I had a question about stack interning. Is the stack interning per session?

**Comment by noahfalk** [comment]
Separate sessions get separate interning tables. You would not be able to reliably resolve an ID from session 1's stream against the interning table serialized in session 2's stream. However the intern table actually has a lifetime that could be much smaller than a session. There are sequence points emitted into the stream at various intervals and crossing a sequence point invalidates all stack ids. This ensures that the reader decoding the event stream can maintain a bounded cache even if you decide it would be great to log 1 trillion events and give each of them a unique stack. It also means that if you want to isolate some EventBlocks from the file, you could grab every StackBlock that is in between the preceding sequence point and the last EventBlock and you will be certain to have the stack interning data you need to resolve all the stacks for those events.

**Comment by noahfalk** [comment]
Btw, if its useful here is the documentation describing the format: https://github.com/microsoft/perfview/pull/948/files#diff-24c420b1dee38d3a5073679d5cb191d2
