### ISSUE TITLE
NO_WAY: JIT must expand the intrinsic!

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#20757]
x86 Checked PMI run over System.Private.CoreLib.dll:
```
Assert failure(PID 166132 [0x000288f4], Thread: 162592 [0x27b20]): Assertion failed 'JIT must expand the intrinsic!' in 'System.Runtime.Intrinsics.X86.Bmi1:BitFieldExtract(int,ubyte,ubyte):int' (IL size 9)

    File: f:\gh\coreclr12\src\jit\importer.cpp Line: 3939
    Image: F:\gh\coreclr12\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\CoreRun.exe
```

Repro:
```
set COMPlus_JitRequired=1 // This turns NO_WAY into assert
// build https://github.com/dotnet/jitutils
// build x86 checked coreclr
F:\gh\coreclr12\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\CoreRun.exe c:\gh\jitutils\bin\pmi.dll PREPALL F:\gh\coreclr12\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\System.Private.CoreLib.dll
// (alter paths as appropriate)
```

Also happens for x64 checked.

Also happens for:
```
System.Runtime.Intrinsics.X86.Bmi1:BitFieldExtract(int,ushort):int
System.Runtime.Intrinsics.X86.Bmi2:ZeroHighBits(int,int):int
System.Runtime.Intrinsics.X86.Bmi2:MultiplyNoFlags(int,int,long):int
System.Runtime.Intrinsics.X86.Sse42:CompareExplicitLengthUnitMask(struct,ubyte,struct,ubyte,ubyte):struct
System.Runtime.Intrinsics.X86.Sse42:CompareImplicitLength(struct,struct,ubyte,ubyte):bool
```

**Comment by BruceForstall** [comment]
I noticed this after https://github.com/dotnet/jitutils/pull/180. We might need to back out that change unless this can be fixed ASAP.

**Comment by BruceForstall** [comment]
@tannergooding @fiigii @CarolEidt 
cc @dotnet/jit-contrib

**Comment by fiigii** [comment]
```
System.Runtime.Intrinsics.X86.Bmi1:BitFieldExtract(int,ushort):int
System.Runtime.Intrinsics.X86.Bmi2:ZeroHighBits(int,int):int
System.Runtime.Intrinsics.X86.Bmi2:MultiplyNoFlags(int,int,long):int
System.Runtime.Intrinsics.X86.Sse42:CompareExplicitLengthUnitMask(struct,ubyte,struct,ubyte,ubyte):struct
System.Runtime.Intrinsics.X86.Sse42:CompareImplicitLength(struct,struct,ubyte,ubyte):bool
```
These 5 intrinsics are not implemented in the JIT yet. Waiting for the API change review.

**Comment by AndyAyersMS** [comment]
Can we just map these to `int3` or similar in the time being?

**Comment by BruceForstall** [comment]
So do we _expect_ to see NO_WAY? We'd like to maintain an invariant that NO_WAY means there is a bug in the JIT.

**Comment by fiigii** [comment]
> So do we expect to see NO_WAY?

Yes, but this PMI failure is temporary and it won't happen with normal test runs.

**Comment by fiigii** [comment]
If you guys have decided to run PMI tests in the CI. I suggest having a solution to ignore this kind of failures. In the future, we may have more intrinsic APIs (e.g., AVX-512) that will need a long time to enable in the runtime.

**Comment by BruceForstall** [comment]
As I understand it, this happens because the Frameworks API appears first and requires an intrinsic implementation. But the JIT side hasn't implemented it yet. However, it appears that if the JIT falls back to MinOpts, it works. Is that correct? I also presume these intrinsics can be identified in the JIT.

If so, I would suggest that there be a list of "defined but not yet implemented" intrinsics in the JIT that force MinOpts early, without going through the NO_WAY path.

Would that work?

**Comment by CarolEidt** [comment]
It would surprise me if the "defined but not yet implemented" intrinsics would succeed in MinOpts if they `NO_WAY` otherwise, as these are not supposed to behave differently for MinOpts. I think that the right answer is for these to be simply handled as a special case in the importer, that would be removed once they are implemented.

> If you guys have decided to run PMI tests in the CI. I suggest having a solution to ignore this kind of failures. In the future, we may have more intrinsic APIs (e.g., AVX-512) that will need a long time to be enabled in the runtime.

While it is inconvenient to time these, we should not be adding APIs that will require a long time to enable. And we should most definitely have a way to handle these effectively. This is **independent** of whether we decide to run PMI tests in the CI. It should not be the case that invoking an unsupported API causes the JIT to fail.

**Comment by AndyAyersMS** [comment]
The reasons things "work" eventually with minopts fallbacks is that with minopts the root method treats the not implemented intrisnsics as calls and doesn't try to inline or expand them. And jitting the intrinsic method causes a catchable `InvalidProgramException` so it doesn't blow up PMI.

I think we discussed having unsupported intrinsics expand into throws when we see them in non-minopts but turned out to be tricky as some of them return values. But maybe it's worth revisiting?

Alternatively we could just treat them as calls until they're implemented, which should be too hard. Basically just pretend that they're not actually intrinsics if they're not the root method.

Or maybe even just BADCODE if we hit the place where we currently NOWAY, as BADCODE is not a fatal thing and does not lead to fallback...?

**Comment by fiigii** [comment]
Hardware intrinsic codegen has no difference between MinOpt and the normal compilation pipeline. so this is not a minpot falls back issue. 

> I think we discussed having unsupported intrinsics expand into throws when we see them in non-minopts but turned out to be tricky as some of them return values. But maybe it's worth revisiting?

Currently, implemented intrinsics could throw PNES, and I think this is a good idea to throw NotImplemented exception from the temporarily unimplemented intrinsics.

> While it is inconvenient to time these, we should not be adding APIs that will require a long time to enable. 

This is also a good option for the future work.

**Comment by fiigii** [comment]
Next week, we will have the final API review meeting for hardware intrinsic. After that, I believe all the remaining APIs will be enabled soon (maybe in one month). 
So, do we have to do something to solve this issue? Or just wait one month?

**Comment by tannergooding** [comment]
I think we could fairly easily update this code: https://github.com/dotnet/coreclr/blob/master/src/jit/importer.cpp#L3935

to do:
```csharp
if (mustExpan && (retNode == nullptr))
{
    return impNotImplementedIntrinsic(CORINFO_HELP_THROW_NOT_IMPLEMENTED, method, sig, mustExpand);
}
```

which would differentiate it from the `PNSE` case, where the intrinsic is implemented, but isn't supported on the platform:
https://github.com/dotnet/coreclr/blob/master/src/jit/hwintrinsicxarch.cpp#L731

**Comment by CarolEidt** [comment]
I think that throwing `NotImplementedException` would be a good interim implementation approach. And relatively easy to search for when we are getting ready for release (to ensure that we don't have any remaining).

**Comment by sandreenko** [comment]
I hit this issue today with another set of x64 AVX intrinsics. (x64 checked running arm64 alrjit pmi diffs on System.Private.CoreLib).

**Comment by fiigii** [comment]
Hmm, weird, I do not think JIT has any issue with `Aes.IsSupported`
