### ISSUE TITLE
[release/2.2] BenchStone - IniArray / Test

### ISSUE THREAD

**Issue by brianrob** [dotnet/coreclr#20811]
While doing a comparison of release/2.2 to release/2.1 I found a regression in the BenchStone IniArray benchmark of about 38% on Windows x64.

It appears that the bulk of the difference is spent in the benchmark function itself as exclusive time as opposed to there being new function calls contributing to the regression.

I can share a repro and traces upon request.

**Comment by AndyAyersMS** [comment]
I'll investigate.

**Comment by AndyAyersMS** [comment]
The jitted code for this test is identical in 2.1 and 2.2.

IniArray is very sensitive to loop alignment, which we don't control. Because of this, performance can change over time, fluctuating between stable level. Here we see two such levels, around 62ms and 100ms.  And that's why it looks like there was a 38% drop: 2.2 is currently getting the slow result, while 2.1 is currently getting the fast result.

Recent history shows this pretty clearly:

* Release 2.1
![image](https://user-images.githubusercontent.com/10121823/48034342-e5278200-e113-11e8-98ad-f6ed21440ea4.png)

* Release 2.2
![image](https://user-images.githubusercontent.com/10121823/48034372-02f4e700-e114-11e8-92e3-1b04a755056d.png)

* Master
![image](https://user-images.githubusercontent.com/10121823/48034480-6aab3200-e114-11e8-89a5-72e46d65fe53.png)

Support for loop alignment (and the co-requisite method alignment) are on the jit backlog, see #11607 and #16873 respectively.

So am going to close this as a known issue with perf stability in this test.
