### ISSUE TITLE
Internal Constructor for MemberInfo

### ISSUE THREAD

**Issue by schotime** [dotnet/coreclr#2086]
Just wondering why this is so?
It means I can't create a DynamicMember (like PropertyInfo but not known at compile time) that inherits from MemberInfo. I can currently do this.

**Comment by jkotas** [comment]
The reflection types like MemberInfo or TypeInfo are sealed in .NET Core contracts today. It is a known deficiency in the .NET Core reflection contracts. 

@weshaggard Do we have it tracked somewhere?

**Comment by weshaggard** [comment]
This is currently by design because there isn't a great way to actually inherit from our existing reflection surface area and successfully work on the different underlying implementations. This is something that @nguerrera looked at in the past and I don't believe there was confidence in getting to work consistently, however we should have another look after we include more of the reflection APIs (cc @pallavit).

**Comment by pallavit** [comment]
All the reflection classes intentionally block extensibility for now and is something that will be revisited in future.

**Comment by danmosemsft** [comment]
MemberInfo's constructor is now protected. I guess that resolves this.
