### ISSUE TITLE
Enable PDBTypeMatch for x64/Windows

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#2089]

**Comment by tzwlai** [comment]
@gkhanna79, any particular reason why you want to enable this tool?  It hasn't been that useful to us in the past.

**Comment by gkhanna79** [comment]
@rahku can comment as he ended up needing it.

**Comment by rahku** [comment]
The tool helps catch bugs where people do not put #ifdef DACCESS_COMPILE at right places. Because of which datastructures in dac and coreclr can go out of sync and would affect debugging. We have this tool running in internal builds but not in open builds. Sometime back there was a PR that got merged but broke the internal builds.

**Comment by tzwlai** [comment]
Thanks @rahku.  Is this something you are planning to address by RTM?

**Comment by rahku** [comment]
This is not a must for RTM. I will let you know soon if I will be able to address it by RTM.
