### ISSUE TITLE
AsyncValueTaskMethodBuilder should create IValueTaskSource based ValueTasks

### ISSUE THREAD

**Issue by benaadams** [dotnet/coreclr#20905]
At the moment it goes via `AsyncMethodBuilder` so creates Task backed ValueTasks when it suspends; however it could create `IValueTaskSource` backed ValueTasks?

e.g.
```csharp
public partial struct AsyncValueTaskMethodBuilder<TResult>
{
    private class AsyncStateMachineBox<TStateMachine> : 
        IValueTaskSource<TResult>, IThreadPoolWorkItem, IAsyncStateMachineBox
        where TStateMachine : IAsyncStateMachine
    {
        // ...
    }
}
```
rather than
```csharp
public partial struct AsyncTaskMethodBuilder<TResult>
{
    private class AsyncStateMachineBox<TStateMachine> :
        Task<TResult>, IAsyncStateMachineBox
        where TStateMachine : IAsyncStateMachine
    {
        // ...
    }
}
```
This would save on the additional allocations that come from inheriting from `Task`? 

(And could perhaps reuse the boxes after completion? For example awaits in a loop)

/cc @stephentoub @davidfowl

**Comment by davidfowl** [comment]
This would apply to the AsyncValueTaskMethodBuilder right?

**Comment by benaadams** [comment]
Yeah; edited code to add containing struct

**Comment by stephentoub** [comment]
> This would save on the additional allocations that come from inheriting from Task?

What additional allocations?

> And could perhaps reuse the boxes after completion?

You mean have the runtime maintain a global pool for each method? That'll introduce potentially huge amounts of contention, plus how much would you actually pool? (Think about how many times certain methods are likely to be running concurrently.)

To do this well, I think you'd need something like: https://github.com/dotnet/csharplang/issues/1407

**Comment by stephentoub** [comment]
The task is the async box. There's just the one allocation.

**Comment by davidfowl** [comment]
The question would be how big is Task compared to this object.

**Comment by stephentoub** [comment]
> The question would be how big is Task compared to this object.

Sure, though that's different than number of allocations, that's the size of the single allocation.  And I think you'll find there's not much savings to be had, and potentially even make things worse, depending on usage.

Consider a common async method like:
```C#
static async Task CopyToAsync(Stream source, Stream dest, Memory<byte> buffer, CancellationToken token)
{
    await Task.Yield(); // just to help measure
    int bytesRead;
    while ((bytesRead = await source.ReadAsync(buffer, token).ConfigureAwait(false)) != 0)
        await dest.WriteAsync(buffer.Slice(0, bytesRead), token).ConfigureAwait(false);
}
```
With the latest compiler and master coreclr bits, release build, that clocks in at 184 bytes on 64-bit.  Even if you could get rid of Task's fields entirely (you can't), at best you'd shave off 48 bytes, which is just 25%.  And you need to be able to store the continuation delegate and the continuation state, which are 16 of those 48 bytes, so now you're down to 32 bytes (17%).  And you need to be able to store an Exception in case the method fails, which requires an object field, so now 24 bytes (13%).  And to help flag misuse due to incorrect reuse you should really store a short token (which could also double as an identifier for tracing), plus it helps to have a Boolean indicating completion as in https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/shared/System/Threading/Tasks/Sources/ManualResetValueTaskSourceCore.cs, so round that up to another word-size field and we're at 16 bytes saved out of 184 (8%).  Which logically makes sense, since basically what you're able to shave off of a Task used purely as a promise are its Delegate and TaskScheduler fields, which total 16 bytes. (Plus, we've toyed with the idea of pushing those two fields out to contingent properties, though that'll require some significant analysis to prove out the theory that the majority of tasks are now promises.)

So, maybe you could shave off 8% of the fields in this case.  And in doing so, you incur other costs.  Now awaits that would normally go through the ValueTask to direct calls to Task instead go through interface dispatch on IValueTaskSource.  Now anyone who calls AsTask() on one of these actually incurs another Task allocation, whereas AsTask() just returns the existing Task object when the ValueTask is backed by a Task, so in any situations where you're using WhenAll, WhenAny, or other such combinators, where you want to block, where you want to hook up multiple continuations, where you want to save it off in some cache, etc., you're actually going to make this more expensive in both allocation and allocated size. Now you lose built-in support that comes with Task, like EventSource/ETW events for every await on them that yields (which you could of course add back, at the expense of even more code duplication), and the diagnostics around incomplete state machines, and the VS debugger's ability to find Tasks (which all of these "async ValueTask" methods are).  And then there's the risk of compat, where even though we say "this is how ValueTask should and should not be used", you know some developers are already going to be depending on things like being able to await the same ValueTask multiple times, in which case since we'd be silently changing the implementation under the hood, we'd probably want to support all of that, which brings even more cost/complexity. And so on.

I considered all of this when adding the `AsyncValueTaskMethodBuilder` and `IValueTaskSource`, and didn't see it being anywhere near worthwhile.  But if you disagree, obviously feel free to prove me wrong :)

**Comment by benaadams** [comment]
> To do this well, I think you'd need something like: dotnet/csharplang#1407

Yes! 😄

Alternative would be to stash it in its parent's `ExecutionContext`; but [AsyncLocal's are evil](https://github.com/dotnet/coreclr/pull/13105#issuecomment-318785942) and I'm all about the Default context...

**Comment by stephentoub** [comment]
Or an async method that calls itself.

**Comment by benaadams** [comment]
> Or an async method that calls itself.

Ah, as mutation to the EC wouldn't propagate. Would need to be a secondary value of an AsyncLocal
```csharp
class StateMachineHolder
{
    public IValueTaskSource src;
}
```
`AsyncLocal<StateMachineHolder> _src = new StateMachineHolder { src = ... }`

But at which point the cost for any non-repeated `await`s is much higher 😢

**Comment by stephentoub** [comment]
Right.

**Comment by stephentoub** [comment]
> The ideal is to pool in its parent statemachine (when its called multiple times)

Not necessarily state machine.  My example in that proposal was that something like Socket or WebSocket could just have a field on it that stored the instances to be reused, one for reading and one for writing.

**Comment by stephentoub** [comment]
> Issue with generalised pooling in AsyncValueTaskMethodBuilder

More than that, you can't really pool at that level, because lots of different async methods, each with their own unique state machine types, couldn't all share the same pool.  So you would need a per-method pool (unless you wanted to box the state machine, which defeats the purpose), and then you hit the issues called out in your various bullet points.

**Comment by benaadams** [comment]
> More than that, you can't really pool at that level, because lots of different async methods, each with their own unique state machine types, couldn't all share the same pool. 

Well, you could pool in the generic; then you'd have one per `TStateMachine`
```csharp
public partial struct AsyncValueTaskMethodBuilder<TResult>
{
    private class AsyncStateMachineBox<TStateMachine> : 
        IValueTaskSource, IThreadPoolWorkItem, IAsyncStateMachineBox
        where TStateMachine : IAsyncStateMachine
    {
        private static AsyncStateMachineBox<TStateMachine> _pooledBox = null; // or other type
        
        // ...
    }
}
```
But the side-effects wouldn't be good 😢

**Comment by benaadams** [comment]
@stephentoub btw the allocation list in  SocketServerDbg.txt here https://github.com/aspnet/AspNetCore/issues/3409#issuecomment-436689028 might be interesting; since it wasn't collecting garbage its an view on general allocations.

**Comment by stephentoub** [comment]
> Well, you could pool in the generic; then you'd have one per TStateMachine

Right, that's what I meant by "at that level" :)

> btw

Thanks.

**Comment by benaadams** [comment]
> > btw

> Thanks.

Ah, looks like its only listing referenced items; at a guess 31k websocket connections. Still interesting on allocations front.

**Comment by stephentoub** [comment]
@benaadams, do you see this issue as still tracking something, or can it be closed?

**Comment by benaadams** [comment]
No, the csharplang probably tracks it better
