### ISSUE TITLE
Provide non-floating tags for docker images

### ISSUE THREAD

**Issue by itrofimow** [dotnet/coreclr#20951]
Hey.

In order to profile some of our apps running inside docker-containers we use standalone container with a lot of stuff installed into it (which we just run via `docker run --pid=host` and investigate w/e `pid` we need), most notably lldb-3.9. 
However, lldb (or should i say libsosplugin) doesnt play nicely with dumps taken by official `createdump` tool, if there is any mismatch in dotnet/libsos version. 
And this is exactly the case we encountered - some of our app were built via floating runtime tags, and as time goes those exact versions became unavailable from docker-hub, so for now it's really hard for us to create a profiler with correct dotnet version.

Yes, we could try to play with `dotnet-symbol` tool, but this way seems really shaky and inconvenient, so what i am asking for - is it possible to create some static tags for upcoming and already existent versions of runtime/aspnetcore-runtime?

**Comment by jkotas** [comment]
cc @mikem8361

**Comment by mikem8361** [comment]
The problems you are having with loading a core dump in lldb sounds like the lldb requirement (not SOS) that the exact version of the "program" (usually the .NET core host program "dotnet") running be passed to lldb when loading the core dump.   The dotnet-symbol should download the exact match of all the .NET Core binaries.

I would like to know what makes the dotnet-symbol tool "shaky".  I know it can be inconvenient and we have a future work item to integrate the support into the lldb plugin/SOS. 

@MichaelSimons would you know anything about creating docker tags?

**Comment by MichaelSimons** [comment]
@itrofimow - can you provide more details on what you mean by "static tags"?  There are a number of tags available in the microsoft/dotnet repo for each image type per supported OS/platform (See https://github.com/dotnet/dotnet-docker/blob/master/TAGS.md for the full list).  For example, the following are the currently supported amd64 Debian tags for the 2.1 ASP.NET Core runtime image.

```
2.1.6-aspnetcore-runtime-stretch-slim, 2.1-aspnetcore-runtime-stretch-slim, 2.1.6-aspnetcore-runtime, 2.1-aspnetcore-runtime, aspnetcore-runtime (2.1/aspnetcore-runtime/stretch-slim/amd64/Dockerfile)
```

Is the `2.1.6-aspnetcore-runtime-stretch-slim` image sufficient?  The .NET content is static in this image.  This tag/image will get updated only when there is a change to the base image - e.g. `debian:stretch-slim`.  If you want the OS to be static, we do not offer a tag for this scenario.  You would need to reference the .NET images via a digest.

**Comment by MichaelSimons** [comment]
@itrofimow - The `<major>.<minor>-<image type>` tags such as `2.1-aspnetcore-runtime` are floating tags and as you mention automatically pick up the latest patches.  These are meant for scenarios in which you want to automatically pickup the latest patches.  It sounds like you want to use the `<major>.<minor>.<patch>-<image type>-<os variant>` tags (e.g. `2.1.2-aspnetcore-runtime-stretch-slim`) which are pinned to a particular version of .NET.  The older versioned tags exist such as `2.1.2-aspnetcore-runtime-stretch-slim` but they are not documented in the readme because they go out of support as soon as a new patch is available.  By "out of support", I mean they don't get rebuilt as the base layers (e.g. the OS) are patched.  If you want to see the full list of tags available on Docker Hub, you can visit https://registry.hub.docker.com/v1/repositories/microsoft/dotnet/tags

**Comment by itrofimow** [comment]
Wow, i didnt know about that, i thought these tags listed here (https://hub.docker.com/r/microsoft/dotnet/tags/) were the only available. TIL.
Thank you very much.

**Comment by MichaelSimons** [comment]
@itrofimow - glad to help.  The [Tags](https://hub.docker.com/r/microsoft/dotnet/tags/) tab on Docker Hub is pretty useless and causes more confusion than good IMO.  The primary issue is that it is not a complete listing rather it is the 100 most recent tags.  There are numerous repos like [microsoft/dotnet](https://hub.docker.com/r/microsoft/dotnet) which have more than 100 active tags not including any historical tags.
