### ISSUE TITLE
Brew - dnvm.sh?

### ISSUE THREAD

**Issue by acidhax** [dotnet/coreclr#2103]
```
You will likely need to register the dnvm command:

source dnvm.sh
```

There is no given path, or hint to where we can find dnvm.sh

**Comment by glennc** [comment]
We've stopped using the Homebrew formula for dnvm.sh. For instructions on getting started with OS X you should go here: https://docs.asp.net/en/latest/getting-started/installing-on-mac.html

Having siad that, IIRC dnvm.sh is on your path once you have installed it using Homebrew. So you can enter it into your bashrc exactly as it outputs and it will work.

But you should go and follow the docs rather than using Homebrew, where did you read the instructions that use Homebrew? Must be something we missed updating.

**Comment by weshaggard** [comment]
@acidhax this isn't the most appropriate repo for this question so I'm closing. Please follow-up with @glennc if you have further questions.
