### ISSUE TITLE
Deprecate TaskCompletionSource and replace it with a struct based type

### ISSUE THREAD

**Issue by omariom** [dotnet/coreclr#2118]
TaskCompletionSource  is mostly an implementation detail and as  an immutable type is a perfect candidate to be a struct. 
Then why not deprecate it and create a new implementation? It will save us 24 bytes and one indirection.

**Comment by stephentoub** [comment]
> Why not deprecate it?

There are plenty of situations where you actually want a reference type, such as when passing it around as object state.

> candidate to be a struct

That's basically what ```AsyncTaskMethodBuilder``` and ```AsyncTaskMethodBuilder<T>``` are.  You can use those directly if you want a struct-based version.  There are some small differences, but the core idea remains the same, e.g.
```C#
var tcs = default(AsyncTaskMethodBuilder<T>);
Task<T> t = tcs;
...; // code that calls tcs.SetResult/SetException
return t;
```

**Comment by omariom** [comment]
@stephentoub 
>There are plenty of situations where you actually want a reference type, such as when passing it around as object state.

In such case one could just box it.

>That's basically what  AsyncTaskMethodBuilder  and  AsyncTaskMethodBuilder<T>  are.

Thanks for the suggestion! I found once its usage in your PR and completely forgot about.
But from API visibility point of view they are not complete replacement for TSC.

Btw, just found that one TSC weighs 104 bytes, but a boxed AsyncTaskMethodBuilder<bool> takes 24 bytes less.

**Comment by stephentoub** [comment]
> just found that one TSC weighs 104 bytes

No, it doesn't.  It's an object with a single field.  

You're likely including the size of the task that's allocated during its construction, whereas AsyncTaskMethodBuilder as a struct, doesn't have a default ctor, and thus its Task isn't created until you you access its Task property.

This also highlights one of the dangers with a struct-based design: if you have such a default struct, you must access its Task before you hand it out to anyone, otherwise they'll be operating on different instances of the struct, and they'll each get their own task.

> In such case one could just box it.

I wasn't arguing against a struct-based approach.  I was saying that there's no reason to deprecate the existing type, which is widely used and works fine, and often you actually do need an object.  In fact, the majority of cases I've seen do actually need an object to pass around multiple pieces of state: with a struct-based type, you'd embed the struct in whatever reference type you write to hold those multiple pieces of data... but you can instead just have that derive from TaskCompletionSource.

> But from API visibility point of view they are not complete replacement for TSC.

Does that matter?  For the cases where you know it's heavier than you need, you have a tool available to you to address it.

**Comment by omariom** [comment]
> No, it doesn't. It's a reference type with a single reference field. 
You're likely including the size of the task that's allocated during its construction, whereas AsyncTaskMethodBuilder as a struct, doesn't have a default ctor, and thus its Task isn't created until you you access its Task property.

Yes, the size of the Task is also counted. But forgot to box ATMB before accessing Task property. Boxed it takes 120 bytes.
TSC: 24 (instance) + 80 (Task) = 104
ATMB: 40 (box) + 80 (Task) = 120
TSC is the winner.

Measured in .NET 4.5.2

**Comment by omariom** [comment]
People may find the discussion interesting so I will leave the issue open for a while.

**Comment by stephentoub** [comment]
Ok, thanks.
