### ISSUE TITLE
Achieve AppDomain.CreateInstanceAndUnwrap with AssemblyLoadContext

### ISSUE THREAD

**Issue by ritchxu** [dotnet/coreclr#21246]
Is following a valid porting from .NET to .NET Core regarding use of AppDomain?

`AppDomain` in .NET
```
public static TypeABC CreateInstanceInDomain(AppDomain appDomain)
{
     return (TypeABC)appDomain.CreateInstanceAndUnwrap(typeof(TypeABC).Assembly.FullName, typeof(TypeABC).FullName);
}
```
`AssemblyLoadContext` in .NET Core
```
public static TypeABC CreateInstanceInDomain()
{
     // AssemblyLoadContext loads assembly into a load context different from that of the currently executing assembly
     Assembly loadContextAssembly = AssemblyLoadContext.Default.LoadFromAssemblyName(typeof(TypeABC).Assembly.GetName());
     return (TypeABC)loadContextAssembly.CreateInstance(typeof(TypeABC).FullName);
}
```

**Comment by vitek-karas** [comment]
That depends on what the code is trying to achieve. But in general I would say that as presented the code doesn't do what it should.

`AssemblyLoadContext.Default` is the default load context - similar to the default AppDomain in .NET Framework. It's the load context into which the app's main assembly is loaded.

If your application is using AppDomains to provide binding isolation (so that it can for example load multiple versions of the same assembly, or to isolate a "plugin" from the app) then it would need to create a custom instance of `AssemblyLoadContext` and load into it. Then it will get the desired isolation. Calling `AssemblyLoadContext.Default.LoadFromAssemblyName` will always load the assembly into the default context.

One other thing to be aware of: If your .NET Framework application relies on the runtime to find the assembly file on the disk (based on its name), then .NET Core will likely not do that for you. The Default load context has a list of all the assemblies which the app was compiled with (static references introduced during build). Those assemblies will almost always load into the default context. So if you need to load some additional assembly which was not part of the app during build, the code will need to find the file itself first.

So you may want to call `LoadFromAssemblyPath` instead. But then again, this depends on what the code is trying to achieve.

If you can describe the scenario in a bit more detail, I'll be happy to provide more detail as to how the implementation should work.

**Comment by ritchxu** [comment]
The code is trying to isolate a plugin from the app as the caller portion shown below:
```
AppDomain appDomain = null;
try
{
    var setup = new AppDomainSetup { ApplicationBase = assemblyPath, PrivateBinPath = Path.Combine(assemblyPath, "plugins") };
    appDomain = AppDomain.CreateDomain(nameof(TypeABC), null, setup);
    var perfCounterInstaller = TypeABC.CreateInstanceInDomain(appDomain);
    // do something else...
}
finally
{
    if (appDomain != null)
    {
        AppDomain.Unload(appDomain);
    }
}
```
Based on your suggestion, I believe I ought to create my own load context:
```
class MyLoadContext : AssemblyLoadContext
{
    protected override Assembly Load(AssemblyName assemblyName)
    {
        return null;
    }
}
```
and replace `AssemblyLoadContext.Default.LoadFromAssemblyName` with `new MyLoadContext().LoadFromAssemblyPath`

If I'm on the right path, that brings me a question on what I should really do when overriding the `Load` method?

**Comment by vitek-karas** [comment]
I think the custom load context should look something like this:
``` C#
class MyLoadContext : AssemblyLoadContext
{
    public MyLoadContext(string basePath)
    {
        this.Resolving += (context, assemblyName) => 
        {
            string path = Path.Combine(basePath, assemblyName.Name + ".dll");
            if (File.Exists(path))
            {
                return context.LoadFromAssemblyPath(path);
            }
            return null;
        };
    }

    protected override Assembly Load(AssemblyName assemblyName) => null;
}
```

Once you have this, you can use it like this:
``` C#
MyLoadContext pluginContext = new MyLoadContext(Path.Combine(assemblyPath, "plugins"));
Assembly pluginAssembly = pluginContext.LoadFromAssemblyName(new AssemblyName("PluginAssembly"));
IPluginInterface plugin = pluginAssembly.CreateInstance("PluginType");
```

From your code above it's unclear what types the code is using to "talk" to the plugin. In .NET Framework the `CreateInstanceAndUnwrap` did some magic to hide this from the user. In .NET Core, there's no such magic, so the code has to be specific. In my sample above the idea is that `IPluginInterface` is the interface through which the app talks to the plugins. For things to work correctly, the `IPluginInterface` needs to be in a separate assembly, which is part of the app. The plugin assembly then references this interface assembly and implements the interface.

As shown this would provide isolation for cases were the isolation is absolutely necessary (plugin using higher version of a given assembly than the app), but otherwise it would try to unify on the assemblies from the app first. If you're looking for more strict isolation, then you would basically do the same but instead of implementing the `Resolving` event handler, you would do so in the `Load` method.

**Comment by ritchxu** [comment]
Thanks for the details explanation. I made a mistake in stating we use `AssemblyLoadContext` to directly isolate plugins. Instead, we intend to isolate the instance that actually loads the plugins later:
```
using System.Runtime.Loader;

internal class BaseLoadContext : AssemblyLoadContext
{
    // follow your sample so omitted here
}

public static Foo CreateInstanceInLoadContext()
{
    BaseLoadContext loadContext = new BaseLoadContext(typeof(Foo).Assembly.Location);
    Assembly assembly = loadContext.LoadFromAssemblyName(typeof(Foo).Assembly.GetName());
    return (Foo)assembly.CreateInstance(typeof(Foo).FullName);
}

Foo.ExtractManifestFiles()
{
    //...
    Assembly assembly = Assembly.ReflectionOnlyLoadFrom(pluginPath);
    //...
}
```
We expect as long as we invoke `ExtractManifestFiles` on the instance created with `CreateInstanceInLoadContext`, plugins would be in the same load context as `Foo`, hence isolated from the main context. Is this assumption correct? As a silly side question if you could suggest what I did wrong, when I attempt to run this code, I keep running into the following error:

> Could not load file or assembly 'System.Runtime.Loader, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by vitek-karas** [comment]
`ReflectionOnlyLoadFrom` is not supported in .NET Core. The API exists, but it will always throw.
We're currently working on a "replacement" dotnet/corefx#2800.

You can load the assemblies for real (`Assembly.Load` or similar) and only use it for reflection - not ideal but should work just fine.

The loading is a bit complicated. If the calling assembly is in some custom context (call it PluginContext) then:
- if the new assembly is directly referenced (as in compile time reference), it will be loaded into the same context (so PluginContext)
- if you use `Assembly.Load` it will try to load to the caller context - but this is load by name (not path), so the PluginContext would need to be able to resolve the assembly in its event handler.
- if you use `Assembly.LoadFrom` it always loads into the Default context - so don't use this here
- similarly `Assembly.LoadFile` will load into yet another context - don't use that

If you want to be explicit, the best way is to call `PluginContext.LoadAssemblyFromPath` - that will for sure load the assembly into the desired context.
If you have an assembly object, you can ask which load context it belongs to by calling `AssemblyLoadContext.GetLoadContext`.

Finally to your error - do you by any change try to run this on .NET Framework (The desktop framework)? `AssemblyLoadContext` doesn't exist there.

**Comment by jeffschwMSFT** [comment]
Closing this question for now, but please feel free to let us know if you have any other questions.
