### ISSUE TITLE
Remove code duplication in gentree.cpp

### ISSUE THREAD

**Issue by alexandrnikitin** [dotnet/coreclr#2150]
There's a code that checks tree for side effects and has logic that checks arguments. That logic is duplicated and executed twice. Can we leave it in one place?

A piece of code in `Compiler::gtTreeHasSideEffects`
https://github.com/dotnet/coreclr/blob/release/1.0.0-rc1/src/jit/gentree.cpp#L10888-L10900

Another on in `Compiler::gtNodeHasSideEffects` which is called from  `gtTreeHasSideEffects`
https://github.com/dotnet/coreclr/blob/release/1.0.0-rc1/src/jit/gentree.cpp#L10820-L10829

**Comment by mikedn** [comment]
Looks like the duplicate in `gtTreeHasSideEffects` is useless because just before it `gtNodeHasSideEffects` is called which does the same thing.

But the whole thing is peculiar. The primary user of these 2 functions is `gtExtractSideEffList` and that one kind of calls both. The comment on `gtTreeHasSideEffects`'s declaration claims that the children are taken into account but it's not clear how that's done, the function only looks at the children in the special case of GT_CALL. I suppose it doesn't really matter as `gtExtractSideEffList` is recursive but it surely looks weird.

**Comment by erozenfeld** [comment]
Fixed by #4041.

**Comment by alexandrnikitin** [comment]
@erozenfeld Thank you!!
