### ISSUE TITLE
New Contention event with duration as a field

### ISSUE THREAD

**Issue by gleocadie** [dotnet/coreclr#21524]
Currently, when you want to measure the contention using ETW/LTTng events emitted by the Runtime, you have to get the timestamp of the Start event and subtract it to the timestamp of the Stop event.

Wouldn't it be simpler to have a new event (ContentionStat or a new version of ContentionEnd) which contains the duration of the contention (and other info if needed… don't have a new one in mind for now)?

**Comment by sywhang** [comment]
@kouvel Do we want this? If so, I can work on adding this.

**Comment by sywhang** [comment]
cc @vancem @noahfalk @jorive

**Comment by vancem** [comment]
First I want to make sure that everyone knows that if you happen to be using the PerfView tool (https://github.com/Microsoft/perfview) that its 'events' view already does what @kouvel suggests (it creates a pseudo-field called DURATION_MSEC for any 'stop' event of a 'Start-stop' pair.   Here is an example 

<img width="420" alt="capture" src="https://user-images.githubusercontent.com/8459414/52227580-c3e64700-2864-11e9-98e6-be4eb8fe0734.PNG">

Here are the pros and cons of having such a field 

PRO

1. For 'dumb' tools you get a useful piece of information (although for contentions, generally speaking the number of contentions is significantly more important than the durations).  
2. You don't need to emit the 'start event'   Since logging an event is much more expensive than logging one more field this can be a win IF the even happens often enough to matter (> 1000/sec), and for Contention events should really not be happening in tuned code (the performance of poor code while collecting events.    To realize this win you also need to have a way of turning off the start events (which we don't have for Contention events at the moment). 

CON
1. You have to do explict work to track the field.   Sometimes finding a place to remember the start time is a problem (for async operations), but for Contention it is trivial (it can be a local variable).
2. Unless you mandate that all start-stop events do this, there is still pressure for the tools to do this work, and if they do do it (like perfView did), then there is no point in doing this work in the runtime (since it does take effort).    
3. For it t work well, you need to enforce some consistancy among start-stop pairs (e.g. all stop events should have a 'duration' field.   
4. This will only work for new runtimes, thus there is pressure to just do it in the tool (and again, what is the point  of having the field if tools can do it better).  

The result of this is that generally I am NOT against having duration fields (because of PRO point 1), however because it really is better done in the tool for ALL start-stop events, I view actually investing in this as a lower priority.  

However @gleocadie  has already done the investment.   I looked over the fix that @gleocadie created and it looked OK (he added a new version of the Contention event with a new double field which is the duration.   It should be compatible.    The code is short and benign and there is no perf concern.   It may not add alot of value, but it adds some value (for dumb viewers) and has a very low cost.   

The long and the short of it, is that I would not block this.   If others feel strongly about it they should chime in.     If @gleocadie  makes a real pull request on CoreCLR out of the fix, I would be OK checking it in.

**Comment by kouvel** [comment]
I'm not worried about the overhead (it's negligible compared to the wait), but it's nonzero, this can be a very frequent occurrence esp. in NetCore (in NetFx it's much rarer) and hence frequent occurrences in NetCore don't necessarily point to an issue, and the tiny overhead from non-problematic contentions may potentially add up to a not-insignificant overhead. I would be happy if there was a way to cheaply check if there is a listener and only do the timing then, is that possible?

I just felt that it would be redundant. I'm sort of less worried about the overhead of two events as opposed to the overhead of timing it ourselves. It may even be more appropriate to decrease the frequency of this event in NetCore. Removing the start event also has the con that (for start/stop events that may last longer) if a start would have occurred but not an end during the profile slice, there would not be information about that in the profile.

**Comment by gleocadie** [comment]
@vancem Thanks for your explanation.

@kouvel I see your point. From my understanding, I can check if the category/keyword "CLR_CONTENTION_KEYWORD" is enabled (as it's done here https://github.com/dotnet/coreclr/blob/master/src/vm/eventtrace.cpp#L886). If enabled,
we can compute the duration and emit the events, otherwise we don't do any computation.
But, I don't see the point in not computing the duration and emitting the events (except avoiding a change in behavior). I would rather not emit the events. What do you think?

Out of Curiosity: Can you elaborate on the con of removing the start event please ? I don't see what would be the value to an analysis/investigation.

**Comment by vancem** [comment]
> Out of Curiosity: Can you elaborate on the con of removing the start event please ? I don't see what would be the value to an analysis/investigation.

For the contention event there is not alot of value in the start event, if the event has a duration (other than consistency with other start-stop events).     However for other start-stop events where actual work is asynchronous (and thus the start and the stop might be on different threads) having an event on the start (so you can take the stack there), is SUPER valuable (you mostly don't care about the stack of the stop event, you care who REQUESTED the work). 

In general when you just want 'high level metrics', having just the stop event with a duration is generally enough, but when you trying to figure out in detail WHY something is happening, having the stacks at the start event is the key piece of information.   

Not historically, we first JUST have a (start) contention event (with a stack).  Frankly that is still super-useful just by itself.   We added the end event so we could get durations (but the incremental value is small.   Given that contentions are expensive and hopefully uncommon, the overhead issue is really not important.

**Comment by kouvel** [comment]
> Out of Curiosity: Can you elaborate on the con of removing the start event please ? I don't see what would be the value to an analysis/investigation.

Regarding what I said about removing the start event, suppose there's a bug or perf issue that causes a thread to hold a lock for a long time, a bunch of other threads eventually get stuck waiting for the lock, and overall perf degrades. If I get a profile that shows the overall perf degrading but not recovering, it would be nice to be able to see the contention start events despite there not being any contention end events in the profile, I can tell how long the lock was held by the end of the profile and correlate that to the perf degradation. There are other ways to debug that and perhaps it's not that interesting. Anyway I'm not particularly concerned about the change.
