### ISSUE TITLE
something funky happening intermittently in dotnet/cli build

### ISSUE THREAD

**Issue by krwq** [dotnet/coreclr#2153]
From time to time we are getting csc.exe crashes in our repo. Roslyn folks say it is coreclr issue:
https://github.com/dotnet/roslyn/issues/6993

To repro simply run dotnet/cli build on Windows in a loop and it will happen eventually (not sure if repros on Linux).

**Comment by agocke** [comment]
Specifically, I think https://github.com/dotnet/cli/issues/132 is probably a bug in CoreCLR. I could believe https://github.com/dotnet/roslyn/issues/6993 is in the DiaSymReader

**Comment by jkotas** [comment]
@JohnChen0 Could you please take a look?

The problem is that:
1. the main csc.exe has ready-to-run native image
2. ready-to-run native image does not get loaded at its preferred base address
3. the relocs that are supposed to be applied to compensate for missing preferred base address are not applied for some reasons

It only repros intermittently because of ASLR - whether the image misses its preferred base address depends on how ASLR decides to randomize the address space.

**Comment by AustinWise** [comment]
For anyone else who would like a workaround in the mean time, set the ComPlus_ReadyToRun environmental variable to 0. On Windows you can do it like this in the console:
```
set ComPlus_ReadyToRun=0
```
I can now build the cli repo again!

**Comment by JohnChen0** [comment]
All related crash dumps I've seen were from Windows 7. I have been able to repro this bug easily on Win7, but haven't been able to repro it at all on Win10. Has anyone been able to repro this on Win8 or above?

I have found a fix that had made csc work reliably on all versions of Windows for me. The fix is to turn on the DLL bit in the PE header of csc.ni.exe. Currently, csc.exe, csc.dll, and csc.ni.exe all have DLL bit turned off, i.e., they all appear as EXE to the OS. This might have confused Win7, making it incorrectly doing ASLR fixups.

For CoreCLR, we can change crossgen to always set DLL bit in ReadyToRun (and native) images, since CoreCLR always requires a host EXE to start the process.

**Comment by JohnChen0** [comment]
Fixed in CoreCLR with #2901. The ReadyToRun image for csc.exe still needs to be re-generated before this AV problem will go away.

**Comment by agocke** [comment]
@JohnChen0 Could this repro without a native image? If so, we may want to modify how we emit assemblies to always set the DLL bit.

**Comment by jkotas** [comment]
@agocke This problem is specific to native images.
