### ISSUE TITLE
Debug mode code gen optimizes unused parameters away

### ISSUE THREAD

**Issue by hoyosjs** [dotnet/coreclr#21544]
@dotnet/jit-contrib 

This issue repros on Windows x64 with runtimes 2.1.6, 2.2.0, and 3.0.0 preview. (SDK 2.1.502, 2.2.101, 3.0.0

With the repro below, the value of `a` gets updated under the debugger once `x` gets defined, possibly as `a` has no future references and it's a value type parameter. However, this doesn't seem to happen with other parameter types. From what I can see got variables have the same address, although in debug mode I expect the JIT not to optimize unused variables (as they can potentially be inspected or used for funceval.

```c#
namespace ConsoleApp
{
    class Program
    {
        public static void Main(string[] args)
        {
            Test(0); 
        }

        private static void Test(decimal a)
        {
            var x = a - 10;
            return; // break here
        }
    }
}
```

```xml
<Project Sdk = "Microsoft.NET.Sdk" >
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.2</TargetFramework>
  </PropertyGroup>
</Project>
```

**Comment by AndyAyersMS** [comment]
Yes, the jit is (somewhat unexpectedly, for debug codegen) optimizing away making a copy of `a` to pass to the decimal subtract method because the call use of `a` is the last use.

This only happens for parameters that are passed implicitly by-reference.

We should not do this optimization for debug codegen.
