### ISSUE TITLE
AppDomain name failure breaks debugging on macOS and some Linux distros

### ISSUE THREAD

**Issue by gregg-miskelly** [dotnet/coreclr#21552]
1. Create a new .NET Core 3.0 preview 1 program on macOS
2. Attempt to launch the program under a debugging using the VS Code C# extension

Result:
Debugging fails because when the app domain create call back is fired, ICorDebugAppDomain.GetName fails with E_FAIL, which all managed debuggers in the VS family do not handle.

**Comment by janvorli** [comment]
@gregg-miskelly does it work correctly on Windows in VS?

**Comment by gregg-miskelly** [comment]
As far as we have seen - yes. It seems like we are always able to get the app domain name during the app domain create call back in 3.0 preview 1.

**Comment by hoyosjs** [comment]
I'll confirm this, it definitely doesn't reproduce on Windows and none of our current tests hit this. Building a debug build to try to drill a bit further.

**Comment by hoyosjs** [comment]
@gregg-miskelly Sorry it took a while to investigate this. I was able to verify this happens in both linux (at least Ubuntu 16.04 and 18.04) and OSx. It was caused by some of the changes done around the default AppDomain. In the DBI when we try to get the AppDomain's name, we obtain it through the system domain. The pointers up to that point were fine, but the default AppDomain was being retrieved as a null pointer. From there, the name resolution ends up throwing a `E_NOINTERFACE` HR that ends up bubbling up as an `E_FAIL`. I was also verified the behavior is no longer present in newer builds of the runtime (say for example 3.0.0-preview-27218-01) and that the pointer is not being properly reported to the DAC.
