### ISSUE TITLE
Add missing test for hoisting static vars

### ISSUE THREAD

**Issue by alexandrnikitin** [dotnet/coreclr#2157]
It seems there's a bug in hoisting static variables reads. Comment says that there's a test that shows that. Could you add the tests please. Better code not binary :smile: 
https://github.com/dotnet/coreclr/blob/release/1.0.0-rc1/src/jit/optimizer.cpp#L5943

```
// Currently we must give up on reads from static variables (even if we are in the first block).
//
if (tree->OperGet() == GT_CLS_VAR)
{
    // TODO-CQ: test that fails if we hoist GT_CLS_VAR: JIT\Directed\Languages\ComponentPascal\pi_r.exe method Main
    treeIsHoistable = false;
}
```

**Comment by mikedn** [comment]
I don't think that the comment implies that there is a bug in the JIT compiler, the bug may actually be in the test itself. Neither the old 64 bit JIT nor the 32 bit JIT hoist local loads and doing so no can break poorly written multithreaded code.

**Comment by alexandrnikitin** [comment]
One more question then: When we decide whether an expression is a CSE candidate in:
https://github.com/dotnet/coreclr/blob/master/src/jit/optcse.cpp#L2003
`GT_CLS_VAR` is set as a candidate for CSE. It's a contradiction, isn't it?

**Comment by mikedn** [comment]
Any static (and instance field) load motion or elimination can affect incorrect multithreaded code. But the other 2 JIT compilers also do CSE in this case so there so the fact that RyuJIT does this as well is unlikely to break existing code.

Anyway, a test for this case should exist. Maybe not the one mentioned in source as it appears to depend on a 3rd party compiler but one specifically designed to catch whatever the problem is.

Interestingly, disabling that check doesn't result in any code changes in the entire mscorlib/corefx. Looks like there aren't many opportunities for this optimization out there.

**Comment by alexandrnikitin** [comment]
Agreed, they both affect multithreaded code. But it works for CSE and doesn't for Hoisting. This's a question for me.

>Interestingly, disabling that check doesn't result in any code changes in the entire mscorlib/corefx. Looks like there aren't many opportunities for this optimization out there.

Do you mean the check in `optimizer.cpp`? or in `optcse.cpp`?

**Comment by mikedn** [comment]
> But it works for CSE and doesn't for Hoisting. This's a question for me.

The point is that CSE was done in previous JIT compilers while static load hoisting wasn't, this might mean this is a backwards compatibility issue.

> Do you mean the check in  optimizer.cpp ?

Yes, the check in optimizer.cpp, the subject of this issue.

**Comment by cmckinsey** [comment]
This issue along with several other issues in the invariant code motion are being tracked right now. Unfortunately we have not been able to move our internal bug system over to Github issues as quickly as we'd like.

Lets avoid using the term bug here. There is no correctness issue, neither in the implementation or the test case that we're aware of. I'm not super familiar with the implementation, but the comment is referring to more work required to be able to determine legally whether static fields can be hoisted out of loops.

I don't believe the concern here is regarding poorly written multi-threaded code. We do have cases where we try to conform to making bad code work, but I don't recall this was one of them. Simply making CSE heuristics more aggressive could make such illegally written multi-threaded code break. Its hard to allow the eco-system to improve if we keep that bar. AFAIK as long as its not marked volatile we can hoist it as long as other issues around class-initialization order are followed. And of course we cannot hoist the load above other side-effects, data-flow, exceptions, or other memory fence/barriers. Because the current SSA implementation does NOT incorporate memory SSA, I believe the CLS_VAR itself probably does not have sufficient def/use information to correctly identify legal cases to hoist out of loops. I believe these later checks are why it's disabled today as there are insufficient checks for some of these.

CLS_VAR is a candidate for CSE because the value-numbering implementation tracks heap definitions separately from the SSA form and that can be used to eliminate redundant references correctly. But value-numbering doesn't tell you where you can move code to. So most of the other optimizations typically check optIsSsaLocal() to determine whether the SSA form holds valid definition information. So in this case I suspect because the code in optTreeIsValidAtLoopHead() does not check for this it cannot correctly determine legal cases to hoist trees that are not a function of all locals.

I believe there are good opportunities for this to benefit, especially for readonly statics and static arrays. I was just looking at some hot code in Roslyn the other day that involved some invariant static load hoisting opportunities.

Regarding the tests, we will soon begin bringing more tests over. In some cases, we may not be able to bring over all the tests we have, either because of pedigree or because of dependence on Full CLR features. So unfortunately I can't say yet whether this test will come over with that broader effort right now. But I'm sure we can capture the fundamental problem from the test and give you the essential principal from which you can seed a new test case if you like?

**Comment by mikedn** [comment]
> So in this case I suspect because the code in optTreeIsValidAtLoopHead() does not check for this it cannot correctly determine legal cases to hoist trees that are not a function of all locals.

Hmm, maybe there actually is a bug somewhere. optTreeIsValidAtLoopHead returns "yes" for constants and any other leaf nodes when it probably should return "yes" for constants and "don't know" for any other leaf nodes. That said, it's not clear to me how is optTreeIsValidAtLoopHead different from optVNIsLoopInvariant, both end up chasing SSA defs to see if they're inside the loop or not. And the VN version is also able to track heap defs via VNF_PhiHeapDef.

I'd surely love to the see that failing test, even if only in executable form :smile:

**Comment by pgavlin** [comment]
@JosephTremoulet have your recent changes to static init hoisting had any effect on this?

**Comment by alexandrnikitin** [comment]
@pgavlin It seems so, there's no such branch in master anymore. I think it can be closed then.
