### ISSUE TITLE
What is the requirment for nuget package to be able to be used by .net core?

### ISSUE THREAD

**Issue by Kimi-Arthur** [dotnet/coreclr#2163]
I recently tried the dotnet cli to build my previous projects. It reports an error starting as:

> The dependency CommandLineParser 2.0.93-alpha does not support framework DNXCore,Version=v5.0.

It is possible to run with mono but doesn't run with dotnet cli (which I presume defaults to DNXCore as the message suggests).
Does it mean it requires modification of the package to support coreclr? I thought the MSIL or CIL code is standardised.

Even if it's intended, it will still greatly reduce the number of available packages to coreclr, which will make it somewhat useless (compared to mono). I do mean the runtime part instead of the cli part (which should be possible to switch to use mono).

**Comment by ericstj** [comment]
That package only carries a desktop implementations (big Windows .NET) for .NET 4.0 and .NET 4.5.  .NET Core is significantly smaller than desktop .NET.  The reason that package works for mono is because Mono pretends that it is the same as desktop .NET in the project metadata it exposes to NuGet.  This works sometimes, so long as the library doesn't use anything that mono didn't or couldn't implement like System.Web, WPF, WMI, platform invokes to Windows dlls, etc.

For the package to work on DNXCore the library developer needs to either target DNXCore50 or create a portable library that targets the subset of surface area supported by .NETCore (EG: netstandard).  For details on porting see: https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/support-dotnet-core-instructions.md

Many portable libraries in packages that exist today will just work on .NET core since it is a superset of all previous portable profiles.
