### ISSUE TITLE
Equivalent for AuthenticatedStream

### ISSUE THREAD

**Issue by tebeco** [dotnet/coreclr#2165]
Hi (and sorry Again),
I'm trying to migrate "ManagedOpenSsl" (can be found on github) to dnx
* AuthenticatedStream
I've found the class in the CoreClr at 2 places :
.\corefx-master\src\System.Net.Security\ref\System.Net.Security.cs
.\corefx-master\src\System.Net.Security\src\System\Net\SecureProtocols\AuthenticatedStream.cs
I'm guessing that this is the Second one I have to use (based on the 'src' vs 'ref' and the filename)

I went to the project.json and based on the file path i've tried :
  "frameworks": {
    "dotnet5.4": {
      "dependencies": {
        "System.Net.Security": "4.0.0-beta-23516"
      }
It's still telling me that it's not available for .Net Plateform 5.4
I've look for examples in coreclr-master but there's too much sln to find one working (sometimes i got 'project.json misisng files'
I've even tried to open the package downloaded with reflector :
.dnx\packages\System.Net.Security\4.0.0-beta-23516\ref\dotnet5.4\System.Net.Security.dll
=> no trace of AuthenticatedStream inside

I'm still new to DNX maybe my approach is really bad but i still don't get why the class is in the source but not the package itself

**Comment by SidharthNabar** [comment]
Hi @tebeco - this issue would be better asked in the corefx repro since System.Net.Security is part of the set of framework libraries (corefx) and not the runtime (clr). In any case, I just tried the latest version of this package from myget.org: 4.0.0-rc2-23525 (https://www.myget.org/feed/dotnet-core/package/nuget/System.Net.Security) and it does have the AuthenticateStream class. I know there are some issues with DNX packaging though - please see: https://github.com/dotnet/corefx/issues/4533 and https://github.com/aspnet/dnx/issues/3183

**Comment by tebeco** [comment]
I've posted to another issue on CoreFx as you proposed on friday
But i still can't make the "dotnet5.4" recognized this Class, for "dnx46" it's fine but so far i've copied/pasted the class from here :
http://referencesource.microsoft.com/#System/net/System/Net/SecureProtocols/AuthenticatedStream.cs

That beeing that you were saying that my question turned out to be about "corefx", not clr.
I have to be honest, i'm confused with all new names :
CoreClr, Clr, dnx, dotnet, CoreFx, .Net Platform, .Net Core ....
I guess that some of them might just be the same or on different level but I can't find a proper Scheme that explains what is what and etc ...
There's lots of page "talking" about it but I can't find clean statement that explain the global new view of all .Net Environment. :(
