### ISSUE TITLE
Attribute params of type `float` and `double` are broken

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/coreclr#2172]
I ran into this because `[Range]` from `System.ComponentModel.DataAnnotations` is broken if you try to give it `double` params. It doesn't honour the 'max' value you try to pass it. On investigation, it's not a bug in `RangeAttribute` - it seems to be a problem in CoreCLR itself, getting a malformed copy of the second attribute parameter if it's a double/float.

**Repro**

Given the following types:

    class TestClass {
        [CustomAttribute(1.0f, 2.0f)]
        public object SomeProperty { get; set; }
    }
    
    class CustomAttribute : Attribute {
        public CustomAttribute(float prop1, float prop2) {
            Console.WriteLine("prop1: {0}, prop2: {1}", prop1, prop2);
        }
    }

... and the following code to trigger it:

    typeof(TestClass)
        .GetProperty("SomeProperty", BindingFlags.Public | BindingFlags.Instance)
        .GetCustomAttributes();

Then on the Mono runtime, it correctly writes to the console:

    prop1: 1, prop2: 2

... whereas on CoreCLR, it writes:

    prop1: 1, prop2: NaN

Likewise, if you replace the floats with doubles, on Mono you correctly get:

    prop1: 1, prop2: 2

... whereas on CoreCLR you get:

    prop1: 1, prop2: 2.12199578948308E-314

Tested on 1.0.0-rc1-final for Mac.

**Comment by janvorli** [comment]
It sounds like a problem with struct passing in registers. I'll take a look into it.

**Comment by janvorli** [comment]
@SteveSandersonMS strange, on Linux with the latest coreclr, it works correctly both for float and double. I'll give it a try on OSX too, but the behavior should be the same since there should be no differences in the affected code between OSX and Linux.
@LLITCHEV - are you aware of any fix since the rc1 on the jitter side that could be related?

**Comment by LLITCHEV** [comment]
No. As far as I know things work. Ani FI/RIs?

**Comment by janvorli** [comment]
I have verified that with the current version of CoreCLR, the test produces correct values even on OSX.
So it must be an issue that was fixed since the RC1 was released.

@LLITCHEV I guess I was not clear. I meant - now it works, but in the 1.0.0-rc1-final it was not working properly based on @SteveSandersonMS. So I was asking if you have any idea which recent change in the jitter have fixed the problem.

**Comment by LLITCHEV** [comment]
@janvorli Thanks for the clarification! There were no fixes/changes (that I know of) since rc1 that could affect this. Since rc1 there were the following changes in the jit.
1. Some code cleanup/refactoring in the jit codebase that did not result in any logical change to the code.
2. A change affecting native layout classification (in an edge case).
3. Addition of tests to bring up the System V struct passing.
4. A fix for creating a proper scope info object for 2 register passed structs on System V (x64) - info needed only by the debugger to properly show values of such structs for arguments not being homed yet (still in the prolog).

The only thing I can remember in this area was a change to the VM to properly load float and doubles, but this was done before rc1 (and you probably know more about than me).

**Comment by janvorli** [comment]
@LLITCHEV thanks for reminding me - I can see that my fix for the floating point registers offset in the transition block somehow didn't make it to the rc1. That explains it all.

**Comment by sergiy-k** [comment]
Already fixed in RC2.
