### ISSUE TITLE
Debug Info Tracking for LCG methods for profiling support

### ISSUE THREAD

**Issue by mjsabby** [dotnet/coreclr#21731]
The runtime does not track IL->Native mapping or local variables for LCG methods. In some of my use cases LCG methods can become quite large and being able to get basic information like IL offset goes a long way in debugging performance and functional problems.

I'm not sure how much perf impact it'll have to JIT time, and so if there is a trade-off to be made maybe we could only pursue IL offset tracking and skip local variable tracking?

**Comment by jkotas** [comment]
The generation of debug info for LCG method is disabled because of there are no APIs for it and no end-to-end scenario that is lights up. What would the API and end-to-end scenario for this look like?

**Comment by mjsabby** [comment]
I'm thinking about it from profiling support. We would send this info to ETW, EventPipe and the Profiler APIs. Lighting it up in the debugger would have many more changes required.

**Comment by noahfalk** [comment]
I'm guessing the increased JIT cost for CPU time would be relatively small, though of course its always good to confirm that once we had a basic implementation in hand. If the perf costs turned out to be higher than I expect making the events opt-in could go a long way to mitigate that.

**Comment by noahfalk** [comment]
cc @tommcdon @vancem @jorive @sywhang

**Comment by vancem** [comment]
To comment on @jkotas question.   There is an ETW event called MethodILToNativeMap that dumps this IL->Native mapping as an ETW event.   As an aside, is also another event called CodeSymbols that will dump any PDB that is loaded (This handles the cases where assemblies/pdbs were loaded as blobs), but is not relevant here because LCG methods don't have source code (although you could imagine they do).  

Making LCG methods emit the IL->Native map (both as ETW or in the profiler API), seems straightforward enough. and PerfView at least will use that to show IL offsets, but that is not terribly useful since it does not have the IL.     If LCG also emitted a PDB that included 'source' (embedded in the PDB), then you could imagine a nice end-to-end experience (but that is a bit of work).

It is not clear to me at all how the debugger handles all of this (if it just has the IL->Native map, what will it do with it).    I think a bit of experimentation to determine exactly what happens without PDBs is in order and whether that is valuable.   

Something certainly can be done here, but because LCG does not have 'source' in a normal sense, exactly what to do needs to be worked out.

**Comment by jkotas** [comment]
>  debugger handles all of this 

LCG methods do not have debugging story. (You can step through disassembly, nothing else.)

**Comment by mjsabby** [comment]
@vancem In .NET Core 2.0 we added support to notify the Profiler API of an LCG method being compiled and loaded. The Profiler can then request the IL and store it as it sees fit. It must do it in the callback because the runtime, (at least in some cases if I remember correctly) doesn't the store IL as well.

In ETW and EventPipe we only notify of compilation start an loading, not the actual IL. So the change in ETW/EventPipe would be in addition to the JIT tracking it.

Currently the JIT doesn't even track the mapping, so this issue to ask that we do that.

Today EventPipe and ETW are behind the Profiler API in the scenario of fetching the IL, but both can't map it back.

Hope that clears things up.

This feature is so that EventPipe can be used for all readonly scenarios and we don't have to use the Profiler API.

**Comment by noahfalk** [comment]
@mjsabby just to summarize my understanding, this is the information that you have available to you today for LCG methods:

- Name - Available via EventPipe
- IL Body - Available via ICorProfiler
- Native -> IL map - Not available
- Local variable homes - Not available

Your ideal story would be that Name, IL Body, and Native -> IL map are all available via EventPipe events. A satsifactory story would be Name and Native->IL map are available via EventPipe,  and IL body continues to be available via profiler. Does that sound accurate?

@vancem - I think we can assume that there will be no immediate improvement in the debugging scenario as part of this work and that is fine by me. The work required to do what Mukul is asking is only a small subset of what the debugger would need and I don't think we should enlarge the scope.

**Comment by vancem** [comment]
@msabby - are you building the profiler-tool support you want (that is what is on the other side of this new capability that gets the IL and displays it when someone shows a 'goto source' or equivalent)?   Perfview certainly does not do this today...

Providing the Native->IL map based using the MethodILToNativeMap event is straightforward enough (I am kind of surprised it does not already work).

**Comment by mjsabby** [comment]
@vancem Yes, if we can't get the data to EventPipe. But my hope is we can get the data to EventPipe.

**Comment by GSPP** [comment]
It would be awesome if you could step through the IL of a LCG method. Visual Studio could disassemble  byte code to IL.

Debugging LCG is quite hard. Any aid would be welcome.

**Comment by mjsabby** [comment]
Looks like ILStubs may be the only kind of code that don't already have their debug info generated. I think that's what the following code means.

https://github.com/dotnet/coreclr/blob/b7167889bc94c084527f184f852b867b2a1c1d56/src/vm/jitinterface.cpp#L12650-L12654

If that's true then JIT throughput may only be mildly impacted, since LCG methods are having their debug info generated by not exposed. I still have to emperically prove this.
