### ISSUE TITLE
Overload for binary search that take Comparison<T>

### ISSUE THREAD

**Issue by hickford** [dotnet/coreclr#2188]
[List<T>.BinarySearch](https://msdn.microsoft.com/en-us/library/3f90y839%28v=vs.110%29.aspx) has an overload that takes an `IComparer<T>`. As [remarked on Stack Overflow](https://stackoverflow.com/questions/8405789/why-doesnt-list-binarysearch-have-overloads-that-take-comparisont-in-additi), it would be helpful to have another overload that takes a [`Comparison<T>`](https://msdn.microsoft.com/en-us/library/tfakywbh%28v=vs.110%29.aspx) delegate. It is often more convenient to define a Comparison<T> than write an `IComparer<T>` class.

[List<T>.Sort](https://msdn.microsoft.com/en-us/library/b0zbh7b6%28v=vs.110%29.aspx) has both overloads. 

---

The same applies for Array.BinarySearch https://msdn.microsoft.com/en-us/library/system.array.binarysearch(v=vs.110).aspx

**Comment by gilbertluis** [comment]
Unlike Sort, BinarySearch need only one element in the collection at a time. so I suggest adding overload which take Func&lt;T, int&gt;, and without T item parameter.  ie.
BinarySearch( Func&lt;T, int&gt; compareTo ); and
BinarySearch( int startIndex, int count, Func&lt;T, int&gt; compareTo );

eg, find 5 in List&lt;int&gt;, call  BinarySearch( 5.CompareTo )

**Comment by mikedn** [comment]
As seen in the above PR attempt adding such an overload is problematic because it introduces ambiguity in overload resolution. `null` is a valid value for `comparer` so code like `list.BinarySearch(42, null)` won't compile anymore because the compiler doesn't know if `null` is a comparer or a comparison.

The presence of the up-for-grabs label seems unfortunate on this issue. I suppose one could "grab" it by working on an API proposal that actually works and can be reviewed.

I'm not even sure if this API addition is truly needed as we already have `Comparer<T>.Create(Comparison<T> comparison)`. Sure, `list.BinarySearch(42, Comparer<int>.Create((x, y) => x.CompareTo(y)));` is somewhat verbose but it does the job and in my experience `BinarySearch` isn't used that often.

Worse, this addition doesn't even solve a problem that is IMO pretty common. Sometimes you sort objects by a property and then you want to search by a property value and you don't have an object around. That is:

```C#
class Person
{
    public int Age { get; set; }
}

static void Main()
{
    var list = new List<Person>();
    // works but I need to create a Person object
    list.BinarySearch(new Person { Age = 42 }, Comparer<Person>.Create((x, y) => x.Age.CompareTo(y.Age)));
    // does not work
    list.BinarySearch(p => p.Age.CompareTo(42));
    list.BinarySearch(42, (p, a) => p.Age.CompareTo(a));
}
```

**Comment by AlexRadch** [comment]
@mikedn  What is `p` in code that does not work?

**Comment by AlexRadch** [comment]
If this issue about Adding API, I sagest add to Array<T> an List<T> many methods with `Func<T, TValue> select` as selector for items values

```
public void Sort<TValue>(Func<T, TValue> select); // sort by some select.
//All other overloads for Sort by select
public void BinarySearch<TValue>(Func<T, TValue> select); // BinarySearch by some select.
//All other overloads for BinarySearch by select
```

**Comment by mikedn** [comment]
> What is p in code that does not work?

`p` is supposed to be the item in the list that's passed to the comparer. As already stated, I'm talking about cases where I don't already have a person object. Since you're searching for objects it's pretty common that you don't already have an object.

> list.BinarySearch(42, (p, a) => p.Age.CompareTo(a)) can not rewrited to any code without creation temp Person.

Yes, it's not possible to reuse the existing implementation to provide such an API. And that may actually be a good thing performance wise, the existing implementation is skewed towards `IComparer<T>` but these days it's probably more common to use lambda expressions for this kind of stuff rather than creating custom comparers. Calling through a delegate can be slightly faster than calling through an interface method.

> public void Sort<TValue>(Func<T, TValue> select); // sort by some select

I'm not sure if that adds any value. For sorting you can always write `Sort((p1, p2) => p1.Age.CompareTo(p2.Age))`. And it is even efficient to do so because there's only one delegate/interface call per compare operation. With selectors you get 3 delegate/interface calls.

**Comment by AlexRadch** [comment]
@mikedn You want have such method `list.BinarySearch(42, p=> p.Age)`. This is search by select function.
So if you have only select function, it would be nice to Sort by this function also.

**Comment by mikedn** [comment]
> You want have such method persons.BinarySearch(42, p => p.Age)

Not really, I don't want that because a select function doesn't include a compare. And it's not only about performance, the select version would need an additional overload that allows you to specify a comparer/comparison to be used to compare the selected values.

Note that lists and arrays already have search facilities that allow you to search for an object when an object isn't already available (`Find`, `FindIndex` etc.) and do not have this select thing.

In any case, my main point is that before jumping at adding an overload there are various things to consider. Does it break existing code? Is it really needed? Is there something else that's needed in the area and that can solve the problem in a different manner?

**Comment by AlexRadch** [comment]
@mikedn Ok. You want next overload for BinarySearch ``
```cs
public delegate int CurredComparison<in T>(T x);
List<T>.BinarySearch(CurredComparison comparison);

// And use it like next
persons.Sort(Comparer<Person>.Create((x, y) => x.Age.CompareTo(y.Age))); //Sort persons by age
persons.BinarySearch(p => p.Age.CompareTo(42)); // Find person by age
```

It have more performance than next
```cs
var  selectAge = p => p.Age;
persons.Sort(selectAge); //Sort persons by Age
persons.BinarySearch(42, selectAge); // Find Person by age
```

But I think second is more flexible and more simple to understand and to write. In many cases default comparison is suitable. Also it looks like like linq.

**Comment by karelz** [comment]
@AlexRadch just a reminder: if you want to save wasted efforts, it would be best to first ping the issue (feel free to mention me) and ask for it to be assigned to you, before you start working on it ...

**Comment by AlexRadch** [comment]
Ok. It was easy code.

**Comment by AlexRadch** [comment]
What about my suggestion to add linq like Sort add BinarySearch ? See https://github.com/dotnet/coreclr/issues/2188#issuecomment-264824711

**Comment by ianhays** [comment]
>What about my suggestion to add linq like Sort add BinarySearch ?

@AlexRadch if you've got a separate API you want to add, please do a search for existing issues and then open a new issue for that API if you cannot find one. It's better not to have too many conversations at once in one issue.

**Comment by karelz** [comment]
Do we still think this API is a good idea? (Skimming through the text it seems it introduces ambiguity we don't want)
If we want to discuss the API and its shape, please file issue in corefx repo.

Closing for now (please speak up if I missed anything and shouldn't have done that ...)
