### ISSUE TITLE
Question on WinDgb and the SOS extension for debugging dotnet/coreclr on Windows OS.

### ISSUE THREAD

**Issue by lizetpena** [dotnet/coreclr#21938]
I used to teach and advanced C# debugging class long ago that would teach how to create memory dumps and analyze the heaps using WinDbg and SOS. This was for the 3.5 to 4.0 CLRs. For production crashes where the IDE is not available and the IntelliTrace collector is not a possibility because the developers don't have the Ultimate VS editions, what is the recommendation to do production debugging in the case of .NET Core solutions? Does WinDbg or SOS exist for this? If so, where could I find the downloads and any documentation on these tools?
Thanks in advance,
-Lizet

**Comment by danmosemsft** [comment]
Yes, windbg and sos work on .NET Core as well. (Since the runtime is named `coreclr.dll` you would do `sxe sos coreclr` where you might have done `sxe sos clr`).

sos.dll ships with .NET Core just as it ships with .NET Framework. Windbg is downloadable as as part of [the debugging tools.](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debugger-download-tools)

Windbg is Windows only though: on Unix, you must load sos into LLDB. Some [info here](https://github.com/dotnet/coreclr/blob/d73e20f6cb12d7cf4c9909ff70a8920c978a1ce3/Documentation/building/debugging-instructions.md). It is a bit more bumpy.

**Comment by lizetpena** [comment]
@danmosemsft 
Thank you! You made my day with the information. I'm preparing a training and I want to include some of the differences and the new ways to debug production issues without an IDE.

**Comment by danmosemsft** [comment]
Sure. Post back if you hit problems. Also if your presentation is public perhaps you could link it here when it's ready!
