### ISSUE TITLE
[profiler api] ilrewrite problem META_E_BAD_SIGNATURE

### ISSUE THREAD

**Issue by caozhiyuan** [dotnet/coreclr#22095]
i want add try catch finnally in method il.
first , i add code (before nop il ) at methed begin , but get error META_E_BAD_SIGNATURE BadImageFormatException: Bad binary signature. (Exception from HRESULT: 0x80131192) 
i check the il code is right, what can cause this problem? 

@noahfalk  can give a help?

code : https://github.com/caozhiyuan/clr-samples/blob/master/ProfilingAPI/ClrProfiler/CorProfiler.cpp#L525

new il:
.maxstack 293
.locals init 110001AA
// code size: 1048
  ldnull
  stloc.s         5146
  ldnull
  stloc.s         5147
  ldnull
  stloc.s         10268
  call            0A0003E3
  ldstr           70004DCC
  ldarg.0
  ldc.i4.3
  newarr          01000012
  dup
  ldc.i4.0
  ldarg.1
  stelem.ref
  dup
  ldc.i4.1
  ldarg.2
  stelem.ref
  dup
  ldc.i4.2
  ldarg.3
  stelem.ref
  callvirt        0A0003E4
  stloc.s         28
  nop
.... old il and EHClause new

**Comment by caozhiyuan** [comment]
i add this il
```
ldnull
stloc.s 26
ldnull
stloc.s 27
ldnull
stloc.s 28
call 0A0003E3
ldstr 70004DCC
ldarg.0
ldc.i4.3
newarr 01000012
dup
ldc.i4.0
ldarg.1
stelem.ref
dup
ldc.i4.1
ldarg.2
stelem.ref
dup
ldc.i4.2
ldarg.3
stelem.ref
callvirt 0A0003E4
stloc.s 28
nop
```

**Comment by noahfalk** [comment]
META_E_BAD_SIGNATURE means that some metadata signature was bad, but without context it would be challenging to determine which one and exactly what is wrong with it. Searching the runtime source there are about ~40 places that generate that error. I'm not going to be able to debug this for you, but I can offer some suggestions that will hopefully help you track it down:

1) Since CoreCLR is open source you can debug the runtime (either your own build, or download source/symbols from Microsoft for an official build). If you stop on the 1st chance exception where the InvalidProgramException is thrown the callstack and locals will likely offer some context about what exactly the runtime was parsing when it triggered the error. You could also put a breakpoint on every usage of META_E_BAD_SIGNATURE in the runtime if necessary.
2) This is a reasonably large IL body. Reducing the example to something minimal can help narrow down the issue. 
3) You can write an example of the code you want with the C# compiler and then disassemble the resulting IL/metadata with a tool such as ildasm, carefully comparing what the compiler generated to what your profiler generated. This is a fairly manual operation, but if you've already done step (2) to create a minimal repro then hopefully there isn't much IL/metadata to compare. 


And just a wild guess, if you changed the IL and added a local did you change the IL local var signature? If you did change it I'd check if you formatted it correctly. Hope that helps.

**Comment by caozhiyuan** [comment]
i changed local  var signature and add three variable and getnewtoken

**Comment by caozhiyuan** [comment]
ok thks i will try it

**Comment by caozhiyuan** [comment]
@noahfalk  i finished it . i DefineMemberRef use sig error.
