### ISSUE TITLE
Optimizing HashSet<s/byte> (and other small numbers) to use a single or few Vector256?

### ISSUE THREAD

**Issue by simplejackcoder** [dotnet/coreclr#22114]
It will be awesome if `HashSet<byte>`/`Dictionary<byte, V>` could be made to use to Intrinsics feature in CoreCLR and optimize the heck out of the this case. It is provable that with Vector256 all operations are basically bit mask operations in one single register.

This also got me thinking if we could have a hash code selection algorithm for HashSets where the developer out right states the max value a hashset may contain and for what max value is it profitable to just use Vector256 registers in sequence.

Most modern processors have a 64-byte cache line, therefore supporting a maximum value of 511 and a minimum value of 0 will be a no-brainer in my opinion using two Vector256 registers.

For the lookup performance, assuming all inlining is done great and well and the key that is being looked up has no collisions, we basically we have to beat the hash function accessing a register and doing math and then a single 64-byte cache line load of the pointer to the bucket and an equality check.

**Comment by simplejackcoder** [comment]
I left out an important point from my issue. The reason why I'm thinking about Vector256 is because I would like to do multiple checks, i.e. comparing multiple values, so think of it likes ContainsMultiple(array of input) and not Contains. Obviously the Contains could be implemented without any vector instructions at all.

**Comment by mikedn** [comment]
> It will be awesome if HashSet<byte>/Dictionary<byte, V> could be made to use to Intrinsics feature in CoreCLR and optimize the heck out of the this case. 

Why is this case worthy of such an optimization? Or to put it another way, if this case is so important to you, why don't you use a more suitable data structure - `BitArray` or some other suitable "bit vector" implementation?

**Comment by danmosemsft** [comment]
There are certainly fast maps that use SIMD instructions, such as Abseil's Swiss table
https://abseil.io/about/design/swisstables
https://github.com/abseil/abseil-cpp/blob/0dffca4e36791c7beeda04da10460b534283948a/absl/container/internal/raw_hash_set.h

It would be interesting to experiment with that approach, but that should start with a proposal or experiment in the dotnet/corefxlab repo (and if it panned out, my guess is that it would add new alternative types rather than lead to modifications in the existing ones - which has implications including code gen size, compatibility, ..)

**Comment by danmosemsft** [comment]
Mind if I move this issue over there @simplejackcoder ?

**Comment by danmosemsft** [comment]
This issue was moved to dotnet/corefxlab#2640
