### ISSUE TITLE
Full dump from CreateDump utility is huge

### ISSUE THREAD

**Issue by klesta490** [dotnet/coreclr#22545]
Simple few line .net core app that is full dumped using createdump utility has dump size  ~2,697,043,968  bytes, that is roughly 2.5GB. That is quite a lot for 10 line application :(. Our production dump, have 25GB+ even when consumed RAM shown in htop is 2.2 GB. 

Any advice? Minidumps are not an options because there are not visible method names from our assemblies.

**Comment by karelz** [comment]
@mikem8361 @noahfalk is this expected?

**Comment by mikem8361** [comment]
Yes, full dumps are large because they contain everything.  This option to createdump was only as a last resort.  The default "mini-dump" is suppose to have everything needed for the managed state, but the metadata needed to resolve the function or type names. This is issue https://github.com/dotnet/diagnostics/issues/56 will address this problem in SOS. We have worked around the problem in the 3.0/master coreclr branch in createdump by adding the metadata to the default minidump.

**Comment by klesta490** [comment]
I gues we can close this if it is going to be sloved in https://github.com/dotnet/diagnostics/issues/56
