### ISSUE TITLE
Double.TryParse behavior is different between .Net Core and .Net framework 

### ISSUE THREAD

**Issue by xuzhg** [dotnet/coreclr#22587]
For example:

If I create a .NET Standard library with a class as below:

```C#
public static class DoubleClass
{
      public static bool CanBeDouble(string numericStr, out double value)
      {
           return double.TryParse(numericStr, NumberStyles.Float, CultureInfo.InvariantCulture, out value);
      }
}
```
I can test the above static method in netcoreapp2.1 and .NET Framework 4.6.1.

Both netcoreapp2.1 and 4.6.1 has the same Main method:
```C#
static void Main(string[] args)
{
         string numStr = "-119.4878";
     // string numStr = "-119.48781";
         if (TestDouble.DoubleClass.CanBeDouble(numStr, out double value))
         {
              Console.WriteLine(numStr + " = " +value.ToString("R", CultureInfo.InvariantCulture));
         }
         else
         {
              Console.WriteLine("Failed");
          }

         Console.ReadKey();
 }
```

With the different input, we have different output:

#Result in .NET Framework

- -119.4878 = -119.4878

- -119.48781 = -119.48781

#Result in .netcoreApp2.1

- -119.4878 = -119.48779999999999

- -119.48781 = -119.48781

**Comment by stephentoub** [comment]
cc: @tannergooding

**Comment by tannergooding** [comment]
I'm actually not able to repro this.

On both net461 and netcoreapp2.1, I see:
```
-119.4878 = -119.48779999999999
```

Printing some additional details via:
```csharp
double d1 = -119.4878;
double d2 = double.Parse("-119.4878");

Console.WriteLine($"{d1}");
Console.WriteLine($"{d1:R}");
Console.WriteLine($"0x{BitConverter.DoubleToInt64Bits(d1):X16}");

Console.WriteLine();

Console.WriteLine($"{d2}");
Console.WriteLine($"{d2:R}");
Console.WriteLine($"0x{BitConverter.DoubleToInt64Bits(d2):X16}");
```

Shows:
```
-119.4878
-119.48779999999999
0xC05DDF381D7DBF48

-119.4878
-119.48779999999999
0xC05DDF381D7DBF48
```

**Comment by tannergooding** [comment]
In netcoreapp3.0, this has changed and we now return the shortest roundtrippable string for "R". This outputs:
```
-119.4878
-119.4878
0xC05DDF381D7DBF48

-119.4878
-119.4878
0xC05DDF381D7DBF48
```

**Comment by tannergooding** [comment]
There may be some cases in netcoreapp2.1 where parsing results in a different behavior. This is because the parsers were updated to be IEEE 754:2008 compliant.
Likewise, in netcoreapp3.0, there are cases where formatting results in a different behavior (because the formatters were updated to be IEEE 754:2008 compliant).

For the parsing changes (.netcoreapp2.1) this functionally means that `double.Parse` will now always return the same bits that the same string as a C# literal would be compiled to. Previously there were a number of values that would differ based on whether you used `double.Parse` or declared them as a literal (with the literals being the correct value).
For the formatting changes (.netcoreapp3.0) this functionally means that `double.Parse(value.ToString())` will now always return `value` (when value is already a `double`). Previously there were a number of values (including `Math.PI`) which would return a string with too few digits, causing a loss of precision when it was re-parsed.

**Comment by xuzhg** [comment]
@tannergooding I think you are using different version of TryParse.

What I am using is:
```
double.TryParse(numericStr, NumberStyles.Float, CultureInfo.InvariantCulture, out value);
```

**Comment by tannergooding** [comment]
@xuzhg, they are all the same method under the hood. I did explicitly try using the exact code you gave (and in the configuration you listed) and was not able to repro using that either. Perhaps you could share you the solution you are using to test this under?

This is also fairly trivial to test online, such as via:
* SharpLab (which uses full framework): https://sharplab.io/#v2:EYLgHgbALANALiATgVwHYB8g
* try.dot.net (which uses netcoreapp)

Just paste the following code:
```csharp
using System;
using System.Globalization;

public static class DoubleClass
{
  public static bool CanBeDouble(string numericStr, out double value)
  {
    return double.TryParse(numericStr, NumberStyles.Float, CultureInfo.InvariantCulture, out value);
  }
}

public class Program
{
  static void Main(string[] args)
  {
    string numStr = "-119.4878";
    // string numStr = "-119.48781";

    if (DoubleClass.CanBeDouble(numStr, out double value))
    {
      Console.WriteLine(numStr + " = " +value.ToString("R", CultureInfo.InvariantCulture));
    }
    else
    {
      Console.WriteLine("Failed");
    }
  }
}
```

**Comment by xuzhg** [comment]
[TestDouble.zip](https://github.com/dotnet/coreclr/files/2863246/TestDouble.zip)

**Comment by xuzhg** [comment]
@tannergooding Attached.

**Comment by tannergooding** [comment]
I see. This isn't a case of .NET Framework vs .NET Core but is instead a case of x86 vs x64. You'll notice that if you uncheck `Prefer 32-bit` in your `ClassicConsoleApp`, it (.NET Framework) will return the same value as .NET Core is returning.

I removed the split implementation (`src/vm/i386/fptext.asm`) back in September as part of https://github.com/dotnet/coreclr/pull/19775. This not only improved the perf significantly, but ensured that x64 and x86 both returned the same result.

As mentioned above, the formatting/parsing algorithms underwent further changes in .NET Core 3.0 and `ToString("R")` will now always return the shortest roundtrippable string. In the above case, this is `"-119.4878"` (the shorter string).

**Comment by xuzhg** [comment]
@tannergooding Thanks for the investigation. 

But, why "-119.4878" input has different behavior, meanwhile, "-119.48781", "-119.4877", "-119.4879" hasn't?

**Comment by tannergooding** [comment]
There were a number of things that lead to the differences between x86 and x64. `-119.4878` just happens to be a value that would trigger these cases. My best guess, without actually digging into the math/old implementations is that it is particularly susceptible because it's "exact string" lead to rounding in most cases but not in the 17 digit case.

For reference:
* `-119.4878`  = `-119.487799999999992905941326171`
  * 8th through 17th digit are 9's, 18th digit doesn't cause rounding
* `-119.48781` = `-119.487809999999996080077835359`
  * 9th through 17th digit are 9's, 18th digit causes rounding
* `-119.4877`  = `-119.487700000000003797140379902`
  * 8th through 17th digit are 0's, 18th digit doesn't cause rounding
* `-119.4879`  = `-119.487899999999996225596987642`
  * 8th through 17th digit are 9's, 18th digit causes rounding

Some additional details...

Prior to the changes made for netcoreapp3.0, the roundtrip format specifier (`"R"`) would effectively do the following:
1. Call an algorithm that generated 15 digits and power of 10
2. Determine if that generated information would parse back to the original value
3. If that information roundtrips to the original value, send it on to the formatter
4. Otherwise, regenerate 17 digits and the power of 10 and send it on to the formatter

The x86 digit generation algorithm relied on the x87 FPU stack, while the x64 digit generation algorithm relied on a method exposed as part of the C Runtime (`_ecvt_s`), which relied on big-integer arithmetic. These differences caused the generated digits to differ in various cases. Couple this with the "roundtrip" check working with the generated digits, rather than the resulting formatted string, causes more scenarios where the algorithms would differ.

In particular, the x86 algorithm relying on the x87 FPU stack meant that it was susceptible to the inaccuracies that exist in floating-point values. The x64 algorithm, on the other hand, didn't have this problem as relying on big-integer arithmetic meant it could always accurately generate the digits.

Depending on how accurately the underlying algorithm generated the digits and how when it applied the rounding semantics (or if it just tracked it as an additional digit) would have impacted whether or not step 3 succeeded.

**Comment by xuzhg** [comment]
@tannergooding Thanks for detail information. 

Would you please share your thoughts who to make the following if condition return true both on .NET Framework and .NET Core ( version < 3.0.0)?

```C#
string numericStr = " -119.4878";
double.TryParse(numericStr, NumberStyles.Float, CultureInfo.InvariantCulture, out double tmpDouble);

decimal.TryParse(numericStr, NumberStyles.Integer | NumberStyles.AllowDecimalPoint, CultureInfo.InvariantCulture, out decimal tmpDecimal);

decimal.TryParse(tmpDouble.ToString("R", CultureInfo.InvariantCulture), NumberStyles.Float, CultureInfo.InvariantCulture, out decimal doubleToDecimalR);
            
decimal.TryParse(tmpDouble.ToString("N29", CultureInfo.InvariantCulture), NumberStyles.Number, CultureInfo.InvariantCulture, out decimal doubleToDecimalN);

if (tmpDecimal == doubleToDecimalR && tmpDecimal == doubleToDecimalN)
{
    // Want to hit here?
}
```

**Comment by tannergooding** [comment]
Those checks, in general, could fail for any number of arbitrary values. Decimal and Double have different precisions and different bases (one being base 10, the other being base 2), so there are always numbers that may cause some loss of precision when converting back and forth between them.

In general, if you want the numbers to be accurate (up to 29 significant digits) you should use `decimal`. If you prefer speed and an approximation is okay, then using `double` or `float` is acceptable.
* As an example, `-119.4878` as a decimal is exactly `-119.4878`, but as a double it is approximately `-119.487799999999992905941326171`

In order to convert between the two, just casting the result should be acceptable and should help minimize the precision loss.

If you want to continue doing it the current way, you would need to pick some format string that only returns "x" significant digits. Using "N17" (which is actually treated the same as `"N15"` for full framework and netcoreapp prior to 3.0) instead of "R" would work here. However, It might break in netcoreapp3.0 and could break for other values on full framework or older versions of netcoreapp.

**Comment by xuzhg** [comment]
@tannergooding Thanks a lot. It seems our codes [here](https://github.com/OData/odata.net/blob/master/src/Microsoft.OData.Core/UriParser/ExpressionLexer.cs#L1177-L1198) need to refactor.

**Comment by tannergooding** [comment]
Some notes that may help...

For any given numeric string that contains less than 29 digits, `decimal` is likely the best choice, as it will always be exact. For any given string that contains more than 29 digits, the conversion will either fail or it will succeed and round. `decimal.ToString("G29")` should always give you a string that roundtrips.

For example: `decimal.Parse("12345678901234567890123456789.0")` will succeed and be exact.
* You can move the decimal point anywhere in the string, except to the very beginning, and have it be exact.
* Adding more digits before the decimal point will cause it to fail
* Adding more digits after the decimal point will cause the last non-zero digit to round or the additional digits to be dropped

For other numeric strings, `double` and `float` should always succeed parsing (no matter how many digits are included), but will round to the nearest representable value (this may be exact, such as for powers of 2, but often will not be exact). `double.ToString("G17")` and `float.ToString("G9")` should always give you a string that roundtrips.
* "R"`, prior to netcoreapp3.0, actually had a few issues and will not always roundtrip
* In full framework and versions of netcoreapp prior to 2.1, the parsing logic only considers up to 50 significant digits and treats remaining digits as `0`, this can lead to values that are not actually the nearest representable value

**Comment by xuzhg** [comment]
@tannergooding Thanks a lot for your explanation.

**Comment by RussKeldorph** [comment]
This appears to be answered.  Please reopen if not.
