### ISSUE TITLE
coreclr_create_delegate to instance methods

### ISSUE THREAD

**Issue by NextTurn** [dotnet/coreclr#22600]
It seems that instance methods are no different from static methods except for an implicit `this` parameter, so I guess it should be possible for `coreclr_create_delegate` or `ICLRRuntimeHost2::CreateDelegate` to create function pointers to instance methods as well as constructors.

If we need to store an object reference in native codes (not always necessary), we will create a `GCHandle` for it.

**Comment by jkotas** [comment]
You can create a static method, get a pointer to it via `coreclr_create_delegate` and that static method can create the instance of the object you need, wrap the result in GCHandle, and do anything else.

It is intentional that `coreclr_create_delegate` handles just the simple case of static methods.

**Comment by NextTurn** [comment]
Then I'd like to request for a more convenient API.

**Comment by NextTurn** [comment]
Closing, since there's been no discussion, which suggests that there is no need for such feature.

**Comment by marler8997** [comment]
Working on a tool to call C# from D, this would be a nice feature for us.
