### ISSUE TITLE
Add Marshal.StructureToSpan

### ISSUE THREAD

**Issue by fanoI** [dotnet/coreclr#22671]
I think it will be nice to have the possibility to marshal a structure directly into a Span instead to have to pass from a IntPtr that always forces you to do a copy.
Using a Span will permits to use stack memory to convert the struct to a Span<byte>.

For example having this struct:

```cs
   [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Ansi, Pack = 1)]
    public struct MyStruct
    {
        int a;
        
        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 5)]
        string b;

        public MyStruct(int a, string b)
        {
            this.a = a;
            this.b = b;
        }
    }
```

To actually convert it to a Span<byte> I have to do:

```cs
        private static Span<byte> CvtStructToSpan<T>(T item) where T : struct
        {
            int rawSize = Marshal.SizeOf(typeof(T));
            IntPtr buffer = Marshal.AllocHGlobal(rawSize);
            Marshal.StructureToPtr(item, buffer, false);
            byte[] rawData = new byte[rawSize];
            Marshal.Copy(buffer, rawData, 0, rawSize);
            Marshal.FreeHGlobal(buffer);
            return rawData;
        }
```

But this is obviously not efficient what about writing in the Span directly?

Something similar to this:

```cs
        private static Span<byte> CvtStructToSpan<T>(T item) where T : struct
        {
            int rawSize = Marshal.SizeOf(typeof(T));
            Span<byte> buffer = stackalloc(rawSize);
            Marshal.StructureToSpan(item, buffer, false);
            return buffer;
        }
```

**Comment by Wraith2** [comment]
The `MarshalAs` attribute on the string field doesn't actually make the string inline. Its an annotation which is handled by the marshalling infrastructure. If you want to see the real memory layout have a look at [this sharplab](https://sharplab.io/#v2:EYLgHgbALANALiATgVwHYB8ACAGABJgRgG4BYAKB3wIDoAlNOASwFsBTagSVTlcQHsADgGVeAN0YBjVgGdSZcpgDM+AEy4AwrgDe5XHvzLCEfFFwBZAIaNUACgCU23fueiLiXM1wBeXKlYB3cwBPITgUCTgbAhVFGAAiQmw4uzlnZy5pAVYI6jNWZj5EIIBxRAsBAAsbZhSnPQBfOtwm/QBtUPC4ABkLIL5kSJ6+gYBpawATahEAR2RWbkYLABsYDQq3EThvNY3WOGoAQVRpRlWABQsJAGttgjsAXSalXGkw5Ajgjve4Jp0yNP0z2sWwsqQBzX+4NalkQ0nWSwO0hsAFVUMwLKgLABzVjjAAqQSy1AAQkEAGrLPEdVZCRgAL1Y6j4xy2PgArA8WoDDAQ8MA5Fy9M8zCE3hEbMDcBZVolcMA7ILHJDwfo4BVGNJqBZtqDFc41RrqMBtvzFY1lbhzfUgA=
). Note that I've put a string longer than the attribute allows, this is because the struct isn't required to obey those rules in any way and only when marshalling will anything check them.

To do what you want you're going to have to layout the struct exactly at you want in memory explicitly and then probably use Unsafe to do type reference trickery.

**Comment by jkotas** [comment]
> pass from a IntPtr that always forces you to do a copy

You example has multiple copies:
- The copy of the struct itself. You can avoid this copy easily by pinning the buffer and passing the pointer to StructureToPtr
- The copy of the string. This copy is not really avoidable as @Wraith2 explained

I do think this would be a good API to add. It does not enable anything new that you cannot do today by writing extra line of code, and having `Span<byte>` for buffer that may need to e.g. have alignment requirements would be misleading.

**Comment by fanoI** [comment]
I don't understand this point: "The MarshalAs attribute on the string field doesn't actually make the string inline", if I print ``rawData`` byte by byte I have an array of 9 bytes with indeed the string inlined: '01'-'00'-'00-'00'-'65'-'65'-'65'-'65'-'00' (a= 1, b = "AAAA").

@jkotas you mean I could pin the internal buffer of the Span itself? Something similar to this will be OK:

```cs
private static unsafe Span<byte> CvtStructToSpan<T>(T item) where T : struct
{
            int rawSize = Marshal.SizeOf(typeof(T));
            Span<byte> buffer = stackalloc(rawSize);

            IntPtr bufferPtr = (IntPtr) buffer;

            Marshal.StructureToSpan(item, bufferPtr, false);
            return buffer;
}
```

That is I've understood that to convert the String to ANSI a copy is unavoidable but that thing that I find really annoying is the fact that I've to use Marshal.AllocHGlobal() and the fact that I've to copy in the byte array.

**Comment by saucecontrol** [comment]
> if I print rawData byte by byte I have an array of 9 bytes with indeed the string inlined

That's only true after you have marshaled a copy of the struct to different memory.  The native storage of the struct consists of an `int` and a pointer to a string. 

> Using a Span will permits to use stack memory to convert the struct to a Span.

You can't return a `Span` to stack memory because that memory is freed when your method returns.

> thing that I find really annoying is the fact that I've to use Marshal.AllocHGlobal() and the fact that I've to copy in the byte array.

You don't have to do that.  You can pin the byte array, marshal a copy into that, and return a `Span` that wraps the byte array.  To rewrite your example, with no `AllocHGlobal` and no second copy:

```C#
private static unsafe Span<byte> CvtStructToSpan<T>(T item) where T : struct
{
    int rawSize = Marshal.SizeOf(typeof(T));
    byte[] buffer = new byte[rawSize];

    fixed (byte* pbuff = &buffer[0])
    {
        Marshal.StructureToPtr(item, (IntPtr)pbuff, false);
    }

    return buffer;
}
```
