### ISSUE TITLE
Writing to frame buffer device on Rpi 3B+  (System.IO.IOException: Invalid argument)

### ISSUE THREAD

**Issue by akacprzak** [dotnet/coreclr#22787]
The issue is that I cannot write data to device frame buffer using File.WriteAllBytes("/dev/fb1", someData);

The function is working when I'm writing to other location for example to /tmp

When i'm using bash helper in dotnet code (writing data from tmp file) it's also working:
```
cat /tmp/test > /dev/fb1
```

I double checked all permission issues (even added user to root group or run dotnet with sudo etc.) and result is the same - I cannot pass/write to /dev/fb1

```
crw-rw---- 1 root video    [...]  fb1
```

Exception info:
```
System.IO.IOException: Invalid argument
   at System.IO.FileStream.CheckFileCall(Int64 result, Boolean ignoreNotSupported)
   at System.IO.FileStream.Init(FileMode mode, FileShare share)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes)
   at System.IO.File.WriteAllBytes(String path, Byte[] bytes)
   at Sense.Led.LedMatrix.SetPixels(Pixels pixels) in SenseHatNet/Sense/Led/LedMatrix.cs:line 146
   at Sense.Led.LedMatrix.ShowMessage(String text) in SenseHatNet/Sense/Led/LedMatrix.cs:line 90
   at led_demo.Program.Main(String[] args) in led_demo/Program.cs:line 55
```

additional exception details:
```
An exception occurred:
Error code: 22
Message: Invalid argument
System.Collections.ListDictionaryInternal
```

I'm using SensHatNet (https://github.com/johannesegger/SenseHatNet) but without docker part.
When using with docker - its working...

**Comment by janvorli** [comment]
My guess is that the issue is caused by the fact that WriteAllBytes creates the target stream with FileMode.Create, which tries to truncate the file if it exists (using the ftruncate native function):
https://github.com/dotnet/corefx/blob/06338637ddb64fa6c80ce3e6b6b3088565f84fff/src/Common/src/CoreLib/System/IO/FileStream.Unix.cs#L108-L113.
As the /dev/fb1 is a special file, I think it doesn't accept the ftruncate call.

If my guess is correct, then the way to fix that would be to modify the SenseHatNet and replace the call to File.WriteAllBytes(path, bytes) by 
```c#
using (FileStream fs = File.Open(path, FileMode.Open))
{
    fs.Write(bytes, 0, bytes.Length);
}
```

**Comment by stephentoub** [comment]
> As the /dev/fb1 is a special file, I think it doesn't accept the ftruncate call.

@janvorli, do you think we should ignore errors from ftruncate here, or potentially just EINVAL?

**Comment by janvorli** [comment]
It seems that it would make sense to ignore EINVAL here. The man page for ftruncate says that EINVAL indicates "The argument length is negative or larger than the maximum file size." Since we are passing in 0, we know that we are not passing argument that's negative or larger than the maximum file size, so it must indicate that the file is special.

**Comment by akacprzak** [comment]
I can confirm that changing code from:
```
File.WriteAllBytes(path, bytes)
```
to:
```
using (FileStream fs = File.Open(path, FileMode.Open))
{
    fs.Write(bytes, 0, bytes.Length);
}
```
is working....thanks for help !!
