### ISSUE TITLE
Audit missing entries in ClrEtwAll.man

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/coreclr#22790]
https://github.com/dotnet/coreclr/pull/22680#discussion_r258028125 - we seem to be missing entries for various flags.

**Comment by vancem** [comment]
We know that the ModuleFlagsMap
```
                    <bitMap name="ModuleFlagsMap">
                        <map value= "0x1" message="$(string.RuntimePublisher.Module.DomainNeutralMapMessage)"/>
                        <map value= "0x2" message="$(string.RuntimePublisher.Module.NativeMapMessage)"/>
                        <map value= "0x4" message="$(string.RuntimePublisher.Module.DynamicMapMessage)"/>
                        <map value= "0x8" message="$(string.RuntimePublisher.Module.ManifestMapMessage)"/>
                    </bitMap>
```
Should be updates so that it includes entries for 0x10, 0x20, 0x40 bits

        None = 0,
        DomainNeutral = 0x1,
        Native = 0x2,
        Dynamic = 0x4,
        Manifest = 0x8,
        IbcOptimized = 0x10,
        ReadyToRunModule = 0x20,
        PartialReadyToRunModule = 0x40,

This is very straightforward.  It is a bit painful because you have to make up names for the strings, but you pretty much just follow the pattern of the other flags.  

@jorive  is this something you could do?

**Comment by jorive** [comment]
@vancem Sure, I'll take it.
