### ISSUE TITLE
Runtime does not emit NativeCode Ids properly on ETW/EventPipe Rundown 

### ISSUE THREAD

**Issue by vancem** [dotnet/coreclr#22908]
During the investigation of issue #22585, I discovered that the run is inconsistent about IDs that it generates that distinguish different versions of  native code for the same method (which you now routinely get with Tiered JITTing).  

As @noahfalk mentions, when Tiered JITTing was added the ReJitID in the Method/LoadVerbose and MethodUnloadVerbose has been changed.  Previously there the only time a method could have two version of the code was if the profiler had updated the IL of the method.   Thus the ReJitID identified both the native and IL version of the method.    However with Tiered JIT, the same IL of a method could have multiple version of native code.   

In the Method/LoadVerbose and MethodUnloadVerbose, the 'ReJitID' field of these events trace the number of NATIVE versions (thus increment for Tiering as well as Profiler IL update).   

Note that there is code in PerfVIew that takes advantage of this new semantic to provide useful views about Tiered JIT.  

However Related methods, done at Rundown (In particular DCStopVerbose) would either be a constant 0 (The only exception to this was when appdomains died),  or it used the IL Version number (that is the number of times the Profiler updated the IL), which is inconsistent with the other Method events.  

Ideally this should be fixed so that the DCStopVerbose uniformly provide the Native version number (thus matching the Method/LoadVerbose and Method/UnloadVerbose events).  

The code that needs updating is in ETW::MethodLog::SendEventsForJitMethodsHelper.    However this rundown method currently has a fGETRejitIDs flag that is typically set to false (which is what forces the id to be 0.  

Note that there is another ILToNativeMapDCStop that should continue to use the IL ID (in its ReJitID field).

Ideally we should rename the ETW field to 'NativeCodeId' where we have changed its meaning.  Whether this is a breaking change is debatable (it would not break PerfView for example).  Having clear nomenclature is important, and frankly it is very unlikely to break people, so we should consider it.  

Finally note that while having the ID field work properly is best, since it has been zeroed out in most cases already, rather than do nothing, simply zeroing it out is better than where we are today (and just changes two lines in ETW::MethodLog::SendEventsForJitMethodsHelper).

**Comment by vancem** [comment]
+ @kouvel

**Comment by noahfalk** [comment]
> Note that there is another ILToNativeMapDCStop that should continue to use the IL ID (in its ReJitID field).

I didn't follow the rationale to put an IL ID there? I'd expect the common case for doing source mapping is that tiered compilation changed the native id while the IL never changed. rejitID = il version in this case means that ETW will see two different mappings per tiered method, each with rejitID=0, but the maps will be incompatible. If the profiler doesn't do something clever to figure out which map goes with which native code body (perhaps proximity of the ILToNativeMap event to a MethodLoad event) then the source mappings are likely to be wrong.

If on the other hand you had an IL rewriting profiler + ETW logging I assume you get valid mappings to an offset in the profiler modified IL, but with no info about how to map profiler modified IL to original IL you still can't map it back to source. I've always assumed ETW source mapping + IL rewriting profiler was  a broken scenario.

The grand 'handle everything case' would probably be to add IL version + native version + some other event that has modified\_il\_to\_original\_il\_map or modified\_il\_to\_source\_map

**Comment by tommcdon** [comment]
@noahfalk feel free to pull this back to 3.0 if this is blocking a mainline scenario

**Comment by noahfalk** [comment]
I think @kouvel will be the right owner for this, he was engaged with various aspects of the Tiered Compilation diagnostic experience.

**Comment by kouvel** [comment]
I'll look into this along with the work for https://github.com/dotnet/coreclr/issues/23221

**Comment by kouvel** [comment]
Thanks for the details @vancem, it helped me quite a bit, I'm new to this stuff.

From what I gathered, it's possible to infer the `NativeCodeID` for the `ILToNativeMapDCStop` event based on the ordering of `DCStopVerbose` and `ILToNativeMapDCStop`. This seems to be what PerfView currently does. When that technique is used, it is necessary that every `ILToNativeMapDCStop` is paired with a `DCStopVerbose`. Because that is currently not happening, it's possible for PerfView to associate tier 0 native to IL maps with tier 1 code or vice versa.

It's not possible to infer the `ILCodeID` from `ILToNativeMapDCStop`. It looks like `PerfView` does not use the `RejitID` from `ILToNativeMapDCStop`. I don't have sufficient information to conclude that it would not be breaking to change the `RejitID` for that event to the `NativeCodeID` (from the perspective of the value, not the naming) instead of the `ILCodeID`. So without further information I'll have to lean towards sending the `ILCodeID` with the `ILToNativeMapDCStop` event.

Perhaps a bit more ideal would be to have `ILToNativeMapDCStop` include both the `ILCodeID` and the `NativeCodeID`. For now though it seems like it would be adequate (without having to introduce a new version of the event unnecessarily) to continue to send the `ILCodeID` with `ILToNativeMapDCStop` because it can't be inferred. Please let me know if you disagree.

**Comment by noahfalk** [comment]
@kouvel - Given that the NativeId is inferable from adjacent events I agree the IL code id seems like a reasoned choice. Thanks for looking into it!

**Comment by tommcdon** [comment]
Thanks @kouvel!
