### ISSUE TITLE
return correct pmask when there are multiple NUMA nodes on linux

### ISSUE THREAD

**Issue by Maoni0** [dotnet/coreclr#22961]
on Linux we need to return the correct pmask when there are multiple NUMA nodes on machines with > 64 cores. discussion is on issue #22861 starting [here](https://github.com/dotnet/coreclr/pull/22861#issuecomment-468807720).

**Comment by janvorli** [comment]
@Maoni0, @vkvenkat I've written a simple testing Linux app that dumps how processors are split to NUMA nodes (using the NUMA library) and what is the current thread affinity by default. Here is the output for my 2 numa node machine. As you can see, Linux doesn't limit the thread affinity to a single numa node like Windows do by default.
```
Numa node 0:
  CPU 0
  CPU 1
  CPU 2
  CPU 3
Numa node 1:
  CPU 4
  CPU 5
  CPU 6
  CPU 7
Current process affinity:
  CPU 0
  CPU 1
  CPU 2
  CPU 3
  CPU 4
  CPU 5
  CPU 6
  CPU 7
```

When using taskset to run my test on processors 2, 3, 4 and 5, I get:
```
Numa node 0:
  CPU 0
  CPU 1
  CPU 2
  CPU 3
Numa node 1:
  CPU 4
  CPU 5
  CPU 6
  CPU 7
Current process affinity:
  CPU 2
  CPU 3
  CPU 4
  CPU 5
```
So again, I can let it be split between two NUMA nodes.

That means that the pmask we are returning on Linux is correct - since by default our process spans multiple numa nodes and according to the GetProcessAffinityMask MSDN doc, we should return 0 in such case.

So it seems we rather need to modify the GCToOSInterface::GetCurrentProcessCpuCount get the number of processors assigned to the process when the pmask is 0 on Unix. 
This number can be obtained from the GetSystemInfo() and updated using PAL_GetCpuLimit().

**Comment by janvorli** [comment]
Actually, the change will be a bit more involved than what I've said above, since we'll need to consider both the limits imposed by cgroups and the taskset.

**Comment by Maoni0** [comment]
sorry, I'm a bit confused. NUMA nodes on the machine @vkvenkat used had on [22861](https://github.com/dotnet/coreclr/pull/22861) spanned a non contiguous # of cores (NUMA0 is 0-23 and 48-71). and when it's set to run on 0-24 which spanned multiple NUMA nodes it did return 25 which is the correct #. so not sure what you meant by "As you can see, Linux doesn't limit the thread affinity to a single numa node like Windows do by default."?

**Comment by janvorli** [comment]
@Maoni0 you have accidentally mixed the windows and linux things here. On Windows, CPUs 0..47 were on  a single NUMA node, thus 0-24 returned CPU count 25 on Windows.
On Linux, CPUs 0-23 and 48-71 are on a single numa node and thus 0-24 returned mask 0 and CPU count 64.

**Comment by vkvenkat** [comment]
@janvorli I tried `GetSystemInfo(&sysInfo)` on Linux and `sysInfo.dwNumberOfProcessors` always returns the total cores on the machine, even when the cores are limited using taskset. So this won't fix the heaps when the cores are limited to 0-24 on Linux. Also `sysInfo.dwActiveProcessorMask` is undefined for Linux. Should we change the behavior of `GetProcessAffinityMask` to mimic Windows & get a non-zero pmask (even though MSDN doc says otherwise)?

**Comment by janvorli** [comment]
> `sysInfo.dwNumberOfProcessors` always returns the total cores on the machine

Yes, that's why I've corrected myself above that the solution would need to be different.

As for changing the GetProcessAffinityMask behavior for Unix, I was hesitant to deviate the behavior from Windows by returning the mask even if it spanned multiple NUMA nodes and wanted to fix the GetCurrentProcessCpuCount instead to reflect the number of CPUs assigned to a process (so that it would reflect the taskset and cgroup limits). However, I've found there are multiple places that use GetProcessAffinityMask and that would benefit from the change you have suggested, so I'll go with that.

**Comment by janvorli** [comment]
Actually, I still have a couple of questions about such solution. My understanding is that GC expects that in case the CPU groups are not enabled, the process is running on a single NUMA node. And the mask returned from the GetProcessAffinityMask matches that based on the tables shared by @vkvenkat in #22861, as the "start /affinity" culls the processor list specified so that only processors from the NUMA node of the first processor specified (?) are used.
However, that's not the case on Linux. As I've already said, the process affinity is set to the list of processors specified by the user without any changes and by default, it spans all the processors on all NUMA nodes.

So I have two options here:
* Return mask representing all processors enabled for the current process (max 64) disregarding their NUMA nodes. 
* Return mask representing only a subset of the processors enabled for the current process (max 64) that belongs to the NUMA node of the first enabled processor.

While the latter would match Windows behavior (as I understand it), it would make GC think the process is running on less processors than it really is. For example, looking at @vkvenkat's tables for Linux, NUMA node0 spans CPUs 0-23,48-71 and  NUMA node1 spans CPUs 24-47,72-95. So the mask would get max 24 bits set and GC would create max 24 heaps. While on Windows on the same machine, we would get max 48 bits set and GC would create max 48 heaps due to the fact that the CPU indexes seem to be remaped from the NUMA level so that each group contains a continuous range of indices. 

It seems that I could possibly emulate it in PAL by adding the same index remapping. The disadvantage of such remapping would be that the CPU indices used by GC would not match the OS CPU indices which could possibly complicate debugging.
And in the case of @vkvenkat's machine, even with the remapping of CPU indices, we would still have only 48 heaps while the process would be running on 96 processors. Or on my machine where I have two NUMA nodes with 4 CPUs each, there would be only 4 heaps while the process would be running on 8 cores.

@Maoni0 what do you think about it from the GC point of view? What is worse - having potentially much less heaps than the actual number of processors executing the process (approx number of CPUs running the process divided by number of NUMA nodes) or returning mask that possibly contains processors from multiple NUMA nodes?
