### ISSUE TITLE
Why not make CLR register-based?

### ISSUE THREAD

**Issue by ygc369** [dotnet/coreclr#2304]
CLR is a kind of Virtual Machine(VM), which is stack-based. I think that register-based VM is more effective, that is why android use it. So why not rewrite CLR to make it register-based?

**Comment by mikedn** [comment]
>  I think that register-based VM is more effective

Why?

> So why not rewrite CLR to make it register-based?

Why rewrite the CLR instead of improving what's already there?

**Comment by ygc369** [comment]
Many tests show that register-based VM is more effective.

**Comment by mikedn** [comment]
> Many tests show that register-based VM is more effective.

Well, show some of those test results here. And be sure that they're not taken out of context.

**Comment by Janiels** [comment]
Changing the VM to be register-based would be an extremely breaking change, considering that all assemblies and the CIL spec right now dictate the stack-based format. It's so breaking that I think this is very unrealistic, regardless of performance differences.

**Comment by canton7** [comment]
Also remember that CIL is not executed directly on a VM. The JIT turns it into (register-based) machine code, which is executed by the CPU. So the question is not "is a stack-based VM more efficient to *run* than a register-based VM?", it's "can a JIT turn a stack-based intermediate language into machine code more efficiently than it can a register-based intermediate language?". My strong suspicion is that no, no it can't.

This would also break so much compatibility that I can't even begin to comprehend it all...

**Comment by mikedn** [comment]
> Also remember that CIL is not executed directly on a VM.

Indeed, that's why I was hoping to see some relevant test results. Register base representation are more likely to help interpreters rather than compilers. This is because register based representations tend to use fewer instructions and thus an interpreter has less work to do.

For compilers the situation isn't as clear cut. A register based representation may make reading the representation faster (for the same reason it helps interpreters) but it may introduce issues in later compilation stages.

Android's VM isn't really representative in this regard, AFAIK it started life as an interpreter. Besides, most Android devices run on ARM and that may help a register based implementation because the number of hardware registers is known in advance.
