### ISSUE TITLE
[Tiered JIT] Possible performance regression with StringBuilder benchmark

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/coreclr#23060]
Following benchmark from the [dotnet/performance](https://github.com/dotnet/performance/blob/600568379660291f92562b6a0bcc37f6973d09f4/src/benchmarks/micro/corefx/System.Runtime/Perf.StringBuilder.cs#L141-L150) repo has most probably exposed a performance regression introduced by Tiered JIT:

```cs
private readonly string _string100 = new string(Enumerable.Repeat('a', 100).ToArray());

[Benchmark]
public StringBuilder AppendMemory()
{
    ReadOnlyMemory<char> memory = _string100.AsMemory();
    StringBuilder builder = new StringBuilder();

    for (int j = 0; j < 1000; j++)
        builder.Append(memory); // Appends a string of length "length" to an increasingly large StringBuilder

    return builder;
}
```

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp3.0 --filter *AppendMemory --dotnet-compilation-mode NoTiering
```

|       Method |     Mean | Gen 0/1k Op | Gen 1/1k Op | Gen 2/1k Op | Allocated Memory/Op |
|------------- |---------:|------------:|------------:|------------:|--------------------:|
| AppendMemory | 39.53 us |     32.1475 |     15.9922 |           - |           198.28 KB |

```cmd
py .\performance\scripts\benchmarks_ci.py -f netcoreapp3.0 --filter *AppendMemory --dotnet-compilation-mode Tiered
```

|       Method |     Mean | Gen 0/1k Op | Gen 1/1k Op | Gen 2/1k Op | Allocated Memory/Op |
|------------- |---------:|------------:|------------:|------------:|--------------------:|
| AppendMemory | 71.41 us |     32.1691 |     15.9314 |           - |           198.28 KB |

@kouvel to my suprise, the benchmark was executed more than 30 times for longer than 100ms during the Pilot stage:

```log
OverheadJitting  1: 1 op, 303100.00 ns, 303.1000 us/op
WorkloadJitting  1: 1 op, 337700.00 ns, 337.7000 us/op

OverheadJitting  2: 16 op, 238000.00 ns, 14.8750 us/op
WorkloadJitting  2: 16 op, 2296500.00 ns, 143.5312 us/op

WorkloadPilot    1: 16 op, 791600.00 ns, 49.4750 us/op
WorkloadPilot    2: 5056 op, 406323900.00 ns, 80.3647 us/op
WorkloadPilot    3: 3120 op, 254337800.00 ns, 81.5185 us/op
WorkloadPilot    4: 3072 op, 237931700.00 ns, 77.4517 us/op
WorkloadPilot    5: 3232 op, 248447600.00 ns, 76.8712 us/op
WorkloadPilot    6: 3264 op, 250983000.00 ns, 76.8943 us/op

WorkloadWarmup   1: 3264 op, 240051800.00 ns, 73.5453 us/op

// BeforeActualRun
WorkloadActual   1: 3264 op, 246424000.00 ns, 75.4975 us/op
WorkloadActual   2: 3264 op, 226364200.00 ns, 69.3518 us/op
WorkloadActual   3: 3264 op, 245537700.00 ns, 75.2260 us/op
WorkloadActual   4: 3264 op, 227831100.00 ns, 69.8012 us/op
WorkloadActual   5: 3264 op, 225822400.00 ns, 69.1858 us/op
WorkloadActual   6: 3264 op, 245149500.00 ns, 75.1071 us/op
WorkloadActual   7: 3264 op, 237240100.00 ns, 72.6839 us/op
WorkloadActual   8: 3264 op, 233381800.00 ns, 71.5018 us/op
WorkloadActual   9: 3264 op, 232428700.00 ns, 71.2098 us/op
WorkloadActual  10: 3264 op, 234195800.00 ns, 71.7512 us/op
WorkloadActual  11: 3264 op, 228846600.00 ns, 70.1123 us/op
WorkloadActual  12: 3264 op, 227919300.00 ns, 69.8282 us/op
WorkloadActual  13: 3264 op, 230796200.00 ns, 70.7096 us/op
WorkloadActual  14: 3264 op, 230353400.00 ns, 70.5740 us/op
WorkloadActual  15: 3264 op, 232992700.00 ns, 71.3826 us/op
WorkloadActual  16: 3264 op, 228328500.00 ns, 69.9536 us/op
WorkloadActual  17: 3264 op, 229133400.00 ns, 70.2002 us/op
```

**Comment by hoyosjs** [comment]
cc @kouvel

**Comment by kouvel** [comment]
The issue only appears when `COMPlus_TC_QuickJitForLoops` is enabled, and it is currently disabled by default.

The difference in profiles the following:

`QuickJitForLoops=0`

Name | Inc % | Inc | Exc % | Exc
-- | -- | -- | -- | --
benchmarkdotnet![QuickJitted]BenchmarkDotNet.Engines.Engine.RunIteration(value class BenchmarkDotNet.Engines.IterationData) | 99.0 | 2,019.072 | 0.0 | 0
\+ 1bcce0f0-7254-4222-939e-76ab832a7665![Optimized]BenchmarkDotNet.Autogenerated.Runnable_0.WorkloadActionUnroll(int64) | 98.4 | 2,007.072 | 0.0 | 1
\+ microbenchmarks![Optimized]System.Tests.Perf_StringBuilder.AppendMemory() | 98.4 | 2,006.072 | 7.5 | 153

`QuickJitForLoops=1`

Name | Inc % | Inc | Exc % | Exc
-- | -- | -- | -- | --
benchmarkdotnet![QuickJitted]BenchmarkDotNet.Engines.Engine.RunIteration(value class BenchmarkDotNet.Engines.IterationData) | 99.0 | 2,567.573 | 0.0 | 0
\+ 3a235c5b-9f8d-445a-bcb5-cfa63d17034b![QuickJitted]BenchmarkDotNet.Autogenerated.Runnable_0.WorkloadActionUnroll(int64) | 98.1 | 2,546.573 | 0.0 | 1
\+ microbenchmarks![OptimizedTier1]System.Tests.Perf_StringBuilder.AppendMemory() | 98.1 | 2,545.573 | 2.9 | 76

When `QuickJitForLoops` is enabled, the second frame is `QuickJitted`. `WorkloadActionUnroll` does not get tiered up very quickly. The test returns the `StringBuilder` instance, and the tier 0 code likely keeps those alive on the stack for longer than necessary, and I see that there is a lot more memory surviving a gen 0 GC and generally more work done during the gen 0 and gen 1 GCs.

Solutions:
- Disable `QuickJitForLoops` (current default)
- It would make sense to add `[MethodImpl(MethodImplOptions.AggressiveOptimization)]` on `WorkloadActionUnroll`
- An easy workaround is to return 'builder.Length` from the test instead of returning `builder`

**Comment by adamsitnik** [comment]
@kouvel thanks for the full explanation!

I can confirm that it's not an issue anymore with latest .NET Core 3.0 previews where QuickJitForLoops is disabled.

**Comment by adamsitnik** [comment]
> It would make sense to add [MethodImpl(MethodImplOptions.AggressiveOptimization)] on WorkloadActionUnroll when targeting netcoreapp3.0

@AndreyAkinshin  this is something we might consider
