### ISSUE TITLE
ILDASM - Not reporting errors

### ISSUE THREAD

**Issue by eli-fin** [dotnet/coreclr#23207]
If you run ildasm on a non-managed binary (like on itself), it will call DumpFile, which will fail when checking g_pPELoader->getCOMHeader().
It then tries to get the error message by calling [RstrUTF(IDS_E_NOCORHDR)](https://github.com/dotnet/coreclr/blob/master/src/ildasm/dasm.cpp#L7315).
This will end up in the switch case inside RstrW, which doesn't seems to handle this case, so an empty buffer is returned and no error is actually printed (this probably happens for all similar errors).

Maybe the [default case](https://github.com/dotnet/coreclr/blob/master/src/ildasm/dasm.cpp#L251) can try to get the error format from the [dasm.rc](https://github.com/dotnet/coreclr/blob/master/src/ildasm/dasm.rc#L145) file?
(or return 'unknown error' if it isn't there)

**Comment by daniel-levin** [comment]
This is not an issue on Linux, as the (conditionally compiled) [PAL branch](https://github.com/dotnet/coreclr/blob/6a6b5b358034ec08e5f2d83a6d561813beb32019/src/ildasm/dasm.cpp#L254) is taken.

I can repro the original issue on Windows. But, running it via the debugger I see that the stack trace is different from the original description. The program bails out earlier than described.

Rather than reaching `getCOMHeader`, ILDASM bails out [here](https://github.com/dotnet/coreclr/blob/6a6b5b358034ec08e5f2d83a6d561813beb32019/src/ildasm/dasm.cpp#L7303). As can be seen from the link, ILDASM reports an `IDS_E_FILEOPEN`, which is also not accounted for in the switch statement.

The root cause is that [`WszLoadString`](https://github.com/dotnet/coreclr/blob/6a6b5b358034ec08e5f2d83a6d561813beb32019/src/ildasm/dasm.cpp#L257) does not populate `buff` with a string when `id=402` is passed to it. @RussKeldorph can you point us to potential reasons why?

**Comment by elif-checkmarx** [comment]
Didn't get a chance further investigate.
Is this also the reason why no help message is shown when starting it with no args (or with '/?')?

**Comment by elif-checkmarx** [comment]
Didn't get a chance further investigate.
Is this also the reason why no help message is shown when starting it with no args (or with '/?')?

**Comment by eli-fin** [comment]
Didn't get a chance further investigate.
Is this also the reason why no help message is shown when starting it with no args (or with '/?')?

**Comment by daniel-levin** [comment]
@eli-fin Yes, I believe so.

ILDASM tries to load string resources from `ildasmrc.dll`. The problem persists even if one puts a copy of this dll in the same directory as `ildasm.exe`.

**Comment by jlanng** [comment]
I've just had a look at this and it now seems to be fixed. @eli-fin can you confirm this is working for you now?

**Comment by eli-fin** [comment]
@jlanng Yep. looks like its working now. Closing the issue
