### ISSUE TITLE
Optimization: Unify construction of empty arrays

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/coreclr#23382]
As an optimization, the JIT could optimize the `newarr` instruction such that `new T[0]` returns the singleton `Array.Empty<T>()` rather than allocating a new empty instance.

**Comment by jkotas** [comment]
This was considered when `Array.Empty<T>()` was introduced. We have decided against it because of it is breaking change (violates spec - the spec says that the newarr instruction creates new array) and it is not always win.

**Comment by GrabYourPitchforks** [comment]
The spec also says that `newobj` always creates a new object, and we already violate this with `String`. :)

```cs
Console.WriteLine(ReferenceEquals(new string(new char[0]), new string(new char[0]))); // prints "True"
```

Surprised it's not always a win. I'd have thought this would be a cheap check to implement, but there must be something I'm not considering.

**Comment by jkotas** [comment]
>  we already violate this with String

Yes, this violation has been there since forever that makes it hard to justify that doing this for arrays is fine too.

> Surprised it's not always a win

For example, we intentionally not use `Array.Empty` in `List<T>`: https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/shared/System/Collections/Generic/List.cs#L30 . Doing so leads to significant regressions in `List<T>` benchmarks.

The problem is not with the check. The problem is cost associated with the singleton (the singleton storage and the singleton access).
