### ISSUE TITLE
[arm64] System.Runtime.Tests crash

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#23444]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_ubuntu16.04_corefx_baseline_tst/144/

**Log:**
```
lldb was not found. Unable to print core file.
Copying core file core to /tmp/coredumps/core.12094 in case you need it.
error: One or more tests failed while running tests from ''.  Exit code 134.
```

**Comment by BruceForstall** [comment]
Actual failure was System.Runtime.Tests:
```
04:20:30 CLR: Managed code called FailFast, saying "Cannot report OperationStatus.Done if we haven't consumed the entire input buffer.
04:20:30 
04:20:30    at System.Text.Unicode.Utf8.FromUtf16(ReadOnlySpan`1 source, Span`1 destination, Int32& numCharsRead, Int32& numBytesWritten, Boolean replaceInvalidSequences, Boolean isFinalBlock)
04:20:30    at System.Text.Unicode.Tests.Utf8Tests.ToBytes_Test_Core(ReadOnlySpan`1 utf16Input, Int32 destinationSize, Boolean replaceInvalidSequences, Boolean isFinalChunk, OperationStatus expectedOperationStatus, Int32 expectedNumCharsRead, ReadOnlySpan`1 expectedUtf8Transcoding) in /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline/_/fx/src/System.Runtime/tests/System/Text/Unicode/Utf8Tests.ToBytes.netcoreapp.cs:line 246
04:20:30    at System.Text.Unicode.Tests.Utf8Tests.ToBytes_WithSmallValidBuffers(String utf16Input, String expectedUtf8TranscodingHex) in /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline/_/fx/src/System.Runtime/tests/System/Text/Unicode/Utf8Tests.ToBytes.netcoreapp.cs:line 33
```

**Comment by BruceForstall** [comment]
@sandreenko looks like System.Runtime.Tests is not error free?

**Comment by BruceForstall** [comment]
@tannergooding Didn't you add the core dumping (back)? Is it expected to complain about missing lldb even if it dumped the core stacks with gdb? I guess we don't have lldb installed on the Linux arm64 CI machines.

**Comment by tannergooding** [comment]
@BruceForstall, yes. I enabled most of the core dumping support back in: https://github.com/dotnet/coreclr/pull/21149.

Grepping the code, it looks like this is being emitted from `bringup_runtest.sh` and is what the `runtest.py` changes were based on. I'm actually not sure why this is printing since `bringup_runtest.sh` is meant to skip these code-paths on ARM64: (https://github.com/dotnet/coreclr/blob/master/tests/bringup_runtest.sh#L723).
* `runtest.py` doesn't have the same limitation, but prints a different error message
* Linux is meant to use `gdb` on both (runtest.py and bringup_runtest.sh) since it should always be available and allows you to get more information

**Comment by sandreenko** [comment]
> @sandreenko looks like System.Runtime.Tests is not error free?

Probably, before it was excluded because of another issue that was fixed.

**Comment by sandreenko** [comment]
Wow, that works with release CoreCLR and fails with checked, intresting.
