### ISSUE TITLE
Dynamically Loading .NET Core Assemblies

### ISSUE THREAD

**Issue by RehanSaeed** [dotnet/coreclr#23757]
I've published an ASP.NET Core project to a folder and I'm trying to dynamically load the assembly containing the ASP.NET Core `Startup` class. I then want to instantiate the `Startup` class and hand it over to the `TestHost` API, so I can start the site in memory. I've written the following code:

```c#
    var directoryPath = @"C:\Dlls";
    var assemblyFilePath = Path.Combine(directoryPath, "Foo.dll");
    var assemblyName = AssemblyLoadContext.GetAssemblyName(assemblyFilePath);
    var assembly = new AssemblyLoader(directoryPath).LoadFromAssemblyName(assemblyName);
    var startupType = assembly.ExportedTypes
        .FirstOrDefault(x => string.Equals(x.Name, "Startup"));
    var webHostBuilder = new WebHostBuilder()
        .UseStartup(startupType)
        .UseUrls(new string[] { "http://localhost" });
    using (var testServer = new TestServer(webHostBuilder))
    {
        var response = testServer.CreateClient().GetAsync("/");
    }

    public class AssemblyLoader : AssemblyLoadContext
    {
        private readonly string directoryPath;

        public AssemblyLoader(string directoryPath) =>
            this.directoryPath = directoryPath;

        protected override Assembly Load(AssemblyName assemblyName)
        {
            var dependencyContext = DependencyContext.Default;
            var compilationLibraries = dependencyContext
                .CompileLibraries
                .Where(x => x.Name.Contains(assemblyName.Name))
                .ToList();
            if (compilationLibraries.Count > 0)
            {
                return Assembly.Load(new AssemblyName(compilationLibraries.First().Name));
            }
            else
            {
                var file = new FileInfo($"{this.directoryPath}{Path.DirectorySeparatorChar}{assemblyName.Name}.dll");
                if (File.Exists(file.FullName))
                {
                    var asemblyLoader = new AssemblyLoader(file.DirectoryName);
                    return asemblyLoader.LoadFromAssemblyPath(file.FullName);
                }
            }

            return Assembly.Load(assemblyName);
        }
    }
```

This works when I publish the app as a self contained application, however, I'd like to avoid dealing with runtime identifiers (RID's) if possible. When I publish normally the code throws a `TypeLoadException` when `assembly.ExportedTypes` is called. The full stack trace:

```
System.TypeLoadException occurred
  HResult=0x80131522
  Message=Method 'ConfigureServices' in type 'Foo.Startup' from assembly 'Foo, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
  Source=<Cannot evaluate the exceptionsource>
  StackTrace:    at
   System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)    at
    System.Reflection.RuntimeAssembly.GetExportedTypes()
```

How can I dynamically load the .NET Core runtime in the `AssemblyLoader` class? [Related StackOverflow question](https://stackoverflow.com/questions/44545544/dynamically-loading-an-asp-net-core-assembly).

[EDIT] @karelz changes: formatting code with c# syntax (\`\`\`c#) and stack trace in \`\`\` block.

**Comment by sdmaclea** [comment]
There are a set of known issues for .NET Core 2.x
* Minimal `AssemblyLoadContext` documentation
* No way to unload an `AssemblyLoadContext`
* It was very difficult to know how to locate dependencies for dynamically loaded assemblies
* It was difficult to figure out how things were loaded.
* The default assembly resolvers for Type.GetType, Assembly.GetType, Activator.CreateInstance loaded types in AssemblyLoadContext.Default instead of the immediate caller (or its effective caller)

There is a lot of work going into assembly loading and isolation toward the .NET Core 3.0 release. It has resulted in fixes for most of these issues.

See 
* [AssemblyLoadContext API docs](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.loader.assemblyloadcontext?view=netcore-3.0)
* [Unloadability](https://github.com/dotnet/coreclr/blob/master/Documentation/design-docs/unloadability.md)
* [AssemblyDepencencyResolver](https://github.com/dotnet/corefx/issues/33165)
* [AssemblyLoadContext extensions](https://github.com/dotnet/corefx/issues/34791)
* [AssemblyLoadContext Contextual Reflection extension](https://github.com/dotnet/corefx/issues/36236)

The work is implemented in the daily .NET Core builds.  Some is present in `preview4`, the rest should be present in the `preview5` release.

**Comment by sdmaclea** [comment]
@shvez @RehanSaeed @JianpingLiu0225 @masums @1iveowl @simbi 
Please take a look at the AssemblyDependencyReolver sample code mentioned above.

I am closing this conglomeration of related issues. It has too many related issues to fully resolve anyone's particular issue. Please feel free to open new issues if they still need to be discussed.

**Comment by shvez** [comment]
@sdmaclea Thanks a lot for the detailed answer. I very appreciate your help. Will check new builds
