### ISSUE TITLE
Inconsistent in ExecutionContext.Run(...) between CoreClr and Clr

### ISSUE THREAD

**Issue by dopare** [dotnet/coreclr#2384]
I got a tiny DNX (1.0.0-rc1-update1 runtime) based console application listed bellow :

```
using System;
using System.Threading;

namespace ConsoleApp1
{
   public class MySyncContext : SynchronizationContext
   {
      public override void Post(SendOrPostCallback d, object state)
      {
         Console.WriteLine(state);
         base.Post(d, state);
      }
   }

   public class Program
   {
       public static void Main(string[] args)
       {
           var sc = new MySyncContext();

           SynchronizationContext.SetSynchronizationContext(sc);

           SynchronizationContext.Current.Post((c) => { }, "hello from main method");

           var context = ExecutionContext.Capture();

           ExecutionContext.Run(context, (s) =>
           {
               SynchronizationContext.Current.Post((c) => { }, "hello from execution run method");
           }, null);
       }
   }
}
```

On full CLR application prints out
 
```
hello from main method
```

On CoreCLR application prints out
```
hello from main method
hello from execution run method
```

**Comment by kouvel** [comment]
It looks like ExecutionContext has a different, simpler implementation in CoreCLR. In CoreCLR, the synchronization context is not captured by ExecutionContext.Capture(). ExecutionContext.Run() seems to capture the synchronization context only for the purpose of restoring it before returning, to undo any changes to the synchronization context during the callback.

@ericeil, is this the expected behavior?

**Comment by ericeil** [comment]
Yes, this is by design.  Note that even in the full CLR, *most* uses of ExecutionContext do not capture/restore the SynchronizationContext, as the Framework itself disables this via private flags in all of its own uses of ExecutionContext.  The hope is that we can keep the CoreCLR implementation of this much simpler, and faster, than the full CLR.

@dopare, is this issue motivated by a real problem this difference has created for you?

**Comment by dopare** [comment]
This example was just for testing purpose. I know that internally full framework is not dealing with SynchronizationContext. But the result of test was a surprise and I just issued it. So if it is by design, I'll close this issue. Are there any documentations about such parts of framework that differ between full and core framework?

**Comment by kouvel** [comment]
@dopare, unfortunately, I'm not aware of any document that outlines the differences between the two.
