### ISSUE TITLE
Loss of `CGroup::GetCpuLimit` in GC

### ISSUE THREAD

**Issue by luhenry** [dotnet/coreclr#23951]
With https://github.com/dotnet/coreclr/pull/23537, we removed the capability to rely on the various `--cpus*` options passed to Docker (https://github.com/dotnet/coreclr/pull/23537/files#diff-884426ee59a5c24ed71672ecde49b06cL556).

This impacts our ability to scale the GC in cases where the machine has lots of processors but the docker is only given a small limit (`--cpus=0.5` for example).

If we decide that it is not worth it, it means we can remove the various uses of `CGroup::GetCpuLimit` in `src/gc/unix/cgroup.cpp` and `src/gc/unix/gcenv.unix.cpp`.

@janvorli could you please post the various benchmarks you have run, with the configurations and the results?

/cc @Maoni0 @sergiy-k

**Comment by janvorli** [comment]
The removal was not intentional. It happened accidentally during the refactorings of the GC code I've made during last two weeks. First, it happened in the unix version of the standalone GC and then it got propagated into the embedded version of GC.
When @luhenry asked me about the change, I wanted to measure the performance implications as he wasn't sure if he has tested the change in the GC and the rest of the runtime separately. He has kindly provided me with access to his testing VM and I have ran tests with the coreclr from the current master and a coreclr with the CPU count limitations for GC added back. I've ran the aspnet benchmarks with 4, 2, 1 and 0.5 CPU limits set on the container. I've ran the test suite for each case four times to see the amount of measurement noise too.
Here are the results I got:

|CPU limits |Current master | Current master with added limit|
|------------|-----------------|------------------------------------|
|4 CPUs RequestsPerSecond: | 1,388,248  1,411,274   1,420,310  1,413,421 | 1,388,724  1,360,094  1,352,725  1,326,625 |
|2 CPUs RequestsPerSecond: | 750,348    756,080     750,705    787,339 |  741,202    744,832    727,046    744,610 |
|1 CPU RequestsPerSecond: | 367,340    379,500     373,349    362,428 |  344,538    359,449    358,965    368,919 |
|0.5 CPU RequestsPerSecond: | 155,569    160,187     160,077    165,711 |  164,076    174,755    177,770    174,832 |

The results seem to indicate that for >= 1 CPUs, adding the limit resulted in about 3 to 3.8% performance degradation. For 0.5 CPU, it  shows 7.8% improvement.

However, as you can see, the measured values vary in a significant way between consecutive runs for the same configuration. And I've also hit a case when the 1 CPU case on the current master was getting around 340,000 requests per second in multiple consecutive runs. I've restarted the server process and waited for a bit and the results went back to the 370000+ range. So I have doubts about these results. Since it was running in a VM, it is possible that the host machine was running some CPU intense code at some points.

So I am going to try to validate the results on a Linux physical box.

**Comment by sergiy-k** [comment]
Would it even be possible to fix https://github.com/dotnet/coreclr/issues/23949 without fixing this issues and restoring the original functionality (i.e. when GC was aware of CPU quota)?

**Comment by janvorli** [comment]
Running the test on my physical Linux box shows the same level of noise in the measured values, so it was not caused by the VM. 
Based on @sergiy-k's suggestion, I've also added memory limit to the docker container in which the server part of the benchmark runs with swapfile turned off for the container. I've tried 512MB memory limit and the tests were passing with the same performance as without any limit. Then I've tried to use 256MB memory limit and the test infrastructure was failing even before the benchmark could be launched. Similar thing happened for 384MB limit, it just failed a bit later during the tests initialization.

I have then tried to measure the performance on my 10 core (20 with HT) Core I9 machine. The larger number of cores had a much larger effect on the performace differences. When I have added back applying the CPU limit to the GC code to the current master and compared it to the same master without these, the version with the CPU limit applied was clearly peforming better, the gain growing as the limit gets smaller:

| CPU limit | RPS without the limit applied | RPS with the limit applied | Perc gain |
|------------|---------------------------------|------------------------------|-----------|
| 4 | 1,465,029 | 1,469,895 | 0.3 |
| 2 | 746,595 | 764,740 | 2.4 |
| 1 | 366,646 | 392,054 | 6.9 |
| 0.5 | 155,087 | 183,489 | 18.3 |
| 0.1 | 19,145 | 27,107 | 41.6 |

So this clearly confirms that we need to add the CPU limiting to the GC.
