### ISSUE TITLE
[question] choosing between class and struct

### ISSUE THREAD

**Issue by caozhiyuan** [dotnet/coreclr#23960]
here has a docment write in 2008 :
https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/choosing-between-class-and-struct

it suggest ：
X AVOID defining a struct unless the type has all of the following characteristics:
It logically represents a single value, similar to primitive types (int, double, etc.).
It has an instance size under 16 bytes.
It is immutable.
It will not have to be boxed frequently.

now . in net core ,suggest instance size under xx bytes changed ? i seems remeber under 40 bytes. 

@jkotas help , thanks.

**Comment by jkotas** [comment]
These are general guidelines. They are not hard rules. "AVOID" means recomendation that does not have to be followed 100% of the time.

16 bytes is a good general number for 32-bit platforms. A good number for 64-bit platforms may be a bit higher, say 24 bytes.

There has been a lot of experiments and interest to use much larger structs to avoid GC heap allocations recently. It typically comes with number of usability issues and it does not even always improve performance unless you are very careful (shift the GC heap allocation costs somewhere else). It is not a good design pattern for mainstream APIs. For example, the new .NET Core 3.0 Utf8JsonReader/Utf8JsonWriter has been designed around large structs and we are considering redesigning it now because of we are not happy it as a mainstream public API.

**Comment by caozhiyuan** [comment]
@jkotas  thanks , Utf8JsonReader/Utf8JsonWriter(ref struct) is stack allocated , may be ok.

**Comment by jzabroski** [comment]
@jkotas I think the basic observation tucked in this question stands : the document https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/choosing-between-class-and-struct should be refreshed with context around the recommendation. Proof by authority is no way to engineer.

**Comment by jkotas** [comment]
@mairaw I do not see the edit button on https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/choosing-between-class-and-struct. Is it possible to edit it, or is the editing disallowed since it is a reprint?

**Comment by mairaw** [comment]
Yes, disallowed by design because of copyright. We need to come up with our own guidelines if we don't want to use that content.

**Comment by jzabroski** [comment]
My ideal vision would be a document that describes current best practices as well as possibly an area for people to document exceptions, and then those exceptions raise awareness for stronger ways of thinking about what APIs we need as engineers to crush Rust in the TechEmpower  benchmark, and just generally write efficient systems with .NET
