### ISSUE TITLE
Inconsistency in RuntimeMethodHandle.InvokeMethod

### ISSUE THREAD

**Issue by EgorBo** [dotnet/coreclr#24087]
As far as I understand all exceptions happened in methods/properties called via reflection should be wrapped with `TargetInvocationException` unless `BindingFlags.DoNotWrapExceptions` is specified.

```csharp
using System;

public class Program
{
    static void Main(string[] args)
    {
        // 1) throws NullReferenceException:
        typeof(Program).GetMethod("NullRef1").Invoke(new Program(), null);

        // 2) throws TargetInvocationException:
        typeof(Program).GetMethod("NullRef2").Invoke(new Program(), null);
    }

    public unsafe ref object NullRef1()
    {
        return ref Unsafe.AsRef<object>((void*) null);
    }

    public unsafe object NullRef2()
    {
        return Unsafe.AsRef<object>((void*) null);
    }
}
```

For two similar cases here InvokeMethod throws different exceptions - is it by design?
I suspect it happens here: https://github.com/dotnet/coreclr/blob/master/src/vm/reflectioninvocation.cpp#L1353

**Comment by filipnavara** [comment]
It is by design, the decision was discussed in https://github.com/dotnet/corefx/issues/15960 and implemented by https://github.com/dotnet/coreclr/pull/17639.

`BindingFlags.DoNotWrapExceptions` affects exceptions thrown by the called method, not exceptions happening as part of the special marshalling behaviour here. The difference makes it possible to distinguish between the ref-returning method causing NRE inside its code and returning null in the return value.

**Comment by MichalStrehovsky** [comment]
*Thank you*. If you read the linked issue, I predicted that people will consider this a confusing behavior a bug and will file it as such.

Cc @VSadov

**Comment by marek-safar** [comment]
To me this should have implications to features like #nullable. I am not sure how we mark static methods throwing NRE as it'd feels little bit weird to have #nullable safe code and receive NRE.

/cc @stephentoub

**Comment by stephentoub** [comment]
> as it'd feels little bit weird to have #nullable safe code and receive NRE.

The nullability feature is far from 100% validating.  You can have methods accepting nullable arguments that throw when null is passed in, and you can have methods return non-nullable types but that end up returning null.  The whole feature is there as an attempt to reduce argument null exceptions and null reference exceptions, but it doesn't eliminate them entirely.

For reflection, InvokeMethod has to be defined where all of the reference types, input and output, are nullable, because it may be used with a method that accepts nulls and may be used with a method that returns nulls.  In other words, we have to define the nullability annotations for InvokeMethod to be as permissive as possible, because it might be used with such a permissive method.  For arguments, obviously that means the compiler won't warn about nulls being passed in, even if the method invoked via reflection can't handle it.
