### ISSUE TITLE
Allow default values in many "Out-Var" scenarios

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/coreclr#24243]
Hi CoreCLR team,
This is related to this C# feature request:
https://github.com/dotnet/csharplang/issues/1033#issuecomment-486524391

Currently, today I can write code like this:
````
if(int.TryParse(data, out var Number)){
  ...
} else {
 Number = -1;
}
````

However, this is clunky as I have to have an additional leg on my IF statement and it obfusicates that my intent is "I want -1 to be the default value for Number".

Instead, I would like to be able to write code like this:
````
if(int.TryParse(data, out var Number = -1)){
  ...
}
````

In order to accomplish that, a few changes need to be made to both C# and the CoreCLR.
1.  Out parameters should be evaluated to see if it makes sense for them to be converted to ref parameters.
2.  "out var..." should also be able to instantiate "ref var" parameters.

With .NET Core 3.0 actively being worked on, now would be a great time to bring in this small change that would have a great quality of life improvement.

**Comment by svick** [comment]
I don't understand, what exactly is the CLR change that you're proposing? If you're suggesting that the signature and implementation of methods like `int.TryParse` should be changed, then:

1. Any proposals to change the API should be made in the corefx repo, following [the API review process](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md) (even though coreclr also has a copy of the relevant source code).
2. It's not clear to me how such a change could be made without a breaking change.
3. Since the changes to methods you seem to be proposing are fairly simple and can be done after the C# feature already exists, I don't see a reason for this discussion now. If the C# feature was accepted, only then would an issue like this one make sense to me.

**Comment by mikedn** [comment]
This doesn't make sense. An `out` parameter is actually a `ref` parameter so the callee can assign any value to that variable, overwriting the default value you provide. And since it is `out` the callee is actually required to assign a value so it's not like you can change `int.TryParse` to prevent it from doing that.

The only this can be done is if the C# compiler rewrites the code such that a temporary variable is created and passed to `TryParse`. That may be another can of worms. But in any case it's up to the C# compiler to implement such semantics.

It is what it is, `TryParse` was never a flexible style and the addition of `var out` is more a band-aid than a comprehensive fix.

**Comment by jkotas** [comment]
Nothing actionable for CoreCLR in this issue.
