### ISSUE TITLE
Legacy behavior in Array.GetValue (InternalGetReference)

### ISSUE THREAD

**Issue by EgorBo** [dotnet/coreclr#24324]
Currently in CoreCLR it's not allowed to use `Array.GetValue` for arrays of pointers, e.g.:
```
int*[] array = new int*[2] {null, null};
object value = array.GetValue(0);
```
throws `NotSupportedException` (from [here](https://github.com/dotnet/coreclr/blob/d3e39bc2f81e3dbf9e4b96347f62b49d8700336c/src/classlibnative/bcltype/arraynative.cpp#L1286-L1296)).
Is it important to keep this legacy behavior? Do I need to throw it from Mono as well? (currently it allows pointers). 

There is a COREFX test for this legacy behavior 

/cc @marek-safar @jkotas

**Comment by iskiselev** [comment]
I believe that pointers are non-boxable types per ECMA-355 (so, they don't have object in their type hierarchy).

**Comment by EgorBo** [comment]
@iskiselev 
```
object obj = Pointer.Box(null, typeof(int*));
```
works for me 🙂

**Comment by EgorBo** [comment]
Btw, https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/shared/System/Array.cs#L935-L946
this code doesn't check for IsPointer so if CORECLR is not defined - it's ok with pointers

**Comment by MeiChin-Tsai** [comment]
@davidwrighton can you answer the question?

**Comment by iskiselev** [comment]
Pointer.Box is special method that creates managed wrapper (Pointer class) around pointer instance. I believe this class just has void* filed inside. It is required, because it is illegal to use IL box instruction with pointer type.
Attempt to cast pointer array to object array is also not supported now - it will throw InvalidCastException (see next example):
```c#
int*[] pointers = new int*[10];
var objs = (object[])(Array)pointers;
```

Though it may be possible to return Pointer wrapper from Array.GetValue if it will be documented, but will it be expected?

**Comment by jkotas** [comment]
@EgorBo What does Mono return for this case?

**Comment by EgorBo** [comment]
@jkotas turns out it happens in a different place: https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/shared/System/Array.cs#L935 Mono successfully casts `(object[])(Array)arrayOfIntPointers` and goes that way without exceptions. So I guess it's our internal issue
