### ISSUE TITLE
Assertion failed '!foundDiff'

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#24336]
Windows/arm64 altjit PMI asm diffs run on Windows/x64 using
```
call jit-diff diff --pmi --diff --base --base_root f:\gh\coreclr12 --arch x64 --build Checked --altjit protononjit.dll --corelib
```

gives:

```
Assert failure(PID 12276 [0x00002ff4], Thread: 12000 [0x2ee0]): Assertion failed '!foundDiff' in 'System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1[Vector`1][System.Numerics.Vector`1[System.Single]]:get_Task():struct:this' (IL size 44)
    File: f:\gh\coreclr10\src\jit\lsra.cpp Line: 2146
    Image: F:\gh\coreclr10\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\corerun.exe
```

**Comment by CarolEidt** [comment]
In working on this, I was curious why this wasn't showing up on x86/x64. As it happens, it will also happen there if you set `COMPlus_SIMD16ByteOnly=1`. The only reason it's not happening is that `TYP_SIMD32` fields won't be promoted if they're not on a 32-byte-aligned offset. I filed #24368, though naturally we wouldn't want to support that until this bug is fixed!
