### ISSUE TITLE
ADO PR testing doesn't work

### ISSUE THREAD

**Issue by sandreenko** [dotnet/coreclr#24416]
PRs are failing with:
`/eng/xplat-job.yml: Could not find /eng/common/templates/job/job.yml in repository self hosted on https://api.github.com using commit c685636c1acc35f635f1415e922795475173515f. GitHub reported the error, "Not Found"`
before they start running any testing.
Examples: https://github.com/dotnet/coreclr/pull/24415, https://github.com/dotnet/coreclr/pull/24411, it has begun today.

PTAL @BruceForstall @RussKeldorph  @dotnet/dnceng 

I did not see any releted changes in our repo today/yerstaday (for example /eng/common/templates/job/job.yml still exists). Maybe it should be moved to core-eng repo.

**Comment by MattGal** [comment]
This is tracked on our side by https://github.com/dotnet/core-eng/issues/5800 ;  there isn't much we can do here because it's about the communication between Azure Dev Ops and GitHub, where GitHub is taking slightly too long to replicate information about PR branches.  Luck and retries should get you past it; thus far there hasn't been any change in the problem
