### ISSUE TITLE
Question on AssemblyLoadContext Proposal

### ISSUE THREAD

**Issue by dazinator** [dotnet/coreclr#24445]
I'm referring to this proposal: https://github.com/dotnet/coreclr/blob/master/Documentation/design-docs/AssemblyLoadContext.ContextualReflection.md

The propose mechanism suggests that if an assembly cannot be loaded from the ALC set as the "current" context, then it would fallback to AssemblyLoadContext.Default.

May I suggest that it falls back to the predecessor ALC to enable patterns such as this:

```
var alc1 = AssemblyLoadContext.Default
var alc2 = new AssemblyLoadContext();
var alc3 = new AssemblyLoadContext();

Using (var globalScope = alc1.EnterScope())
{
  Using (var commonScope = alc2.EnterScope())
  {
    Using (var vendorScope = alc3.EnterScope())
  {
  
   }
  }
}
```
In this situation, if assemblies cannot be resolved from the current scope they fallback for resolution from predecessor scope making it possible to define a hierarchy.

**Comment by jkotas** [comment]
cc @sdmaclea

**Comment by sdmaclea** [comment]
Each `AssemblyLoadContext` acts as an `Assembly` cache.  This requires certain constraints. The result of looking up in a given AssemblyLoadContext must always return the same `Assembly`, so that it can be effectively cached.

The `AssemblyLoadContext` cache effectively needs to include the Assemblies it loaded and those Assemblies' references (even if they are not from the same `AssemblyLoadContext`).  **Therefore** the fallback order for a given AssemblyLoadContext should be established at `AssemblyLoadContext` construction.

Normal code could accomplish what you desire by overriding the `AssemblyLoadContext.Load()` method.  Something like

```C#
public class ChildAssemblyLoadContext : AssemblyLoadContext
{
    private AssemblyLoadContext? _parent;
    public ChildAssemblyLoadContext(string name, AssemblyLoadContext parent) : base(name)
    {
        if (parent != AssemblyLoadContext.Default)
        {
            _parent = parent;
        }
    }
    public override Assembly? Load(AssemblyName assemblyName)
    {
        // Look here
        ....
        // Fallback to parent
        return ParentLoad(assemblyName);
    }
    public override Assembly? ParentLoad(AssemblyName assemblyName)
    {
        if (_parent)
        {
            try
            {
                return _parent.LoadFromAssemblyName(assemblyName);
            }
            catch
            {
            }
        }
        return null;
    }
}
```

@dazinator The behavior you suggested could be accomplished by modifying constructor above to something like:
```C#
    public ChildAssemblyLoadContext(string name, AssemblyLoadContext parent) : base(name)
    {
        _parent = AssemblyLoadContext.CurrentContextualReflectionContext;
        if (parent != null && parent != AssemblyLoadContext.Default)
        {
            _parent = parent;
        }
    }
```
