### ISSUE TITLE
[EventPipe] Events missing when circularBufferMB set to a large value

### ISSUE THREAD

**Issue by jiangzeng01** [dotnet/coreclr#24491]
Test:
coreclr\tests\src\tracing\eventsource\eventsourcetrace\EventSourceTrace.cs
Line 33:
Set circularBufferMB = 1024000

Actual: 17 events
Expected: 10000 events

**Comment by tommcdon** [comment]
@cshung please investigate.  Possible duplicate to #24470 and #24468

**Comment by jorive** [comment]
Is this an `EventPipe` or `EventSource` issue?

**Comment by sywhang** [comment]
@jorive It strongly feels like an `EventPipe` issue.

@jiangzeng01 Did you run this under x64 or x86? If you're running in x86 I think it's possible that we're getting an integer overflow for the size of buffer that `EventPipeBufferManager` uses because size_t is 32 bit on x86, which would limit the max size to 4GB. 

If you ran it on x64 this may be pointing at a bigger issue. I'll try to repro and see what it might be.

**Comment by jorive** [comment]
Does the test pass when using ETW?

**Comment by jiangzeng01** [comment]
@sywhang I ran  this under a x64  windows machine by following commands, it should against x64:
1. build
2. set CORE_ROOT=F:\TempRepo\coreclr\bin\tests\Windows_NT.x64.Debug\Tests\Core_Root
3. Edit the test 
4. msbuild tests\src\tracing\eventsource\eventsourcetrace\eventsourcetrace.csproj
5. bin\tests\**Windows_NT.x64.Debug**\tracing\eventsource\eventsourcetrace\eventsourcetrace\eventsourcetrace.cmd

Please let me know if anything was wrong for the above steps.

**Comment by sywhang** [comment]
Thanks @jiangzeng01 . I was able to repro this. I'll be sending out a PR that fix this shortly.

**Comment by sywhang** [comment]
Should be fixed with https://github.com/dotnet/coreclr/pull/24512.
