### ISSUE TITLE
Please provide a kind of lightweight finalizer

### ISSUE THREAD

**Issue by ygc369** [dotnet/coreclr#2470]
The lightweight finalizer of an object should be executed in GC thread when GC find the object is garbage. After that, the object should be collected at once, no need to wait for next GC. Of course, object resurrection is forbidden in lightweight finalizer. The lightweight finalizer is usually useful for statistics purpose and would not delay GC. 
For example:
class test
{
    private static int count=0;
    public int a;
    public test()
    {
        count++;
    }
    lightweight ~test()
    {
        count--;
    }
    public static int GetCount()
    {
        return count;
    }
}

**Comment by ygc369** [comment]
Another idea: https://github.com/dotnet/coreclr/issues/1856

**Comment by whoisj** [comment]
Executing something as the GC is dangerous for many reasons. How should the GC handle a NRE for example?

**Comment by ygc369** [comment]
@whoisj 
What is NRE?

**Comment by jasonwilliams200OK** [comment]
NRE = NullReferenceException

**Comment by Joe4evr** [comment]
You've already commented in #430, isn't this just basically the same thing?

**Comment by ygc369** [comment]
@Joe4evr 
Not the same

**Comment by OtherCrashOverride** [comment]
It presents the exact same issues as #430.  The compiler does not insert destructor (dtor) calls when a variable goes out of scope.  Instead, the pattern is ``IDisposable`` and the "using" keyword in C#.  This allows you to manually scope a variable and prevent the finalizer from running (``CG.SuppressFinalizer()``).  However, the GC still has to run to know if an object is garbage or not since it has to do tracing.

Converting the example given in OP to use IDisposable is the current solution to this. See http://stackoverflow.com/questions/151051/when-should-i-use-gc-suppressfinalize

```
public class Test : IDisposable
{
    static int count=0;

    bool disposed = false;
    int a;


   public Test()
   {
       count++;
   }

    ~Test()
    {
        Dispose(false);
    }


    protected virtual void Dispose(bool disposing)
    {
        if (!disposed)
        {
            if (disposing)
            {
                // called via Dispose().
            }

            count--;
            disposed = true;
        }
    }

    public void Dispose() // Implement IDisposable
    {
        Dispose(true);
        GC.SuppressFinalize(this);
    }
}
```

**Comment by GSPP** [comment]
How is resurrection supposed to be disallowed? Almost any reference assignment could be a resurrection.
