### ISSUE TITLE
[ARM64/Linux] Range checks against constants contain unneeded moves

### ISSUE THREAD

**Issue by TamarChristinaArm** [dotnet/coreclr#24711]
It seems like the sequence for doing range checks was optimized for the variable case. when the index is a constant the comparison generates suboptimal code (with `QuickJIT` off).

```
static int[] Test(int[] a, int n)
{
  a[2] = n;
  return a;
}
```
generates
```
        52800041          mov     w1, #2
        B9800803          ldrsw   x3, [x0,#8]
        6B03003F          cmp     w1, w3
        54000082          bhs     G_M32566_IG04
        B9001802          str     w2, [x0,#24]
```

while flipping the branch condition would have gotten

```
        B9800803          ldrsw   x3, [x0,#8]
        6B03003F          cmp     w3, #2
        54000082          bls     G_M32566_IG04
        B9001802          str     w2, [x0,#24]
```

saving the need for a move and register usage.

/CC @CarolEidt @tannergooding

**Comment by mikedn** [comment]
> It seems like the sequence for doing range checks was optimized for the variable case

Nah, it looks like it's the other way around - it simply wasn't optimized for the integer index case. Due to ARM immediate mode encoding complexities the type of the node that uses the immediate matters and the code that does this (`Lowering::IsContainableImmed`) doesn't recognize `GT_ARR_BOUNDS_CHECK`. Codegen seems to already support this so try adding a `case GT_ARR_BOUNDS_CHECK:` after `case GT_GT:`.

**Comment by TamarChristinaArm** [comment]
Ah, indeed that does work as expected.

**Comment by AndyAyersMS** [comment]
@TamarChristinaArm do you plan to put up a PR to fix this?

Marking as future but if it's just expanding the containment check we probably would take it in 3.0.

**Comment by TamarChristinaArm** [comment]
@AndyAyersMS sure, I'll send a PR for it.
