### ISSUE TITLE
Unexpectedly long and memory-wasting JIT compilation when optimizations are allowed

### ISSUE THREAD

**Issue by speshuric** [dotnet/coreclr#2472]
In some cases JIT compilation in "release" execute mode can take a lot of time and lot of memory.
### Repro
1. Take code [here](https://gist.github.com/speshuric/b646c20fddb1543f8052).
2. Create exe with this code
3. Execute program

**What program do**
1. Method `Main` create `Tst` object and invokes `Do()` method
2. There is loop of `limit` times In `Do()` method that executes `fNN()` which is `2^nn` executions of `f00()`. It should not take a lot of time up to f30(). 
3. In repro `f00()` increments private field `i` and there is "backward" loop to compare time.

### Expected:
The program executes successfully with NN up to 30-35
Output looks lite this (with `f30` in `Do`):
```
Main start 2015-12-27 12:48:31.303
Do start 2015-12-27 12:48:31.306
End step, frw = 8558, bck = 10968, j = 0, i = 0, maxi = 1073741824
End step, frw = 8558, bck = 10968, j = 1, i = 0, maxi = 1073741824
End step, frw = 8558, bck = 10968, j = 2, i = 0, maxi = 1073741824
End step, frw = 8558, bck = 10968, j = 3, i = 0, maxi = 1073741824
End step, frw = 8558, bck = 10968, j = 4, i = 0, maxi = 1073741824
End step, frw = 8558, bck = 10968, j = 5, i = 0, maxi = 1073741824
End step, frw = 8558, bck = 10968, j = 6, i = 0, maxi = 1073741824
End step, frw = 8558, bck = 10968, j = 7, i = 0, maxi = 1073741824
End step, frw = 8558, bck = 10968, j = 8, i = 0, maxi = 1073741824
End step, frw = 8558, bck = 10968, j = 9, i = 0, maxi = 1073741824
Do finished 2015-12-27 12:50:20.907
Main finished 2015-12-27 12:50:20.908
```
Note that time between `Main start` and `Do start` is negligible
### Fact
When the repro build with disabled optimizatios ("debug" mode in VS) behaviour is the same as expected. 
In "release" mode of compilation repro behaviour depends on platform (x86/x64) and NN:
1. Small NN executes near to expected (up to `f10`-`f12`)
2. `f12`-`f14` executes on all x86/x64 but there is perceptible interval between `Main start` and `Do start`
3. Starts from `f19`-`f20` DNX Core.Net and core from sources throw OutOfMemoryException in x86. Old framework works but it takes a long time.
4. When execution between `Main start` and `Do start` a lot of memory allocated on `f14` and greater (depends as `2^NN`). 
5. It looks like execution time between `Main start` and `Do start` depends as `2^NN`

### WIP, notes:
1. I tested this repro in "old" 4.6-4.6 .NET Framework - results are similar. I tested only for Windows. I did not tested on other OSes. 
2. I will try to debug this case and fix this bug.
3. `ngen` hangs on this assembly

Can anyone check behaviour on other OSes?

**Comment by mikedn** [comment]
> Take code here

The repro code is unnecessarily complex. All `Do` needs to do is to call `f21`, there's no need for loops and whatnot.

> I will try to debug this case and fix this bug

You may want to wait for someone from the JIT team to comment on this first. [Planning](https://github.com/dotnet/coreclr/blob/master/Documentation/design-docs/inline-size-estimates.md)/[work](https://github.com/dotnet/coreclr/blob/master/Documentation/design-docs/inlining-plans.md) seems to be in progress that would impact the relevant JIT code.

**Comment by speshuric** [comment]
@mikedn Thank you for feedback! [Here](https://gist.github.com/speshuric/a36086c7f03e30630aeb) is reduced repro.
>You may want to wait for someone from the JIT team to comment on this first.

Yes, you are right. It would be better to wait the comment. And I think this repro can help them.

**Comment by mikedn** [comment]
To be more clear: it's perfectly fine to debug this and even fix it if it turns out that this is a genuine bug - that is, there is code that's supposed to avoid this issue but it doesn't function properly due to some minor bug. But you may find that such code doesn't exist at all or that it has serious issues, attempting to add/fix it without feedback from the team may turn out to be a waste of time.

Perhaps @AndyAyersMS would be interested to have a look at this issue.

**Comment by AndyAyersMS** [comment]
@speshuric Thanks for the interesting test case. I'll take a look.

**Comment by AndyAyersMS** [comment]
RyuJit has an `ALWAYS_INLINE` size threshold that is set to 16 bytes of IL. All the various `fnn`s have sizes at or below this. So the jit will consider these to all be excellent inline candidates. There's also a `MAX_INLINING_RECURSION_DEPTH` which, despite the name, is a general depth check. So RyuJit will inline at most 20 levels deep. There's no corresponding check or limit on the total number of inlines or number of IL bytes inlined. So the jit will inline the call tree up to 20 levels deep here. Timing of the repro case shows quadratic growth with depth up to level 20. After that the time levels off for a bit. Once we get above 30 levels or so, the top-level inlined tree will have numerous subtrees which can themselves incur deep inlining, and this will cause the time to start rising again dramatically.

I suspect the x86 jit will have similar control parameters and inlining dynamics, but haven't looked yet. Given the limited address space available for x86 running out of memory seems plausible. The legacy 64 bit jit may well behave differently and put on the inlining brakes before things get crazy.

Because of the always inline size limit, only a fairly narrow set of programs can exhibit this behavior. Two call instructions require 10 bytes of IL and the return instruction is another byte, so there's not much space left to do much else.

Still, we should consider doing something to prevent things from taking this long (and this much memory) to jit. The simplest countermeasure is probably some kind of limit on the total number of inlines, but we might be better off trying to model and limit the overall compile-time impact of the inlining. So perhaps a limit on the total amount of introduced IL would serve as a better proxy (one hopes jit optimizations are largely linear time). Whatever we do here also needs to behave reasonably in the face of the `AggressiveInlining` attribute.

I'll have to think about this further. I'm somewhat reluctant to add an additional check to the current inlining control structure, but if the check can be crafted to be sufficiently narrow in scope, it might be worth doing.

**Comment by speshuric** [comment]
Can I help you with something?

**Comment by AndyAyersMS** [comment]
I'd be happy to have you help out. We've got a bunch more prep work to do before we start making changes to the inliner.

We need to make a reasonable set of test cases and benchmarks available, and push through a number of improvements in the diagnostic reporting of the inliner itself. 

Probably our greatest need is benchmarks. Any ideas?

**Comment by speshuric** [comment]
I think I can help, but only after holydays (2-3 days). Can you point any examples of current bencmarks to look how they are integrated to coreclr.

**Comment by AndyAyersMS** [comment]
Take look at my recent commits. 

For JIT benchmarks we generally try and avoid stressing the platform or the GC too much, so that any code generation issues stand out. I aim for about 1 second long iterations for benchmark tests (via xunit-performance's [benchmark]). I'm also making these be usable as standalone benchmarks.
