### ISSUE TITLE
Move to cmake based incremental build from python

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#2486]
https://github.com/dotnet/coreclr/pull/2464 is unconditionally generating the ETW logging header files before each invocation. It completely kills incremental build - everything is rebuilt every time.

**Comment by jkotas** [comment]
Is there a reason why the header file generation cannot be done as regular makefile step - that runs only if any of the files that it depends on change?

**Comment by ramarag** [comment]
we can not make it run as a makefile step because the script generates CMake and header files which are consumed in the coreclr build

**Comment by janvorli** [comment]
@ramarag Generating headers is ok, we already have several places where we generate headers consumed by the build and the dependency chain works properly. Generating the CMakeLists.txt scripts can also be invoked from a CMakeLists.txt. You just need to make is so that the generated CMakeLists.txt are not part of the main CMakeLists.txt tree (I mean not including them from any of the static CMakeLists.txt), but you invoke the cmake itself as a custom command for your generated CMakeLists.txt (having a generated "root" one that would include all the others).

**Comment by janvorli** [comment]
You can see an example on how to invoke cmake from the CMakeLists.txt here:
https://cmake.org/pipermail/cmake/2011-November/047333.html

**Comment by jkotas** [comment]
Could you please look into using the cmake to do the incremental build logic per @janvorli feedback?

I do not think building our own clone of incremental build tracking in python is a good idea.

**Comment by AndyAyersMS** [comment]
Is this the issue tracking getting incremental builds to work 100%? If so, I'd love to see it get fixed ASAP.

**Comment by ramarag** [comment]
nope I have opened up a new issue for this in #2701

**Comment by ramarag** [comment]
The work remaining here is to transition Generating linux lttng specific infrastructure from python to cmake. basically the following logic needs to be moved:https://github.com/dotnet/coreclr/blob/master/build.sh#L87
