### ISSUE TITLE
Stack Smashing Failures (SIGSEGV) instead of NullReferenceExceptions

### ISSUE THREAD

**Issue by PiotrSpikowski** [dotnet/coreclr#25166]
I don’t know if it’s related to #16276 but it’s possible to end up in the stack smashing detected failure instead of `NullReferenceException`

We are trying to consume some native libraries e.g. the IBM MQ Client. As far as I can tell the IBM MQ sets up its own signal handlers. By doing this it saves any previously registered handler for each signal. The library handles one of the signals and then attempts to call the original handler that was in effect previously.

If we only allow the library to register its own signal handlers (SIGSEGV) we end up in the `stack smashing detected` errors instead of getting `NullReferenceException`s. So the following code  crashes the entire app (e.g. on 2.2 and 3 preview):

```csharp
object obj = null;
obj.ToString();
```

I understand that we are loading and using native libraries. I also understand that Core uses signals on certain platforms in order to handle NullReferenceExceptions. I however wonder what’s the expected behaviour here and what is allowed?

The C# spec says that when a value of X is null, then a `System.NullReferenceException` is thrown. Is this guarantee broken here? In our case a native library seems to be indirectly involved which: 
* first is not obvious for.NET developers
* secondly is not well documented

If the above signal interaction cannot be changed then maybe it’s worth documenting it e.g. in the .NET native interoperability guidelines.

I guess it’s not possible to force .NET not to use signals and do explicit null checks (it might not be performance wise anyway). I recall something like this for mono set via the MONO_DEBUG (but as the name speaks it is also for debug and not release versions)

**Comment by jkotas** [comment]
cc @janvorli

**Comment by janvorli** [comment]
@PiotrSpikowski the issue is most likely due to the fact that coreclr uses an alternate stack for handling sigsegv, That means that when we register the sigsegv handler, we also set SA_ONSTACK flag which tells the kernel to call the handler on a stack that is registered for these purposes using the sigaltstack API instead of the stack of the failing thread. The reason why we do that is that without this, we would not be able to report stack overflows in a meaningful way. The app would be terminated without any note, because the kernel would not have stack space to launch the signal handler.
Now as for what I think happens in your case. When the native library you are using registers its own sigsegv handler, it most likely doesn't set the SA_ONSTACK flag. So when their handler calls our handler, our SIGSEGV handler is not called on the alternate stack, but on the stack of the application. Our code cannot handle that case and that leads to the stack smashing.
The issue #16276 handles just the case when we are running on a thread that doesn't belong to coreclr.

I think that we have two options:
* change our sigsegv handler to detect whether it is running on the alternate or an original stack and behave well in both cases (loosing the ability to report stack overflows if there is a 3rd party library loaded that registers sigsegv without alternate stack).
* Add a config knob (COMPlus_xxxx variable or something like that) that would disable usage of alternate stack for sigsegv handlers completely.

**Comment by PiotrSpikowski** [comment]
@janvorli the issue is clear now. The native library does not set the SA_ONSTACK flag.

Looking at this from a .NET developer perspective I would say that the option covering both cases (with an alternate and an original stack) is preferred. So from a dev point of view everything is better than a crash especially having in mind that:
* A crash might be detected late and only in some specific circumstances normally leading to null reference exceptions
* A crash might be harder to diagnose in comparison to standard exceptions as for example it may result in constant restarts of containers while runing on platforms such as Kubernetes
* A crash may give an impression of a behavior not conformant to the specification (even if it’s the native library messing around)

When it comes stack overflows… I was a bit surprised reading this in [the documentation](https://docs.microsoft.com/en-us/dotnet/api/system.stackoverflowexception?view=netcore-2.2): 

> Starting with the .NET Framework 2.0, you can't catch a StackOverflowException object with a try/catch block, and the corresponding process is terminated by default.

This seems to apply to .NET Core as well. I don’t know how it relates to the ECMA standard but in such a case not handling stack overflows would seem not to break the rules.

**Comment by janvorli** [comment]
> not handling stack overflows would seem not to break the rules.

We don't handle stack overflows and fail fast. What I was referring to though is that we at least print error message "Stack Overflow" so that the user knows what was wrong. Without the alternate stack, the sigsegv handler isn't even called (because there is no space on the stack for the signal context etc), so the process dies silently.
