### ISSUE TITLE
InitializeCoreClr() and multiple calls

### ISSUE THREAD

**Issue by RickStrahl** [dotnet/coreclr#25246]
I have an application that hosts the .NET Core runtime, which can effectively clear out memory - it's a host IDE and it has the ability to basically clear memory. When this happens it effectively releases all the state in my host DLL including the `hostHandle` and `domainId` that the `initializerCoreClr()` delegate generates.

I use a few global variables to cache the runtime specific values:

```cpp
void* hostHandle;
unsigned int domainId = 0;
```

and on subsequent requests check if these exist and then reuse. 

```cpp
       if (domainId == 0)
       {
               coreclr_initialize_ptr initializeCoreClr = (coreclr_initialize_ptr)GetProcAddress(coreClr, "coreclr_initialize");

                // This function both starts the .NET Core runtime and creates
		// the default (and only) AppDomain
		HRESULT hr = initializeCoreClr(
			runtimePath,        // App base path
			appDomainName,
			sizeof(propertyKeys) / sizeof(char*),   // Property count
			propertyKeys,       // Property names
			propertyValues,     // Property values
			&hostHandle,        // Host handle
			&domainId);         // AppDomain ID
       }
```

This works fine for standard operation - multiple calls call the init once, and then just re-use the hostHandle and domainId for the actual invocation to create a proxy. 

But if the host clears memory the domainId goes away and neither it or hostHandle are available for the required delegate invokations later. If I call the delegate a second time  I get an 'Invalid Operation' error.

I think it would be useful to allow for this API to return the one and only **existing** runtime reference and repopulate the hostHandle and domainId if this is called subsequent times.

Either that or provide some way to attach to find an existing (or rather the only one) runtime and re-populate the hostHandle and domainId.

Classic .NET hosting allowed for this and simply returned the existing default AppDomain which seems to be a good alternative.

I realize _this is a bit of a special case_ (releasing all memory) but I've not found a way around this issue, which is kind of a deal breaker for using .NET Core (over classic .NET Framework) on a technicality.

**Comment by AaronRobinsonMSFT** [comment]
@RickStrahl I would suggest the new `nethost` scenario. An example of this can be found [here](https://github.com/dotnet/samples/tree/master/core/hosting/HostWithHostFxr). Specifically I would look at the [documentation](https://github.com/dotnet/core-setup/blob/dd20086b6d7990a7bf509aefa9f258770abe26b6/Documentation/design-docs/native-hosting.md) regarding `hostfxr_initialize_for_runtime_config`. Changing this at the `coreclr` API surface is not something we are considering since we recommend consumers use the new `nethost` approach.

cc @elinor-fung @sdmaclea @vitek-karas

**Comment by sdmaclea** [comment]
@elinor-fung Is updating our https://docs.microsoft.com/dotnet/core/tutorials/netcore-hosting tutorial for 3.0 to recommend the nethost with this PR  https://github.com/dotnet/docs/pull/12872.

**Comment by RickStrahl** [comment]
@AaronRobinsonMSFT Is this still going to work with a result `IUnknown` coming back that can be marshaled back via COM to the host app? I looked at some of this a while back and it wasn't clear whether that was going to work.

@sdmaclea Yeah the docs are mighty confusing as they mention two different approaches and then there are 3 separate samples that all do something different. The code above actually works just fine, except for the issue of not being able to re-attach to an existing running instance if the host completely disconnects. Unfortunately the way the host disconnects it looks like there's no notification or even destructors firing :-(. I will give Nethost a try when I have a little more time. For now, stoked with proof of concept that at least it works.

**Comment by AaronRobinsonMSFT** [comment]
>Is this still going to work with a result `IUnknown` coming back that can be marshaled back via COM to the host app?

@RickStrahl Yes. Yep brand new sample. @elinor-fung just checked it in earlier this week.

**Comment by AaronRobinsonMSFT** [comment]
@RickStrahl I am going to close this specific issue since changing `InitializeCoreClr()` semantics isn't an option and `nethost` is our recommended solution for "re-attaching" to an existing runtime instance. During your investigation if you discover issues in `nethost` scenario, please file them in https://github.com/dotnet/core-setup. Thanks.

**Comment by RickStrahl** [comment]
Just some feedback on the nethost API - that API is painful to read and understand with all the delegate pointers and funky naming of commands. I suppose this is Unix style C++ or something but man that's not good code for implementers to work with IMHO.

Also I can't get the sample to run as is. There's a dependency missing...

**Comment by elinor-fung** [comment]
@RickStrahl, what error are you getting with the sample? Does it build fine, but not run?

**Comment by RickStrahl** [comment]
The dependency on dotnetlib that's referenced is not available. 

![image](https://user-images.githubusercontent.com/1374013/59945350-07e87b80-9403-11e9-9892-119acee7a4af.png)

I suppose that's just a sample lib that's called but it still would be nice if this was already there and just worked.

Also not sure what this points at:
```cpp
 const char_t *dotnet_type = STR("DotNetLib.Lib, DotNetLib");
```

Shouldn't that be a DLL?

Anyway looks pretty rough right now so I probably hold off.

**Comment by vitek-karas** [comment]
@RickStrahl I assume you didn't build it from the command line first. If I do that and then open the `NativeHost.csproj` the dependency is correctly resolved.

This sample is a bit tricky since it combines native and managed code, and there's no good build system which works on all platforms (Linux/Mac) which supports both managed and native code. The sample solves this by relying on msbuild and invokes the C++ compiler directly. For that reason the `NativeHost` is a `csproj` even though it actually produces a native binary and has no managed sources. I guess this is confusing if you're looking to open the sample from Visual Studio.

I filed https://github.com/dotnet/docs/issues/12974 to track possible improvements to make the sample easier to work with from IDEs.

As for the line:
```C++
 const char_t *dotnet_type = STR("DotNetLib.Lib, DotNetLib");
```

This is an assembly qualified type name of the type from the managed component. The assembly is called `DotNetLib` (that is the last part), the namespace is `DotNetLib` and the type name is `Lib`. The path to the assembly from which this type is loaded is specified on the live above the one you mention:

```C++
const string_t dotnetlib_path = root_path + STR("DotNetLib.dll");
```

Creating the sample in a way which is easy to consume is relatively hard, because we want it to work on all supported platforms. And as mentioned above it requires a non-trivial build system support. If you're just trying to play with this, the very simple way to build it which the sample uses should be sufficient. If you want to integrate this into your larger project, then the two components must be migrated to use whatever build system your project uses for native and managed components respectively.
