### ISSUE TITLE
Add info about MSILC JIT to docs

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/coreclr#253]
In https://github.com/dotnet/coreclr/pull/249 the MSILC JIT was enabled, which from the comments in runtest.cmd is an "alternative JIT for testing".

I'm curious what this is, can we get a bit more info added to the docs?

**Comment by russellhadley** [comment]
Yes,  the CLR has functionality to allow for an “alternate jit” that can be loaded for method JITing while still falling back to the base JIT if needed.  This is a useful tool for JIT testing and debugging as you can probably imagine.  You’re right, it looks like we need additions to the docs here.   The common ‘alt’ scenario is that the current RyuJIT is built as a dll  that includes a developers changes and then is used as an alt jit for testing/binary search.    Architecturally CoreCLR defines a JIT interface that allows different JITs to be plugged in so there has been different alternate JITs internally over the years.  The “MSILC” you saw is just one of those, and which in the pipeline to come open - we're just resource constrained or it'd be out already.    

Today if you set COMPlus_AltJit=*, and specify COMPlus_AltJitName=<altjitName>.dll, CoreCLR will load the dll as the alternate JIT and try to compile a method with it before falling back to the main JIT.  More description is in the below link about enabling a RyuJIT CTP.

https://github.com/Microsoft/dotnet/tree/master/docs

Your issue is a good one – we’ll get somebody to add some basic docs initially and then start on some more overarching description.

**Comment by akoeplinger** [comment]
Great, I suspected something like that, thanks for the explanation!

**Comment by richlander** [comment]
@akoeplinger Do you have a suggestion for what we should do? Should we make an entry in the wiki, start a new file in the Documentation direction? What would work best for you, as a user of the info?

**Comment by akoeplinger** [comment]
@richlander Hmm, I don't think it fits in the wiki, I'd prefer something in the Documentation folder.

**Comment by richlander** [comment]
@akoeplinger OK, works. I'll talk to folks about that. I'm thinking a document that describes the alt-jit mechanism, it's intention and the instructions would be good. Sound, good?

@cmckinsey or @CarolEidt can probably help with that. I assigned to @cmckinsey.

**Comment by akoeplinger** [comment]
Yep that sounds excellent!

**Comment by WalkingCat** [comment]
@akoeplinger actually the AltJit mechanism is easy to understand, what's interesting/unclear here is what MSILCJIT/LLILCJIT itself is. any progress ? @richlander

**Comment by WalkingCat** [comment]
alright, to answer my own question, MSILCJIT or LLILCJIT is an LLVM based JIT for .NET https://github.com/dotnet/llilc

**Comment by russellhadley** [comment]
Last question answered with llilc link.  Closing.
