### ISSUE TITLE
VSDBG launch fails with 0x80131c49 for Alpine based docker container running inside AKS

### ISSUE THREAD

**Issue by xinyanmsft** [dotnet/coreclr#25315]
Found this when trying to get Azure DevSpaces sport Alpine based Docker images.

In Docker container, VSDBG is installed via (also tried vs2017u5)
RUN curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -r linux-musl-x64 -v vs2019 -l /vsdbg/linux-musl-x64

and have a Dockerfile from Alpine:
FROM mcr.microsoft.com/dotnet/core/sdk:2.2-alpine3.9

ARG BUILD_CONFIGURATION=Debug

ENV ASPNETCORE_ENVIRONMENT=Development

ENV DOTNET_USE_POLLING_FILE_WATCHER=true

EXPOSE 80

WORKDIR /src

COPY ["webfrontend.csproj", "./"]

RUN dotnet restore "./webfrontend.csproj"

COPY . .

WORKDIR "/src/."

RUN dotnet build --no-restore "webfrontend.csproj" -c $BUILD_CONFIGURATION

RUN echo "exec dotnet run --no-build --no-launch-profile -c $BUILD_CONFIGURATION --" > /entrypoint.sh

ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]

When launch the debugger (via remote debugger, our own SSH-ish pipe), getting the error below. This container runs in AKS.

Starting: "azds" exec --interactive --on-exit-resume-up -- /vsdbg/linux-musl-x64/vsdbg --interpreter=vscode

------------------------------------------------------------------- You may only use the Microsoft .NET Core Debugger (vsdbg) with Visual Studio Code, Visual Studio or Visual Studio for Mac software to help you develop and test your applications. -------------------------------------------------------------------

Unable to attach to CoreCLR. Unknown Error: 0x80131c49

The program '[152] webfrontend.dll' has exited with code -1 (0xffffffff).

**Comment by mikem8361** [comment]
Have you tried a 3.0 alpine docker image like mcr.microsoft.com/dotnet/core/sdk:3.0.100-preview6-alpine?

**Comment by mikem8361** [comment]
I need some help setting up my docker container.  I created a container locally on my ubuntu machine using the above 3.0 image, installed vsdbg using the getvsdbgsh script and then tried to start vsdbg. I do this explicitly in my container and not in a DockerFile.  

$container_id is the container id:

     sudo docker exec -it --privileged --workdir=$HOME $container_id bash
     curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -r linux-musl-x64 -v vs2019 -l /vsdbg/linux-musl-x64
     /vsdbg/linux-musl-x64/vsdbg --interpreter=vscode

Can I connect the VSCode installed in my host machine to this container?  I don't understand how remote debugging works.

/cc: @gregg-miskelly

**Comment by xinyanmsft** [comment]
Mike, let me setup an environment for you to repro.

**Comment by xinyanmsft** [comment]
as I investigate more, this might have to do with the pipe program behave different on Alpine image. Let me drill into it more.

**Comment by gregg-miskelly** [comment]
@xinyanmsft aside from running under a different account maybe? That doesn't sound very possible for the error you are seeing.

**Comment by gregg-miskelly** [comment]
@mikem8361 -- a few notes:
1. I am not seeing this on my local Alpine container, so I suspect there is something different with the way these containers are being hosted in Azure, so I am kind of doubtful that you will be able to reproduce this locally, but you are certainly welcome to try.
2. In @xinyanmsft's scenario, he is using VS as a client, though you can use VS Code if you prefer. I believe he is also doing a launch rather than an attach. Here are a few example launch.json files if you want to try using VS Code: [attach to docker example](https://github.com/OmniSharp/omnisharp-vscode/wiki/Attaching-to-remote-processes#configuring-docker-attach-with-launchjson), [remote launch example](https://github.com/OmniSharp/omnisharp-vscode/wiki/Remote-Debugging-On-Linux-Arm#sample-launchjson---macos-and-linux).
3. Getting a native debugger attached to vsdbg in alpine in Azure is going to be tricky. If I would you, I would add log statements instead. If you want to try anyway: there is a `--pauseEngineForDebugger` argument that you could try to add to vsdbg. I haven't tested it on Alpine, but it is supposed to force vsdbg to wait for a native debugger to attach. If you are driving vsdbg using vscode, you can do this by setting `pipeArgs` to something like `"pipeArgs": [ "exec", "-i", "my_container_name", "${debuggerCommand} --pauseEngineForDebugger" ],`

**Comment by mikem8361** [comment]
@xinyanmsft is your alpine docker container started with SYS_TRACE capablity (with --cap-add=SYS_PTRACE or --privileged)?

**Comment by xinyanmsft** [comment]
@mikem8361 @gregg-miskelly 
the user account / security context is not an issue. In the same Container in AKS, I was able to invoke vsdbg debugging while doing it directly. however if I invoke vsdbg via another .net process (also running inside the container, just redirect stdin/stdout), I see the 0x80131c49 error. I've verified the stdin/stdio redirection works as expected.

**Comment by mikem8361** [comment]
It is still not clear to me how to debug this.  Logging may be the simplest but I will need to add some logging/build a debug version of the runtime for you to try.  Have you tried a 3.0 SDK/runtime? I guess I could build a debug 2.2 runtime with extra logging and give it to you to try. 

Ignore my comment about SYS_TRACE capability since this was repro'ed on 2.2.

**Comment by xinyanmsft** [comment]
I think this has to do with an environment variable I accidentally set. To work around a dotnet limitation (published bits can't run on certain Alpine images), an environment variable LD_LIBRARY_PATH was set. And I think that has to do with the failure. I am in the middle of verifying, if that's the case I will close this issue. Apologize.

**Comment by xinyanmsft** [comment]
close this issue - this was caused by LD_LIBRARY_PATH environment.
