### ISSUE TITLE
CoreClr crashes sporadically when interacting with Windows COM API

### ISSUE THREAD

**Issue by bergmeister** [dotnet/coreclr#25502]
This issue has been observed to happen sporadically and is hard to reproduce but we have lots of logs and narrowed down the offending code. The issue causes PowerShell Core itself to sporadically crash on Windows at startup
- It does not seem to be specific to a version of Windows, it has been seen in various environments
- It has been observed with the latest runtime of .Net Core 2.1 as well as `3.0-preview5`
- The process is running in `MTA` appartment state and interacts with Windows COM APIs to create an elevated `JumpList` entry on application startup. The APIs are public and there were no issues when the code was written in `C++` for Windows PowerShell and the code was later ported to managed C# with COM interfaces being taken from the Windows API kit.
- The issue is described in detail [here](https://github.com/PowerShell/PowerShell/issues/9295) with a crash log [here](https://github.com/PowerShell/PowerShell/issues/9295#issuecomment-500770387), a memory dump [here](https://github.com/PowerShell/PowerShell/issues/9295#issuecomment-501135947) and its associated stack trace [here](https://github.com/PowerShell/PowerShell/issues/9295#issuecomment-501353113), some preliminary analysis of what goes on in the coreclr is [here](https://github.com/PowerShell/PowerShell/issues/9295#issuecomment-501353113)
- We added more logging statements and found that the fatal CLR error happens [here](https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.ConsoleHost/WindowsTaskbarJumpList/TaskbarJumpList.cs#L87) in PowerShell's code. Sometimes (more rarely) a `InvalidComObjectException` is observed, which is happening just one line later, see comment with stack trace [here](https://github.com/PowerShell/PowerShell/issues/9295#issuecomment-505638825)

**Comment by weltkante** [comment]
I had a look at the dump and it crashed in the [RCWHolder helper class](https://github.com/dotnet/coreclr/blob/master/src/vm/runtimecallablewrapper.h#L1599). The line `m_pSB->GetInteropInfoNoCreate()->GetRCWAndIncrementUseCount();` returns NULL for the middle call of `GetInteropInfoNoCreate()`. I don't know if its representative for the failures.

I've reviewed the [COM interop declarations](https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.ConsoleHost/WindowsTaskbarJumpList/ComInterfaces.cs) and couldn't see anything obviously wrong in the methods they use ([some](https://github.com/PowerShell/PowerShell/pull/9899/files) of the unused methods were using PreserveSig wrongly but that shouldn't matter since they were never called). They are [using an enum](https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.ConsoleHost/WindowsTaskbarJumpList/HResult.cs) for HRESULT return values, in case there's any known bugs around that.

**Comment by jkoritzinsky** [comment]
I've taken a look at this. I suggest adding the `[STAThread]` attribute to the entry-point for PowerShell Core on the line above https://github.com/PowerShell/PowerShell/blob/e7e53b603a84c7e43d2baccbb5d99f6b83a1c0d9/src/powershell/Program.cs#L20. The shell extension APIs like the jump list require that they be run on the STA or you will get weird spurious failures (such as this one).

**Comment by weltkante** [comment]
Will STA work without having a message loop? We once got deadlocks in IIS because a COM STA object wanted to get back to its thread in the finalizer but there was no message loop running. The finalizer thread got deadlocked and the GC stopped working.

**Comment by bergmeister** [comment]
Thanks for the info/suggestion. PowerShell Core is running in `MTA` mode at the moment for historical reasons (.Net Core used to be MTA only).
For PowerShell 7 that uses .Net Core 3, the plan is to go back to STA again, there is a tracking issue already: https://github.com/PowerShell/PowerShell/issues/7216
However, I would still not expect the CoreClr to fail with a fatal error but rather give a catchable exception instead.
What we should to about PowerShell 6.x that is on .Net Core 2.1 @SteveL-MSFT ?

**Comment by jkoritzinsky** [comment]
I've checked the registry and the COM server that's being created is an STA-only COM object (see the screenshot below and the [docs](https://docs.microsoft.com/en-us/windows/desktop/com/inprocserver32))

![image](https://user-images.githubusercontent.com/1571408/60472971-f03d9e00-9c1f-11e9-843a-354e0235678f.png)

Creating an STA COM server in an MTA threading apartment will cause a host of problems that can lead to destabilizing the runtime and causing weird crashes as you've seen.

**Comment by jkoritzinsky** [comment]
Considering that WPF requires the thread to be an STA thread before using the jump list, I presume that there are long-standing reasons for that code and that PowerShell should also follow suit.

**Comment by AaronRobinsonMSFT** [comment]
To add a little bit more context to @jkoritzinsky's response, the class marked as an STA is `CLSID_EnumerableObjectCollection`. This class is being used at:

https://github.com/PowerShell/PowerShell/blob/bd6fdae73520931f0d27a29d6290e18761772141/src/Microsoft.PowerShell.ConsoleHost/WindowsTaskbarJumpList/TaskbarJumpList.cs#L74-L78

**Comment by AaronRobinsonMSFT** [comment]
The `CLSID_DestinationList` class is also marked as STA and being used at:

https://github.com/PowerShell/PowerShell/blob/bd6fdae73520931f0d27a29d6290e18761772141/src/Microsoft.PowerShell.ConsoleHost/WindowsTaskbarJumpList/TaskbarJumpList.cs#L26-L29

**Comment by AaronRobinsonMSFT** [comment]
Since this isn't a specific defect in CoreCLR - other than the fact we apparently permit creation of an STA only object on the MTA. I am going to move this to future. This specific issue should be moved to PowerShell and an issue tract in coreclr to limit the creation of STA object only on an STA.

**Comment by weltkante** [comment]
> we apparently permit creation of an STA only object on the MTA

I don't yet get how that happens, I thought `CoCreateInstance` was responsible for creating objects in the right apartment (should have spun up an STA thread and returned a proxy in the MTA apartment) and your scenario could only happen in the new "lightweight COM" when you create COM-like objects through explicitely exported DLL functions rather than CoCreateInstance, but maybe I'm mistaken.

As far as powershell is concerned I guess they'll either have to turn themselves into STA (and should have a top level message loop in order to not deadlock the finalizer thread?), or they need to spin up their own separate STA thread and be really careful to deterministically release the COM objects before terminating that thread.

**Comment by AaronRobinsonMSFT** [comment]
>we apparently permit creation of an STA only object on the MTA
>>I don't yet get how that happens, I thought CoCreateInstance was responsible for creating objects in the right apartment

@weltkante  `CoCreateInstance` does check but helps the caller when possible. If a proxy has been registered, then the instance can be created in the host STA that is managed by COM itself and a proxy returned. Documentation for this is sparse, but is mentioned at: https://docs.microsoft.com/windows/desktop/com/inprocserver32.

Sentences of interest are:
>If the first STA in a process is initialized by COM, rather than by an explicit call to CoInitialize or CoInitializeEx, it is called the host STA. For example, COM creates a host STA if an in-process server to be loaded requires an STA but there is currently no STA in the process.

There is also the more comprehensive documentation for threading models that gives some additional [details](https://support.microsoft.com/help/150777/info-descriptions-and-workings-of-ole-threading-models).

How .NET Core handles the host STA is more than likely not really defined and probably poorly or never tested which is why the failure is so bad. Per usual when using COM, it is much better for consumers to be explicit about their apartment requirements rather than relying on any "helpful" COM behavior. Similar "helpful" behavior is the implicit MTA - see [APTTYPEQUALIFIER_IMPLICIT_MTA](https://docs.microsoft.com/windows/win32/api/objidlbase/ne-objidlbase-apttypequalifier). Since there is an implicit reliance, any thread that is implicit MTA is in a bad state if/when the thread that called `CoInitializeEx()` calls `CoUninitialize()`.

**Comment by bergmeister** [comment]
Thanks for the feedback, I created the following PR in PowerShell to make the JumpList creation code be run in an STA thread as changing PowerShell to be run from MTA to STA is a bigger undertaking (that is planned but is a separate item not related to this). Can you please review the PR below if you think this is OK as a solution @AaronRobinsonMSFT ?
https://github.com/PowerShell/PowerShell/pull/10057
Otherwise I think we can close the issue for now, what do you think? Should the problem persist, we can re-open. I'll leave it up to the CLR team to create a separate item for better error handling.

**Comment by weltkante** [comment]
Well, what you are saying exactly matches my expectations and what I suggested should happen.

Since PowerShell currently calls this code from MTA the CoCreateInstance call should setup a host STA for the created object to live in and return a proxy to the calling MTA. This proxy is the only thing .NET Core ever sees, it will not see the host STA nor interact with it at all, as its a native object running there .NET Core does not have any business with it.

Since .NET Core only sees the proxy which was generated for the MTA apartment it doesn't matter what .NET Core does, COM does all the marshaling to the host STA, and the .NET finalizer can run on any MTA thread. This should work perfectly fine, unless there's a bug in the native COM object implementation (i.e. not in .NET Core) which makes proxies not work and require STA. Happened before in other Windows components, so its a possibility.

However the crash in the dump looks suspicious and more like a fault in .NET Core. Something is NULL when the caller doesn't expect it to be NULL, so some invariant has been broken. In the given scenario .NET Core is only managing interfaces and not providing COM object implementations, so since COM doesn't call into .NET the observed broken invariant most likey resulted from incorrect code in the .NET Core runtime.

I'm not disagreeing with PowerShell trying to go STA and see if the bug disappears, it just as well might be a viable workaround for them, but all evidence points to there being a bug in .NET Core COM interop which probably will show up again in other contexts sooner or later, so it might be worth learning as much as possible from the scenario and available dump before discarding the issue.
