### ISSUE TITLE
coreclr.dll contains "FX_VER_PRIVATEBUILD_STR" as its PrivateBuild property

### ISSUE THREAD

**Issue by leculver** [dotnet/coreclr#25557]
Coreclr.dll contains this in its PrivateBuild string:

    0:000> lmvm coreclr
            PrivateBuild:     FX_VER_PRIVATEBUILD_STR

For an official build, this should be empty.  For non-official builds it would be helpful to put something meaningful here.  On desktop CLR we used to put the user-alias of the MSFT employee who built it.  That was SUPER helpful in tracking down issues that were unique to someone building a broken coreclr and knowing who built it to go ask them...

I don't know the right thing for .Net Core in the open source world, but at minimum we should probably get rid of that string for official  builds at least.

**Comment by AaronRobinsonMSFT** [comment]
The biggest issue here is the lack of any way to currently detect an official build during the native build. I am going to remove the logic entirely and defer to the suggestions from @leculver to later. I agree that inserting an alias is probably interesting in .NET Framework, but I am dubious of how often private builds are passed around due to the ease of build and creating a test machine.

**Comment by leculver** [comment]
@AaronRobinsonMSFT It's fine if you want to just remove it entirely.  I'm just capturing context.
