### ISSUE TITLE
What is the detaching profiler procedure on Unix?

### ISSUE THREAD

**Issue by ww898** [dotnet/coreclr#25568]
Could you please tell me what should I use in my profiler on Unix platforms instead of `FreeLibraryAndExitThread`?

Comment in .NET Core code:
https://github.com/dotnet/coreclr/blob/be5445e56ea2bdb6de907e3f892ca732fc802f0f/src/vm/profdetach.cpp#L133-L134

The David Broman's manuscript:
https://github.com/dotnet/coreclr/blob/6f1bdfffb77ba1c95f46e16a7eeff3cfaf2f2f1f/Documentation/Profiling/davbr-blog-archive/Profiler%20Detach.md#how-detaching-works

**Comment by tommcdon** [comment]
@davmason @noahfalk

**Comment by davmason** [comment]
@janvorli Since you're a linux expert, do you have advice for this situation?

A profiler probably wants to do some cleanup work post detaching, on Windows our advice was to call `LoadLibrary` on yourself before the call to `RequestProfilerDetach`, then detach and once detach is over you can clean up and then call `FreeLibraryAndExitThread` when you are done with cleanup.

I don't see an equivalent function on Linux, and I'm not seeing any documentation about whether it's safe to call `dlclose` from code that would be unloaded. My naive assumption is that `dlclose` would be subject to the same issue that `FreeLibrary` is, where the return code would be unloaded and cause an AV.

@ww898 as a workaround it should always be safe (i.e. you will never see a crash functional issue) to just not freethe profiler library on Linux. It will cause some extra memory usage, but it shouldn't be a huge impact and once the process exits it will be released.

**Comment by janvorli** [comment]
> My naive assumption is that `dlclose` would be subject to the same issue that `FreeLibrary` is

It it implementation specific, POSIX standard doesn't require the library binaries to be removed from memory when the refcount reaches zero. Only the handle to the library is required to be closed. See http://pubs.opengroup.org/onlinepubs/007904975/functions/dlclose.html

As for the `FreeLibraryAndExit`, there is no equivalent to that. The only portable way seems to be to call a function containing `dlclose` followed by `pthread_exit` from another library than the one being unloaded.

**Comment by davmason** [comment]
Long term we'll probably have to offer an API to unload the profiler after cleanup, but it won't be part of 3.0 since we're past the point where new features can be checked in.

Short term, either not calling `dlopen` and doing your cleanup before calling `RequestProfilerDetach` to let the runtime unload your profiler or just leaving the profiler loaded in memory seems to be the easiest thing.

If you need to unload your profiler, another possible workaround would be to write a tiny library that exports a method that will call `dlclose` and then `pthread_exit` as Jan mentions. You would have to leave this second library in memory, but it should be much smaller and therefore lower impact than your profiler.

**Comment by ww898** [comment]
@davmason @janvorli Thanks a lot for ideas!

**Comment by ww898** [comment]
@davmason @janvorli What do you think about the following decision for clang 6.0.0.0 x64:
```
__attribute__((noinline))
void dlclose_and_pthread_exit(void * module_handle)
{
    __asm("pushq %0\n"       // The 16-bytes stack aligment
          "pushq %1\n"       // The pthread_exit() address as the return address of dlclose()
          "movq %2, %%rax\n"
          "jmpq *(%%rax)\n"  // The long jump to absolute address
        :
        : "D"(module_handle), "g"(&pthread_exit), "g"(&dlclose)
        : "%rax");
}
```
The side effect is an unpredictable thread exit code, but it is not important, is it?

**Comment by jkotas** [comment]
It will work ok for now, but it is not going to work once https://www.bing.com/search?q=Intel+Control+Flow+Enforcement+Technology becomes a thing.

**Comment by noahfalk** [comment]
I think the question was answered so closing issue. We can reopen if more needed to happen here.
