### ISSUE TITLE
Generic Interlocked methods with unmanaged constraint

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/coreclr#25609]
Would it make sense to introduce generic methods with the `unmanaged` constraint on `Interlocked` for say Add(Inc/Dec)/Exchange/CompareExchange?

Came across this in npgsql during some lock-free fun.
It looks somewhat like this
```cs
[StructLayout(LayoutKind.Explicit)]
internal struct PoolState
{
    [FieldOffset(0)]
    public int Idle;
    [FieldOffset(4)]
    public int Busy;

    [FieldOffset(0)]
    public long All;
}

private PoolState State;
``` 

I'd rather just be able to pass `State` to these `Interlocked` methods than `State.All`

**Comment by stephentoub** [comment]
> Would it make sense to introduce generic methods with the unmanaged constraint on Interlocked for say Add(Inc/Dec)/Exchange/CompareExchange?

No. `unmanaged` says nothing about the size of the state, and interlocked operations have strict size constraints.

**Comment by NinoFloris** [comment]
@stephentoub You're completely right of course. 
I must have remembered that wrong, it being a strict size requirement too...

**Comment by GSPP** [comment]
`Exchange` could throw an exception if used with incompatible types. Does this not make sense for structs of up to 16 bytes?

**Comment by stephentoub** [comment]
> Does this not make sense for structs of up to 16 bytes?

Up to?  How would this work, for example, with Byte in a way that was both atomic and guaranteed not to corrupt state?

**Comment by GSPP** [comment]
How could exchanging a byte corrupt state? I can't figure it out :smile:. Is there limited CPU support?

If it is only possible to exchange 4 and 8 byte quantities reliably, this could still be made to work for structs of that size.

Also, smaller sizes can be emulated from larger sizes using loops. I found http://mail.openjdk.java.net/pipermail/hotspot-dev/2014-September/015213.html on this idea. This can only be implemented in the runtime. User code cannot emulate this.

On the other hand, I don't think 8 byte structs would necessarily be 8 byte aligned. This can't even be implemented using 16 byte CPU instructions because we can't cross cache lines.
