### ISSUE TITLE
DoStackSnapshot from P/Invoke

### ISSUE THREAD

**Issue by iskiselev** [dotnet/coreclr#25652]
Is it safe to call DoStackSnapshot for Synchronous Stack Walk from P/Invoke call?
Per my tests it works, but [documentation](https://docs.microsoft.com/en-us/dotnet/framework/unmanaged-api/profiling/icorprofilerinfo2-dostacksnapshot-method) states, that it can be done in response to the CLR calling one of your profiler's ICorProfilerCallback (or ICorProfilerCallback2) methods.
If it is safe, should documentation be updated? Should it be safe at least call it from any ICorProfilerCallbackX calls?

**Comment by davmason** [comment]
I think it should be fine. The officially supported way to do it would be to register for `ICorProfilerCallback::UnmanagedToManagedTransition` and then do a stack walk from within that callback. I can't think of a reason it would matter to the stack walker if you called from within a PInvoke versus that callback though.

I don't want to update the documents since we don't test that scenario. And since it is untested you may run in to corner case issues down the line.

**Comment by noahfalk** [comment]
I think the issue was resolved, we can reopen if I misunderstood.
