### ISSUE TITLE
Method enter/exit hook not working for few methods

### ISSUE THREAD

**Issue by Gopinath-mahadevan** [dotnet/coreclr#25872]
I got the core clr profiler from the below link. 
https://github.com/microsoft/clr-samples/tree/master/ProfilingAPI/ELTProfiler

I'm trying to find the time taken for execution of all methods. I created a single api .net core web application to test it. But method enter/exit hook is not working for the function i wrote. 

Below is the sample code what I'm testing. Here enter hook works for ValuesController.Get method. But enter/exit hook doesn't works for the other methods what I wrote eg: MyTestMethod(), one(), Two(), AppService.getCalssName()

```
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
namespace SampleApp.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class ValuesController : ControllerBase
    {

        [HttpGet]
        public ActionResult<IEnumerable<string>> Get()
        {
            AppService app = new AppService();
            One();
            return new string[] { One(), app.getCalssName() };
        }

        public string MyTestMethod()
        {
            return "MyTestMethod";
        }

        public string One()
        {
            return "One";
        }

        public string Two()
        {
            return "Two";
        }
    }
}
```
I'm not sure what I'm missing.

**Comment by tommcdon** [comment]
@davmason

**Comment by davmason** [comment]
Hi @Gopinath-mahadevan,

You aren't seeing the function entered callbacks because your functions are being inlined since they are so small. This is normal behavior and you will see inlining happening all over.

As a profiler author you have a couple methods to deal with this (each one has it's own set of benefits and drawbacks though)

- Monitor jit inlining through the `ICorProfilerCallback::JitInlining` callback, and either block the inlining by returning false for the methods you care about, or record that it happened so you know when `Get()` is called it has inlined `One()`. This is the best solution for performance but the most costly to implement.
- Disable inlining for methods you care about in C# code with a `[MethodImpl(MethodImplOptions.NoInlining)]` attribute. This requires you to own the C# code though, and wouldn't work for running your profiler on arbitrary code.
- Disable inlining globally by setting `COR_PRF_DISABLE_INLINING` in the profiler event mask. ***Warning*** this will affect performance of your app pretty noticeably. Even though it is the easiest option because it requires no other changes on the profiler side, it has pretty severe performance implications. Don't go down this route unless you fully understand the implications.

**Comment by Gopinath-mahadevan** [comment]
Thanks @davmason 

The enter/exit hook for those method works when I set the flag COR_PRF_DISABLE_INLINING in the profiler.
