### ISSUE TITLE
System.Data.SqlClient, Version=4.6.0.0 is requested, Version=4.7.0... fits

### ISSUE THREAD

**Issue by AdmiralSnyder** [dotnet/coreclr#25897]
There is a problem with communicating the required minimal version of an assembly:
### Repro:
**Setup**
Create an empty solution, add a .net framework (4.0) winforms app, create an SqlConnector e.g. in the Click event handler, add a .net core (3) winforms app, create an instance of that framework form.

**Run**
--> Error at runtime:
System.IO.FileNotFoundException: "Could not load file or assembly 'System.Data.SqlClient, Version=4.6.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Das System kann die angegebene Datei nicht finden."

**try to fix**
So, add nuget reference to System.Data.SqlClient, Version=4.6.0
--> Error at runtime:
System.IO.FileLoadException: "Could not load file or assembly 'System.Data.SqlClient, Version=4.6.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)"

**fix**
update nuget reference to System.Data.SqlClient, Version=4.7.0(preview…)
no error

-> why does the error ask for the wrong version?

**Comment by danmosemsft** [comment]
@ericstj maybe knows?

**Comment by ericstj** [comment]
AssemblyVersion and PackageVersion are not synced.  This is largely due to the history of desktop and trying to represent things that are inbox on various frameworks (we have to bump package version to deliver new out of band implementations to some frameworks while other frameworks carry a version inbox so we cannot change the assembly version).

We're hoping to fix all this in 5.0 and line up package and assembly version in most cases for the "latest" implementations.

The reason you didn't automatically get that reference is that SQLClient is part of .NETFramework but not part of .NETCore nor the WindowsDesktop shared framework.  @terrajobst recently led an effort to consider growing this set but SQLClient was still out.

In general, when you see an error like this the steps to fix the issue are to install the latest version of the package rather than to select a specific version, especially when considering System.* dependencies.
