### ISSUE TITLE
Discrepancy between RyuJIT and Mono mini compiling IL with conditional branch

### ISSUE THREAD

**Issue by gdkchan** [dotnet/coreclr#25949]
I found that problem some months ago. Didn't really open a issue at the time because I assumed the IL is technically invalid according to the spec (but now reading it again, I don't see anything on it that explicitly says this kind of pattern is invalid). But the interesting part is that it does work fine with the mono JIT. Here's a very simple program that shows the issue:
```cs
using System;
using System.Reflection.Emit;

namespace ILTest
{
    delegate int TestMethod();

    class Program
    {
        static void Main(string[] args)
        {
            DynamicMethod meth = new DynamicMethod("TryMe", typeof(int), null);

            ILGenerator generator = meth.GetILGenerator();

            generator.Emit(OpCodes.Ldc_I4_1);

            Label lbl = generator.DefineLabel();

            generator.MarkLabel(lbl);
            generator.Emit(OpCodes.Brfalse_S, lbl);
            generator.Emit(OpCodes.Ldc_I4_1);
            generator.Emit(OpCodes.Ret);

            int result = ((TestMethod)meth.CreateDelegate(typeof(TestMethod)))();

            Console.WriteLine("Result: " + result);
        }
    }
}
```
On .NET Core it throws:
```
System.InvalidProgramException: The JIT compiler encountered invalid IL code or an internal limitation.
```
On mono it works fine, printing `Result: 1` and exiting.

I recently saw https://github.com/dotnet/corefx/pull/39765 which apparently tries to fix a somewhat similar issue (well, not exactly the same, but it also arose due to a discrepancy between mono and .NET Core JIT), although in this case its the opposite problem (it works on mono but not .NET Core).

**Comment by AndyAyersMS** [comment]
The IL is unverifiable per Ecma-355 III.1.8.1.1 Verification algorithm, in particular these two parts:

> The verification algorithm shall simulate all possible control flow paths through the code and ensure that a valid stack state exists for every reachable CIL instruction. The verification algorithm does not take advantage of any data values during its simulation (e.g., it does not perform constant propagation), but uses only type assignments

RyuJit does not (generally) constant propagate during importation and so the backwards branch here is considered a possible control flow path.

> The algorithm shall also fail if there is an existing stack state at the next instruction address (for conditional branches or instructions within a try block there might be more than one such address) that cannot be merged with the stack state just computed

Because the backwards branch to the label is stack empty and the fall through to the label is not, RyuJit rejects this method as bad IL.

RyuJit is often a bit more permissive than the spec, and it looks like Mono is too.

Expecting both jits to always agree on what happens for IL that is outside the spec seems unrealistic.

But perhaps we should keep tabs on the differences, and if it's not too difficult, work to minimize them.

**Comment by BruceForstall** [comment]
Since there is nothing actionable here, I'm going to close this. If we choose to tackle Mono/RyuJIT differences, we should choose an appropriate mechanism (which might indeed by GitHub issues).
