### ISSUE TITLE
VB6 COM Interop - Cannot see .NET Core library in references list

### ISSUE THREAD

**Issue by adamlonsdale** [dotnet/coreclr#25966]
We have a small part of our product in VB6. I need the ability to register a .NET Core Library as an in-process COM server and consume it from VB6. I further need to consume a VB6 library from .NET Core and that will enable us to upgrade to .NET Core 3.

Having installed 3.0 Preview 7 and successfully registering a .NET Core COM Server Library with help from @AaronRobinsonMSFT and team I can see changes in the registry for my GUID which add in 

**[HKEY_CLASSES_ROOT\Clsid\{B8D9CB8F-E6A4-48A7-ACBF-FF0DCABB779E}]
@="CoreCLR COMHost Server"**

**[HKEY_CLASSES_ROOT\Clsid\{B8D9CB8F-E6A4-48A7-ACBF-FF0DCABB779E}\InProcServer32]
@="C:\\Users\\Adam.Lonsdale\\Desktop\\netcorewinforms\\WinFormsCore.comhost.dll"
"ThreadingModel"="Both"**

However, the old VB6 registration or previous netfx libraries registered with regasm add in more registry keys such as version, ProgID etc. 

**[HKEY_CLASSES_ROOT\Clsid\{B8F4F8B6-1C08-3F34-9B1E-39D984D20276}]
@="MyLibrary.wsMyLibrary.name"**

**[HKEY_CLASSES_ROOT\Clsid\{B8F4F8B6-1C08-3F34-9B1E-39D984D20276}\Implemented Categories]**

**[HKEY_CLASSES_ROOT\Clsid\{B8F4F8B6-1C08-3F34-9B1E-39D984D20276}\Implemented Categories\{62C8FE65-4EBB-45e7-B440-6E39B2CDBF29}]**

**[HKEY_CLASSES_ROOT\Clsid\{B8F4F8B6-1C08-3F34-9B1E-39D984D20276}\InprocServer32]
@="mscoree.dll"
"Assembly"="MyLibrary, Version=2.2.112.1, Culture=neutral, PublicKeyToken=null"
"Class"="MyLibrary.wsMyLibrary.name"
"CodeBase"="file:///C:/Program Files/Fee Earner Desktop/Rel22/MyLibrary.DLL"
"RuntimeVersion"="v4.0.30319"
"ThreadingModel"="Both"**

**[HKEY_CLASSES_ROOT\Clsid\{B8F4F8B6-1C08-3F34-9B1E-39D984D20276}\InprocServer32\2.2.112.1]
"Assembly"="MyLibrary, Version=2.2.112.1, Culture=neutral, PublicKeyToken=null"
"Class"="MyLibrary.wsMyLibrary.name"
"CodeBase"="file:///C:/Program Files/Fee Earner Desktop/Rel22/MyLibrary.DLL"
"RuntimeVersion"="v4.0.30319"**

**[HKEY_CLASSES_ROOT\Clsid\{B8F4F8B6-1C08-3F34-9B1E-39D984D20276}\ProgId]
@="MyLibrary.wsMyLibrary.name"**

The old netfx libraries show up in VB6 references when registered and the new .NET Core don't. 

I would like to write an article when this is solved to provide further documentation for the community who are supporting legacy code via Interop.

**Comment by AaronRobinsonMSFT** [comment]
The gist here is missing ProgIDs and categories. Categories are bit less interesting, but ProgIDs are important and should be brought back. This shouldn't be a ton of work, but will require updates to both the dotnet/sdk and dotnet/core-setup repos.

cc @jeffschwMSFT @jkoritzinsky

**Comment by adamlonsdale** [comment]
Is there any documentation on the implementation of COM via the Registry? 

I presumed I could in the meantime put in a ProgID Key manually which unfortunately doesn't do the trick. Just wondering if there is anything else I need to manually add in and whether I could ascertain that from any documents.

**Comment by AaronRobinsonMSFT** [comment]
>Is there any documentation on the implementation of COM via the Registry?

Yes. Nothing the CLR does with respect to COM is a secret, it should all be fully documented. https://docs.microsoft.com/windows/win32/com/com-registry-keys

>I presumed I could in the meantime put in a ProgID Key manually which unfortunately doesn't do the trick.

Right, you need a bit more to make it work. See above for documentation on COM registry keys.

**Comment by bclothier** [comment]
> Yes. Nothing the CLR does with respect to COM is a secret, it should all be fully documented. https://docs.microsoft.com/windows/win32/com/com-registry-keys

That is a great article - this has several things documented in one place which is great! But also, this seems incomplete to me. I don't see any comments about TypeLibs nor Records. I believe for VB6 or VBA clients, there must be a TypeLib entry. A CLSID-only registration is a valid COM registration but this is not sufficient for what VB6/VBA requires since they are more of an Automation client. The article should at least explain the minimal requirement for COM registration at every level, especially at Automation level since I think the majority of COM interop will be intended for use with Automation clients such as VB6/VBA.

FWIW, we used Larry's blog as a guide for helping us documenting what is required to successfully register a COM object for use by VB6/VBA clients. 

[COM Registration wiki](https://github.com/rubberduck-vba/Rubberduck/wiki/COM-Registration)
[Larry's blog from where the wiki was based off](https://blogs.msdn.microsoft.com/larryosterman/2006/01/11/what-registry-entries-are-needed-to-register-a-com-object/)

**Comment by adamlonsdale** [comment]
I have managed to call my library via COM after creating a corresponding ProgID and pointing it at the CLSID already created by registering the library. But as you say, TypeLib / Records are not there so I can only late-bind my library, which relies on the entire CLSID being done manually. 

Is it even possible to create a .tlb for a .NET Core application? If I can generate one then I can put the reg keys in manually as a test.

**Comment by bclothier** [comment]
I would think it is, although I have not actually tried it. It's basically just more registry entries. `regasm.exe` supposedly has switch to generate registry entries but it is incomplete, so we use WiX's `heat.exe` to extract the `TypeLib` registration (plus others) and write the registry entries in our installer manually. This enables us to do a proper per-user installation without needing to request an admin elevation. IMO, manually writing registry entries is usually better than using tools like `regasm.exe` because otherwise, we wouldn't be able to do a per-user installation or have control over our installer's behavior.

For actually generating a type library, using [`tlbexp.exe`](https://docs.microsoft.com/en-us/dotnet/framework/tools/tlbexp-exe-type-library-exporter) is sufficient. However, you also have the option of authoring your own type library, which may be helpful if you need more control over how it should get exported. Refer to [TypeLibConverter](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.typelibconverter.convertassemblytotypelib?view=netframework-4.8#System_Runtime_InteropServices_TypeLibConverter_ConvertAssemblyToTypeLib_System_Reflection_Assembly_System_String_System_Runtime_InteropServices_TypeLibExporterFlags_System_Runtime_InteropServices_ITypeLibExporterNotifySink_) for details.

**Comment by AaronRobinsonMSFT** [comment]
>Is it even possible to create a .tlb for a .NET Core application?

TypeLib generation within in .NET Core is not presently supported. This is a rather large work item and the cost in the .NET Core 3.0 time frame did not fit. As @bclothier mentions, generating the TLB from the .NET Framework toolchain is possible in some instances.

**Comment by weltkante** [comment]
@AaronRobinsonMSFT  I've been trying to get ProgID registered but it doesn't seem to work. I'm using todays nightly (5.0.100-alpha1-014067) and would have expected something from last month to be in there. Do I need to do anything special for ProgIDs to get registered? the clsidmap file has a progid entry but after registration I don't see it (I do see the clsid entry)

**Comment by AaronRobinsonMSFT** [comment]
@weltkante Where are you looking for this registration? I pulled it down and was also able to verify the `.clsidmap` contained the `progid` entry. I also stepped through the registration and observed it was properly placed in the registry. What tool are you using to verify the registration?

**Comment by weltkante** [comment]
I've created a new .NET Core class library project and added a dummy class to test this out. I've done a build and publish for 64 bit windows target architecture.

I'm running (64 bit) regsvr32 to register/unregister and use regedit to check the results, looking at the registry for `HKCR\Y.Class1` (which isn't there) but `HKCR\CLSID\{...}` is there. The progid is set to Y.Class1 in the clsidmap and its properly embedded in the dll. If it works for you the only thing I can think of is that the wrong template dll got used.

Thanks for checking that it works on your side, I'll try on another machine and create a separate issue with my repro if I can't get it to work.

**Comment by weltkante** [comment]
@AaronRobinsonMSFT turns out it uses comhost.dll from preview7, I opened #26578 with a binlog attached, something must be wrong with the lookup rules in the build process
