### ISSUE TITLE
Hopefully .net core supports all cpu architectures

### ISSUE THREAD

**Issue by guodf** [dotnet/coreclr#25983]
C#本来是一门优秀的语言，绝对有可能一统江湖，结果一手好牌被打的稀巴烂。
以前因为不开源，处处受到限制，现在因为生态，处处受到限制，未来因为平台，依然会处处受到限制。
从.net到.net core,从.net core到.net 5,我想说你们真的很闲，虽然统一.net这一步意义重大，但是当下环境可能并不是最重要的。
最让人感觉垃圾的地方在于，不停的优化asp.net core，ef core，以及性能上的优化，我想问这些真的很重要吗？难道社区就不能出来做这些吧，好吧，我承认.net社区真的很烂，但是能怪谁呢！.net做的越多，社区做的就越少，可能最后都懒得做了，拿现成的用好了。
尤其是.net在中国的市场，一步步被瓜分，不知道我软是否考虑过原因。
.net core我们已经给了你5年的时间了，结果你也看见了，如果你以为这是绝地重生，我只能说哈哈~~你赢了。
在中国这个市场，不是你想怎么做就怎么做的，如果你跟着政府的步伐走一定会走的很好。
最后，从目前.net/.net core的市场情况来看，优化.net性能并不重要，现在的性能我们可以接收，ef core，asp.net core好不好用我们不在乎，能用就行，我们最关注的是你的可能性，可以在各种cpu架构下运行，支持所有国产操作系统（即使这些系统再垃圾），起码中国的市场还有一部分人愿意守护，维护你。

It would have been an excellent language, it is absolutely possible to unify the river and lake, the result of a good card was beaten with a thin bar.
Previously because not open source, everywhere is restricted, now because of ecology, everywhere is restricted, the future because of the platform, will still be restricted everywhere.
From .net to .net core, from .net core to .net 5, I'd like to say that you're really idle, and while the step of unifying .net is significant, the environment may not be the most important.
What makes people feel most trashy is that it's really important to keep optimizing asp.net core, ef core, and performance optimization. Can't the community come out and do this, well, I admit, the .net community is really bad, but who can blame it! .net do more, the less the community does, and may end up too lazy to do it, get ready-made.
Especially in the Chinese market.net, step by step is divided, do not know whether I soft whether to consider the reason.
.net core we have given you 5 years, the result you also see, if you think this is the Rebirth of the Jedi, I can only say haha - you won.
In This market in China, it's not what you want to do, and if you follow the pace of the government, you'll definitely go well.
Finally, from the current market situation of .net/ .net core, optimization of .net performance is not important, now the performance we can receive, ef core, asp.net core good use we do not care, can use on the line, we are most concerned about your possibility, Can run under a variety of cpu architecture, support all domestic operating systems (even if these systems are garbage), at least china's market there is still some people willing to guard, maintain you.

**Comment by guodf** [comment]
@.net/.net core 
你的未来就在我这个issus上了，想要迎头赶上java，py的生态我们就不奢望了，支持所有平台是你唯一歪道超车的机会。
Your future is on my issus, want to catch up with java, py ecological we do not expect, support all platforms is your only crooked overtaking opportunity.

**Comment by myFirstway** [comment]
Now more and more localization in China, they first adapted to jdk. Now more and more government projects require domestic cpu. Many people have to give up .net and use Java instead. You can see this post http://tieba.baidu.com/p/5626600505.

**Comment by NMSAzulX** [comment]
You're right.

**Comment by huoyaoyuan** [comment]
> C#本来是一门优秀的语言，绝对有可能一统江湖，结果一手好牌被打的稀巴烂。

C#仅仅是主流语言里的优秀者而已，语言特性上还有不少的可改进之处

> 最让人感觉垃圾的地方在于，不停的优化asp.net core，ef core，以及性能上的优化，我想问这些真的很重要吗？难道社区就不能出来做这些吧

你好，真的很重要，社区真的做不出来，因为水平太菜
我们无法忍受用着各种开发效率和运行效率都垃圾的东西了

> .net core我们已经给了你5年的时间了，结果你也看见了，如果你以为这是绝地重生，我只能说哈哈~~你赢了。

本来就不是绝地，中途转型而已，并给出了和旧.net人划清界限的机会

> 尤其是.net在中国的市场，一步步被瓜分，不知道我软是否考虑过原因。

原因是中国还处于软件小农阶段，有工业品概念的人都很少
原先的市场大部分是拖控件和WebForm，这些人根本无法有效转化为现代程序工作者，徒给.net添加坏名而已

> 我们最关注的是你的可能性，可以在各种cpu架构下运行，支持所有国产操作系统（即使这些系统再垃圾）

请问“所有”有多少？拿出一个不是Windows、macOS、linux、FreeBSD的？

> 你的未来就在我这个issus上了，想要迎头赶上java，py的生态我们就不奢望了，支持所有平台是你唯一歪道超车的机会

看看现在C的困境吧，有支持广度又能怎样呢

> Many people have to give up .net and use Java instead. 

Did they **ever** use **real** .net?
Loongnix has a team to support .net on them.


Why Java? Android. Why Python? Tensorflow and PyTorch. Why JavaScript? Chrome.
Make .NET popular? Bring back Windows Phone and Silverlight and make them popular. Make ML.Net better.
The popular languages are never popular themselves.

**Comment by SuperSnowYao** [comment]
> > C#本来是一门优秀的语言，绝对有可能一统江湖，结果一手好牌被打的稀巴烂。
> 
> C#仅仅是主流语言里的优秀者而已，语言特性上还有不少的可改进之处
> 
> > 最让人感觉垃圾的地方在于，不停的优化asp.net core，ef core，以及性能上的优化，我想问这些真的很重要吗？难道社区就不能出来做这些吧
> 
> 你好，真的很重要，社区真的做不出来，因为水平太菜
> 我们无法忍受用着各种开发效率和运行效率都垃圾的东西了
> 
> > .net core我们已经给了你5年的时间了，结果你也看见了，如果你以为这是绝地重生，我只能说哈哈~~你赢了。
> 
> 本来就不是绝地，中途转型而已，并给出了和旧.net人划清界限的机会
> 
> > 尤其是.net在中国的市场，一步步被瓜分，不知道我软是否考虑过原因。
> 
> 原因是中国还处于软件小农阶段，有工业品概念的人都很少
> 原先的市场大部分是拖控件和WebForm，这些人根本无法有效转化为现代程序工作者，徒给.net添加坏名而已
> 
> > 我们最关注的是你的可能性，可以在各种cpu架构下运行，支持所有国产操作系统（即使这些系统再垃圾）
> 
> 请问“所有”有多少？拿出一个不是Windows、macOS、linux、FreeBSD的？
> 
> > 你的未来就在我这个issus上了，想要迎头赶上java，py的生态我们就不奢望了，支持所有平台是你唯一歪道超车的机会
> 
> 看看现在C的困境吧，有支持广度又能怎样呢
> 
> > Many people have to give up .net and use Java instead.
> 
> Did they **ever** use **real** .net?
> Loongnix has a team to support .net on them.
> 
> Why Java? Android. Why Python? Tensorflow and PyTorch. Why JavaScript? Chrome.
> Make .NET popular? Bring back Windows Phone and Silverlight and make them popular. Make ML.Net better.
> The popular languages are never popular themselves.
楼上的，你说许多人放弃了.net，转向了java，这很正常。因为你放弃的是.net，我们现在拥抱的是.netcore，所以，你说的放弃仅仅代表你自己罢了。你为什么如此焦燥呢，.netcore本来就很优秀，.netcore框架之上的各种语言开发效率就是比java高，.netcore的性能就是比java好，更何况，.netcore也支持跨平台，容器化方面也比java更优秀。更重要的是，java及其相应的框架可以搞的，.netcore照搞不误，而且效率高，性能好。所以不要抱着井底之蛙的态度来看待IT行业每一天的变化 ，执迷不悟，不接受新的技术出现，最后受伤的肯定是自己。你可以不用.netcore，但是千万不要说它这不行那不行，因为这只会让已经将它使用到生产中的同行们笑话。

**Comment by SuperSnowYao** [comment]
> > Many people have to give up .net and use Java instead.

楼上的，你说许多人放弃了.net，转向了java，这很正常。因为你放弃的是.net，我们现在拥抱的是.netcore，所以，你说的放弃仅仅代表你自己罢了。你为什么如此焦燥呢，.netcore本来就很优秀，.netcore框架之上的各种语言开发效率就是比java高，.netcore的性能就是比java好，更何况，.netcore也支持跨平台，容器化方面也比java更优秀。更重要的是，java及其相应的框架可以搞的，.netcore照搞不误，而且效率高，性能好。所以不要抱着井底之蛙的态度来看待IT行业每一天的变化 ，执迷不悟，不接受新的技术出现，最后受伤的肯定是自己。你可以不用.netcore，但是千万不要说它这不行那不行，因为这只会让已经将它使用到生产中的同行们笑话。
You said that many people abandoned.net and switched to Java, which is normal.Because you gave up.net, we are now embracing.netcore, so when you say give up, you just mean yourself.Why are you so upset? Netcore is already very good, the development efficiency of various languages on the netcore framework is higher than Java, the performance of netcore is better than Java, what's more, netcore also supports cross-platform, containerization is better than Java.What's more, Java and its corresponding framework can be done correctly.So don't hold the attitude of a frog in a well to look at IT industry changes every day, unrepentant, do not accept the emergence of new technology, the final injury must be yourself.You don't have to use a.netcore, but don't say that it doesn't work or that it doesn't work, because it just makes people laugh at the people who already use it in production.

**Comment by SuperSnowYao** [comment]
> > C#本来是一门优秀的语言，绝对有可能一统江湖，结果一手好牌被打的稀巴烂。
> 
> C#仅仅是主流语言里的优秀者而已，语言特性上还有不少的可改进之处
> 
> > 最让人感觉垃圾的地方在于，不停的优化asp.net core，ef core，以及性能上的优化，我想问这些真的很重要吗？难道社区就不能出来做这些吧
> 
> 你好，真的很重要，社区真的做不出来，因为水平太菜
> 我们无法忍受用着各种开发效率和运行效率都垃圾的东西了
> 
> > .net core我们已经给了你5年的时间了，结果你也看见了，如果你以为这是绝地重生，我只能说哈哈~~你赢了。
> 
> 本来就不是绝地，中途转型而已，并给出了和旧.net人划清界限的机会
> 
> > 尤其是.net在中国的市场，一步步被瓜分，不知道我软是否考虑过原因。
> 
> 原因是中国还处于软件小农阶段，有工业品概念的人都很少
> 原先的市场大部分是拖控件和WebForm，这些人根本无法有效转化为现代程序工作者，徒给.net添加坏名而已
> 
> > 我们最关注的是你的可能性，可以在各种cpu架构下运行，支持所有国产操作系统（即使这些系统再垃圾）
> 
> 请问“所有”有多少？拿出一个不是Windows、macOS、linux、FreeBSD的？
> 
> > 你的未来就在我这个issus上了，想要迎头赶上java，py的生态我们就不奢望了，支持所有平台是你唯一歪道超车的机会
> 
> 看看现在C的困境吧，有支持广度又能怎样呢
> 
> > Many people have to give up .net and use Java instead.
> 
> Did they **ever** use **real** .net?
> Loongnix has a team to support .net on them.
> 
> Why Java? Android. Why Python? Tensorflow and PyTorch. Why JavaScript? Chrome.
> Make .NET popular? Bring back Windows Phone and Silverlight and make them popular. Make ML.Net better.
> The popular languages are never popular themselves.

楼上的，你说许多人放弃了.net，转向了java，这很正常。因为你放弃的是.net，我们现在拥抱的是.netcore，所以，你说的放弃仅仅代表你自己罢了。你为什么如此焦燥呢，.netcore本来就很优秀，.netcore框架之上的各种语言开发效率就是比java高，.netcore的性能就是比java好，更何况，.netcore也支持跨平台，容器化方面也比java更优秀。更重要的是，java及其相应的框架可以搞的，.netcore照搞不误，而且效率高，性能好。所以不要抱着井底之蛙的态度来看待IT行业每一天的变化 ，执迷不悟，不接受新的技术出现，最后受伤的肯定是自己。你可以不用.netcore，但是千万不要说它这不行那不行，因为这只会让已经将它使用到生产中的同行们笑话。
You said that many people abandoned.net and switched to Java, which is normal.Because you gave up.net, we are now embracing.netcore, so when you say give up, you just mean yourself.Why are you so upset? Netcore is already very good, the development efficiency of various languages on the netcore framework is higher than Java, the performance of netcore is better than Java, what's more, netcore also supports cross-platform, containerization is better than Java.What's more, Java and its corresponding framework can be done correctly.So don't hold the attitude of a frog in a well to look at IT industry changes every day, unrepentant, do not accept the emergence of new technology, the final injury must be yourself.You don't have to use a.netcore, but don't say that it doesn't work or that it doesn't work, because it just makes people laugh at the people who already use it in production.

**Comment by SuperSnowYao** [comment]
> > C#本来是一门优秀的语言，绝对有可能一统江湖，结果一手好牌被打的稀巴烂。
> 
> C#仅仅是主流语言里的优秀者而已，语言特性上还有不少的可改进之处
> 
> > 最让人感觉垃圾的地方在于，不停的优化asp.net core，ef core，以及性能上的优化，我想问这些真的很重要吗？难道社区就不能出来做这些吧
> 
> 你好，真的很重要，社区真的做不出来，因为水平太菜
> 我们无法忍受用着各种开发效率和运行效率都垃圾的东西了
> 
> > .net core我们已经给了你5年的时间了，结果你也看见了，如果你以为这是绝地重生，我只能说哈哈~~你赢了。
> 
> 本来就不是绝地，中途转型而已，并给出了和旧.net人划清界限的机会
> 
> > 尤其是.net在中国的市场，一步步被瓜分，不知道我软是否考虑过原因。
> 
> 原因是中国还处于软件小农阶段，有工业品概念的人都很少
> 原先的市场大部分是拖控件和WebForm，这些人根本无法有效转化为现代程序工作者，徒给.net添加坏名而已
> 
> > 我们最关注的是你的可能性，可以在各种cpu架构下运行，支持所有国产操作系统（即使这些系统再垃圾）
> 
> 请问“所有”有多少？拿出一个不是Windows、macOS、linux、FreeBSD的？
> 
> > 你的未来就在我这个issus上了，想要迎头赶上java，py的生态我们就不奢望了，支持所有平台是你唯一歪道超车的机会
> 
> 看看现在C的困境吧，有支持广度又能怎样呢
> 
> > Many people have to give up .net and use Java instead.
> 
> Did they **ever** use **real** .net?
> Loongnix has a team to support .net on them.
> 
> Why Java? Android. Why Python? Tensorflow and PyTorch. Why JavaScript? Chrome.
> Make .NET popular? Bring back Windows Phone and Silverlight and make them popular. Make ML.Net better.
> The popular languages are never popular themselves.

楼上的，你说许多人放弃了.net，转向了java，这很正常。因为你放弃的是.net，我们现在拥抱的是.netcore，所以，你说的放弃仅仅代表你自己罢了。你为什么如此焦燥呢，.netcore本来就很优秀，.netcore框架之上的各种语言开发效率就是比java高，.netcore的性能就是比java好，更何况，.netcore也支持跨平台，容器化方面也比java更优秀。更重要的是，java及其相应的框架可以搞的，.netcore照搞不误，而且效率高，性能好。所以不要抱着井底之蛙的态度来看待IT行业每一天的变化 ，执迷不悟，不接受新的技术出现，最后受伤的肯定是自己。你可以不用.netcore，但是千万不要说它这不行那不行，因为这只会让已经将它使用到生产中的同行们笑话。
You said that many people abandoned.net and switched to Java, which is normal.Because you gave up.net, we are now embracing.netcore, so when you say give up, you just mean yourself.Why are you so upset? Netcore is already very good, the development efficiency of various languages on the netcore framework is higher than Java, the performance of netcore is better than Java, what's more, netcore also supports cross-platform, containerization is better than Java.What's more, Java and its corresponding framework can be done correctly.So don't hold the attitude of a frog in a well to look at IT industry changes every day, unrepentant, do not accept the emergence of new technology, the final injury must be yourself.You don't have to use a.netcore, but don't say that it doesn't work or that it doesn't work, because it just makes people laugh at the people who already use it in production.

**Comment by NMSAzulX** [comment]
> 楼上的，你说许多人放弃了.net，转向了java，这很正常。因为你放弃的是.net，我们现在拥抱的是.netcore，所以，你说的放弃仅仅代表你自己罢了。你为什么如此焦燥呢，.netcore本来就很优秀，.netcore框架之上的各种语言开发效率就是比java高，.netcore的性能就是比java好，更何况，.netcore也支持跨平台，容器化方面也比java更优秀。更重要的是，java及其相应的框架可以搞的，.netcore照搞不误，而且效率高，性能好。所以不要抱着井底之蛙的态度来看待IT行业每一天的变化 ，执迷不悟，不接受新的技术出现，最后受伤的肯定是自己。你可以不用.netcore，但是千万不要说它这不行那不行，因为这只会让已经将它使用到生产中的同行们笑话。

转JAVA是事实，不管是.NET Core还是.NET,  对.NETCore 也没必要太理想化，众多特性都在开发中，让官方意识到中国市场在发生变化，我认为是件有必要的事情。
Switching to JAVA is a fact, and whether it's. Net Core or. Net, we don't have to be too idealistic about. Net Core. Many features are under development. It is necessary for the authorities to realize that the Chinese market is changing.

**Comment by fawdlstty** [comment]
This can actually be done by the community.All you need to do is compile the coreclr on the target platform

**Comment by guodf** [comment]
> This can actually be done by the community.All you need to do is compile the coreclr on the target platform

Need to adapter to the operating system? Just compile it?

**Comment by fawdlstty** [comment]
Compile and run successfully. Issue if you encounter other problems later

**Comment by huoyaoyuan** [comment]
> Need to adapter to the operating system? Just compile it?

As I know, all the "custom" OSes used in production are based on Linux/BSD. No additional adaption is required.

**Comment by fawdlstty** [comment]
> As I know, all the "custom" OSes used in production are based on Linux/BSD/Windows IoT(CE). No additional adaption is required.
And RTOS such as VxWorks etc.

**Comment by guodf** [comment]
首先，感谢各位的捧场！
其次，跟.net core团队致歉，我说话有点难听，对不起，Sorry！

我不知道.net core支持不支持龙芯、mips这类架构的cpu，之前看论坛确实有人尝试过，但是没有成功。

我认为每种cpu架构的指令会有些许的区别，如果要适配可能需要.net core团队加入特定的cpu指令，我想这是一个C#程序员搞不定的地方，对着编译教程能编译通过就是一件不容易的事了，更别想自己适配cpu指令了。

希望有能力的人尽早加入.net core的开源社区多多贡献吧，也希望.net core越来越好，早日实现自己心中的目标。

_为了显示我道歉的诚意，就不翻译。_

**Comment by SuperSnowYao** [comment]
> 转JAVA是事实，不管是.NET Core还是.NET, 对.NETCore 也没必要太理想化，众多特性都在开发中，让官方意识到中国市场在发生变化，我认为是件有必要的事情。
> Switching to JAVA is a fact, and whether it's. Net Core or. Net, we don't have to be too idealistic about. Net Core. Many features are under development. It is necessary for the authorities to realize that the Chinese market is changing.
是什么事实，只知道转JAVA里面也有大批量混水摸鱼者，开发效率低下。就想不明白了，有了更好的，更通用的，效率更高的开发语言和框架，非要背道而驰。.netcore本来就是很优秀的，这就是事实。一句话，用不用随便，做技术的讲究事实求是，看效率，看结果的。JAVA在国内效果好一些，是因为这几个大厂当靶子，仅此而矣。后面看结果就是了。

**Comment by xhk** [comment]
支持各种cpu、操作系统的活，C#程序员就不用操心了，交给C/C++程序员就好了。

**Comment by guodf** [comment]
> 支持各种cpu、操作系统的活，C#程序员就不用操心了，交给C/C++程序员就好了。

我们默默的给你加油！！！

**Comment by xhk** [comment]
少说话多做事，空谈误国，实干兴邦。

**Comment by guodf** [comment]
我要是有那误国的本事还担心它能不能再龙芯下运行

**Comment by NMSAzulX** [comment]
国人的issue总是能引杠精过来内战，我快特么忍不住要喷人了。

**Comment by NMSAzulX** [comment]
> > 转JAVA是事实，不管是.NET Core还是.NET, 对.NETCore 也没必要太理想化，众多特性都在开发中，让官方意识到中国市场在发生变化，我认为是件有必要的事情。
> > Switching to JAVA is a fact, and whether it's. Net Core or. Net, we don't have to be too idealistic about. Net Core. Many features are under development. It is necessary for the authorities to realize that the Chinese market is changing.
> > 是什么事实，只知道转JAVA里面也有大批量混水摸鱼者，开发效率低下。就想不明白了，有了更好的，更通用的，效率更高的开发语言和框架，非要背道而驰。.netcore本来就是很优秀的，这就是事实。一句话，用不用随便，做技术的讲究事实求是，看效率，看结果的。JAVA在国内效果好一些，是因为这几个大厂当靶子，仅此而矣。后面看结果就是了。

清醒一点，如果你真的有办法就先稳住国内的市场。人不努力，还看什么结果，坐等么？

**Comment by SuperSnowYao** [comment]
> > > 转JAVA是事实，不管是.NET Core还是.NET, 对.NETCore 也没必要太理想化，众多特性都在开发中，让官方意识到中国市场在发生变化，我认为是件有必要的事情。
> > > Switching to JAVA is a fact, and whether it's. Net Core or. Net, we don't have to be too idealistic about. Net Core. Many features are under development. It is necessary for the authorities to realize that the Chinese market is changing.
> > > 是什么事实，只知道转JAVA里面也有大批量混水摸鱼者，开发效率低下。就想不明白了，有了更好的，更通用的，效率更高的开发语言和框架，非要背道而驰。.netcore本来就是很优秀的，这就是事实。一句话，用不用随便，做技术的讲究事实求是，看效率，看结果的。JAVA在国内效果好一些，是因为这几个大厂当靶子，仅此而矣。后面看结果就是了。
> 
> 清醒一点，如果你真的有办法就先稳住国内的市场。人不努力，还看什么结果，坐等么？
你不行就是不行，看什么结果？看你OVER的结果。还坐等，你有坐等的机会吗？

**Comment by SuperSnowYao** [comment]
> 国人的issue总是能引杠精过来内战，我快特么忍不住要喷人了。

你喷啊，大家看你喷。你就是一个废青。你说别人是杠精，我看你才是高纯度杠精。

**Comment by NMSAzulX** [comment]
> > 国人的issue总是能引杠精过来内战，我快特么忍不住要喷人了。
> 
> 你喷啊，大家看你喷。你就是一个废青。你说别人是杠精，我看你才是高纯度杠精。

拜拜
