### ISSUE TITLE
Audit all the usages of the cached stack limits

### ISSUE THREAD

**Issue by sergiy-k** [dotnet/coreclr#2606]
As we have recently discovered, getting the correct value for thread’s stack limit is problematic on Unix platforms. For example: https://github.com/dotnet/coreclr/issues/2467.

In addition, there was an OS bug introduced in OS X 10.9 that causes the pthread_get_stacksize_np() function to always return 512K for the main thread (even though the default stack size of the main thread is 8MB). Besides, it disregards the value that has been set by “ulimit -s”. This issue exists on OSX 10.9 and 10.10 but seems to be fixed on 10.11.

So we need to audit all the usages of the cached stack limits and fix the ones that matter using similar means like in #2573 or some other ways (e.g. for the current thread using the current SP as the limit instead of the cached value).

**Comment by janvorli** [comment]
I've audited all the usages of Thread::GetCachedLimit (and Thread::m_cacheLimit) and PAL_GetStackLimit. I have found the following usage patterns:
1. Checking whether a stack pointer is inside of a stack for debugging purposes. The case when the cached stack limit is lower than the actual stack limit doesn't break anything, it just opens a possibility of the test passing in case the address is in area that was removed from the original stack range.
2. Checks that are never executed on CoreCLR and checks that are never executed on Unix

So there is no place like the one fixed in #2467 where the exact detection of whether an address is in a stack or not would be crucial.

The cases where we check whether a stack pointer is inside of a stack can be split into two categories:
1. Checks performed for the current thread. Those can easily be changed to use current SP as the stack limit, which makes them precise and still cheap.
2. Checks performed for other threads. We could possibly add support for extracting the current stack limit for an arbitratry thread to PAL, but we have learned in the past that getting the stack limit is an expensive operation. So using that would make sense only in cases that are not performance sensitive.

**Comment by janvorli** [comment]
Implemented change for checking stack range for current thread in #2660

**Comment by janvorli** [comment]
I've prototyped a change that implements checks for other threads than the current one - getting the stack range dynamically. The perf hit in debug build was 30% (no hit in release build since these checks were debug build only) and it is also worth mentioning that unless the stack size is set to unlimited, it doesn't add any benefit, since the cached static values are equal to what we would get from the dynamic calls. So I believe it is not worth it and I'm closing this issue.
