### ISSUE TITLE
Using coreclr profiling api how to get the return values of functions which returns Stream

### ISSUE THREAD

**Issue by Gopinath-mahadevan** [dotnet/coreclr#26332]
I'm implementing a dotnet profiler which implements ICorProfilerCallback2. I'm trying to monitor return values of functions. On the function exit hook I'm able to get the return values of functions if its return type is string.

One of the methods return type is System.IO.Stream. How can I get the content from the stream which is returned by the function.

**Comment by jeffschwMSFT** [comment]
@tommcdon

**Comment by tommcdon** [comment]
@davmason

**Comment by davmason** [comment]
Hi @Gopinath-mahadevan,

There isn't going to be an easy way to get the contents of a stream like a string. String is a special case managed object since it is implemented in native code and a profiler can grab a pointer to the buffer and read its contents.

A stream could be reading from any arbitrary data source. It could be reading from a file on disk, from memory, from the network, and so on. There isn't a convenient text buffer you can just grab. It's possible when you go to inspect it that the stream won't have any data read in memory and it's all still on disk/network/etc.

Using the profiler APIs it would be technically possible, with `IMetaDataImport::EnumFields` to get the class layout,  and then calling `ICorProfilerInfo2:GetClassLayout` to know which offsets the fields map to, then recursively walking the data structures until you find what you need.

I **do not** recommend this approach though. You would have to work out how to read all the different stream types and it would be very fragile and anytime the implementation of them changes you would have to update your code.

A less fragile approach would be to use IL rewriting to hook the method and read the value of the stream. Although you would still have to be careful to leave the stream in the state you found it (i.e. if you advance the stream return it to the original position).

We have some documentation about IL rewriting in the profiler documentation folder.
[Module Load Instrumentation](https://github.com/dotnet/coreclr/blob/master/Documentation/Profiling/davbr-blog-archive/Creating%20an%20IL-rewriting%20profiler.md)
[ReJIT Basics](https://github.com/dotnet/coreclr/blob/master/Documentation/Profiling/davbr-blog-archive/ReJIT%20-%20The%20Basics.md)

**Comment by Gopinath-mahadevan** [comment]
Hi @davmason ,
Thanks. I'm not familiar with profiling api and IL rewriting. I'll go through the docs and try it.

In my method, byte array is passed in method argument and after few process it will be returned as steam.

Instead of getting the value from stream object on return type, I think it will be easy to read the value from byte array which is passed as the function argument.

How can I find the offset and memory address of the content in the byte[] using COR_PRF_FUNCTION_ARGUMENT_INFO on method enter? It will be helpful if there is any document or sample code available for this.

**Comment by noahfalk** [comment]
I think the question was answered so going to close this.
