### ISSUE TITLE
interpreter has bug about CEE_LDLOC_0?

### ISSUE THREAD

**Issue by pirunxi** [dotnet/coreclr#26427]
issue code is at line 2008 in interpreter.cpp, lastest master branch . show above:
       case CEE_LDLOC_0:
            LdLoc(0);
            m_ILCodePtr++;
            continue;
        case CEE_LDLOC_1:
            LdLoc(1);
            break;
        case CEE_LDLOC_2:
            LdLoc(2);
            break;
why it processes CEE_LDLOC_0 need a extra "m_ILCodePtr++;"？ is it a bug ?

**Comment by mikedn** [comment]
Not a bug, just confusing code. In other cases `break` is used to break out of the switch and reach the `m_ILCodePtr++;` after the switch. In the case of  `CEE_LDLOC_0`, `m_ILCodePtr++;` is done right there and `continue` is used instead of `break`.

While the interpreter isn't actually used, there have been attempts to enable it and it's unlikely that such a "bug" would have passed unnoticed.

**Comment by BruceForstall** [comment]
One guess for why it was done this way is it is (slightly) faster.
