### ISSUE TITLE
IFormatProvider is passed into a function but never referenced. Seems odd

### ISSUE THREAD

**Issue by mlevinmail** [dotnet/coreclr#26585]
https://github.com/dotnet/coreclr/blob/456afea9fbe721e57986a21eb3b4bb1c9c7e4c56/src/System.Private.CoreLib/shared/System/Boolean.cs#L93

**Comment by svick** [comment]
It might be odd, but I don't see anything wrong here. The method has to exist, because `Boolean` implements `IConvertible` (though I'm not sure why the method isn't an explicit interface implementation, like the other `IConvertible` methods). But the rules for formatting `Boolean` are so simple that there is no room to use the `IFormatProvider`, so it's not used.
