### ISSUE TITLE
CPAOT - re-enable vtable calls within CoreLib

### ISSUE THREAD

**Issue by trylek** [dotnet/coreclr#26629]
We need to temporarily disable the optimization regarding vtable calls in CoreLib because it requires either re-implementing the CoreCLR method table builder in CPAOT or persisting the vtable layouts in the R2R image. Neither technology exists today. We however need to re-enable this optimization before shipping because the optimization is important for CoreLib performance and needed for letting us publish R2R (instead of fragile NGEN) CoreLib.

The bit of code I am commenting out is in ceeInfoGetCallInfo in CorInfoImpl.ReadyToRun.cs around line 1070 under the conditional clause

<code>
if (MethodInSystemVersionBubble(callerMethod) && MethodInSystemVersionBubble(targetMethod))
</code>

**Comment by fadimounir** [comment]
Closing this issue since we don't need to implement it for the CPAOT compiler.
The runtime is able to generate vtable-based jump stubs instead of VSD based vtable calls (wasn't the case when I initially made the change for s.p.corelib), and this is good enough. Porting all the MethodTable based complexities to the CPAOT compiler will not be worth it.
