### ISSUE TITLE
ExceptionDispatchInfo.Throw() restores the wrong debugger call stack

### ISSUE THREAD

**Issue by smoogipoo** [dotnet/coreclr#26760]
With the following code:

```
static void Main(string[] args)
{
    ExceptionDispatchInfo dispatchInfo;

    try
    {
        throw new Exception(); // Line 16
    }
    catch (Exception ex)
    {
        dispatchInfo = ExceptionDispatchInfo.Capture(ex);
    }

    dispatchInfo.Throw(); // Line 23
}
```

The exception's callstack is correctly preserved as:

```
Exception has occurred: CLR/System.Exception
An unhandled exception of type 'System.Exception' occurred in System.Private.CoreLib.dll
   at CrossThreadExceptionRethrowTest.Program.Main(String[] args) in /Users/smoogipoo/Workbench/CrossThreadExceptionRethrowTest/CrossThreadExceptionRethrowTest/Program.cs:line 16
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at CrossThreadExceptionRethrowTest.Program.Main(String[] args) in /Users/smoogipoo/Workbench/CrossThreadExceptionRethrowTest/CrossThreadExceptionRethrowTest/Program.cs:line 23
```

But the debugger callstack shows:
![image](https://user-images.githubusercontent.com/1329837/65123790-fc6f1580-da2e-11e9-8e8e-77a3897531db.png)
I would think that "line 16" should be shown in the debugger callstack, but it's completely missing - perhaps it's lost in the `[External Code]` frames?

The same is exhibited on all of:
netcore2.2
netcore3.0
mono 6.0.0
netframework 4.7.2

This is a very simplified reproduction case, but is this the wrong way of rethrowing exceptions? And if so is there a way to capture an exception and rethrow it while preserving the debugger-visible call stack?

I've also tested on the following IDEs, all showing the same results:
VSCode (macOS)
Visual Studio 2019 (Windows)
JetBrains Rider (macOS)

**Comment by noahfalk** [comment]
It sounds like you want the debugger to stop at line 16 and notify you of the first chance exception. It is capable of doing that, but it isn't the default configuration. To get the behavior you want:

1) Use Debug->Windows->Exception Settings (Ctrl+Alt+E)
2) In window which pops up, navigate in the tree control to 'Common Language Runtime Exceptions' -> System.Exception and check the box:
![image](https://user-images.githubusercontent.com/6243776/68293211-5c9f3280-0042-11ea-873f-74ad97281db1.png)

You could alternatively check the top level box for 'Common Language Runtime Exceptions' if you want the debugger to notify you when any managed exception is thrown as opposed to only the System.Exception type.

After changing this setting running the debugger again will stop on line 16:
![image](https://user-images.githubusercontent.com/6243776/68293420-c15a8d00-0042-11ea-93e2-19e3d5edfe42.png)

And the callstack will also report line 16:
![image](https://user-images.githubusercontent.com/6243776/68293528-f49d1c00-0042-11ea-8df3-47bf06300763.png)


The behavior you were seeing is that at line 16 the debugger logs a message to the output window indicating an exception was thrown but it does not display a dialog or stop the app because it can determine that the exception will be caught. The program continues executing, the exception is caught at line 18, then re-thrown at line 23. This time the exception is not caught so the debugger stops the program and displays the unhandled dialog. The callstack is correct in reporting line 23 because that is where the thread has executed to. The stack trace shown in the exception object is a historical record of every time the exception object has been rethrown. The line 16 recorded there in the past does not conflict with execution of the program being at line 23 in the present. Hope this helps!

**Comment by noahfalk** [comment]
I'm going to close this issue because I don't think there is any bug to be fixed, but do let us know if that was premature. Thanks!
