### ISSUE TITLE
CoreCLR should handle SIGTERM as equivalent to Environment.Exit()

### ISSUE THREAD

**Issue by stephentoub** [dotnet/coreclr#2688]
SIGTERM is meant to be used for graceful shutdown of an app.  The runtime should handle it by doing the equivalent of Environment.Exit().  Then with https://github.com/dotnet/corefx/issues/5205, apps will also be able to plug in their own cleanup that'll be triggered on any graceful shutdown, including those triggered by SIGTERM.

As an example, ```docker stop``` will initially send a SIGTERM to give the app a chance to gracefully shutdown before it eventually then sends SIGKILL if the process is still alive.
https://github.com/aspnet/Hosting/issues/516

**Comment by masonwheeler** [comment]
On Windows, a graceful shutdown request is a *request*, generally provided by the user hitting ALT-F4 or clicking the red X.  In many cases it is inappropriate to call a shutdown routine at this point; rather you need to confirm with the user and give them the chance to save and/or cancel shutdown.  (There's nothing graceful about having the application pulled out from under you; from the end-user's perspective that's a crash, not a graceful shutdown.)

We should do our best to maintain consistency across platforms.  SIGTERM should be treated as a polite request to shut down, to be handled in an application-defined manner, not as a kill switch that automatically calls `Environment.Exit`.

**Comment by stephentoub** [comment]
> not as a kill switch that automatically calls Environment.Exit.

Right now SIGTERM isn't handled at all, so it's a kill switch that's even less graceful than calling Exit, running any Unloading event handlers, etc.

**Comment by masonwheeler** [comment]
>Right now SIGTERM isn't handled at all, so it's a kill switch that's even less graceful than calling Exit, running any Unloading event handlers, etc.

Fair enough.  I'm just saying that if we want to handle this, it's important to get it right, no?

**Comment by stephentoub** [comment]
> Fair enough. I'm just saying that if we want to handle this, it's important to get it right, no?

My thinking is this:
- The current state is the worst: it's supposed to be graceful, but because the signal isn't handled at all, the default handling kicks in and the app is simply terminated.
- We can change make a relatively small but impactful change that at least allows the system's normal shutdown to take place, including executing any cleanup handlers the app has registered.  libcoreclr can register a signal handler if no other handler has been registered, making it a pure step forward.  This doesn't require any additional APIs.
- At some point in the future if/when if when we provide specialized APIs for signal handling, they can be used to override the default handling.

I don't see us designing, implementing, and shipping that last bullet for an initial release.  But since it can be done purely additively on top of the second bullet, I think we should do the second bullet, as in my mind it's significantly better than the first and for relatively little work.

**Comment by adityamandaleeka** [comment]
Done with #4309

**Comment by stephentoub** [comment]
Thanks.

**Comment by tugberkugurlu** [comment]
@adityamandaleeka, @stephentoub might not be relevant here but how should I listen on `SIGTERM` on a .NET Core console application? My app level entry point accepts `CancellationToken` and I am planning to trigger a cancellation through a `CancellationTokenSource` when I receive `SIGTERM` in my static `Main` method.

**Comment by tugberkugurlu** [comment]
Maybe https://github.com/dotnet/coreclr/issues/2688#issuecomment-216841213 is related to https://github.com/dotnet/corefx/issues/3188?

**Comment by tugberkugurlu** [comment]
> might not be relevant here but how should I listen on SIGTERM on a .NET Core console application?

A few other places like https://github.com/Microsoft/vsts-agent/issues/215 suggests that `AssemblyLoadContext.Default.Unloading` is where one would hook into `SIGTERM` but it doesn't seem to be working for me.

**Comment by nathan-alden** [comment]
I am wondering the same thing, @tugberkugurlu. There was a lot of discussion on the implementation details but I can't find any guidance on how I should be implementing graceful shutdown in a .NET Core console application so it behaves the same on any OS.

**Comment by axelbodo** [comment]
With AssemblyLoadContext.Default.Unloading literally you are enabled to place a shutdown hook, so imo it is a question in what state the runtime is in that point. A related queston which I not found here: When I call IApplicationLifeTime.StoppApplication in other place than the Unloading event (e.g. ina controller handler), after the unloading executes, the Kestler will throw an ObjectDisposedException and the ServiceProvider I've created won't call any Dispose on any singleton. there is a related stackoverflow question, but as I see StopApplication suffers from the same issue than the original requestor's problem.

**Comment by kouvel** [comment]
Finalizers don't run on shutdown in .NET Core, so if the finalizer calls `Dispose` and the object is held in a static field or is otherwise reachable, `Dispose` won't be called on shutdown. See dotnet/corefx#5205 for more details.

If you have unmanaged resources that need to be cleaned up on graceful shutdown, the `Unloading` event can be handled to do so. Since other code may run during or after this, this cleanup and consumers of the unmanaged resources may need to be hardened for this possibility.

**Comment by Mattacks** [comment]
@kouvel 
I’m trying to understand how our .Net Asp.Net Core MVS system should gracefully handle SIGTERM and SIGKILL events when running in Kubernetes.

All the posts I read on SO and GitHub seem to contradict each other.


[This post  ](https://stackoverflow.com/questions/38291567/killing-gracefully-a-net-core-daemon-running-on-linux)says use AssemblyLoadContext.Default.Unloading, then to use AppDomain.CurrentDomain.ProcessExit

But the official documentation is vague and ambiguous.
[AppDomain.CurrentDomain.ProcessExit ](https://docs.microsoft.com/en-us/dotnet/api/system.appdomain.processexit?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(System.AppDomain.ProcessExit)%3Bk(SolutionItemsProject)%3Bk(SolutionItemsProject)%3Bk(SolutionItemsProject)%3Bk(DevLang-csharp)%26rd%3Dtrue&view=netcore-2.1)‘Occurs when the default application domain's parent process exits.’
[AssemblyLoadContext.Default.Unloading ](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.loader.assemblyloadcontext.unloading?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(System.Runtime.Loader.AssemblyLoadContext.Unloading);k(SolutionItemsProject);k(SolutionItemsProject);k(SolutionItemsProject);k(DevLang-csharp)%26rd%3Dtrue&view=netcore-2.1)(no documentation at all)

In the former it says one has 2 seconds to do the work, but [here ](https://stackoverflow.com/questions/40391164/kubernetes-services-connection-draining#40395664)it says in Kubernetes one has 30 seconds.
The discussion in coreclr git are a mess. [Here](https://github.com/dotnet/coreclr/issues/7394), for example, it talks about having to look for a keypress event!

How do we do this bit: ‘The system [Kubernetes] waits terminationGracePeriodSeconds (default 30s), or until the Pod completes on it's own.’?

Please could we have some official advice?
Thanks
Matt

**Comment by kouvel** [comment]
> gracefully handle SIGTERM and SIGKILL events

According to [this](http://man7.org/linux/man-pages/man2/signal.2.html), SIGKILL can't be caught or ignored.

SIGTERM raises the `AssemblyLoadContext.Default.Unloading` and `AppDomain.CurrentDomain.ProcessExit` events. The equivalent on Windows is CTRL_CLOSE_EVENT.

The events above are equivalent. The `Unloading` event was added when `AppDomain` was initially not going to be exposed in the .NET Core API. That has since changed, so now both events exist.

At the point when these events are raised, nothing significant has been torn down yet, so the event handlers should be able to do most things. Those events are currently raised on the finalizer thread, so finalizers can't be relied upon, even with `GC.WaitForPendingFinalizers()`. Probably would be good to raise those events on a different thread in the future.

Any exception thrown by an event handler will crash the process.

SIGINT and SIGQUIT are currently treated as abrupt termination and do not raise the events above.

> AssemblyLoadContext.Default.Unloading (no documentation at all)

Thanks for pointing that out, I'll file an issue.

> In the former it says one has 2 seconds to do the work

That is for .NET Framework, the docs need to be updated, I'll file an issue. .NET Core currently does not time-out the event handlers above, though that may change in the future.

> but here it says in Kubernetes one has 30 seconds.
> How do we do this bit: ‘The system [Kubernetes] waits terminationGracePeriodSeconds (default 30s), or until the Pod completes on it's own.’?

Kubernetes may have its own timeout but that's separate and not in .NET Core's control. The parent of the .NET Core process may for instance issue a SIGTERM and if the process does not exit within a timeout the parent may issue a SIGKILL. A parent process may do something like that to ensure that a child process is torn down in a timely manner. It may be possible to configure the timeout, you'd have to consult the container's docs.

> The discussion in coreclr git are a mess. Here, for example, it talks about having to look for a keypress event!

Yea there was a time when SIGTERM was not handled. There was some other bug related to handling the CancelKeyPress event, I don't remember the details. You can ignore these.

**Comment by stephentoub** [comment]
> SIGINT and SIGQUIT are currently treated as abrupt termination and do not raise the events above.

But will also raise the Console.CancelKeyPress event, which can override that termination.

**Comment by kouvel** [comment]
I was just editing to add that above :)

**Comment by Mattacks** [comment]
@kouvel @stephentoub Perfect answer for me, thanks.
