### ISSUE TITLE
Is it possible to specify the code blocks that are most used to JIT in order to let it optimize those blocks?

### ISSUE THREAD

**Issue by faruknane** [dotnet/coreclr#26935]
I have been learning a lot these days and heard of JIT optimizes codes based on their statistical information like how frequently they are used by letting the code work without optimization by a few times and measuring it. Some codes are not optimized to keep the memory usage(edit: memory space on disk mostly) lower for example and some codes needs to be optimized at most to gain performance. Before JIT testing my code statistics, can I inform JIT that some methods need to be optimized the most? So it performs at best from the beginning. By this way, I don't need to wait it (compiler) to explore which codes need optimizing. 

Example I have a method A();
Run A 20 times -> 450ms
Run A 2000 times -> 36000ms

So can I somehow inform JIT that when I run A 20 times, it takes 360ms? 

Note: [MethodImpl(MethodImplOptions.AggressiveInlining | MethodImplOptions.AggressiveOptimization)] these doesn't help to do so.

**Comment by faruknane** [comment]
What's going on @GrabYourPitchforks ? It shouldn't be hard to reply like yes we have that feature or no we have not developed it yet :(

**Comment by GrabYourPitchforks** [comment]
I don't know the answer to your question. All I did was categorize it so that the area owners see it when next they triage issues. Since the issue was opened over a weekend nobody has had time to look into it yet.

**Comment by faruknane** [comment]
Thank you sir, you are right. Sorry for my ignorance @GrabYourPitchforks

**Comment by AndyAyersMS** [comment]
Similar in spirit to #6024.

Not sure if you are talking about exclusive time (time spent in `A` only) or inclusive time (time spent in `A` and all the methods and runtime mechanisms it invokes).

Just knowing that a method like `A` takes a long time to execute (or rather, that its execution time dominates performance) is not as useful in improving perf as one would hope. While we could enable more aggressive optimization, it would still be a guessing game as to what optimizations might matter. And we would guess wrong most of the time.

What would be more useful is a way to provide profile feedback so the jit can better understand why methods (or what parts of methods) are slow to execute, so that we can focus the optimization better.

**Comment by jkotas** [comment]
> can I inform JIT that some methods need to be optimized the most? So it performs at best from the beginning

This is exactly what `[MethodImpl(MethodImplOptions.AggressiveOptimization)]` does (more details in https://github.com/dotnet/corefx/issues/32235).

**Comment by faruknane** [comment]
@AndyAyersMS So here is what I have understood, even If JIT knows what should be optimized, it still doesn't know how to optimize. So instead of letting JIT know only what to optimize, we should provide how to optimize it as well right?

@jkotas Thank you!

**Comment by AndyAyersMS** [comment]
I'm skeptical that we can rely on additional annotations and programmer-provided hints to profitably guide jit optimizations. There may be some room for it in places, but as a whole it just seems to add complexity and confusion. Much of what you'd ask the jit to do you can do yourself in source.

A system that can provide feedback to the jit automatically by observing program behavior seems preferable.
