### ISSUE TITLE
Suboptimal codegen for delegate invocation in static methods

### ISSUE THREAD

**Issue by omariom** [dotnet/coreclr#26973]
The delegate reference  is [spilled](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gOgCUBXAOwwEt8YLAMIR8AB14AbGFADKMgG68wMXAG4aNZkiakGQmgG8aDUwwDaAWRgYAFhAAmASXGSAFNbuOXYyQHkxPgguXBYAQQBzCNhcXF4FGAC+fF4AL2wgrgBKAF0TMzEoeIyYJnIdXh4GABEYaQiSoWxJaSg3YgBWAB5KjAA+Bgc6rIZ802NqMymmAHZBurcRgGoGcg1JswBfGm3qGiA).

```ASM
    sub rsp, 0x28

    mov [rsp+0x20], rcx
    mov rcx, [rcx+0x8]
    mov rax, [rsp+0x20]
    call qword [rax+0x18]

    inc eax
    add rsp, 0x28
    ret
```

The call site could be 
```ASM
    mov rax, rcx
    mov rcx, [rcx+0x8]
    call qword [rax+0x18]
```

**Comment by omariom** [comment]
Well.. it happens only when the delegate is the first parameter. A very corner case  ¯\_(ツ)_/¯

**Comment by mikedn** [comment]
> it happens only when the delegate is the first parameter

Yes, because that goes in `rcx` and then the delegate's first parameter also goes in `rcx` so they interfere. If it's not the first param then it's not in `rcx` and it all works fine (well, at least until the delegate has more parameters):
```asm
G_M55886_IG01:
       4883EC28             sub      rsp, 40
G_M55886_IG02:
       488B4A08             mov      rcx, gword ptr [rdx+8]
       FF5218               call     qword ptr [rdx+24]System.Func`1[Int32][System.Int32]:Invoke():int:this
       FFC0                 inc      eax
G_M55886_IG03:
       4883C428             add      rsp, 40
       C3                   ret
```

This is a rather unlucky case or IR ordering and register allocation - since loads can be reordered the generated code could be:
```asm
    mov rax, [rax+0x18]
    mov rcx, [rcx+0x8]
    call rax
```
but then that's probably tricky to get right. Might be easier for the register allocator to spill to a register instead of the variable home location, like you show in your example.

**Comment by omariom** [comment]
Closing it as I don't think it is worth the efforts.
