### ISSUE TITLE
Assembly.LoadFile blocks for ~50sec

### ISSUE THREAD

**Issue by cheesi** [dotnet/coreclr#26974]
Hey!

I'm currently porting our application to .NET Core 3.0 from .NET Core 2.2.

Our application has a plugin system and loads all DLLs from a specified folder with `AssemblyLoadContext.Default.LoadFromAssemblyPath();`

And we have the following files in our plugin folder:

- plugin-x.dll
- plugin-y.dll
- plugin-z.dll
- plugin-wrapper-native.dll
- native-plugin.dll

As you can see, we have four plugins, of which one is a wrapper and will call the native Delphi dll in the same folder.

This is our code to load the assemblies:
```csharp
try
{
	Assembly assembly = AssemblyLoadContext.Default.LoadFromAssemblyPath(dllFile);
	if (assembly != null)
	{
		assemblies.Add(assembly);
	}
}
catch (BadImageFormatException)
{
	_Logger.LogTrace("Could not load DLL: {dllFile}", dllFile);
}
```

With .NET Core 2.2, everything worked fine, in .NET Core 3.0, however, the `AssemblyLoadContext.Default.LoadFromAssemblyPath` takes about **48sec** to throw the `BadImageFormatException`, which is kind of too long.

The exception:
```
System.BadImageFormatException: Bad IL format.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at CompanyCode.LoadPlugins()
```

Systeminfo: Dell XPS 15, latest Windows 10, .NET Core 3.0.100

Let me know, if I can do anything to help to resolve this problem. (especially if you want the dll to test it, as I can't really provide it here publicly).

BR Christian

**Comment by jkotas** [comment]
To start diagnosing this, could you please help us find out where the process is blocked for the 48s by attaching unmanaged debugger (Windows Debugger or Visual Studio).

Here are the detailed steps for Visual Studio:

- When the process is blocked inside the Load call, find it in Task Manager Details view, right click and select "Create dump file"

Inside Visual Studio:
- Select "Debug / Options" in the Visual Studio menu, select "Debugging / Symbols" property page and enable "Microsoft Symbol Servers"
- Open the .dmp file created earlier in Visual Studio
- Select "Debug with Native Only"
- Go to the Threads view and select the thread that is blocking inside the Load call (it is likely going to be the main thread)
- Go to the Call Stack view. If it says "External code", right click and check show external code. If it has numbers instead of names for unmanaged .dlls like coreclr.dll or kernelbase.dll, right click and select "Load Symbols"

Share the callstack with us (redact any details that you cannot share if there are any).

**Comment by cheesi** [comment]
Hi @jkotas !

Thanks for your response! I did the steps described by you and got the following call stack:
![callstack](https://user-images.githubusercontent.com/5590254/66048152-57256880-e529-11e9-9cea-f21f27767905.png)

Based on this, I think I also kind of know, what the problem is. The native dll executes a init procedure after it is loaded (i don't know how this works, as I don't have the source or anything of that dll) and opens a connection to a MSSQL database. The plugin may later be used to export data into that database.

Now on my dev system (like as on many client systems) the database for that connection doesn't exist, as it is an external system, I don't have.

It seems like, .NET Core 3 waits for those init procedure to finish?

**Comment by jkotas** [comment]
.NET Core 2 did not run the init procedure at all. .NET Core 3 added back the code that runs the init procedure (for managed C++ support).

**Comment by jeffschwMSFT** [comment]
cc @jkoritzinsky @vitek-karas

**Comment by cheesi** [comment]
Alright I see. Is there a way to restore the "old behavior"? Or another way to check for .NET DLLs only?

Filtering on a hardcoded file name seems kind of wrong for a dynamic plugin system 😅

**Comment by jeffschwMSFT** [comment]
Considering the dependencies that are doing the long pause, is there a way to configure them to exit out earlier?  For instance, is there a SQL timeout that can be set to something smaller?

It is very possible that previously the module was not behaving as designed due to the lack of the init procedure not running.

**Comment by cheesi** [comment]
Nah the native plugin behaved just fine, because if it is used, there is also a correct configuration for it, as the same configuration file is used for their main application. So the init procedure won't take that long. Also the native plugin isn't used directly, but with a c# wrapper plugin with P/Invoke.

It looks like I can't configure the timeout, and even if I could, it would be problematic, as I already mentioned, their main application uses the same configuration file.

**Comment by vitek-karas** [comment]
A good solution should be https://docs.microsoft.com/en-us/dotnet/api/system.reflection.metadataloadcontext.loadfromassemblypath?view=dotnet-plat-ext-3.0#System_Reflection_MetadataLoadContext_LoadFromAssemblyPath_System_String_. This is a purely managed API (no ties to the runtime), it opens the file and tries to parse it as a managed assembly. It will return `BadImageFormatException` when you try to load native dll with it.
