### ISSUE TITLE
Question about GCC fastcall convention

### ISSUE THREAD

**Issue by NextTurn** [dotnet/coreclr#26989]
https://github.com/dotnet/coreclr/blob/ce66024ba7d60fc7bb72d5b780e395bd9d11719e/src/vm/fcall.h#L381-L382

I don't understand this comment. I looked into the GCC sources and found that the fastcall convention uses EDX and ECX for parameters (and EAX only for the static chain pointer). Under what circumstances will GCC pass the parameter in EAX?

**Comment by janvorli** [comment]
The comment is a bit misleading. It is not talking about fastcall calling convention that compiler understands, but rather about calling convention for calls that coreclr runtime calls FCalls (or fast calls). If you look few lines above that, you'll see that the calling convention we use is defined using 
`#define F_CALL_CONV __attribute__((cdecl, regparm(3)))` That one passes arguments in EAX, EDX and ECX as the comment correctly describes.

**Comment by NextTurn** [comment]
Thanks @janvorli. Does it mean that we can take advantage of `regparm(3)` to make the call "fast"er?

**Comment by NextTurn** [comment]
Thanks @janvorli for clarification. Does it mean that we can take advantage of `regparm(3)` to make the call "fast"er?

**Comment by janvorli** [comment]
The JIT would have to be modified to take advantage of that as the FCalls are only called by the managed code. It is not clear whether it would really have any perf benefit and it would also influence only Linux x86, which is currently not officially supported.

**Comment by NextTurn** [comment]
Then why don't we use `__fastcall` on GCC since it behaves the same? What's the motivation for adopting a different convention on Linux?

**Comment by janvorli** [comment]
@NextTurn there are two problems there. First, in fastcall, the callee cleans the stack while with the cdecl,regparm(3), the caller cleans it. The second problem is that the order of arguments passed in register is different between ECX and EDX (fastcall passes first argument in ECX and the second in EDX, while cdecl,regparm(3) passes second argument in EDX and third in ECX).
The usage of cdecl,regparm(3) basically means that the calling convention between windows and Linux differs only in the extra argument passed in EAX on Linux. So, JIT doesn't have to care at all. It passes first argument in EDX, second in ECX and the rest on stack. The macros in fcall.h define the native functions to have an extra dummy argument at the first position that is ignored. So that skips the EAX and it doesn't matter what's in it.

**Comment by NextTurn** [comment]
@janvorli I know FCalls have to conform to the EE calling convention. Why don't we use `__fastcall` as the global calling convention?

https://github.com/dotnet/coreclr/issues/8708#issuecomment-268961078

> In the future, it might make sense to switch the runtime native code to use fastcall by default

https://github.com/dotnet/coreclr/issues/8817#issuecomment-270639751

> I believe it should be defined as `__fastcall` unconditionally here, since the jitter generates the same x86 code as for windows now.

**Comment by janvorli** [comment]
I was looking at the history and I've found why we cannot use __fastcall (although it is the same as on Windows) for the FCalls. The reason is that we've switched the x86 JIT on Unix to use caller cleanup of arguments instead of the callee one on Windows. The switch happened in #10410 and you can find the reasoning behind that in the PR comments.

**Comment by NextTurn** [comment]
Thanks for the information. I've got to take some time to figure out the reason for the switch.
