### ISSUE TITLE
[crossgen2] Make sure hardware intrinsic are generated for CoreLib only

### ISSUE THREAD

**Issue by cshung** [dotnet/coreclr#26998]

**Comment by 4creators** [comment]
Is it possible to provide a description of the problem and software architecture associated with it? It would make the issue understandable to all coreclr contributors.

**Comment by cshung** [comment]
> Is it possible to provide a description of the problem and software architecture associated with it? It would make the issue understandable to all coreclr contributors.

Please check your outlook email, thanks.

**Comment by janvorli** [comment]
@cshung The issue needs to contain a description as @4creators suggests so that everyone from the community can understand why this is an issue.

**Comment by MichalStrehovsky** [comment]
> To be brutally honest, I don't actually understand what the problem is, at least not in a clearly reproducible manner. The comment must have written to make sure certain scenarios will not fail. I have yet to figure out what those scenarios are.

@cshung's crossgen2 change enabled crossgen2 to pregenerate code for all things that use hardware intrinsics ahead of time (when we don't know the HW architecture of the target machine), except the IsSupported method (which always stays a call). This way we pregenerate both the intrinsics and the fallback. This works as long as the user wraps all intrinsic use under an IsSupported check. If the user forgets to wrap intrinsic use in IsSupported check, they're supposed to get a PlatformNotSupportedException at runtime. How things currently stand in crossgen2, they would get an illegal instruction exception and failfast.

We only allow pregeneration in CoreLib since we can vouch for CoreLib's correct use of hardware intrinsics.

**Comment by cshung** [comment]
> If the user forgets to wrap intrinsic use in IsSupported check, they're supposed to get a PlatformNotSupportedException at runtime. How things currently stand in crossgen2, they would get an illegal instruction exception and failfast.

Is it possible to construct an example such that it actually failfast? That's what I meant by 'clearly reproducible' above. It would be nice for us to have a test case such that it fails if it ever regresses.

**Comment by MichalStrehovsky** [comment]
To hit the failfast, one needs to generate native code using instructions that are not supported by the current CPU.

There's an additional limitation that we don't enable anything that uses VEX encoding (the more "modern" ISA extensions such as Avx and Avx2).

You need a machine that has a CPU introduced before SSE42 and pregenerate code with crossgen2 for something that uses a SSE42 intrinsic without an IsSupported check. Writing such test is easy. Finding a machine to repro on is hard. Pretty much all CPUs sold in the past 5+ years have it (SSE42 was introduced in 2008).

We only found out about the Round/Ceiling/Floor issue (related thing) because WPF runs test passes on an ancient machine https://github.com/dotnet/corefx/issues/38762.

**Comment by MichalStrehovsky** [comment]
@cshung is there anything left for this after #27347?

**Comment by cshung** [comment]
Not that I know, closing this issue for now.
