### ISSUE TITLE
[crossgen2] Handle Floor and Ceiling

### ISSUE THREAD

**Issue by cshung** [dotnet/coreclr#26999]
https://github.com/dotnet/coreclr/pull/26982#discussion_r330444620

**Comment by 4creators** [comment]
Is it possible to provide a description of the problem and software architecture associated with it? It would make the issue understandable to all coreclr contributors.

**Comment by cshung** [comment]
> Is it possible to provide a description of the problem and software architecture associated with it? It would make the issue understandable to all coreclr contributors.

This issue is created to track the work required to address one of these work items mentioned as a comment in my pull request.

https://github.com/dotnet/coreclr/pull/26982#discussion_r330448744

The pull request was created as a cherry-pick of [6ec78980083123ec82300cbcbaadbb34fd34ea0a](https://github.com/dotnet/coreclr/commit/6ec78980083123ec82300cbcbaadbb34fd34ea0a), which is a port of these 3 pull requests (#24689, #24917, #25365). As I understand it, the original pull request allow `crossgen` to use hardware intrinsics. The port was intended to allow `crossgen2` to also use hardware intrinsics.

To be brutally honest, I don't actually understand what the problem is, at least not in a clearly reproducible manner. The comment must have written to make sure certain scenarios will not fail. I have yet to figure out what those scenarios are. 

@MichalStrehovsky who authored the original pull requests and the original comment should be able to explain in detail what the problem is.

**Comment by MichalStrehovsky** [comment]
This is specifically about part of #25365 crossgen fix that should have been ported to crossgen2, but wasn't. The issue linked from the pull request has the details (basically, since we allow RyuJIT to use SSE41, RyuJIT is free to use SSE41 in expansion of Round/Floor/Ceiling). Expanding Round/Floor/Ceiling is not what we intended to enable (we only intended to enable SSE41 on the SSE41 intrinsic class that is supposed to guard all use of the intrinsics with an SSE41.IsSupported check - Math.Round is not guareded by SSE41.IsSupported).

I hope this clarifies things.
