### ISSUE TITLE
Directly Encode Filter String Key-Value Pairs in Diagnostics IPC Protocol

### ISSUE THREAD

**Issue by josalem** [dotnet/coreclr#27064]
The `CollectTrace` commands in the Diagnostics IPC Protocol currently pass the entire filter string as a single length-prefixed string.  This should be modified so that it is sent as an array of key-value pairs of strings.  This more closely maps to the APIs used in the runtime for communicating these values into `EventSource`s, and moves the burden of encoding these values to outside tools, thus removing unneeded complexity in the runtime implementation.

Compatibility Considerations:
This change would be the first major change in behavior for the protocol, so we will need to consider how we handle different client versions.  The 3.X versions of the runtime will be expecting a single string and any values containing `;` or `=` to be escaped with `"`.  If we change this to consume a bag of key-value pairs, we will no longer require the escaping via `"`.  This will require us to formalize our versioning strategy for the IPC protocol, as we will need to make sure a client gets the expected parsing behavior.  My expectation is that it will play out something like this:

* a client sends a v2 protocol collect command
  * if the target runtime is using a v2 protocol, continue
  * if the target runtime is using a v1, send back a "incorrect version" response and fall back the v1 protocol on the client side.

dotnet/diagnostics#539

CC - @davidfowl @sywhang @noahfalk @tommcdon

**Comment by noahfalk** [comment]
> This will require us to formalize our versioning strategy for the IPC protocol

Hmm, I didn't think of the versioning as being unknown... that probably means I failed to communicate it well, sorry about that : / My expectation for command protocol versioning is very much like COM versioning, once you ship a command the input/output semantics of that command are forever fixed. If you later decide that you did it wrong you introduce a second (or third or N'th) command which exists side-by-side with all the old ones. New clients can opt into the new command by using its new command id, old clients are unaffected because they continue to use the old command. We've already done this once, see [CollectTracing2](https://github.com/dotnet/diagnostics/blob/master/documentation/design-docs/ipc-protocol.md#collecttracing2). This change would presumably introduce CollectTracing3.


> send back a "incorrect version" response and fall back the v1 protocol on the client side.

When a command isn't supported, the client gets back a CORDIAGIPC_E_UNKNOWN_COMMAND. The client can then attempt to [fallback](https://github.com/dotnet/diagnostics/blob/master/src/Tools/dotnet-counters/CounterMonitor.cs#L213-L221)

**Comment by noahfalk** [comment]
@josalem - Are you aware of any key/value pair encoding that can't be achieved with the current text input? Although I fully agree a binary encoding would be a cleaner design if we had started there, at this point the question is do we have a text-only mechanism or both a text-only mechanism + a binary mechanism SxS? As long as everything can be encoded with the text mechanism there isn't much value to be gained by adding a 2nd option. We can close this issue in that case.

**Comment by josalem** [comment]
I'm not aware of anything that can't be encoded with the current, single, quoted-string approach.  I agree with your sentiments.  We can hide this implementation detail by having the client library APIs use `IEnumerable<KeyValue<string, string>>` (I believe this is already in the current draft) and hide the need for the quoting behind that.  Closing for now.
