### ISSUE TITLE
Alternate way to serialize/de-serialize data using Resource Manager in NetCore

### ISSUE THREAD

**Issue by mageshsankar** [dotnet/coreclr#27225]
I have an custom control which inherited from component and one of the property of  my custom control is MemoryStream type. 

I have stored some layout state information in the LayoutStream property using MemoryStream which is generated in resource file. But In NetCore 3.0 MemoryStream is not supported to serialize the data which stored in resource file. **Since it is not marked  as serializable.** 

Here I have attached sample application which contain both framework project and NetCore project. While run framework project it works as excepected but it fails with NetCore project.

In the attached project, i have created custom control which has serliazable property called LayoutStream. You can able to reproduce it while run the attached NetCore project.

Sample Link: https://drive.google.com/file/d/18JUjS1cPBI8CDbH2sPbb1JGHlBmLpY1B/view

Here CustomControl added as assembly. Please find code for CustomControl

Class

` [ToolboxItem(true)]
    public class Custom : Control
    {
        public Custom()
        {
            this.Size = new Size(30, 30);
            this.BackColor = Color.Red;
            LayoutStream = new CustomControl.SerializableByteList();
        }
        private CustomControl.SerializableByteList layoutStream;
        
        public CustomControl.SerializableByteList LayoutStream
        {
            get
            {
                return layoutStream;
            }
            set
            {
                layoutStream = value;
            }
        }
    }
`
Exception:

![image](https://user-images.githubusercontent.com/55440472/66894619-8ac6bf00-f00e-11e9-89e0-6fad20f12767.png)

Please check the sample and suggest any other solution.

Thanks,

**Comment by jkotas** [comment]
cc @ericstj

**Comment by ericstj** [comment]
Related #26472, https://github.com/dotnet/project-system/issues/5460

Instead of using MemoryStream you could use your own Serializable type with fields for each value you wish to store.  
```c#
[Serializable]
public class LayoutState
{
  public int Info { get; set;} 
  ....
}

...
// instead of public MemoryStream LayoutStream
public LayoutState LayoutState { get; set; }
```

Alternatively you could expose the backing byte-array instead of a MemoryStream.

```c#
// instead of public MemoryStream LayoutStream
public byte[] LayoutBytes { get; set; }
```

Both of these seem a little counter-intuitive from the whole point of the resx.  The resources abstraction is the thing responsible for representing types in a stream (the embedded .resources): by doing the same thing in your control you're doing unnecessary work.  Additionally the whole point of having a field marked as "Localizable" and storing it in the resx is so that it can be easily localized.  An embedded stream containing layout information doesn't seem to be very friendly to localization.

Can you please explain how a user goes about setting the value of the Stream?  This wasn't clear in your sample.  If they set it through other properties on the object maybe its better to make those properties as `Localizeable(true)` and set `Localizable(false)` on the LayoutStream.  If you don't need to store the value in resources at all, consider just setting `Localizable(false)` on the LayoutStream property.

**Comment by mageshsankar** [comment]
Hi @ericstj 

I have already tried Method which you suggested here. By using byte[] array,im facing an issue reported in https://github.com/dotnet/coreclr/issues/27224.

**Comment by ericstj** [comment]
In issue #27224 you aren't using a byte array, you're using a serializable user type that contains a List<byte>.  Try using `byte[]` specifically.  This is treated as a primitive by ResourceWriter and will bypass BinaryFormatter. 
 https://github.com/dotnet/corefx/blob/master/src/Common/src/System/Resources/ResourceWriter.cs#L482

**Comment by ericstj** [comment]
@mageshsankar as I pointed out you weren't using a byte[], you exposed SerializableByteList which exposed List<byte>.  Update your sample to use byte[] instead and it will avoid this issue.  We'll still be fixing  https://github.com/dotnet/coreclr/issues/27224, but using byte[] should be a resonable workaround.
