### ISSUE TITLE
CoreRun cannot load assembly

### ISSUE THREAD

**Issue by HexJacaranda** [dotnet/coreclr#27251]
After building coreclr, I tried to run some samples on my build in PowerShell but got the exception
“this module was expected to contain an assembly manifest” for console program and "Entry point
not found" for compiled dll.
OS Version： 10.0.18362.1
I don't know what goes wrong.

**Comment by HexJacaranda** [comment]
![QQ截图20191016173024](https://user-images.githubusercontent.com/26338326/66971392-a4760e00-f0c3-11e9-8346-8cb84071359e.jpg)

**Comment by AaronRobinsonMSFT** [comment]
Based on the command line, I would try supplying `Target.dll` instead of `Target.exe` to the `CoreRun.exe` process.

**Comment by HexJacaranda** [comment]
> Based on the command line, I would try supplying `Target.dll` instead of `Target.exe` to the `CoreRun.exe` process.

Thanks，it's solved. but why I can't supply Taget.exe to the CoreRun process? Simply becasue it doesn't support？

**Comment by AaronRobinsonMSFT** [comment]
@HexJacaranda That is a great question that requires discussion of the .NET Core hosting strategy. In .NET Framework, the Runtime was installed on the OS and always in a well-known location. This made launching a .NET application simple, but required deep integration with the OS to know what to do when a .NET application was requested for launch.

In the .NET Core world, there is no integration with the OS. The intent is that the OS (Windows or non-Windows) treat the application launch like any other native application launch (i.e. non-.NET). What this means is we need to handle the activation and discovery of the Runtime instead of it being in a well-defined location and letting the OS handle it. The solution in the current example is the EXE (entry binary) isn't actually a .NET image, but rather a native image (i.e. platform specific) whose one and only job is to discover where the Runtime is installed on the system and then load the .NET assembly that represents the entry point.

In the scenario above your application is `Target`. The result of this is the .NET assembly that is the entry point (i.e. `Target.dll`) and the native entry point (i.e. `Target.exe`) that finds the correct runtime based on the application's configuration (`*.runtimeconfig.json` and `*.deps.json`). These configuration files are examined in detailed on [Nate McMaster's blog](https://natemcmaster.com/blog/2017/12/21/netcore-primitives/).

The `CoreRun.exe` is a simplified version of the native hosting binary that is used by the coreclr repo for testing so supplying the actual managed entry point is the requirement here where as using the binary that is created during the project build has been modified to know exactly what .NET entry point to load and start.
