### ISSUE TITLE
genHWIntrinsic_R_RM_I uses address of a dead local.

### ISSUE THREAD

**Issue by sandreenko** [dotnet/coreclr#27371]
In #23629 such code was added:
https://github.com/dotnet/coreclr/blob/eb4815e2b7f2481a7cb277c8128e691fe426d3e5/src/jit/hwintrinsiccodegenxarch.cpp#L482-L490

`memIndir = &load; ` saves address of a stack variable that lives in `if (memIndir == nullptr) ` scope.
`emit->emitIns_R_A(ins, attr, reg, memIndir);` uses that address that points to a dead stack slot and could be rewritten by another local var (`emitIns_R_A` dereferences it).

That works on x64 because we don't have other locals in that method and don't tailcall `emitIns_R_A`(that is strange why we don't, it looks profitable), but generally unsafe.

@tannergooding could you please fix that or say why it is safe in the current version?

PVS warning.

**Comment by sandreenko** [comment]
and the same in https://github.com/dotnet/coreclr/blob/eb4815e2b7f2481a7cb277c8128e691fe426d3e5/src/jit/instr.cpp#L1115-L1124

**Comment by tannergooding** [comment]
The code wasn't added in the previous PR, it was just moved from its old location. @CarolEidt added it originally a number of PRs ago and would be the best person to comment.

**Comment by tannergooding** [comment]
Actually, I think I might've gotten my PRs mixed up, let me see where the code was first added....

**Comment by mikedn** [comment]
Bleah, I should finish my removal of fake indir nodes from the emitter interface... I left it rot because I did not think it's useful enough. Maybe it is.

**Comment by tannergooding** [comment]
Ok, the pattern was originally added in https://github.com/dotnet/coreclr/pull/23558, and then I copied it to the other methods in https://github.com/dotnet/coreclr/pull/23629 shortly thereafter.

I'm not familiar enough with the optimizations the C++ compiler can/will do to say whether or not this is safe, but the fix is trivial enough to make (just move `GenTreeIndir load` outside the `if()` check) so it should probably be done.

**Comment by CarolEidt** [comment]
I hope that we can indeed eliminate these fake indir nodes, but in the meantime I think that moving the creation outside of the check should be a reasonable fix.

**Comment by mikedn** [comment]
> I hope that we can indeed eliminate these fake indir nodes

If someone wants that it's mostly done here: https://github.com/dotnet/coreclr/compare/master...mikedn:ind-load-store
Otherwise it's not my priority ATM.

**Comment by mikedn** [comment]
Does anyone know if 3.0/3.1 future updates will be done using the same C++ compilers that were used to build 3.0? If the compiler might get updated then it may be better to fix this in 3.1 as well to avoid sudden breakage due to compiler changes.

**Comment by sandreenko** [comment]
> Does anyone know if 3.0/3.1 future updates will be done using the same C++ compilers that were used to build 3.0? If the compiler might get updated then it may be better to fix this in 3.1 as well to avoid sudden breakage due to compiler changes.

@jeffschwMSFT and @BruceForstall, probably you could answer that.

**Comment by jeffschwMSFT** [comment]
@markwilkie has a proposal on our schedule to update VC compilers.  If this relates to a x-plat compiler, I believe the new consolidated repo has control on what version we use.

**Comment by sandreenko** [comment]
> I hope that we can indeed eliminate these fake indir nodes
> 
> If someone wants that it's mostly done here: master...mikedn:ind-load-store
> Otherwise it's not my priority ATM


The change looks good, can't find what is not finished there?

**Comment by mikedn** [comment]
> The change looks good, can't find what is not finished there?

I think I spotted one or two fake indirs that I missed, possibly while resolving conflicts. In general, I need take a careful look at it because it's been a while since I've done it and conflicts were pretty bad.

Also, it may be a good opportunity to also remove `Base`/`Index`/`Offset` from `GenTreeIndir`. I wanted to it back then but tried to keep the change smaller. The result? People get confused and waste time writing code that isn't needed - https://github.com/dotnet/coreclr/pull/27397#discussion_r338227460. Funny coincidence.
