### ISSUE TITLE
GCCollect does not clear WeakReferences

### ISSUE THREAD

**Issue by wvpm** [dotnet/coreclr#27447]
(Moved from AspNetCore issues)
VS 2019
C# 8.0
Release build (JIT optimizations on)

var obj = new object();
var wRef = new WeakReference(obj);

GC.Collect(2, GCCollectionMode.Forced);
GC.WaitForPendingFinalizers();
obj = null;
GC.Collect();
Console.WriteLine(wRef.IsAlive); // Prints False for .Net Core 2.2 but True for .Net Core 3.0
Console.ReadKey();

**Comment by janvorli** [comment]
The fact that you are assigning null to obj doesn't necessarily mean there is no reference to the actual object. JIT can store a copy of the reference it in some helper internal local on stack.

**Comment by 0xd4d** [comment]
If you disable tiered compilation it behaves the same as 2.1.

**Comment by janvorli** [comment]
The fact that it behaves differently in 2.1 / with disabled tiered compilation is just because the JIT generates slightly different code. There is no requirement / guarantee that after setting a seemingly only local to null, there won't be more references.

**Comment by wvpm** [comment]
So, how to force GC Collect in .Net Core 3.0 then?

**Comment by 0xd4d** [comment]
> disabled tiered compilation is just because the JIT generates slightly different code

Yes I thought he knew that.

> So, how to force GC Collect in .Net Core 3.0 then?

You just did that in your example. The reason it wasn't collected has already been explained.

**Comment by janvorli** [comment]
@wvpm if you want to make sure the reference to the object is really gone, you'll need to put the code that works with that object to a separate function marked with attribute [MethodImpl(MethodImplOptions.NoInlining)] so that it doesn't get inlined.
Return the WeakReference from that function and do the GC.Collect etc after returning from it.

You can see some more details in my article on unloading where people can hit this exact problem:
https://docs.microsoft.com/en-us/dotnet/standard/assembly/unloadability
