### ISSUE TITLE
IDispatchEx-over-IExpando support in CCW?

### ISSUE THREAD

**Issue by jerrys-msft** [dotnet/coreclr#27461]
The lack of IDispatchEx-over-IExpando support in .NET Core CCWs is documented; in fact, .NET Core doesn't officially support IExpando at all. I noticed however that there's an incomplete, internal version of IExpando in the code ([see here](https://github.com/dotnet/coreclr/blob/release/3.1/src/System.Private.CoreLib/src/System/Runtime/InteropServices/Expando/IExpando.cs)), so I was wondering if support for this CCW feature was planned for a future release.

**Comment by AaronRobinsonMSFT** [comment]
@jerrys-msft There is no such plan. Its presence is the result of the mass port from .NET Framework and just the lack of time to properly excise it from the code base. There are a myriad of COM features still in the code base at varying levels of atrophy that will eventually be removed. Is there a specific scenario where it is needed?

**Comment by ClearScriptLib** [comment]
Thanks, @AaronRobinsonMSFT. The feature was useful for exposing managed objects to classic (pre-Chakra) JScript. Is it safe to assume that any interop feature currently documented and working will not be yanked, at least in the foreseeable future?

**Comment by jerrys-msft** [comment]
@AaronRobinsonMSFT Thanks for your response. I was just wondering why IDispatch-over-IReflect was deemed worthy, but not its logical extension :)

**Comment by AaronRobinsonMSFT** [comment]
@jerrys-msft This specific decision was more related to inconsistencies during the port. The `IRefect` interface is a .NET concept so was kept, whereas `IExpando` originated in COM so was removed. There is technically no reason both can't be supported. The more practical argument for removing support for less foundational COM types (i.e. `IDispatch` vs `IExpando`) is that support for .NET interop can become coupled/intertwined with COM details and since we have a mechanism that we can evolve at our own cadence keeping both approaches is more legacy burden than future benefit. 

I can appreciate that the above probably isn't satisfactory with respect to "We just want it to work". If this is blocking you, we can consider it in the .NET 5 timeframe, but it would require some business justification and additional feedback from the community. Please let us know if we should consider adding back support in the future.

**Comment by jerrys-msft** [comment]
@AaronRobinsonMSFT Thanks for the explanation; it makes a lot of sense. Now I understand why IReflect and IExpando are so far apart on the namespace tree :)

I can provide no business justification for this feature; in fact, I can think of no non-legacy scenario that would benefit from it. It was a nifty feature, but unless you find justification elsewhere, feel free to close this issue. Thanks again!
