### ISSUE TITLE
GC.KeepAlive JIT intrinsic

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#27541]
`GC.KeepAlive` is implemented as a empty non-inlineable call today. The call is cheap, but it still shows up as bottleneck in some cases. I have run into it while working on https://github.com/dotnet/coreclr/issues/27106 and https://github.com/dotnet/coreclr/issues/18111.

**Comment by jkotas** [comment]
@dotnet/jit-contrib Does it need to be a new `GT_KEEPALIVE` node type, or can one of the existing nodes be used to construct it?

**Comment by mikedn** [comment]
Hmm, to keep the object alive you need to report the reference to the GC so this probably needs to be some kind of special variable, not a node. Something similar "pinned" variables.

**Comment by jkotas** [comment]
Can I get away with a node that consumes the value, but does not produce any code? Maybe `GT_NOP` with side-effects so that it cannot be optimized away?

**Comment by mikedn** [comment]
`NOP`s get removed during rationalization.

Can't think of something that doesn't produce any code right now. `ADD_OVF_UN<TYP_I_IMPL>(ref, TARGET_POINTER_SIZE)` might be valid IR and won't get removed because the JIT isn't smart enough to figure out that adding 8 to a reference can't actually overflow, at least not on current systems. But it does produce a bit of code.

Yeah, maybe a new oper is needed. Though it seems a bit overkill to add one just for this.

**Comment by sandreenko** [comment]
> NOPs get removed during rationalization.

even with side effects? I need to check that.

**Comment by mikedn** [comment]
NOPs shouldn't have side effects. Well, I suppose one could try to set a side effect flag on a NOP node but that's not expected. They may get side effects by inheriting them from gtOp1 but that does not apply in LIR.

**Comment by AndyAyersMS** [comment]
Phoenix had a `SideEffect` instruction that we used for this purpose -- generated no code, produced no result, just kept its operand live, and could not be removed.
