### ISSUE TITLE
Some CultureData initialization depends on current thread

### ISSUE THREAD

**Issue by stephentoub** [dotnet/coreclr#27808]
e.g. LocalizedCountryName calls GetRegionDisplayName, which bases its return value on CultureInfo.CurrentUICulture.  That would seem to then potentially impact how LocalizedCountryName is evaluated for an instance that is potentially shared with multiple threads.

@tarekgh, is this an issue?

**Comment by tarekgh** [comment]
@stephentoub yes but it is minor issue. The first thread request the DisplayName will set the display name for the other thread calling DisplayName too. I am saying this is minor issue because it is the behavior in core clr since day 1 and most of the time even we fix the issue we'll pick the NativeName as we don't carry a resources for the display names in .NET Core. On the full framework, as the framework carry resources for the region display names, we always request the resource using the default UI culture from the default appdomain. it is possible to run into the same issue on the full framework if manually set different UI culture on the default appdomain.

**Comment by stephentoub** [comment]
Ok, thanks.
