### ISSUE TITLE
GcStress: Linux: Assert failure in GcCover

### ISSUE THREAD

**Issue by swaroop-sridhar** [dotnet/coreclr#2785]
Assert failure in GcCoverage testing in the following tests:

```
JIT/Directed/lifetime/lifetime1/lifetime1.exe
JIT/jit64/opt/rngchk/ArrayWithThread_o/ArrayWithThread_o.sh 
JIT/Methodical/tailcall/Desktop/_il_relthread-race/_il_relthread-race
Exceptions/Finalization/Finalizer/Finalizer
```

```
corerun JIT/Directed/lifetime/lifetime1/lifetime1.exe
A
A.F(): iMember = 123

Testcase 1
A.F(): iMember = 123
~A

Assert failure(PID 27789 [0x00006c8d], Thread: 27795 [0x6c93]): Consistency check failed: FAILED: !pThread->HasPendingGCStressInstructionUpdate()
    File: /home/swaroops/git/a/coreclr/src/vm/gccover.cpp Line: 1634
    Image: /home/swaroops/git/a/coreclr/bin/Product/Linux.x64.Debug/corerun

**** MessageBox invoked, title 'corerun - Assert Failure (PID 27789, Thread 27795/0x6c93)' ****
  Consistency check failed: FAILED: !pThread->HasPendingGCStressInstructionUpdate()

/home/swaroops/git/a/coreclr/src/vm/gccover.cpp, Line: 1634

Abort - Kill program
Retry - Debug
Ignore - Keep running


Image:
/home/swaroops/git/a/coreclr/bin/Product/Linux.x64.Debug/corerun

********

/home/swaroops/bin/runn: line 3: 27789 Aborted    
```

Repro steps
* cp \scratch2\scratch\swaroops\coredistools\libcoredistools.so somewhere
* export LD_LIBRARY_PATH=somewhere
* export COMPlus_GCStress=0xC
* Run the above test

**Comment by swaroop-sridhar** [comment]
This could be a bug in the GcStress infrastructure implementation.
@adityamandaleeka said he'll take a look.

**Comment by adityamandaleeka** [comment]
I'm not sure about the solution for this yet, but here's what I've found so far...

The assumption behind this assert is that when we call `StressHeap` and it returns TRUE, it means that a GC was performed, and as part of the runtime suspension involved in the GC, any pending GC stress instruction updates should have been committed. This assumption is being violated because it appears that `GarbageCollectGeneration` can return without actually triggering a GC if there is already one in progress.

The GC that's in progress should commit pending GC stress updates on every thread in the ThreadList, but based on the stacks I see in the coredump, it looks like the thread that's performing a GC is currently in `SuspendRuntime` and waiting for thread(s) to leave cooperative mode. The code that commits the GC stress instruction updates has not executed at this point.

Let's say our thread (the one that's firing this assert) was in cooperative mode and executing managed code. If the activation injection in `SuspendRuntime` raised the signal for our thread and the GC suspension handler were called, the handler would have seen that this thread is executing managed code and either pulsed the GC mode (if at a GC safe point) or patched the return address to forcibly take the thread to an appropriate stub. Obviously, the former has not happened, and looking at the contents of the stack, it doesn't seem like the latter did either (return address doesn't look patched).

The current theory is that, since we spend a lot of time handling segfaults for GC stress, chances are that we're in the runtime's exception handling code when the GC suspension signal is raised. In this case, we will bail out of `inject_activation_handler` right away since we're not in managed code, and the thread that's in `SuspendRuntime` will be left waiting for all the other threads to leave cooperative mode. Meanwhile, the thread that's trying to handle the GC stress instruction sees that a GC is already in process and doesn't try to commit the pending instruction update itself because it assumes someone else is going to do that (which is when this assert fires).

**Comment by adityamandaleeka** [comment]
@sergiy-k

**Comment by swaroop-sridhar** [comment]
This failure is showing up in several test runs, sometimes non-deterministically.
 For example: 

```
export COMPlus_GCStress=0xC
export COMPlus_JitStress=2
export COMPlus_ZapDisable=1

FAILED   - JIT/Regression/CLR-x86-JIT/V2.0-Beta2/b425314/b425314/b425314.sh
               BEGIN EXECUTION
               /home/swaroops/test/Tests/coreoverlay/corerun b425314.exe
               Timeout: The `CastClass' scenario exceeded the time limit (180s) without reaching the basic work thresholds.
               
               Assert failure(PID 46124 [0x0000b42c], Thread: 46124 [0xb42c]): Consistency check failed: FAILED: !pThread->HasPendingGCStressInstructionUpdate()
                   File: /home/swaroops/git/coreclr/src/vm/gccover.cpp Line: 1633
                   Image: /home/swaroops/test/Tests/coreoverlay/corerun
               
               **** MessageBox invoked, title 'corerun - Assert Failure (PID 46124, Thread 46124/0xb42c)' ****
                 Consistency check failed: FAILED: !pThread->HasPendingGCStressInstructionUpdate()
               
               /home/swaroops/git/coreclr/src/vm/gccover.cpp, Line: 1633
               
               Abort - Kill program
               Retry - Debug
               Ignore - Keep running
               
               
               Image:
               /home/swaroops/test/Tests/coreoverlay/corerun
               
               ********
               
               ./b425314.sh: line 55: 46124 Aborted                 (core dumped) $_DebuggerFullPath "$CORE_ROOT/corerun" b425314.exe $CLRTestExecutionArguments $Host_Args
               Expected: 100
               Actual: 134
               END EXECUTION - FAILED

```

**Comment by adityamandaleeka** [comment]
@swaroop-sridhar 

While looking into this some more, I synced to the latest sources on master and have not been able to reproduce it since doing so. I will continue investigating to find out what the problem is/was and whether it was fixed or just hidden.

Please let me know if you are still hitting this assert with the latest bits.

**Comment by adityamandaleeka** [comment]
Never mind... disregard that comment.

**Comment by swaroop-sridhar** [comment]
Fixed by
https://github.com/dotnet/coreclr/commit/2fc254794c9a31d02cd995df04176e64d0c13eeb
