### ISSUE TITLE
RyuJIT: Access violation when calling IsLclVarUpdateTree on GenTreeHWIntrinsic

### ISSUE THREAD

**Issue by saucecontrol** [dotnet/coreclr#27937]
When compiling the `crash` method below, RyuJIT throws an AV when `GenTree::IsLclVarUpdateTree` is called from `Compiler::optExtractInitTestIncr`.  The rhs arg in this case is a `GenTreeHWIntrinsic`  (NI_Vector128_Zero), which causes a nullptr dereference.

```C#
using System.Runtime.Intrinsics;

class Program
{
    static unsafe void crash(float* fa, float* fb)
    {
        float* pb = fb;
        float* eb = pb + 16;

        do
        {
            float* pa = fa;
            float* ea = pa + 16;
            var va = Vector128<float>.Zero;

            do
            {
                *pa = va.ToScalar();

                pa += Vector128<float>.Count;
                pb += Vector128<float>.Count;
            } while (pa < ea);

        } while (pb < eb);
    }

    static unsafe void Main()
    {
        float* a = stackalloc float[16];
        float* b = stackalloc float[16];

        crash(a, b);
    }
}
```

**Comment by mikedn** [comment]
Ha, code is checking if the oper is binary and crashes because `op1` is null. `HWINTRINSIC` is one of the few opers that lies about being binary when in fact it can be anything from nullary (like `Zero`) to ternary and more.

Should be an easy fix, at least for this particular case. The proper solution is to make `HWINTRINSIC` `GTK_SPECIAL` instead of `GTK_BINARY`. That will happen when I get rid of `GT_LIST`.
