### ISSUE TITLE
ArrayPool's Return() and Rent() have the wrong signature

### ISSUE THREAD

**Issue by znakeeye** [dotnet/coreclr#27945]
[ConfigurableArrayPool.Return()](https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/shared/System/Buffers/ConfigurableArrayPool.cs#L123) should return a `bool`, indicating if the buffer was indeed returned. Similarly, there should be a `Rent(int minimumLength, out bool rented)` so that you can quickly determine if the returned buffer is indeed from the pool.

**Important for unit tests**
The current implementation makes it impossible to determine if you are working with a pooled array or temporary array. Distinguishing between the two can be critical for e.g. unit tests. In our use case, we traverse a tree structure and it's important that we don't reach a point where the array pool has been exhausted. Here, fine-tuning the size of the pool (impossible due to the above) would allow us to get a deterministic GC behavior.

**Comment by stephentoub** [comment]
> have the wrong signature

They don't have the "wrong" signature; they just don't have the signature you're asking for.

> so that you can quickly determine if the returned buffer is indeed from the pool

It's not entirely clear to me what you mean with this.  It sounds like you're assuming a certain implementation?  The pool implementation doesn't start with all possible buffers allocated.  Rather, it allocates on-demand: if there's not currently a buffer available in the pool when you rent, it allocates one, and when you return, if there's space available, it stores it.  So, for example, the very first time you call Rent on a pool, it's going to allocate a new instance because there won't be one available... does that mean "rented" or not?

> impossible due to the above

I agree it's harder to determine, but it's not impossible.  The pool fires an EventSource event when it needs to allocate:
https://github.com/dotnet/runtime/blob/c50eae5725623c6d7b6de0d54e1010eb6e2c17fa/src/libraries/System.Private.CoreLib/src/System/Buffers/ConfigurableArrayPool.cs#L116-L117
and you could write a custom EventListener in your unit tests that listened for this event.

**Comment by znakeeye** [comment]
Rented or not, let's focus on the `Return` method instead then. Returning a bool from there seems like a no-brainer.

I saw these events, but never had any success listening on them. In my sample project, these events never fired (maybe you need to elevate when using `Microsoft.Diagnostics.Tracing.TraceEvent`?). Perhaps it was because we are targeting `.NET Framework` from the [System.Buffers](https://www.nuget.org/packages/System.Buffers/) Nuget package. Not sure why it never worked. Anyway, `ETW` is way too complicated for our needs.

**Comment by stephentoub** [comment]
> Returning a bool from there seems like a no-brainer.

What API are you proposing?  We can't change the existing one.

**Comment by znakeeye** [comment]
Not sure why a different return value would matter. Care to explain?

Anyway, perhaps add a method then:
```c#
bool IsRented(T[] array);
```

**Comment by stephentoub** [comment]
> Not sure why a different return value would matter. Care to explain?

Because changing the return type of a method is a binary breaking change.  The return type is part of the signature.

> perhaps add a method then

None of the existing implementations could implement that correctly; they do not store data on every array that's been rented.

**Comment by znakeeye** [comment]
Right. So you can actually `Return()` an array which was never rented, effectively replacing one of the bucket arrays?

**Comment by stephentoub** [comment]
> So you can actually Return() an array which was never rented, effectively replacing one of the bucket arrays?

If the array meets all of the criteria of the pool (e.g. it's of a valid size), then the pool implementation can't distinguish it from one that was returned from Rent and is allowed to be returned as with any other rented array.

**Comment by znakeeye** [comment]
Alright. Seems like `ArrayPool` simply does not keep track of the references. Hence my request is void.
