### ISSUE TITLE
How do I write code that allows a method to use Calli instructions at run time? 

### ISSUE THREAD

**Issue by NMSAzulX** [dotnet/coreclr#27968]
Now, I use MethodInfo.CreateDelegate to create delegates, but its execution performance is lower than that of Calli. How can I improve it?

**Comment by benaadams** [comment]
There's a csharp proposal for function pointers https://github.com/dotnet/csharplang/blob/master/proposals/function-pointers.md

Otherwise you'd need to use [System.Reflection.Emit.ILGenerator.EmitCalli](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.ilgenerator.emitcalli?view=netcore-3.0) to generate the il at runtime?

**Comment by NMSAzulX** [comment]
@benaadams Wow! will this feature appear in C#9?

**Comment by NMSAzulX** [comment]
@benaadams  I'm looking forward to this feature in C#9, as well as Function Templates and AOP.  This is so great.

**Comment by benaadams** [comment]
Is still one of the proposals; don't think what will be in C#9 has been decided yet.

**Comment by NMSAzulX** [comment]
@benaadams Thank you~!
