### ISSUE TITLE
INJECT_ACTIVATION_SIGNAL alias SIGRTMIN not available

### ISSUE THREAD

**Issue by krytarowski** [dotnet/coreclr#2909]
NetBSD is one of the systems without `SIGRTMIN` exported for user-land (the same applies for `SIGRTMAX`).

What would be the correct approach to define `INJECT_ACTIVATION_SIGNAL` in `src/pal/src/exception/signal.cpp` for such systems?

**Comment by jkotas** [comment]
@janvorli @adityamandaleeka do you have any recomendation?

**Comment by jasonwilliams200OK** [comment]
IMO, this will do the job:

```c
// before line 48
// https://github.com/dotnet/coreclr/blob/43b39a7/src/pal/src/exception/signal.cpp#L48

#ifndef SIGRTMIN
#define SIGRTMIN 32
#endif
```

**Comment by krytarowski** [comment]
NetBSD uses standard signals for 1-31.

Additional 32:

```
#define SIGPWR          32      /* power fail/restart (not reset when caught) */
```

Kernel-only:

```
#ifdef _KERNEL
#define SIGRTMIN        33      /* Kernel only; not exposed to userland yet */
#define SIGRTMAX        63      /* Kernel only; not exposed to userland yet */
#endif
```

Reference:
https://github.com/IIJ-NetBSD/netbsd-src/blob/master/sys/sys/signal.h#L52

It would be nice to reuse on of the 1-31.

**Comment by krytarowski** [comment]
@jsonn have you got tips on it?

**Comment by adityamandaleeka** [comment]
> It would be nice to reuse on of the 1-31.

This is possible, but it will need to be tested thoroughly since real-time and standard signals have different characteristics (for example, multiple instances of the same real-time signal can be queued, and they are delivered in a deterministic order). I'm not sure it would be a great idea to have `INJECT_ACTIVATION_SIGNAL` be real-time on some platforms and not on others.

I'm also not a fan of hardcoding a value for `SIGRTMIN` unless it's absolutely needed. The recommended practice for working with real-time signals is always by using `SIGRTMIN+n`, since threading implementations or other parts of the platform might want to reserve some of the real-time signals for their own purpose.

I'm curious why the `SIGRTMIN` definition isn't being exposed to userland yet. Is the implementation of real-time signals not ready yet for NetBSD? I don't know much about the project, but I found [this doc page](http://netbsd.gw.com/cgi-bin/man-cgi?sigevent++NetBSD-current) for the current version of NetBSD which says: 

```
Please note that this manual describes an interface that is not yet fully
     functional in NetBSD: neither realtime signals nor SIGEV_THREAD are cur-
     rently supported.
```

I'm not sure whether this doc page just hasn't been updated though. People familiar with the NetBSD project will have to comment on that.

**Comment by krytarowski** [comment]
I've checked the code and it looks unimplemented. These defines for kernel-only world aren't really used anywhere.

**Comment by krytarowski** [comment]
How to fallback to !real-time signals?

**Comment by krytarowski** [comment]
Alternatively -- is it hard dependency and should it be implemented in the kernel for any progress?

**Comment by jkotas** [comment]
This is needed for `FEATURE_HIJACKING`. `FEATURE_HIJACKING` is not crucial - pretty much any reasonable program will work without it. It is performance optimization for the most part (allows GC to suspend thread faster).

You can ignore this problem for now (disable `FEATURE_HIJACKING` in the top level CMakefile`), and return back to it later once the system is functional and you can test what works and what does not.

**Comment by krytarowski** [comment]
Thank you for your feedback @jkotas . For now I will disable it and return to it once base functionality will be done.

**Comment by adityamandaleeka** [comment]
:+1:

**Comment by janvorli** [comment]
@krytarowski A possibility would also be to implement the activation injection in a way similar to how it works on OSX, using thread suspension. I can see that the

**Comment by krytarowski** [comment]
@janvorli I will have a look at it. Thank you for tip. This will be left for finalization.

**Comment by krytarowski** [comment]
http://mail-index.netbsd.org/source-changes/2016/08/04/msg076563.html implemented in NetBSD-current!

**Comment by janvorli** [comment]
@krytarowski that's great!
