### ISSUE TITLE
GCStress: JitStress: Crash in ldloca_s_r4

### ISSUE THREAD

**Issue by swaroop-sridhar** [dotnet/coreclr#2921]
```
export COMPlus_ZapDisable=1
export COMPlus_JitStress=2
export COMPlus_GCStress=1

corerun JIT/IL_Conformance/Old/directed/ldloca_s_r4/ldloca_s_r4.exe
{0x1e5a-0x7fd937b17c30} ASSERT [THREAD ] at /home/swaroops/git/coreclr/src/pal/src/thread/context.cpp.685: Got unknown signal number 11 with code 128
/home/swaroops/bin/runn: line 3:  7770 Aborted                 (core dumped) ./corerun ~/test/$1.exe
134
```

**Comment by sivarv** [comment]
Repro is a case of casting address of a local to float.  importer detects that address of local could be considered as TYP_I_IMPL instead of TYP_BYREF.  Essentially front-end produces

GT_CAST(float<-- long, GT_ADDR(lcl var))

Begin Note:
Front-end ensures that there is never a GT_CAST node with an operand of gc-type, because emitter cannot handle casting away gc-ness.  For this reason, fgMorphCast() creates a non-gc temp and assigns gc-variable to temp and cast is done on temp, for cases where gc-byref is not known to be an address on stack.
End Note


Rationalizer converts GT_ADDR(lcl_var) into GT_LCL_VAR_ADDR and changes the type on its to TYP_BYREF instead of copying the type of GT_ADDR node.  Codegen routine genIntToFloat() uses its src operand type (byref) while emitting cvtsi2ss instruction which emitter incorrectly deduces that the instruction is writing to a gc-ref and reports xmm0 reg is going alive!  This incorrect gc-reporting leads to a crash.

Currently working on a fix for this.
