### ISSUE TITLE
RoMetadata.dll needs to be ported to non-Windows platforms

### ISSUE THREAD

**Issue by gregg-miskelly** [dotnet/coreclr#301]
The VS debugger needs to be able to obtain an IMetaDataImport for a blob of metadata. On desktop Windows we can do this with the desktop .NET Framework. On Windows Phone and other non-desktop SKUs, we can do this through RoMetadata.dll. We need this dll to be available on non-Windows platforms to do the same.

**Comment by MattWhilden** [comment]
@sergiy-k @gregg-miskelly This issue is marked as up-for-grabs so it would be nice to have a bit more detail about how someone from the community would get started. Some things to consider including:
* Where does RoMetadata source live?
* A rough estimate about how difficult an undertaking this is? (trivial, easy, medium, hard)
* Which non Windows platforms?

**Comment by janvorli** [comment]
I have started working on it.

**Comment by janvorli** [comment]
It turned out that it is not needed, the VS debugger can use the libcoreclr instead.
