### ISSUE TITLE
Can QueueUserWorkItemCallback be pooled?

### ISSUE THREAD

**Issue by benaadams** [dotnet/coreclr#3147]
They don't seem to be particularly exotic consisting of only 3 fields; is fairly local/contained type
```csharp
private WaitCallback callback;
private ExecutionContext context;
private Object state;
```
Could be returned to pool at end of `QueueUserWorkItemCallback::IThreadPoolWorkItem.ExecuteWorkItem`

Feature high in plaintext allocations (+41MB/s)

![QueueUserWorkItemCallback](http://aoa.blob.core.windows.net/aspnet/QueueUserWorkItemCallback.png)

Higher when pipelining

**Comment by stephentoub** [comment]
I'm not sure about them being pooled, but I expect some of the cost could be trimmed off in the common case.  With CoreCLR, that ```context``` field will typically be ```ExecutionContext.Default```; with some refactoring, I expect the type could be split into two types, one with and one without the context field.  Rather than just doing ```new QueueUserWorkItem(...)``` and having it use ```ExecutionContext.Capture``` internally, the Capture call could be moved out to the call site, and then the smaller type could be constructed in the default case, e.g.
```C#
ExecutionContext context = compressStack && !ExecutionContext.IsFlowSuppressed() ?
    context = ExecutionContext.Capture(ref stackMark, ExecutionContext.CaptureOptions.IgnoreSyncCtx | ExecutionContext.CaptureOptions.OptimizeDefaultCase) :
    null;
QueueUserWorkItemCallback tpcallBack = (context == ExecutionContext.Default) ?
    new QueueUserWorkItemCallback(callBack, state) : // default context
    new QueueUserWorkItemCallbackWithContext(callBack, state, context); // null context or non-default context
```

@ericeil, any reason that wouldn't work?  Assuming most of those instances were the default, that should lower it from ~41MB to ~33MB.

**Comment by omariom** [comment]
May be it is time  to make `IThreadPoolWorkItem` public or create it's public equivalent?
Then `state` could be carried by the implementers. Pooling could be possible as well.
And in case `context` is null  or `ExecutionContext.Default` it wouldn't be necessary to wrap the provided workitem.

**Comment by ericeil** [comment]
I don't think these can be pooled without some changes to the work queue implementation, which does a bunch of crazy lock-free stuff that assumes object identity is a good proxy for work item identity.  If it suddenly became true that a given object may now represent many different workitems, depending on when you observe it, then we'd be likely to have a long tail of subtle issues where we fail to execute work, execute it twice, etc.  

Getting this to work correctly would be very hard.

**Comment by benaadams** [comment]
Closing, as resolved in a way.
