### ISSUE TITLE
ThreadAbortException caught without rethrow?

### ISSUE THREAD

**Issue by rominator1983** [dotnet/coreclr#3155]
Hi,

Colleagues of mine had an isse with a ThreadAbortException (used heavily in ASP.NET)
The exception was caught in a catch-block "catch (ThreadAbortException)". As you know the exception has to be rethrown by the runtime after the finally block even if there is no "throw;"-statement in the catch-block.

This happened with a C#6-build, 64-bit Architecture (don't know if build-setting or runtime-architecture. Probably "Any CPU"), .NET 4.5.x-Runtime. So it seems like a problem with the C#6-Output.
We do not have a repro-sample at the moment since this happened on a testing-machine in a complicated try/catch-scenario.

The work-around was to add a "throw;" in the "catch (ThreadAbortException)"-block. This should not be needed! This behaviour can be problematic if there is a "catch (Exception)"-block without a "throw;".
This can obiously break the standard ASP.NET-behaviour and cause havoc in IIS!

Can anyone look into this?

Thank you and kind regards

**Comment by MichaelKetting** [comment]
Standard release build, AnyCPU, 64-bit AppPool

We haven't done a repro yet outside of IIS, so no idea if it is a general platform compatibility problem or isolated to IIS-hosted applications.

Best regards, Michael

**Comment by MichaelKetting** [comment]
That issue actually belongs to Roslyn (https://github.com/dotnet/roslyn), not the Core CLR.
I'll create one update here once we have a repro-sample available.

**Comment by rominator1983** [comment]
I opened an issue https://github.com/dotnet/roslyn/issues/8800 since this is most likely not an RyuJIT/CoreCLR problem.

**Comment by sharwell** [comment]
@rominator1983 At the point where the failure occurs, is the thread in an "abort requested" state?

```csharp
bool abortRequested = (Thread.CurrentThread.ThreadState & ThreadState.AbortRequested) != 0;
```

I can't see how this would be a Roslyn issue. Nothing in the C# language specification points to the special behavior of `ThreadAbortException` which would normally lead me to believe it is a runtime issue. However, nothing in ECMA-335 specifies this behavior either, which would suggest the documented behavior of `ThreadAbortException` is an unspecified behavior of the runtime which may or may not occur in any given implementation, although I would expect consistent behavior within a specific implementation.

**Comment by MichaelKetting** [comment]
@sharwell Since we could triage this to using/not-using the C#6 compiler, strange/weird as is it, yeah it does look like it is due to Roslyn. 

That's interesting. I'll admit, I never read the standard, but if the MSDN is stating that ThreadAbortExceptions can't be caught (https://msdn.microsoft.com/en-us/library/system.threading.threadabortexception.aspx, "ThreadAbortException is a special exception that can be caught, but it will automatically be raised again at the end of the catch block.") and this can actually vary between the Desktop CLR and the Core CLR, this might also be a bit of a surprise for folks switching platforms.

**Comment by jkotas** [comment]
This looks related to a known issue that was fixed in .NET Framework 4.6.

Roslyn C# compiler used to generate a slightly different IL code for complex exception handling clauses. It exposed bugs in how JITed code deals with thread abort handling. This issue was fixed both:
- In RyuJIT: Generate code that handles thread abort properly (https://github.com/dotnet/coreclr/blob/master/src/jit/importer.cpp#L7805)
- In Roslyn: Do not generate the IL code that exposes the JIT bug (https://github.com/dotnet/roslyn/blob/7acf8dd1a6db27faf922db16bd2de133d9860769/src/Compilers/Core/Portable/CodeGen/ILBuilder.cs#L607).

The JIT fix was done by @BruceForstall (TFS bug #1088278), the Roslyn fix was done by @VSadov (TFS bug #1088278).

Can you check whether the Roslyn compiler that you are using contains the above fix?

**Comment by MichaelKetting** [comment]
@jkotas, I'll have to appologize for not properly noticing your response over on this thread. I've taken the liberty to quote it over on https://github.com/dotnet/roslyn/issues/8800#issuecomment-192639041, since we are affected by the Roslyn issue. I've also given a more detailed response to your questions there and would very much like to continue the discussion on the Roslyn thread to keep things single threaded :) But just for reference purposes: I will be tracking down the exact versions but I believe it was the RTM version of MSBuild Tools 2015 and Visual Studio 2015 Update 1, but those versions I will have to verify with my colleagues next week and will be postign the results in https://github.com/dotnet/roslyn/issues/8800

Best regards, Michael

**Comment by sergiy-k** [comment]
Hi @rominator1983, @MichaelKetting, do you still want to keep this issue open on the CoreCLR repository? I'm asking because you opened another one for this problem on https://github.com/dotnet/roslyn. Thank you!

**Comment by MichaelKetting** [comment]
@sergiy-k It's okay to close it for me. Thanks :)

**Comment by sergiy-k** [comment]
Thank you!
