### ISSUE TITLE
Task.Delay hangs tests on Linux

### ISSUE THREAD

**Issue by cesarbs** [dotnet/coreclr#3306]
Repro here:

https://github.com/cesarbs/AsyncHangRepro

Does not happen on Windows or Mac.

We're hitting this issue in `HandlesAsyncExecutes` and `PropagatesAsyncExceptions` in https://github.com/aspnet/Common/blob/dev/test/Microsoft.Extensions.CommandLineUtils.Tests/CommandLineApplicationTests.cs.

**Comment by stephentoub** [comment]
Is your Linux machine single-core?

**Comment by cesarbs** [comment]
@stephentoub Yes.

**Comment by stephentoub** [comment]
It's not a bug in Task.Delay.  xunit uses a SynchronizationContext to ensure that at most N tests run at a time, where by default N == Environment.ProcessorCount.  If N is one, and if you block that one thread, nothing else will run.  In your example, you're blocking waiting for an operation to complete, but in order for it to complete, it needs to queue an await continuation back to the SynchronizationContext whose sole worker is blocked.  I expect in your repro if you change ```await Task.Delay(5);``` to ```await Task.Delay(5).ConfigureAwait(false);```, or if you make your ```Repro``` fact an async method and await instead of blocking, or if you override xunit's default number of workers, etc., that your issue will go away.

**Comment by cesarbs** [comment]
I wasn't aware of those details. Thanks! :smile: I'll fix the test.

**Comment by stephentoub** [comment]
:smile:
