### ISSUE TITLE
Marshal.SecureStringToGlobalAllocAnsi

### ISSUE THREAD

**Issue by Bibo1978** [dotnet/coreclr#3338]
When building with CoreCLR I am getting this error 
 DNXCore,Version=v5.0 error 
CS0117: 'Marshal' does not contain a definition for 'SecureStringToGlobalAllocAnsi'

Is there a missing dependency .. or this is an error

**Comment by vcsjones** [comment]
You need to add `"System.Security.SecureString"` as a dependency to your project, then use `System.Security.SecureStringMarshal.SecureStringToCoTaskMemUnicode` to convert your secure string.

The DNXCore version of this package seems to only support the Unicode encoding using the COM allocator, not Ansi or the global allocator.

The implementation of this appears to only work on Windows, as well.

**Comment by ellismg** [comment]
I believe we decided to remove System.Security.SecureString from .NET Core because we would be unable to implement it cross platform in a reasonable way.  Some pre-release packages were published to NuGet before we made that call, but they will not be cross platform and will not go stable with the rest of .NET Core 1.0

Are you trying to port some existing code to .NET Core?

/cc @stephentoub

**Comment by stephentoub** [comment]
https://github.com/dotnet/apireviews/blob/master/2015-07-14-securestring/README.md

**Comment by sergiy-k** [comment]
Hi @Bibo1978, I'm closing this issue based on the comments. Please feel to re-open it if you need more information.

**Comment by sturlath** [comment]
@stephentoub your urls not working. This works https://github.com/dotnet/apireviews/tree/master/2015/07-14-securestring

**Comment by sturlath** [comment]
https://github.com/dotnet/apireviews/tree/master/2015/08-11-process-and-securestring
