### ISSUE TITLE
Debugger causes OSX security prompt when launching

### ISSUE THREAD

**Issue by gregg-miskelly** [dotnet/coreclr#3369]
In testing on a clean OSX El Capitan box, we are seeing that when dbgshim launches vmmap to find the version of CoreCLR in the target process the user gets a security prompt. We should see if we can do something else to avoid this. For example: shared memory section instead of image map, or calling the image APIs directly.

**Comment by janvorli** [comment]
FYI - lldb does the same thing unless run using sudo.

**Comment by gregg-miskelly** [comment]
We haven't been able to quite find the pattern of when OSX decides to show this dialog -- it does **NOT** seem to be any of:
* Once per reboot
* Once per machine
* Once per project

There must also be some sort of security setting that causes it to not get shown anymore.
We will need to better understand when this happens to see how important it is to fix.

**Comment by janvorli** [comment]
I have remembered that the `/usr/sbin/DevToolsSecurity --enable`  fixes the problem for lldb and it needs to be run once in the lifetime of the machine. But it needs to be run from the GUI since it shows the same kind of dialog.
Please see https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man8/DevToolsSecurity.8.html
I wonder if it would fix the problem for us too.

**Comment by gregg-miskelly** [comment]
We will have to figure out a reliable repro so that we can confirm, but it sounds very promising.

**Comment by mikem8361** [comment]
@gregg-miskelly Should we close this issue now since I haven't seen a reliable repro?

**Comment by gregg-miskelly** [comment]
Sure, we can close this for now.

**Comment by tzwlai** [comment]
Thanks Gregg.  Closing this now.
