### ISSUE TITLE
JIT's allocator performance seems to be low

### ISSUE THREAD

**Issue by mikedn** [dotnet/coreclr#3408]
I profiled `crossgen mscorlib.dll` out of curiosity and noticed that ~5% of the time is spent in `VirtualFree`. These free calls come from the `ArenaAllocator` (formerly known as `norls_allocator`). It's kind of funny that freeing memory takes about the same time as other JIT actions that do actual work (for example, `SsaBuilder::Build` takes ~5% as well).

I suspect that this happens because the allocator's page is 64 kbytes and as a result a lot of pages are allocated and a lot of free calls have to be made. Though it's peculiar that allocation is very fast (time spent in `VirtualAlloc` is less than 1%), perhaps this is a Windows kernel issue.

In any case, 64 kbytes seems too low for 64 bit architectures. I tried with 1 megabyte and `crossgen mscorlib.dll` time drops down from ~6.8 seconds to ~6.0 seconds.

@pgavlin Perhaps you'll find this interesting, as far as I understand from your recent commit you're planning to do some more work around the allocator.

**Comment by mikedn** [comment]
The command line is simply `crossgen System.Private.CoreLib.dll` (it was mscorlib.dll before). The 6.8 seconds result was obtained on a Haswell i5-4440 (6 MB cache, 3.10 GHz), 8 GB RAM and Windows 10 x64.

I can try later today various things, let me know what you have in mind. For now I can say that the 6.8 seconds persists so there weren't any positive or negative changes since I reported this.

> but for running apps it doesn't look that simple - I've run a bunch of experiments with ASP.NET / MusicStore and Roslyn, and what seemed to work best was to start with 128K and then add 256K chunks after that

I wonder if we can't estimate an initial size based on method IL code size and number of local variables. Probably it's possible but we'd need to keep this estimation up to date with compiler changes and that may turn out to be a problem.

**Comment by mikedn** [comment]
[Here](https://gist.github.com/mikedn/8cea1c56965f1e569e60485f27c7bde6) are the results from a series of crossgen runs with 64, 128, 256, 512 and 1024 kbytes pages. It's pretty easy to observe that 512 kbytes is enough and event 256 would do, 1024 is too much.

**Comment by pkukol** [comment]
Thanks for getting those measurements - the results basically jive with what I've seen. The allocator I think is initialized before we know much about the IL so we may not have the data available for the initial chunk, but after that we should probably add at least 128 or 256K at a pop and, for bonus points, come up with a simple heuristic based on whatever we think is easy to gauge and is relevant. Does this sound like a reasonable plan?

**Comment by mikedn** [comment]
> Does this sound like a reasonable plan?

Yes.

> The allocator I think is initialized before we know much about the IL so we may not have the data available for the initial chunk.

Good point. Though it would be interesting to know how much memory the JIT needs to compile a small method. If we discover that it needs more than 256k of memory to compile a 10 bytes method then it's clear that we can allocate even more at first. Though I really hope that it doesn't need that much memory for 10 bytes of IL :)

**Comment by pgavlin** [comment]
One thing that is important to note about the allocator when considering the size of the initial page is that the same allocator instance is shared between most methods and the first page will remain allocated as long as the JIT instance is in use (i.e. it is allocated when `jitStartup` is called and freed during `jitShutdown`). It would be interesting to measure the average memory consumption per method when crossgen'ing S.P.C and see how things perform when the initial allocation is just large enough to cover that amount.

**Comment by pgavlin** [comment]
@pkukol: that plan seems reasonable to me as well. It seems like we might also want to vary our allocation sizes based on the host architecture if we aren't already doing so.

**Comment by pkukol** [comment]
You're right @pgavlin, and @mikedn - though I think the initial page should probably remain pretty modest, based on what we discover about the size distribution (except maybe in specific scenarios like NGen on x64 since there's likely lots of memory available there). Past experience tuning things like this tells me that the problem space is likely very hard to map, though (the graph usually looks like a crazy spiky fractal) so I wouldn't aim for perfection (unless someone wants to spend their time doing it, of course ;). I'd also tend to be on the conservative side because the harm done by trying to grab massive blocks could be much worse than sipping memory a bit slower than we could in other cases. Perhaps the thing to do is collect total memory consumed per method histograms for a few of the major scenarios, and then try a few allocator configs and move on. Sound OK or does anyone have a better suggestion? And of course volunteers to help with this are always welcome as well ;).

**Comment by mikedn** [comment]
> Sound OK or does anyone have a better suggestion?

Hmm, there may be some alternatives:

1. Attempt to reserve a large chunk of virtual memory from the OS. Commit memory only as needed and free the large chunk at the end. Tempting but might work or not depending on OS implementation.

2. Don't do nothing at the moment, first attempt to decrease the JIT memory usage. For example, there was once a discussion about having a per phase allocator so that memory that's used only within one phase can be reused by future phases.

**Comment by pgavlin** [comment]
> For example, there was once a discussion about having a per phase allocator so that memory that's used only within one phase can be reused by future phases.

IIRC @russellhadley looked into this a bit. Russ, any feedback?

**Comment by pkukol** [comment]
Quick comment - there used to be a "page commit" allocator, but 21 years later I can't remember why I dropped it. Please feel free to experiment, of course, but my recollection was that it wasn't worth the hassle of adding #ifdef's for different targets and all that. As for freeing up no longer needed memory, well that's a pretty radical concept; seriously, though, doing that would likely make the other tweaks look silly but it's potentially zillion times more work. We could also look at making the initial block size smarter - maybe based on code we see being compiled or whatever, it could even be a commit-style thing where it expands and shrinks based on what happens. Or we could leave this kind of stuff to MSR and do something simple and move on ;). Let's hear from @russellhadley first, though.

**Comment by russellhadley** [comment]
@pkukol, @mikedn, @pgavlin My experiments never got out of the prototype stage.  I was working on a bug where the SSA build was using alloca as part of it's topological sort of the flow graph and blowing up on a large flow graph in NGen mode.  I experimented with a "Temp" allocator object to see if I could get all of the SSA info into the temp pool so it could be freed in bulk after the optimizer.   In concept these "temp" allocators are pretty simple (so simple it's been done in every other compiler I've ever worked on so I'm not really being creative here) but as Peter says it's probably difficult to get this kind of change seamlessly integrated with the current source.  Long story short I don't have data on this so it remains an outstanding question.

**Comment by briansull** [comment]
@russellhadley

**Comment by pgavlin** [comment]
Given the impact that the initial block size has on JIT throughput, looking into this further seems timely.

cc @BruceForstall @CarolEidt

**Comment by AndyAyersMS** [comment]
Running release build PMI jitting Microsoft.CodeAnalysis.CSharp.dll I see about 1.7% of the time in `PooledAllocator::destroy` (1.1% for a minopts run).

Am going to start looking at performance tradeoffs for using larger default page sizes.

**Comment by AndyAyersMS** [comment]
Scaling for time in spent jit, it's 1.8% for minopts...

**Comment by mikedn** [comment]
> Running release build PMI jitting Microsoft.CodeAnalysis.CSharp.dll I see about 1.7% of the time in PooledAllocator::destroy (1.1% for a minopts run).

Hmm, that seems to be far lower than the impact it has on crossgen corelib. I tried this recently on the latest Win 10 build and the crossgen time still drops by 0.5-1 sec if the default page size is increased to 128k.

That said, the issue is a bit strange. MemStats shows that 51% of the methods in corelib only need the default pooled page and another 36% only need to allocate an extra page. The largest method needs 56 pages but then you'd expect such a method to also take quite a bit of time to compile. It's not very clear how the numbers add up so that VirtualFree ends up taking 5% during crossgen.

I tried to replicate the VirtualAlloc/VirtualFree pattern outside the JIT but it didn't look like VirtualFree is extraordinarily expensive. Though one could question the use of virtual memory allocation vs. heap memory allocation. It's not clear why the JIT thinks it's special enough to go directly to the kernel to ask for memory but HeapAlloc/HeapFree might work better.

At the same time, the JIT has a tendency to waste memory at every step so increasing the allocator page size is a bit of a sweep the garbage under the rug case...

**Comment by AndyAyersMS** [comment]
This was with PMI and not crossgen, so there might be some differences from that. And I was using PerfView to measure, and can't figure out how to stop it from asking the CLR for some events that end up kind of costly.

**Comment by mikedn** [comment]
> And I was using PerfView to measure, and can't figure out how to stop it from asking the CLR for some events that end up kind of costly.

Can't PMI somehow measure wall clock time? This is one of those rare cases where the impact is so large that you can measure by using the most primitive means, at least in the crossgen case. It would be interesting to find out that this doesn't hold true for PMI and that this issue is somehow crossgen specific.

**Comment by mikedn** [comment]
For example in the crossgen case I use a little program that shows the wall clock time (measured using a stopwatch) and process times reported by the `Process` class. I end up with something like:
```
wall:7.117s total:7.109s user:6.031s kernel:1.078s
```
where one can easily see the huge amount of time spent in kernel mode. A profiler can then show that most of that is due to `VirtualFree`.

**Comment by AndyAyersMS** [comment]
Yeah, sure. I just haven't tried it yet.

I've been planning on looking into jit throughput issues with PMI moreso that crossgen, since PMI is somewhat closer to what end users experience.

**Comment by mikedn** [comment]
> but HeapAlloc/HeapFree might work better

As in
```
wall:6.516s total:6.470s user:6.269s kernel:0.202s
```
instead of
```
wall:7.357s total:7.366s user:6.372s kernel:0.994s
```

**Comment by AndyAyersMS** [comment]
Keeping current request pattern, just changing the default size, minopts, pmi of Microsoft.CodeAnalysis.CSharp:

| Size | Size Ratio | Time (ms) | Time Ratio |
| ---  | ---- | ---  | --- |
| 64K  | 1x   | 2811 | 1.00 |
| 128K | 2x   | 2758 | 0.98 |
| 192K | 3x   | 2592 | 0.92 | 
| 256K | 4x   | 2574 | 0.92 |
| 320K | 5x   | 2699 | 0.96 |
| 512K | 8x   | 2636 | 0.94 |

Same, but with full optimization:

| Size | Size Ratio | Time (ms) | Time Ratio |
| ---  | ---- | ---  | --- |
| 64K  | 1x   | 6644 | 1.00 |
| 128K | 2x   | 6174 | 0.93 |
| 192K | 3x   | 5958 | 0.90 | 
| 256K | 4x   | 5959 | 0.90 |
| 320K | 5x   | 5910 | 0.90 |
| 512K | 8x   | 5975 | 0.90 |

So yes it looks like there is some real promise here. 3x is maybe a sweet spot.

Let me try this on some jit-intensive apps.

**Comment by AndyAyersMS** [comment]
Some benchmark data from JitBench. 3-5% improvement across a lot of metrics. No sure what's up with Word2Vec training.

|       Benchmark         |          Metric      |        Default (64K) |  3x Default (192K)  |  Ratio |
| :---------------------- | :------------------- | -------------------: | ------------------: |  ----: |
| Dotnet_Build_HelloWorld |       Duration (ms)  |      1453  |    1412 |  0.97  |
|        Csc_Hello_World  |       Duration (ms)  |      720.5 |   697.5 |  0.97  |
|      Csc_Roslyn_Source  |       Duration (ms)  |       3004 |    2968 |  0.99  |
|             MusicStore  |        Startup (ms)  |        654 |     638 |  0.98  |
|             MusicStore  |  First Request (ms)  |        682 |     651 |  0.95  |
|             MusicStore  | Median Response (ms) |       2.54 |   2.525 |  0.99  |
|               AllReady  |        Startup (ms)  |       1588 |    1529 |  0.96  |
|               AllReady  |  First Request (ms)  |        583 |     554 |  0.95  |
|               AllReady  | Median Response (ms) |        4.5 |    4.38 |  0.97  |
|               Word2Vec  |       Training (ms)  |      48065 |   51338 |  1.07  |
|               Word2Vec  |   First Search (ms)  |         31 |    31.5 |  1.02  |
|               Word2Vec  |  Median Search (ms)  |      28.22 |    27.9 |  0.99  |

**Comment by AndyAyersMS** [comment]
Am also going to try and look at perf on non-Windows and for 32 bits.

I would guess that for 32 bit jits we don't need quite as much of a size boost. Rule of thumb is that data size grows 60% when moving from 32 to 64 bits. So if 192K is "optimal" for 64 bits, maybe 128K would "optimal" for 32 bits.

**Comment by AndyAyersMS** [comment]
On a MacMini, using 192K default size, total PMI time for Microsoft.CodeAnalysis.CSharp:

| Size | Size Ratio | Time | Time Ratio | 
| ---- | --- | --- | ---
| 64K |  1x       | 7890 | 1.00 |
| 128K | 2x      | 6533 | 0.83 |
| 192K | 3x      | 6610 | 0.84 |
| 320K | 5x     | 6589 | 0.84 |

and with`COMPlus_JITMinOpts=1` (why is this capitalized differently than most other jit opts..?)

| Size | Size Ratio | Time | Time Ratio | 
| ---- | --- | --- | ---
| 64K |  1x       | 2979 | 1.00 |
| 128K | 2x      | 2591  | 0.87 |
| 192K | 3x      | 2577 | 0.87 |
| 320K | 5x     | 2695 | 0.90 |

So 3x looks like a pretty good change there too.

**Comment by AndyAyersMS** [comment]
3x also seems be slightly beating out 2x for x86 windows.

**Comment by mikedn** [comment]
> Rule of thumb is that data size grows 60% when moving from 32 to 64 bits. So if 192K is "optimal" for 64 bits, maybe 128K would "optimal" for 32 bits.

Indeed. And it looks like 64K was what JIT32 used so RyuJIT should have moved to at least 128K a long time ago when it targeted 64 bit.

> On a MacMini, using 192K default size, total PMI time for Microsoft.CodeAnalysis.CSharp:

Nice to see that this would be an improvement on other platforms as well.

What do you think about using HeapAlloc instead of VirtualAlloc? The reason why VirtualAlloc is used is probably lost in history but these days HeapAlloc sounds like a more reasonable choice while VirtualAlloc would be one of those special tweaks that requires some pretty good evidence to back up.

**Comment by AndyAyersMS** [comment]
I kicked the tires a bit and didn't see any additional benefit (on windows) using HeapAlloc over VirtualAlloc with the 3x default size increase.

**Comment by mikedn** [comment]
> I kicked the tires a bit and didn't see any additional benefit (on windows) using HeapAlloc over VirtualAlloc with the 3x default size increase.

The idea is to use HeapAlloc without increasing the default. Though I'd probably make a compromise - 128k default on 64 bit + HeapAlloc.

**Comment by AndyAyersMS** [comment]
Ok, let me give that a try.

**Comment by AndyAyersMS** [comment]
Using HeapAlloc at 64K gives perf comparable to VirtualAlloc running PMI at 128K or 192K. Increasing the HeapAlloc size beyond 64K didn't seem to change perf much.

I'm still not sure how to robustly evaluate whether using HeapAlloc ends up being "better" overall, given that it may lead to more page usage or fragmentation. I suppose the acid test is running this way on actual apps.

I've put the 192K VirtualAlloc version through our scenario perf lab (similar to what I ran locally) above and the data is still holding up very nicely -- eg 7% faster startup time in MusicStore (where startup is dominated by jit time), 2% faster building simple apps via Roslyn / MSBuild.

So let me do the same for the HeapAlloc version.

@jkotas @janvorli any thoughts here?

**Comment by jkotas** [comment]
I do not think that the chunk size is what really matters. I think think what really matters is how much memory is kept around cached and how to manage the total size of this cache.

I think that the key problem today is that there is just one 64kB chunk cached. I think that doing something about this single one-size-fits-all chunk should be part of the plan. I expect that the difference between 64kB chunk or 192kB chunk will be a wash once you do that.

I can imagine a few different schemes:

- malloc/free does a good job on caching the "right" amount. Then we can just forward the big allocs to malloc/free.

- We believe that we can do better job on caching the "right" amount. Then we should basically implement a logic similar to the managed ArrayPool: have multiple blocks cached per core, and free them up when they are not used for a while.

I would expect that the single cached chunk limitation will make a more significant difference for tiered JIT because of the foreground and background threads are competing for this single chunk now.

**Comment by mikedn** [comment]
> I'm still not sure how to robustly evaluate whether using HeapAlloc ends up being "better" overall, 

Yep, that's the difficult part. It's likely better for the JIT simply because HeapAlloc/HeapFree calls are cheaper than VirtualAlloc/Free calls that involve kernel transitions. The problem is if JIT's alloc/free calls could somehow interfere with other allocations done by the application. Probably for many typical managed applications they won't, simply because most of the app allocated memory will be in the GC heap and that doesn't involve HeapAlloc/Free. But the process heap may still be used - either by other runtime components or by native libraries (e.g. WPF's "milcore").

But then this may be a case of worrying too much about something and end up doing the wrong thing. I remember reading stories about VS using multiple heaps, supposedly in an attempt to avoid fragmentation, and ending up worse due to increased memory usage. JIT's use of VirtualAlloc/Free may too be a case of "this component is special so let's allocate memory in a special way".

**Comment by mikedn** [comment]
> malloc/free does a good job on caching the "right" amount. Then we can just forward the big allocs to malloc/free.

So you're saying to just use malloc and drop JIT's default page? Indeed, at least for crossgen x64, once you switch to HeapAlloc the default page becomes pretty much useless, there's less than 2% difference and that may be just noise.

**Comment by jkotas** [comment]
> So you're saying to just use malloc and drop JIT's default page?

Yes, I think it would be the simplest strategy that gives best results across the range of scenarios and platforms. I think it may be even worth experimenting with making the page size less than 64kB for this plan.

crossgen is single threaded. Most scenarios - especially once tiered JIT is enabled by default - are going to be multi-threaded. I expect that the JIT's default page is more of a problem for them today.

The difference between VirtualAlloc and HeapAlloc is not just in that the VirtualAlloc is syscall. The memory returned by VirtualAlloc has to be zero-filled, memory returned by HeapAlloc does not. Performance of frequent VirtualAlloc/Free depends on supply of zero-filled pages in the system. If there are idle cores - that is likely the case when you are benchmarking single-threaded crossgen, these idle cores will keep supplying the zero-filled pages for free. If you are on a busy system or a small single-core VM/container, the zero-filling will be slowing down the critical path.

> Tempting but sounds like quite a bit of work, in particular the "free them up when they are not used for a while".

Yes, getting custom pools like this right is work. I think we would have it in VM and "free them up when they are not used for a while" part would be done on the finalizer thread that tends to tick naturally.

**Comment by mikedn** [comment]
> I think it may be even worth experimenting with making the page size less than 64kB for this plan.

Hmm, maybe but it may turn out that the JIT can't do much with less than 64KB right now:
```
; crossgen corelib memory statistics
Distribution of total memory used      per method (in KB):
     <=         16 ===>       0 count (  0% of total)
     17 ..      32 ===>      10 count (  0% of total)
     33 ..      64 ===>   14683 count ( 51% of total)
     65 ..     128 ===>   10276 count ( 87% of total)
    129 ..     192 ===>    2037 count ( 94% of total)
    193 ..     256 ===>     720 count ( 97% of total)
    257 ..     512 ===>     597 count ( 99% of total)
    513 ..    1024 ===>     152 count ( 99% of total)
   1025 ..    4096 ===>      47 count (100% of total)
   4097 ..    8192 ===>       0 count (100% of total)
```
> The memory returned by VirtualAlloc has to be zero-filled, memory returned by HeapAlloc does not. Performance of frequent VirtualAlloc/Free depends on supply of zero-filled pages in the system.

Right. Zero filled memory would actually be useful to the JIT as it minimizes the chance that some garbage values are used. But because of JIT's page pooling this zeroing is actually useless.

In the meantime I managed to reduce JIT's memory usage by 6.5% in #18504.

**Comment by jkotas** [comment]
> can't do much with less than 64KB right now

Allocating 4x 16kB blocks using malloc may have better performance than allocating 1x 64kB block. In the default Windows memory allocator, there are two interesting cut-offs: 16kB and 512kB. `size <= 16kB` is using the fast allocator that has per-thread caches, `16kB < size <= 512kB` is using a global cache, `512kB < size` is pass through to VirtualAlloc.

Here is micro-benchmark that demonstrates this /w results from my Windows x64 box:

```c
#include <stdio.h>
#include <Windows.h>

// This is rough approximation of JIT memory usage pattern
static void Work()
{
#if 0 // 2.2 seconds
    void *p1 = malloc(16384);
    memset(p1, 42, 16384);
    void *p2 = malloc(16384);
    memset(p2, 42, 16384);
    void *p3 = malloc(16384);
    memset(p3, 42, 16384);
    void *p4 = malloc(16384);
    memset(p4, 42, 16384);
    free(p4);
    free(p3);
    free(p2);
    free(p1);
#endif
#if 0 // 2.9 seconds
    void *p = malloc(65536);
    memset(p, 42, 65536);
    free(p);
#endif
#if 1 // 74 seconds
    void * p = VirtualAlloc(NULL, 65536, MEM_COMMIT | MEM_RESERVE, PAGE_READWRITE);
    memset(p, 42, 65536);
    VirtualFree(p, 0, MEM_RELEASE);
#endif
}

DWORD WorkerThread(void *)
{
    for (;;) Work();
}

int main()
{
    CreateThread(NULL, 0, WorkerThread, NULL, 0, NULL);
    Sleep(100);
    int start = GetTickCount();
    for (int i = 0; i < 1000000; i++)
    {
        Work();
    }
    int end = GetTickCount();
    printf("%d\n", end - start);
}
```

Also, you can see that VirtualAlloc is super bad on this microbenchmark.

> reduce JIT's memory usage by 6.5%

Nice!

**Comment by mikedn** [comment]
>  In the default Windows memory allocator, there are two interesting cut-offs: 16kB and 512kB. size <= 16kB is using the fast allocator that has per-thread caches, 16kB < size <= 512kB is using a global cache, 512kB < size is pass through to VirtualAlloc.

Thanks, I knew there are some cut-offs but could not find them. I experimented a bit and crossgen corelib does show a 1-2% improvement from decreasing the page size from 64k to 16k. Though I need to check what affect such a change has on internal fragmentation - JIT's arena allocator doesn't handle this. I also wonder if it's worth encroaching on HeapAlloc's per thread caches for 1-2%. Perhaps this will be more clear once the tiered JIT story advances more.

Right now it seems that
* VirtualAlloc isn't a very good choice
* Increasing the default page size because VirtualAlloc is slow isn't a good choice as well

Switching to HeapAlloc seems like a no-brainer, unless someone is concerned that this may somehow negatively impact apps that also do a lot of native memory allocation. Especially if such a change ends up in the desktop version (hmm, how does SQL Server hosting implements ClrHeapAlloc?)

**Comment by jkotas** [comment]
>  HeapAlloc seems like a no-brainer

Agree.

I am not worried about using HeapAlloc in .NET Core.

If there are any worries about the risk for desktop, we can put it under desktop-specific ifdef or quirk. I think that more practical risk is that it may expose latent app bugs: JIT will be likely using same memory as the app, and so it will be exposed to use-after-free bugs in the app.

**Comment by AndyAyersMS** [comment]
Doing some perf lab runs with HeapAlloc (tiered and non-tiered). Trying 16K first.

@mikedn if you have a set of changes you think we should build on, please point me at them.

**Comment by mikedn** [comment]
> if you have a set of changes you think we should build on, please point me at them.

I've run my experiments on top of #15025. Mainly because it's easier to make changes around the pool page as it's separated from the allocator. Otherwise I don't think it affects numbers.

BTW - I also tried `HeapAlloc` + 8k, it seems a bit slower. Right now 16k seems best provided that it doesn't actually increase memory usage due to internal arena fragmentation.

**Comment by AndyAyersMS** [comment]
Lab run is back. 

HeapAlloc @16K reduces tiered JitBench MusicStore first request time by 0.93 (~430 -> 401).  This is a fairly dramatic speedup in the jit considering it is probably even at worst case only using about 

Our measurement ability in the lab is a bit rough but 401 is clearly well below the range of recent observations:

![image](https://user-images.githubusercontent.com/10121823/41562495-aaf686b0-7301-11e8-9a2a-36da6f59fea1.png)

Non-tiered first request speeds up by a similar ratio (~554 -> 510).

This is still with the pooled allocator / cached page stuff in place. I'll pick up your changes and see if removing that has any additional benefits.

**Comment by AndyAyersMS** [comment]
#15025 is merged...time to move this one forward.

I'm going to redo my measurements above with 16K default heap allocations and no cached pages.

**Comment by AndyAyersMS** [comment]
When I disable caching I can't get decent perf out of PMI or crossgen.

With caching I don't see a big difference between 16K and 64K default: smaller page is very slight better for crossgen and worse for PMI.

So that seems to suggest that HeapAlloc plus current caching is a good improvement from where we are now, and that more elaborate caching is worth investigation.

**Comment by jkotas** [comment]
> Locally I see decent speedups with HeapAlloc at 64K

I think you are just indirectly hitting sizes of internal HeapAlloc caches. The numbers say that the caches are big enough to cover `typical_total_size - 64k`, but not enough to cover `typical_total_size`. Also, the numbers will be different for Unix because Unix memory allocator will have different treas-holds for sure, and for Tiered JIT where multiple threads will be competing for the single cached block.

It suggests that we may end up with a custom caching policy at the end.

**Comment by mikedn** [comment]
Hrm, it's starting to look as if it's easier to cut down on JIT's memory usage than sorting this one out :)

**Comment by AndyAyersMS** [comment]
The proposed speedups seem pretty tantalizing though. Previous lab runs had shown decent speedups which is why these new results are a puzzle.

I have run similar HeapAlloc experiments on OSX and have decent results there as well. I don't think we have any official lab measurements for OSX.

I've been using WSL for Ubuntu lately, but I suspect that is not the most robust environment for making these kinds of measurements. I'll have to set up a native install.

So it seems like we have pretty good indications that there are nice improvements to be had. The question is how to do so robustly and reliably.

Is there anything in the runtime already with this sort of caching structure, or would we have to invent something from scratch?

**Comment by jkotas** [comment]
Here is my prototype of a simple custom pool: https://github.com/dotnet/coreclr/compare/master...jkotas:jit-alloc

**Comment by AndyAyersMS** [comment]
Thanks, Jan. That looks promising.

**Comment by erozenfeld** [comment]
@dotnet/jit-contrib

**Comment by mikedn** [comment]
Nice! Much better than the JIT forever holding onto a block of memory.

Is this something that could go into netfx as well or will the JIT have to ifdef it out in that case?

**Comment by AndyAyersMS** [comment]
Lab numbers and local numbers so far are in agreement that this is a big improvement. 

For instance, PMI of Microsoft.CodeAnalysis.CSharp drops from 4400 to around 3800; crossgen of the same goes from 2850 to 2630 (all times ms).

For some reason my tiering lab run failed to produce data. Not sure why just yet.

**Comment by AndyAyersMS** [comment]
Scenario tests are hanging ... looks like the `Reclaim` method needs to reset `s_pCurrentCachedList`.

**Comment by jkotas** [comment]
I have pushed this fix to github shortly after posting here. You must have missed it by a couple of minutes. Sorry for not giving heads up.

**Comment by AndyAyersMS** [comment]
No worries.

Here are some local numbers for scenario benchmarks. Some huge speedups without tiering. 

Interestingly tiering doesn't see as big of wins. Not sure why just yet -- perhaps because the tier 1 jit latency overlaps with ongoing computation, so a slightly faster tier1 jit doesn't impact the overall app time that much. Though I would also have expected tier0 to speed up, but perhaps the current caching scheme handles that reasonably well?

I'll see if the lab gets similar results.

**NO TIERING**

|        Benchmark        |     Metric (ms)  |        jit-alloc     |    baseline           | ratio  |
| ----------------------- | ---------------- |  ------------------- |  -------------------  | ------ |
| Dotnet_Build_HelloWorld |        Duration  |     1070 (1061-1080) |      1390 (1284-1409) | 0.770  |
|         Csc_Hello_World |        Duration  |      460.5 (459-461) |         571 (563-574) | 0.806  |
|       Csc_Roslyn_Source |        Duration  |     2178 (2165-2199) |      2532 (2514-2561) | 0.860  |
|              MusicStore |         Startup  |        506 (499-513) |         523 (515-526) | 0.967  |
|              MusicStore |   First Request  |        453 (447-457) |         506 (501-512) | 0.895  |
|              MusicStore | Median Response  |     2.96 (2.91-3.05) |      2.82 (2.79-2.88) | 1.050  |
|                AllReady |         Startup  |     1074 (1065-1079) |      1153 (1148-1159) | 0.931  |
|                AllReady |   First Request  |        376 (374-386) |         420 (418-421) | 0.895  |
|                AllReady | Median Response  |      3.88 (3.79-3.9) |       3.81 (3.8-3.88) | 1.018  |
|                Word2Vec |        Training  |  33397 (33056-33726) |   34370 (33923-34721) | 0.972  |
|                Word2Vec |    First Search  |           24 (24-24) |            25 (24-25) | 0.960  |
|                Word2Vec |   Median Search  |  22.03 (21.89-22.14) |    21.9 (21.85-21.96) | 1.006  |

**TIERING**

|        Benchmark        |    Metric (ms)  |        jit-alloc     |    baseline            | ratio  |
| ----------------------- | --------------- |  ------------------- |  --------------------  | ------ |
| Dotnet_Build_HelloWorld |        Duration |      1034 (1025-1038)|       1044 (1039-1056) | 0.990  |
|        Csc_Hello_World  |        Duration |      388.5 (387-390) |       387.5 (386-388)  | 1.003  |
|      Csc_Roslyn_Source  |        Duration |     2280 (2272-2327) |      2312 (2286-2341)  | 0.986  |
|             MusicStore  |         Startup |        473 (469-478) |         482 (481-485)  | 0.981  |
|             MusicStore  |   First Request |      364.5 (363-366) |       396.5 (394-400)  | 0.919  |
|             MusicStore  | Median Response |     2.21 (2.14-2.23) |      2.12 (2.07-2.21)  | 1.042  |
|               AllReady  |         Startup |       984 (971-1005) |      1024 (1020-1032)  | 0.961  |
|               AllReady  |   First Request |        297 (295-305) |         316 (313-318)  | 0.940  |
|               AllReady  | Median Response |     3.11 (3.09-3.13) |      3.16 (3.15-3.22)  | 0.984  |
|               Word2Vec  |        Training |  36617 (35701-37007) |   35648 (35560-35742)  | 1.027  |
|               Word2Vec  |    First Search |           85 (83-86) |            82 (82-87)  | 1.037  |
|               Word2Vec  |   Median Search |   21.99 (21.9-22.01) |    21.8 (21.74-21.84)  | 1.009  |

**Comment by AndyAyersMS** [comment]
Couple of ideas:
* Defer flushing the free lists if the tiered compilation manager has a backlog of rejit requests. 
* Initialize the last flush time during `Init` so the first finalizer tick doesn't always immediately flush.

**Comment by jkotas** [comment]
> Initialize the last flush time during Init so the first finalizer tick doesn't always immediately flush

Fixed.

> Defer flushing the free lists if the tiered compilation manager has a backlog of rejit requests.

I think that the current implemented policy should take of this reasonably well. If the tiered compilation keeps doing work, the blocks that it actually needs won't get freed. They will get pushed to second list once in a while, but then bumped to the first list. The cost of pushing the blocks to the second list should be pretty small.

This may help outliers like when the method takes more than 2 seconds to JIT. We can go back to this if outliers like this become more common.

**Comment by AndyAyersMS** [comment]
> Defer flushing the free lists if the tiered compilation manager has a backlog of rejit requests

I didn't see much difference with this one way or the other, so no need to pursue it now.

Lab results generally in agreement that this is a solid improvement, though they are not quite as optimistic as my local runs.

Cache misses attributed to clrjit.dll are significantly reduced in lab runs.
