### ISSUE TITLE
Named mutex not supported on Unix

### ISSUE THREAD

**Issue by drieseng** [dotnet/coreclr#3422]
Creating a named mutex on Unix currently throws a **PlatformNotSupportedException** stating *"Named synchronization primitives are not supported on this platform"*.

Is this scheduled to arrive  ? I'm sure @migueldeicaza will be eager to port this from **Mono** to **.NET Core** :p

Personally, I don't think it makes sense to expose APIs on both Windows and Unix, but only implement them on one of them.   In what way does the **Portability Analyzer** even take this into account ?

**Comment by mikedn** [comment]
Related to #1237

**Comment by drieseng** [comment]
Duplicate of issue #1237.

**Comment by mikedn** [comment]
I wouldn't say it's a duplicate. That issue was resolved by removing the functionality. It would be nice to actually fix the actual problem and restore the functionality.

**Comment by stephentoub** [comment]
> I'm sure @migueldeicaza will be eager to port this from Mono to .NET Core :p

Miguel can correct me if I'm wrong, but I don't believe Mono implements this either, or more specifically I believe they implement it the same general manner that the coreclr did before it was disabled to throw those exceptions: the names are only process-wide, not cross-process.  That's why we decided to throw exceptions on coreclr; otherwise, since names are typically used for cross-process synchronization, you use the names thinking you're getting cross-process synchronization, but in reality you've just got a bunch of race conditions silently waiting to cause problems.

**Comment by drieseng** [comment]
Reopened because of @mikedn comment.

**Comment by kouvel** [comment]
My search for ways to add a cross-process mutex didn't yield many options. I'm currently planning on this:
- On Linux, we have the pthread robust mutex that can be allocated in shared memory, so that's great
- Elsewhere, it seems like file locks are the only decent option

Currently, we are looking for the following features:
- Track lifetime across processes and users. One process/user should be able to create the mutex, and another process/user should be able to delete it. This eliminates the System V semaphore since only the creator or owner can delete a semaphore set.
- Detect when no processes are using the mutex so that it can be deleted or reinitialized. File locks allow this detection.
- A way to detect an abandoned mutex (similar to pthread robust mutex) even if the process owning the lock crashes or is killed.
- Be able to do a timed wait. On OSX, this eliminates pthread named semaphore and pshared rwlock. For file locks too, we would need to poll for the lock in loop, sleeping in-between, which has other issues but may be workable if it's the only option. I also looked into Mach semaphores and kqueue, but their lifetime seems to be tied to the creator process.

Any other ideas?

CC @kangaroo

**Comment by janvorli** [comment]
cc @krytarowski for NetBSD

**Comment by krytarowski** [comment]
I don't have anything portable offhand, other than maybe `<semaphore.h>` or `pthread_mutexattr_init`(3).

**Comment by jasonwilliams200OK** [comment]
Mono's create named semaphore implementation is situated at: https://github.com/mono/mono/blob/ef40790/mono/io-layer/semaphores.c#L193-L289.

**Comment by stephentoub** [comment]
> Mono's create named semaphore

Mino's implementation is not cross-process.

**Comment by ChangePlaces** [comment]
I'm confused, what's the current state of named Mutexes in core? Will they work on windows and linux?

**Comment by krytarowski** [comment]
There was an implementation with POSIX robust mutexes on Linux.

**Comment by ChangePlaces** [comment]
so that's a yes?

**Comment by krytarowski** [comment]
I guess so, this is why I need to implement POSIX robust mutexes on my platform (NetBSD).

**Comment by ChangePlaces** [comment]
I've just tried on Ubuntu 14.04 and the answer is a no

**Comment by stephentoub** [comment]
> I've just tried on Ubuntu 14.04 and the answer is a no

What code did you try? Named mutexes should work fine on in Ubuntu.

**Comment by ChangePlaces** [comment]
Interesting, this is my code, other processes are not honouring the mutex and are acquiring the mutex and repeating the same work

```
using (var m = new Mutex(false, mutexName))
{
    var hasMutex = false;
    try
    {
	if (m.WaitOne(2))
	{
	    hasMutex = true;
	    ProcessIterationAsync(currentOutputFileNameBase, c, _config.CountryCode).Wait();
	}
    }
    catch (AbandonedMutexException e)
    {
	continue;
    }
    catch (Exception e)
    {
        continue;
    }
    finally
    {
	if (hasMutex)
	{
	    m.ReleaseMutex();
	}
    }
}
```

**Comment by kouvel** [comment]
What name did you use? By default, names have session scope and sessions are more granular on Unix (each terminal gets its own session). If you haven't already, please try adding a "Global\" prefix to the name minus the quotes.

There is build-time code to detect if the system supports POSIX robust mutexes, see https://github.com/dotnet/coreclr/blob/master/src/pal/src/configure.cmake#L997 and https://github.com/dotnet/coreclr/blob/master/src/pal/src/configure.cmake#L1020. Based on that, it would use POSIX robust mutexes or file locks, but it should work either way.

**Comment by kouvel** [comment]
Although unrelated, in the above code, when an AbandonedMutexException is thrown, the thread is still given ownership of the lock, so you'd have to ReleaseMutex on that path as well

**Comment by ChangePlaces** [comment]
I prefixed the name with "Global\" as suggested [here](https://msdn.microsoft.com/en-us/library/system.threading.mutex(v=vs.110).aspx) to no avail. I am running the processes in multiple screen instances. This is with RC4

**Comment by kouvel** [comment]
Would it be possible to provide a small runnable repro? I can give it a try and see what's going on.

**Comment by ChangePlaces** [comment]
I took this down to the most basic example I could make and it worked... so I worked backwards and fixed. I think it was the missing "Global\\" - User error - thanks and sorry!

**Comment by kouvel** [comment]
Ok great, closing then

**Comment by NVoronchev** [comment]
Hi!

I have try the following program in Debian 9 and it seems mutex is not global (cross-process):
```
using System;
using System.Threading;

namespace test_mutex
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Started! Try to Mutex.ctor...");
            var m = new Mutex(false, @"Global\aaaaa");

            Console.WriteLine("We have the Mutex! Try to lock mutex...");
            m.WaitOne();

            Console.WriteLine("Locked! Sleep...");
            for (int i = 5; i > 0; --i)
            {
                Console.WriteLine("  {0}", i);
                Thread.Sleep(1000);
            }

            Console.WriteLine("Sleep done! Release mutex...");
            m.ReleaseMutex();

            Console.WriteLine("Done.");
            m.Close();
        }
    }
}
```
I started two instances of the application and both of them counting down simultaneously.

Would you be so kind to clarify is it my mistake or Mono bug?

**Comment by stephentoub** [comment]
> Would you be so kind to clarify is it my mistake or Mono bug?

Are you using .NET Core or Mono?

**Comment by NVoronchev** [comment]
@stephentoub, I try Mono `5.18.0.240` and `6.1.0 (master/72512cfbcbc Thu Feb 21 19:00:53 MSK 2019)`.

**Comment by stephentoub** [comment]
Thanks.  This issue / repo are for coreclr.  Can you open an issue instead in http://github.com/mono/mono?

**Comment by NVoronchev** [comment]
@stephentoub, Oh, I see. I chose wrong project. My apologies!

**Comment by stephentoub** [comment]
No worries; it's confusing :)

**Comment by ritchxu** [comment]
Sorry for pinging on old thread. What is the situation for `Semaphore`? Which seems to still [only support named instance on Windows](https://github.com/dotnet/corefx/blob/master/src/Common/src/CoreLib/System/Threading/Semaphore.Windows.cs).

**Comment by stephentoub** [comment]
> Which seems to still only support named instance on Windows.

Correct.
