### ISSUE TITLE
ObsoleteAttribute should not be sealed

### ISSUE THREAD

**Issue by MovGP0** [dotnet/coreclr#349]
The ```ObsoleteAttribute``` should not be sealed, so that customers can provide specialized obsolete messages: 

```csharp
public sealed MyObsoleteAttribute : ObsoleteAttribute
{
   private Version CurrentAssemblyVersion => // ...

    public MyObsoleteAttribute(string message, string replacement, Version removeInVersion) 
        : base(string.Format("{0} Replace with {1}", message, replacement), 
                   CurrentAssemblyVersion >= removeInVersion ? true : false)
    {
    }
    
    public MyObsoleteAttribute(string message, string replacement) 
        : base(message)
    {
    }

    // ...
}
``` 

see also: [Obsolete.Fody: ObsoleteEx should derive from Obsolete](https://github.com/Fody/Obsolete/issues/7)

**Comment by ellismg** [comment]
If we were to do this (and I'm not advocating we should) we should better understand how this works with Roslyn.  For example, is Roslyn set up to understand when an attribute inherits from ObsoleteAttribute?  In the above example, how would Roslyn understand what needs to be done here?  Does it need to actually run the IL for the .ctor of the "MyObsoleteMessage" attribute to figure out if things are an error or not?  That does not seem like it would work very well.

In general, I worry about unsealing attributes that tools consume from metadata.  It seems like doing so opens up a bunch of cases the tools might not consider and things will probably not behave as expected.

**Comment by terrajobst** [comment]
@jaredpar What are your thoughts on this?

**Comment by jaredpar** [comment]
My preference is to remain `sealed` for pretty much the reasons that @ellismg laid out.  Additionally the problem is not limited to Roslyn:

- F# + C++ would need to change. 
- Every non-Microsoft language that supports obsolete would need to change (lots of them). 
- No one is going to update the native compilers and they remain very much in use.  Making this change would let code compile fine for them because they don't flag `MyObselete` but fail when using Roslyn.

**Comment by ellismg** [comment]
Thanks @jaredpar.
