### ISSUE TITLE
Why are there two mscorlib variants?

### ISSUE THREAD

**Issue by ghost** [dotnet/coreclr#3532]
Native: mscorlib.ni.dll
Managed: mscorlib.dll

Assuming they are interchangeable and capable of doing the same things; can't there be just one in CoreCLR (preferably the native one)? Or are there other/historical reasons to keep both variants?

Also noticed that CoreFX build script explicitly deletes the native version: https://github.com/dotnet/corefx/blob/021ced7/run-test.sh#L174-L179.

cc @ellismg, @davidfowl

**Comment by jkotas** [comment]
The CoreCLR nuget package is going to contain just the native one.

Deleting of the native version in corefx was workaround from the days when the managed build was done on Windows and the result copied over to Unix - the script sometimes copied the native image from Windows to Unix that resulted into spectacular crash. This workaround should be no longer needed.

**Comment by jasonwilliams200OK** [comment]
> The CoreCLR nuget package is going to contain just the native one.

This is a great news! :)

1. Does that also mean that some part of document <kbd>**Book of Runtime, Chapter: mscorlib** -
https://github.com/dotnet/coreclr/blob/8d3936b/Documentation/botr/mscorlib.md</kbd> are outdated? such as:

  ```diff
  Introduction
  - Mscorlib is the `assembly` for defining the core parts of the type system
  + Mscorlib is the `library` for defining the core parts of the type system
  ```

  and

  ```diff
  - To reiterate, the needs of managed code in mscorlib include:
  ```

  etc.

2. Would there be any relationship between dotnet CLI and CoreCLR nuget pacakge? Such as; dotnet-cli would download and inflate the CLR nuget package on install-time, followed by the rest of the stuff (instead of maintaining two separate CLR packages)?

3. Would the CLR nuget package include the native dependencies separately for each OS or inspect and report if its dependency is missing on the target machine?
  * For example, on Ubuntu, using native OS package manager (aptitude) resolves the dependency graph on install and informs the user with something like "Installing this package will also install such and such libraries which are missing from your system, do you want to continue" and then installs the package with all the missing dependencies.
    * nuget is also capable of managing the dependency graph; not sure if it can introspect various operating systems for native libs too.
    * Currently on a brand new Ubuntu Server 14 VM, if we install dotnet-cli, it does not install any depndency nor does it gives feedback about the missing deps to the user until we execute corerun; which fails with something like "libunwind is missing".
    * In case dotnet-cli and nuget can't automate the missing dependent libs issue, it would probably the best to release CLR to Linux and BSDs via their respective package managers to exercise the aforementioned advantages and the better know-how of the target system; as opposed to releasing the core runtime via dotnet-cli or nuget.

**Comment by jkotas** [comment]
- `mscorlib` is assembly. Having native code for it does not change this fact.

Our current plan is:
- The full cli package will depend on the coreclr package (we actually call it "shared runtime" because of it will contain more than just coreclr proper)
- Both of these packages will be native platform packages - aptget will automatically install it's dependencies, etc.

**Comment by kasper3** [comment]
I think this issue is resolved since as there is no mscorlib.ni.dll generated in coreclr.
