### ISSUE TITLE
mscorlib.dll is not delay signed

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#3583]
Doing sn -v against one built in the open fails.

As part of fixing this, please also enable signing in the closed build.

**Comment by gkhanna79** [comment]
CC @weshaggard @AlexGhiondea

**Comment by joperezr** [comment]
This is actually expected. `sn -v` is expected to fail because of the way we do strong name signing in the open. Since we don't have access to the private keys, all we do is to delay sign the binaries and flip a header bit saying it's strong name signed even though it's not. Only the build lab can actually fully strong name sign the assemblies. If you run `sn -Tp` instead on the mscorlib assembly produced by the open build, you'll notice how public keys are correctly placed on the assembly as part of the build.

**Comment by joperezr** [comment]
And just to clarify, that means that mscorlib is correctly delay signed, and that `sn -v` failing doesn't mean otherwise, simply that strong name verification is not done since assembly is not fully signed.

**Comment by joperezr** [comment]
This is done and has been verified by @gkhanna79. If anybody wants to produce delay signed mscorlib, simply pass in the param `disableoss` to the build script.
