### ISSUE TITLE
Runtime crash in decimal.ToString

### ISSUE THREAD

**Issue by jaredpar** [dotnet/coreclr#3623]
From a customer reported issue.  The following, contrived, `decimal` instance will cause a runtime crash when invoking the `ToString` method:

``` csharp
var d = default(decimal);
object o = d;
o.
    GetType().
    GetField("flags", BindingFlags.NonPublic | BindingFlags.Instance)
    .SetValue(o, unchecked ((int)0xffffffff));
var s = o.ToString();
```

**Comment by cmckinsey** [comment]
Fails in NumberToString in the VM calling DoJITFailFast()

**Comment by janvorli** [comment]
Let me take a look.

**Comment by janvorli** [comment]
I've discovered that it crashes in desktop CLR as well.

**Comment by janvorli** [comment]
In the CoreCLR, the bug is in the NumberToString or the FormatGeneral function. When the former calls the latter with the bSuppressScientific argument set to TRUE, the latter it doesn't try to limit the number of generated digits in any way and generates as many digits as the number->scale specifies, not taking into the account the nMaxDigits parameter. But the NumberToString reserves a buffer that's based on the nMaxDigits which then overflows.
In our failure case, the number->scale is -255 and the nMaxDigits is 28.
I need to look into it more, I am not sure yet if the FormatGeneral should limit the number of generated digits by the nMaxDigits or if the NumberToString should base the string buffer size on the number->scale.

**Comment by janvorli** [comment]
Looking at the MSDN doc, the allowed values of the number->scale are 0..28, so the bug is that the NumberToString doesn't check it. It is not possible to construct such invalid numer using any of the decimal constructors (attempt to use constructor Decimal(0, 0, 0, false, 255) results in System.ArgumentOutOfRangeException). But when it is set via reflection, there is obviously no check and so the runtime needs to be protected.

**Comment by janvorli** [comment]
Actually, it is not just a problem of formatting. If I replace the `var s = o.ToString();` by e.g. `var d2 = (decimal)o + 1;`, it still crashes, obviously at a different place.
So it seems that we need to add validity check of the scale to all FCalls in the coreclr that have decimal arguments.

**Comment by janvorli** [comment]
So I would add the check below to all such places. I've verified that it fixes the crash with in the sample code at the beginning of this github issue.
```C++
    if (DECIMAL_SCALE(value) > 28)
    {
        COMPlusThrowArgumentOutOfRange(W("value"), W("ArgumentOutOfRange_DecimalScale"));
    }
```
@jkotas do you see any potential pitfalls with that?

**Comment by jkotas** [comment]
Changing private fields using reflection can lead to all sorts of crashes. We are not trying to protect against it.

In this particular case, I think it would make sense to add a check that prevents the buffer overrun - as a defense in depth. I would add it close to where the buffer is written to - check whether the buffer is big enough.

I do not think we should be adding scale checks to all decimal operations. This should is done during decimal construction, and that should be sufficient for all valid uses.

**Comment by janvorli** [comment]
Ok, makes sense.

**Comment by gkhanna79** [comment]
@janvorli Is this something you are still looking into?

**Comment by janvorli** [comment]
It is something that would be nice to do at some point, but since it can only be triggered by putting incorrect data into the decimal object by reflection and the issue has been there for a very long time, it has currently a low priority on my list.

**Comment by pentp** [comment]
This issue is no longer relevant - number formatting was moved to managed code about a year ago. Running it on .NET Core prints [zero point 255 zeroes].

**Comment by janvorli** [comment]
@pentp thank you for pointing it out, I have missed the fact that the native decimal handling code was removed already. Closing this issue.
