### ISSUE TITLE
Switch JIT to generate RBP-chains on Unix

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#366]
Unlike on Windows, RBP-chains seems to be used for fast stack-unwind on Unix (e.g. stack trace logging). JIT needs to be switches to generate them. It should involve:
- Turn on ETW_EBP_FRAMED for Unix
- Tweak the prolog/epilog so that method with RBP frames start with the usual "push rbp; mov rbp, rsp"
- Make sure that nothing breaks

**Comment by jkotas** [comment]
FYI @brianrob

**Comment by LLITCHEV** [comment]
This is merged in master.

**Comment by mjsabby** [comment]
Great! Any reason why we shouldn't switch this for Windows as well?

I've wanted EBP frame walking for continuous profiling scenarios. Not to mention it'd be nice to have the ability to use unix-based profiling tools on Windows and not have to teach them our x64 unwind.

**Comment by jkotas** [comment]
It is trade-off between simplicity of diagnostic tools (frame chains make stackwalking simple) and code quality (frame chain register is another register for compilers to play with if it is not reserved for the frame chain). For better or worse, Windows x64 choose to weight code quality side. 

It does not help to change the defaults in the JIT only. All code has to follow the same convention for frame chains to be really useful.

**Comment by LLITCHEV** [comment]
Jan is right.
In general on Windows the Jit is really aggressive to use as much as possible registers for scheduling locals, temps and parameters. The RBP is scheduled as a frame register only if needs to be. Otherwise it is used as a general purpose register (GPR.) My experiments in the past (on different platforms and runtimes) showed about 4% CQ benefit if RBP is used as a GPR. Experiments has also shown that for important loads in the data centers every percent of CQ translates into real savings.

On Windows the unwinding is a OS-wide feature and the PE format's .pdata and .xdata sections allow for unwinding for any level of optimizations of the compilers. Tools should probably use these records to collected and presented most realistic data for any program, compiled with any switches.

**Comment by mjsabby** [comment]
Oh I understand and agree with the code-quality argument. I'm noting that there are some scenarios that actually benefit from RBP being used -- e.g. a sampling profiler running 24x7 in your datacenter.

@jkotas yup, but I imagine for a lot of scenarios, one would care about coreclr.dll (which one could compile with no fpo) and the managed code frames, I understand that things will fall apart on other compiled code.

In any case, an interested party can follow your change and do it themselves if they so care.

Thanks!
