### ISSUE TITLE
Crossgen failing for Roslyn

### ISSUE THREAD

**Issue by mmitche** [dotnet/coreclr#3918]
This is building roslyn on the standard .NET CI Ubuntu 14.04 image

*** Error in `./crossgen': malloc(): memory corruption: 0x0000000001c0c660 ***
build/scripts/crossgen.sh: line 35:  3191 Aborted                 (core dumped) ./crossgen -nologo -platform_assemblies_paths $BIN_DIR mscorlib.dll
make: *** [bootstrap] Error 134

I have a machine with this live

**Comment by jaredpar** [comment]
CC @gkhanna79

**Comment by gkhanna79** [comment]
The command line seems to imply we are compiling mscorlib and not Roslyn. Can you please share machine details with @JohnChen0 to take a look?

**Comment by JohnChen0** [comment]
Roslyn build is using a very old version of crossgen. https://github.com/dotnet/roslyn/blob/master/build/scripts/crossgen.sh is hardcoded to use version 1.0.1-beta-23504. The crash was caused by a bug that was fixed over four months ago with PR #2046. Any reason why we're using such an old build? Many bugs have been fixed since then.

**Comment by jaredpar** [comment]
CC @agocke 

The build is old because updating CoreClr is a relatively expensive operation.  In the past it's forced us to also update our NuGet dependencies which can have lots of downstream consequences (in particular making it difficult for us to insert bits into VS).  Hence we've tended to update CoreClr on a slower pace than we would like.  

Now that update 2 is behind us we have the bandwidth to absorb a new version.  What is the best version for us to look to use?

**Comment by mmitche** [comment]
@jaredpar Awesome, when you get this updated we'll move over.

**Comment by leecow** [comment]
@jaredpar Please work with @piotrpMSFT to pickup the latest CoreCLR package that CLI is using as well for RC2.

**Comment by piotrpMSFT** [comment]
CLI is on 23924 right now, and we're in the process of taking 23925.

**Comment by mmitche** [comment]
This is fixed now
