### ISSUE TITLE
ARM64: Test FromNativePaths fails when run under Smarty, passes when run standalone

### ISSUE THREAD

**Issue by briansull** [dotnet/coreclr#3968]
Test Id: [FromNativePaths.exe_5811]
Standalone:
%CORERUN% Loader\NativeLibs\FromNativePaths\FromNativePaths.exe
echo %ERRORLEVEL%
prints 100 when run standalone

Under Smarty it prints:
type Smrt00000001\Tests.lst_FromNativePaths.exe__5811.result.1.1.txt
FromNativePaths failed: Failed to move native library to CORE_ROOT: access to the path is denied

**Comment by kyulee1** [comment]
It appears the lab (smarty) doesn't complain this. I can't repro locally either.
Did you set up CORE_ROOT correctly or any permission issue on the path?
As in https://github.com/dotnet/coreclr/pull/4110, I'm re-enabling this.

**Comment by kyulee1** [comment]
Since this doesn't repro in the lab and locally, I'm closing this.

**Comment by briansull** [comment]
The test requires write permission on the %CORE_ROOT% directory.
For me and most devs the %COOR_ROOT% directory will be a network share.
I can make the test pass by changing the permission on my share to grant "Everyone" write permission.
If your share has only read permission the test will fail.

**Comment by briansull** [comment]
I think that it should not try to move a native dll into %CORE_ROOT% as the test will still find the native dll in the test directory.  So moving it to %CORE_ROOT% is unnecessary.

**Comment by kyulee1** [comment]
@briansull I think this is not arm64 specific issue. Like any other jobs, currently we are assuming %CORE_ROOT% is on local disk not in network map as you did.
So, fixing the test is a separte issue. I would recommend to close this issue, but create another one that fixes this test (which unnecessarily copy the binary) based on your description.
Can you also assign it to you or just leave it open? Since you've already known the cause, can you just fix it instead of assiging it back to me?

**Comment by briansull** [comment]
OK
