### ISSUE TITLE
One bug about String.ToLower()

### ISSUE THREAD

**Issue by xiechaoyi** [dotnet/coreclr#4027]
#I want to convert string "GetInstances" to lowercase, use method String.ToLower(),but is return "getınstances",the letter "i" is error,and test to urlencode result is get%C4%B1nstances.

**Comment by stephentoub** [comment]
What OS is this? If it's Linux or OSX, what do you see at the terminal when you use the "locale" command?

And what version of coreclr are you using?

It looks like you're using a Turkish culture.  My guess is you're on Linux or OSX, and you're using a "POSIX" locale due to not having a LANG environment variable set?  If so, this should be fixed by https://github.com/dotnet/coreclr/pull/2548.

**Comment by xiechaoyi** [comment]
OS is docker FROM microsoft/aspnet:1.0.0-rc1-final-coreclr,1.0.0-rc1-update1-coreclr also have this bug

**Comment by stephentoub** [comment]
Thanks, @xiechaoyi. Yes, that's an older build, from before the fix in #2548.

**Comment by xiechaoyi** [comment]
@stephentoub ok,thank you!
