### ISSUE TITLE
RyuJIT bug related to side-effects in exception filter

### ISSUE THREAD

**Issue by cmckinsey** [dotnet/coreclr#4044]
https://github.com/dotnet/roslyn/issues/7030

Reproes only on /o+ on 64bit.

The following code loops infinitely printing “3”

```
using System;

class C
{
    static void Main()
    {
        int i = 3;
        do
        {
            try
            {
                throw new Exception();
            }
            // we should be decrementing i here, it does not happen
            catch (Exception) when (--i < 0)   
            {
                Console.Write("e");
                break;
            }
            catch (Exception)
            {
                // just printing constant 3 here
                //000000b5  mov         ecx,3 
                //000000ba  call        000000005B3CBAF0
                Console.Write(i);
            }
        } while (true);
    }
}

```

**Comment by JosephTremoulet** [comment]
When the filter clause returns false, the exception may then be handled by the second `catch`.  It looks like our liveness calculation ignores that control flow edge; we figure out that `i` is live-in to the second `catch`, but don't propagate that to make it live-out of the filter.  This leads us to mark the use of decremented `i` in the compare in the filter expression as "last-use", which might contribute to our removing the store (?).
SSA construction seems to be missing the same edge, so the use of `i` in the second `catch` gets wired directly to the initial `i = 3` def; hence (I presume) the propagation of the constant `3` to that use.  We should have seen that edge, should have inserted a PHI for `i` at the top of the second `catch`, which in turn should have prompted us to insert a PHI for `i` at the top of the `do`/`while` loop; since we're missing the edge, we have the wrong dominance graph, and also wire the initial use of `i` in the filter directly to the `i = 3` def.
Presumably the fix involves updating `EHSuccessorIter` to visit the enclosing handler when the pred has JumpKind `BBJ_EHFILTERRET`.  Likely with symmetric change to `Compiler::BlockPredsWithEH`, etc.  Will pursue that.

/cc @BruceForstall who can chime in if it sounds like I'm heading in the wrong direction here...

**Comment by JosephTremoulet** [comment]
Actually, since filters run in the first pass, we'd also need edges to *inner* try regions' finally handlers, since those could get run *after* any enclosing filter expression.  For example, with this function:

```C#
        public static void Main()
        {
            int i = 1;
            try {
                Console.WriteLine("one");
                try {
                    Console.WriteLine("two");
                    try {
                        Console.WriteLine("three");
                        throw new Exception();
                    }
                    finally {
                        Print(i);
                    }
                }
                catch when (++i == 10) {
                    Print(i);
                }
            }
            catch { }
        }
```

the correct behavior (which we exhibit w/o optimizations) is to print '2' from the `finally`, but running this with optimizations we print '1'...

**Comment by JosephTremoulet** [comment]
Adding the "start the 2nd pass" edges from `filtret` to inner finallies will could increase the non-exception-path penalty for not cloning finallies.  If we have something like

```
  Start;
  try {
    A;
    try {
      B;
    } finally {
      C;
    }
    D;
  } catch when E {
    F;
  }
```
then (since we also add an edge from Start to E in order to make sure exceptions at the starts of try regions are modeled), we'll pick up a path Start->E->C->D, so A will no longer dominate D.  I still think it's probably the right way to fix this correctness issue, and wouldn't guess that there'd be widespread impact, and we already knew that cloning finallies would be a nice thing to do for situations like these.  Will see what shakes out in asm diffs.

**Comment by BruceForstall** [comment]
It doesn't surprise me that we have bugs in this area, since until recently (with "catch when" added to C#) we haven't had many filters to deal with. It sounds like you're going down the right path.

**Comment by JosephTremoulet** [comment]
It seems the problem is a level deeper; the code that inserts phi sources, computes liveness, and likely other things, looks up the "try region" of the block it's on to determine if it needs to worry about there being multiple exit points from the block (to its handler).  An exception raised from a filter will get discarded and resume the search for a handler for the prior exception, so we need flow edges from those spots to the next-outer try of the try that the filter protects, which might be a try region that does not contain the filter blocks (since e.g. both the filter and the outer handler can be protecting the same try block).  So now I'm auditing uses of hasTryIndex and getTryDsc and such; some really want to get the descriptor that will handle exceptions raised at the given point, but others want the structural view that is what's returned today.

**Comment by JosephTremoulet** [comment]
There are two separable related issues raised here: getting the wrong "next handler" for filter expressions and modeling the flow as 1 pass instead of two.  I've created #4590 for the one-vs-two-pass problem, and will submit a fix separately for the "next handler" problem that caused the bad codegen here.
