### ISSUE TITLE
SIGABRT_System.Globalization.Native.so!UErrorCodeToBool

### ISSUE THREAD

**Issue by schaabs** [dotnet/coreclr#4046]

**Comment by adityamandaleeka** [comment]
The problem here seems to be that the assert isn't valid. `uloc_getLanguage` will return `U_BUFFER_OVERFLOW_ERROR` if the language code is longer than the size of the buffer passed in. 

In this case, "NotAValidCulture" is used as the locale, and the capacity if the buffer is 12. The function can only fit "notavalidcul" in the buffer and sets `err` to `U_BUFFER_OVERFLOW_ERROR`.

**Comment by adityamandaleeka** [comment]
@steveharter Can you take a look at this please?

cc: @ellismg

**Comment by steveharter** [comment]
Sure taking a look now

**Comment by steveharter** [comment]
Still taking a look. I believe the error is coming from here:
    if (U_SUCCESS(*err))
    {
        // Make sure the "language" part of the locale is reasonable (i.e. we can fetch it and it is within range).
        // This mimics how the C++ ICU API determines if a locale is "bogus" or not.

        char language[ULOC_LANG_CAPACITY];
        uloc_getLanguage(localeNameTemp, language, ULOC_LANG_CAPACITY, err);

        if (*err == U_STRING_NOT_TERMINATED_WARNING)
        {
            // ULOC_LANG_CAPACITY includes the null terminator, so if we couldn't extract the language with the null
            // terminator, the language must be invalid.

            *err = U_ILLEGAL_ARGUMENT_ERROR;
        }
    }

Where ULOC_LANG_CAPACITY=12. This code was recently added which does make the assert invalid as buffer overflow can result (in addition to U_STRING_NOT_TERMINATED_WARNING). So we can either add buffer overflow to that check, or remove the assert.

**Comment by steveharter** [comment]
Added fix. Researching why corefx debug tests did not catch this.
