### ISSUE TITLE
Possible unintended reference comparison in ResourceManager

### ISSUE THREAD

**Issue by radischevo** [dotnet/coreclr#4105]
I've been investigating the issue with incorrect resource set returned from `ResourceManager` in certain cases, likely in a multithreaded environment (ASP.NET app is the example). 

Looking at the sources of `ResourceManager` I've noticed, that in the `InternalGetResourceSet` method there are two condition statements where `CultureInfo`s are compared using the equality operator. Since the `CultureInfo` class does not override it, the reference comparison is used. 

Seems that in certain cases two equal `CultureInfo`s may reference two different objects, therefore breaking the loop logic at [line 809 ](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Resources/ResourceManager.cs#L809). In such case, the last obtained resource set may be cached and then returned instead of any parent culture, including invariant one. 

Also, at [line 774](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Resources/ResourceManager.cs#L774), there is another reference comparison, which does not seem to break anything, but yet needs to be revised. 
I suggest using `Equals` method call instead of the equality operator to test cultures for equality in both places.

There is a repro for .NET 4.0 — 4.6 along with the 'hacked' version of `ResourceManager` which seems to fix the issue: https://bitbucket.org/radischevo/resmanrc.

**Comment by gkhanna79** [comment]
@ramarag PTAL for 1.2.0.

**Comment by ramarag** [comment]
The race condition here occurs inside the [CultureInfo.get_Parent](https://github.com/dotnet/coreclr/blob/b638af3a4dd52fa7b1ea1958164136c72096c25c/src/mscorlib/src/System/Globalization/CultureInfo.cs#L909) method called from [ResourceFallbackManager.GetEnumerator](https://github.com/dotnet/coreclr/blob/b638af3a4dd52fa7b1ea1958164136c72096c25c/src/mscorlib/src/System/Resources/ResourceFallbackManager.cs#L80)

This results in the Enumerator providing different CultureInfo objects with the same culture identity on different iterations

ResourceManager uses the CultureInfo object identity in its logic, especially in populating its [resourceset cache](https://github.com/dotnet/coreclr/blob/b638af3a4dd52fa7b1ea1958164136c72096c25c/src/mscorlib/src/System/Resources/ResourceManager.cs#L697)

The scenario where the above mentioned issue occurs is like follows.

The following are the locales used-
ru-Ru   -  [no resource available]
ru         -  [some resource available]
neutral - [ has the key we are interested in say -"K1"]

If a ResourceManager(RM) is created with the locale ru-Ru. And on multiple threads if the RM is used to query the "K1". All the threads race to populate the resourceset cache. 
An unlucky thread could get a culutreinfo object for "ru" in iteration to find which resourcesets are [available](https://github.com/dotnet/coreclr/blob/b638af3a4dd52fa7b1ea1958164136c72096c25c/src/mscorlib/src/System/Resources/ResourceManager.cs#L657). this object will not be linked in the parent hierarchy of "ru-Ru", because a [race](https://github.com/dotnet/coreclr/blob/b638af3a4dd52fa7b1ea1958164136c72096c25c/src/mscorlib/src/System/Globalization/CultureInfo.cs#L909) could add another object in the chain.

When this thread wins the race to populate the resouresetcache,it  will populate the resourceset of "ru" for all the locales in the parent chain of "ru-Ru" because of the caching [logic comparing only object references](https://github.com/dotnet/coreclr/blob/b638af3a4dd52fa7b1ea1958164136c72096c25c/src/mscorlib/src/System/Resources/ResourceManager.cs#L697). So even the neutral locale cache gets populated with resourceset of "ru" instead of its own.

Subsequently when the RM is queried for "K1", it will fail to find the associated resource

**Comment by radischevo** [comment]
@ramarag, thank you providing the fix. I don't feel I could dig that deep :)

**Comment by gkhanna79** [comment]
@ramarag do we need to fix this for Desktop as well?

**Comment by ramarag** [comment]
@gkhanna79 yes we have corresponding connect bug for desktop.
