### ISSUE TITLE
RyuJIT:  JIT, readonly static fields and dynamic dispatch

### ISSUE THREAD

**Issue by omariom** [dotnet/coreclr#4108]
JIT could replace  virtual, interface and delegate dispatch with static one when it knows the target at jit-time. JIT could even inline it when appropriate.

``` C#
private static readonly EqualityComparer<T> eqCmpr = EqualityComparer<T>.Default;
private static readonly IComparer<T> cmpr = CreateComparer();
private static readonly Func<T, T, bool> funcCmpr  = CreateDelegateComparer();

private void HappenedToBeJittedFirst(T x, T y)
{
    eqCmpr.Equals(x, y);
}

private void LuckyOne(T x, T y)
{
    eqCmpr.Equals(x, y);
}

```

category:cq
theme:devirtualization
skill-level:expert
cost:medium

**Comment by GSPP** [comment]
Testing on 4.6.1 I find that this version of RyuJIT does not seem to be capable of tracking the precise receiver type in any way. So

    IInterface x = new Class();
    x.VCall();

results in an actual vcall. I tried all kinds of patterns with calls and casts and none were optimized if the local variable was not typed exactly right.

I'm sure the team is tracking this. What's the roadmap regarding type data flow analysis and optimizing indirect calls and casts based on that?

**Comment by pgavlin** [comment]
cc @cmckinsey

**Comment by omariom** [comment]
@GSPP 
This issue is specifically about case when the receiver is known because the `static readonly` field has already been initialized.

**Comment by GSPP** [comment]
I understand that. The receiver is also known in:

    IInterface x = new Class();
   x.VCall();

The JIT apparently does not have any devirtualization infrastructure at the moment as it seems. I'm kind of hoping that all of this work can be done in one swoop by propagating type information through the data flow. A read of a `static readonly` field would be a flow source as would be a `new T()`.

**Comment by omariom** [comment]
One of the cases where it would help to increase perf is tuples. 
[This one  is from `tuples`](https://github.com/dotnet/roslyn/blob/54b0912b7cb3f5b68dd6d562a1930af53b6d41d0/docs/features/ValueTuples.cs#L144) branch of Roslyn.

**Comment by pgavlin** [comment]
@AndyAyersMS does the devirt implementation cover any of this?

**Comment by AndyAyersMS** [comment]
For the current devirt, the type we'd recover would be the declared type, not the actual type of object the static currently refers to. And currently we only get the declared type in some simple cases, pending #10732, since static access expands into complex sequences at times.

If we know for sure the static cannot be redefined at runtime then we could inspect the value at jit time and if non-null, rely on the type for codegen.  I'd have to review the ECMA rules for when we actually have this guarantee. But even if the value can be redefined we still could consider guarded devirtualization based on the current type, if we think redefinition is unlikely.

**Comment by omariom** [comment]
@AndyAyersMS 

Currently JIT treats `static readonly` fields of  scalar types as jit time constants
