### ISSUE TITLE
RyuJIT x86: NYI: "Casts from TYP_LONG"

### ISSUE THREAD

**Issue by adiaaida** [dotnet/coreclr#4169]
This NYI:

NYI: "Casts from TYP_LONG"
File coreclr\src\jit\codegenxarch.cpp Line:1859

Is hit by these tests:
JIT\Directed\perffix\primitivevt\callconv2_cs_do\callconv2_cs_do.cmd
JIT\Regression\CLR-x86-JIT\V1.2-M01\b14617\b14617\b14617.cmd
JIT\Regression\CLR-x86-JIT\V1-M12-Beta2\b50033\b50033\b50033.cmd
JIT\Regression\CLR-x86-JIT\V1-M11-Beta1\b41621\b41621\b41621.cmd
JIT\Regression\Dev11\dev11_10427\conv_ovf_i4\conv_ovf_i4.cmd
JIT\Regression\CLR-x86-JIT\V1-M09.5-PDC\b31273\b31273\b31273.cmd
JIT\IL_Conformance\Old\Conformance_Base\ldc_conv_ovf_u8_u4\ldc_conv_ovf_u8_u4.cmd
JIT\IL_Conformance\Old\Conformance_Base\Conv_I4\Conv_I4.cmd
JIT\Regression\CLR-x86-JIT\V1-M09.5-PDC\b25835\b25835\b25835.cmd
JIT\Directed\PREFIX\PrimitiveVT\callconv2_cs_ro\callconv2_cs_ro.cmd

**Comment by sejongoh** [comment]
I have a few questions about this:

1. Do we want to implement this in the codegen? It would be desired to handle this in the decomposition pass.
2. Generating instructions for a cast node needs to add control flow to detect overflow. Is it feasible to add new basic blocks and manipulate control flow?
3. If not, what would be a good solution? A simple solution might be to add a new tree node like ovf_check(low_part, high_part), so that we can simply avoid seeing long type after decomposition and codegen lower the tree node to instructions and labels. Another solution might be to transform cast to multiple basic blocks before decomposition.

**Comment by mikedn** [comment]
> Do we want to implement this in the codegen? It would be desired to handle this in the decomposition pass.

IMO all the `TYP_LONG` work should be done in decomposition/lowering. But it's not surprising that some of this work is done in codegen, it is easier because it avoids flow graph manipulation. Also, decomposition was mostly intended to deal with nodes that produce `TYP_LONG` values, not with nodes that consume `TYP_LONG` values.

> Generating instructions for a cast node needs to add control flow to detect overflow. Is it feasible to add new basic blocks and manipulate control flow?

Switch lowering does manipulate control flow so this should be possible in decomposition as well.

> If not, what would be a good solution?

Hmm, what casts is codegen supposed to handle anyway? Some "from `TYP_LONG`" casts are already handled during decomposition (see #4986). What I expect codegen to handle is the case of signed long->int cast as that requires more complex overflow checks.

**Comment by mikedn** [comment]
Hmm, some of the NYI long casts involve floating point. Usually these require helper calls and as such they shouldn't reach codegen. Some of them can be implemented using FPU instructions (assuming the JIT is willing to continue to use FPU in this case) and then they have to be done in codegen.

**Comment by sejongoh** [comment]
As you mentioned, long -> double/float casts are converted to helper calls in morph. My understanding is that we are going to use SSE2. I was curious about the implementation of those helper calls but couldn't find where they are so far.

**Comment by mikedn** [comment]
> I was curious about the implementation of those helper calls but couldn't find where they are so far.

See vm\jithelpers.cpp and vm\i386\jithelp.asm.

**Comment by sejongoh** [comment]
Thanks!

**Comment by sejongoh** [comment]
Thank @BruceForstall, @CarolEidt , and @mikedn for inputs. Based on discussion, implementing this in codegen looks a good approach.

**Comment by mikedn** [comment]
@RussKeldorph You can assign this to me.

**Comment by mikedn** [comment]
Fixed by #7126 and #7133
