### ISSUE TITLE
Fix simplestruct test for non-windows platform.

### ISSUE THREAD

**Issue by tijoytom** [dotnet/coreclr#4193]

**Comment by tijoytom** [comment]
Not a test issue.Closing since managed -> native layout seems to be messed by when LayoutExplicit is mentioned for a struct with union.Combining the investigation with https://github.com/dotnet/coreclr/issues/4193

**Comment by tijoytom** [comment]
Same as https://github.com/dotnet/coreclr/issues/4307

**Comment by tijoytom** [comment]
@yizhang82 We should definitely emit a warning  or even throw an exception for sure.. I spent almost a day trying to debugging this yesterday.

**Comment by yizhang82** [comment]
@tijoytom Thanks for looking into this. Unfortunately I don't think it is right thing to do to emit a warning in compiler nor throw in runtime - as there is no good way to tell whether that matches native side. We should invest in tooling so that this never happen - writing an correct struct that has same layout as native is a very challenging task that we should leave to tool, and not real humans.

**Comment by tijoytom** [comment]
@yizhang82 I fixed the test and disabled the specific scenario for now.
