### ISSUE TITLE
MarshalStructAsLayoutExp test fails non-windows platform

### ISSUE THREAD

**Issue by tijoytom** [dotnet/coreclr#4195]

**Comment by yizhang82** [comment]
This is related to #4307 and is test issue. However we should see whether we can fix the product at some point - but it's too risky at this point.

**Comment by yizhang82** [comment]
It's unlikely that we'll address this for 2.0.0.

**Comment by jkoritzinsky** [comment]
We do not support interop of explicit layout structs passed by value on x64 Unix.

@janvorli is there plans to support this? Do you know/remember the reason why this was initially omitted?

**Comment by janvorli** [comment]
@jkoritzinsky there was no plan yet to support those. Supporting them would require making the struct classification algorithm more complex. The SystemV Amd64 ABI says that a structure cannot be passed in registers and it has to be passed in memory (on stack) if it is a non-POD structure, a union or if it contains unaligned fields. So we would need to analyze the explicit layout to check if fields overlap or are unaligned and it seems we would also need to generate "sequentialized" view of the layout so that it can be run through the classification algorithm to find out how to pass the struct since the algorithm processes the members in a sequential order. This would need to be done in both the JIT and the runtime (e.g. for passing parameters during reflection).

**Comment by jkoritzinsky** [comment]
Thanks for the insight!

**Comment by jkoritzinsky** [comment]
cc: @luqunl
