### ISSUE TITLE
[Discussion]Performance of clr

### ISSUE THREAD

**Issue by zgxnet** [dotnet/coreclr#422]
It seems that CLR is very slow for some simple scenarios, more than 10x slower than its C++ counterpart. Using disassembly I found that there are some important cases where CLR is not optimized.
The following are my test cases (both in x64 release mode): 
C#:
``` C#
class Program
{
	static long counter = 0;
	static void Main(string[] args)
	{
		for (int m = 0; m < 100; m++)
		{
			Stopwatch s = new Stopwatch();
			s.Start();
			for (long i = 0; i < 200000000; i++)
			{
				counter = counter * 2 + 3;
			}
			s.Stop();
			Console.WriteLine(s.Elapsed.TotalMilliseconds + " ms");
		}
	}
}
```
C++:
``` C++
#include <iostream>
#include <windows.h>
using namespace std;
static __int64 counter = 0;
void main()
{
	for (int m = 0; m < 100; m++)
	{
		DWORD start = ::GetTickCount();
		for (__int64 i = 0; i < 200000000; i++)
		{
			counter = counter * 2 + 3;
		}
		cout << ::GetTickCount()-start << " ms" << endl;
	}
}
```
For C# code, each inner loop takes more than 400ms. While for C++, each inner loop takes less than 40ms.

I dig into the assembly code, and found that CLR jitted code is far less efficient than C++’s.
The inner loop body for CLR:
``` assembly
mov         rax,qword ptr [7FF84FB63628h]  
add         rax,rax  
add         rax,3  
mov         qword ptr [7FF84FB63628h],rax  
inc         rcx  
cmp         rcx,0BEBC200h  
jl          00007FF84FC80110  
```

The inner loop body for C++:
``` assembly
lea         rcx,[rcx*4+9]  
dec         rdx  
jne         main+30h (07FF7AD7C12A0h)  
```
A huge difference, isn’t it?
At least there are two optimization areas CLR forgot:
1.	For static / class field, the CLR does not use registers to cache variables. I tried to change counter to local variable, and saw that CLR used a similar strategy as C++.
2.	For simple loops, the CLR uses one more comparison.

I heard that CLR can be as efficient as C++, but this really make me disappointed. Any plans to improve it?

**Comment by ala53** [comment]
In the C++ body, something seems very wrong. There's a conditional jump without ever evaluating for the condition. It should be 
```
```

**Comment by zgxnet** [comment]
@ala53 It is not wrong. dec does the job. And you can try it yourself.

**Comment by ala53** [comment]
@zgxnet Maybe I am wrong - I know only enough assembler to understand the basics.

Here's the `counter = counter * 2 + 3` line
```
00007FFCCA2D48E2  mov         rax,qword ptr [00007FFCCA313F88h]  
00007FFCCA2D48EC  mov         edx,2  
00007FFCCA2D48F1  movsxd      rdx,edx  
00007FFCCA2D48F4  imul        rax,rdx  
00007FFCCA2D48F8  mov         edx,3  
00007FFCCA2D48FD  movsxd      rdx,edx  
00007FFCCA2D4900  add         rax,rdx  
00007FFCCA2D4903  mov         qword ptr [00007FFCCA313F88h],rax  
````

In the inner loop in human readable terms:

 - Load the [long] value from memory into rax
 - Load the [integer] "2" into edx
 - Convert [integer] edx's value into a [long] and put it into rdx
 - Multiply our rax by rdx
 - Load the [integer] "3" into edx
 - Convert [integer] edx's value into a [long] and put it into rdx
 - Add rdx to rax
 - Store the new value from rax back into memory

Herein lies (an) issue: note that we are doing two unnecessary 32-64 conversions, which could be done in place. A better optimized assembly code would be (assuming we have to load the register each time for safety):

```
mov rdx,[memory location]
imul rdx, 2
add rdx,3
mov [memory location],rdx
```

The key issue is that the CLR is leaving the integers as integers during compilation (even when they don't need to be) and then doing on-chip conversions each iteration.

**Comment by ala53** [comment]
At the beginning of each iteration (the `` line):

```

00007FFCCA2F48D6  xor         ecx,ecx  
00007FFCCA2F48D8  movsxd      rcx,ecx  
00007FFCCA2F48DB  mov         qword ptr [rbp-20h],rcx  
00007FFCCA2F48DF  nop  
00007FFCCA2F48E0  jmp         00007FFCCA2F4920  
```

 - We zero out ecx (why is that needed?)
 - then zero out rcx in an unoptimized way (xoring causes the cpu to change to a virtual register, negating the overhead of actually *zeroing* the register. See (here)[http://stackoverflow.com/questions/16419960/x86-comparison-instruction-that-uses-xor-instead-of-subtraction])
 - We then zero out some memory location (unknown)
 - And call the loop code via a jump

**Comment by zgxnet** [comment]
@ala53 You can just use the release mode, in which you will not see the unnecessary instructions.

**Comment by ala53** [comment]
Then at the end of each iteration, we need to do bookkeeping:

```
00007FFCCA2F490D  mov         rax,qword ptr [rbp-20h]  
00007FFCCA2F4911  mov         edx,1  
00007FFCCA2F4916  movsxd      rdx,edx  
00007FFCCA2F4919  add         rax,rdx  
00007FFCCA2F491C  mov         qword ptr [rbp-20h],rax  
00007FFCCA2F4920  mov         rcx,qword ptr [rbp-20h]  
00007FFCCA2F4924  mov         eax,0BEBC200h  
00007FFCCA2F4929  movsxd      rax,eax  
00007FFCCA2F492C  cmp         rcx,rax  
00007FFCCA2F492F  jl          00007FFCCA2F48E2  
```
- We load the counter from memory (despite the fact that we can *guarantee* that it will not be touched from outside the loop)
- Load the [integer] "1" into edx
- Convert the [integer] edx into a [long] in rdx
- Add one to rcx (our counter variable)
- Store rcx back into memory
- Load the 200,000,000 as an [integer] into eax
- Convert eax's [integer] into a [long] 
- Compare the 200,000,000 to our counter
- And jump

That entire thing could be replaced by:
```
inc rcx
cmp rcx, 200000000
jl <pointer>
```

It seems the CLR is overusing conversions.

(Sorry about 3 posts, but it seemed like dividing would make for easier reading)

**Comment by ala53** [comment]
@zgxnet That was release mode. http://i.imgur.com/ouqcjac.png 

I have no idea why we are getting different code but this was .Net 4.5.3 and not the CoreCLR - my performace woes might be a bug that has been fixed already but the optimization is still broken somewhere.

**Comment by zgxnet** [comment]
@ala53 You should start the exe outside vs, and then attach to it.

**Comment by ala53** [comment]
@zgxnet Strange. I still get the same jitted code even when I launch outside of VS and attach (in release mode, of course).

**Comment by zgxnet** [comment]
@ala53 CoreCLR uses ryujit, which does not have much performance diferrence. Anyhow, CLR seems poor in code generation, worse than jvm in many cases.

**Comment by MattWhilden** [comment]
Adding some folks from our codegen team. Either to redirect or comment themselves. @BruceForstall @CarolEidt

**Comment by mikedn** [comment]
@ala53 The assembly code that you have posted is surely generated with optimizations disabled. I'm not sure how you ended up with it in a Release build that's run outside VS but I've never seen that kind of code in an optimized build. Make sure to uncheck "suppress JIT optimization on module load" in VS debugger general options, even if you run outside the debugger you can still get unoptimized code if you somehow managed to attach the debugger before the method is JIT compiled.

@zgxnet The CLR JIT is very conservative when it comes to eliminating field load/stores. I suppose it would be nice to improve this but doing that may break poorly written code where fields are observed by another thread without using locks, volatile, memory barrier etc. For better or worse, most performance conscious .NET devs know this and they won't use this kind of code when performance is a concern.

> I heard that CLR can be as efficient as C++, but this really make me disappointed. Any plans to improve it?

Eh, let's be realistic. A JIT compiler is not a C++ compiler, it doesn't have a lot of time at its disposal nor it can look at the entire code the same way the C++ compiler can. 

Anyway, while there's certainly room for improvement in my experience the JIT compiler does a reasonable job, especially if you give it a helping hand from time to time.

**Comment by zgxnet** [comment]
@mikedn I think such conservation is really harmful, losing more than its gain. We should not take care of such poor written code at the cost of performance, which is crucial for a language's success. In my experience, even java does a better job in field load/store. And this makes java faster in many cases.
Field access is so frequent such that we cannot move it to a local variable before use.

**Comment by mikedn** [comment]
> I think such conservation is really harmful, losing more than its gain. We should not take care of such poor written code at the cost of performance, which is crucial for a language's success.

Yeah, I'm not very happy with this either. And not only due to performance but also because this increases the chances that poorly written code works "by accident" rather than "by design", at least on x86/x64. The fact that the memory model of CLR isn't well documented and the JIT compiler appears to be event stricter than the thinly documented memory model doesn't help either.

> The current case is that CLR assumes every field is volatile, isn't it?

Not really, loads from instance fields can be eliminated. For example, if you add something like `+ x` to the expression you have in the loop body and x is an instance field you'll likely find that the load of x has been hoisted outside of the loop.

**Comment by brianrob** [comment]
@zgxnet, looking at the generated code in your original post, it actually looks like the main difference I see is due to optimization.  The C++ generated code doesn't actually touch the counter variable, and simply loops, while the C# code does actually modify the counter.  The C++ compiler has optimized this away because the variable counter doesn't actually get used other than inside the loop, and only as an lval for assignment.  I'm not sure why the JIT doesn't optimize this away, but it does make me wonder if this is an issue worth pursuing.

My suspicion is that the comparisons would certainly get closer if you actually used the counter, even just to print it at the end of the benchmark.  If you did see a significant difference in this case, it would certainly be of interest.  The microbenchmark here is akin to spinning, as the work is essentially throw-away, and the C++ compiler has noticed this, and will just spin for less time.

For what it's worth...

**Comment by ala53** [comment]
@mikedn Hmm. I think I see my problem. I moved the loop into its own routine so I could hook before it started. Unfortunately, the debugger disabled optimization here and then compiled the loop method. Good to know for the future - I didn't know VS disabled optimization the second it begins to observe.

Now, I get this, but there's still room for optimization
```
            for (long i = 0; i < 200000000; i++)
00007FFCCA2E493E  xor         ecx,ecx  
            {
                counter = counter * 2 + 3;
00007FFCCA2E4940  mov         rax,qword ptr [00007FFCCA323F88h]  
00007FFCCA2E494A  shl         rax,1  
00007FFCCA2E494D  add         rax,3  
00007FFCCA2E4951  mov         qword ptr [00007FFCCA323F88h],rax  
            for (long i = 0; i < 200000000; i++)
00007FFCCA2E495B  inc         rcx  
00007FFCCA2E495E  cmp         rcx,0BEBC200h  
00007FFCCA2E4965  jl          00007FFCCA2E4940  
            }
```
What's really weird is that we're xoring ecx even though it is not used in the loop at all (1 instruction doesn't matter but it seems like a bug). 
Also, it's interesting to note that CoreCLR optimized the method differently than 4.5.3. Here, we do a bit shift (`shl rax,1`) while CoreCLR uses an add (`add rax, rax`). Anyone know which one is faster?

**Comment by ala53** [comment]
Also, I'm probably driving someone on the code gen team insane by nitpicking their choice of x86 instructions without having a PhD. in the field. 
_Sorry about that :/_

**Comment by CarolEidt** [comment]
I am seeing slightly different code generation here than @ala53 posted above, though not significantly (and I am working with a slightly different version).  In any case, register ecx is actually the same register as rcx, though the xor should specify rcx to zero the full 64 bits.  In my version the xor is specifying the 64-bit register (rcx).
Regarding the loads and stores, the defacto CLR memory model doesn't allow for optimizing away reads and writes to non-local objects.
That being said, we know that there's still plenty of opportunity to improve the code generated by the JIT.

**Comment by ala53** [comment]
@CarolEidt I think it might just be a bug in 4.5.3's code gen.

```
for (long i = 0; i < 20,000,000,000; i++)
00007FFCCA2E4962  xor         ecx,ecx  
```

Even when it is set to 20 billion, the xor only deals with low 32 bits and the outer loop also doesn't reset the counter.

**Comment by CarolEidt** [comment]
My colleague, @BruceForstall informs me that this is expected behavior - writing a 32-bit register zeros the upper bits, and the 32-bit version is one byte shorter.

**Comment by ala53** [comment]
@CarolEidt Correct me if I'm wrong, but in a situation like the below, wouldn't a 64 bit xor be needed? Zeroing out the upper bits won't reset it to zero in this case (I think).
```
                for (long i = 0; i < 3000000702L; i++)
00007FFCCA2E4962  xor         ecx,ecx  
```

**Comment by CarolEidt** [comment]
@ala53 Xor-ing a value with itself yields zero.  The side-effect of clearing the upper bits is what gives you the full 64-bit zero.

**Comment by ala53** [comment]
@CarolEidt I know. What I'm talking about is this:

Lets say the value in a register is `0xFFFFFFFFFFFFFFFF`. If you xor the upper bits `0xFFFFFFFFFFFFFFFF | 0xFFFFFFFF00000000`, you would get `0x00000000FFFFFFFF` (unsigned 4,294,967,296), not 0. Is the xor doing something behind the scenes to zero out the other half?

**Comment by mikedn** [comment]
> Is the xor doing something behind the scenes to zero out the other half?

Yes but that's not specific to xor. This is described in the Intel arch manual:

> 32-bit operands generate a 32-bit result, **zero-extended to a 64-bit result** in the destination general-purpose register

**Comment by CarolEidt** [comment]
@ala53 - the lower bits are zero'd because xoring a register with itself produces zero.  Your example is two different values.

**Comment by zgxnet** [comment]
I really wonder why there is such a bad defacto memory model that field load/write cannot be optimized. There are so many cases that we read/write from object fields, and in some cases we have to do this. This means C# can never be as fast as C++. Another case is C++/clr. When we choose supporting clr in C++ projects, the behavior changes, and the performance degenerates significantly.

Do you have a test on java? JVM does not have such a limitation, and in many cases it is much faster than CLR. I know java is a very conservative, and it does a lot to adapt poor code. Even so it does not choose such an unreasonable strategy. In contrast, C# does a lot to improve the performance, e.g. unsafe. But in my opinion, the field load/write optimization problem ruins all the effects.

In my opinion, C# can be a language better than C++. If such a defacto standard lasts, I have to turn to C++ as my work sometimes needs scientific calculation. In fact, there are many posts on the web (e.g. stackoverflow) complaining that C# is sometimes much slower than java. If C# wants to replace java, such a poor memory model have to change, or it will always be in the current awkward situation – only used in limited areas and lack excellent programmers.

Finally, I just wonder why there is such a memory model and what is the meaning of it? Just take care of poorly written code?

**Comment by ala53** [comment]
>I know java is a very conservative, and it does a lot to adapt poor code. Even so it does not choose such an unreasonable strategy.

@zgxnet Actually, the (Oracle) JVM is anything but conservative. The reason the JVM is a faster in that specific use case is because it makes speculative optimizations. It does guesswork based on heuristics to optimize away things such as loads and stores but if a prediction doesn't pan out, it has to spend a lot of time doing optimization bailouts. It's a lot like javascript compilers in that way.

A good test on that would be doing a function that accepts an object as the value and squares it. First try passing a million integers and then a million doubles. On the JVM, it will probably be a lot faster as the tracing JIT can use heuristics while the CLR only compiles once in a safe way. Then try passing 1 int then 1 double then 1 int, etc. Then, the CLR will undoubtedly win; the JVM will be unable to optimize the code well (no better than the CLR) and might even fall back to interpreting it while the CLR can use a full-unoptimized code gen and avoid the overhead of the monitor phase (collecting type information) and the deoptimization bailouts.

If you try a multithreaded comparison, where you're running four of those tests on the same counter, you'll see a problem right away. I'd venture a guess that the CLR would be a bit faster as it already has the optimal code for that case while the JVM would likely go through a few passes of deoptimization.

The JVM will probably work faster in single threaded scientific calculations (but not as fast as C++) but the CLR will rip it to pieces with any sort of struct or generic based workload (neither of those actually exist in Java - the compiler removes the type information for generics ("type erasure") and structs don't exist at all in Java). C++ gives you better memory management and performance but you have to deal with pointer hell and 40 years of backwards compatibility. Every language/framework/architecture/system will not be perfect (that's why the CLR lets you interact with C++ libraries) and you have to choose the right tool for the job.
 
 - Doing heavy scientific calculations? Use C++.
 - Need to pass around a lot of data without dealing with free() calls? Use the CLR.
 - Working with non-typesafe code? Use the JVM.
 - Need quick prototyping? Ruby or Python.
 - etc. 

Sure, the memory model could be improved, but would causing the CLR team to spend months changing codegen be worth it when you could literally do this:

```
static void Main() {
long _counter = counter;
//calculation using _counter instead of counter
counter = _counter;
}
```
That'll (probably) give the same optimized code as the JVM and C++. 

By the way: I haven't used C++/CLR, but from what I understand (unless you require pure IL generation via some flag), it only turns functions that use CLR types into IL and the rest is native.

**Comment by zgxnet** [comment]
@ala53 The key problem is not just static members, but every field. For general optimization, you do not have to consider multithreading. If you do want to consider it, please add volatile. In fact, why C++ can do it but C# cannot? And JVM does not rely on heuristic to optimize field access, it just uses similar way as C++.

**Comment by ala53** [comment]
@zgxnet My apologies, I'm not really a java developer. I didn't know that Java had `volatile` and just assumed it makes speculative optimizations when it _thinks_ that the field is safe enough.

> In fact, why C++ can do it but C# cannot?

C# does have `volatile` but I have no idea what it is used for. Also, there's now 14? years of backwards compatibility to deal with and the changing the CLR would break a few of them. Sure, it wouldn't be many but it would still call a problem.

> For general optimization, you do not have to consider multithreading.

Given that processors are getting ever more multithreaded and that C# is supposed to "just work", considering multithreading might not be that bad. I actually never thought about volatiles when programming and have written multithreaded programs. In that sense, C# saved me from my own stupidity but at a performance cost.

**Comment by mikedn** [comment]
> The key problem is not just static members, but every field.

This "every field" makes me think you're overstating a bit the importance the memory model here. It's not like if you change the memory model all C# code will get 10x performance. There's a lot of code that will see much smaller performance improvements, if any. There are a lot of conditions that need to be fulfilled by the code to see such large perf improvments:
* The code must be inside a loop. If it's in a method that's called from a loop and the method isn't inlined then you cannot eliminate the load/stores anyway.
* The loop body must be small/simple enough that enough registers are available. If you run out of CPU registers some load/stores will still have to be done anyway.
* The computation that's done inside the loop needs to be fast enough for the cost of load/stores to be significant. Try adding a division to your loop for example, the 10x difference will drop to less than 2x.
* There should be no calls to other methods between load/stores. No matter what the memory model is the JIT compiler has to assume the worst, that other methods load/store the same field and in this case the load/stores in the caller cannot be eliminated. Occasionally this kind of thing can burn you even in C++.

Yes, there are real world examples of code that look just like yours. Like this [Crc32Calculator](http://referencesource.microsoft.com/#WindowsBase/Base/MS/Internal/IO/Zip/Crc32.cs,79) used by System.IO.Packaging ZIP compression. But not all code is like that.

**Comment by mikedn** [comment]
> C# does have  volatile  but I have no idea what it is used for.

Well, it's used to force load/stores to occur and do so in a particular order. As I mentioned before, CLR's memory model doesn't actually treat all field access as volatile.

> Given that processors are getting ever more multithreaded and that C# is supposed to "just work", considering multithreading might not be that bad.

It "just works" until it doesn't, the loop in the following code will never terminate despite the strong memory model of CLR:

```C#
using System.Threading;

class Program {
    bool done;

    void Run() {
        var ready = new ManualResetEvent(false);

        var t1 = new Thread(() => {
            ready.Set();
            while (!done) { }
        });

        var t2 = new Thread(() => {
            ready.WaitOne();
            done = true;
        });

        t1.Start();
        t2.Start();
    }

    static void Main() {
        new Program().Run();
    }
}
```
Granted, it's unlikely to see such an empty loop in real world code and the optimization that's responsible for this "problem" may or may not not kick in if the loop actually does something. Anyway, volatile is required in such a case.

**Comment by zpodlovics** [comment]
On the counter example after moving the global counter variable to a local variable (just before the Stopwatch s = new Stopwatch(); line) Mono (3.12 x86_64) LLVM AOT was able to eliminated not just the inner loop body, but the whole inner loop. The inner loop usually executed after warmup in ~0.0001 ms.

On the multi-threaded example the done variable will be cached in CPU register, changing it from one thread will not be visible from an another thread. You need to force the CPU to read/write from/to memory location instead of a register. But that's only the visibility part. The ordering and atomicity could be also difficult especially when the CPU could reorder instructions.

Volatile fields and read/write are defined in ECMA-335:

I.8.6.1.2 Location signatures
[..]
"Instead, CIL includes a volatile. prefix to certain instructions to specify that the value neither be cached nor computed using an existing cache."

I.12.6.7 Volatile reads and writes
"The volatile. prefix on certain instructions shall guarantee cross-thread memory ordering rules.
They do not provide atomicity, other than that guaranteed by the specification of §I.12.6.6."

Is there any strict (formal) definition exists and available for CLR semantics and for the CLR memory model?

Semantics example (the memory model not yet integrated):
https://github.com/kframework/jvm-semantics
http://fsl.cs.illinois.edu/index.php/K-Java:_A_Complete_Semantics_of_Java

Memory model and barrier elimination example:   
http://gee.cs.oswego.edu/dl/jmm/cookbook.html
http://shipilev.net/blog/2014/jmm-pragmatics/
http://www.cl.cam.ac.uk/~pes20/weakmemory/index.html

**Comment by CarolEidt** [comment]
As far as I know there is no formal definition for the CLR memory model, though this blog post from some years ago describes the de facto model pretty accurately, I believe: http://joeduffyblog.com/2007/11/10/clr-20-memory-model/. A couple of additional points:

First, the JIT is somewhat more conservative than Joe describes in his post.  That is, I don't think it will eliminate stores to "non-local" fields even if they are "adjacent" (i.e. not separated by any calls or aliased references that could be accessing them).  By "non-local" I mean any location that may be visible to other threads.

Second, the JIT is also somewhat limited in its optimizations, which means that even the load will not be eliminated because it would require a loop transformation to enregister the counter prior to the loop.

**Comment by cmckinsey** [comment]
One additional point that hasn't been touched on, the C++ compiler above also unrolled the loop and folded the math leaving half as many iterations as the C# version which makes a big difference.

The C# RyuJIT misses applying these optimizations:

- unroll counted loops (this is the truly big win in this case)
- down-count loops (not always a win, but in this case saves one cycle per iteration)
- form an LEA from an SHL/ADD. However, this only saves code sizes as lea with scale is 2 clocks last I checked. In combination with the loop unroll you actually cut the number of operations in half over the life of the loop.
- perform scalar-replacement (sometimes called load-motion) on heap references. (This is probably the most substantial loss for this loop)
- perform store-motion on heap references (In my experience this never leads to performance wins except in the rare case that the pipeline has a full store buffer)

The CLR memory model is an area that is difficult to discuss without talking about a lot of implementation details. I would describe the rules "roughly" as heap stores always have release semantics and heap loads are free to be cached (i.e. reuse redundant references) but not refetched and do not have acquire ordering semantics by default. Just saying volatile/non-volatile does not succinctly cover the rules for loads.

So anyway we already today perform scalar-replacement of heap loads, we just do not handle the loop carried cases. Take for example if I hand unroll the above C# loop, that gives this out of the JIT:

00007ffb`25bf0d0a 48a1f848ae25fb7f0000 mov rax,qword ptr [00007FFB25AE48F8h]
00007ffb`25bf0d14 488d044503000000 lea     rax,[rax*2+3]
00007ffb`25bf0d1c 48a3f848ae25fb7f0000 mov qword ptr [00007FFB25AE48F8h],rax
00007ffb`25bf0d26 48d1e0          shl     rax,1
00007ffb`25bf0d29 4883c003        add     rax,3
00007ffb`25bf0d2d 48a3f848ae25fb7f0000 mov qword ptr [00007FFB25AE48F8h],rax
00007ffb`25bf0d37 48ffc1          inc     rcx
00007ffb`25bf0d3a 4881f900c2eb0b  cmp     rcx,0BEBC200h

You can see that the load of the static field has been reused. So the JIT is not treating heap loads as fundamentally volatile today.

I don't see any reason why the C# version of this loop could not match C++ performance. I'm not making a more general statement about performance capabilities between the languages however. That's beyond this discussion.

Here is a slightly more optimized .cs version of the program:

using System;
using System.Diagnostics;

class Program
{
    static long counter = 0;
    static void Main(string[] args)
    {
        for (int m = 0; m < 100; m++)
        {
            Stopwatch s = new Stopwatch();
            s.Start();
            long temp = counter;
            for (long i = 0; i < 100000000; i++)
            {
                temp = temp * 2 + 3;
                temp = temp * 2 + 3;
                counter = temp;
            }
            s.Stop();
            Console.WriteLine(s.Elapsed.TotalMilliseconds + " ms");
        }
    }
}

For which RyuJIT generates:

00007ffb`25be0d11 488d0c4d03000000 lea     rcx,[rcx*2+3]
00007ffb`25be0d19 488d0c4d03000000 lea     rcx,[rcx*2+3]
00007ffb`25be0d21 48890dd03befff  mov     qword ptr [00007ffb`25ad48f8],rcx
00007ffb`25be0d28 48ffc0          inc     rax
00007ffb`25be0d2b 483d00e1f505    cmp     rax,5F5E100h
00007ffb`25be0d31 7cde            jl      image00000000_00be0000!Program.Main

Further improvements are of course possible. But for the C++ version I get around 78 ms, for the optimized C# version I get 76 ms on my machine. Close enough.

So overtime I expect the JIT will approach this level of performance as we develop further improvements in the optimizer. Whether the compile-time is available to perform all of these optimizations remains to be seen. I expect most of these are local and linearized transformation which means they're doable in a JIT. But we'll make sure we use data when we make these trade-offs.

Thanks zgxnet for reporting this. These are the kinds of things we'll be looking at investing in the future.

**Comment by mikedn** [comment]
> One additional point that hasn't been touched on, the C++ compiler above also unrolled the loop

Hmm, right, that gives almost 2x perf improvement. Turns out that VC++ is quite conservative with unrolling because this specific loop can be unrolled more than 2 times without any increase in code size. The C++ version takes around 30ms on my machine and the following C# version takes only 12ms:

```C#
long counter = 0;

for (long i = 0; i < 200000000 / 10; i++)
    counter = (counter << 10) + 3069;
```
