### ISSUE TITLE
No drawing/imaging/windowing subsystems?

### ISSUE THREAD

**Issue by SuperJMN** [dotnet/coreclr#4358]
I think this scenario isn't covered by the framework.

It would be really good if there was a to create windows and draw on them. This could enable people to create cross-platform presentation frameworks, more easily. For example, it could make Perspex (https://github.com/Perspex/Perspex) be available in every platform with minimal changes.

**Comment by myungjoo** [comment]
I guess it is not related with CoreCLR (the runtime), but with the library (such as Xamarin Forms or CoreFX although CoreFX generally doesn't cover UI/UX.).

**Comment by mellinoe** [comment]
Yes, this is probably a better fit for dotnet/corefx as it's library-related rather than runtime-related.

Depending on what level of control you want, there are already some options for you. For example, you can already use [OpenTK](https://github.com/opentk/opentk) and [SharpDX](https://github.com/sharpdx/SharpDX) on CoreCLR if you'd like. OpenTK has some windowing functionality built-in as well.

These are not exactly "drawing/imaging" libraries, but then again I'm not sure exactly what you're looking for exactly. I suspect that Perspex could already be implemented on .NET Core, but they are probably waiting for more stability before committing. That assumption is based on the fact that they seem to carry their own XAML implementation, etc and seem fairly standalone in terms of dependencies. There are already some UI implementations that are runnable on .NET Core in various states of usability, so the pieces we have certainly make it possible already.

**Comment by adityamandaleeka** [comment]
Closing this issue since, as mentioned above, it's not really runtime-related.
