### ISSUE TITLE
RyuJIT fails to eliminate "isinst" introduced null checks that are redundant

### ISSUE THREAD

**Issue by mikedn** [dotnet/coreclr#450]
IL's `isinst` instruction generates an implicit null check that isn't eliminated like explicit null checks are.

This is specific to type checks involving sealed types. For non sealed types a helper function is used and it's debatable if it's worth doing something about the null check that the helper function performs.

```C#
sealed class Program {
    int value;
    static int Main() {
        var a = new object[100];
        var c = 0;
        for (int i = 0; i < a.Length; i++) {
            var o = a[i];
            if (o == null) {
                c++;
            }
            else {
                var p = o as Program;
                if (p != null) {
                    c += p.value;
                }
            }
        }
        return c;
    }
}
```
Loop code:
```
00007FF8789504A5 4C 63 C9             movsxd      r9,ecx  
00007FF8789504A8 4E 8B 4C C8 10       mov         r9,qword ptr [rax+r9*8+10h]  
00007FF8789504AD 4D 85 C9             test        r9,r9  
00007FF8789504B0 75 04                jne         00007FF8789504B6  
00007FF8789504B2 FF C2                inc         edx  
00007FF8789504B4 EB 23                jmp         00007FF8789504D9  

; this null check is redundant, r9 was already checked at 00007FF8789504AD
00007FF8789504B6 4D 85 C9             test        r9,r9  
00007FF8789504B9 74 12                je          00007FF8789504CD  
00007FF8789504BB 49 BA B8 45 75 78 F8 7F 00 00 mov         r10,7FF8787545B8h  
00007FF8789504C5 4D 39 11             cmp         qword ptr [r9],r10  
00007FF8789504C8 74 03                je          00007FF8789504CD  
00007FF8789504CA 45 33 C9             xor         r9d,r9d  
00007FF8789504CD 4D 85 C9             test        r9,r9  
00007FF8789504D0 74 07                je          00007FF8789504D9  
00007FF8789504D2 45 8B 49 08          mov         r9d,dword ptr [r9+8]  
00007FF8789504D6 41 03 D1             add         edx,r9d  
00007FF8789504D9 FF C1                inc         ecx  
00007FF8789504DB 44 3B C1             cmp         r8d,ecx  
00007FF8789504DE 7F C5                jg          00007FF8789504A5  
```

**Comment by zgxnet** [comment]
CLR seems not optimized in many ways. I also wish the CLR team can pay attentions to the optimization. I know that JIT has some time limit preventing complex optimization. How about open sourcing .net native?

**Comment by cmckinsey** [comment]
@mikedn Thanks for the test case. RyuJIT has an assertion propagation phase to eliminate null-checks. In the case when an isinst can be inlined to an equality comparison of the objects vtable with its runtime type handle (this is done in importer.cpp), it is internally represented as a QMARK (think ?: operator in C). The QMARK operator holds the null-comparison as well as the type-test comparison. Just a guess here but that code shape difference is probably not handled in the normal assert propagation algorithm that targets explicit flow/branches. Feel free to dig further if you want, we'll also keep this on our backlog for the future.

There is also further optimization opportunity available in this test case, if you look at the test at address ending in $04CD you will see that branch also can be statically eliminated because both predecessors have provably known 0,!0 values for r9. RyuJIT does not yet have this optimization.

@zgxnet Eliminating the redundant null-check on the type-test should be something doable in an ahead of time JIT compiler. This is likely just a kink in the implementation. Thanks.

Btw, in case either of you are interested in getting deeper into the JIT, you can take a look at the assembly output of the JIT without having to drop into the debugger and its a bit easier to read.

set COMPLUS_JitDisasm = [[NameSpace.]ClassName::]MethodName]

So for the above set COMPLUS_JitDisasm=Main

shows

; Assembly listing for method Program:Main():int
; Emitting BLENDED_CODE for X64 CPU with SSE2
; optimized code
; rsp based frame
; fully interruptible
; Final local variable assignments
;
;  V00 loc0         [V00,T04] (  3,   6  )     ref  ->  rax
;  V01 loc1         [V01,T02] (  6,  10  )     int  ->  rdx
;  V02 loc2         [V02,T00] (  5,  17  )     int  ->  rcx
;  V03 loc3         [V03,T03] (  3,  10  )     ref  ->   r9
;  V04 loc4         [V04,T05] (  3,   6  )     ref  ->   r9
;  V05 tmp0         [V05,T01] (  5,  14.9)     ref  ->   r9
;  V06 OutArgs      [V06    ] (  1,   1  )  lclBlk (32) [rsp+0x00]
;  V07 cse0         [V07,T06] (  3,   6  )     int  ->   r8
;
; Lcl frame size = 40

G_M45811_IG01:
       4883EC28             sub      rsp, 40

G_M45811_IG02:
       48B9523B9DAAFC7F0000 mov      rcx, 0x7FFCAA9D3B52
       BA64000000           mov      edx, 100
       E82862145F           call     CORINFO_HELP_NEWARR_1_OBJ
       33D2                 xor      edx, edx
       33C9                 xor      ecx, ecx
       448B4008             mov      r8d, dword ptr [rax+8]
       4585C0               test     r8d, r8d
       7E3C                 jle      SHORT G_M45811_IG07

G_M45811_IG03:
       4C63C9               movsxd   r9d, ecx
       4E8B4CC810           mov      r9, gword ptr [rax+8*r9+16]
       4D85C9               test     r9, r9
       7505                 jne      SHORT G_M45811_IG04
       FFC2                 inc      edx
       EB24                 jmp      SHORT G_M45811_IG06

G_M45811_IG04:
       4D85C9               test     r9, r9
       7412                 je       SHORT G_M45811_IG05
       49BA485DF04EFC7F0000 mov      r10, 0x7FFC4EF05D48
       4D3911               cmp      qword ptr [r9], r10
       7403                 je       SHORT G_M45811_IG05
       4533C9               xor      r9, r9

G_M45811_IG05:
       4D85C9               test     r9, r9
       7407                 je       SHORT G_M45811_IG06
       458B4908             mov      r9d, dword ptr [r9+8]
       4103D1               add      edx, r9d

G_M45811_IG06:
       FFC1                 inc      ecx
       443BC1               cmp      r8d, ecx
       7FC5                 jg       SHORT G_M45811_IG03

G_M45811_IG07:
       8BC2                 mov      eax, edx

G_M45811_IG08:
       4883C428             add      rsp, 40
       C3                   ret

; Total bytes of code 103, prolog size 4 for method Program:Main():int
; ============================================================

which has some extra interesting information you might like.

**Comment by mikedn** [comment]
> The QMARK operator holds the null-comparison as well as the type-test comparison. ...

Yes, the QMARK uses GT_EQ 0 as condition and it is expanded during morphing to GT_JTRUE + condition, everything seemed fine when I looked at this initially. Turns out that the type of the 0 Icon is wrong, it's TYP_I_IMPL and should be TYP_REF, see [importer.cpp:8181](https://github.com/dotnet/coreclr/blob/master/src/jit/importer.cpp#L8181). 0 and null have different VNs and assertion propagation fails to find eliminate the null check.

Fixing the type of 0 remove the redundant null check in this example but unfortunately it doesn't remove it from the original code this example was extracted from. I'll try to dig more when I find some more time, it's likely that I'm seeing an entirely different issue in my code.

> There is also further optimization opportunity available in this test case, ...

I know, there's an old Connect bug for that :smile:

> Btw, in case either of you are interested in getting deeper into the JIT, you can take a look at the assembly output of the JIT without having to drop into the debugger and its a bit easier to read.

Thanks, those variable assignments in the disassembly dump may be useful for another issue I saw.

**Comment by cmckinsey** [comment]
Yes, I had come to the similar conclusion and was in fact testing that change for a PR. The value-numbering phase does not treat nullptr and 0 as the same value number and therefore the assertion propagation does not consider the assertion in BB02 to eliminate the test in BB04.

Sorry to hear it doesn't get your original case however, I do see lots of good assembly diffs in some of our internal customer benchmarks. It's still worth fixing.

**Comment by mikedn** [comment]
My original case looks like the below example. I replaced the `as` with a plain null check because `as` isn't itself the problem here, it just takes the blame because it inserts the null check.

```C#
class Program {
    Program next;

    static int Main() {
        var o = new Program();
        var count = 0;
        for (; o != null; o = o.next) {
            if (o != null) { // this null check isn't eliminated
                count = 42;
            }
        }
        return count;
    }
}
```

It's probably obvious what's different, the `o` variable is now in a SSA cycle. I looked a bit more at the assertion propagation code but I have no idea how data flow analysis is supposed to work with SSA/GVN. 

There are 2 different versions of the same variable each with its own non-null assertion. Data flow merging is using intersection and the back edge assertion is dropped on the floor. It seems to me that merge should use union and let the PHIs deal with the merge but union breaks all other cases. Oh well...

Note that this works fine in the x86 JIT.

**Comment by cmckinsey** [comment]
In general union will not work correctly for this problem because we need assertion properties that hold true for all paths, not just any paths.

The x86 JIT gets this case because its assertion propagation is based on lexical equality for which o != null on both paths is identical and survives intersection through the loop header join. As you point out here they have different value-numbers in the SSA/GVN based version. Without putting explicit SSA side-effects after the predicates (think PI nodes from ABCD algorithm) its difficult to get these cases in SSA without some kind of graph pattern matching.

In the meantime we're not likely to get the loop case, but I'll work on getting the fix to the isinst expansion in. I see lots of improvements in our framework libraries with it, so thanks again.

**Comment by cmckinsey** [comment]
The fix for non-loop case is fixed with PR #548. I'm going to close this issue because I don't believe we're going to handle the cyclic case anytime soon as it requires some significant extensions to the current algorithm. @mikedn if you feel this still should be on the table for someone else to grab please open another issue for that case. Thanks again.

**Comment by mikedn** [comment]
Thanks for the fix!

Note that the cycle issue isn't really specific to cycles. It occurs any time 2 versions of the same variable have to be merged, this include some simple if/else situations. That said, the amount of work required to fix this case seems disproportionate so I'm not going to bother with it, at least for now.

**Comment by cmckinsey** [comment]
Yes agreed, should have been more specific.
