### ISSUE TITLE
StringBuilder is being internally corrupted if exceeding the maximum allowable length

### ISSUE THREAD

**Issue by GSPP** [dotnet/coreclr#4507]
static void StringBuilderNRE()
        {
            var length = checked(1024 * 1024 * 256);
            var str = new string('x', length);

            var sb = new StringBuilder();
            try
            {
                for (int i = 0; i < 10000; i++)
                {
                    sb.Append(str);
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex); //This is expected.
            }

            sb.Append("x"); //Crashes with NRE.
        }

**Comment by mikedn** [comment]
As described in #4514 this particular test should throw `ArgumentOutOfRangeException`, not `OutOfMemoryException` as it does now. The underlying cause is an integer overflow in `ExpandByABlock`.

It's also possible to get an `OutOfMemoryException` if there's not enough memory available. In that case the string builder becomes corrupted due to another `ExpandByABlock` issue, the chunk array is allocated after the new chunk is chained.
