### ISSUE TITLE
StringBuilder.Append(char, int) can fail mid-way

### ISSUE THREAD

**Issue by GSPP** [dotnet/coreclr#4514]
var sb = new StringBuilder();

            sb.Append('x', 2);
            sb.Length--;

            try
            {
                sb.Append('x', int.MaxValue);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex); //Expected.
            }

            Console.WriteLine(sb.ToString()); //Prints "xxxxxxxxxxxxxxxx", should print "xx".

Prints "xxxxxxxxxxxxxxxx", should print "xx". Also, the `StringBuilder` becomes corrupted but that is nothing new.

**Comment by mikedn** [comment]
>  should print "xx"

Why? Does the existing documentation make any guarantees about what happens when an OutOfMemoryException is thrown?

**Comment by GSPP** [comment]
It is true that this is not specified. But if you think it this is not guaranteed then you must also think that *all* framework methods are allowed to do arbitrary things in case of an exception. That's surely not the intention.

For example, nowhere is it guaranteed that `new string('x', -1)` does not format your disk *and* throws an exception.

**Comment by GSPP** [comment]
In particular it is hideous to design an API such that the object is left in a completely undefined state in case of an error. This is .NET, not C.

**Comment by mikedn** [comment]
> But if you think it this is not guaranteed then you must also think that all framework methods are allowed to do arbitrary things in case of an exception. That's surely not the intention.

Most framework methods do not guarantee anything in the face of certain exceptions and `OutOfMemoryException` is such an exception.

**Comment by tamlin-mike** [comment]
I'll have to agree with @GSPP here. This object should be able to not destroy its own state in face of this condition. Imagine a List encountering OOM on an Add() - would you except it to format your disks, in addition to removing (or duplicating!) random elements from the list and throwing an exception? I wouldn't. I'd expect it to retain its previous state and throw the exception.

Even if the .NET framework provides no promises whatsoever, it should at a minimum provide an implementation delivering the least amount of surprises. If not, why even bother?

**Comment by GSPP** [comment]
I think the framework should be changed so that the operations in question behave atomically. I see no reason this can't be done rather easily and efficiently at the same time. Then, these properties should be documented. `StringBuilder` is one of the most core types there are. It must be solid.

**Comment by mikedn** [comment]
> would you except it to format your disks

There's no need for such drama. This discussion is mainly about printing "xx" and not about whatever corrupted state the `StringBuilder` object might end up in. I don't know exactly what corrupted state @GSPP refers to since he felt the need to create multiple issues about what the same or similar underlying problem and now the discussion is spread between 3-4 threads.

And if your disks are formatted then it's likely your fault for catching exceptions indiscriminately, continuing as if nothing happened and even using the object that was being modified when the exception was thrown. It would be `StringBuilder` fault if the unsafe code that it contains ends up corrupting other memory but at this point I don't know if this is the case.

> Imagine a List encountering OOM on an Add()

`List<T>.AddRange` does just that. It doesn't become corrupted but the post exception state is not the original state. To make things even more complicated it only does this if the collection object doesn't implement `ICollection<T>`.

**Comment by mikedn** [comment]
Judging by the existing documentation and code `Append` should throw `ArgumentOutOfRangeException` in this particular case, not `OutOfMemoryException`. That's because appending `int.MaxValue` characters to a string builder that already contains something would result in `MaxCapacity` being exceeded. And if `ArgumentOutOfRangeException` is thrown then it would be reasonable to expect that the string builder is left unmodified even if argument exceptions usually don't carry such a requirement.

There is code in `ExpandByABlock` that's supposed to throw an argument exception (with a weird parameter name) but it fails to work in this case due to an integer overflow. Should be trivial to fix unless someone is concerned about the change in the thrown exception type. Probably not as in typical cases that code already works fine and throws `ArgumentOutOfRangeException`.

But if you try to append, say, `int.MaxValue - 42` characters then you get a legitimate `OutOfMemoryException`. In this case the string builder does become corrupted because `ExpandByABlock` first chains the new chunk and then allocated the char array for the new chunk. The net result is that both the old and the new chunk use the same char array and future appends make a mess.

This is trivial to fix and probably worthwhile. But making the entire append atomic with respect to exceptions doesn't seem necessary. Appending some characters and then throwing is just as valid as not appending anything and throwing. This sounds more like a feature request rather than a bug.

**Comment by GSPP** [comment]
I believe FastAllocateString can be called with too big of an argument in many cases (not just the case of this issue). Probably, all of those cases should become a different exception type such as ArgumentOutOfRangeException as documented. That exception type feels wrong, too, but we're probably stuck with it.
