### ISSUE TITLE
[x86] Failing test b46649

### ISSUE THREAD

**Issue by LLITCHEV** [dotnet/coreclr#4547]
Failing test running d:\repos\coreclr\tests\src\TestWrappers_x86_Checked\JIT\JIT.XUnitWrapper.cs(335238): error : JIT._Regression_CLR_x86_JIT_V1_M11_Beta1_b46649_b46649_b46649_._Regression_CLR_x86_JIT_V1_M11_Beta1_b46649_b46649_b46649_cmd [FAIL] [d:\repos\coreclr\tests\runtest.proj] test on x86 CoreCLR.

**Comment by sivarv** [comment]
The test case is AV'ing in optLoopCodeMotion() in the following if statement condition

```
            if  ((loopRmv & loopBit)     ||
                 tail == 0               ||
                 head->bbTreeList == 0    )

```

optLoopCount =1 but head is null.
head = optLoopTable[loopNum].lpHead->bbNext

AV is hit in the very first for-loop iteration. 

The repro case is

```
i = -111
while ( i > 0)
{
    // another nested loop goes here
}
return 100
```

After assertionProp, due to while loop condition lot of stmts get deleted as unreachable and in that process optLoopTable doesn't seem to be updated properly somewhere in fgUpdateFlowGraph().

**Comment by sivarv** [comment]
A fix to this issue is checked-in on tfs side.
