### ISSUE TITLE
jitShutdown called twice when CoreCLR shuts down

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/coreclr#4605]
If `FEATURE_MERGE_JIT_AND_ENGINE` is defined, `jitShutdown` gets called first when `EEShutdown` runs, then again when the coreclr dll unloads.

`jitShutdown' does a bit of cleanup and some off-by-default reporting. Calling it twice is is evidently harmless enough for the cleanup parts, but the second invocation can mess up reporting.

**Comment by adityamandaleeka** [comment]
@AndyAyersMS Commit https://github.com/dotnet/coreclr/commit/121d095ed0b0076fb1c7ff59e6446fd19d506b32 brought over a bunch of JIT changes, including the addition of a call to `jitShutdown` in `CILJit::ProcessShutdownWork`, which seems to be called when `EEShutdown` runs.

The other place where `jitShutdown` is called (under `FEATURE_MERGE_JIT_AND_ENGINE`) is in the `DLL_PROCESS_DETACH` in `DllMain` for mscoree. It looks like that's been there since the initial commit to GitHub.

I'm not sure why the one in `ProcessShutdownWork` was added. Perhaps @briansull knows?

Anyway, one potential fix here is to remove the call to `jitShutdown` when mscoree unloads, since it's already being run during `EEShutdown`. Does that sound reasonable?

**Comment by adityamandaleeka** [comment]
I just noticed https://github.com/dotnet/coreclr/pull/5015 is changing some of this code.

**Comment by AndyAyersMS** [comment]
When #5015 lands I'll see if I can remove my workaround.

**Comment by adityamandaleeka** [comment]
#5015 has been merged and should fix this. @AndyAyersMS I'll let you close the issue.

**Comment by AndyAyersMS** [comment]
Verified it's fixed. Thanks all.
