### ISSUE TITLE
Arm64: JIt is not correctly generating code for looking up classhandle

### ISSUE THREAD

**Issue by ramarag** [dotnet/coreclr#4615]
The following is the code generated by JIt to lookup Classhandle to be passed to VM helper- in this case JIT_New [ in mscorlib_ni!System.AppDomain.SetupDomain for ]

18000580 ldr         w0,mscorlib_ni+0xa5e818 
 97f29a45 bl          CORINFO_HELP_NEWSFAST  (mscorlib_ni+0x705080 )

the correct code should be like below, with the memory location having the correct classhandle value
ldr         x0,mscorlib_ni+0xa5e818 

@kyulee1 : brian asked me to assign this to you

cc @briansull @gkhanna79

**Comment by kyulee1** [comment]
Looking at this issue, it appears `ldr x0, <label>` is not the right one either.
`adr x0, <label>` should be a right form. But this only can express address range within +- 1MB using 21bit only which is impractical in the common case
I was surprised that we only support this 21bit fix-up at this point both in VM/Zap/Jit.
We should have additional fix-up (12 bit for page offset) so that we can compute address of data in the following way:
```
adrp x0, <label> : 21 bit encoding for page address
add x0, x0, <label>: 12 bit encoding for page offset
```
