### ISSUE TITLE
[question] Is it possible to debug mscorlib from Visual Studio?

### ISSUE THREAD

**Issue by jamesqo** [dotnet/coreclr#4678]
I'm trying to debug a Release build of mscorlib I built locally using Visual Studio, but it doesn't seem like it's working. I made sure the `.pdb` file is copied to the output directory and Just My Code is disabled, but it doesn't appear to be working.

Is it possible to debug mscorlib from within Visual Studio yet, or do I still have to ues WinDbg/SOS? It says [here](https://github.com/dotnet/coreclr/blob/775003a4c72f0acc37eab84628fcef541533ba4e/Documentation/building/debugging-instructions.md#debugging-mscorlib-andor-managed-application) that debugging mscorlib should be available with VS 2015, is this still true?

Thanks.

**Comment by mikedn** [comment]
Hmm, try deleting the native image (mscorlib.ni.dll) that the build produces. Or see if you can get crossgen to generate a PDB for mscorlib.ni.dll now that #4572 has been merged.

**Comment by benaadams** [comment]
Yes, though I don't know if this is the best way... Make sure you have all the options ticked in 
`Options->Debugger->Just In Time`

Make a standalone app (rather than shared framework) 
e.g `netstandardapp1.4` with `"runtimes": { "win7-x64": { } }`

`dotnet publish` (`-c Release` if you want a release build of app)

Your app + framework + runtime should now be in directory `bin\Debug\netstandard1.4\win7-x64\publish`

Copy `*.dll` from `coreclr\bin\Product\Windows_NT.x64.Release` into this directory
Copy `*.pdb` from `coreclr\bin\Product\Windows_NT.x64.Release\PDB` into this directory

Run your program from this directory, either doing attach to process in VS or adding a new Profile for you app in its debug properties and running, or adding a `Debugger.Launch()` statement in code.
