### ISSUE TITLE
Some test cases require more than 2GB RAM

### ISSUE THREAD

**Issue by mylibero** [dotnet/coreclr#4714]
I notice that the following test cases are trying to use 2GB RAM.

tests/src/GC/LargeMemory/Allocation/largeexceptiontest
tests/src/GC/LargeMemory/API/gc/gettotalmemory
tests/src/GC/LargeMemory/API/gc/keepalive
tests/src/GC/LargeMemory/API/gc/suppressfinalize

They take the size for allocation as an integer argument in GB. 
That means modifying csproj will only reduce it to 1GB, which is still huge for some testing environments.

How about modifying test cases so that they allocate as much as they can within the specified amount?
If no one else is interested in, I will modify test cases.

@myungjoo @jyoungyun

**Comment by myungjoo** [comment]
Possible amends:

1. Just skip the testcases for systems < N GB. (not good)
2. Make it adaptive and and allow the argument to get < 1GB input as well. (great IMHO)
  e.g., Try to use 80% of free memory.

**Comment by swgillespie** [comment]
There is a "playlist" for tests that allocate a lot of memory or are otherwise inappropriate to run on constrained devices. Tests are marked for this playlist using this msbuild attribute on Windows: https://github.com/dotnet/coreclr/blob/master/tests/src/GC/Features/BackgroundGC/concurrentspin2.csproj#L16 and this file on Linux: https://github.com/dotnet/coreclr/blob/master/tests/longRunningGcTests.txt . We could move these tests to this playlist if they are too resource-intensive for running as part of the normal test run.

**Comment by mylibero** [comment]
The question would be whether we want to test those TCs on our devices.
The answer's yes and I will change the test cases.

**Comment by swgillespie** [comment]
Sounds good!
