### ISSUE TITLE
GC\Scenarios\DoublinkList\dlstack.cs times out under gcstress.

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/coreclr#4748]
http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/x64_checked_windows_nt_gcstress0x3/lastCompletedBuild/testReport/

Runtime is at best unpredictable.  I ran it twice locally.  The first one I killed after five hours; the second passed after two hours.

Assuming this isn't a product bug, the test should be moved out of mainline runs and added to the "long running" set.

**Comment by swgillespie** [comment]
@RussKeldorph This passes in a matter of seconds without GCStress set. I took a trace and it looks like majority of the time is spent doing contract checks and in control-flow guard related functions, so I don't think it's a product issue. Would you be OK disabling this for GCStress instead of moving it to the long running set? The long running set currently only runs on Release builds where this doesn't repro.

**Comment by RussKeldorph** [comment]
@swgillespie sure, marking gcstressincompatible is fine.  Sorry, I  shouldn't have proposed a solution.

**Comment by swgillespie** [comment]
Just disabled the test for GCStress. thanks!
