### ISSUE TITLE
Tests failing due to expected constructor not running

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/coreclr#4853]
I'm not certain, but these tests look like they may be failing because they are expecting a constructor to run that isn't.   I may also be incorrect about these tests failing for the same issue.  This grouping is just based on an initial impression.

Tests
```
JIT\Methodical\cctor\misc\tail_il_d\tail_il_d.cmd
JIT\Methodical\cctor\misc\tail_il_r\tail_il_r.cmd
```
Output
```
Testing .cctor() invocation by calling virtual method

Before running virtual method
After running virtual method
in Main() after f(ref b), measure.a is 0
FAILED
Expected: 100
Actual: -1
```
Tests
```
JIT\Methodical\cctor\misc\threads3_il_d\threads3_il_d.cmd
JIT\Methodical\cctor\misc\threads3_il_r\threads3_il_r.cmd
```
Output
```
Before calling static field
Thread #0 in .cctor(), measure.a is 0
Thread #1 in .cctor(), measure.a is 0
Thread #3 in .cctor(), measure.a is 0
Thread #2 in .cctor(), measure.a is 0
Thread #3 in .cctor(), after +=8, measure.a is 3
Thread #1 in .cctor(), after +=8, measure.a is 2
Thread #2 in .cctor(), after +=8, measure.a is 4
Thread #4 in .cctor(), measure.a is 0
Thread #4 in .cctor(), after +=8, measure.a is 5
Thread #0 in .cctor(), after +=8, measure.a is 1

After calling static field
in Main(), measure.a is 5
FAILED
Expected: 100
Actual: -1
```
Tests
```
JIT\Methodical\cctor\simple\precise3_il_d\precise3_il_d.cmd
JIT\Methodical\cctor\simple\precise3_il_r\precise3_il_r.cmd
```
Output
```
Testing .cctor() invocation by calling virtual method

Before running virtual method
After running virtual method
in Main() after f(ref b), measure.a is 0
FAILED
Expected: 100
Actual: -1
```

**Comment by RussKeldorph** [comment]
I'm hoping this is just a test issue, but I can't say much for sure yet.

**Comment by LLITCHEV** [comment]
For the tail_il_d and tail_il_r this is a test issue.
The constructor of test2 class (test2::.ctor) is badly written. It calls the constructor of object instead of the one of the base class - test. The test class is never instantiated and its static constructor never executed. Below is the code. Call os a virtual method doesn't trigger class initialization (running the static constructor). According to the spec, a static constructor is invoked when the first instance of a class is created ir any static member is referenced. (See below the test2 constructor the part of the spec that discusses when a static constructor is called). It is unclear to me what this test is trying to test.

.class private auto ansi beforefieldinit test2
       extends test
{
  .method public hidebysig specialname rtspecialname 
          instance void  .ctor() cil managed
  {
    .maxstack  1
    IL_0000:  ldarg.0
    IL_0001:  call       instance void [mscorlib]System.Object::.ctor()
    IL_0006:  ret
  } 
} 

"A static constructor is used to initialize any static data, or to perform a particular action that needs performed once only. It is called automatically before the first instance is created or any static members are referenced."

**Comment by RussKeldorph** [comment]
@LLITCHEV test.il passes with Full CLR.  Is this a difference in beforefieldinit semantics between .NET Core and .NET (Full)?

**Comment by jkotas** [comment]
It is bad test - the test contains invalid IL. The ECMA-335 spec says: `CLS Rule 21: An object constructor shall call some instance constructor of its base class`. The constructor of the test2 type is violating this rule.

**Comment by LLITCHEV** [comment]
The reason for these test failures is the same. These tests make assumptions on the invocation of static constructors. The VM can decide when to call a static initializer in case of present .beforefieldinit flag, as long as it is invoked before accessing any static field of the class containing the static initializer. The problem here is the tests make incorrect assumption.
