### ISSUE TITLE
[Arm64] Consistency check failed: AV in clr at GC call stack

### ISSUE THREAD

**Issue by ramarag** [dotnet/coreclr#4877]
Affected tests:  
System.Dynamic.Runtime.Tests
System.Collections.Tests
System.Linq.Parallel.Tests

```
Assert failure(PID 18284 [0x0000476c], Thread: 2844 [0x0b1c]): Consistency check failed: AV in clr at this callstack:
------
CORECLR! WKS::gc_heap::background_mark_simple1 + 0x8B8 (0x00007ff8`1b080930)
CORECLR! WKS::gc_heap::background_mark_simple + 0x2C0 (0x00007ff8`1b081c20)
CORECLR! WKS::gc_heap::background_promote + 0x224 (0x00007ff8`1b0831a4)
CORECLR! PinObject + 0xD4 (0x00007ff8`1ab89034)
CORECLR! ScanConsecutiveHandlesWithoutUserData + 0x80 (0x00007ff8`1afd2a60)
CORECLR! BlockScanBlocksWithoutUserData + 0x40 (0x00007ff8`1afd2280)
CORECLR! ProcessScanQNode + 0x58 (0x00007ff8`1afd2868)
CORECLR! ProcessScanQueue + 0x58 (0x00007ff8`1afd28e0)
CORECLR! xxxTableScanQueuedBlocksAsync + 0xE0 (0x00007ff8`1afd3290)
CORECLR! xxxAsyncSegmentIterator + 0x54 (0x00007ff8`1afd30cc)
CORECLR! TableScanHandles + 0xE8 (0x00007ff8`1afd2e68)
CORECLR! xxxTableScanHandlesAsync + 0x74 (0x00007ff8`1afd3174)
CORECLR! HndScanHandlesForGC + 0x198 (0x00007ff8`1ab86e10)
CORECLR! Ref_TracePinningRoots + 0xF8 (0x00007ff8`1ab8abc8)
CORECLR! GCScan::GcScanHandles + 0x8C (0x00007ff8`1afa20f4)
CORECLR! WKS::gc_heap::background_mark_phase + 0x814 (0x00007ff8`1b07e5ac)
CORECLR! WKS::gc_heap::gc1 + 0x19C (0x00007ff8`1b09b93c)
CORECLR! WKS::gc_heap::bgc_thread_function + 0x778 (0x00007ff8`1b086bc8)
CORECLR! WKS::gc_heap::bgc_thread_stub + 0x68 (0x00007ff8`1b087170)
-----
.AV on tid=0xb1c (2844), cxr=00000078316BE1D0, exr=00000078316BE560
FAILED: false

CORECLR! CHECK::Trigger + 0x2C4 (0x00007ff8`1aa6f384)
CORECLR! CLRVectoredExceptionHandlerPhase3 + 0x26C (0x00007ff8`1ac0d32c)
CORECLR! CLRVectoredExceptionHandlerPhase2 + 0x70 (0x00007ff8`1ac0cde0)
CORECLR! CLRVectoredExceptionHandler + 0x178 (0x00007ff8`1ac0cd08)
CORECLR! CLRVectoredExceptionHandlerShim + 0xC4 (0x00007ff8`1ac0d5a4)
NTDLL! RtlIsProcessorFeaturePresent + 0x1D8 (0x00007ff8`4f3a6f88)
NTDLL! RtlLogStackBackTrace + 0x198 (0x00007ff8`4f40b1d8)
NTDLL! KiUserExceptionDispatcher + 0x28 (0x00007ff8`4f3821c8)
CORECLR! WKS::gc_heap::background_mark_simple1 + 0x8B8 (0x00007ff8`1b080930)
CORECLR! WKS::gc_heap::background_mark_simple + 0x2C0 (0x00007ff8`1b081c20)
    File: e:\git\coreclr\src\vm\excep.cpp Line: 8141
    Image: Z:\core_root\CoreRun.exe
```

**Comment by swgillespie** [comment]
Possibly related: https://github.com/dotnet/coreclr/issues/4802

**Comment by rahku** [comment]
This is due to incorrect GCInfo for below method in xunit.console.netcore.exe
Xunit.ConsoleClient.CommandLine.Parse(System.Predicate`1<System.String>)

In particular it reports stack sp+0x20 as being live at offset of 0x484. This is not correct.

Stack slot id for offset 32 (0x20) (frame) = 27

Set state of slot 27 at instr offset 0x484 to Live.
Set state of slot 27 at instr offset 0x9b8 to Dead

From below disassembly we can see that code does not store any live object at sp+0x20 at code address around 0x484 offset. So it is reporting garbage value as live object.

!u 00007ff84862e218+480

00007ff8`4862e688 d2861d01 mov         x1,#0x30E8

00007ff8`4862e68c f2ae0121 movk        x1,#0x7009 lsl #0x10

00007ff8`4862e690 f2c03fc1 movk        x1,#0x1FE lsl #0x20

>>> 00007ff8`4862e694 f9400021 ldr         x1,[x1]

00007ff8`4862e698 aa1503e0 mov         x0,x21

00007ff8`4862e69c 97ffd4af bl          System.String.Equals(System.String, System.String) 
(00007ff8`48623958)

4862e6a0 7100001f cmp         w0,#0 (gcstress)

4862e6a4 54000100 beq         00007ff8`48708a00 (gcstress)

4862e6a8 f94083a0 ldr         x0,[fp,#0x100] (gcstress)

4862e6ac f94087a1 ldr         x1,[fp,#0x108] (gcstress)

4862e6b0 97ffcdd8 bl          00007ff8`486fc14c (gcstress)

4862e6b4 f94017a1 ldr         x1,[fp,#0x28] (gcstress)

4862e6b8 52800020 mov         w0,#1 (gcstress)

**Comment by rahku** [comment]
Adding jitdump file <script src="https://gist.github.com/rahku/00fc18932666fb3f92271ea1ae07026a.js"></script>

It is a large file

**Comment by rahku** [comment]
https://gist.github.com/rahku/00fc18932666fb3f92271ea1ae07026a.js

**Comment by rahku** [comment]
https://gist.github.com/rahku/00fc18932666fb3f92271ea1ae07026a

**Comment by briansull** [comment]
The supremely large JitDump could be reduced by using
COMPLUS_JitDump=CommandLine:Parse
to generate the JitDump for just that one method

**Comment by briansull** [comment]
The GC info printed out by the dump indicates that the JIT believes that that slot is becoming live at offset 00484.

We will need to investigate why the JIT prints out the following info in the dump:

gcrReg +[x1]
IN0112: 00047C  F9400021          ldr     x1, [x1]
gcrReg +[x0]
IN0113: 000480  AA1503E0          mov     x0, x21
New GC ref live vars=000000000000000000020004 {V00 V06}
[78964D38] gcr var born at [fp+28H]
[78964D50] gcr var born at [fp+20H]
New gcrReg live regs=200000 {x21}
gcrReg -[x0]
gcrReg -[x1]
[78964DB8] ptr arg pop  0
IN0114: 000484  97FFD4AF          bl      System.String:Equals(ref,ref):bool

**Comment by kyulee1** [comment]
I have a fix for it -- https://github.com/dotnet/coreclr/pull/5789
But still another consistency failure far later on.
Once I merge the above, I might reassign it to @rahku.

**Comment by kyulee1** [comment]
Via #5789 and #5821, Validated all tests are passed (not crash, no failure).
