### ISSUE TITLE
Add package authoring for Fedora 23 and Ubuntu 16.04

### ISSUE THREAD

**Issue by ellismg** [dotnet/coreclr#4987]
We already have these packages being produced via TFS, but we should augment the open source authoring as well.

Presently blocked on getting a CLI build we can depend on so we can generate mscorlib.dll and mscorlib.ni.dll.

**Comment by gkhanna79** [comment]
> Presently blocked on getting a CLI build we can depend on so we can generate mscorlib.dll and mscorlib.ni.dll.

@ellismg Can you please elaborate on this? mscorlib.dll and mscorlib.ni.dll are built as part of CoreCLR repo build.

**Comment by ellismg** [comment]
We need a working CLI to be able to restore the tool runtime and run MSBuild so we can compile mscorlib here.

**Comment by davzucky** [comment]
@ellismg, rather than trying to have a custom package for all the different distribution and version, why not creating a cli package for the dotnet build only where all the native dependency are statically linked. The two that I found so far are 

- System.Globalization.Native.so : Dependency on icu
- System.Net.Http.Native.so : Dependency on curl 

I have a push request ready for System.Net.Http.Native that allow to link curl into it. 

# Pro
- Anyone with any version of Linux for the right architecture would be able to build dotnet
- Simplification of the Build script as we would need only to check the architecture and not the distribution
- Easy to get new distribution
# Cons
- Bigger size package for build

This would not remove the need to create to production package for each distribution however it would make it easier.

Another that I was think as well regarding that. If we arrive to have one cli package that would work for all the Linux distribution, we could think about having all the Linux distribution build been generated using Docker for each Linux version which would be managed from the repository. This could even simplify the infrastructure going forward and the turn around to get a new distribution/version

**Comment by joshfree** [comment]
Linking issues https://github.com/dotnet/corefx/issues/5990 and https://github.com/dotnet/corefx/issues/7191 by request

**Comment by ellismg** [comment]
@davzucky 

In general, the team is very weary of static linking for official builds.  In addition to the dependencies you pointed out, there are others.  We use libunwind for stack walking, we use libcrypto and libssl (from openssl) for cryptography.  We use libz for compression.  We link against additional libraries like gssapi for kerberos support. 

The heart if the issue is that we don't want to sign up for CoreCLR and the CLI to be distribution mechanisms for the above.  When there is a CVE in OpenSSL, we don't want to have to patch the core libraries and the CLI.  We don't want to folks to have to understand that they have another copy of OpenSSL floating around their system.  We don't want distributions that choose to package us (and the long term goal is to try to get our packages in as many distributions as possible) to have to undo the static linking.  In addition to the security/servicing related aspect, there's probably some internal legal work that Microsoft would need to do to ensure shipping with statically linked dependencies just to make sure we are doing everything correctly.  It's also possible that distributions have introduced patches for each of our dependencies specific for their distro and we want to pick up these patches,

The current plan for 1.0 is that we'll produce binary package for supported platforms that link against what is in the package manager.

Having said that, static linking is super interesting and our general position is we welcome patches that will enable either CoreFX or CoreCLR to statically link against dependencies.  Having a statically linked CLI would be useful in some bootstrapping scenarios and allowing folks to build their own copy of the static that was statically linked when it meets their needs is something that I think is overall goodness.

Regarding this specifically:

> If we arrive to have one cli package that would work for all the Linux distribution, we could think about having all the Linux distribution build been generated using Docker for each Linux version which would be managed from the repository. This could even simplify the infrastructure going forward and the turn around to get a new distribution/version

Very soon I would like to build infrastructure on top of docker images that takes as input a docker image with a toolchain and produces as output a version of the CoreFX, CoreCLR and the CLI built in that image.  I'm not sure if I'll have everything nailed down by RTM, but doing so is important to me.  It would accurately describe how to bootstrap the entire stack, which is something I care deeply about.

**Comment by davzucky** [comment]
@ellismg, thank you for your detailed answer. I may not have been clear on my previous answer but I think we are on the same page. We should have a bootstrap Cli package to allow to build on any distribution (coreclr, corefx), use to build all the target Linux distribution package.
Thank you for the list of the other dependency, I will have a look at that as well, I will keep that on the side as I'm updating the packaging.
My point doesn't add any value of this issue which is about the support of new distribution, sorry about that.

**Comment by ellismg** [comment]
> We should have a bootstrap Cli package to allow to build on any distribution (coreclr, corefx), use to build all the target Linux distribution package.

Cool.  I agree we are on the same page.

**Comment by ellismg** [comment]
This is done now (and also in 1.0.0/release)
