### ISSUE TITLE
Why doesn't Task.FromResult use cached Tasks

### ISSUE THREAD

**Issue by benaadams** [dotnet/coreclr#5185]
Like AsyncTaskMethodBuilder?

**Comment by stephentoub** [comment]
It was essentially a design decision made so that FromResult behaved like a ctor, where you knew you were always getting back a new instance.  The majority of the times FromResult is used, it would not be able to pull from a cache, and thus it would generally be paying the overhead of accessing the cache even though it would rarely hit.  There are of course a few exceptions to that, like for bools, but in those cases you're better off anyway just having your own fields you can hit quickly rather than going through the gymnastics inside this generic implementation to get the right cache and fetch the right associated task based on the supplied generic value.

**Comment by benaadams** [comment]
Close #5186 then?

**Comment by stephentoub** [comment]
I just tried your PR.  Using Task.FromResult<int> with values other than -8 to 8 got ~25% slower on my machine.  If you believe that the majority of FromResult usage won't hit cached values, e.g. when used in a Stream.ReadAsync, won't be returning that small pool of values, then changing FromResult in this manner is actually a step backward.  We did it for AsyncTaskMethodBuilder because in those cases you don't have any explicit control over caching, and since we do want to do some (e.g. for 0, 1, -1, etc. which are fairly common return values from methods), we already have to pay the cache-access overhead, but FromResult is a way to enable the developer to have complete control, to do their own caching, and to avoid caching overheads when they don't want it.

**Comment by benaadams** [comment]
Might be a moot change anyway with arbitrary async returns https://github.com/dotnet/roslyn/issues/10902

**Comment by benaadams** [comment]
Might be a moot change anyway with arbitrary async returns https://github.com/dotnet/roslyn/issues/10902

e.g. not worth trying to investigate whether the caching could be improved for this scenario; as there is a potential better solution already which works with all return values (and it can be cached as you point out for standard ones in user code)
