### ISSUE TITLE
C# compiler and reflection API inconsistency

### ISSUE THREAD

**Issue by JeWaVe** [dotnet/coreclr#5368]
See [this stackoverflow question](http://stackoverflow.com/questions/37567665/how-to-emit-defaulttimespan-as-the-default-value-of-an-optional-parameter/37570005#37570005)

C# compiler (visual 2012), consider the following code as valid: 

```
public class MyClass
{
    public static void Foo(TimeSpan ts = default(TimeSpan))
    {
    }
}
```

and it compiles down to 

```
.method public hidebysig static 
    void Foo (
        [opt] valuetype [mscorlib]System.TimeSpan ts
    ) cil managed 
{
    .param [1] = nullref
    // Method begins at RVA 0x2050
    // Code size 1 (0x1)
    .maxstack 8

    IL_0000: ret
} // end of method MyClass::Foo
```

However, it's impossible to emit this msil by directly using System.Reflection.Emit. 

The expected code: 

`parameterBuilder.SetConstant(default(TimeSpan))`

throws an exception: 

> Unhandled Exception: System.ArgumentException: System.TimeSpan is not a supported constant type.
>    at System.Reflection.Emit.TypeBuilder.SetConstantValue(ModuleBuilder module, Int32 tk, Type destType, Object value)

It's possible to workaround that by invoking manually internal methods from Reflection.Emit (as you can see in the attached code, or in the stackoverflow question). 

I wouldn't consider it a bug if C# compiler wouldn't support that syntax, but since it does, I think reflection API should allow emission of this kind of msil. 
[Program.zip](https://github.com/dotnet/coreclr/files/293603/Program.zip)

**Comment by stakx** [comment]
@JeWaVe: It's instructive to also look at the default value of your `ts` parameter using reflection: According to `ParameterInfo.DefaultValue`, it will be `null` (as recorded in metadata), not `default(TimeSpan)` (as in C# source code).

I can think of two ways to improve reflection:

1. Allow `ParameterBuilder.SetConstant(default(TValueType))`. This gets reflection closer to the high-level languages (C#, VB.NET). In this case, `ParameterInfo.DefaultValue` on a `TValueType`-d parameter should probably also return `default(TValueType)` for consistency's sake (and to get correct "roundtripping" behaviour).

2. Allow `ParameterBuilder.SetConstant(null)` on `TValueType`-d parameters. This brings client code using reflection closer to metadata implementation details and allows you to mimick the C# compilers' way of handling this situation. It also gives us consistency wrt to `ParameterBuilder.SetConstant` & `ParameterInfo.DefaultValue`. But you'll have to know that `default(TValueType)` must be translated to/from `null` in user code.

While option (1) might seem preferable from a C# programmer's perspective, option (2) is the smaller and less risky* change overall, so to get things rolling I've submitted an issue (https://github.com/dotnet/corefx/issues/26184) and a PR (https://github.com/dotnet/coreclr/pull/17887) to get us there.

*) Why is option (2) "less risky"? Because it enables an additional use case that is currently disallowed, so it's unlikely to break existing user code. (1) on the other hand would change the behaviour of an existing & permitted use case and thus might be a breaking change.

**Comment by JeWaVe** [comment]
@stakx Option 2 looks perfectly reasonable to me. Glad to see this issue will be solved :)

**Comment by jkotas** [comment]
This was fixed by https://github.com/dotnet/corefx/issues/26184
