### ISSUE TITLE
libsosplugin.so getting an RPATH of /usr/lib/llvm on RHEL

### ISSUE THREAD

**Issue by ellismg** [dotnet/coreclr#5391]
@omajid pointed this out to me.  When building on RHEL, the resulting libsosplugin.so that's produced has an RPATH pointing to /usr/lib/llvm.  (libsos.so and libmscordbi.so also have an RPATH but it is set to $ORIGN).  When building on Ubuntu 16.04 (I'll look at all the other distros later) libsosplugin.so doesn't have a RPATH at all.

@mikem8361 Do you know what's going on here?  I thought some of this stuff needed RPATHS sout could load in the debugger without having to set `LD_LIBRARY_PATH` but I don't know if the plugin itself needs it or why it would be a hard coded value.

**Comment by omajid** [comment]
Could this be caused by the difference in where the RHEL llvm package [1] and the Ubuntu llvm package place their libraries?

On [RHEL](https://matell.blob.core.windows.net/rpms/llvm-libs-3.6.2-1.el7.centos.x86_64.rpm):
    /usr/lib64/llvm/LLVMgold.so
    /usr/lib64/llvm/libLTO.so

On [Ubuntu](http://packages.ubuntu.com/xenial/amd64/llvm-dev/filelist):
    /usr/lib/LLVMgold.so
    /usr/lib/libLTO.so

An RPATH of `/usr/lib` is probably getting removed (by the linker? or the .NET build system?) because it's the default linker path already. And `/usr/lib64/llvm/` isn't. However, on RHEL, `/etc/ld.so.conf.d/llvm-x86_64.conf` already configures the linker to include `/usr/lib64/llvm/` in the default linker search path. So it should not be needed either.

[1] There is no official llvm in RHEL yet

**Comment by mikem8361** [comment]
I'm going to try to explicitly set the RPATH like the other projects by adding the below to sosplugin's CMakeLists.txt.

# Set the RPATH of mscordbi so that it can find dependencies without needing to set LD_LIBRARY_PATH
# For more information: http://www.cmake.org/Wiki/CMake_RPATH_handling.
if(CORECLR_SET_RPATH)
  set(CMAKE_BUILD_WITH_INSTALL_RPATH TRUE)
  if(CLR_CMAKE_PLATFORM_DARWIN)
    set(CMAKE_INSTALL_RPATH "@loader_path")
  else()
    set(CMAKE_INSTALL_RPATH "\$ORIGIN")
  endif(CLR_CMAKE_PLATFORM_DARWIN)
endif(CORECLR_SET_RPATH)

**Comment by mikem8361** [comment]
@omajid I'm curious what problem this RPATH causes?  libsosplugin.so is loaded explicitly by the LLDB "plugin load" command so I don't think the RPATH matters.  And on Ubuntu 14.04 build, libsosplugin.so has the RPATH of where the LLDB libraries are too (as least on my local build and I'm building against a LLDB 3.8 I've built myself).

readelf -d libsosplugin.so
...
 0x000000000000000f (RPATH)              Library rpath: [/home/mikem/builds/llvm/release/lib]

**Comment by omajid** [comment]
@mikem8361 `RPATH`s are discouraged by Linux distributions for various reasons (including security, multi lib support and so on). I believe an `RPATH` of `$ORIGIN` is an exception to the rule.

- Debian: https://wiki.debian.org/RpathIssue
- Fedora: https://fedoraproject.org/wiki/Packaging:Guidelines?rd=Packaging/Guidelines#Beware_of_Rpath
- openSUSE: https://en.opensuse.org/openSUSE:Packaging_checks#Beware_of_Rpath

**Comment by omajid** [comment]
Btw, a more modern approach is to use `RUNPATH` instead of `RPATH`. This lets users (and developers and test systems) override the `RUNPATH` using `LD_LIBRARY_PATH`. See [this article](http://blog.tremily.us/posts/rpath/) for more details.

**Comment by mikem8361** [comment]
PR #5482
