### ISSUE TITLE
Build fail on FreeBSD10

### ISSUE THREAD

**Issue by avkarenow** [dotnet/coreclr#5509]
Hello,

I have problem to build the latest version from git-master on FreeBSD 10.2:
LLDB_LIB_DIR=/usr/local/llvm37/lib LLDB_INCLUDE_DIR=/usr/local/llvm37/include ./build.sh clang3.7
(...)
[  3%] Building CXX object src/pal/src/CMakeFiles/coreclrpal.dir/memory/heap.cpp.o
[  3%] Linking CXX shared library native_i3s/native_i3s.so
[  3%] Building CXX object src/pal/src/CMakeFiles/coreclrpal.dir/misc/dbgmsg.cpp.o
[  3%] Building CXX object src/pal/src/CMakeFiles/coreclrpal.dir/memory/local.cpp.o
Scanning dependencies of target native_i6c
[  3%] Built target native_i3c
Scanning dependencies of target native_i7c
Scanning dependencies of target native_i6s
[  3%] Linking CXX shared library native_i5s/native_i5s.so
[  3%] Building CXX object src/pal/src/CMakeFiles/coreclrpal.dir/misc/error.cpp.o
[  3%] Building CXX object tests/src/JIT/jit64/mcc/interop/CMakeFiles/native_i7c.dir/native_i7c.cpp.o
[  4%] Building CXX object tests/src/JIT/jit64/mcc/interop/CMakeFiles/native_i6s.dir/native_i6s.cpp.o
[  4%] Building CXX object src/pal/src/CMakeFiles/coreclrpal.dir/misc/environ.cpp.o
[  4%] Building CXX object tests/src/JIT/jit64/mcc/interop/CMakeFiles/native_i6c.dir/native_i6c.cpp.o
[  4%] Built target native_i3s
[  4%] Linking CXX shared library native_i5c/native_i5c.so
/home/test/git/coreclr/src/pal/src/map/virtual.cpp:1561:11: error: use of undeclared identifier 'PALGetLibRotorPalName'
    if (!(PALGetLibRotorPalName(palName, MAX_PATH_FNAME)))

Best Regards.

**Comment by adityamandaleeka** [comment]
Hi @avkarenow, I just took a very brief look at the code, and it appears that on your system, `MMAP_IGNORES_HINT` is being set, which is in turn defining `RESERVE_FROM_BACKING_FILE`, causing `VIRTUALGetBackingFile` to be compiled (which fails because `PALGetLibRotorPalName` doesn't exist).

My guess is that on every other platform, `MMAP_IGNORES_HINT` has not been defined, which is why this error is not being hit elsewhere. As a workaround, you can try disabling `MMAP_IGNORES_HINT`.

If you want to investigate why it's being set, take a look at the code we run through CheckCXXSourceRuns here: https://github.com/dotnet/coreclr/blob/master/src/pal/src/configure.cmake#L443

**Comment by adityamandaleeka** [comment]
@jkotas Any objection to deleting this dead code?

**Comment by jkotas** [comment]
Sounds good to me.

**Comment by avkarenow** [comment]
Thanks, last version of coreclr from master is compiling now without any changes.
