### ISSUE TITLE
[GCStress] GC\API\GC\GetGenerationWR2 fails under GCStress=3

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/coreclr#5514]
**Environment**
set COMPlus_GCStress=3

**Output**
```
BEGIN EXECUTION
 "O:\tfs\pk\src\NDP\clr\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\corerun.exe" GetGenerationWR2.exe
Test should return with ExitCode 100 ...
Test Failed
Expected: 100
Actual: 1
END EXECUTION - FAILED
FAILED
```

**Comment by RussKeldorph** [comment]
@swgillespie Could you confirm whether or not this test should pass under GCStress=3?  If it's not a test issue, we should escalate ASAP.

**Comment by swgillespie** [comment]
@RussKeldorph will do!

**Comment by RussKeldorph** [comment]
Removed x86 from the title as this should fail with x64 as well.

**Comment by swgillespie** [comment]
@RussKeldorph This is a product bug. This test fails when a GC occurs between lines 22 and 23, here: https://github.com/dotnet/coreclr/blob/master/tests/src/GC/API/GC/GetGenerationWR2.cs#L23 , because the array will have been promoted once before the WeakReference class is allocated. The call to GetGeneration here is to the `System.Object` overload and not the WeakReference one, so the generation of the WeakReference class is returned and not the generation of the target of the weak reference, causing the failure. The previous behavior would have been to call the WeakReference overload of GetGeneration, which does the correct thing (i.e. returns the generation of the WeakReference's target)

It would appear that the overload of GetGeneration that runs on `System.WeakReference` is not exposed via `mscorlib` (https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/GC.cs#L299). cc @jkotas @sergiy-k @Maoni0 , was this intentional for CoreCLR?

**Comment by jkotas** [comment]
> `GetGeneration` that runs on  `System.WeakReference`  is not exposed via  `mscorlib`

This is intentional for .NET Core v1.0. Note however, that this will be revisited going forward - this API is going to come back as part of https://blogs.msdn.microsoft.com/dotnet/2016/05/27/making-it-easier-to-port-to-net-core/.

**Comment by jkotas** [comment]
This is not a product bug - the v1.0 product is behaving as expected here.

**Comment by swgillespie** [comment]
In that case, this test will fail until we re-expose that API. I will exclude this test and other related ones.

**Comment by swgillespie** [comment]
Disabled by #5534.
