### ISSUE TITLE
Serialize benchmarks are slower on Linux than on Windows

### ISSUE THREAD

**Issue by erozenfeld** [dotnet/coreclr#5558]
xunit-perf numbers on benchmarks from coreclr\tests\src\JIT\Performance\CodeQuality\Serialization show a discrepancy between results on Linux and on Windows (lower is better):

| Benchmarks | Windows | Margin of error | Linux | Margin of error | (L - W)/W |
| --- | --- | --- | --- | --- | --- |
| Serialize.SerializeJsonNetBinary | 298 | 0.34% | 682 | 0.25% | 128.86% |
| Serialize.SerializeDataContractJson | 396 | 0.37% | 2390 | 0.08% | 503.54% |
| Serialize.SerializeJsonNet | 335 | 1.93% | 1560 | 0.12% | 365.67% |
| Serialize.SerializeDataContract | 438 | 0.40% | 1600 | 0.11% | 265.30% |

**Comment by erozenfeld** [comment]
I investigated Serialize.SerializeDataContractJson and opened 3 issues:
[Speed up JsonWriterDelegator.WriteDateTimeInDefaultFormat](https://github.com/dotnet/corefx/issues/9342)
[Make search in TimeZoneInfo.GetAdjustmentRuleForTime more efficient]
(https://github.com/dotnet/coreclr/issues/5716)
[Convert DateTime parameter of TimeZoneInfo.GetAdjustmentRuleForTime to UTC before searching for timezone rule]
(https://github.com/dotnet/coreclr/issues/5717)

Additionally, the benchmark is affected by _ecvt inefficiency tracked by [Perf: double.ToString(CultureInfo) 7x slower on Linux](https://github.com/dotnet/corefx/issues/3815)

Fixing these issues should speed up the benchmark on Linux by at least 4x.

**Comment by karelz** [comment]
The issue seems to be blocking #16636 (which is blocking .NET Core adoption for a customer who reached to us via CSS).
@erozenfeld @russellhadley are you on track to look into the problem for 2.0? Do you have ETA?
Note that @zhenlan's team will need time to verify the end-to-end scenario after the fix to make sure there are not more things hiding. Thanks!

**Comment by erozenfeld** [comment]
@karelz The investigation of this benchmark resulted in 4 issues above. Looks like 1 of them is fixed and 3 are still open. It doesn't look like any of them identified codegen issues so the jit team is not investigating this at the moment.

**Comment by karelz** [comment]
@erozenfeld thanks! Do we need this issue opened?
cc @mellinoe

**Comment by erozenfeld** [comment]
This issue was kept open to re-measure the benchmark once the 4 identified issues have been fixed to see if Windows vs. Linux perf is close enough then.

**Comment by tarekgh** [comment]
@karelz just to get some idea, are we moving all perf issues to v2.0.0? or how we decided which issues really blocking the customer from adapting netcore?

**Comment by karelz** [comment]
It's a DTS escalation (details offline) ...

**Comment by RussKeldorph** [comment]
Recent snapshot (dce9085e36908c076417ae56b5b8ce69480a29f2) numbers I see are below, so, while perhaps not at parity, this issue seems to have been substantially mitigated.  If there is further work necessary, please open a new issue.

| Benchmarks | Windows | Linux | (L - W)/W 
| --- | --- | --- | --- 
| Serialize.SerializeJsonNetBinary | 378 | 396 | 4.76%
| Serialize.SerializeDataContractJson | 374 | 386 | 3.21%
| Serialize.SerializeJsonNet | 298 | 323 | 8.39%
| Serialize.SerializeDataContract | 279 | 303 | 8.60%
