### ISSUE TITLE
CoreRun tries to execute .exe from incorrect path.

### ISSUE THREAD

**Issue by myungjoo** [dotnet/coreclr#5631]
This was tested and observed at both ARM/Linux and x64/Linux.

Reproduction
- Install coreclr & corefx at directory `/A/`
- Install `a.exe` at directory `/B/`
- Create another `a.exe` (different from `/B/a.exe`) at `/A/` (for a more dramatic failure, create a null file, `/A/a.exe`)
- At `/A/`, run `./corerun /B/a.exe`

Expected
- The file `/B/a.exe` is executed.

Result
- The file `/A/a.exe` is executed.

Note that if `/A/a.exe` does not exist, it properly executed `B/a.exe`.

**Comment by mkborg** [comment]
I had similar issue.

I was playing with 'HelloWord' example trying to create some test but it was not working. Finally I took original 'HelloWord' example and just changed the message but on launch it printed **original** unmodified message. I even tried to change file name but it didn't help.

It printed new message only when I changed name of the 'class' in my modified 'HelloWord' example.

It helped me to find that I had 'HelloWord' application binary in directory with 'corerun'.

I suppose it worked in the following way: when I launched `corerun_dir/corerun my_dir/my_app.exe`, 'corerun' extracted name of the 'class' from my binary and started to load 'class' with than name but instead of using explicit path (my_dir/my_app.exe) specified in command line 'corerun' started to search for file with necessary 'class' name and found alternative file with the same 'class' name  in its own directory (corerun_dir).

**Comment by myungjoo** [comment]
`HRESULT AssemblyBinder::BindByTpaList(...)`uses `simpleName` that extracts the filename from the full path, which later makes the `fileName` at line 1362 of the same function, to refer `/A/a.exe`, not `/B/a.exe`. 

This is a logic error in ``HRESULT AssemblyBinder::BindByTpaList`.

**Comment by myungjoo** [comment]
A fix is being implemented by enforcing CLRPrivBinderCoreCLR::Bind()'s call to AssemblyBinder::BindAssembly() explicitly state that it MUST find the assembly in the given path.

**Comment by myungjoo** [comment]
It look like the current commit of CoreCLR has this issue fixed.
I'll verify if it's completely gone and close this afterwards.

**Comment by danmosemsft** [comment]
The linked PR had some issues and wasn't completed, so this issu remains up for grabs.
