### ISSUE TITLE
Profiling API Documentation: ELT APIs (SetEnterLeaveFunctionHooks*, etc.) do not work on MacOSX

### ISSUE THREAD

**Issue by mjsabby** [dotnet/coreclr#5660]
I couldn't find any evidence of the stubs that are required for ELT to function properly in Linux and/or MacOSX x64 

It's best if we document that this can/will fail the target process spectacularly, i.e. the profiler author must not pass `COR_PRF_MONITOR_ENTERLEAVE` to SetEventMask. Particularly because SetEventMask may succeed (I vaguely remember it did in fact succeed in my testing) and that the program from then on may be exhibiting undefined behavior.

I'll open a separate issue to track the fact this work needs to happen for our currently supported platforms.

**Comment by mjsabby** [comment]
cc @noahfalk @kspawa

**Comment by mjsabby** [comment]
Actually the JIT issue is being tracked as #2927

**Comment by noahfalk** [comment]
Thanks for the heads up!

@kspawa commented in #445 that we only support a small subset of the flags so far. She was planning to get that statement of support posted as a doc so it will be a little more obvious... I have no expectation that all our profiler devs are going to read every comment on every issue with profiler in the title : )

Unfortunately one of the dangers of letting devs use APIs before we've thoroughly tested them is that you can accidentally wander into failures like this one. We are hoping on balance the danger is a reasonable cost to pay for that freedom to explore, but certainly I want to keep an eye on it and feedback is encouraged. If it causes too much trouble we can be more aggresive about blocking profiler APIs until testing has proven they are functional on .Net Core.

**Comment by lt72** [comment]
This work item requires at least a few preliminary explorations and activities
- [ ] frame exactly what is working and what is not working for profiling on *MacOS*
- [ ] define a target and add appropriate test set
- [ ] implement missing features as needed, ELT callbacks being one of them

**Comment by sywhang** [comment]
I am in progress of testing the profiler APIs on macOS. Here is a list of the tests in the process of being brought up:
- [ ] CEE
- [ ] LTS
- [ ] ReJIT
- [ ] ELT Hooks 
- [ ] InjectMetaData
- [ ] Unit
- [ ] JIT

**Comment by sywhang** [comment]
Internal testing revealed an issue with ReJIT on MacOS, but apart from that, the ELT APIs are fully functional and have been tested on macOS. The change that enabled this is #12603, which enabled it for AMD64/Linux, but macOS is thankfully only on x64 architecture so this enabled the ELT callbacks on macOS as well. 

I will follow up with a PR to update the Profiler API documentation on this repo to update this recent progress.

**Comment by dotnetjt** [comment]
@sywhang  - any code sample for using the ELT callbacks? I'm not great with assembler....

**Comment by sywhang** [comment]
Hey @dotnetjt,

Here is a sample profiler that uses the Enter/Leave callbacks: https://github.com/Microsoft/clr-samples/tree/master/ProfilingAPI/ReJITEnterLeaveHooks.

**Comment by noahfalk** [comment]
The sample you mentioned is using ReJIT to simulate the same effect as ELT, but it doesn't use the ELT APIs actually. Unfortunately I'm not aware of a good sample for ELT itself, but using ReJIT to accomplish the same task might still work well for you if you want to stay clear of writing your own assembly.

**Comment by sywhang** [comment]
https://github.com/dotnet/coreclr/pull/15659 updated the outdated docs. Closing the issue.

**Comment by tig66208** [comment]
Yes @noahfalk you are right. But it's ok, I figured it out using the ELT hooks.

The challenge is that I maintain a profiler that has been based on Windows only for a long time. There were plenty of examples to go off of for that, and MASM integrated with VS/MSBUILD was the way to go.

In the examples given to me prior on different issues in this repo ("look at asmhelpers.S"), there is a huge gap: I don't know the coreclr repo / build process well. The example made sense on paper, but I've been used to using MASM on Windows, and took me a lot of trial, error, and digging to realize that the file suggested for reference was using intel syntax with GCC (rather than NASM or GAS; not to mention this sample profiler above referenced uses clang). But, I now have it working.

All that to say; for those of us that have built tooling around the APIs provided in the original, full framework, the tools were at least familiar and we could make it work. In this new world, some of us are having to learn a lot of new things - and I think this entire repo could use a lot more "how to" for people like myself I can pull it and build it..... and use the output. But the build process / tool chain / test projects, etc are a steep learning curve. I've learned a lot more from 3rd parties / bloggers than I have from the project itself. I think you'd have a lot more people contributing if they understood these things better - .net developers are fairly stuck in a certain ecosystem, and getting them to contribute to something where they have little to no knowledge of the tooling, etc, is difficult.

**Comment by mattwarren** [comment]
@noahfalk 

> Unfortunately I'm not aware of a good sample for ELT itself,

What about the [CLR Profiler sample](https://github.com/MicrosoftArchive/clrprofiler/tree/master/CLRProfiler/) (previously [on CodePlex](http://clrprofiler.codeplex.com/SourceControl/list/changesets?branch=master)) or is that too out of date?

After a quick glance is *seems* to have the ELT hooks implemented, i.e.

- https://github.com/MicrosoftArchive/clrprofiler/tree/master/CLRProfiler/profilerOBJ/amd64
- https://github.com/MicrosoftArchive/clrprofiler/blob/master/CLRProfiler/profilerOBJ/ProfilerCallback.cpp#L173-L188

**Comment by noahfalk** [comment]
@mattwarren - Thanks for the reminder, I had completely forgotten about that old fellow. If someone needed a windows sample, that seems like a fine one!

**Comment by noahfalk** [comment]
@tig66208 - Thanks for the feedback. It seems like you are putting together lack of sample/docs for using the profiler APIs with lack of sample/docs for engineering in the coreclr repo itself? I have no doubt both of those areas could use work, but satisfying one doesn't necessarily seem like it would help you do the other. In any case the best things I can think of that would improve that would be opening issues on specific docs/samples/tutorials that would be most helpful to you if they existed and/or contributing back content/links that you found helpful if you wound up learning something on your own. I'll certainly admit that for profiling the team at Microsoft is prioritizing getting everything functional and tested above generating docs and samples. I know probably not what you wanted to hear, but just telling it how it is : )

**Comment by tig66208** [comment]
@noahfalk yes, you are right... kind of two concerns merged together. And, you are also right this probably isn't the place to hang those cards. Sorry, just was venting a bit!

**Comment by noahfalk** [comment]
@tig66208 - no worries at all - its good for us to hear that stuff!

**Comment by dotnetjt** [comment]
Hey @noahfalk I've circled back to the issue I had originally here with being able to produce the assembly. Wondering if you might have a few minutes to chat with me about it without cluttering up this repo with an issue that isn't with the coreclr itself.

**Comment by noahfalk** [comment]
@roterdam - could you include a link to the MicrosoftArchive code you are referring to? 

I've been looking into the code for this and seeing a variety of inconsistencies between docs, comments, and implementations (#19023). If you are referring specifically to x64 on Windows, the current implementation of the JIT appears to restore all the argument registers after returning from the FunctionEnter callback which would mask mistakes if ProfileEnter itself didn't do the restore. I wouldn't recommend relying on that undocumented implementation behavior, but that is likely why it works at the moment.

**Comment by sywhang** [comment]
FYI, I believe the MicrosoftArchive code @roterdam is referring to is this, which is x64 on Windows: https://github.com/MicrosoftArchive/clrprofiler/blob/master/CLRProfiler/profilerOBJ/amd64/asmhelpers.asm#L123 (Please correct me if I'm wrong @roterdam!)

**Comment by noahfalk** [comment]
Thanks @sywhang! Yeah, that sample doesn't appear to conform to the MSDN documentation requirements, but it probably works because its taking advantage of undocumented runtime behavior. Given that its Microsoft's old sample I think we'd have to honor it and preserve the undocumented behavior as-is, just be careful assuming the same things work on different architectures/OS. I'm trying to drive a bit more clarity on it right now.
