### ISSUE TITLE
Seg fault in System.Collections.Immutable.Tests on CentOS 7.1

### ISSUE THREAD

**Issue by stephentoub** [dotnet/coreclr#5687]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/centos7.1_release_prtest/115/consoleText

```
Discovering: System.Collections.Immutable.Tests
  Discovered:  System.Collections.Immutable.Tests
  Starting:    System.Collections.Immutable.Tests
  /mnt/resource/j/workspace/dotnet_corefx/master/centos7.1_release_prtest/bin/tests/AnyOS.AnyCPU.Release/System.Collections.Immutable.Tests/netcoreapp1.0/RunTests.sh: line 215: 59023 Segmentation fault      ./corerun xunit.console.netcore.exe System.Collections.Immutable.Tests.dll -xml testResults.xml -notrait Benchmark=true -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing -notrait category=nonlinuxtests
  Finished running tests. End time=15:51:23. Return value was 139
```

**Comment by stephentoub** [comment]
Again here:
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/centos7.1_release_prtest/116/consoleText

**Comment by sergiy-k** [comment]
Hi @stephentoub, I think this was addressed by one of the stress fixes that were checked during the last couple days. I've been running stress on multiple machines and stress testing did not hit the issue. I have also run more than 40 CoreFX test jobs in CI on Centos7.1 (debug and release) and none of them failed due to this error. I'm going to move this to v1.1 for tracking purposes. Please let me know if you see this issue again.

**Comment by gkhanna79** [comment]
I wonder if this was due to the same problem as https://github.com/dotnet/coreclr/issues/5672.

CC @janvorli

**Comment by adityamandaleeka** [comment]
See https://github.com/dotnet/coreclr/issues/6283#issuecomment-246041964

**Comment by adityamandaleeka** [comment]
This issue was marked as 1.1.0, but I moved it to 1.2.0 since there's nothing actionable for us to do now. The fix in the kernel needs to be released and CI machines should be updated at that point. For now, the CI machines have been running with THP disabled as a workaround and I haven't heard of this crash occurring since then.

**Comment by danmosemsft** [comment]
I am going to close this since it's not really tracking work -- this test hasn't failed since, the workaround works, and the CI machines will get updated inevitably in due course. Do reopen if I misunderstand
