### ISSUE TITLE
Generate symbol packages for CoreCLR binaries

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#5832]
These are required for uploading symbols to myget for master branch builds. Once built:

1) please work with @wtgodbe to generate them in the build pipeline and push them on myget feed
2) please work with @dagood to ensure they are also indexed on internal symbol server.

**Comment by dagood** [comment]
In CoreFX the packaging tasks from buildtools automatically find the PDBs by looking in the same folder, but that doesn't work in CoreCLR since PDBs are in a subdirectory. I think the simplest way to create these is to do it like the xplat symbol packages: https://github.com/dotnet/coreclr/blob/master/src/.nuget/Microsoft.NETCore.Runtime.CoreCLR/osx/Microsoft.NETCore.Runtime.CoreCLR.pkgproj

**Comment by tzwlai** [comment]
Just want to make it clear that this is specifically for Windows.

**Comment by mikem8361** [comment]
Still need to do the TFS side for ARM.

**Comment by mikem8361** [comment]
TFS changeset #1628605
