### ISSUE TITLE
Discussion: Stack only types

### ISSUE THREAD

**Issue by omariom** [dotnet/coreclr#5860]
Now that we have [Span](https://github.com/dotnet/coreclr/issues/5851) - another ByRefLike type - should the idea of  stack only types be extended to other structs? It would allow us to encapsulate `ref`s and Spans.
It could be like this:
If struct A has a field of _stack-only_ type it makes the struct itself _stack-only_. The same all the way up.

``` C#
struct A
{
    private ref Message message; // or Span<byte>
}

struct B
{
    private A a;
}
```

@KrzysztofCwalina  @jkotas

**Comment by MI3Guy** [comment]
This would be great because it would allow for a lot that is currently impossible (without resorting to pointers). Especially when related to closures.

**Comment by jaredpar** [comment]
The design I think makes the most sense here is to:

1. Add `ref` fields to the language 
2. Generalize the notion of `ref types` to include both `ref` locals, parameters and types which have ref fields. 

The generalized notion of `ref types` is more applicable here because they actually have a number of restrictions, not just stack only:

- Stack only: heap doesn't allow interior pointers (ref fields).
- Can't be used as generic arguments: if they could then they could trivially be escaped into the heap.
- Can't be used as pointer types.

**Comment by omariom** [comment]
Will it allow to create `Span<T>` fields?

**Comment by jaredpar** [comment]
@omariom yes in the cases where the containing type is a `struct` itself.  It's not possible to create `ref type` fields in a `class` type.  

There are some mitigation for `Span<T>` to allow it to be stored as fields of a `class` type.  That would be specific to `Span<T>` though and not a general purpose feature for all `ref types`.

**Comment by MI3Guy** [comment]
I think it would be far better to allow ref types as generic types. It would require a constraint to be added that would restrict its usage. This would be much more useful than banning them from generics.

**Comment by omariom** [comment]
```C#
```

**Comment by jkotas** [comment]
This materialized as ref-like types: https://github.com/dotnet/csharplang/blob/master/proposals/span-safety.md
