### ISSUE TITLE
High CPU in Monitor.Enter when the system clock interval is set to a low value on Windows

### ISSUE THREAD

**Issue by ccurrens** [dotnet/coreclr#5927]
Affects: CoreCLR and Full .NET Framework desktop

It appears that the smaller the system timer resolution, the more CPU is spent spinning when trying to acquire a contended lock via `Monitor*.Enter` methods. In multiple traces, I've seen absurdly high amounts of CPU being used by `AwareLock::Contention`[1]. It also looks like as the number of processors increase, the overall performance decreases when there are many threads contending for a lock[2].

Often times changes to the system timer resolution are outside of a program's control. In fact, most WPF programs, including Visual Studio lower the timer resolution to 1ms. If there are locks with heavy contention in any managed program on the machine, it will cause unnecessary CPU spikes. 

I wrote a test program[3] that does an admittedly trivial amount of work for an indefinite period of time, but shows how the amount of CPU increases as the system timer resolution decreases. I tested this on a WS2012R2 machine that has 24 logical cores (HT, 12 physical):

![timer_resolution_cpu](https://cloud.githubusercontent.com/assets/1033555/16276317/ab33551c-3862-11e6-94b7-7ee07acebef0.png)

If I change to use `SpinLock` instead of `Monitor`, the cpu drops to around 9-10% instead of hovering at 95-100%.

I've found that modifying the `Spin*` configuration values decreases the maximum CPU used in my test program by a significant amount. At 1ms timer resolution, the program uses 95% CPU. When changing the spin configuration values to match those of the managed `SpinLock` struct, it drops down to around 10% usage:

```
SET COMPlus_SpinLimitProcFactor=0x100
SET COMPlus_SpinLimitProcCap=0xC (# of processors on machine)
```

I don't exactly know why changes to the timer resolution affects the `AwareLock` as much as it does, whereas the managed `SpinLock` doesn't have the same problem. I know that they accomplish spinning in different ways, but I haven't had time to dig into it further.

---

[1] https://github.com/dotnet/coreclr/blob/775003a4c72f0acc37eab84628fcef541533ba4e/src/vm/syncblk.cpp#L3289

[2] [https://github.com/dotnet/coreclr/blob/775003a4c72f0acc37eab84628fcef541533ba4e/src/vm/syncblk.h#L166](https://github.com/dotnet/coreclr/blob/775003a4c72f0acc37eab84628fcef541533ba4e/src/vm/syncblk.h#L166)

[3] [https://gist.github.com/ccurrens/cda696c7f931fc0b1db6320b07bf2575](https://gist.github.com/ccurrens/cda696c7f931fc0b1db6320b07bf2575)

**Comment by MattWhilden** [comment]
@ericeil

**Comment by kouvel** [comment]
The issue here is that in the test code, the amount of time for which the lock is taken is dependent on the system clock resolution, due to the use of DateTime.UtcNow to measure a duration of 1 ms. When the resolution is set to 1 ms, that loop will wait for approximately 1 ms and the lock is held for a short duration, which means it keeps threads spinning for the lock, hence higher CPU usage. When the resolution is set to 15 ms, that loop waits for approximately 15 ms and the lock is held for a longer duration, which means it allows threads waiting for the lock to go into a wait state more frequently, hence the lower CPU usage.

If I change the use of DateTime.UtcNow to use Stopwatch instead, which uses the high-resolution timer, the CPU is near 100% regardless of the system clock resolution.

That said, the monitor in my opinion spins far more than it should, but look into that as part of #6144.

Closing, please reactivate if you believe there is still a problem with the monitor with respect to the system clock resolution.
