### ISSUE TITLE
Displace build dependency on perl, python etc. by shell or javascript

### ISSUE THREAD

**Issue by ghost** [dotnet/coreclr#5969]
We can pretty much do all this stuff in native scripts (ps1 & sh) or fancy JavaScript (node.js, which is installed as part of VS2015, and easily script-able to obtain the local exe from their dist https://nodejs.org/dist/latest/ or https://nodejs.org/en/download/package-manager/):

``` sh
coreclr/build.[sh/ps1]
        |
        # wgets node in coreclr/tools and exports coreclr/tools to PATH,
        # if node isn't already present in PATH
        |
        # then calls
        |
        node coreclr/build.js src test [other args] # all written in one language
```

This will remove the dependency on all other kinds of language runtimes to be installed on dev / build machines.

**Comment by myungjoo** [comment]
Why do we need to replace python scripts with javascripts? (Perl is not "required" for build anyway although there are perl scripts in the source repository as utilities) What's the benefit of it?

Anyway, adding more degrees of out-of-repo dependencies (being required/able to download ever-changing packages to build) makes it more unstable to build for isolated build servers, usually for embedded devices, or OS releases.

(because of this, it'd be better if we could build CoreCLR WITHOUT fetching prebuilt binaries, which makes it completely independent from the network. Depending on other "installed" packages is ok because it is easily controllable and deterministic.)

**Comment by jasonwilliams200OK** [comment]
>Anyway, adding more degrees of out-of-repo dependencies

This is exactly the opposite of what I am proposing here! Try reading again..

**Comment by parjong** [comment]
I think that @myungjoo concerns the use of ``npm``, which definitely inreases the degree of out-of-repo dependencies.

Anyway, I agreed with @myungjoo. IMHO, it will take too much cost to rewrite all the scripts in JavaScript, compared with its benefit, and thus the use of python (which is already in use) would be better.

**Comment by jasonwilliams200OK** [comment]
@parjong,

> it will take too much cost to rewrite all the scripts in JavaScript

Care to elaborate *all*? There are only few (9?) python files at the moment in coreclr repo, which can be written in native shell (which is the *F I R S T* preference in my proposal). Besides I can write it without incurring any cost on you, so don't you worry about it. ;)

While native shell which is :heart:++, JavaScript is the second option in this proposal

> concerns the use of npm, which definitely inreases the degree of out-of-repo dependencies.

What npm issue are you referring to? So if i need to use pip in python to consume dependent module, how would it not bring the same amount of complexity? We can write the JS code without any dependency and use of npm. If you have build.py without any dependency and you execute it like `python build`, you can have build.js and execute it like `node build`.


To why would we even consider using JS over Py (and Perl) is because:

1. py2 script doesn't always work with py3 and vice-versa (and py4 is going to once again bring about the breaking change).
2. JS syntactically share the same c-family of languages as c++/c#, which is familiar to this repo.
3. JavaScript with its own share of issues is the only language in the world which is supported from server, networks, browsers -> everywhere!

**Comment by parjong** [comment]
@jasonwilliams20OK Oh, that is great. I don't care underlaying script language if it doesn't require any external dependencies from network. My concern was that the build script written in JS will depends on some remote resources (which is common in JS).

**Comment by RussKeldorph** [comment]
At one point, the high level plan was to use a few native scripts (one per shell--cmd, bash, ...) which did the minimum work to bootstrap .NET CLI and use that for everything else.  Obviously, we're not there yet, and Python became a semi-official stand-in, though even then we don't have as much discipline as we probably should.

I think unifying the way we run tests between Windows and Unix is more urgent and is related (runtest.sh).  I can't say exactly when we'll clean up these build dependencies and get a consistent story, but I certainly hope it happens sooner rather than later.

@gkhanna79 @ramarag @russellhadley @jashook
