### ISSUE TITLE
test build has a zillion build warnings

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#6022]
Most (16352 in a default x64 debug build) are of the form:

```
Your project is not referencing the ".NETCoreApp,Version=v1.0" framework. Add a reference to ".NETCoreApp,Version=v1.0" in the "frameworks" section of your project.json, and then re-run NuGet restore.
```

**Comment by RussKeldorph** [comment]
#5784 related

**Comment by jasonwilliams200OK** [comment]
I think the fix is to add:

```json
    "Microsoft.DotNet.BuildTools.TestSuite": "1.0.0-prerelease-00520-02",
    "test-runtime": {
      "target": "project",
      "exclude": "compile"
    },
```

in project.json dependency of each test project.

Similar issue in CoreFX: https://github.com/dotnet/corefx/issues/9464 (happens only in few test projects where `test-runtime` is missing in project.json)

**Comment by dagood** [comment]
This should be fixed by https://github.com/dotnet/coreclr/pull/6479, which changed test dependencies from `dnxcore50` to `netcoreapp1.0`. (It does add a test-runtime (test_runtime) project and dependencies too, but I don't think that was the direct cause of the errors.) There are still some other warnings, but not zillions anymore.

**Comment by mazong1123** [comment]
This issue still exists. Do we have any plan to fix it?

**Comment by dagood** [comment]
@mazong1123 I think this has been fixed in https://github.com/dotnet/coreclr/issues/7626. This 6022 issue was resolved for a while, but it was just never closed and eventually regressed. Closing now--let me know if you're still seeing a ton of warnings and I can reopen #7626 if it matches the warnings you're seeing.
