### ISSUE TITLE
System.Threading.Timer roots itself inconsistently

### ISSUE THREAD

**Issue by GSPP** [dotnet/coreclr#6055]
I just found this on Stack Overflow: [C# Timers and Garbage Collection](http://stackoverflow.com/questions/37681583/c-sharp-timers-and-garbage-collection) and I thought I'd report it here as a public service.

It seems that a `System.Threading.Timer` only sometimes roots itself.

I propose:
1. Make `System.Threading.Timer` always root itself. A timer logically is an independent agent generating events. It's just like a `Thread` or a `Task` which do not need to be rooted either. A timer should be able to exist on its own.
2. Document this behavior so that it can be relied upon. I don't see why this would ever be changed. In particular it can never be changed for compatibility reasons so we might as well document it.
3. Decide, what happens with disabled (but not disposed) timers. Probably, they should be consistently unrooted.

The comments by `Hans Passant` seem spot on.

**Comment by kouvel** [comment]
The `Timer` instance (more importantly, the `TimerHolder` instance) is rooted when the `Timer(TimerCallback)` overload is used because the the Timer instance is stored as the state in the corresponding `TimerQueueTimer` instance to pass into the callback as its state object.

It does look like it would be a breaking change to not root it, but fixing this makes me a bit uncomfortable because it would become even easier to leak timers by forgetting to call `Dispose`, and existing usage that relies (perhaps unintentionally) on the timer automatically unregistering itself by unreferencing the timer object would now leak the timer instead.

@stephentoub, thoughts?

**Comment by kouvel** [comment]
That said, it probably would have made sense to always root the timer when it's registered to tick

**Comment by stephentoub** [comment]
I'm sympathetic to the request, and agree it should have been designed to always root itself.  You can see, for example, that Task.Delay uses the non-rooting ctor but then uses an internal helper to keep the timer rooted until it fires (or is disposed): https://source.dot.net/#System.Private.CoreLib/src/System/Threading/Tasks/Task.cs,5424

However, making it consistent by changing the existing behavior will almost certainly cause problems for existing code.  I know I've written code in the past that uses the Timer(TimerCallback) ctor specifically to get the rooting behavior, and code in the past that uses the Timer(TimerCallback, object, int, int) ctor specifically to get the non-rooting behavior.  I also remember that when @ericeil overhauled Timer for .NET 4 (I think that was the version, maybe .NET 4.5), he went out of his way to maintain this behavior, due to compat concerns.

**Comment by kouvel** [comment]
It looks like we can't do anything about this, closing

**Comment by GSPP** [comment]
I understand. Maybe we can make rooting explicit in the API by adding some options ctor that takes a bool of flags. Or, it could be a property on the object `bool KeepInstanceAlive`. That way we as users can adopt a new self-documenting pattern `new Timer(..., keepInstanceAlive: true)`.
