### ISSUE TITLE
Integrate Debugger Test run within CI and Pipeline infrastructure

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#6165]
Currently, debugger tests run against a day old CoreCLR/CoreFX for their validation, in their own repo. We should look into integrating it closer to the product to identify regressions and status sooner.

CC @sergiy-k

**Comment by lt72** [comment]
We will complete early this in 1.2

**Comment by alsemenn** [comment]
Here is a plan to solve this:

- [ ] Check-in Zhicheng changes for debugger tests
   - [ ] Check that build tasks are not rebuilding debuggee each time.
- [ ] Modify debugger tests
   - [ ] Our runscripts are generated by the RunScriptConfig tool during the build.
   - [ ] Allow to build all debbugees upfront.
- [ ] Figure out how tests are enabled/disabled and run in CoreClr Repo so we can disable debugger tests on per-test basis.
- [ ] Check-in changes to allow downloading of debugger tests repo
   - [ ] Disable running.
   - [ ] Disable downloading (temporary before allowing for run)
   - [ ] Use small C# instead of scripts
   - [ ] Figure out how not to mess with the Windows incremental test running.
      - [ ] Look at how other tests are picking up the right Clr.
- [ ] Separate downloading and building of debugger tests repo from it’s running.
- [ ] Modify CoreClr scripts to build all the debugger tests upfront.
- [ ] Run all the tests in CoreClr
- [ ] Update our CI to publish newer versions of debuggertests repo

**Comment by gkhanna79** [comment]
@lt72 Is this happening for 2.0? If not, can you please move this to future?

**Comment by lt72** [comment]
Updated milestone according to current planning ==> 2.1

**Comment by lt72** [comment]
Completed.
