### ISSUE TITLE
Members in RuntimeHelpers are optimised away

### ISSUE THREAD

**Issue by dpen2000** [dotnet/coreclr#6250]
Some methods in RuntimeHelpers are defined in coreclr but are missing from final assemblies.
For instance, PrepareConstrainedRegions is defined here (as public): https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Runtime/CompilerServices/RuntimeHelpers.cs#L211
but is missing when you try and use it in a coreclr app.

Presumably, this is because these methods only call other methods so get optimised away. This is a regression from .net framework where these did show up.

**Comment by mikedn** [comment]
> Presumably, this is because these methods only call other methods so get optimised away. This is a regression from .net framework where these did show up.

It has nothing to do with optimizations. It's just that .NET Core is a subset of .NET Framework and as such lacks certain features, constrained execution in this case.

**Comment by gkhanna79** [comment]
@dpen2000 Do you have any outstanding questions on this issue?

**Comment by dpen2000** [comment]
@gkhanna79 I'm still intrigued to know how this member gets excluded from built assembly considering it's defined as public here.

**Comment by mikedn** [comment]
> I'm still intrigued to know how this member gets excluded from built assembly considering it's defined as public here.

There used to be a tool called bclrewriter that was removing stuff from the System.Private.CoreLib assembly generated by the compiler. That's no longer the case, whatever code was removed by that tool is now removed from the source code itself.

But it looks like your problem is slightly different as `PrepareConstrainedRegions` was and still is present in System.Private.CoreLib. What really happens is that when you compile a .NET Core app (and even a .NET Framework app) you're not referencing the real assemblies (e.g. System.Private.CoreLib.dll) but some special assemblies called "reference assemblies" (e.g [System.Runtime.dll](https://github.com/dotnet/corefx/blob/master/src/System.Runtime/ref/System.Runtime.cs)). If a type/method doesn't exist in the reference assembly then it's not part of .NET Core.

**Comment by mikedn** [comment]
And if you're looking at the history of System.Runtime.cs file in corefx you'll see that PrepareConstrainedRegions was recently added back, probably for .NET Core 2.0 - https://github.com/dotnet/corefx/pull/11930

**Comment by dpen2000** [comment]
Ah interesting. Thanks
