### ISSUE TITLE
The results of "==" and "Equals" are not consistent in TimeZoneInfo class.

### ISSUE THREAD

**Issue by RickyLin** [dotnet/coreclr#6292]
See the code below:

```csharp
TimeZoneInfo t1 = TimeZoneInfo.Local; // my "Local" is "China Standard Time"
TimeZoneInfo t2 = TimeZoneInfo.FindSystemTimeZoneById("China Standard Time");
Console.WriteLine("t1 == t2 ? " +  (t1 == t2)); 
Console.WriteLine("t1.Equals(t2) ? " + t1.Equals(t2));
```

This is the output:

```
t1 == t2 ? False
t1.Equals(t2) ? True
```

The result is not consistent, I think `t1 == t2` should also be `true`.

**Comment by jasonwilliams200OK** [comment]
The output you are getting is correct. `==` and `Equals` are two different things.

The operator `==` calls [ReferenceEquals](https://msdn.microsoft.com/en-us/library/system.object.referenceequals.aspx) method on the objects of reference types; `class` (but not `struct`). That means objects being compared are same: produced by one [`new` operator](https://msdn.microsoft.com/en-us/library/system.object.referenceequals.aspx#Anchor_1) call. Check this out:

```c#
using System;

// TimeZoneInfo is class

TimeZoneInfo t1 = TimeZoneInfo.FindSystemTimeZoneById("China Standard Time");
TimeZoneInfo t2 = TimeZoneInfo.FindSystemTimeZoneById("China Standard Time");

Print(t1 == t2)  // False
```

This is because `FindSystemTimeZoneById` is calling `new TimeZoneInfo` everytime and returns a different object and does not cache anything.

For value types (`struct`), `==` compares the content of the objects. For example

```c#
using System.Drawing;

// Point is struct

Point t1 = new Point(42, 12);
Point t2 = new Point(42, 12);

Print(t1 == t2)  // True
```

However, in case of `Equals` method (which is defined as `virtual` in base class Object), if the derived type (`class` or `struct` doesn't matter) has it overriden such as TimeZoneInfo https://github.com/dotnet/coreclr/blob/fc728f2/src/mscorlib/src/System/TimeZoneInfo.cs#L901-L917, then the overriden implementation is called where user can implement their own way of checking the equality.

**Comment by RickyLin** [comment]
That makes sense but not intuitive.

[Object.Equals Method (Object)](https://msdn.microsoft.com/en-us/library/bsc2ak47(v=vs.110).aspx) say:

>If your programming language supports operator overloading and you overload the equality operator for a given type, you must also override the Equals(Object) method to return the same result as the equality operator. This helps ensure that class library code that uses Equals (such as ArrayList and Hashtable) behaves in a manner that is consistent with the way the equality operator is used by application code.

so if I overload the equality operator, I should also override `Equals` method, but if I override the `Equals` method, I can leave equality operator as-is? Most of the time I (probably most developers) use `==` other than `Equals`, if the result of `==` and `Equals` are different, I have to consider using `Equals` all the time from now on instead of `==` to avoid the potential differences like this.

**Comment by jasonwilliams200OK** [comment]
Yeah, differentiating between reference (`class`) and value (`struct`) types generally is bit tricky for devs coming from different language background. Check this out https://blogs.msdn.microsoft.com/ericlippert/2009/04/09/double-your-dispatch-double-your-fun/

**Comment by jamesqo** [comment]
Maybe you could [submit an API proposal](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md) to CoreFX for overloading `==` on `TimeZoneInfo` (and possibly other related types). :)

**Comment by RickyLin** [comment]
I closed this issue because [the related issue](https://github.com/dotnet/corefx/issues/10114) was closed.
