### ISSUE TITLE
RyuJIT can't detect that certain expressions are loop invariant

### ISSUE THREAD

**Issue by mikedn** [dotnet/coreclr#6303]
Consider the following example:
```C#
using System;
using System.Runtime.CompilerServices;

class Program {
    [MethodImpl(MethodImplOptions.NoInlining)]
    static void use(int x) {
    }
    static void Main() {
        var r = new Random();
        int x = r.Next();
        int y = r.Next();
        int z = r.Next();

        for (int i = 0; i < 10; i++)
            use(x * y * z);
    }
}
```
The `x*y*z` expression is invariant but it is not hoisted:
```
G_M45811_IG03:
       8BCF                 mov      ecx, edi
       0FAFCB               imul     ecx, ebx
       0FAFCE               imul     ecx, esi
       E892FBFFFF           call     Program:use(int)
       41FFC6               inc      r14d
       4183FE0A             cmp      r14d, 10
       7CEA                 jl       SHORT G_M45811_IG03
```

As far as I can tell this happens because the JIT can't detect that `x`, `y` and `z` themselves are invariant. There doesn't seem to exist a VN function application for `Random.Next` calls and without that there seems to be no way to tell where a particular VN was defined, outside the loop in this case.

**Comment by russellhadley** [comment]
I'll take a look.  This just seems weird.

**Comment by mikedn** [comment]
See `optVNIsLoopInvariant` in optimizer.cpp, it returns false for `x` & co. 

It does work if the loop is extracted to a separate method in which case `x` & co. become method args and then they have an associated `VNF_InitVal(constant)`. That constant isn't a true constant, it's the index of the lclVar argument. Weird but it's good enough to make all method arguments loop invariant as they should be. But for true local variables there's nothing like this, they probably never be considered invariant.

**Comment by JosephTremoulet** [comment]
It seems the issue is not specifically that `x` & co are locals, but rather that their reaching definitions are function calls.  Changing them to another expression, e.g. like so:

```C#
        [MethodImpl(MethodImplOptions.NoInlining)]
        static void Foo(int a, int b, int n)
        {
            int x = a + 5;
            int y = b + 7;

            for(int i = 0; i < n; ++i)
            {
                use(x * y);
            }
        }
```

does indeed result in the mul getting hoisted.

The code in `fgValueNumberCall` gives each call a new unique `VNForExpr()` value number (which indicates that the call is value-equal to itself and nothing else).  The `VNForExpr` value numbers don't have any internal structure, and thus don't use backing memory, which is good for memory usage but means they don't have a place to record the position of the callsite (which we need to tell if the call is in the loop or not).

I took a look at short-circuiting `optHoistLoopExprsForTree` to consider a `lclVar` hoistable (regardless of its value number) if it has an SSA def outside the loop, but that proved fruitless since the check on the multiply of the two `lclVar`s (which is what we really want to hoist) checks the multiply's value-number, which recursively checks the call value numbers (and in the general case the value number expression tree and IR expression tree might not have the same shape).

So I'm looking into adding a `VNF_` operator for calls that will give a place to record the SSA heap def which can then be used to prove them loop-invariant.  My [current attempt](https://github.com/JosephTremoulet/coreclr/commit/aa2dc8dd7f87b86c0f1d30a2dcfc7245b7099976) is getting the testcase above, just now starting to test it on more code, assess diffs/tp, etc.

**Comment by mikedn** [comment]
> It seems the issue is not specifically that x & co are locals, but rather that their reaching definitions are function calls.

Not only calls, the same happens if they're fields:

```C#
int a, b, c;

static void Main()
{
    var p = new Program();
    int x = p.a;
    int y = p.b;
    int z = p.c;

    for (int i = 0; i < 10; i++)
        use(x * y * z);
}
```
Interestingly, it works fine for static fields.

**Comment by JosephTremoulet** [comment]
> Not only calls, the same happens if they're fields

That's interesting, I'll take a look.  It can hoist fields at least sometimes, as with this example:

```
    public class C
    {
        int f;
        int g;

        [MethodImpl(MethodImplOptions.NoInlining)]
        int Foo(int n)
        {
            int x = 0;
            for (int i = 0; i < n; ++i)
            {
                x += f;
                g = 2;
            }
            return x;
        }
```

so I guess it's not the value number on the ldfld per-se that's blocking your example.  Will dig in...

**Comment by benaadams** [comment]
> That's interesting, I'll take a look. It can hoist fields at least sometimes, as with this example:

Out of curiosity does it move `g = 2;` before or after the loop?

**Comment by mikedn** [comment]
Indeed, if I put that code in an instance method and access those fields via `this` then it works fine. But only up to a point:
```C#
for (int n = 0; n < 10; n++)
{
    int k = n + a;
    int l = n + b;

    for (int i = 0; i < 10; i++)
        use(k * l); // * not hoisted
}
```

**Comment by mikedn** [comment]
> Out of curiosity does it move g = 2; before or after the loop?

It does not move it.

**Comment by benaadams** [comment]
> > Out of curiosity does it move g = 2; before or after the loop?

> It does not move it.

Not sure what is hoisted then, unless it drops the loop entirely:
```csharp
int Foo(int n)
{
    int x = f * n;
    g = 2;
    return x;
}
```

**Comment by mikedn** [comment]
> Not sure what is hoisted then

The `f` field access.

**Comment by JosephTremoulet** [comment]
I looked into

```C#
    var p = new Program();
    int x = p.a;
    int y = p.b;
    int z = p.c;

    for (int i = 0; i < 10; i++)
        use(x * y * z);
```

The "new Program()" expression is a call-to-helper at the time of value numbering, and calls to helpers use a different codepath than the one I changed before (which affects non-helper calls).  If I [also change helper call handling](https://github.com/JosephTremoulet/coreclr/commit/eb778181bffd085b75256bc4bc58a91d7d1955c4) then we get this case too.

I'll take a look at

```c#
for (int n = 0; n < 10; n++)
{
    int k = n + a;
    int l = n + b;

    for (int i = 0; i < 10; i++)
        use(k * l); // * not hoisted
}
```

It might make more sense to allocate space to record a block number in `VNForExpr()`s than to expand value numbering's view of each relevant opcode...

**Comment by JosephTremoulet** [comment]
I should mention that the common theme is that you'd hope the test for loop-invariance would be happy once it finds a definition outside of the loop, but the code doesn't work that way because it's checking if the **value number** is invariant, and the value number expression tree doesn't have location annotations except for phis, so rather than being able to prove an intermediate node is outside the loop, it walks all the way to leaves/phis, effectively requiring the leaves to be constants or arguments.

The SSA graph of course records defs' positions, but we can't simply use SSA instead of value numbers for the invariance test since the SSA graph (currently) doesn't track heap dependencies.

Adding location info to all value numbers doesn't seem like a good way to go either, since you'd like equivalent expressions at different locations to share their value number.  But the *unique* `VNForExpr()` value numbers can't be the result of redundant computations in the first place, so annotating them with locations seems appropriate.  OTOH, recording more refined information for operators of interest (as I'm looking at doing for calls, which naturally are functions of the heap and so naturally would include the relevant heap def which is always a `VNF_HeapPhiDef` or "constant") seems a less radical change.

**Comment by JosephTremoulet** [comment]
Regarding

```c#
for (int n = 0; n < 10; n++)
{
    int k = n + a;
    int l = n + b;

    for (int i = 0; i < 10; i++)
        use(k * l); // * not hoisted
}
```

it turns out I was wrong when I said a " heap def ... is always a `VNF_HeapPhiDef` or 'constant'" -- in particular, in loops with "heap havoc" (i.e. some coarsely-modeled heap side-effect, as from a function call), the value number for the heap at the head of the loop is not a `VNF_HeapPhiDef`, but [rather](https://github.com/dotnet/coreclr/blob/3e6f64fc55703a3937704a52b583fb891969bd8f/src/jit/valuenum.cpp#L4519-L4528) one of these opaque `VNForExpr()` value numbers.  So, in this example, since the loads occur in the outer loop, which (transitively) contains the call to `use` that constitutes "heap havoc", the heap source of the loads in the value numbering is opaque and the `k * i` that is ultimately an expression of them is not considered invariant.

Interestingly, in straight-line code with heap mutations, there's [a trick](https://github.com/dotnet/coreclr/blob/3e6f64fc55703a3937704a52b583fb891969bd8f/src/jit/valuenum.cpp#L4655-L4656) to attach a block number by wrapping the opaque value in a unary phi.  If I apply the [same trick](https://github.com/dotnet/coreclr/commit/eec891b5b11cc318272f730be253f0fdb023301f) to the "heap havoc" loop heads, then we get the hoist as desired in this case.

It looks like the [same issue](https://github.com/dotnet/coreclr/blob/3e6f64fc55703a3937704a52b583fb891969bd8f/src/jit/valuenum.cpp#L4559-L4568) is present for loops that don't have "heap havoc" but do have multiple incoming forward edges.

All of this is further convincing me that attaching block ids to opaque VNs is worth looking into, so I'll start taking a stab at that...

**Comment by mikedn** [comment]
It will be interesting to see how much this improves code generation. As is now LICM doesn't do much, I did a diff with it disabled and it hoists loads and type initialization calls here and there. That said, it may turn out that there aren't many opportunities for this optimization anyway, at least in the framework code.
