### ISSUE TITLE
Question: How are global static variables found by the GC?

### ISSUE THREAD

**Issue by tomspilman** [dotnet/coreclr#6343]
I was using the GC stand alone from CoreCLR and looking to implement the equivalent of C# static member variables.

How does the VM normally handle static variables so that the GC doesn't immediately collect them?  Is there an API in the GC i am missing?

@Maoni0 ?

**Comment by Maoni0** [comment]
These are implemented as object arrays on LOH pointed to by GC handles. Take a look at AllocateObjRefPtrsInLargeTable in appdomain.* where they are allocated. Another way to look at it to see how this method: SystemDomain::EnumAllStaticGCRefs is implemented (it eventually calls Module::EnumRegularStaticGCRefs). It goes through the statics. GC already marks them via the handle table but when we are in server GC we use this because we want to have all threads mark statics if they can.

**Comment by tomspilman** [comment]
>These are implemented as object arrays on LOH pointed to by GC handles.

That makes sense now.

AllocateObjRefPtrsInLargeTable: https://github.com/dotnet/coreclr/blob/master/src/vm/appdomain.cpp#L1296
EnumAllStaticGCRefs: https://github.com/dotnet/coreclr/blob/master/src/vm/appdomain.cpp#L2632

Thanks Maoni!
