### ISSUE TITLE
[LSRA][RyuJit] Make untracked locals contained when possible.

### ISSUE THREAD

**Issue by sivarv** [dotnet/coreclr#6364]
For an untracked local that occurs on rhs of an assignment, LSRA creates two ref positions: a def and a use.  Right now LSRA supports reg optional Use positions.  When no reg is allocated to a reg optional Use position of such an untracked local, allocating a reg for def position of untracked local is not a must.  In fact it would lead to better code quality if we don't allocate a reg to its def position - because we will save load to a reg and spill  reg to a spill temp. In that case, the Use should directly use the value from the memory location of untracked local.

**Comment by CarolEidt** [comment]
The original title of this issue was "Support for reg optional def of an untracked local that occurs on rhs of an assignment when its use is marked as reg-optional and wasn't allocated a reg". However, in the case where an untracked local doesn't require a register, it should simply be marked as contained and never allocated a register.

**Comment by pgavlin** [comment]
@CarolEidt is this done? I know you did some work in this area recently.

**Comment by CarolEidt** [comment]
Yes, indeed. This should have been closed with #11878
