### ISSUE TITLE
LINQ tests in CoreFx segfault on non-Windows platforms

### ISSUE THREAD

**Issue by jhendrixMSFT** [dotnet/coreclr#6517]
In our official CoreFx builds the functional tests for LINQ segfault on non-Windows platforms.  Can somebody please investigate?  You can find more information in Mission Control.

https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster/type/test~2Ffunctional~2Fcli~2F/build/20160728.04/workItem/System.Linq.Parallel.Tests

Click the above link, then click on of the red boxes with OS name in it.  @MattGal can help with instructions on rerunning these tests.

**Comment by adityamandaleeka** [comment]
@MattGal 

Can you share a bit more about how these tests are run? I looked at a bunch of "Core Tests" runs on [this page](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster) and it appears that these tests are failing on every Release run on every non-Windows platform.

However, the System.Linq.Parallel.Tests tests that are running in Jenkins ([here, for example](http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/ubuntu14.04_release/lastCompletedBuild/testReport/System.Linq.Parallel.Tests/)) appear to be passing.

**Comment by MattGal** [comment]
@adityamandaleeka 
    In Helix, the tests run the same way that they run in Jenkins... build produces a runtests.sh file containing commands to copy over any additional dependencies resolved from NuGet Packages, then invokes runtests.sh with the only argument being the path to the packages folder.  They aren't "kind of" the same, what is building and running is produced by the same repo, with the same code, and the same .targets files.  They are literally the same.

   That said, there can be differences in how build occurs between local machines, Jenkins CI, and the official build pipeline.  For instance, as far as I know today (would need to see the build commands invoked for Jenkins CI runs) CI and local builds will default to building via project-to-project references.  This can result in differences between package-based and project-reference-based runs, since the build tools code is set up to prefer DLLs that the tests themselves bring along over ones coming from the Nuget package folder.   All official runs are built entirely against packages;  this is my top suspect in things to check out.

   Another difference that has affected us in the past would be missing or outdated dependencies on the Linux machines by the libraries themselves.  This is something to consider, but given that this only fails for Release builds I'm not sure how likely it is (unless there are debug and release versions of these dependencies.

  My final suggestion would be just differences in the machines themselves.  CPU-wise they may be faster or slower with more or fewer cores than the Jenkins CI machines, and disk-operation wise they are way beyond even my nicest home PC.  

The easiest way to debug this would be to first use the HelixJobReproCore tool to run it on your local *nix machine of choice.   If the problem repros there, you can analyze the assemblies for differences / debug / etc.  If the official built binaries don't repro the problem, it's most likely a machine configuration issue and we can explore that as well by SSH'ing into a Helix VM.  The core version of the repro tool is a bit rough right now but I can help you with it tomorrow.

**Comment by MattGal** [comment]
Update:  Tried this just now using the repro tool, my personal Centos VM gets the same segfault as a normal run.  Stop by and I'll get you set up with this tomorrow AM.

**Comment by adityamandaleeka** [comment]
Yup, I can confirm that this is a real bug, and it appears to be in JIT. The test where we crash always seems to be "System.Linq.Parallel.Tests.ParallelQueryCombinationTests.Average_Nullable".

Here is the first part of the code for Average_Nullable (up until the point where it crashes). It appears we crash trying to call some method on some object that came in via RDI.

``` assembly
    0x7fff7d880910: push   rbp
    0x7fff7d880911: push   r15
    0x7fff7d880913: push   r14
    0x7fff7d880915: push   rbx
    0x7fff7d880916: sub    rsp, 0x68
    0x7fff7d88091a: lea    rbp, [rsp + 0x80]
    0x7fff7d880922: xor    eax, eax
    0x7fff7d880924: mov    qword ptr [rbp - 0x48], rax
    0x7fff7d880928: mov    qword ptr [rbp - 0x40], rax
    0x7fff7d88092c: mov    qword ptr [rbp - 0x28], rdi
    0x7fff7d880930: mov    qword ptr [rbp - 0x20], rsi
    0x7fff7d880934: xor    edi, edi
    0x7fff7d880936: lea    rax, [rbp - 0x38]
    0x7fff7d88093a: vxorpd xmm0, xmm0, xmm0
    0x7fff7d88093f: vmovdqu xmmword ptr [rax], xmm0
    0x7fff7d880944: vmovsd xmm0, qword ptr [rip + 0x143] ; xmm0 = mem[0],zero 
    0x7fff7d88094d: lea    rdi, [rbp - 0x38]
    0x7fff7d880951: call   0x7fff7cf75dc0
    0x7fff7d880956: movabs rcx, 0x7fff680074b8
    0x7fff7d880960: mov    rcx, qword ptr [rcx]
    0x7fff7d880963: mov    rdi, qword ptr [rbp - 0x20]
    0x7fff7d880967: mov    rdi, qword ptr [rdi + 0x8]
    0x7fff7d88096b: mov    esi, 0x8
    0x7fff7d880970: mov    edx, 0x10
    0x7fff7d880975: mov    rax, qword ptr [rbp - 0x28]
    0x7fff7d880979: call   qword ptr [rax + 0x18] <------------------- this is 0 so we segfault.
```

When we enter the function, RDI points to a string ("Cast") and RSI points to a System.Linq.Parallel.Tests.ParallelQueryCombinationTests+Operation.

Looking at the layout of the latter object, we see that at offset 0x18, there is a _methodPtr:

``` 
00007fff7d1ed148  4000535        8        System.Object  0 instance 00007fff582bba28 _target
00007fff7d1ed148  4000536       10        System.Object  0 instance 0000000000000000 _methodBase
00007fff7d1f30a0  4000537       18        System.IntPtr  1 instance 00007FFF7D893B38 _methodPtr
00007fff7d1f30a0  4000538       20        System.IntPtr  1 instance 0000000000000000 _methodPtrAux
00007fff7d1ed148  400139d       28        System.Object  0 instance 0000000000000000 _invocationList
00007fff7d1f30a0  400139e       30        System.IntPtr  1 instance 0000000000000000 _invocationCount
```
It's possible that this is what we were supposed to call.

BTW, it turns out this test has been crashing in CoreFX Jenkins CI too, but it doesn't get reported properly so the failure doesn't show up in the results.

**Comment by adityamandaleeka** [comment]
@RussKeldorph Can you please take a look and re-route as appropriate? It's pretty easy to repro locally.

**Comment by jhendrixMSFT** [comment]
@mmitche for FYI on the reporting issue in Jenkins.

**Comment by mmitche** [comment]
Do you have a link to a log with the failure that didn't get reported?

**Comment by MattGal** [comment]
@mmitche literally any outerloop jenkins run for the past several weeks should show it.

**Comment by mmitche** [comment]
@MattGal I've looked through a few logs and seen no crashes.  Can you point me to one?

**Comment by MattGal** [comment]
From http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/master/job/outerloop_centos7.1_release/lastBuild/console 

09:11:55 /mnt/resource/j/workspace/dotnet_corefx/master/outerloop_centos7.1_release/Tools/tests.targets(265,5): error : One or more tests failed while running tests from 'System.Linq.Parallel.Tests' please check log for details! [/mnt/resource/j/workspace/dotnet_corefx/master/outerloop_centos7.1_release/src/System.Linq.Parallel/tests/System.Linq.Parallel.Tests.csproj]

**Comment by RussKeldorph** [comment]
@dotnet/jit-contrib FYI

Looking for someone to investigate...

**Comment by kyulee1** [comment]
This repros since https://github.com/dotnet/coreclr/pull/6342

``` assembly
    0x7fff7d880975: mov    rax, qword ptr [rbp - 0x28]   --> This points to RDI value which is wrong. It should get the value from RSI instead which is [rbp-0x20] in this case.
    0x7fff7d880979: call   qword ptr [rax + 0x18]
```
