### ISSUE TITLE
Caching the result of Char.ToString

### ISSUE THREAD

**Issue by jamesqo** [dotnet/coreclr#6532]
Since `Char.ToString` is called so often when concatenating variable chars to strings, e.g.

```cs
"The letter " + letter + " is the " + i "th letter in the alphabet."
// or String.Format
$"The letter {letter} is the {i}th letter in the alphabet."
```

and people typically aren't aware that it involves boxing + a string allocation, we may want to consider caching the `ToString` part for ASCII characters. It could look something like this:

```cs
private static readonly string[] s_asciiStrings =
{
    "\u0000",
    "\u0001",
    "\u0002",
    "\u0003",
    "\u0004",
    ...
};

public string ToString()
{
    return m_value <= '\u007f' ? s_asciiStrings[m_value] : new string(m_value, 1);
}
```

I haven't submitted a PR for this yet since I haven't tested the performance impact (it would probably kill inlining for the method since now it needs to include a branch + array index range check), and the overhead of the array + cached strings would be quite substantial (I think ~32-40 bytes for each string assuming 64-bit, and the array itself would take up about 8 * 128 bytes).

cc @omariom @GSPP

**Comment by mikedn** [comment]
> Since Char.ToString is called so often

Hmm, how exactly did you determined that it is called often?

> and people typically aren't aware that it involves boxing

The concatenation version doesn't involve boxing. The format version does box the char but also happens for a lot of other value types (`int`, `float` etc.) which are far more common than `char`.

**Comment by GSPP** [comment]
I can already see the Stack Overflow questions coming: "Why is `ReferenceEquals('A'.ToString(), 'A'.ToString()) == true` but `ReferenceEquals('Ü'.ToString(), 'Ü'.ToString()) == false`???"

;-)

I think inlining is not really important here because the cost of executing this is so much higher than the call cost. Inlining does not simplify anything away here. It's just the call that's avoided. So that's not a significant loss.

Java has something similar with boxing. Certain numbers box to well-known references I think. I believe the Java people sometimes have bugs and irritations caused by that.

If this is implemented I'd lazily initialize the array slots and I'd start the array at something more realistic like `' '`.

I also think that this is more useful for integers. Culture could play a role there. [Not sure how culture could possibly affect the result.](http://stackoverflow.com/questions/8492449/is-int32-tostring-culture-specific)

`Boolean.ToString()` already does something like this.

Another concern is that this could be implemented as a library method. It does not have to be in the BCL (but it could).

This would not only benefit in terms of reduced CPU cost but also in terms of reduced working set size. Some applications keep a lot of data in memory. This optimization could cause a lot of structure sharing.

**Comment by bbowyersmyth** [comment]
By chance I had to do a similar mapping recently but it was a pretty specialised situation.

The `char` boxing in the concat was taken out by https://github.com/dotnet/roslyn/pull/415. There is still the char `ToString` allocation and the boxing of the `int` though. That link also contains the discussion on why int's weren't given the same `ToString` treatment.

**Comment by jamesqo** [comment]
@mikedn

> Hmm, how exactly did you determined that it is called often?

Well, [this](https://github.com/search?l=csharp&q=%22Char+ToString%22&type=Code&utf8=%E2%9C%93) brings up a couple of scenarios...

- `EndsWith` on a char
- Replacing a char with `string.Empty`
- `Contains` on a char (although that is suboptimal, it could instead be `IndexOf(c) != -1`)
- etc.

**Comment by jamesqo** [comment]
@GSPP 

> If this is implemented I'd lazily initialize the array slots

Good idea!

> and I'd start the array at something more realistic like ' '.

Maybe... that would shave off 32 * 8 bytes from the array size, which doesn't sound too bad.

> Not sure how culture could possibly affect the result.

I think by default int.Parse/ToString uses CurrentCulture, so depending on where you live the same input might give different results. For example the answer in the post you linked to mentions that it's possible to override the negative sign, e.g. have `(-123).ToString()` print `!123`.

@bbowyersmyth Interesting... so that's why `box` is emitted for ints but not chars. Thanks for linking to that PR.

**Comment by mikedn** [comment]
> Well, this brings up a couple of scenarios...

And in how many of those instances the string allocation made by `char.ToString` constitutes a bottleneck and in how many instances the code simply sucks performance wise and could have been easily replaced with something that doesn't involve `char.ToString`?

> EndsWith on a char, Replacing a char with string.Empty, Contains on a char

`EndsWith` should have a `char` overload as that would be more efficient even if `char.ToString` is changed as you suggest. `Replace` is inherently slow and allocates anyway. Replacing chars/strings with the empty string is a relatively common scenario in my experience and IMO it would be better served by some additional `Remove` overloads. `Contains` already has a better alternative as you already suggested.

**Comment by omariom** [comment]
I like the idea. The only  thing concerns me is that it is another root GC needs to check - the array and then string instances it keeps.

**Comment by jamesqo** [comment]
I am closing this. Even using lazy initialization of the array slots, there would still need to be at least ~30 repetitions of the same characters to justify the memory taken up by the array.
