### ISSUE TITLE
All CoreCLR files went down in version after shipping in VSO

### ISSUE THREAD

**Issue by ericstj** [dotnet/coreclr#6559]
All DLLs should be versioned monotonically so that installer technology like MSI can reason about what version "wins" when installed to the same location.  All of the DLLs in CoreCLR carry a redist license that permits folks to install them in where-ever they want so they should follow this rule. 

CoreCLR broke this when switching to build from the open:
When building from TFS dlls (coreclr.dll, mscorrc.dll, mscorlib.dll, etc) all had file version 4.6.build.revision.
When building from VSO/open the same dlls now have version 1.0.build.revision.

This will break anyone redistributing the files via MSI.  If folks were installing builds prior to the VSO switch those files will never be updated by the lower versioned files.

/cc @jhendrixMSFT @gkhanna79 @chcosta

**Comment by gkhanna79** [comment]
> This will break anyone redistributing the files via MSI. If folks were installing builds prior to the VSO switch those files will never be updated by the lower versioned files.

I am not aware of anyone redistributing CoreCLR binaries via MSI. The first time such a thing was done was for .NET Core RC1/2 (which came from TFS build) but .NET Core RTM MSI (which came from open build) is not replacing those binaries (since it is SxS).

Can you please elaborate which scenario is broken?

CC @weshaggard

**Comment by gkhanna79** [comment]
@rahku As discussed, can you PTAL?
