### ISSUE TITLE
Arm Emulator vm runs out of space

### ISSUE THREAD

**Issue by jashook** [dotnet/coreclr#6676]
The arm emulator is building, copying and running entirely on the machines /tmp drive. We can switch this over to a temp directory on another drive /mnt. This will speed up the build and keep the space issues from happening often.

In addition there needs to be more cleanup for arm emulator jobs.

http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/arm_emulator_cross_debug_ubuntu_prtest/1263/consoleFull
/usr/bin/cp: error writing ‘/home/coreclr/Windows_NT.x64.Debug/Tests/coreoverlay/mscorlib.dll’: No space left on device

**Comment by sjsinju** [comment]
OK I got it. Let me check this issue.

**Comment by sjsinju** [comment]
@dotnet-bot test Linux ARM Emulator Cross Debug Build please

**Comment by jashook** [comment]
@sjsinju here is a list of the current drives of the failing machine. Either the mounted vm or /dev/sda could be filling up when running. Either way this should be possible to avoid by working in /dev/sdb1.

Filesystem      Size  Used Avail Use% Mounted on
udev            6.9G  8.0K  6.9G   1% /dev
tmpfs           1.4G  408K  1.4G   1% /run
/dev/sda1        29G   15G   14G  52% /
none            4.0K     0  4.0K   0% /sys/fs/cgroup
none            5.0M     0  5.0M   0% /run/lock
none            6.9G  8.0K  6.9G   1% /run/shm
none            100M     0  100M   0% /run/user
none             64K     0   64K   0% /etc/network/interfaces.dynamic.d
/dev/sdb1       197G  6.7G  181G   4% /mnt
/dev/loop0      6.8G  2.2G  4.3G  34% /opt/linux-arm-emulator-root
shm             6.9G     0  6.9G   0% /opt/linux-arm-emulator-root/run/shm

**Comment by sjsinju** [comment]
@jashook I think the problem is occurred while running the script 'runttest.sh'.  This run on the rootfs of emulator(/opt/linux-arm-emulator-root) with chroot command by below codes in 'arm32_ci_script.sh'
```
sudo chroot $__ARMRootfsMountPath /bin/bash -x <<EOF
        cd /home/coreclr
        ./tests/runtest.sh --testRootDir=$__testRootDirBase \
                           --mscorlibDir=$__mscorlibDirBase \
                           --coreFxNativeBinDir=$__coreFxNativeBinDirBase \
                           --coreFxBinDir="$__coreFxBinDirBase" \
                           --testDirFile=$__testDirFileBase \
                           --testNativeBinDir=$__testNativeBinDirBase \
                           --coreClrBinDir=$__coreClrBinDirBase
```

I think it has needed more disk space to test after "TypeSystem generics test cases (#6663)".
So I tried to build with 7G rootfs(current) and 10G rootfs on local system. The building with 10G rootfs was successful. 
Now, I increased the rootfs of emulator to 10G on the captured CI system that you told me. Please apply current updated CI System to real cloud CI System.

**Comment by jashook** [comment]
This issue has been mitigated by increasing the rootfs's virtual filesystem size.

@sjsinju This problem still exists and can be hit in the future; therefore, before closing this it would be better to solve the problem entirely.

If we could mount a temporary drive while chrooted into the emulator which has significantly larger amount of storage this would be preferable. Including @mmitche who may want to give his own opinion on how to solve this.

My proposal would be to bind a temp folder in the job's workspace to <arm-emulator>/tmp. All files required to run coreclr would be run from the <arm-emulator>/tmp and the storage issue would be addressed. We also get the added bonus of working on a faster drive.

**Comment by jkotas** [comment]
Pretty much all jobs are hitting the out of space errors again.

**Comment by RussKeldorph** [comment]
@sjsinju We can't keep increasing FS size.  We need you to apply @jashook's fix or equivalent ASAP.  Any ETA on that?  If this isn't mitigated in the next day or two, we're going to have to switch these jobs from PR-triggered to commit-triggered so that people aren't constantly distracted with these false negatives in their PRs.

**Comment by sjsinju** [comment]
@RussKeldorph OK. Let me try to apply @jashook's proposal to my local PC. And after that I will fix this issue ASAP.

**Comment by BruceForstall** [comment]
I believe this issue is obsolete; closing.
