### ISSUE TITLE
Array.IsReadOnly should return true for empty arrays

### ISSUE THREAD

**Issue by DerpMcDerp** [dotnet/coreclr#6692]
i.e. Array.cs should have this:

``` C#
    // Is this Array read-only?
    public bool IsReadOnly
    { get { return this.Length == 0; } }
```

instead of this:

``` C#
    // Is this Array read-only?
    public bool IsReadOnly
    { get { return false; } }
```

Note: the above change breaks code which does something like:

``` C#
    Contract.Requires(!list.IsReadOnly, "list should be writable")

    for (int i = 0; i < list.Count; ++i) {
        list[i] = whatever;
    }
```

Which was an incorrectly specified invariant anyway.

**Comment by hughbe** [comment]
I hate to be a killjoy @DerpMcDerp, but this probably has too many breaking change implications. I assume that a new implementation would consider this, but the baggage of the past has to be taken into account

**Comment by denis-dbm** [comment]
IsReadOnly is just inherited from IList interface, isn't? There is real use of this property for array type?

I think the property should return false always.

**Comment by jasonwilliams200OK** [comment]
BTW, how does `this.Length == 0;` convey the message that collection is IsReadOnly? It should explicitly be either true (for `ReadOnlyCollection` types) or false (for non-`ReadOnlyCollection` types) because that would assert an artificial limitation on Add/Remove/Indexer methods. Or am I missing something?

Probably having `IsFixedSize` in addition to `IsReadOnly` would somehow mitigate the confusions around the area as @jskeet pointed out: http://stackoverflow.com/a/26475514

**Comment by danmosemsft** [comment]
Per [issues guidance](https://github.com/dotnet/coreclr/blob/master/Documentation/workflow/IssuesFeedbackEngagement.md) 
> If in the managed code log it in the CoreFX repo even if the code is in this CoreCLR repo (ie., in mscorlib/System.Private.Corelib). The reason for this is we sometimes move managed types between the two and it makes sense to keep all the issues together.

**Comment by danmosemsft** [comment]
Issue moved to [dotnet/corefx #14324](https://github.com/dotnet/corefx/issues/14324) via [**ZenHub**](https://www.zenhub.com/)
