### ISSUE TITLE
Runtime cannot load Ready-to-Run image multiple times from the same location

### ISSUE THREAD

**Issue by JohnChen0** [dotnet/coreclr#6695]
If an app loads a Ready-to-Run image (or a fragile native image) using `AssemblyLoadContext.LoadFromAssemblyPath`, and then tries to load the same image again by some other means, the second load fails with the error `Native image cannot be loaded multiple times`. This has been observed in CLI build (Microsoft/msbuild#750).

We need to investigate exactly what scenarios are allowed or disallowed by the runtime, and find possible ways to make the behavior more user-friendly.

**Comment by tmeschter** [comment]
@JohnChen0 When you say "the same image" what exactly do you mean? Do mean loading the exact same file on disk more than once will cause this exception? Or that two different native image files on disk with the same assembly identity would also have this problem?

Other questions:

* Does it matter if the loads are in different `AssemblyLoadContexts`?
* If I can load an IL assembly more than once, but I can't load the equivalent native image more than once, isn't that fundamentally broken? How can I ever safely load an assembly that may or may not be a native image?

**Comment by agocke** [comment]
@JohnChen0 After thinking about this a bit more, I'm worried this is going to have a significant impact on being able to ship new versions of  the compiler with the .NET Core tooling.

Since the compiler is loaded into .NET Core MSBuild via a build task, if we ship multiple versions of the compiler (as we do now in the Microsoft.Net.Compilers NuGet package) that could conceivably cause multiple versions of the build task to be loaded.  If, for instance, we were to ship a new version of the compiler build task with a few of the binaries remaining the same (e.g., System.Collections.Immutable) this could conceivably cause the runtime to crash when the second load occurs, correct?

I'd like to understand the impact of this bug for the .NET Core tooling before the 1.0.0 time frame.

**Comment by tmeschter** [comment]
@agocke This is why MSBuild is now careful to only ever use the default `AssemblyLoadContext`. So long as the default context does not try to load a particular crossgen'd image more than once (and I'm assuming it will not) we're fine.

If you have two different versions of an assembly then you necessarily have files at two different paths, and that does not sound like it should pose a problem.

**Comment by agocke** [comment]
@tmeschter But what about indirect loads? I'm worried about this situation:

MSBuild -> Microsoft.Build.Tasks.CodeAnalysis v2.0.0 -> System.Collections.Immutable v1.8.0

MSBuild -> Microsoft.Build.Tasks.CodeAnalysis v2.1.0 -> System.Collections.Immutable v.1.8.0

**Comment by tmeschter** [comment]
@agocke Since this is all in the same `AssemblyLoadContext` I expect that the first request will load System.Collections.Immutable _and then cache the Assembly_. The second request would simply return the cached assembly.

**Comment by agocke** [comment]
@tmeschter Note that System.C.I in the second load would be a different file in a different location. Would it still be cached?

**Comment by tmeschter** [comment]
@agocke I don't think it would even look for the second file, since is already has an assembly with the proper identity and can simply use that. Loading multiple assemblies with the same identity is not the behavior you want for the default `AssemblyLoadContext`.

Even if it did, it would then load them from two different locations--at which point you won't run into this bug.

**Comment by agocke** [comment]
OK, sounds good. My concerns are assuaged, then.

**Comment by JohnChen0** [comment]
Resolved with PR #7809.
