### ISSUE TITLE
Lazy initialization of TextInfo::m_IsAsciiCasingSameAsInvariant is not thread safe

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#6794]
`m_IsAsciiCasingSameAsInvariant` is `Nullable<bool>`, but it is lazily initialized in lock-free fashion. This is not thread safe because of assignment of `Nullable<bool>` is not atomic.

**Comment by jkotas** [comment]
We may want to have generalize `enum TurkishCasing` to fix this, and also change its size to `byte` while we are on it.

**Comment by joheredi** [comment]
Hi,

I was looking at this issue and wanted to contribute. Based on your comments here and in #6770 there may be two options.

1) Create a more generic enum such as 

```c#
enum Tristate : byte
{
	NotInitialized,
	True,
	False,
}
```

2) Or follow DateTimeFormatFlags more closely and have a TextInfoCasingFlags like this

```c#
[Flag]
enum TextInfoCasingFlags
{
   None = 0x00000000,
   AsciiSameAsInvariant = 0x00000001,
   TurkishCasing = 0x00000002,

   NotInitialized = -1,
}
```

I think I'm leaning towards 1) since it would be a smaller change and there are not many flags in this case.

@jkotas what are your thoughts?

**Comment by jkotas** [comment]
@joheredi I like your Tristate proposal as well. Thank you!
