### ISSUE TITLE
Activator.CreateInstance fails to call constructor for value types

### ISSUE THREAD

**Issue by gafter** [dotnet/coreclr#6843]
See https://github.com/dotnet/roslyn/issues/1029 and http://roslyn.codeplex.com/workitem/465 for some context.

> The issue is basically an optimization introduced in Activator.CreateInstance around CLR 4.0 and present ever since. The optimization assumes that parameterless instantiation of generic T type does not cause sideeffects if T is found to be a struct and therefore instances can be cached. Parameterless struct constructors (which are permitted by spec) violate such assumptions and make optimization observable.

**Comment by jkotas** [comment]
[This code](https://github.com/dotnet/coreclr/blob/00c85b302a078d5d13cfe9ff8cb453cd8296d6aa/src/mscorlib/src/System/RtType.cs#L5143) makes incorrect assumption that value types have no default constructor.

**Comment by jkotas** [comment]
@gkhanna79 Could you please reassign it as appropriate?

**Comment by gkhanna79** [comment]
@ramarag PTAL

**Comment by andrewjsaid** [comment]
I read an article earlier today about Wire Serialiser where one of the optimisations was able to determine whether the constructor of a type had any side effects by counting the number of IL instructions. The author intelligently determined that any constructor with fewer than 8 IL bytes, accessed through GetILAsByteArray(), must have no side effects.

I am not familiar with the coreclr code based but I presume that the same optimisation can be used such that instead of 

	if (!ace.m_type.IsValueType)

we can have

	// Pseudocode
	if (defaultConstructor.GetILAsByteArray().Count > 8)

For reference:
See the section titled "Fast creation of empty objects" in the first link
https://rogeralsing.com/2016/08/16/wire-writing-one-of-the-fastest-net-serializers/
http://mattwarren.org/2016/08/23/Analysing-Optimisations-in-the-Wire-Serialiser/

This would then also provide a benefit to reference types which do not override the default constructor, although I am not sure whether you would also need to check all base types and whether that would be more expensive. Maybe it could be an optimisation only for those types inheriting from Object or ValueType?

**Comment by gkhanna79** [comment]
@ramarag Did you take a look at this?

**Comment by gkhanna79** [comment]
@kouvel Can you PTAL?
