### ISSUE TITLE
!u & !bpmd broken

### ISSUE THREAD

**Issue by rahku** [dotnet/coreclr#6874]
!u and !bpmd sos commands do not work anymore most likely due to PR #6783. I tried this on windows x64 debug builds

0:000> !u 00007ffd0dde0920
Normal JIT generated code
Porgram.Main()
Begin 00007ffd0dde0920, size 1c
e0434352 Exception in F:\coreclrGit\coreclr\bin\tests\Windows_NT.x64.Debug\Tests\Core_Root\SOS.dll.u debugger extension.
      PC: 00007ffd`b53a1f28  VA: 00000000`00000000  R/W: 80131040  Parameter: 00000000`00000000

It seems like sos is trying to load diasymreader.dll which it is unable to find.

**Comment by mikem8361** [comment]
Does the exception still happen if you do "!u -n ..."? 

If diasymreader.dll was missing, you should get a nice error message.  PR #6783 did cause SOS to attempt to load/get disasymreader.dll now where it didn't before, but it shouldn't crash.  It could be crashing trying to load a portable PDB for the program.  It might be crashing because you don't have a recent enough System.Reflection.Metadata assembly as part of the runtime used to execute your app.  For portable PDBs, the managed assembly SOS.NETCore is loaded by the native SOS and it has the System.Reflection.Metadata dependency.  But even then, any errors like that should be caught and ignored (no source/line info of course). 

I need more info, since I can't repro this locally. Could you attach VS (or windbg) to windbg/cdb and get more info on the exception. And maybe even trace into the SOS code in SymbolReader::LoadSymbolsForPortablePDB.

**Comment by rahku** [comment]
!u -n works fine
0:000> !u -n 00007ffd0dde0920
Normal JIT generated code
Porgram.Main()
Begin 00007ffd0dde0920, size 1c
>>> 00007ffd`0dde0920 4883ec28        sub     rsp,28h
00007ffd`0dde0924 48b96830001052020000 mov rcx,25210003068h
00007ffd`0dde092e 488b09          mov     rcx,qword ptr [rcx]
00007ffd`0dde0931 e8b2f7ffff      call    System.Console.WriteLine(System.String) (00007ffd`0dde00e8)
00007ffd`0dde0936 90              nop
00007ffd`0dde0937 4883c428        add     rsp,28h
00007ffd`0dde093b c3              ret

sent you my private binaries for repro

**Comment by mikem8361** [comment]
PR #6905 fixes (even though the title doesn't seem appropriate) the cases where System.Reflection.Metadata.dll is missing or the wrong version. 

You still have some kind of mismatch probably with mscorlib/System.Private.CoreLib and CoreClr.dll.  The corefx bin directory contains those in the *.Tests* directories. This is unlikely because the timestamps of the all the coreclr binaries match in your zip file. I'm just throwing out possibilities.
