### ISSUE TITLE
CultureAwareComparer and CompareOptions

### ISSUE THREAD

**Issue by panost** [dotnet/coreclr#693]
Change [CultureAwareComparer's](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/StringComparer.cs#L137) "bool _ignoreCase" field to an "CompareOptions _options" with a ctor that initialize it. The ctor with the boolean can stay and just call the above ctor with "ignoreCase? CompareOptions.IgnoreCase :  CompareOptions.None"

This change will have two benefts

1. Performance: each time a method of  CompareInfo is about to be called, CompareOptions [are computed from the ignoreCase](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/StringComparer.cs#L169). Now for each method you can use the _options field value directly

2. By providing an overload static method in [StringComparer.Create](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/StringComparer.cs#L64) that accepts CultureInfo  and CompareOptions, you'll be able to create an SqlServer-compatible ignore case, accent insesitive StringComparer (or whatever combination of a valid CompareOptions values you want**). Currently you are out of options because you can't provide valid HashCodes, since CompareInfo.GetHashCodeOfString that accepts CompareOptions is internal

** this method should not accept Ordinal,OrdinalIgnoreCase or StringSort options. It should check this by using the same check that [CompareInfo.GetHashCodeOfString uses](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Globalization/CompareInfo.cs#L1235)

**Comment by MattWhilden** [comment]
@panost I know it's super confusing but I'm pretty sure this request is better served over in the CoreFX side of the house. They have all the machinery for API review/additions/modification etc.

Maybe @terrajobst has a better sense for where to have this issue looked at/discussed.

**Comment by panost** [comment]
I didn't check CoreFX because StringComparer doesn't belong there. That of course was a wrong assumption since StringComparer isn't there but CultureAwareComparer is !!

...and not only that [is implemented](https://github.com/dotnet/corefx/blob/master/src/System.Globalization.Extensions/src/System/Globalization/Extensions.cs) almost as I described in my first post, with only one ctor accepting CompareInfo  and CompareOptions.

Clearly there is some duplicated code between those two projects. Perhaps CoreFX's CultureAwareComparer should be moved to CoreCLR

**Comment by tarekgh** [comment]
@panost you can get the culture aware comparer with CompareOptions from using System.Globalization.Extensions. so you can do something like CompareInfo.GetStringComparer(CompareOptions)
you may look at the code here https://github.com/dotnet/corefx/blob/master/src/System.Globalization.Extensions/src/System/Globalization/Extensions.cs
we have to expose this functionality from System.Globalization.Extensions because of contract layering as StringComparer is exposed from System.Runtime and we want to avoid having System.Runtime depends on System.Globalization contract.
by that, I think your issue is addressed. please let me know if you have any question I can help with. otherwise we can close this issue
Thanks

**Comment by panost** [comment]
@tarekgh My last suggestion was to avoid two CultureAwareComparer classes, by merging them in one in System.Runtime. But my main concern is addressed, so yes, you can close this issue.

**Comment by tarekgh** [comment]
Thanks @panost
