### ISSUE TITLE
RyuJIT x86: DevDiv_255263 test fails

### ISSUE THREAD

**Issue by CarolEidt** [dotnet/coreclr#6940]
This is an IL test reproducing an issue that was found with managed C++ in the desktop version of .NET.  It is failing on x86, but no analysis has yet been done to determine the cause.

**Comment by BruceForstall** [comment]
The problem is with unrolling an initblk with a constant init value, and a length greater than 16 (size of the SSE registers). We generate this code:
```
mov      eax, 0xAAAAAAAA
mov      edx, gword ptr [05901C04H]
add      edx, 4
movd     xmm1, eax
punpckldq xmm1, xmm1
movdqu   qword ptr [edx], xmm1
mov      dword ptr [edx+16], eax
mov      dword ptr [edx+20], eax
mov      byte  ptr [edx+24], al
```

The problem is, the `movd xmm1, eax` copies a 4-byte value, and `punpckldq` converts it to an 8-byte value. The upper 16 bytes are zero. On x64, the value starts off as 8-bytes and the `punpckldq` converts it to 16 bytes.

**Comment by drieseng** [comment]
Shouldn't the exclude for DevDiv_255263 (for x86) have been removed as well?

**Comment by BruceForstall** [comment]
Yes; submitting another PR now.
