### ISSUE TITLE
RyuJIT: Volatile param shouldn't prevent inlining

### ISSUE THREAD

**Issue by benaadams** [dotnet/coreclr#7054]
`[FAILED: argument has side effect] Math:Min(int,int):int`

[Math:Min(int,int):int](https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/Math.cs#L427-L431) doesn't appear to have any side effect?

Related issue: https://github.com/dotnet/corefx/issues/11441 "ConcurrentQueue has Math.Min non-inlines "

**Comment by mikedn** [comment]
> Math:Min(int,int):int doesn't appear to have any side effect?

Not `Math.Min` but its arguments may have side effects. For example you get this if you pass in 2 volatile variables.

**Comment by benaadams** [comment]
Interesting... sort of makes sense.

**Comment by benaadams** [comment]
Also seems to do it for a volatile and a const?

**Comment by mikedn** [comment]
> sort of makes sense.

More or less. The JIT could introduce temporaries to avoid reordering.

> Also seems to do it for a volatile and a const?

It doesn't matter how many arguments are volatile, one is enough to block inlining.

**Comment by mikedn** [comment]
The inliner seems to be introducing temporaries anyway so it's possible that this restriction might be pointless.

**Comment by pgavlin** [comment]
cc @AndyAyersMS @kyulee1

**Comment by pgavlin** [comment]
and, of course @dotnet/jit-contrib

**Comment by cmckinsey** [comment]
The only trivially correct evaluation of the arguments for a method inline is to evaluate each actual into a temporary and replace each formal with the temporary. Doing anything else requires analysis. So I wouldn't expect side-effects like volatile to be the issue. It's an overloaded term and might refer to something else as the blocker here. Anyway we should look into this. I agree with toub's comments to not ask developers to code around this when they invoke methods.

**Comment by benaadams** [comment]
For reference

The code that won't inline `Math.Min` is 
```csharp
private const int SEGMENT_SIZE = 32;
private volatile int _low;

internal int Low
{
	get
	{
		return Math.Min(_low, SEGMENT_SIZE);
	}
}
```
The code that will inline `Math.Min` is 
```csharp
private const int SEGMENT_SIZE = 32;
private volatile int _low;

internal int Low
{
	get
	{
		int low = _low;
		return Math.Min(low, SEGMENT_SIZE);
	}
}
```

**Comment by mikedn** [comment]
Volatile is just an example, there may be other situations that trigger the same issue.

In any case, the current behavior is illogical:

```C#
static volatile int x;

[MethodImpl(MethodImplOptions.NoInlining)]
static int X() => x;

static void Test()
{
        Console.WriteLine(Math.Min(X(), 32));  // inlined
        Console.WriteLine(Math.Min(x, 32));    // not inlined due to side effect !?!
}
```

**Comment by JosephTremoulet** [comment]
> The only trivially correct evaluation of the arguments for a method inline is to evaluate each actual into a temporary and replace each formal with the temporary. Doing anything else requires analysis

True, but the inliner currently does the analysis.  It seems to be doing the analysis optimistically -- assume the argument IR node can be copied/re-used until analysis proves otherwise.  The comment at this inliner bail-out seems to indicate that, at least when it was written, the code processing those "proves otherwise" annotations can't handle certain side-effects:

```c++
    if (curArgVal->gtFlags & GTF_ORDER_SIDEEFF)
    {
        // Right now impInlineSpillLclRefs and impInlineSpillGlobEffects don't take
        // into account special side effects, so we disallow them during inlining.
        inlineResult->NoteFatal(InlineObservation::CALLSITE_ARG_HAS_SIDE_EFFECT);
        return;
    }
```

and, indeed, the `GTF_ORDER_SIDEFF` flag is used for volatile (and also for other things):

```c++
                if (prefixFlags & PREFIX_VOLATILE)
                {
                    assert(op1->OperGet() == GT_IND);
                    op1->gtFlags |= GTF_DONT_CSE;      // Can't CSE a volatile
                    op1->gtFlags |= GTF_ORDER_SIDEEFF; // Prevent this from being reordered
                    op1->gtFlags |= GTF_IND_VOLATILE;
                }
```

The inliner can already handle some other kinds of side-effects, the code that makes note of them looks like so:

```c++
        inlCurArgInfo->argHasGlobRef = (curArgVal->gtFlags & GTF_GLOB_REF) != 0;
        inlCurArgInfo->argHasSideEff = (curArgVal->gtFlags & GTF_SIDE_EFFECT) != 0;
```

Seeing as how the inliner already has the capability to evaluate arguments to temps when it so chooses, presumably a similar annotation could be added for these "special" side-effects and they could be treated similarly to the `argHasSideEff` case, though in general I'm not clear on how `GTF_SIDE_EFFECT` and `GTF_ORDER_SIDEEFF` differ.

Clearly one place that would need to handle the side-effect annotation is `impInlineFetchArg`, as that's where the decision is made whether to generate a temp for a given argument.  It looks like `fgInlinePrependStatements` would also have to be in on the game, since that has code responsible for making sure side-effecting arguments are still evaluated even if they're not used in the inlinee.

I have to wonder if this is as simple as setting `argHasSideEff` when an arg has `GTF_ORDER_SIDEEFF`, but I'm not sure how best to confirm that theory.

**Comment by benaadams** [comment]
I assume `GTF_ORDER_SIDEEFF` means changing the read or write order would have a side effect to the behaviour?

`GTF_SIDE_EFFECT` seems to be [for a wide range of items](https://github.com/dotnet/coreclr/blob/ed9721c7be52ff867bcce2d26a85798382189a15/src/jit/assertionprop.cpp#L3643-L3682)

Comment on the [`optCanMoveNullCheckPastTree`](
https://github.com/dotnet/coreclr/blob/c880f864bb91bddd83d5390a85a33c34eee04183/src/jit/earlyprop.cpp#L657-L660)

```csharp
if (isInsideTry)
{
	// We disallow calls, exception sources, and all assignments.
	// Assignments to locals are disallowed inside try because
	// they may be live in the handler.
	if ((tree->gtFlags & GTF_SIDE_EFFECT) != 0)
	{
		result = false;
	}
}
else
{
	// We disallow calls, exception sources, and assignments to
	// global memory.
	if (GTF_GLOBALLY_VISIBLE_SIDE_EFFECTS(tree->gtFlags))
	{
		result = false;
	}
}
```

**Comment by benaadams** [comment]
May suggest assigning to a volatile would be `GTF_ORDER_SIDEEFF | GTF_SIDE_EFFECT` and read would only be `GTF_ORDER_SIDEEFF`?

**Comment by JosephTremoulet** [comment]
> `GTF_SIDE_EFFECT` seems to be for a wide range of items

I'm not sure I follow; the large disjunction in linked code is identifying which helper calls implement checked casts, and the reference to `GTF_SIDE_EFFECT` in it is used to avoid throwing away any side effects in the argument list as it rewrites the code to avoid the call (in the case that it can prove the cast will always succeed).

From their [definitions](https://github.com/dotnet/coreclr/blob/762833dae43d312a3693b6a767771200e476fed9/src/jit/gentree.h#L722-L735), it seems that `GTF_SIDE_EFFECT` means "assignment, or call, or operation that can raise an exception", whereas `GFT_ORDER_SIDEEFF` means "sub-expression has a re-ordering side effect".  From that, the `GTF_SIDE_EFFECT` meaning seems less ambiguous, and `GTF_ORDER_SIDEEFF` certainly sounds like it's meant to capture volatile/acquire/release, and indeed the code uses it for volatile ([1](https://github.com/dotnet/coreclr/blob/762833dae43d312a3693b6a767771200e476fed9/src/jit/importer.cpp#L11899) [2](https://github.com/dotnet/coreclr/blob/762833dae43d312a3693b6a767771200e476fed9/src/jit/importer.cpp#L11996) [3](https://github.com/dotnet/coreclr/blob/762833dae43d312a3693b6a767771200e476fed9/src/jit/importer.cpp#L12961) [4](https://github.com/dotnet/coreclr/blob/762833dae43d312a3693b6a767771200e476fed9/src/jit/importer.cpp#L13206)), but also uses it for more ambiguous "please avoid optimizing this too much"-type annotations, both for catch args ([1](https://github.com/dotnet/coreclr/blob/762833dae43d312a3693b6a767771200e476fed9/src/jit/importer.cpp#L2392-L2394) [2](https://github.com/dotnet/coreclr/blob/762833dae43d312a3693b6a767771200e476fed9/src/jit/flowgraph.cpp#L20255)) and for operations where it has cleared the `GTF_EXCEPT` flag in a control-dependent way and so doesn't want the operation "moved around too much" ([1](https://github.com/dotnet/coreclr/blob/762833dae43d312a3693b6a767771200e476fed9/src/jit/earlyprop.cpp#L608-L612) [2](https://github.com/dotnet/coreclr/blob/762833dae43d312a3693b6a767771200e476fed9/src/jit/assertionprop.cpp#L3476-L3479)).

It's these latter cases that are concerning, because it's hard to know what "avoid optimizing too much" needs to mean.  But perhaps someone else on @dotnet/jit-contrib has a firmer idea.

All that said, however, leaving in exactly one evaluation of a `GTF_ORDER_SIDEFF` operation, in the argument setup portion of an inlined callsite, seems like it should always be "as-if" (and, to quote @cmckinsey , it's "trivally correct" :))... and we need to do that much for `argHasSideEff`/`GTF_SIDE_EFFECT` arguments already, so it still seems like replicating that behavior for these arguments should be correct, modulo seeing what issue with `impInlineSpill...` the comment was referring to and whether perhaps there's an issue with `GFT_ORDER_SIDEEFF` being ignored by the inlining code when it appears on non-leaf nodes or something.

**Comment by JosephTremoulet** [comment]
I tracked down the implementations of `impInlineSpillLclRefs` and `impInlineSpillGlobEffects`.  It turns out the inliner used to have its own import loop, which didn't handle as many cases, and for which those methods were trimmed-down versions of `impSpillLclRefs` and `impSpillSideEffects`.  Now that the inliner shares the main import loop with the importer, it's using the full versions of those helpers which have `impSpillSpecialSideEff` calls as needed to handle the `GTF_ORDER_SIDEFF` cases.

Meanwhile, it looks like everything the inliner does for `argHasSideEff` args is something it needs to do for volatiles, and AFAIK is sufficient for them, so I'll try testing the change to set it for `GTF_ORDER_SIDEEFF` arguments.
