### ISSUE TITLE
PAL_sxs SEH failure w/ CoreCLR built with LTO

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#7069]
The PAL test should be fixed by using the same __attribute__((noinline)) __attribute__((optnone)) hack as what we are using in the product - https://github.com/dotnet/coreclr/blob/5ac6af932fe2a3f4b285b6dcc79010caf807ea9d/src/debug/shared/dbgtransportsession.cpp#L1144

**Comment by jkotas** [comment]
Related to https://github.com/dotnet/coreclr/issues/5519

**Comment by lt72** [comment]
@hanblee @janvorli @jankotas 
hanblee found out that the suggested work around does not resolve the issue. Any other suggestions we could try?

**Comment by janvorli** [comment]
The attributes are not enough. They don't prevent the compiler / linker to get rid of the exception handling info for ranges where the compiler doesn't see any throw statement. Even with regular `-O3` optimization without LTO. 
The only thing I found working so far is to add a throw statement wrapped in an if with a condition being a volatile bool variable always set to false to a function that can generate a hardware exception, transitively called from the `try`. That function must also be marked with `__attribute__(noinline)` because inlining it into the `try` block would cause the compiler to generate the EH info only for the range where the fake `throw` is located.
I will paste here a piece of sample code where it works in a minute - need to find it on one of my Linux machines.

**Comment by jkotas** [comment]
Agree. The test should look like the hack that is used in the debugger code - https://github.com/dotnet/coreclr/blob/5ac6af932fe2a3f4b285b6dcc79010caf807ea9d/src/debug/shared/dbgtransportsession.cpp#L1144

**Comment by janvorli** [comment]
Right, that's a good example - in the test case, it would mean moving the *p = 1 into a separate function with `__attribute__(noinline)` `__attribute__(optnone)` and adding `if (p == NULL) { throw PAL_SEHException(); } before or after the assignment.

**Comment by lt72** [comment]
This should be fixed with #7267
