### ISSUE TITLE
HelloWorld sample Linux x64: dlopen failed to open the libcoreclr.so

### ISSUE THREAD

**Issue by bobahml** [dotnet/coreclr#708]
Ubuntu 14.04 x64
I perform all the steps described in the instructions:
https://github.com/dotnet/coreclr/wiki/Linux-instructions

Each step of this instruction has been successfully completed.
But when I try to run test sample 
./corerun HelloWorld.exe linux
dlopen failed to open the libcoreclr.so with error libcoreclrpal.so: cannot open shared object file: No such file or directory

PS:
When I run  ~/git/coreclr$ ./build.sh  I've seen in the console messages like these.
Linking CXX static library libcordbee_dac.a
Linking CXX shared library libcoreclr.so
Linking CXX static library libdebug-pal.a
But build was  successfully completed.

There is a feeling that the instructions something is missing.

**Comment by mikem8361** [comment]
My latest change to move the PAL to a separate module (libcoreclrpal.so) is causing this problem. A workaround for now is to set the LD_LIBRARY_PATH environment variable to the runtime binaries (where corerun/lib* are). The reason we didn’t hit this problem is because LD_LIBRARY_PATH is required to use the lldb sos plugin and debugger binaries.  I created issue #709 to address this.

Example:

“export LD_LIBRARY_PATH=~/coreclr/bin/Product/Linux.x64.Debug”

**Comment by bobahml** [comment]
Thank you! It works.
