### ISSUE TITLE
RyuJIT x86: [GCStress=0xC][ZapDisable=1] Consistency check failed: AV in clr at CLRVectoredExceptionHandlerShim

### ISSUE THREAD

**Issue by adiaaida** [dotnet/coreclr#7088]
In Windows_NT.ryujit.x86.Checked.gc_stress.0xc.zap_disable.1

set COMPlus_AltJit=*
set COMPlus_AltJitName=protojit.dll
set COMPlus_GCStress=0xc
set COMPlus_ZapDisable=1

/Regressions/common/date/date.cmd

> D:\j\workspace\x86_ryujit_ch---d780febb\bin\tests\Windows_NT.x86.Checked\TestWrappers\Regressions\Regressions.XUnitWrapper.cs(450): error : Regressions._common_date_date_._common_date_date_cmd [FAIL] [D:\j\workspace\x86_ryujit_ch---d780febb\tests\runtest.proj]
> Assert failure(PID 3408 [0x00000d50], Thread: 8552 [0x2168]): Consistency check failed: AV in clr at this callstack:
> ------
> CORECLR! CLRVectoredExceptionHandlerShim + 0x194 (0x716d2604)
> NTDLL! RtlDeleteAce + 0x1D2 (0x779d67e2)
> NTDLL! LdrUnloadDll + 0x181 (0x77a3cff1)
> NTDLL! KiUserExceptionDispatcher + 0xF (0x77a105bf)
> CORECLR! PreStubWorker + 0x3BE (0x717afd8e)
> CORECLR! ThePreStub + 0x11 (0x716738f2)
> CORECLR! CallDescrWorkerInternal + 0x34 (0x71673501)
> CORECLR! CallDescrWorker + 0xDB (0x718a36a9)
> CORECLR! CallDescrWorkerWithHandler + 0x137 (0x718a3845)
> CORECLR! MethodDescCallSite::CallTargetWorker + 0x894 (0x718a410d)
> CORECLR! MethodDescCallSite::Call_RetArgSlot + 0x8B (0x718644d7)
> CORECLR! ``RunMain'::`21'::__Body::Run'::`5'::__Body::Run + 0x15D (0x7186a2ce)
> CORECLR! `RunMain'::`21'::__Body::Run + 0x64 (0x7186a46e)
> CORECLR! RunMain + 0xD1 (0x7186a5a1)
> CORECLR! Assembly::ExecuteMainMethod + 0x144 (0x718664e0)
> CORECLR! CorHost2::ExecuteAssembly + 0x23C (0x715f2cec)
> CORERUN! TryRun + 0x567 (0x002ed884)
> CORERUN! wmain + 0x98 (0x002ee41c)
> CORERUN! invoke_main + 0x1E (0x0030da5e)
> -----
> .AV on tid=0x2168 (8552), cxr=02A4D364, exr=02A4D314
> FAILED: false
> CORECLR! CHECK::Trigger + 0x30E (0x715ba13c)
> CORECLR! CLRVectoredExceptionHandlerPhase3 + 0x229 (0x716d23c2)
> CORECLR! CLRVectoredExceptionHandlerPhase2 + 0x4B (0x716d206e)
> CORECLR! CLRVectoredExceptionHandler + 0x138 (0x716d201b)
> CORECLR! CLRVectoredExceptionHandlerShim + 0xBB (0x716d252b)
> NTDLL! RtlDeleteAce + 0x1D2 (0x779d67e2)
> NTDLL! LdrUnloadDll + 0x181 (0x77a3cff1)
> NTDLL! KiUserExceptionDispatcher + 0xF (0x77a105bf)
> NTDLL! RtlDeleteAce + 0x1D2 (0x779d67e2)
> NTDLL! LdrUnloadDll + 0x181 (0x77a3cff1)
> File: d:\j\workspace\x86_ryujit_ch---d780febb\src\vm\excep.cpp Line: 8141
> Image: D:\j\workspace\x86_ryujit_ch---d780febb\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\CoreRun.exe
> Return code: 1
> Raw output file: D:\j\workspace\x86_ryujit_ch---d780febb\bin\tests\Windows_NT.x86.Checked\Reports\Regressions\common\date\date.output.txt
> Raw output:
> BEGIN EXECUTION
> "D:\j\workspace\x86_ryujit_ch---d780febb\tests\..\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\corerun.exe" date.exe
> Expected: 100
> Actual: 123456789
> END EXECUTION - FAILED
> FAILED
> Test Harness Exitcode is : 1

**Comment by adiaaida** [comment]
This now fails with the following message:

Regressions\common\date\date.cmd
BEGIN EXECUTION
 "C:\michelm\coreclr\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\corerun.exe" date.exe

Assert failure(PID 11960 [0x00002eb8], Thread: 25480 [0x6388]): !CREATE_CHECK_STRING(!"Detected use of a corrupted OBJECTREF. Possible GC hole.")

CORECLR! Object::ValidateInner + 0x5FD (0x0f0fc34d)
CORECLR! Object::Validate + 0x152 (0x0f0fbad2)
CORECLR! OBJECTREF::OBJECTREF + 0x6D (0x0f0f3df0)
CORECLR! ArrayNative::InitializeArray + 0x69 (0x0f716309)
<no module>! <no symbol> + 0x0 (0x09c612ad)
CORECLR! CallDescrWorkerInternal + 0x34 (0x0f143631)
CORECLR! CallDescrWorker + 0xDE (0x0f3745ba)
CORECLR! CallDescrWorkerWithHandler + 0x137 (0x0f374756)
CORECLR! `DispatchCallDebuggerWrapper'::`3'::__Body::Run + 0x50 (0x0f375266)
CORECLR! DispatchCallDebuggerWrapper + 0x37 (0x0f3750ae)
    File: c:\michelm\coreclr\src\vm\object.cpp Line: 1842
    Image: C:\michelm\coreclr\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\CoreRun.exe

Expected: 100
Actual: 1
END EXECUTION - FAILED
FAILED

**Comment by pgavlin** [comment]
@dotnet/jit-contrib:

This failure is due to a GC hole that occurs whenever we pass a struct containing a GC reference on x86. RyuJIT/x86 passes such structs by storing each pointer-sized slot to the stack in sequence like so:

```
IN0009: 00002A sub      esp, 4
IN000a: 00002D mov      edi, esp
IN000b: 00002F lea      esi, [V00 ebp-0CH]
IN000c: 000032 mov      ecx, gword ptr [esi]
IN000d: 000034 mov      gword ptr [esp], ecx
IN000e: 000037 add      esi, 4
IN000f: 00003A add      edi, 4
IN0010: 00003D call     [Test:c(struct)]
```

Unfortunately, this is completely different from the legacy backend, which always passes such structs using `push`:

```
000028 8D45FC       lea      eax, bword ptr [ebp-04H]
00002B FF30         push     gword ptr [eax]
00002D FF152049CE02 call     [Test:c(struct)]
```

Because `FEATURE_FIXED_OUT_ARGS` is not defined on x86 and the legacy backend always uses `push` to store outgoing GC ref args to the stack, the emitter is not set up to recognize that the `mov` instructions emitted by RyuJIT/x86 need to have corresponding updates in the GC info.

The simplest fix for this is to always use `push` when storing outgoing GC ref args to the stack in the RyuJIT x86 backend. I think we already do this for arguments that are not struct fields, so the only problematic cases are struct fields (incl. elements of a `GT_FIELD_LIST`). A more involved fix might be to recognize the `mov, [eso], r32` pattern, though it is unclear how much work that would take.

**Comment by pgavlin** [comment]
For completeness, here are the GC info dumps for the two snippets shown above:

RyuJIT/x86:
```
0C             |             [EBP-0CH] an untracked  local
F3 4F          | 0027        reg ECX becoming live
F1 BF 73       | 003A        reg ESI becoming live (iptr)
F0 09          | 0043        reg ECX becoming dead
30             | 0043        reg ESI becoming dead
FF             | 
```

Legacy backend:
```
04             |             [EBP-04H] an untracked  local
F3 45          | 0025        reg EAX becoming live
06             | 002B        reg EAX becoming dead
BF 40          | 002B        reg EAX becoming live (iptr)
82             | 002D        push ptr  0
06             | 0033        reg EAX becoming dead
C8             | 0033        pop  1 ptrs
FF             | 
```

**Comment by BruceForstall** [comment]
This code is re-using the x64 code to copy structs to the stack, namely genPutStructArgStk(). Probably because it was convenient, and you can copy in normal order, not push in reverse order. (It's unfortunate that this code is essentially a clone of the cpobj code and doesn't share that code somehow.)

Rewriting this for x86 to use 'push' seems like a good thing, although there would likely be CQ decisions to be made here depending on the characteristics of the copy, like using rep or not.

Seems like teaching the the emitter about this is required.

**Comment by pgavlin** [comment]
> Seems like teaching the the emitter about this is required.

In the long term, I agree. In the short term, we should be okay if we always use `push` to store outgoing GC references to the stack.
