### ISSUE TITLE
JIT throughput: Eliminate setLastUses

### ISSUE THREAD

**Issue by CarolEidt** [dotnet/coreclr#7256]
`LinearScan::setLastUses()` was originally added because the ordering of local variable references within a statement was not always correct. I believe that those bugs have been fixed, so that this should be changed to a debug-only phase that validates that the last use info is correct.

**Comment by pgavlin** [comment]
Liveness is definitely still broken here.

The fundamental issue is that liveness and LSRA use different orderings for lclVar uses: liveness considers a use of a lclVar to occur at the point at which the corresponding `GT_LCL_VAR` node appears in code order, while LSRA (correctly) considers a use of a lclVar to occur at the node that uses the `GT_LCL_VAR` node. This is further complicated by the presence of contained nodes: because the execution of a contained node is subsumed by that of its user, any operands to a contained node become operands to its user. Phrased differently, the set of operands to a node N is the union of its non-contained operands and the transitive closure of the operands to its contained operands, and correctly visiting nodes in use order requires calculating this closure. This calculation is not complicated, but it isn't free: adjusting liveness to properly visit a node's operands for the purposes of marking last uses is certainly going to come at some cost. LSRA already pays this cost during `buildRefPositionsForNode` and persists the proper ordering of uses in its data structures, which allows it to accurately recompute last use information.

From what I see, we three options here:
1. Leave things as they are. I don't feel like this is a particularly bad design, but it does cost us some throughput, and I think we can do better.
2. Perform last-use computation as part of `buildRefPositionsForNode`. This is actually pretty simple: at each kill for a lclVar interval, mark the most recent ref position in that interval as a last use. The trick here is getting the set of kills correct; I think it's just (defs, block ends where the lclVar is not live-out). This option takes advantage of the fact that we are already doing the work in LSRA to visit uses in the correct order.
3. Fix liveness to visit uses in the correct order during `fgComputeLifeLIR`. This is not terribly difficult--it just requires some extra code to visit a node's operands (taking care with operands that are contained nodes) and to ensure that nodes are not multiply-visited--but it ends up redoing some work that LSRA is going to do anyway (i.e. figuring out what the operands to a node actually are).

I think that for now we should go with option (2) above: aside from LSRA, there aren't any phases that really depend on last-use information (it does get consumed during codegen, but I don't *think* that it's necessary for correctness), so the extra cost of option (3) doesn't really add any corresponding value.

@BruceForstall @sivarv @russellhadley thoughts?
