### ISSUE TITLE
Bump Clang version to 3.6?

### ISSUE THREAD

**Issue by janhenke** [dotnet/coreclr#740]
I want to discuss switch to Clang 3.6 for compiling CoreCLR. We are already using LLDB from the LLVM 3.6 release. It would be more consistent to use Clang from the same release.

For the Ubuntu 14.04 machines I created a PPA, which brings the LLVM 3.6 release from Ubuntu 15.04 to Ubuntu 14.04. It is available here: https://launchpad.net/~jhe/+archive/ubuntu/llvm-toolchain

**Comment by jkotas** [comment]
We will likely raise the min bar at some point in future, but it is going to be a while.

We would like to support range of recent OS and compiler versions, to lower bar for adoption. Also, we require that the official build is done by officially released build of compilers.

LLDB 3.6 on Linux is outlier. We had to switch to it for SOS extension because of LLDB 3.5 on Linux is pretty broken (known bug, fixed in 3.6). LLDB 3.6 is actually not required to build. The build will skip the SOS extension if LLDB dev package is not present.

So far, we have not run into any problems from mixing Clang 3.5 with LLDB 3.6.

**Comment by janhenke** [comment]
Okay. As an alternative I will look into changing the build.sh file to accept an optional version parameter, so the used version can be specified. Would that work for you? It could be handy to test newer version easily without bumping the default.

**Comment by jkotas** [comment]
Sounds good to me.

**Comment by josteink** [comment]
I'm also for having clang-version easily selected with a parameter.

I know the FreeBSD-build isn't up and going yet, but if all it takes to *test* it is tweaking a parameter, I can quickly provide feedback if a potential clang-upgrade in the future will be causing troubles in FreeBSD-land or not.
