### ISSUE TITLE
Heap Allocations/Large Pages

### ISSUE THREAD

**Issue by bjjzqd** [dotnet/coreclr#748]
I am curious how the gc increases the size of the managed memory when allocating new objects. Can you describe how the allocator determines the size to increase a heap segment by? In the documentation it states typical allocations are 8k - are allocations in any way biased towards this size?

I am interested in experimenting with larger allocation sizes and even using the OS's support for large pages (2MB+). Has anyone done any past experimentation in those areas?

@Maoni0

**Comment by Maoni0** [comment]
The doc says allocation *quantum* is typical 8k: 

"The Allocation quantum is the size of memory that the allocator allocates each time it needs more memory, in order to perform object allocations within an allocation context. The allocation is typically 8k and the average size of managed objects are around 35 bytes, enabling a single allocation quantum to be used for many object allocations."

is this what you want to experiment with? Or were you referring to something else?

**Comment by bjjzqd** [comment]
Yes, I want to experiment with increasing the allocation quantum, or at least understand how the allocation quantum is decided.

**Comment by Maoni0** [comment]
This is explained in the doc:

"Efficient cache usage: The allocator allocates memory in allocation quantum units, not on an object-by-object basis. It zeroes out that much memory to warm up the CPU cache because there will be objects immediately allocated in that memory. The allocation quantum is usually 8k."

Obviously the number could be larger if you are asking for an object that's larger than 8k.

**Comment by benaadams** [comment]
@bjjzqd I think it uses the process's page size https://github.com/dotnet/coreclr/blob/4cf8a6b082d9bb1789facd996d8265d3908757b2/src/jit/alloc.cpp#L130 though it doesn't look like it includes the [MEM_LARGE_PAGES](https://github.com/dotnet/coreclr/blob/4cf8a6b082d9bb1789facd996d8265d3908757b2/src/jit/alloc.cpp#L140) flag if the [OS_page_size](https://github.com/dotnet/coreclr/blob/4cf8a6b082d9bb1789facd996d8265d3908757b2/src/jit/alloc.h#L107) > normal which would be required by [VirtualAlloc](https://msdn.microsoft.com/en-us/library/windows/desktop/aa366887(v=vs.85).aspx)

You also need to [escalate privileges](https://msdn.microsoft.com/en-us/library/windows/desktop/aa366720(v=vs.85).aspx) I think to use Large Page support; unsure that the Allocator would refresh its value though?
