### ISSUE TITLE
First class structs additional types TYP_STRUCT[16|24|32]?

### ISSUE THREAD

**Issue by benaadams** [dotnet/coreclr#7525]
The [First class structs](https://github.com/dotnet/coreclr/blob/master/Documentation/design-docs/first-class-structs.md) document mentions the additional types TYP_STRUCT[1|2|4|8]

Could this be extended to include the types TYP_STRUCT[16|24|32]?

For example

(16 bytes with padding - one xmm register)

``` csharp
struct ReadCursor
{
    BufferSegment Segment; // ptr
    int Index;
}
```

(32 bytes with previous padding - two xmm registers or one ymm register)

``` csharp
struct ReadableBuffer
{
    ReadCursor Start;
    ReadCursor End;
}
```

Or unwrapped
(24 bytes)

``` csharp
struct ReadableBuffer
{
    private BufferSegment startSeg; // ptr
    private BufferSegment endSeg; // ptr
    private int startIndex;
    private int endIndex;

    ReadCursor Start => new ReadCursor(startSeg, startIndex);
    ReadCursor End => new ReadCursor(endSeg, endIndex);
}
```

Which would allow these types to be passed in registers 

/cc @CarolEidt

**Comment by RussKeldorph** [comment]
@dotnet/jit-contrib

**Comment by CarolEidt** [comment]
Unfortunately, adding these types would not easily enable them to be passed in registers on Windows, and the unix ABI only supports passing *some* 16 byte types in registers. We follow the platform calling convention so that calls to/from managed to native code work correctly. We have discussed the possibility of using xmm/ymm registers on x86/x64 for passing `Vector<T>` as it is not an interop type.
