### ISSUE TITLE
RyuJIT x86: Assertion failed '!"unknown shared statics helper"'

### ISSUE THREAD

**Issue by adiaaida** [dotnet/coreclr#7546]
set complus_altjitngen=*

crossgen.exe Microsoft.CodeAnalysis.dll

Assert failure(PID 8400 [0x000020d0], Thread: 27364 [0x6ae4]): Assertion failed '!"unknown shared statics helper"' in 'Roslyn.Utilities.ObjectWriterData:.ctor(ref):this' (IL size 102)
    File: c:\michelm\coreclr\src\jit\flowgraph.cpp Line: 6866
    Image: C:\michelm\coreclr\bin\Product\Windows_NT.x86.Checked\crossgen.exe

**Comment by mikedn** [comment]
Looks like another Ready to Run thing: CORINFO_HELP_READYTORUN_STATIC_BASE

**Comment by sandreenko** [comment]
Was fixed in #7576.
There are a lot of messages like
"Failed to load type token 69003027 for the profile data in [C:\git\coreclr\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\Microsoft.CodeAnalysis.dll] The type specified by the IBC data is no longer present in the assembly's metadata.  The type was [System.Collections]System.ArrayT`1."

But
"Native image C:\git\coreclr\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\Microsoft.CodeAnalysis.ni.dll generated successfully."
