### ISSUE TITLE
RyuJIT x86: [GCStress=0xC] !CREATE_CHECK_STRING(!"Detected use of a corrupted OBJECTREF. Possible GC hole.")

### ISSUE THREAD

**Issue by adiaaida** [dotnet/coreclr#7548]
Assert failure(PID 848 [0x00000350], Thread: 8416 [0x20e0]): !CREATE_CHECK_STRING(!"Detected use of a corrupted OBJECTREF. Possible GC hole.")
02:45:14         
02:45:14         CORECLR! Object::ValidateInner + 0x5FD (0x708ec3ed)
02:45:14         CORECLR! Object::Validate + 0x152 (0x708ebb72)
02:45:14         CORECLR! Object::ValidatePromote + 0x11 (0x708ec41d)
02:45:14         CORECLR! WKS::GCHeap::Promote + 0x118 (0x70e16bb8)
02:45:14         CORECLR! ReportPointersFromValueType + 0x77 (0x70b51917)
02:45:14         CORECLR! ReportPointersFromValueTypeArg + 0x23 (0x70b51962)
02:45:14         CORECLR! MetaSig::GcScanRoots + 0x32A (0x70b4c320)
02:45:14         CORECLR! TransitionFrame::PromoteCallerStackHelper + 0x112 (0x70ab8c22)
02:45:14         CORECLR! TransitionFrame::PromoteCallerStack + 0xA9 (0x70ab8afe)
02:45:14         CORECLR! GcStackCrawlCallBack + 0x20F (0x70d4f82f)
02:45:14             File: d:\j\workspace\x86_ryujit_ch---ddc305d1\src\vm\object.cpp Line: 1842
02:45:14             Image: D:\j\workspace\x86_ryujit_ch---ddc305d1\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\CoreRun.exe
02:45:14         
02:45:14         
02:45:14   
02:45:14   Return code:      1
02:45:14   Raw output file:      D:\j\workspace\x86_ryujit_ch---ddc305d1\bin\tests\Windows_NT.x86.Checked\Reports\JIT\jit64\gc\misc\structfp3_1\structfp3_1.output.txt
02:45:14   Raw output:
02:45:14   BEGIN EXECUTION
02:45:14          "D:\j\workspace\x86_ryujit_ch---ddc305d1\tests\..\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\corerun.exe" structfp3_1.exe 
02:45:14         Expected: 100
02:45:14         Actual: 123456789
02:45:14         END EXECUTION - FAILED
02:45:14         FAILED
02:45:14         Test Harness Exitcode is : 1
02:45:14         
02:45:14   To run the test:
02:45:14   > set CORE_ROOT=D:\j\workspace\x86_ryujit_ch---ddc305d1\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root
02:45:14   > D:\j\workspace\x86_ryujit_ch---ddc305d1\bin\tests\Windows_NT.x86.Checked\JIT\jit64\gc\misc\structfp3_1\structfp3_1.cmd
02:45:14   
02:45:14         Expected: True
02:45:14         Actual:   False

**Comment by pgavlin** [comment]
I looked into a similar issue this morning that appeared to be due to missing GC info for the code generated for a `storeBlk` node.

**Comment by pgavlin** [comment]
After further investigation, the root cause of this failure appears to a bad interaction between a fully-interruptible method and the code generation for a GC-unsafe `GT_STORE_BLK`. For these sorts of stores, the code generator encloses the copy within a non-interruptible region. As far as I can tell, however, this does not cause the method to be marked partially-interruptible.

@briansull: does the x86 GC encoding have the capability to mark a particular region of code as non-interruptible in a method that is otherwise fully-interruptible? It looks like there are a few other constructs for which we attempt to use non-interruptible regions that may also be affected.

cc @CarolEidt @dotnet/jit-contrib

**Comment by briansull** [comment]
No on JIT32 a method is either entirely fully interruptible or entirely partially interruptible, no mixing.

JIT64 introduced that and I don't think that it was a good idea to have special areas that have to be non-interruptible
