### ISSUE TITLE
Performance regression in RyuJIT vs, LegacyJIT 

### ISSUE THREAD

**Issue by ayende** [dotnet/coreclr#7564]
See the code here:

https://gist.github.com/ayende/3993d6631b583650a6fb87475530f68a#file-lazystringparser-cs

And the benchmark here:

https://gist.github.com/ayende/87281557ed5913459f28ea09e9d5a340#file-dateparsingbench-cs

With LegacyJIT, we see times in the 71 ns.
With RyuJIT, we see times in the 95 ns.

**Comment by mikedn** [comment]
Are these results from CoreCLR's RyuJIT (and if so which version) or from .NET Framework's RyuJIT?

**Comment by redknightlois** [comment]
RyuJIT CoreCLR 1.0.1 afaik.

**Comment by mikedn** [comment]
One obvious difference is that RyuJIT loads `ptr[i]` from `TryParseNumber` 3 times instead of loading it once and keep it in a register. But that doesn't seem to impact performance much.

The actual problem appears to be in `DateTime`'s constructor, more precisely in the `DateToTicks` method that it calls. This method accesses a static field and that requires a helper call when mscorlib is NGENed.

Now you'll probably ask - what has the legacy JIT to do with NGEN? Well, it looks like in .NET 4.6.2 using the legacy JIT results in the mscorlib native image being ignored. When that happens the JIT generates code at runtime for `DateToTicks` and that code doesn't have the helper call. To confirm you could try running your code on CoreCLR after deleting `System.Private.CoreLib.ni.dll`.

**Comment by pgavlin** [comment]
cc @dotnet/jit-contrib

**Comment by RussKeldorph** [comment]
@ayende Did you happen to run the experiment suggested by @mikedn?

**Comment by ayende** [comment]
@RussKeldorph No, we left it.

**Comment by pgavlin** [comment]
@ayende given the lack of traffic, I am going to close this for now. Please feel free to reopen if this remains an issue.
