### ISSUE TITLE
Publish a guide how to create app that is able to run on coreclr

### ISSUE THREAD

**Issue by Alexx999** [dotnet/coreclr#76]
Because it is not that trivial, especially if you want to use Visual Studio and replace mscorlib to know about missing methods like Console.ReadKey.
Also, it does not support apps compiled with AnyCPU - that's not obvious at all.

Plus there is no System.dll - is this OK? For example MeasureIt tool you mention in #72 depends on it, so it can't be run yet.

**Comment by maxinfet** [comment]
This would be really useful

**Comment by poizan42** [comment]
Here is what I did to build a project in visual studio, I don't know if that is the best way but feel free to use as basis for a guide.

First create a normal C# (or your .net language of choice) project. The open the project file in a text editor and edit the following:

In the Debug|AnyCPU and Release|AnyCPU sections add `<NoStdLib>true</NoStdLib>`.

Remove all the `<Reference>`'s and replace them with
```xml
    <Reference Include="mscorlib">
      <HintPath>(path to CoreCLR output directory)\mscorlib.dll</HintPath>
    </Reference>
```

This works fine for testing locally, but hardcodes the path to mscorlib. Furthermore Visual Studio have a tendency to automagically find a "better" mscorlib to change to hint path to if the file is at any time removed while VS is running.

For something using System.dll I think you need to build CoreFX as well and explicitly reference it the same way (it may not work if you try to add the reference from VS because it *really* wants to use a version from the GAC, though this may not be a problem as long as you only use apis available in CoreFX).

Also don't try to launch your project under the debugger in VS by setting it to run CoreRun.exe - this seems to crash the debugger. Instead launch it from a C++ project such as the INSTALL project as suggested by the guide (the INSTALL project has all the necessary projects as requirements) - or use WinDbg.

**Comment by Alexx999** [comment]
@poizan42 well, that's what I've done before opening this issue. However, that's not straightforward, so it would be nice to have such guide in docs.
And yeah, System.dll should be probably replaced by CoreFx. Too bad it misses some features.

PS: You can add NoStdLib before Debug/Release sections just once.

**Comment by weshaggard** [comment]
Have you guys looked into the [demo](https://github.com/dotnet/corefxlab/blob/master/demos/CoreClrConsoleApplications/HelloWorld/HelloWorld.cs) we posted on the [announcement blog post](http://blogs.msdn.com/b/dotnet/archive/2015/02/03/coreclr-is-now-open-source.aspx). I think that is the best we have right now but I know that @KrzysztofCwalina is working on some better console app support for CoreCLR.

**Comment by kangaroo** [comment]
Is this still an issue?  While better documentation and guides are always a stretch goal, I think the current documentation is sufficient for the current use cases.  Can we close this out?

**Comment by weshaggard** [comment]
Yes see the sample in the corefxlab repo https://github.com/dotnet/corefxlab/wiki/.NET-Core-Console
