### ISSUE TITLE
Validate that mscordaccore.dll's minidump auxiliary code works properly

### ISSUE THREAD

**Issue by leculver** [dotnet/coreclr#7723]
We need to validate that mscordaccore's minidump auxiliary data stream code path works properly.  This code likely hasn't been tested since Silverlight days, so we need to make sure there are no issues when running it and that minidumps are generated properly.

Noah would have the most context on this.

**Comment by lt72** [comment]
@noahfalk: please check that there is no blocking issue to enable this. 
@alsemenn: please check with Noah and then move to this work asap item if there is not blocker.

**Comment by noahfalk** [comment]
Manually it can certainly be done. In an automated fashion the main hiccup is that it requires writing a machine global registry key with administrative permission. Depending on the environment where tests are running we may not have that capability.

Aside from that its just work to bring tests online.

@leculver - Have you solved the deployment issue with writing the registry key? If we are going to test it would be good to understand the E2E how this gets used so that we are testing it accurately.

**Comment by lt72** [comment]
Manual is fine for the release. Automation right after as part of the test set we are enabling anyway.

**Comment by gkhanna79** [comment]
@alsemenn Can this be closed?
