### ISSUE TITLE
Support a way to indicate whether a PInvoke call needs to be surrounded by Vzeroupper on AVX hardware

### ISSUE THREAD

**Issue by sivarv** [dotnet/coreclr#7761]
Right now RyuJIT emits VzeroUpper in prolog and epilog of methods that use AVX 32-byte vector operations.  But vzeroupper is not emitted around PInvoke calls for the reason that it could lead to unnecessary code size increase in majority of cases where SIMD intrinsics are not used.

But it is possible that a method is both using SIMD intrinsics and also Pinvoke to native layer that might be executing SSE2 code.  Kesteral server has such methods.  This will lead to avx-sse transition penalty as noted in benchmark analysis https://github.com/dotnet/coreclr/issues/7240

The following are the possible solutions:
0) JIT always emits vzeroupper around Pinvoke calls - this has the drawback that we will incur code size increase in majority of the cases where SIMD intrinsics are not used or if used, not executed on AVX hardware.

1) Support vzeroupper intrinsic - this doesn't fit within the design goals of SIMD API and specific to AVX hardware.  

2) Extend DllImportAttribute to indicate whether such a pinvoke call needs to be surrounded by vzeroupper.  That info could be exposed by VM to JIT through a flag on call node.  If such a flag is set JIT will emit vzeroupper around the Pinvoke call.

**Comment by sivarv** [comment]
CC @CarolEidt

**Comment by jkotas** [comment]
This problem is not limited to PInvoke calls. Virtual calls (that can end up calling PInvoke) suffer from the same problem.

This looks like another case of mismatch between what the current SIMD provide vs. what is actually needed for fine tuned SIMD code, as discussed in https://github.com/dotnet/coreclr/issues/6906. 

cc @redknightlois

**Comment by redknightlois** [comment]
I agree with @jkotas the underlying issue is pervasive to the entire SSE codegen. We can continue plugging holes, but eventually we will draught in complexity. An API design leveraging intrinsics would solve the issue for good, even though that would require to rewrite numerics in pure managed code (which doesn't sounds like a bad idea either).

**Comment by sivarv** [comment]
This is longer required with PR https://github.com/dotnet/coreclr/pull/8588
Now JIT is generating vzeroupper in the following cases:
1) just before a PInvoke if the method is known to contain 256-bit AVX instructions.
2) in method prolog if the method is known to contain 128-bit or 256-bit AVX instructions so that when  Reverse PInvoked by a native routine that uses legacy SSE will not incur transition penalty.
