### ISSUE TITLE
Expose a 64-bit monotonic timer

### ISSUE THREAD

**Issue by nvivo** [dotnet/coreclr#779]
.NET currently exposes Environment.TickCount which is 32 bit.

Would be nice if a 64-bit monotonic timer was provided based either on `GetTickCount64` or something else, so we can avoid different dependencies on windows and mono.

**Comment by jkotas** [comment]
Take a look at System.Diagnostics.Stopwatch.

If there are things you would like to see improved in Stopwatch, https://github.com/dotnet/corefx/ is the right repo for that. The code for System.Diagnostics.Stopwatch should show up in the corefx repo soon.

**Comment by nvivo** [comment]
I'm aware of stopwatch.  But those are different things. TickCount is implemented in coreclr repo.

**Comment by nvivo** [comment]
Just for clarification:

Most people implement a call to GetTickCount64 because it's faster than QueryPerformaceCounter and high precision is not required. 

It seems Threading.Timer uses another yet implementation different from QueryPerformanceCounter on newer Windows versions. 

The point is that the only fast monotonic counter exposed is TickCount that is 32 bit and there is no reason to not expose a 64 bit one,  since this is already available in windows and mono and most cpus are 64 bit nowadays.

This helps to avoid writing logic to handle overflows on 32 bit timers.

**Comment by nvivo** [comment]
@jkotas I know this is still early, but is this something that can be considered?

**Comment by jkotas** [comment]
https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/api-review-process.md describes the process for adding new APIs. I would recommend starting with the speclet for the new API. For example, it would be very useful to have a example of real world code that would be simpler or otherwise better if this API is available.

@weshaggard @AlexGhiondea do we have still the guidance to track any API additions under corefx repro?

**Comment by AlexGhiondea** [comment]
Yes -- that is the right thing to do (start with CoreFx).

**Comment by nvivo** [comment]
Thanks. I'll do that.
