### ISSUE TITLE
", >, and < are valid wildcard characters 

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/coreclr#7830]
FsRtllsNameInExpression offers MS-DOS-compatible wildcard characters: DOS_DOT, DOS_QM, and DOS_STAR, corresponding to ", >, and <, respectively. System.IO.PatternMatcher attempts to support these, so they should be treated as valid characters. Otherwise, behavior is inconsistent throughout .NET. See http://stackoverflow.com/a/17739503/1188377

Note that this pull request lacks a related bug fix that can be found at Microsoft/referencesource#19, as dotnet/coreclr currently lacks PatternMatcher. For correct functionality of > and <, the typos in PatternMatcher need to be fixed; until then, their functionality is swapped.

This was the premise of PR https://github.com/dotnet/coreclr/pull/3942 which was abandoned due to age.

**Comment by am11** [comment]
@danmosemsft, the Path.cs implementation has been changed (moved from CoreFX) since the PR: https://github.com/dotnet/coreclr/blob/ee5862c/src/mscorlib/corefx/System/IO/Path.Windows.cs#L21-L28.
Is the remaining work to remove `(char)22` (i.e. `"`) from line 26?

(also I noticed that the current CoreFx internal implementation of same is bit out of sync: https://github.com/dotnet/corefx/blob/9c06da6/src/Common/src/System/IO/PathInternal.Windows.cs)

**Comment by danmosemsft** [comment]
@JeremyKuhne for this question

**Comment by JeremyKuhne** [comment]
It is (char)22 (SYNC, or CTRL-V) not (char)0x22. :)

I had updated the path code with #8669. That code was later moved down to CoreCLR and optimized. We're currently working on the UAP builds of CoreFX- the code in CoreFX will be pulled when we make the same changes to CoreRT and the UAP runtime.

Afaik that means this issue is addressed? Or was there some other location you know of, @danmosemsft?

**Comment by danmosemsft** [comment]
I don't know anything about this issue, I just recorded it from an old PR. 

I"ll close then, feel free to reactivate
