### ISSUE TITLE
Testing-with-corefx instructions out of date

### ISSUE THREAD

**Issue by Clockwork-Muse** [dotnet/coreclr#7841]
The [instructions](https://github.com/dotnet/coreclr/blob/master/Documentation/building/testing-with-corefx.md) for testing with corefx basically consist of this:

> As part of building tests, CoreFX restores a copy of the runtime from myget, in order to update the runtime that is deployed, a special build property BUILDTOOLS_OVERRIDE_RUNTIME can be used. If this is set, the CoreFX testing targets will copy all the files in the folder it points to into the test folder, overwriting any files that exist.
> To run tests, follow the procedure for running tests in CoreFX. You can pass /p:BUILDTOOLS_OVERRIDE_RUNTIME=<path-to-coreclr>\bin\Product\Windows_NT.x64.Release to build.cmd to set this property.

.... but the instructions are out of date, and doing so causes an exception (if calling `build` from the root of the repository), or does nothing (if calling from a child project, or using msbuild)

**Comment by danmosemsft** [comment]
@ellismg looks related to https://github.com/dotnet/buildtools/pull/753. Do you expect this to work?

This is the first I've seen of this mechanism and I certainly would find it useful to be able to run tests including changes I've made in coreclr. What would be particularly useful is if it could include mscorlib symbols, since then we could get code coverage data.

**Comment by Clockwork-Muse** [comment]
Hmmm... It hasn't been able to pull in coreclr stuff since around that time, or at least not going by those instructions (at the time I was dealing with changes to BitArray).  Or it's possible that it just no longer pulls in mscorlib while doing so.

**Comment by RussKeldorph** [comment]
Note that we have CI jobs, e.g. [baseline](http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_ubuntu_corefx_baseline_prtest/), for dotnet/coreclr that use this mechanism.  They are broken in master now for a number of reasons, but I plan to get them working again soon.  If you need additional functionality like coverage, please consider building on what we have rather than inventing something new.

**Comment by Clockwork-Muse** [comment]
Instructions have been updated, and they work.  HOWEVER, if the directory doesn't exist the corefx build system proceeds with grabbing the "default" runtime, meaning it can be difficult to recognize that you didn't actually run against a live CLR.  Don't know if we should make it throw an error in that case...

**Comment by xoofx** [comment]
Is `BUILDTOOLS_OVERRIDE_RUNTIME` still used for building corefx with a local coreclr build? Not able to get it running and I don't see this variable used apart from a sh script, so this might not work on Windows then?

**Comment by xoofx** [comment]
nevermind, `BUILDTOOLS_OVERRIDE_RUNTIME` seems to be working.

**Comment by gkhanna79** [comment]
@wtgodbe PTAL

**Comment by wtgodbe** [comment]
@danmosemsft is this doc now up-to-date with https://github.com/dotnet/coreclr/commit/e50207b834d9946027828f8c3b3467e29ac2efb1 ?

**Comment by danmosemsft** [comment]
I think the instructions work -- I'm not sure whether "if the directory doesn't exist the corefx build system proceeds with grabbing the "default" runtime, " is still an issue since it's churned since then.. I suggest we close and see whether anyone still has issues.
