### ISSUE TITLE
Span<T> design question

### ISSUE THREAD

**Issue by bencyoung** [dotnet/coreclr#8054]
I had a question on the Span<T> type and its design relating to arrays, slices and unmanaged memory. 

The idea as I understand it is that the Span will be stack only so that it can safely point to stack allocated or otherwise scoped memory, but it seems to me it would be nicer if the *instance* was scoped instead of the type? That way you could simply reuse the array syntax for Span<T>, and if you need an API that supports stack allocated or native memory then you specify that in the contract. It would be similar to the ref returns API I guess.

The important point is that you wouldn't need new classes like Span and Memory, it would all be done via the array syntax. You would perhaps want a new readonly array class though. Some examples (I'm using "nocapture" as a keyword, but it's not a nice one....)

Slicing:
```csharp
int[] a = new[] {1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
int[] b = a.Slice(3, 2); // Looks exactly like a normal array
// b == {4, 5}
```

Stack allocated:
```csharp
nocapture int[] = stackalloc int[10]; // Can only be passed to nocapture methods

// This API can parse slices, native memory, stackallocated etc
void int Parse(nocapture char[] data)
```

Native:
```csharp
int* rawData;
nocapture int[] = BindNative(rawData, length); // Bind the native memory to an uncapturable array
```

I believe Joe Duffy mentioned something somewhat like this in his recent Midori series.

Objects that are only passed to nocapture methods could potentially be stack allocated and a reference passed

Anyway, I was just wondering if this kind of approach had been considered and discarded, or if there are other factors at play here?

**Comment by KrzysztofCwalina** [comment]
@jaredpar was the main person designing "no capture". he should be able to best describe the difficulties/trade-offs here.

**Comment by jaredpar** [comment]
The problem with nocapture is that it's incredibly viral as a general purpose feature.  Consider for example this simple code:

``` csharp
nocapture MyType t = new MyType();
t.ToString();
```

In order for this code to be safe it requires modifications to the constructor and `ToString` method on `MyType`.  Both of these members have the potential to capture `this` and must be protected to prevent it from happening.  This restriction applies to any members these members might call into: base constructors, helper methods, etc ...   It certainly can be done and there are sound approaches to doing it, but it's quite viral in anything but the most trivial of samples. 

It also has some interesting consequences for core types like delegate.  Consider for a minute that `MyType.ToString` method is annotated such that `this` can't be captured.  This means the following conversion cannot work:

``` csharp
MyType t = new MyType();
Func<string> s = t.ToString(); // Error 
```

Even though the local `t` is not marked as nocapture, the method ToString is.  Hence it can't safely convert to a delegate where the `this` value can be freely captured.  Otherwise it would be trivial to escape a nocapture through the delegate members (or by just capturing the delegate itself).

There are many, many examples you can go into here.  All can be solved with enough work but it's a **ton** of work because C# / .NET really wasn't designed for this type of feature.

**Comment by bencyoung** [comment]
Thanks jaredpar, that's very useful feedback. I guess some of this would be more suited to a new language (something like an amalgam of C# and Rust seems close to the perfect language to me)

On your specific points, to keep backwards compatibility, as you say,  you wouldn't be able to add nocapture to things like ToString, and so you wouldn't be able to call ToString (or GetHashCode) on a "non capturable" reference. I'm not sure if that would be the end of the world though. Concrete overloads would be able to safely add nocapture in a covariant fashion I think, but any call through "object" would have to keep the current API (and assume ToString could in theory capture)

I'm not sure I agree with your delegate example (or I may be misunderstanding). Even if ToString does not capture "this", it doesn't mean this can't be captured outside. I see this binding happening externally to the signature of the method

```csharp
class X
{
  nocapture string Print() {...}
}

var x = new X()
Func<string> print = bind(x, X.Print); // Fine as x is not nocapture

nocapture var x = new X()
nocapture Func<string> = bind(x, X.Print); // Fine as the delegate has a smaller scope than x

nocapture var x = new X()
Func<string> = bind(x, X.Print); // Error, would allow capturing x via the backdoor
``` 

I do agree it would be viral, but I'm not sure it needs to be initially any more viral than the Span<T> type will be, as I can see us using that all through the code where we're trying to avoid allocations etc!

This is a theoretical discussion though, and I am extremely glad to see these new high perf APIs being added to .NET. It has been very hard to tread the right path between readability and performance up till now.

**Comment by jaredpar** [comment]
> On your specific points, to keep backwards compatibility,  ...  I'm not sure if that would be the end of the world though. 

It's not the end of the world for sure, but it's generally the end of a feature. :smile:

Back compat, love or hate it, is king.  Every time you break compat in the language, even in the smallest most esoteric ways, you break customers.  Typically a lot of customers. 

> Concrete overloads would be able to safely add nocapture in a covariant fashion I think, but any call through "object" would have to keep the current API (and assume ToString could in theory capture)

An overload of a nocapture must maintain the nocapture semantics.  Otherwise it's possible to violate nocapture rules by capturing 'this' in an override of `ToString`.  

Or in shorter: an override can add nocapture but it cannot remove it. 

> I'm not sure I agree with your delegate example (or I may be misunderstanding). 

Based on your example you seem to have a grasp of the problem I was pointing out.  The nocapture is essentially viral and the annotation on the delegate essentially has to match the annotation of the caller.  

It's actually a bit more viral than the sample alludes to.  Think about the problem of type checking a method marked as nocapture.  So far we've only discussed it in terms of the `this` parameter.  Essentially a method marked as nocapture must ensure only the `this` value isn't captured.  Yet the way you've written the delegate sample implies it's actually more restrictive.  

Look deeper into the delegate type and you'll see a `class` with roughly the following outline:

``` csharp
class Delegate {
  private object _target;
  private IntPtr _method;

  public object Target => _target;
  public IntPtr Method => _method;

  protected Delegate(object target, IntPtr method) {
    _target = target;
    _method = method;
  }
}
```

In order for `nocapture Func<string>` to be safe in your sample it must ensure that both `this` and `_target` are not captured.  Otherwise I could escape a nocapture object trivially by doing the following:

``` csharp
nocapture X local = ...;
Func<string> func = local.ToString;
X local2 = func.Target;
```

For the sample you wrote to type check it would imply that nocapture must ensure that `this` and all reachable references from `this` are not captured.  That's downright draconian and falls apart very quickly in more complex types: most notably collections and enumeration. 

Solving that problem more elegantly requires a parametric polymorphism solution.  Essentially a way to mark fields and members as nocapture if the caller is also nocapture.  It works and can type check pretty reasonably but it's also a bit more advanced than the average C# user is used to .

**Comment by bencyoung** [comment]
Hi Jaredpar, I think we are in agreement! I meant that it wouldn't be the end of the world if you couldn't call ToString on a nocapture variable (i.e. you could add a covariant nocapture in a derived class, but not remove it). And I completely agree on the delegate thing. Passing a nocapture variable to a constructure would have to mean it flowed to the fields somehow too. 

Thanks for going through your thought processes. Looking forward to getting Span. I imagine it's going to be lots of work flowing it through all the parse methods etc, especially if both utf8 and utf16 variants are supported!
