### ISSUE TITLE
Investigate locked-free implementations of ArrayPool

### ISSUE THREAD

**Issue by stephentoub** [dotnet/coreclr#8203]
ArrayPool currently uses a SpinLock per bucket to protect each bucket's state.  The lock covers only a small number of instructions and generally performs well.  However, if a thread happens to be interrupted while holding the spin lock, all other threads can be prevented indefinitely from making forward progress.

**Comment by benaadams** [comment]
Lower contention would be good too; whether that's multiple pools per bucket based on bounded Interlocked.Increment or a ThreadLocal/Static

**Comment by stephentoub** [comment]
> Lower contention would be good too; whether that's multiple pools per bucket based on bounded Interlocked.Increment or a ThreadLocal/Static

Potentially, but that's a separate issue, involving a different set of tradeoffs.

**Comment by benaadams** [comment]
> Potentially, but that's a separate issue, involving a different set of tradeoffs.

Ah, yeah is mentioned here https://github.com/dotnet/coreclr/issues/7747#issuecomment-261129073

**Comment by redknightlois** [comment]
We use a tiered structure which works pretty well in practice without the needs of locks for the lower most immediate part. 

We distribute the arrays into their own thread based storages and only when we are going to evict an array we move it to the higher global level (which requires the locks). In that design, it doesnt matter if someone rents an array on one thread and returns it in a different one, because in practice all belong on the global pool. The only thing you have to be careful when coding it is into ensuring that there cannot be thread-hops during the renting and returning methods. So you need to use a Thread Storage that is aware of async/await contexts.

**Comment by stephentoub** [comment]
@redknightlois, can you elaborate?  How does one thread get at an array that's stored in another thread's local data structure?  What you describe sounds slightly similar to a work-stealing data structure, but even there locks are necessary even for local access when the number of items in the local queue is sufficiently low that there could be a conflict between the local thread accessing an element and another thread trying to steal one.

**Comment by redknightlois** [comment]
Probably I didn't explain correctly, there is no work-stealing kind of data structure. 

- Each thread has its own local thread storage.
- There is a global storage.

Say thread-1 rented an array, life goes on and then that object was moved to thread-2 (we have worker and writers, so that happens a lot here). Then thread-2 is done with it and returns the array. All this can be done without needing a lock. 

Now the array has been taken from thread-1 storage, but has been returned to thread-2 storage. If for instance the dynamic behavior is thread-1 already rent and thread-2 always returns. thread-2 will start dumping arrays to the GC and thread-1 will be creating arrays continously.

In a 1-level (per-thread) storage system design we are suddenly failing to gain anything. We gain that we don't have contention, but we fail horrendously to account for those kind of use patterns (pretty common in a database btw :D ). But, having a global pool was not good either, the contention and lock performance was killing us. That's why we devised a tiered structure.

The per-thread holding structure will behave like a cache, if you need we will try to get it from the cache (the code is so small that you can even force inlining of that); only if we fail we are going to move to the global tier and rent from there (and pay the lock cost). When returning it is more or less the same, we first try to return it into the per-thread pool, if that fails, we evict a few of the ones we have in the thread to the global tier. Only when the global tier is full the GC will need to start taking care of those arrays. 

What would happen in an scenario like the one I have layout? Since every time the per-thread storage is full, we return a fraction of the arrays stored there you will have a cyclic behavior. thread-1 gets a few from that size bucket from the global tier, thread-2 returns it into it's own storage, eventually thread-2 is gonna became full, and return a few of them back into the global tier; and so on.

Does it makes sense?

**Comment by stephentoub** [comment]
> Does it makes sense?

Yes, thanks for the explanation. This is a fairly typical tiered strategy.  And it has some of the tradeoffs I hinted at in my initial response to Ben.  For example, the more threads you have, the more arrays you can end up caching, potentially unbounded (without additional synchronization), and arrays that are valid and created can be completely unavailable to other threads.  That may be an entirely valid strategy for certain applications, but it's something we have to be extremely careful of in a general pool, as it can lead to degenerate behaviors.  This is why I believe it's a separate issue.

**Comment by redknightlois** [comment]
Ahhh, OK. If you need something bounded, you should look into a cache line optimized ring-buffer. In that way you can do lock-free acquisition and release in a bounded environment. It is very good limiting the false-sharing (usual cause of contention) and fairly easy to implement correctly (discounting the it's multithreaded code multiplier, that is).

**Comment by stephentoub** [comment]
> you should look into a cache line optimized ring-buffer

That's essentially what I have ;)

**Comment by jkotas** [comment]
> The more threads you have, the more arrays you can end up caching, potentially unbounded (without additional synchronization), and arrays that are valid and created can be completely unavailable to other threads.

Note that we have runtime tricks to play with now that ArrayPool is in corelib. For example, if there are arrays in thread-local caches that are not getting a good use for a while, it should be pretty straightforward to flush them when the GC kicks in. These kind of optimizations is what I have in mind with #7747.

**Comment by stephentoub** [comment]
> These kind of optimizations is what I have in mind with #7747.

Great, that'll be cool.  This is essentially why I kept this issue (#8203) separate from #7747.  I see this as two separate things:
- Improve the global pool
- Add local pools with whatever tricks we can muster
It's also why in #8209 I separated the implementations into two concrete derivations of ArrayPool, so that we can then take it to the next step and apply local pools to the shared one without having to be concerned about the individual ones.

**Comment by jkotas** [comment]
> unbounded (without additional synchronization), and arrays that are valid and created can be completely unavailable to other threads

If the pathological case that requires forceful load-balancing is rare, we may be able to avoid the synchronization cost for common case by using [RCU](https://en.wikipedia.org/wiki/Read-copy-update) algorithm. Either way, it may be a nice to add `Interlocked.FlushProcessWriteBuffers()` as public API. I am pretty sure that there are quite a few interesting RCU datastructures that it would encourage.
