### ISSUE TITLE
x86/Linux: compile error "Dacp structs cannot be modified due to backwards compatibility"

### ISSUE THREAD

**Issue by seanshpark** [dotnet/coreclr#8369]
`DacpXXXX` structure seems size difference in x86/Linux compilation. I think elements are assumed to be 8 byte aligned but does not solve with adding `__attribute__((aligned(8)))` for the structure
Error message is like this;
```
In file included from coreclr/src/utilcode/dacutil.cpp:15:
coreclr/src/inc/dacprivate.h:973:1: error: static_assert failed "Dacp structs cannot be modified due to backwards compatibility."
static_assert(sizeof(DacpThreadStoreData) == 0x38, "Dacp structs cannot be modified due to backwards compatibility.");
^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

If I force add a padding DWORD it seems to work, for example for `DacpThreadData`
```
struct DacpThreadData : ZeroInit<DacpThreadData>
{
    DWORD corThreadId;
    DWORD osThreadId;
    int state;
    ULONG preemptiveGCDisabled;
    CLRDATA_ADDRESS allocContextPtr;
    CLRDATA_ADDRESS allocContextLimit;
    CLRDATA_ADDRESS context;
    CLRDATA_ADDRESS domain;
    CLRDATA_ADDRESS pFrame;
    DWORD lockCount;
+    DWORD dummyalign1;
    CLRDATA_ADDRESS firstNestedException; // Pass this pointer to DacpNestedExceptionInfo
    CLRDATA_ADDRESS teb;
    CLRDATA_ADDRESS fiberData;
    CLRDATA_ADDRESS lastThrownObjectHandle;
    CLRDATA_ADDRESS nextThread;

    HRESULT Request(ISOSDacInterface *sos, CLRDATA_ADDRESS addr)
    {
        return sos->GetThreadData(addr, this);
    }
};
```
Does anyone know how to solve this kind of problem? I couldn't find how ARM32 works.

**Comment by seanshpark** [comment]
CC @parjong

**Comment by seanshpark** [comment]
@BruceForstall, could you help?

**Comment by BruceForstall** [comment]
@seanshpark What you've done looks correct to me.

@noahfalk What do you think?

**Comment by janvorli** [comment]
Clang is expected to align structure members to their natural alignment, which for basic integer elements is their size, unless the struct is marked as packed. I can see that even in their unit tests - see `https://llvm.org/svn/llvm-project/cfe/branches/eh-experiment/test/Sema/struct-packed-align.c`. So I am really curious on what's going on here.

**Comment by janvorli** [comment]
I have done some investigations and it seems that I was wrong in one aspect. What I've said about the alignment is true, but only for types with size <= sizeof(void*), in other words, for sizes <= natural integer size. For larger sizes, the members are aligned to the natural integer size, which for x86 is 4 bytes.
But there is an attribute that can be attached to the members we want to have aligned arbitrarily. __attribute__((aligned(8))) on all members of CLRDATA_ADDRESS type fixes the problem.
So my suggestion is to define a macro that would expand to __attribute__((aligned(8))) for __clang__ and to empty otherwise and place it before each member of CLRDATA_ADDRESS type.
Or alternatively, create a typedef for the CLRDATA_ADDRESS (e.g. CLRDATA_ALIGNED_8) that would be used in this file and that would have the `__attribute__((aligned(8)))` attribute on it.
E.g.
```C++
typedef __attribute__((aligned(8))) CLRDATA_ADDRESS CLRDATA_ADDRESS_ALIGNED_8;
```

**Comment by janvorli** [comment]
I've verified that it works using a simple testing app.

**Comment by janvorli** [comment]
Actually, I have found even easier way. Apply `__attribute__((ms_struct))` to these structures when `__clang__` is defined. That works too.

**Comment by janvorli** [comment]
Actually, there is define MSLAYOUT that can be used here. It is defined as empty for MSVC.

**Comment by seanshpark** [comment]
@janvorli , thank you for the guide. I've updated #8377
