### ISSUE TITLE
ildasm roundtrip failing for JIT\opt\perf\doublealign\Locals\Locals

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#8418]
This test started failing after recent corefx update

**Comment by jkotas** [comment]
https://github.com/dotnet/coreclr/pull/8419/commits/28e4d0d2422cd88839944686c550529904915b5b should be rolled back once this is fixed.

**Comment by BruceForstall** [comment]
ildasm generates .il that includes:

```
.assembly Locals
{
...
  .permissionset reqmin
             = {[System.Runtime.Extensions]System.Security.Permissions.SecurityPermissionAttribute = {property bool 'SkipVerification' = bool(true)}}
...
```
Then, ilasm calls, during `Assembler::EmitSecurityInfo()`:
```
if(FAILED(m_pEmitter->DefinePermissionSet(token,
                                           pPset->m_Action,
                                           pPset->m_Value->ptr(),
                                           pPset->m_Value->length(),
                                           NULL)))
            report->error("Failed to define security permission set for 0x%08X\n", token);
```
which fails (in src\md\compiler\emit.cpp, RegMeta::DefinePermissionSet()) with E_NOTIMPL because FEATURE_METADATA_EMIT_ALL is not defined.

**Comment by BruceForstall** [comment]
@jkotas @stephentoub I don't understand what happens during one of the "Update CoreClr, CoreFx to beta-24801-03, beta-24721-02, respectively (master)" events. Did corefx or Roslyn change something (this was back in November/December) that caused assembly permissionset attributes to be emitted to a test compilation (perhaps just one compiled with /unsafe)? It looks like ildasm/ilasm round tripping fails because the `DefinePermissionSet` API is not implemented in CoreCLR.

**Comment by jkotas** [comment]
The C# compiler emits this attribute if it is in the reference assembly. This attribute was not in the reference assembly back in 1.0 and so it was not emitted by C# compiler. It was added back as part of NS2.0 work and so C# compiler emits it now.

This attribute is still ignore by the .NET Core runtime.

There are potential two ways to fix this:
1. Change the failure to emit the attribute in ilasm to warning
or 
2. Remove the `FEATURE_METADATA_EMIT_ALL` ifdefs that this is hitting; or just define `FEATURE_METADATA_EMIT_ALL`.
