### ISSUE TITLE
Windows exception interop support

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/coreclr#8459]
Jit codegen for inline pinvoke is currently more restricted than necessary for CoreCLR, since it is working around issues that arise with exception interop on windows. 

We should remove the support and the restrictions on jit codegen.

See notes for #8263.

**Comment by AndyAyersMS** [comment]
@janvorli I'd be willing to give this a try, but would need some guidance.

**Comment by janvorli** [comment]
@AndyAyersMS sure. I believe that for AMD64, ARM and ARM64 we need to replace the personality routine on TheUMEntryPrestub and UMThunkStub in all the .asm files listed below with a new personality routine that behaves like the UnhandledExceptionHandlerUnix on Unix, it means it calls the DefaultCatchHandler and fails fast after that.
Here are the files where it needs to be replaced:
 * src\vm\arm\asmhelpers.asm
 * src\vm\amd64\UMThunkStub.asm
 * src\vm\arm64\asmhelpers.asm

As for x86, I need to look into it. The way the stubs and EH works is different over there and I am not that familiar with it.

**Comment by janvorli** [comment]
So here are the details for x86. Here, the exception personality routine of our interest is stored in FrameHandlerExRecord that's created by the thunk code, which in turn is generated by UMEntryThunk::CompileUMThunkWorker. You can see that it sets the exception handler to FastNExportExceptHandler. So for CoreCLR (FEATURE_CORECLR) , this handler body should be modified to call the DefaultCatchHandler and fail fast, like for the other case.
The same applies to UMThunkPrestubHandler.
Actually, now that I think about it, for the case of ARM, ARM64 and AMD64 that I've described before, we  should also just modify the bodies of UMEntryPrestubUnwindFrameChainHandler and UMThunkStubUnwindFrameChainHandler for coreclr instead of creating a new personality routine.

**Comment by gkhanna79** [comment]
@janvorli @AndyAyersMS Are we planning to make this change for 2.0?

**Comment by AndyAyersMS** [comment]
It would probably be a good idea. I doubt we want anyone taking a dependence on the current behavior.

**Comment by janvorli** [comment]
@AndyAyersMS do you still think you'd find time to make the change or should we find someone else to do it?

**Comment by AndyAyersMS** [comment]
Not clear yet -- if you have somebody ready to take this on, please go ahead. Otherwise I'll try to get to it soon.

**Comment by mjsabby** [comment]
Will this cause a difference in behavior for between an assembly running on .NET Desktop vs. .NET Core on Windows? If so, I don't think this is a good idea.

**Comment by AndyAyersMS** [comment]
@mjsabby It will cause differences, yes. 

The proposal here is to make .Net Core behavior consistent across OS platforms, which means in this area .Net Core and .Net Desktop will diverge.

Under this proposal, for all .Net Core platforms including Windows, exceptions that cross a managed-native or native-managed boundary will cause the runtime to terminate with an unhandled exception.

cc @jkotas @richlander

**Comment by jkotas** [comment]
> .Net Core behavior consistent across OS platforms

And also consistent with Mono runtime. There is a great write up on it here: http://www.mono-project.com/docs/advanced/pinvoke/#runtime-exception-propagation

**Comment by gkhanna79** [comment]
CC @rahku and @yizhang82

**Comment by mjsabby** [comment]
@AndyAyersMS Ok, I suppose that is a reasonable thing to expect. Can we setup a tag where there is difference in behavior between runtimes (coreclr on windows/xplat, vs desktop, etc.) -- I know the list might get big if we truly tag everything like many jit changes that may not be going into desktop, etc.

But having the truly esoteric ones will help people along the way. I'm also going to ask the same on CoreFX.

**Comment by jkotas** [comment]
> Can we setup a tag where there is difference in behavior between runtimes

Won't this tag be set on *everything* ? Changes and fixes that are going to .NET Core are not in other runtimes by design; and it is hard to predict when they will be. I guess you may be looking for a summary like this https://msdn.microsoft.com/en-us/library/dn600634(v=vs.110).aspx ... it is very hard to read such summaries.

**Comment by mjsabby** [comment]
I understand, but this is where we get to decide what we think will be impactful vs not. If you look at the issue @janvorli referenced, that is an asp.net dev running into this issue which will get addressed. Another example is networking in CoreFX. Today httpwebrequest is built on top of httpclient which has noticeable difference in behavior.

I think one such list could be places where we throw PlatformNotSupportedException now with NS 2.0

While I agree those summaries are hard to read, it's at least one or two places where a developer can find information when something is amiss.

I'm particularly concerned because as we make more things binary compatible with NS2.0 things will start blowing up at runtime.

**Comment by jkotas** [comment]
I agree that documentation is useful, but I believe it should be local to the affected API. E.g. The documentation for httpwebrequest should talk about the differences in behavior between different implementations.

**Comment by jkotas** [comment]
Back to the original issue:

We should be careful about how to roll this out. E.g. maybe introduce a quirk to make the transition easier.

**Comment by jkotas** [comment]
@gkhanna79 and I have been discussed this a few days ago. One of the stated top goals for .NET Core 2.0 is easy migration from desktop on Windows. Removing the exception handling interop would go against this goal. We should instead look into how to fix the implementation so that the codegen does not have to be pessimized for it. Adding some tests for it would be good too.
