### ISSUE TITLE
How does this repo relate to the full desktop .NET?

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/coreclr#87]
Will for example perf improvements also be included in future desktop FW versions?

**Comment by jkotas** [comment]
Whether/when changes made in this repo are going to be included in future desktop versions is on case by case basis. The desktop has to maintain very high compatibility guarantees. Changes with low compat risk are likely going to be included after some bake time. Changes with high compat risk are not going to be included by default - we will ask for such changes to be made under FEATURE_CORECLR ifdef, or under a target framework version specific quirk.

**Comment by gkhanna79** [comment]
The Desktop CLR and CoreCLR are built from the same codebase. In principle, any contributions made to this repo will be mirrored back to the Desktop CLR branch as well. However, since Desktop CLR has a high degree of compatibility onus on it, any such change will have a closer scrutiny. Also, when they figure out in a public release of the Desktop CLR will depend upon its release schedule.
