### ISSUE TITLE
[Deadlock] Stream uses same Semaphore for Async Read & Write

### ISSUE THREAD

**Issue by benaadams** [dotnet/coreclr#8752]
A pending Read can cause a Write to deadlock and vice versa: see https://github.com/dotnet/corefx/issues/14698#issuecomment-269730422

**Comment by jkotas** [comment]
There may be stream implementations that depend on single lock being used for both for correctness. Fixing this may get rid of the deadlock for some streams, but introduce races for other streams.

**Comment by stephentoub** [comment]
> Fixing this may get rid of the deadlock for some streams, but introduce races for other streams.

Right.  For example, this would cause problems with a variety of streams that rely on this to protect their internal buffering state (e.g. FileStream created with useAsync=false).  While it's arguable whether such streams should have had this behavior when the Begin/End methods were introduced in the first place, changing it now would lead to potentially significant problems.

> A pending Read can cause a Write to deadlock and vice versa

This should be handled by by stream implementations that actually support concurrent reading and writing, rather than relying on the base stream's behavior.
