### ISSUE TITLE
DirectoryInfo.CreationTimeUtc is broken under Unix

### ISSUE THREAD

**Issue by paradissimon** [dotnet/coreclr#8762]
It seems the concept of a file or directory creation time does not exists on Unix. On Linux/Ubuntu 16.04.1 LTS with .Net Core 1.1, the *CreationTimeUtc* property returns *DateTime.MinValue* for both files and directories. This creates a different behavior between Windows and Linux. Code work correctly on Windows but not Linux.

One must use *LastWriteTimeUtc* instead.

**Comment by stephentoub** [comment]
Thanks for the report, but creation time as a concept doesn't exist in Linux, though it does on both Windows and macOS ("birth time").  Since .NET exposes this creation time property, though, to implement it on Linux we really only have two options: return a default value or throw an exception.  And in this case we chose to return a default value.
