### ISSUE TITLE
Unable to specify interface type to GetCustomAttributes

### ISSUE THREAD

**Issue by mconnew** [dotnet/coreclr#8794]
On the full framework, WCF looks for any attributes declared on a type where the attribute type derives from IServiceBehavior. This works on the full framework, but on .Net Core an `ArgumentException` is thrown with the message "Type passed in must be derived from System.Attribute or System.Attribute itself." Here is a simple repro which runs to completion on the full framework but throws on .Net Core.
```csharp
using System.Reflection;
using System.ServiceModel;
using System.ServiceModel.Description;

    class Program
    {
        static void Main(string[] args)
        {
            var ti = typeof(MyService).GetTypeInfo();
            var attrs = ti.GetCustomAttributes(typeof(IServiceBehavior), false);
        }

        [ServiceContract]
        public interface IMyService
        {
            [OperationContract]
            string Hello(string hello);
        }

        public class MyService : IMyService
        {
            public string Hello(string hello) { return hello; }
        }
    }
```

**Comment by AtsushiKan** [comment]
It looks like the desktop has a mismatch in behavior between

    MemberInfo.GetCustomAttributes(attributeType, inherit)  (accepts interface on desktop)

  and

    CustomAttributeExtensions.GetCustomAttributes(this memberInfo, attributeType, inherit) (does NOT accept interface on desktop.)

That was probably an oversight since CustomAttributeExtensions was supposed to emulate the MemberInfo version, but fixing that is a (sort of) breaking change.

On the desktop, the C# expression "ti.GetCustomAttributes()" resolves to MemberInfo.GetCustomAttributes().

On .NetCore 1.0, MemberInfo.GetCustomAttributes() doesn't exist, so the expression "ti.GetCustomAttributes()" resolves to the more restrictive CustomAttributeExtensions version.

With .NS2.0, MemberInfo.GetCustomAttributes() is returning, so this won't be such a problem.

However, as part of investigating this, I realized that corert gets MemberInfo.GetCustomAttribute() wrong so there's an issue to fix there.

**Comment by AtsushiKan** [comment]
With .NS2.0, MemberInfo.GetCustomAttributes() is returning, so this won't be such a problem.
