### ISSUE TITLE
Missing System.Runtime when using .net standard 1.5 lib in 4.6.2 Console app

### ISSUE THREAD

**Issue by Gentlehag** [dotnet/coreclr#8845]
I created a library in .net standard 1.5

now i reference the library from a .net 4.6.2 project and trying to instantiate a class. but i immediatly get:

> System.IO.FileNotFoundException: 'Die Datei oder Assembly "System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" 

what am I missing ? Anything i should configure or in install in the .net 4.6.2 part of the application?

When I add the netstandard library nuget package it works, but is this an intended behavior?

doesn't the classes of this nuget package conflict with the preexisting GAC assemblies?

**Comment by Gentlehag** [comment]
btw in the meanwhile i also posted here: http://stackoverflow.com/questions/41535341/using-net-standard-1-5-lib-in-net-4-6-2-misses-system-runtime-4-1-0-0

**Comment by gkhanna79** [comment]
CC @weshaggard

**Comment by weshaggard** [comment]
cc @ericstj @terrajobst 

@Gentlehag Yes it is intended that you need to reference the NETStandard.Library package from your .NET 4.6.2 project so that it will pull in the latest version of the contract facades, like System.Runtime in your case. For your other question there is a System.Runtime in the GAC but it is version 4.0.0.0 and to support the later netstandard versions we have a 4.1.0.0 version of that library that does come from the NETStandard.Library package. That one will override the one in the GAC when it deploy it along with the assembly binding redirects with your application.

**Comment by weshaggard** [comment]
Also looks like @terrajobst answered your question on stackoverflow. I'm going to close this issue but please feel free to ask any follow-up questions.
