### ISSUE TITLE
Support building coreclr tests on Linux

### ISSUE THREAD

**Issue by tmds** [dotnet/coreclr#8891]
cfr https://github.com/dotnet/coreclr/issues/4437, a Windows machine is needed to build artifacts used by the Linux test.

How far are the tests from being buildable on Linux? What are the steps to take?

**Comment by RussKeldorph** [comment]
As a non-expert, my approach would be "figure out what dotnet/corefx does and port that." 

@gkhanna79 Do you happen to have a more detailed list of steps or otherwise more useful advice?

**Comment by tmds** [comment]
@RussKeldorph @gkhanna79 

This is probably one of challenges, From https://github.com/dotnet/coreclr/issues/4437#issuecomment-262424688 

> The current result does not include .sh and .cmd files; CodeTaskFactory is required to generate those files, but MSBuild currently does not support it

**Comment by tmds** [comment]
@gkhanna79 can you give some advice?

**Comment by gkhanna79** [comment]
The most appropriate way to go about this is to enable the existing build of tests (done for Windows) to non-Windows - authoring build-tests.sh, fixing Windows specific assumptions, etc. This is how I approached it last year but had to abandon the effort due to other pressing issues.

I know @russellhadley was also making an attempt at it and could share something more recent he  may have built.

CC @ramarag @wtgodbe

**Comment by tmds** [comment]
@gkhanna79 do you know something more about the 'CodeTaskFactory'? Is that still a blocker?

**Comment by gkhanna79** [comment]
It should not be if we are able to build the tests on Windows using MSBuild that runs on .NET Core. Have not revisited this, so cannot say for sure.

**Comment by gkhanna79** [comment]
At the time I looked into this, MSBuild was not working on .NET Core, so this was a blocker.

**Comment by mazong1123** [comment]
So the reason that we cannot get rid of the Windows build for Linux test is MSBuild was not working on .NET core. I may misunderstanding something but since we can build the source code of coreclr on Linux, we should be able to build the tests on Linux in the same way. 

I understand some projects depend on CodeTaskFactory which is not supported by MSBuild on .NET Core. But how about rewrite these projects by leveraging cross-platform features? This makes sense in my opinion as the tests for a cross-platform library should be build-able cross platform either.

I'm willing to try my best to fix this :)

**Comment by russellhadley** [comment]
@rartemev are you in flight with this work?  @mazong1123 I think there may be some effort ongoing on this already.  Let's make sure there isn't duplicated effort. :)

**Comment by rartemev** [comment]
@russellhadley @mazong1123 I have almost finished with this work. I will make pull-request as soon as possible (today or tomorrow).
