### ISSUE TITLE
Console.CancelKeyPress fails to hook Ctrl+C on subsequent registrations

### ISSUE THREAD

**Issue by anroOfCode** [dotnet/coreclr#892]
The Console.CancelKeyPress event handler code doesn't call ControlCHooker.Hook in the follow sequence of events:

```csharp
Console.CancelKeyPress += SomeHandler;
Console.CancelKeyPress -= SomeHandler;
Console.CancelKeyPress += SomeHandler; // doesn't call _hooker.Hook();
```

It looks like a fairly trivial issue in the event registration/unregistration implementation:

```csharp
        public static event ConsoleCancelEventHandler CancelKeyPress {
            [System.Security.SecuritySafeCritical]  // auto-generated
            add {
                new UIPermission(UIPermissionWindow.SafeTopLevelWindows).Demand();

                lock(InternalSyncObject) {
                    // Add this delegate to the pile.
                    _cancelCallbacks += value;

                    // If we haven't registered our control-C handler, do it.
                    // NOTE: _hooker will be instantiated but unhooked on the second registration.
                    if (_hooker == null) {
                        _hooker = new ControlCHooker();
                        _hooker.Hook();
                    }
                }
            }
            [System.Security.SecuritySafeCritical]  // auto-generated
            remove {
                new UIPermission(UIPermissionWindow.SafeTopLevelWindows).Demand();

                lock(InternalSyncObject) {
                    // If count was 0, call SetConsoleCtrlEvent to remove cb.
                    _cancelCallbacks -= value;
                    Contract.Assert(_cancelCallbacks == null || _cancelCallbacks.GetInvocationList().Length > 0, "Teach Console::CancelKeyPress to handle a non-null but empty list of callbacks");
                    if (_hooker != null && _cancelCallbacks == null)
                        _hooker.Unhook();
                }
            }
        }
```

**Comment by jasonwilliams200OK** [comment]
RE: Unable to re-hook the `_hooker`! :smile: 

I think the fix is to dispose the hooker on removing the final hander from delegate `_hooker.Dispose();` instead of [`_hooker.Unhook();`](https://github.com/dotnet/coreclr/blob/cbf46fb0b6a0b209ed1caf4a680910b383e68cba/src/mscorlib/src/System/Console.cs#L1682), the dtor of `_hooker` will then call `Unhook()` internally. 

Alternatively, the [`class ControlCHooker`](https://github.com/dotnet/coreclr/blob/cbf46fb0b6a0b209ed1caf4a680910b383e68cba/src/mscorlib/src/System/Console.cs#L1532) can expose a property `public bool Hooked { get { return _hooked; //already there }}` and then in [`CancelKeyPress { add {} }`](https://github.com/dotnet/coreclr/blob/cbf46fb0b6a0b209ed1caf4a680910b383e68cba/src/mscorlib/src/System/Console.cs#L1659-L1672), change `if (_hooker == null)` to `if (!_hooker.Hooked)` (:p). The rest of the code is already in place.

**Comment by ellismg** [comment]
We should have already addressed this issue as part of the process to move Console into it's own standalone assembly in CoreFX (see the difference in [Console.cs#L110](https://github.com/dotnet/corefx/blob/master/src/System.Console/src/System/Console.cs#L110).  I'll look into us back-porting the fix so it shows up for desktop .NET, but for .NET Core this bug is actually already fixed, since we use the System.Console implementation from CoreFX.

/cc @AlexGhiondea.  Do we have a good strategy for porting fixes we make in FxCore back to CoreCLR so they make their way to full .NET?

**Comment by jasonwilliams200OK** [comment]
@ellismg, I am confused; should there be overlapping implementations in CoreFX and CoreCLR in first place? If something is implemented in CoreCLR, is it mandatory to re-implement it in CoreFX?

**Comment by ab500** [comment]
I'd like a little bit more information here too- the divisions between mscorlib, CoreFX, and the rest of CoreCLR are a little murky and it'd be nice to make them a little clearer. 

For what it's worth I found the bug in Desktop.NET, and just wanted to make sure the fix eventually gets pushed through the pipe.

**Comment by joshfree** [comment]
@pallavit can you move this to /dotnet/corefx please

**Comment by pallavit** [comment]
@ellismg Is there any follow-up left here from the Desktop perspective? Based on the information in the bug looks like we wanted to update the Desktop implementation as well but I believe that is still pending. Can you please confirm?

**Comment by AlexGhiondea** [comment]
@ellismg I am working on figuring out the process for doing that.
For now, please file an internal bug to track this. For Desktop we probably want to figure out a way to not break people that might have taken a dependency on the current behavior.

**Comment by joshfree** [comment]
Moved this issue to https://github.com/dotnet/corefx/issues/8288
