### ISSUE TITLE
Assert failure(PID 2748 [0x00000abc], Thread: 2664 [0x0a68]): Assertion failed 'StateMatchedCounts[stateID] < _UI16_MAX' in 'Tests.ThousandMoreField:.ctor():this'

### ISSUE THREAD

**Issue by pgavlin** [dotnet/coreclr#8932]
This assertion is hit when crosgenning `bin\tests\Windows_NT.x64.Checked\JIT\Regression\CLR-x86-JIT\V2.0-Beta2\b399444\b399444b\b399444b` with `COMPlus_JitStress=2` (see e.g. https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_windows_nt_r2r_jitstress2/lastCompletedBuild/testReport/JIT/_Regression_CLR_x86_JIT_V2_0_Beta2_b399444_b399444b_b399444b_/_Regression_CLR_x86_JIT_V2_0_Beta2_b399444_b399444b_b399444b_cmd/).

@AndyAyersMS, can you take a look?

**Comment by AndyAyersMS** [comment]
JitStress=2 enables the random inliner in the method `Tests.ThousandMoreField:.ctor():this` which has on the order of 240,000 repetitions of the IL sequence `ldarg; ldc; stsfld`. Evaluation of this method as an inline includes running the inline state machine pattern matcher over the IL. The repetitive pattern is one of the recognized patterns and so for each match the state machine increments a corresponding word-sized match count. This count cannot safely exceed UI16_MAX, and the code asserts this is true.

The only way the jit would ever evaluate such a huge method as a discretionary inline is when running under stress. Huge methods can be force inlined but in force inline cases the jit does not bother creating a code size model for the method. 

Since the match counting code seems to exist solely to trigger this assert, it seems reasonable to delete the counting and the assert.
