### ISSUE TITLE
[Linux] Using DAC interfaces from outside CoreCLR build

### ISSUE THREAD

**Issue by ayuckhulk** [dotnet/coreclr#8960]
I'm trying to create LLDB plugin for CoreCLR which uses DAC interfaces (`IXCLRDataProcess` and friends).

There is code in Strike to load DAC interface (function `LoadClrDebugDll` in `util.cpp`):

    IXCLRDataProcess* s_clrDataProcess;

    PAL_InitializeDLL();
    hdac = LoadLibrary("mscordaccore");
    pfn = GetProcAddress(hdac, "CLRDataCreateInstance");
    pfn(__uuidof(IXCLRDataProcess), &clrDataProcess);
    ...

However, there is no standalone PAL library when building outside of CoreCLR
and I have to use PAL functions by manually linking them from `libmscordaccore.so`:

    h = dlopen("mscordaccore");
    initdllfn = dlsym(h, "PAL_InitializeDLL");
    loadfn = dlsym(h, "LoadLibrary");
    getprocfn = dlsym(h, "GetProcAddress");

    initdllfn();
    hdac = loadfn("mscordaccore");
    pfn = getprocfn(hdac, "CLRDataCreateInstance");
    pfn(__uuidof(IXCLRDataProcess), &clrDataProcess);
    ...

This code works, but it looks very fragile.

So, I have several questions about using DAC:

1. Is it OK to use `CLRDataCreateInstance` function? Comments say that it's a legacy entrypoint.

2. What is the correct way load DAC without PAL available?

@jkotas @janvorli 

CC @Dmitri-Botcharnikov

**Comment by janvorli** [comment]
@ayuckhulk I wonder why are you creating another plugin for LLDB when we already have one for managed code debugging - the libsosplugin.so? What is the goal of your work?

**Comment by ayuckhulk** [comment]
@janvorli  Actually I am investigating about adding proper C#/CoreCLR language runtime plugin to LLDB (similar to ObjC).

Currently there are 2 ways of working with managed code through LLDB:
1. `GDB JIT` Enables LLDB to undestand native/source mappings and some method or variable types
2. `SOS Plugin` Adds commands to view internal CoreCLR structures/info and managed stack traces.

But none of them allows to implement proper stepping through managed code (as it is done by ClrDbg). One issue is that LLDB cannot follow through stubs without debug info (and it asks ObjC runtime about target call addresses in case of ObjC executable). Another issue is that exact types for generic methods can be resolved only when the method is executed - so we cannot use GDBJIT in that case.

**Comment by lemmaa** [comment]
cc: @richlander

**Comment by janvorli** [comment]
@ayuckhulk I was thinking about it a bit. It may be that a good way would be to extend libsos.so / libsosplugin.so by the functionality needed. But to be sure, I would need some more details on how the new functionality will work. Will it register some callback with LLDB that LLDB will call when it needs to unwind a stack frame or something like that?

**Comment by ayuckhulk** [comment]
@janvorli Thank you for your response! As I understand, you are suggesting not to use DAC directly and instead try to use it from inside `libsosplugin.so`. I am not sure that existing API for loadable LLDB plugins would be enough to implement all the functionality related to correct stepping/variable/method viewing. It needs further investigation.

**Comment by janvorli** [comment]
@ayuckhulk yes, that was my idea.

**Comment by noahfalk** [comment]
@gkhanna79 - Given that (I think) ayuckhulk is proposing the work it would be up to him to set his own schedule no? : ) 

@janvorli/@ayuckhulk - This is a cool project! Depending on how far you plan to take it just want to give a heads up that it could be a significant undertaking. There is quite a bit of code in mscordbi and debug/ee that is dedicated to breakpoint and stepping logic, and more still in clrdbg. If this work is going to necessitate a significant expansion of SOS/DAC I would encourage that to occur on ICorDebug and the underlying DAC interfaces which support that stack, not IXClrDataProcess. Although this isn't what SOS uses in many places for historical reasons, its been an ongoing problem over time that we divided our efforts with multiple implementations in the DAC that do nearly the same thing. Often ICorDebug wasn't used by SOS because the interface wasn't low enough level, but I think it would be better to grow ICorDebug lower if it helps consolidate all our development effort around a single stack.
