### ISSUE TITLE
Tutorial to compile NetCore on Raspberry 3?

### ISSUE THREAD

**Issue by scrambler86** [dotnet/coreclr#8965]
Hello!

I would like to compile NetCore for Raspberry 3, I have read most issues, but there is no tutorial step by step.

Please can anyone post a tutorial to compile it?

Example:
1.- $ mkdir / git
2.- $> git clone https://github.com/dotnet/coreclr
3.- $> git clone https://github.com/dotnet/corefx
etc..

**Comment by janvorli** [comment]
You can only build the native parts of coreclr and corefx directly on RPI3 now. The managed parts of coreclr (mscorlib.dll and System.Private.CoreLib.dll) and managed parts corefx need to be built on x64 Linux at the moment due to the fact that dotnet cli tools are not available for ARM32 Linux yet.
See the #4332 for details on the native build and prerequisities.

**Comment by qmfrederik** [comment]
@scrambler86 If you're running Ubuntu on your RPi, there are pre-built binaries available here: core-setup#725

**Comment by qmfrederik** [comment]
#6321 also contains some additional info related to cross-compiling

**Comment by scrambler86** [comment]
Thank you
