### ISSUE TITLE
[Question] How many GCHeap and gc_heap instances per .net process?

### ISSUE THREAD

**Issue by 303248153** [dotnet/coreclr#8995]
Hello, I'm trying to understand gc in coreclr,
and my question is simple: how many GCHeap and gc_heap instances per .net process?

As I read there 3 global veriables
`IGCHeap g_pGCHeap` defined in gcheaputilities.h
`IGCHeapInternal g_theGCHeap` defined in gccommon.cpp
`gc_heap[] g_heaps` defined in gcpriv.h

`g_pGCHeap` and `g_theGCHeap` point to same instance created by `SVR::CreateGCHeap` or `WKS::CreateGCHeap`.
`g_heaps` have multi instance with a number of logical cores if server gc feature is available
each `gc_heap` have its own GCHeap instance, and they reference each other.

so if gc feature is available, there **1 + logical cores** GCHeap instances and **logical cores** gc_heap instances per .net process,
and if gc feature is unavailable, there **1** GCHeap instance and **0** gc_heap instance (because all gc_heap member mark static).
Is this right? I think my conclusion is very likely to be wrong.
These code are confusing me, I also try to find documents about GCHeap and gc_heap, but only this found:
https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/garbage-collector-guidelines.md

Anybody can answer for me or give me some documents? Thanks.

**Comment by jkotas** [comment]
cc @swgillespie

**Comment by swgillespie** [comment]
> so if gc feature is available, there 1 + logical cores GCHeap instances and logical cores gc_heap instances per .net process,
and if gc feature is unavailable, there 1 GCHeap instance and 0 gc_heap instance (because all gc_heap member mark static).

This is correct. The "original" GCHeap instance (the one created by `SVR::CreateGCHeap` or `WKS::CreateGCHeap`) is the one that serves as the interface between the runtime and the GC - both the runtime and the GC have a reference to this instance (`g_pGCHeap` and `g_theGCHeap`, as you noticed) and refer to it whenever they need to invoke the GC. (The GC needs `g_theGCHeap` because it occasionally needs to invoke methods on this "original" GCHeap instance). At any time, there is 1 + (gc_heap instances) GCHeap instances and one gc_heap instance per core if using Server GC, or no gc_heap instances if using Workstation GC.

The most detailed document on the topic of GC internals is probably [this one](https://github.com/dotnet/coreclr/blob/master/Documentation/botr/garbage-collection.md), though it doesn't cover this particular topic.

**Comment by 303248153** [comment]
Thank you very much for your answer!
I hope to have more documents about internal released.

**Comment by swgillespie** [comment]
Feel free to email me if you have any other questions! Perhaps it would be good to start aggregating some more documentation about GC internals.

**Comment by mattwarren** [comment]
<shameless plug> I have a [few articles on my blog that look at the .NET GC internals](http://mattwarren.org/tags/#Garbage-Collectors).

I must admit that for most of the posts I started by looking at the [GC BOTR page](https://github.com/dotnet/coreclr/blob/master/Documentation/botr/garbage-collection.md) linked above and then when I had more questions I grepped the source (gc.cpp)

**Comment by swgillespie** [comment]
@303248153 So I re-read my response and realized there's a bit I missed - the choice of whether or not the GC uses Workstation GC or Server GC is made at startup time:

> so if gc feature is available
At least on CoreCLR, the GC is always capable of using either Workstation GC or Server GC, and it's up to whomever is hosting the CLR which to do. (Practically, the dotnet CLI uses a json file to indicate which GC variant to use).

**Comment by 303248153** [comment]
@swgillespie @mattwarren
Thank you both for your enthusiastic response.
Yes `FEATURE_SVR_GC` is a static flag enabled by default, and the choice is made at startup time in `ceemain.cpp: InitializeStartupFlags`.
I'm writing blog about coreclr internals (in chinese) so if I have another question I'll ask again :)
