### ISSUE TITLE
Exponential slowdown in task execution when using WhenAny

### ISSUE THREAD

**Issue by yosefd** [dotnet/coreclr#9011]
@kouvel @alexperovich @stephentoub

The bug we found causes exponential slowdown, so it is pretty severe. I wouldn’t classify it as a performance problem. This practically kills process for all practical purposes, which what happened to our product.  As far as I can see in sources, the bug is in all versions of .net.

This is the repro (run release version, not attached to debugger):

            // Simulate slow operation.
            var completionForOperationThatWillTakeLotsOfTime = new TaskCompletionSource<object>();

            Func<Task> main = async () =>
            {
                for (int i = 0; i < 100; i++)
                {
                    var startBatch = DateTime.UtcNow;
                    for (int j = 0; j < 10000; j++)
                    {
                        // Execute fast operation in a loop, but wait in parallel if slow operation is eventually completed (which btw will never happen)
                        var taskFastOperation = Task.Run(() => { });
                        var taskAny = await Task.WhenAny(taskFastOperation, completionForOperationThatWillTakeLotsOfTime.Task);
                        if (taskAny != taskFastOperation)
                        {
                            // Slow operation should never complete as the task completion source for it is never completed.
                            Console.WriteLine("Unexpected");
                            Console.Read();
                        }
                        // Fast operation completed. Can take the result now.
                        await taskFastOperation;
                    }
                    Console.WriteLine("Batch execution time: {0} ms", (DateTime.UtcNow - startBatch).TotalMilliseconds);
                }
            };

            var start = DateTime.UtcNow;

            main().Wait();

            Console.WriteLine("Execution time: {0} ms", (DateTime.UtcNow - start).TotalMilliseconds);
            Console.Read();

Each batch runs 10000 iterations. Each iteration awaits one of  2 tasks, one of which completes fast, since it do almost nothing (Task.Run(()=>{})). Upon completion of the operation, new iteration starts.

You would expect each batch to run the same time. In reality first few batches are very fast, under 50ms, the following batches become very slow and can run long minutes, eventually. This is output of the code above after a few minutes of execution:

Batch execution time: 30.0168 ms
Batch execution time: 21.8036 ms
Batch execution time: 70.5011 ms
Batch execution time: 359.5303 ms
Batch execution time: 520.5175 ms
Batch execution time: 610.5054 ms
Batch execution time: 1188.5082 ms
Batch execution time: 1477.0104 ms
Batch execution time: 2279.5154 ms
Batch execution time: 2013.0131 ms
Batch execution time: 2319.6705 ms
Batch execution time: 3414.528 ms
Batch execution time: 2962.9172 ms
Batch execution time: 4005.1755 ms
Batch execution time: 4398.0309 ms
Batch execution time: 4364.5613 ms
Batch execution time: 5283.0364 ms
Batch execution time: 5468.2549 ms
Batch execution time: 6222.791 ms
Batch execution time: 8137.3497 ms
Batch execution time: 8732.3413 ms
Batch execution time: 8614.286 ms
Batch execution time: 9403.7989 ms
Batch execution time: 10822.8591 ms

Debugging of this shows the problem in Task implementation. In example above, CPU is consumed in RemoveContinuation function. The following lookup:

int index = continuationsLocalListRef.IndexOf(continuationObject);

becomes very slow, since m_continuationObject becomes very big (it is List<object>).  

Looking on the functions FinishContinuations and AddTaskContinuationComplex reveals why this vector becomes so big. Upon completion the object in the vector is set to null and not removed. The vector is compacted if it reaches the capacity. However, in a race condition one object might be added before the compaction, causing the underlying list to grow twice in size. It is just a matter of time until another race will cause another capacity increase to the double size.

Clearly, List<object> is not the right data structure to be used. The operation on this list are remove, add and traverse all. Just using LinkedList instead would already fix the problem (or at least the severe part of it).

Also as it was diagnosed by @kouvel:

FinishContinuations does not hold the lock while setting items to null, and AddTaskContinuationComplex could be concurrently resizing the internal array, causing Finish to see the old array and set its element to null after Add copies the non-null element into to the new array during resize. There are also memory ordering issues here, Add may have completed resizing before Finish sets the element to null but Finish may still see the old array since it is likely to be cached.

The suggestion is to use LinkedList. If there is a concern with performance of nodes allocation, I think, this should be handled in LinkedList. It can use zone allocation for multiple nodes in array and to link all unused nodes, so that can be reused again.

**Comment by stephentoub** [comment]
> Also as it was diagnosed by @kouvel

@kouvel, are you saying you believe there are race conditions in the existing implementation that can manifest problems (unrelated to this issue) today?  Can you elaborate?

> FinishContinuations does not hold the lock while setting items to null, and AddTaskContinuationComplex could be concurrently resizing the internal array

How?  FinishContinuations takes the lock in order to synchronize with AddTaskContinuationComplex:
https://source.dot.net/#System.Private.CoreLib/src/System/Threading/Tasks/Task.cs,3607
After that lock has exited, since prior to the lock it has already set the field to the sentinel object, it knows that it has sole ownership of the list (since the add process checks the field again while holding the lock).

> There are also memory ordering issues here, Add may have completed resizing before Finish sets the element to null but Finish may still see the old array since it is likely to be cached

The list in Add is only manipulated while holding a lock, and Finish takes that lock before processing the list.  The act of releasing the lock should act as a barrier against this, no?

> int index = continuationsLocalListRef.IndexOf(continuationObject);

It'd be worth experimenting I think with changing this to be LastIndexOf instead of IndexOf.  I expect in situations where there are multiple continuations and where continuations are being removed (which IIRC only happens today due to continuation cancellation, WhenAny, and synchronous Waits that time out) that, due to coding patterns, one is more likely to find the continuation to be removed closer to the end of the list rather than closer to its beginning.  There are a few cases where it will be closer to the beginning, but I don't expect those to be the majority case.

> The suggestion is to use LinkedList. If there is a concern with performance of nodes allocation

This would add non-trivial overhead to many use cases to account for a relatively rare use-case.  And I don't believe it would really address the problem.  From what I can see, the fact that IndexOf is taking a long time is a side-effect not of nulls not being compacted, but from completed continuations not being nulled out.  I suspect it's actually a bug in the WhenAny implementation.  I'll take a look there.

**Comment by kouvel** [comment]
Regarding the races in Finish/Add, you're right of course, I missed it

**Comment by jnm2** [comment]
Can this be tagged to port to netfx?

**Comment by kouvel** [comment]
Filed an internal issue to track porting the fix
