### ISSUE TITLE
Many expensive uses of gtGetOp2

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#9237]
Conversation in #8672 pointed out that gtGetOp2 is called many times where a nullptr result is not expected, leading to an expensive unnecessary function. Change this function to directly access gtOp.gtOp2 and create a new gtGetOptionalOp2 to be explicit about the caller expecting a possible nullptr.

**Comment by mikedn** [comment]
I've looked a bit into this couple of days ago and it seems that there are many uses that rely on the current behavior of `gtGetOp2`. Some uses are normal (e.g. in `fgWalkTree*` functions) but there are also cases where `gtGetOp2` is needlessly called on random nodes (e.g `fgMorphForRegisterFP` calls `gtGetOp2` before checking if the oper is arithmetic/compare).

It seems that there's quite a bit of work to cleanup this. Maybe it's simpler to just rename `gtGetOp2` to `gtGetOptionalOp2` then add back `gtGetOp2` and use it here and there where it is obvious that it correct (e.g. many such uses are in lowering and codegen since they tend to have a lot of oper specific code).

**Comment by BruceForstall** [comment]
I was looking through this earlier today (hence the new issue). I think it would be not too difficult to split existing uses between `gtGetOp2` and `gtGetOptionalOp2`. At least conservatively, there are many places that call `gtGetOp2`, typically in newer code, that obviously can't handle nullptr return.

**Comment by mikedn** [comment]
Wasn't this fixed by #9392?

**Comment by BruceForstall** [comment]
Yep.
