### ISSUE TITLE
Missing support for MemberInfo.ReflectedType?

### ISSUE THREAD

**Issue by voloda** [dotnet/coreclr#926]
Hi - is there a way how to access information originally published via MemberInfo.ReflectedType without using Portability analyzer suggestion to use an instance of class?

If not - would it be possible to add it?

Thanks.

**Comment by weshaggard** [comment]
cc @nguerrera

**Comment by voloda** [comment]
I looked into code and apparently ReflectedType property is available in mscorlib.dll but it is not available for usage via System.Reflection nuget package. But I may be missing something here.

I am willing to send a pull request but I haven't find a way how to expose it there yet thus I may perhaps need some initial guidance.

**Comment by nguerrera** [comment]
Please see http://blogs.msdn.com/b/kingces/archive/2005/08/01/446247.aspx which describes some issues with the API. That is why we've opted not to expose it moving forward.

**Comment by voloda** [comment]
@nguerrera Thanks for explanation. Just out of curiosity. Would it be possible to share some details how for example System.Reflection nuget package and its content are created?

**Comment by nguerrera** [comment]
Closing this because the API is intentionally excluded..

I can answer the follow-up question more easily now that more of the infrastructure is on GitHub. The ref/ folders in corefx have the source for the reference assemblies. For System.Reflection, see here:  https://github.com/dotnet/corefx/blob/master/src/System.Reflection/ref/System.Reflection.cs

**Comment by mellinoe** [comment]
For the runtime facade assembly, i.e. the one with all of the type forwards into mscorlib which you deploy at runtime, we have an internal build process that automatically generates them. It is very similar to the process we use to build the partial facade assemblies in corefx (see System.Runtime.csproj for example). We run a tool called GenFacades which fills in a partial assembly with type forwards in order to satisfy the entire contract of a "reference assembly" (the one built from that file Nick linked to above).

The only difference between the internal build process that makes the "full facades" and the process that makes the "partial facades" in corefx is that partial facades have some types already defined in the partial assembly, and full facades do not (so we start with a blank assembly and fill it with type forwards).

**Comment by voloda** [comment]
@nguerrera @mellinoe Thanks guys. So the file above is the source code for the runtime facade, correct?

**Comment by plioi** [comment]
@nguerrera That blog post is no longer accessible. Do you know of anywhere else that explains why it was removed? I've got a MethodInfo. It may or may not have come from a child class of the DeclaredType, and I want to know what I'm actually looking at.

**Comment by Mike-EEE** [comment]
+1 to @plioi ... the blog/website is no longer available.  Can someone assist with a pointer to its new location?  I am not sure why it's bad to have a reference to the type that was queried to retrieve the reflection data. Would be nice/super convenient to have access to this.

**Comment by Cologler** [comment]
@Mike-EEE  archive.org has the content snapshots:

https://web.archive.org/web/20160429093051/http://blogs.msdn.com/b/kingces/archive/2005/08/01/446247.aspx

**Comment by Mike-EEE** [comment]
> archive.org has the content snapshots

I have been out-internetted yet again. 😆 Thanks @Cologler. 👍
