### ISSUE TITLE
Using parts of Reference Source in CoreCLR

### ISSUE THREAD

**Issue by hadi77ir** [dotnet/coreclr#9301]
As both are Microsoft's properties, is it possible (I mean in legal terms) to use parts of code from Reference Source in CoreCLR?

**Comment by benaadams** [comment]
There is also the MIT licenced version of reference source on GitHub which I imagine its ok to use https://github.com/Microsoft/referencesource

**Comment by hadi77ir** [comment]
@benaadams But that has many parts removed and has less code than [referencesource.microsoft.com](https://referencesource.microsoft.com/). By "Reference Source", I mean this web site and the package available in the download section.
Can we port System.Windows.Forms to .NET Core (CoreCLR)? Is it legal?

**Comment by danmosemsft** [comment]
@richlander @karelz I am actually intersted to know this myself. I think it may need a scan of some sort.

**Comment by richlander** [comment]
You can use the code at https://github.com/Microsoft/referencesource to augment .NET Core. You can see that the licenses are the same, so they are by definition compatible. The license at https://referencesource.microsoft.com/ is different and not compatible with MIT, so cannot be used to augment .NET Core.

When we created the MIT-licensed referencesource repository, our goal was to make code available that had present or (expected) future analogs in .NET Core. This would make it easier for anyone working on .NET Core to consider existing .NET Framework behavior, grab code or otherwise make themselves more efficient. We have no plans to add one of the Windows UI stacks to .NET Core, so have no added the associated code to the referencesource repository as a result.

**Comment by karelz** [comment]
That makes sense. I think it answers the question. Closing.
