### ISSUE TITLE
QUWI forceGlobal => false

### ISSUE THREAD

**Issue by benaadams** [dotnet/coreclr#9393]
I raised an api request in corefx to expose the `forceGlobal` flag for QUWI https://github.com/dotnet/corefx/issues/12442; rather than always having it set to true. A related issue was exposing `IsThreadPoolThread` https://github.com/dotnet/coreclr/issues/5407 for a similar reason.

However, now I'm not so sure. I'm swaying towards setting `forceGlobal` to `false` for `QUWI` instead.  (As Tasks currently do)

It significantly improves any secondary QUWI queuing that happens on the threadpool from a threadpool thread on a multicore machine by reducing contention on the global queue; as even the stealing has less contention as it is distributed.

The effects need more investigation; however is there anything fundamentally wrong with the change?

Or it the current behaviour is prefereable on lower core counts; where there is less contention anyway, perhaps have the flag default set by core count? `<= 4` true; `> 4` false

/cc @stephentoub

**Comment by omariom** [comment]
Can it increase the chance of deadlocking in the existing code?

**Comment by benaadams** [comment]
> Can it increase the chance of deadlocking in the existing code?

Via threadpool starvation with `.Wait`, `lock` and `.Result`? Or do you mean via ways? I don't think it should effect anything in this respect, but I may be wrong.

**Comment by benaadams** [comment]
@omariom If Task.Run is used rather than QUWI its what it does (when not long running); though that path has extra overheads

**Comment by stephentoub** [comment]
> As Tasks currently do

Tasks make it an option.  The default is forceGlobal:false, but you can have forceGlobal be true via Task{Creation/Continuation}Options.PreferFairness.

> It significantly improves any secondary QUWI queuing that happens on the threadpool from a threadpool thread on a multicore machine

This is not always true.  Consider a scenario where one thread pool thread is a producer and is constantly producing work; another thread pool thread is a consumer and is constantly consuming work.  With today's forceGlobal:true, the producer will produce to the global queue, and the consumer generally won't have to steal, as it'll find its work in the global queue.  By changing forceGlobal:false, in this scenario you guarantee that every work item the consumer wants will need to be stolen, which is *significantly* more expensive than getting work from the global queue (and the consumer will have had to check the global queue anyway before stealing).  This is also potentially more expensive for the producer, as while pushing to a local queue is very cheap when there are a few items already in the local queue, when there aren't, all access to the local queue from both the producer and a stealer requires a lock.

> however is there anything fundamentally wrong with the change?

It could break a lot of assumptions that could significantly impact performance.

Work-stealing queues originated out of the idea of fork/join scenarios, and more generally out of scenarios where an individual "request" can be split up into multiple pieces as part of its processing.  So a work item comes into the global queue, is picked off by a worker thread, and then during the processing of that one request, it may fork off additional pieces of work; if another thread is available to help it, that other thread can steal it, so by breaking it into pieces this thread allows for other threads that are starved to assist it, but if there aren't any, it's able to then pick off the work it created and process them itself.  Since workers consider the global queue before stealing, new requests are prioritized over pieces of old ones.

This is why Tasks default to going to the global queue.  Their nature is very much about fork/join, if for no other reason than you can {a}wait for them.  QueueUserWorkItem, not so much.  Now, it's very possible that QueueUserWorkItem is being used as the fork part of the equation, and the body being forked does something else that will signal a synchronization mechanism that supports the join aspect, it's just not built in to the API.

By changing QUWI to target the local queues, it'll be changing a few things:
- The cost of taking one of those work items.  If code was previously using a pattern where production/consumption wasn't homogenous across workers, then such a change could make such scenarios much more expensive, as the slow act of stealing could become more common and even more expensive (the more stealing you have, the more contention you have for the per-queue locks).
- Prioritization.  Right now any QUWI done by a worker thread is prioritized in a FIFO manner with any outside requests coming into the global queue.  With this change, any QUWI done by a worker thread would implicitly be lower priority for all-but-that-worker than all other outside requests coming into the global queue.

> I'm swaying towards setting forceGlobal to false for QUWI instead

This should not be done lightly.  Pretty much any microbenchmark one writes is going to favor this decision one way or another and be inherently biased.  Before even considering this, we would need to examine a variety of real-world scenarios, examine the impact of this change on them, and prioritize those workloads, as I expect some would improve and others would regress.

**Comment by benaadams** [comment]
Api for explicit method is approved, so closing
