### ISSUE TITLE
Cleanup globalization duplication

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#9397]
We have two copies of globalization i: 
- The original one from full framework that is used on Windows
- The refactored one shared with CoreRT that is used on Unix

This duplication should be fixed.

**Comment by danmosemsft** [comment]
@tarekgh can describe how much of this will happen as part of the UWP work.

**Comment by tarekgh** [comment]
@danmosemsft 

> can describe how much of this will happen as part of the UWP work.

Nothing is planned to do this work but after the UWP work get done we'll be closer. we'll need to investigate how much difference (and breaking) when we can fully use the code under corefx folder and retire the code under mscorelib\src\System\Globalization. 

CC @ellismg if he has any thoughts as he is the one originally did this fork.

**Comment by ellismg** [comment]
> @ellismg if he has any thoughts as he is the one originally did this fork.

The fork was mainly done because at the time the code was shared with Desktop and we were very hesitant about making any changes.  We also started from the implementation of System.Globalization that we had for UWP, since we preferred the factoring at that it was mostly managed code.

As part of this plan, you could consider trying to pull more of the code in the runtime that deals with globalization up into C# (and implement the PAL on top of PInvokes to Win32).  I'm not sure how much additional complexity that brings in.  Just implementing the PAL we have on top of the existing FCALLs into the runtime would probably also be a way to remove a bunch of duplication.

**Comment by tarekgh** [comment]
> As part of this plan, you could consider trying to pull more of the code in the runtime that deals with globalization up into C# (and implement the PAL on top of PInvokes to Win32). I'm not sure how much additional complexity that brings in. Just implementing the PAL we have on top of the existing FCALLs into the runtime would probably also be a way to remove a bunch of duplication.

I think we already done most of this work and will do the rest when we do the UWP work. this is why I said we get closer after UWP work. I mean the code under corefx will be the copy we can just use.

**Comment by tarekgh** [comment]
this is already done
