### ISSUE TITLE
SIMD tests failing under GCStress=0xC on x86

### ISSUE THREAD

**Issue by pgavlin** [dotnet/coreclr#9452]
See e.g. https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_checked_windows_nt_gcstress0xc/11

@BruceForstall, can you take a look?

**Comment by BruceForstall** [comment]
The issue seems to be that the x86 unwinder doesn't expect to see `vzeroupper` instructions in the epilog. (In fact, it has a VERY specific epilog pattern that it expects to see, which is reflected in the GC info.) So we should see about either not emitting this instruction, or moving it out of the epilog.

There is another issue, where it appears the epilog size is 2 bytes too large as currently reported. I wonder if it is because of this problem:
```
IN0119: 0005ED vzeroupper  (ECS:5, ACS:3)
Instruction predicted size = 5, actual = 3
```
Seems like it should be simple to correctly predict this instruction size.
