### ISSUE TITLE
[Unix] Unsupported varargs tests segfault

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#9530]
I ran all the unsupported on Linux AMD64 on [Arm64/Unix]  several of the unsupported varargs test caused segfaults.  I ran the same tests on Ubuntu16.04 AMD64 and the same tests also segfaulted.  Based on the naming convention of the files it looked like segfaults were triggered by higher argument count tests

Seems like the code should produce a error message and gracefully in all builds exit.

**Comment by RussKeldorph** [comment]
I believe the runtime should be rejecting these in at least some cases.  @sdmaclea, can you mention one or more of the tests you're referring to so we can makes sure we know what you're talking about?

**Comment by sdmaclea** [comment]
I am referring to these tests
```
JIT/jit64/mcc/interop/mcc_i*/mcc_i*.exe
```

My assumption is the least significant digit corresponds to the number of arguments.

All cases which end in 7 segfault.

```
~/overlay/corerun ~/test/JIT/jit64/mcc/interop/mcc_i17/mcc_i17.exe
Segmentation fault (core dumped)
```

The other cases produce an unhandled exception
```
~/overlay/corerun ~/test/JIT/jit64/mcc/interop/mcc_i10/mcc_i10.exe

Unhandled Exception: System.InvalidProgramException: Vararg calling convention not supported.
Aborted (core dumped)
```

I'm not sure where the threshold is, but I think 6 also fails....

**Comment by mazong1123** [comment]
Does this issue still exist? I just ran the test specified but only got following message:

```
SKIPPED  - JIT/jit64/mcc/interop/mcc_i07/mcc_i07.sh
               Not supported on this platform.
```

**Comment by sdmaclea** [comment]
The test is skipped because it is in the tests/testsUnsupportedOutsideWindows.txt file.  In order to run you will probably need to run manually, remove from the above list, or use --runFailingTestsOnly flag on runtest.sh.  Be careful though at least one of the GC unsupported tests will consume all memory and in my case have often forced a complete reboot.  I would recommend limiting the tests to a specific directory tree.  The tests should be throwing an assert varargs not supported.

**Comment by mazong1123** [comment]
In [method.cpp:5049](https://github.com/dotnet/coreclr/blob/master/src/vm/method.cpp#L5049) , there is a weird code:

```cpp
    // Handle ordinals.
    if (GetEntrypointName()[0] == '#')
    {
        long ordinal = atol(GetEntrypointName()+1);
        return reinterpret_cast<LPVOID>(GetProcAddress(hMod, (LPCSTR)(size_t)((UINT16)ordinal)));
    }
```
The `ordinal` is a number (Actually, it is `1` in mcc_i07.exe test). `(LPCSTR)(size_t)((UINT16)ordinal)` results a pointer to an invalid address `0x1` , which apparently causes a segmentation fault when accessing the value of `ordinal` later. 

I don't know how Windows handle this but seems like a memory error should be thrown as well.

**Comment by janvorli** [comment]
@mazong1123 this is correct based on the GetProcAddress spec on MSDN:
> lpProcName [in]
The function or variable name, or the function's ordinal value. **If this parameter is an ordinal value, it must be in the low-order word; the high-order word must be zero.**

**Comment by janvorli** [comment]
Looking at GetProcAddress implementation for Unix, it does not support lookup by ordinals, since, well, there are no ordinals in the Unix shared library world. So this test is incompatible with Unix.

**Comment by janvorli** [comment]
See here:
https://github.com/dotnet/coreclr/blob/master/src/pal/src/loader/module.cpp#L299-L307

**Comment by sdmaclea** [comment]
@janvorli since ordinals are not supported, and the cited assert is imprecise, it seems we should do something to stop going down this wrong code path.  I would recommend and an assert and/or #ifdef be added near the GetProcAddress() call site https://github.com/dotnet/coreclr/blob/master/src/vm/method.cpp#L5049

**Comment by janvorli** [comment]
@sdmaclea I would not assert, but just ifdef out the whole if block with check for the ordinal for FEATURE_PAL or keep it in and return NULL for FEATURE_PAL from inside of the `if`. 
@jkotas do you have any opinion on it?

**Comment by jkotas** [comment]
I would ifdef it out for `FEATURE_PAL`.

**Comment by mazong1123** [comment]
Do we still need https://github.com/dotnet/coreclr/blob/master/src/pal/src/loader/module.cpp#L299-L307 if we idef the ordinal check for `FEATURE_PAL` ? Those line of code could never be reached in Unix because https://github.com/dotnet/coreclr/blob/master/src/pal/src/loader/module.cpp#L285 will raise the segmentation fault.

**Comment by janvorli** [comment]
@mazong1123 PAL is used by other libraries than libcoreclr, e.g. by libmscorddac or libjit. So it is better to keep the assert in to catch possible future issues. But as you've pointed out, it should be moved before the line 285.

**Comment by mazong1123** [comment]
It's not enough to just ifdef out the ordinal check here.
[dllimport.cpp:6397-6417](https://github.com/dotnet/coreclr/blob/master/src/vm/dllimport.cpp#L6397-L6417) will throw `kEntryPointNotFoundException` because [dllimport.cpp:6377](https://github.com/dotnet/coreclr/blob/master/src/vm/dllimport.cpp#L6377) return a NULL pointer. 

Even if we ifdef out [dllimport.cpp:6397-6417](https://github.com/dotnet/coreclr/blob/master/src/vm/dllimport.cpp#L6397-L6417) we still have a problem. 

Looking at [dllimport.cpp:6502](https://github.com/dotnet/coreclr/blob/master/src/vm/dllimport.cpp#L6502), [unixasmhelpers.S:116](https://github.com/dotnet/coreclr/blob/master/src/vm/amd64/unixasmhelpers.S#L116) and [unixasmhelpers.S131](https://github.com/dotnet/coreclr/blob/master/src/vm/amd64/unixasmhelpers.S#L131), `GetNDirectTarget()` should return the next native target address. However, since [dllimport.cpp:6377](https://github.com/dotnet/coreclr/blob/master/src/vm/dllimport.cpp#L6377) return a NULL pointer, we don't know the correct native target address and `SetNDirectTarget` won't be called. This results an infinite loop as native target address won't be changed (keep the last valid address and the program jump to this address over and over again).

I think the proper way to fix this issue is to find a way to make `GetProcAddress` work with ordinals on Unix. Otherwise, we have to add an assert to terminate the execution which sounds better than a segmentation fault. @janvorli @jkotas @sdmaclea do you have any better idea?

**Comment by jkotas** [comment]
> will throw kEntryPointNotFoundException because dllimport.cpp:6377 return a NULL pointer

This is the right behavior on Unix. The ordinal imports do not exist on Unix.

**Comment by mazong1123** [comment]
@jkotas All right. I'll let the exception thrown as it should be.
