### ISSUE TITLE
[JitStress=2] Assertion failed '!call->IsImplicitTailCall() || !gtIsRecursiveCall(call)' in fgMorphCallInlineHelper()

### ISSUE THREAD

**Issue by sivarv** [dotnet/coreclr#9568]
The following tests are failing with the above mentioned assert both on Ubuntu and Windows x64.

```
JIT.Generics.Coverage.chaos55915408cs_o.chaos55915408cs_o
JIT.Generics.Coverage.chaos56200037cs.chaos56200037cs
JIT.Generics.Coverage.chaos65204782cs.chaos65204782cs
JIT.Generics.Coverage.chaos65204782cs_o.chaos65204782cs_o
JIT.Performance.CodeQuality.Serialization.Deserialize.Deserialize
JIT.Performance.CodeQuality.Serialization.Serialize.Serialize
```

These failure seems to be a regression from PR https://github.com/dotnet/coreclr/pull/9405

**Comment by AndyAyersMS** [comment]
The underlying issue here is that `gtIsRecursiveCall` doesn't work properly in the inlinee compiler, and lets recursive calls through as inline candidates. It's been this way a long time.

Now with #9405, inlinee calls can also be marked as implicit tail calls, and such calls trigger the indicated assert. The fix is to update the check in  `gtIsRecursiveCall`  to correctly handle the case where it is called from the inlinee compiler. 

This should be generally no diff; will verify.
