### ISSUE TITLE
[Arm64/Unix] Unwinding to call site produces incorrect ControlPC

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#9585]
The result of to fthe discussion of Fix exception catch clause off by one error (#9515) was that the CLR-ABI documentation was correct and a EH region should not end in a BL, but should be padded with a breakpoint.

#9515 is an incorrect workaround for a symptom of the underlying problem. 

This issue will track progress until the root issue is resolved

@janvorli 
@BruceForstall

**Comment by sdmaclea** [comment]
Looks like the issue is like this line

https://github.com/dotnet/coreclr/blob/master/src/jit/codegenlinear.cpp#L514

#ifdef _TARGET_AMD64_
        // On AMD64, we need to generate a NOP after a call that is the last instruction of the block, in several
        // situations, to support proper exception handling semantics. This is mostly to ensure that when the stack
        // walker computes an instruction pointer for a frame, that instruction pointer is in the correct EH region.
        // The document "X64 and ARM ABIs.docx" has more details. The situations:
        // 1. If the call instruction is in a different EH region as the instruction that follows it.
        // 2. If the call immediately precedes an OS epilog. (Note that what the JIT or VM consider an epilog might
        //    be slightly different from what the OS considers an epilog, and it is the OS-reported epilog that matters
        //    here.)
        // We handle case #1 here, and case #2 in the emitter.
        if (getEmitter()->emitIsLastInsCall())
        {
            // Ok, the last instruction generated is a call instruction. Do any of the other conditions hold?
            // Note: we may be generating a few too many NOPs for the case of call preceding an epilog. Technically,
            // if the next block is a BBJ_RETURN, an epilog will be generated, but there may be some instructions
            // generated before the OS epilog starts, such as a GS cookie check.
            if ((block->bbNext == nullptr) || !BasicBlock::sameEHRegion(block, block->bbNext))
            {
                // We only need the NOP if we're not going to generate any more code as part of the block end.

                switch (block->bbJumpKind)
                {
                    case BBJ_ALWAYS:
                    case BBJ_THROW:
                    case BBJ_CALLFINALLY:
                    case BBJ_EHCATCHRET:
                    // We're going to generate more code below anyway, so no need for the NOP.

                    case BBJ_RETURN:
                    case BBJ_EHFINALLYRET:
                    case BBJ_EHFILTERRET:
                        // These are the "epilog follows" case, handled in the emitter.

                        break;

                    case BBJ_NONE:
                        if (block->bbNext == nullptr)
                        {
                            // Call immediately before the end of the code; we should never get here    .
                            instGen(INS_BREAKPOINT); // This should never get executed
                        }
                        else
                        {
                            // We need the NOP
                            instGen(INS_nop);
                        }
                        break;

                    case BBJ_COND:
                    case BBJ_SWITCH:
                    // These can't have a call as the last instruction!

                    default:
                        noway_assert(!"Unexpected bbJumpKind");
                        break;
                }
            }
        }
#endif // _TARGET_AMD64_

**Comment by parjong** [comment]
#4496 (and #4503) seems to be related with this issue.

**Comment by BruceForstall** [comment]
@sdmaclea what does the ARM64 unwinder do? For ARM32, it always subtracts 2 on stack unwinds (see the referenced issues added by @parjong ). For ARM64, does it do this or not? If it does, there shouldn't be any need for a nop / bkpt after a call at the end of an EH region.

cc @briansull

**Comment by sdmaclea** [comment]
This was the last instruction in the try EH region.  It was at offset 0x74
`
        94000043          bl      CORINFO_HELP_GETSHARED_NONGCSTATIC_BASE
`

After throw from callee, unwind set the ControlPC to 0x78.  The next instruction.

Sounds like ControlPC should be 0x74.

I can take a look and see what fragment of code is missing.

**Comment by sdmaclea** [comment]
The ARM64 padding info is probably also out of date.

### ARM and ARM64 padding info

The OS unwinder uses the `RUNTIME_FUNCTION` extents to determine which function or funclet to unwind out of. The net result is that a call (bl opcode) to `IL_Throw` cannot be the last thing. So similar to AMD64 the JIT must inject an opcode (a breakpoint in this case) when the `bl IL_Throw` would otherwise be the last opcode of a function or funclet, the last opcode before the end of the hot section, or (this might be an x86-ism leaking into ARM) the last before a "special throw block".

The CLR unwinder assumes any non-leaf frame was unwound as a result of a call. This is mostly (always?) true except for non-exceptional finally invocations. For those cases, the JIT must place a 2 byte NOP **before** the address set as the finally return address (in the LR register, before jumping to the finally). I believe this is only needed if the preceding 2 bytes would have otherwise been in a different region (i.e. the end or start of a try body, etc.), but currently the JIT always emits the NOP. This is because the stack walker looks at the return address, subtracts 2, and uses that as the PC for the next step of stack walking. Note that the inserted NOP must have correct GC information.

**Comment by sdmaclea** [comment]
Here is a quick draft for comment.

### ARM, ARM64 and x86 padding info

The OS unwinder uses the `RUNTIME_FUNCTION` extents to determine which function or funclet to unwind out of.   The CLR unwinder detemines whether any non-leaf frame was unwound as a result of a call. In case of an unwind to a call site the control pc is adjusted to point at the call site.  For some architectures (arm & x86) this may not point to the beginning of the call instruction..

In cases where the final instruction in a EH region could cause a hardware exception, the JIT must insert a NOP.  Note that the inserted NOP must have correct GC information.

**Comment by BruceForstall** [comment]
Note that that code you changed in https://github.com/dotnet/coreclr/pull/9610 is only for `FEATURE_PAL` and `WIN64EXCEPTIONS`, so it's trying to mimic the Windows native implementation for non-Windows implementations. Consequently, I'm not sure about the x86 padding requirements.

We don't want to delete the second paragraph. It turns out, that paragraph only applies to ARM due to the way we generate non-exceptional calls to finally blocks on ARM (i.e., load LR with continuation address, then direct branch to finally). We don't do that on ARM64. This is what the `BBF_FINALLY_TARGET` bit is all about in the JIT.

So, maybe it should say:

# ARM and ARM64 padding info

The OS unwinder uses the RUNTIME_FUNCTION extents to determine which function or funclet to unwind out of. The net result is that a call (bl opcode) to IL_Throw cannot be the last thing. The JIT must inject an opcode following the call (a breakpoint in this case) when the bl IL_Throw would otherwise be the last opcode of a function or funclet, the last opcode before the end of the hot section, or (this might be an x86-ism leaking into ARM) the last before a "special throw block".

ARM specific: The CLR unwinder assumes any non-leaf frame was unwound as a result of a call. This is always true except for non-exceptional finally invocations on ARM, where we generate non-exceptional finally calls by loading the continuation address in the LR register, then branching directly to the finally. This makes it appear during unwinding that a call to the finally was made from the instruction before the continuation address. For those cases, the JIT must place a 2 byte NOP before the address set as the finally return address (in the LR register, before jumping to the finally). This is only needed if the preceding 2 bytes would have otherwise been in a different region (i.e. the end or start of a try body, etc.), but currently the JIT always emits the NOP. This is because the stack walker looks at the return address, subtracts 2, and uses that as the PC for the next step of stack walking. Note that the inserted NOP must have correct GC information.

**Comment by sdmaclea** [comment]
Maybe we should just make the text per platform to reduce complexity.

**Comment by BruceForstall** [comment]
Possibly, although there is a lot of commonality.
