### ISSUE TITLE
[x86/Linux] sigsegv not cathed when fired from managed code

### ISSUE THREAD

**Issue by seanshpark** [dotnet/coreclr#9604]
JIT.Regression.CLR-x86-JIT.V1-M09.5-PDC.b16335 fails for this issue.
```
FAILED   - [ 4300 :    2 sec ] JIT/Regression/CLR-x86-JIT/V1-M09.5-PDC/b16335/b16335/b16335.sh
               BEGIN EXECUTION
               /root/dotnet-test/coreclr_unittest_20170214_103305_x86_x86-emu/coreclr-unittest-170214-013615/overlay/corerun b16335.exe
               ./b16335.sh: line 131: 20595 Segmentation fault      (core dumped) $_DebuggerFullPath "$CORE_ROOT/corerun" b16335.exe $CLRTestExecutionArguments
               Expected: 100
               Actual: 139
               END EXECUTION - FAILED
```

**Comment by seanshpark** [comment]
`IsSafeToHandleHardwareException` returns false for this unit test

**Comment by seanshpark** [comment]
```
    CHECK_RANGE(JIT_WriteBarrier)
    CHECK_RANGE(JIT_CheckedWriteBarrier)
```
this block is not included for `_TARGET_X86_`. I think we need to include for `FEATURE_PAL`

**Comment by seanshpark** [comment]
CC @parjong

**Comment by janvorli** [comment]
@seanshpark yes, we need to check for the write barriers for x86 on Unix. But the check needs to be different since for x86, we have multiple write barriers (JIT_WriteBarrierEAX, JIT_WriteBarrierEBX, ... - the same for the JIT_CheckedWriteBarrier). They are all next to each other in memory and so we need to check against JIT_WriteBarrierStart / JIT_WriteBarrierLast range in the IsIPInMarkedJitHelper for x86 Unix.
It also seems we need to check against JIT_PatchedWriteBarrierStart / JIT_PatchedWriteBarrierLast range too.
