### ISSUE TITLE
Consistency between tagging in CoreCLR/CoreFX

### ISSUE THREAD

**Issue by MattWhilden** [dotnet/coreclr#970]
These repos are pretty tightly coupled already. It seems easiest for everyone if CoreCLR adopts the CoreFX tagging or some reasonable subset. In particular, the progress tracking labels help everyone know what's a priority and what is in the backlog.

**Comment by richlander** [comment]
It would good to outline what the various corefx labelling strategies are, if we're to genericize them. In general, I agree that adopting the same systems would be good.

I'm not super keen on the assignment tags that is used for corefx. I much prefer the low-fi coreclr approach. My understanding is that corefx does the following with issues:

- Assign to an internal Microsoft person more or less immediately, say @richlander.
- Use the "Grabbed by assignee" label if that person takes it.
- Use the "Grabbed by community" label if say @janhenke takes it, but leave it assigned to @richlander.

I have a sense of why that is done, but I think it has significant problems and probably the result of the broken GiHub permissions model. 

- It's complicated and takes extra care and feeding.
- It doesn't (IMO) encourage collaboration as much as unassigned with up for grabs. You have to understand the system in order to effectively participate in it. It's not AFAIK an established workflow elsewhere.
- Leaving issues assigned to Microsoft people when they've been taken up by awesome community people doesn't provide the level of recognitions and ownership that I think is appropriate. I'm sure I'm not alone on this one. I'm guessing @sharwell would agree.

Would be good to get more feedback than just the folks on CC. This is more of an engineering process question.

/cc @janvorli @sergiy-k @jkotas @kangaroo

**Comment by janhenke** [comment]
In general I can live with any reasonable tagging system. I do agree however that it is not really a motivating nor clear thing to assign an issue to a MS person, while in fact it is being worked on by a community member. In that case it would be better to leave the issue unassigned in Github and just tag it with "assigned to community member" or something similar.

**Comment by kangaroo** [comment]
I've touted this horn before.  Please assign issues to the person working on it, not some random MS person.  :)

**Comment by MattWhilden** [comment]
FWIW I find the assignment policy in the CoreFX repo to be a bit confusing. Unless someone has a great counter argument I think we'll be happy to have CoreCLR follow a revised assignment policy.

**Comment by akoeplinger** [comment]
@kangaroo the problem is that GitHub can only assign issues to people that have permissions on the project, not everyone. The reasoning on corefx was that for community work the assigned MS person is the contact person for questions etc, but I agree this isn't super clear without knowing it beforehand.

I think I prefer @janhenke's suggestion of leaving it unassigned and tag it with "assigned to community member" (it should be clear from the discussion who that is).

**Comment by sharwell** [comment]
Issues can be assigned to anyone who is a member of the organization where the repository is. For DotNetAnalyzers, we have a team called "Members" where the only permission is read access to the public repositories in the organization. In our case, we invite people to join this team as soon as they express interest in working on a specific issue, or as soon as they substantially contribute to a pull request code review (pull requests in StyleCopAnalyzers generally get "assigned" to whoever does the primary code review).

The one part that's rather a pain is you can't just add someone new to a team. You have to send them an invitation to join the organization, and they'll only be part of the team (i.e. you can only assign issues to them) after they accept the invitation.

Note that the dotnet organization has one additional consideration - I recommended that users only be added to a team like our Members team if they have a CLA in place/accepted.

**Comment by akoeplinger** [comment]
@sharwell yeah, that's what the https://github.com/orgs/dotnet/teams/dotnet-community team is for, but it's still a bit of a pain having to go through all those steps just to assign an issue.

**Comment by eatdrinksleepcode** [comment]
It may be a pain but I think it's worth doing for the sake of clear communication with the community.

**Comment by richlander** [comment]
Agree with you all. I'm also happy to add plenty of people to the dotnet-community team to this end, as @akoeplinger suggests.

Here is the [contributor guidance](https://gist.github.com/richlander/553f9c3b2971f4edec09) that a few of us (me, @akoeplinger and @sharwell primarily) worked on last month. Any more feedback on that? It seems in very close alignment with this conversation.

**Comment by richlander** [comment]
@MattWhilden - how do you think we should move forward based on the feedback?

**Comment by karelz** [comment]
This is in progress -- labels are already a little bit aligned and we are creating the right coreclr areas.
See corefx [issue guide](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/issue-guide.md) for general idea.
