### ISSUE TITLE
Add test with corefx option for dotnetbot 

### ISSUE THREAD

**Issue by benaadams** [dotnet/coreclr#9715]
To test coreclr against corefx from a coreclr PR

**Comment by AndyAyersMS** [comment]
I believe anyone can request this via

@dotnet-bot test Windows_NT corefx_baseline

(similarly for other OSess...)

**Comment by benaadams** [comment]
Wow, ok 😄

**Comment by danmosemsft** [comment]
@dotnet-bot help

**Comment by danmosemsft** [comment]
@AndyAyersMS what does the above command do -- JIT tests only? (Help seems to suggest so)
```@dotnet-bot test Windows_NT x64 corefx_baseline	Queues Windows_NT x64 Checked Build and Test (Jit - CoreFx)```

What @benaadams may be looking for is a way to run CoreFX tests against a CoreCLR PR. Does that exist? Because it would sure be useful.

@stephentoub

**Comment by AndyAyersMS** [comment]
It should do what you want -- build a CHK CoreCLR and then build and run CoreFX tests using this CoreCLR.

Last I knew the job wasn't completely clean. @RussKeldorph was working through resolving issues (mainly from assertion checking in the BCL) and they may or may not all be fixed.

**Comment by RussKeldorph** [comment]
Go to https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/ and search corefx_baseline.  x64 (Windows and Ubuntu only) are green.  x86 was failing due to dotnet/corefx#15913, so should hopefully go green in a couple of hours.

@danmosemsft There's nothing JIT-specific about the jobs other than the JIT team created them and has thus far been the only ones monitoring them.  The baseline jobs could reasonably be moved out of the jitstress folder.  They are only there out of convenience.

**Comment by stephentoub** [comment]
@RussKeldorph, how up to date are the CoreFx bits / tests with what's in the CoreFx repo?  Are they pulled regularly?

**Comment by RussKeldorph** [comment]
@stephentoub It's terrible, actually.  The job clones the live corefx repo and builds it every time.  Ideally it would have some way to stay in synch with coreclr-compatible corefx build and pull down appropriate test bins or clone the repo at the correct commit, but I haven't figured that out yet.  For now, the downtime due to interface-breaking changes hasn't been as bad as that due to BCL assertions, but we may be past that now.

**Comment by stephentoub** [comment]
> The job clones the live corefx repo and builds it every time

So really, really up-to-date ;)

Thanks.

**Comment by AndyAyersMS** [comment]
Would be nice if each official build would create a tag in the master repo so it would be trivial to sync the repo to the same commit that created the build.

I don't think pushing a tag to a remote requires PRs or anything so it seems like this could be pretty painless.

**Comment by danmosemsft** [comment]
The above system doesn't sound too bad as generally they should be compatible (eg, most CoreCLR insertions work first try). You could open an issue in the core-eng repo if you'd like to suggest something first class.

@alexperovich you might find this mechanism above useful, if you want to try running corefx tests against coreclr changes without doing it manually. Let us know how it goes.
