### ISSUE TITLE
Consider running the CodeFormatter over mscorlib source

### ISSUE THREAD

**Issue by weshaggard** [dotnet/coreclr#972]
There has been a number of questions about making the code formatting consistent in mscorlib and it is something we would like to consider doing in the future once we fully understand the codeflow between the sources on github and our internal source that ships in the full .NET Framework. The reason we are hesitant to run the formatter right now is there is a lot of code and it would add a lot of risk to the full desktop framework source code. A couple of the risks factors stem from things like incorrect merges which are always going to happen when you have a large codebase with code churning on multiple forks and the code formatter will definitely change almost every line of source code in mscorlib. Other things like renaming fields we simply cannot even do because it will break compatibility with serializers for the full framework. 

At any rate I'm opening this issue to track the desire to run the code formatter but it will likely not happen for some time.

**Comment by jamesqo** [comment]
I'm in favor of this! Not too familiar with Roslyn/the formatter, but would it be possible to configure the formatter not to make breaking changes (like renaming fields etc)?

**Comment by jaredpar** [comment]
@jamesqo every rule on code formatter can be disabled including field renames.

**Comment by jamesqo** [comment]
@jaredpar 

> every rule on code formatter can be disabled including field renames.

That's great!

@weshaggard It's been almost a year now, is there any progress on this? I think it would make it easier for people to contribute to mscorlib if the code there were better-formatted.

**Comment by weshaggard** [comment]
There has been no progress. Right now I'm not even sure we will do it at all because of various constraints where this code is shared and will cause nightmare merges which adds more risk then it actually adds in value. I'm keeping the item open because I do want to try and do it at some point in the future if the opportunity arises but I will only do it if I can also bast all the formatting changes to all the places this code is shared at the same time.

**Comment by jamesqo** [comment]
@weshaggard Sounds awesome :grinning: Sorry for the late reply, but please let us know here if/when you're able to do this. I'm sure other contributors to mscorlib would appreciate this, as well.

**Comment by GSPP** [comment]
Maybe it is more feasible to format subsections of the codebase that are not being worked on in branches at the time? It's not necessary to format everything at once.

In general it is important to format by fixing bad things instead of reformatting everything. There is no formatting engine on earth which can produce a nice layout for everything. Formatting should be constrained to obviously correct fixed.

**Comment by jamesqo** [comment]
@weshaggard, it has been another 5 months since you last commented. I understand your concern that formatting things could cause massive merge conflicts, but I'm afraid that this issue will be forgotten about. Would it be a good idea to follow @GSPP's suggestion and format only namespaces that aren't being worked on at the time?

**Comment by weshaggard** [comment]
@danmosemsft @karelz what are your thoughts on this? I personally still feel the value isn't worth the risk.

**Comment by danmosemsft** [comment]
What _have_ we been running it over so far? Just selected files in corefx as they're changed, and none of the impl of mscorlib in coreclr? We haven't really been consistent, I think?

**Comment by karelz** [comment]
We might need to wait until we unplug internal TFS mirror (@jkotas mentioned JIT team would be likely broken due to that).
While I personally like formatted code, this sounds like a huge cost (even just on reviews). Given there are only 2 votes so far, I am not convinced it is worth the cost -- IMO there are changes with much higher impact we should do in .NET Core to make it either even more compelling platform (netstandard2.0 implementation, bug fixes, new APIs), or a great code base to work in (drive intermittent test failures to 0, increase test coverage, improve infrastructure).
That said, I am open to change my opinion if new facts arise, or if someone from .NET Core team is passionate about it and is willing to do the code reviews.

BTW: Why is this issue in coreclr and not corefx?

**Comment by weshaggard** [comment]
>What have we been running it over so far? Just selected files in corefx as they're changed, and none of the impl of mscorlib in coreclr? We haven't really been consistent, I think?

We have only been running it on truly forked code that lives in corefx as the coreclr code is still mirrored internally and shared. Once we turn off the mirror it will be disconnected and then we can decide to format it or not. At that point the primary code sharing is between this and corert. @jkotas do you have thoughts on running the formatter on this code?

>BTW: Why is this issue in coreclr and not corefx?

Because this is about formatting code in the coreclr repo.

**Comment by jkotas** [comment]
There would be quite a bit of manual adjustment needed to make everything work again. There is a lot of unwritten contracts about internal type, method and fields names. When we have run codeformatter on corert corelib, it took like a week of fulltime work to do the manual adjustments, followed by a bug tail from different directions.

A better plan - after the mirror is disabled - may be:

1. Switch to corert already-formatted versions of as many files as possible (e.g. like what we have been doing with Unix globalization under https://github.com/dotnet/coreclr/tree/master/src/mscorlib/corefx)
2. Cleanup ifdefs and delete dead code in the partition not shared with corert. It should allow us to disable bclrewriter as a side-effect.
3. Carefully reformat the partition not shared with corert

**Comment by jkotas** [comment]
The mirror is disabled, so this can be done now.

1 and 2 can be worked on in parallel. 3 should be done only after 1 and 2 are done.

**Comment by jamesqo** [comment]
:+1: :tada: Have been waiting this for months.

**Comment by karelz** [comment]
Do you plan to grab it?

**Comment by jamesqo** [comment]
@karelz I might grab it after https://github.com/dotnet/coreclr/issues/4651 is fixed, however doing this before then would create merge conflicts/increase the work to do. Maybe this should be marked as 'blocked'.

**Comment by danmosemsft** [comment]
@jamesqo #4651 is part of the 2nd bullet here https://github.com/dotnet/coreclr/issues/972#issuecomment-257633318 . The 1st bullet can happen in parallel as presumably types that are common with CoreRT are not in fact dead types.

**Comment by jkotas** [comment]
Fixed by #9726
