### ISSUE TITLE
Need APIs for unicode case mapping and case folding

### ISSUE THREAD

**Issue by gafter** [dotnet/coreclr#976]
The Unicode function for determining the category of Unicode characters (`System.Globalization.CharUnicodeInfo.GetUnicodeCategory(char)`) appears to reflect a fairly recent version of the Unicode standard. However, the functions for performing Unicode case mapping (culture-insensitive uppercase and lowercase) appear to reflect Unicode version 1.0. This mismatch was a severe impediment for implementing spec-compliant case folding in the VB compiler.

There is also no support whatsoever for performing case folding according to the Unicode specification (simplified or otherwise). APIs in the platform to do this would help with any language that, like VB, wants to depend on the Unicode specification for the meaning of case-insensitive identifiers.

**Comment by jkotas** [comment]
cc @ellismg

**Comment by ellismg** [comment]
This is something I'd like to do.  I think the open issue is how we support this on Windows (since I think that we can get Case Folding functionality from ICU).

In general, we've tried to move away from the framework itself shipping globalization data and used the OS provided APIs instead.  Since Windows doesn't currently expose a way to do case folding, we'd have to figure out what to do.

**Comment by karelz** [comment]
@tarekgh do we need a new API for this? If yes, we should move it to CoreFX. If not, let's remove "api addition".

**Comment by tarekgh** [comment]
Issue moved to [dotnet/corefx #17233](https://github.com/dotnet/corefx/issues/17233) via [**ZenHub**](https://www.zenhub.com/)
