### ISSUE TITLE
NI Size by FragileNonversionable is larger than by ReadyToRun

### ISSUE THREAD

**Issue by sjsinju** [dotnet/coreclr#9760]
In ubuntu 16.04 x64 environment, A native image size of whole .NET Core overlay generated by /FragileNonVersionable option that is hidden and can be found in the code is 132,141,056. And the size by default /ReadyToRun option is 73,101,312.

I printed the Zapper Stats and checked the difference between the two cases.

**System.Runtime.ni.dll with /FragileNonVersionable 
Output file size: 114688
Image of EE structures: 61596 53.71%**

**System.Runtime.ni.dll with /ReadyToRun
Output file size: 57344
Image of EE structures: 0 0.00%**

I figured out the result with '/ReadyToRun' option doesn't have 'Image of EE structures' data.

I am wondering why the result from '/ReadyToRun' option is not included 'Image of EE structures' data unlike from /FragileNonVersionable option.

**Comment by jkotas** [comment]
Check https://github.com/dotnet/coreclr/blob/master/Documentation/botr/readytorun-overview.md 

It is a trade-off: 
- FragileNonVersionable images are bigger because of they contain EE structures that the R2R images do not contain
- FragileNonVersionable images tend to startup faster because the EE structures do not have to be built at runtime
- FragileNonVersionable images are brittle - if you change runtime or any component of your application, the native images for everything that depends on it have to be regenerated. It is not the case with ReadyToRun.

**Comment by sjsinju** [comment]
@jkotas Thanks your detailed comment!
