### ISSUE TITLE
Crossgen is in the wrong folder in arm package.

### ISSUE THREAD

**Issue by ericstj** [dotnet/coreclr#9884]
the coreclr package `runtime.win8-arm.Microsoft.NETCore.Runtime.CoreCLR.2.0.0-beta-25101-04` has a busted path for crossgen.exe.

Core-setup is expecting `tools\x86_arm\crossgen.exe` but the package has `tools\x86_AnyCPU\crossgen.exe`

I think that was a regression from https://github.com/dotnet/coreclr/pull/9263

**Comment by ericstj** [comment]
See https://github.com/dotnet/core-setup/pull/1604#issuecomment-283465632

**Comment by gkhanna79** [comment]
This needs to be fixed for Arm64 as well.

**Comment by ericstj** [comment]
Yeah I believe the problem is just the calculation of CrossTargetComponentFolder.

**Comment by ericstj** [comment]
Ping.  I just noticed this again when working on https://github.com/dotnet/corefx/issues/14595

**Comment by gkhanna79** [comment]
@chcosta Are you planning to undo https://github.com/dotnet/core-setup/blob/7d42a3bd8cced9517e24a3b35ce380959ded8720/build_projects/shared-build-targets-utils/Utils/Crossgen.cs#L54 and related changes?

**Comment by chcosta** [comment]
Yes, but it wasn't high on my priority list because there was a workaround in place.  I'll look into fixing this in the next couple of days.  Thanks for bringing this back to my attention.

**Comment by ericstj** [comment]
Just a heads up, I'm moving crossgen into the packages so that code that @gkhanna79 pointed out might get deleted.

**Comment by gkhanna79** [comment]
Why are we moving crossgen into CoreCLR package @ericstj?

**Comment by ericstj** [comment]
You misunderstand.  please read the issue: https://github.com/dotnet/corefx/issues/14595

**Comment by gkhanna79** [comment]
@chcosta Do you have ETA on this?

**Comment by chcosta** [comment]
I was waiting on dotnet/corefx#14595.  Now that the work for that has transferred to me, it's blocked on the other work I have in progress which is moving Core-Setup to BuildTools.  That will be a major change to the Core-Setup repo.  I'm working on updating the official build definitions to produce official builds for the new BuildTools version, I think that work will take another week to get validated and then I need to get those changes merged.  Here's my current expectation.

- 4/19 Core-Setup official builds validated
- 4/20 PR available for review

I fully expect that there will be a lot of opinions on these changes, but I'm planning to take most of the feedback and file issues so that I don't block the PR.  I know that there will be a lot of cleanup work.  After that merges, I'll be able to pick up dotnet/corefx#14595 along with the other cleanup work and I'll have a better estimate for timing.

**Comment by danmosemsft** [comment]
@chcosta can you pleas give an update? On track for 5/10 ZBB?
@weshaggard @Chrisboh @markwilkie

**Comment by chcosta** [comment]
/cc @ericstj as an FYI as well

The timeline is currently tight, bringing up official builds revealed a lot of gaps and pushed the schedule out.  I'll feel better about this after core-setup official builds are back up, but there are a lot of moving pieces.  I'll sync with @Petermarcu to see if there are resources available.  Otherwise, I'll, unfortunately, be able to give you a better estimate around 5/3.

**Comment by danmosemsft** [comment]
Thanks @chcosta !
@gkhanna79

**Comment by ericstj** [comment]
I picked this up since it was needed to fix https://github.com/dotnet/core-setup/issues/1960
