### ISSUE TITLE
[x86/Linux][Question] Calling convention for reverse P/Invoke delegates

### ISSUE THREAD

**Issue by lucenticus** [dotnet/coreclr#9905]
I tried to enable GDBJIT interface on x86/Linux. With PR https://github.com/dotnet/coreclr/pull/9855 it crashed because m_cbRetPop is equal m_cbActualArgSize. But if  add `PALAPI` here https://github.com/dotnet/coreclr/blob/master/src/vm/gdbjithelpers.h#L30, then it works fine. On x64/Linux GDBJIT  works fine either with and without `PALAPI`. 
So the question is following: what calling convention should be used for reverse P/Invoke delegates? Is it OK to use `PALAPI` for them or I missed something in the `UMThunkStub`?
CC: @janvorli

**Comment by janvorli** [comment]
@lucenticus the reason why x64 doesn't care about PALAPI is because x64 use a single calling convention and the __stdcall is ignored. And PALAPI is defined as __stdcall.
Function pointers returned by the coreclr_create_delegate have __stdcall calling convention. I would use STDCALL instead of PALAPI in the header. PALAPI is appropriate when it is related to PAL functions.

**Comment by lucenticus** [comment]
Thanks a lot for clarifying!
