### ISSUE TITLE
Don't copy *-ms-win-* into non-windows test overlay

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/coreclr#9918]
We shouldn't be copying these files into Core_Root for non-windows: see https://github.com/dotnet/coreclr/pull/9907/files#diff-e99015da4fdea5ed8c0b58186a5e4b70R396

**Comment by wtgodbe** [comment]
@weshaggard @mmitche this is happening because https://github.com/dotnet/coreclr/blob/master/tests/src/Common/test_runtime/project.json#L5-L7 are bringing in an old version of the CoreCLR package, which depends on the APISets package. Is it safe to remove those dependencies? Who might know?

**Comment by mmitche** [comment]
@russellhadley or @RussKeldorph Might know, since that's jit land

**Comment by RussKeldorph** [comment]
Coincidentally, I believe @rartemev had a problem with these dependencies as well in his Unix test build PR.  @russellkhadley or @sbomer should be able to speak to whether they are necessary or if it's possible to simply upgrade their dependencies.

@dotnet/jit-contrib

**Comment by sbomer** [comment]
We'll want to create newer versions of those packages from the tip of jitutils eventually, but this needs to happen together with changes to the dasm jobs, because the command-line interface for jitutils has been changing.

The current packages are fairly standard tools targeting netcoreapp1.0. I don't understand why its dependencies would cause a problem on linux - are we restoring on windows and then copying over to the overlay for linux? Might the effort to build tests on linux (https://github.com/dotnet/coreclr/pull/10532) fix this?

**Comment by sdmaclea** [comment]
@sbomer Yes you are correct.  This issue is due the the create windws overlay, copy most of it to a Linux overlay, then replace windows specific dll's with Linux ones.

**Comment by rartemev** [comment]
@wtgodbe This happened because we have required source of packages missed in tests\src\NuGet.config.
You should add https://dotnet.myget.org/F/dotnet-corefxlab/api/v3/index.json there. 
For more details see https://github.com/dotnet/coreclr/pull/10532/files#diff-bc6eba596262c94bfe6c0d138549f8b3R9

**Comment by sbomer** [comment]
@rartemev, I think the problem you're referring to is a bit different from this, just a coincidence as @RussKeldorph said. The problem here isn't that restoring fails due to missing sources, but that some of the restored dlls that are windows-specific are getting copied to the overlay when they shouldn't be.

I'm not sure how exactly we use the overlay today, but to me it seems like the correct thing to do in general is to restore these packages for linux in the first place. @wtgodbe, is this an option? I assume that building tests on linux as per https://github.com/dotnet/coreclr/pull/10532 will do the right thing.

**Comment by wtgodbe** [comment]
@sbomer most likely Linux will be fine after https://github.com/dotnet/coreclr/pull/10532, but we actually don't want these binaries to appear in Core_Root on Windows, either - having https://github.com/dotnet/coreclr/blob/master/tests/src/Common/test_runtime/project.json#L5-L7 still puts us in a position where those binaries are appearing in Core_Root.

**Comment by sbomer** [comment]
Thanks @wtgodbe. Is there a more appropriate place to restore test runtime dependencies such as tools that the tests don't need to reference themselves? These jitutils are restored to be used in our dasm test legs.
Also out of curiosity, what's the problem with having the ms-win binaries in core_root on windows?
/cc @ramarag

**Comment by wtgodbe** [comment]
Having them there doesn't cause any test issues, but our tests no longer depend on them, so having them in Core_Root is unnecessary. It would probably be fine to add a new project.json inside of tests/src/Common for just these dependencies - @ramarag may have an opinion on this as well.

**Comment by RussKeldorph** [comment]
@jashook ...in case this goes away with new Unix workflow.

**Comment by jashook** [comment]
This is still an issue. This issue will be fixed when we switch our tests to build with arcade. Note that project.assets.json will most likely need to go away and we should add packagerefs in our test sdk projects.

**Comment by jashook** [comment]
Aiming for post 3.0 for the test arcade port.

**Comment by jashook** [comment]
This will die in the new repo.
