### ISSUE TITLE
[x86/Linux] Unit test NativeCallableTest fails with SIGSEGV

### ISSUE THREAD

**Issue by lucenticus** [dotnet/coreclr#9935]
Unit test `Interop/NativeCallable/NativeCallableTest/NativeCallableTest.exe` fails with segmentation fault.
It seems that we have some issue with calling convention processing at UMThunkStub, because if i remove `WINAPI` from `CallManagedAdd`  ([NativeCallableDll.cpp:9](https://github.com/dotnet/coreclr/blob/master/tests/src/Interop/NativeCallable/NativeCallableDll.cpp#L9)), then it works fine. It seems we should fix calling stdcall managed function from unmanaged stdcall function in UMThunkStub.
We use `m_cbRetPop` instead of ret in UMThunkStub ([umthunkstub.S:118](https://github.com/dotnet/coreclr/blob/master/src/vm/i386/umthunkstub.S#L118)), but in this test `m_cbRetPop` is equal to zero (argument passed through `ecx`)

**Comment by gkhanna79** [comment]
@hseok-oh Do you know who can help look into this?

**Comment by hseok-oh** [comment]
cc/ @parjong @seanshpark @wateret @jkotas

**Comment by seanshpark** [comment]
Could this be related with https://github.com/dotnet/coreclr/issues/9357#issuecomment-278026518  from @janvorli ?

**Comment by lucenticus** [comment]
>  So, the difference between the m_cbRetPop and the m_cbActualArgSize represents the size of the arguments passed in registers. 

@seanshpark It seems that the behavior described above is not working as expected on x86/Linux, because in this test case we passed one argument (`n`) through ecx register, but  `m_cbActualArgSize` is equal to zero. 

It happens because  we expected cdecl calling convention for unmanaged part, and we have code below for  
`m_cbActualArgSize` calculation:
```
   m_cbActualArgSize =
        (pStubMD != NULL) ? pStubMD->AsDynamicMethodDesc()->GetNativeStackArgSize() : pMD->SizeOfArgStack();
```

**Comment by janvorli** [comment]
@seanshpark, @lucenticus I have looked through the sources again and found I was wrong. It is really the case that the m_cbActualArgSize is the size of the stack arguments only. I am sorry for misleading you.

**Comment by lucenticus** [comment]
@janvorli Thanks for clarifying, do you know a way to check whether we have arguments in registers too, or how to check calling convention of caller? If I right understand, at this moment we expected that caller always has `CDECL` calling convention.

**Comment by janvorli** [comment]
@lucenticus if the m_cbRetPop was zero in the UMThunkStub, that means that the runtime thinks the target of the call uses cdecl calling convention.
If you look at the UMThunkMarshInfo::RunTimeInit, you'll see the following code, so the m_cbRetPop is either zero or equal to the m_cbActualArgSize.
```C++
    if (sigInfo.GetCallConv() == pmCallConvCdecl)
    {
        // caller pop
        m_cbRetPop = 0;
    }
    else
    {
        // callee pop
        m_cbRetPop = static_cast<UINT16>(m_cbActualArgSize);
    }
```

Btw, are you sure the parameter is passed in ecx? That would be a fastcall calling convention. My guess is that the argument is just loaded into ecx and then stored to [esp + xxx] before the call.

**Comment by seanshpark** [comment]
@janvorli , thank you.

**Comment by lucenticus** [comment]
@janvorli thanks for explanation. Yes, it seems that ecx loaded to esp before the call.
Here is a disassemble of the `CallManagedAdd`:
```
(gdb) disassemble /s
Dump of assembler code for function CallManagedAdd(CALLBACKADDPROC, int):
/home/epavlov/Git/coreclr/tests/src/Interop/NativeCallable/NativeCallableDll.cpp:
10	{
   0xf7fd1cd0 <+0>:	push   %ebp
   0xf7fd1cd1 <+1>:	mov    %esp,%ebp
   0xf7fd1cd3 <+3>:	push   %ebx
   0xf7fd1cd4 <+4>:	push   %esi
   0xf7fd1cd5 <+5>:	sub    $0x10,%esp
   0xf7fd1cd8 <+8>:	call   0xf7fd1cdd <CallManagedAdd(CALLBACKADDPROC, int)+13>
   0xf7fd1cdd <+13>:	pop    %eax
   0xf7fd1cde <+14>:	add    $0x2323,%eax
   0xf7fd1ce4 <+20>:	mov    0xc(%ebp),%ecx
   0xf7fd1ce7 <+23>:	mov    0x8(%ebp),%edx
   0xf7fd1cea <+26>:	mov    %edx,-0xc(%ebp)
   0xf7fd1ced <+29>:	mov    %ecx,-0x10(%ebp)

11	    return pCallbackAddProc(n);
   0xf7fd1cf0 <+32>:	mov    -0xc(%ebp),%edx
   0xf7fd1cf3 <+35>:	mov    %esp,%esi
   0xf7fd1cf5 <+37>:	mov    %ecx,(%esi)
   0xf7fd1cf7 <+39>:	mov    %eax,%ebx
   0xf7fd1cf9 <+41>:	call   *%edx
=> 0xf7fd1cfb <+43>:	add    $0xc,%esp
   0xf7fd1cfe <+46>:	pop    %esi
   0xf7fd1cff <+47>:	pop    %ebx
   0xf7fd1d00 <+48>:	pop    %ebp
   0xf7fd1d01 <+49>:	ret    $0x8
End of assembler dump.
(gdb) 
```
If I stop at the  line ` if (sigInfo.GetCallConv() == pmCallConvCdecl)`, then I get following:
```
(gdb) p sigInfo.GetCallConv()
$4 = pmCallConvStdcall
(gdb) p m_cbActualArgSize 
$5 = 0
(gdb) p numRegistersUsed
$6 = 1
```

**Comment by janvorli** [comment]
The UMThunkStub is called when calling from native to managed code, that means the pCallbackAddProc(n) above. 
The target function of that callback is a jitted function and that means it uses the fastcall calling convention and that means its argument is in ecx.
The UMThunkStub needs to translate the call parameter from the native caller that is on stack to the managed function argument that is in ecx.
And now we are getting to the culprit. The m_cbActualArgSize describes the stack arguments of the target managed function. That means that the m_cbActualArgSize=0 is correct. And so the m_cbRetPop is zero too. But the issue is that UMThunkStub uses the m_cbRetPop to determine how many arguments were pushed by the native caller. And that's a completely different thing!

The good thing is that now that @parjong has changed the pinvoke to use cdecl convention by default on x86 Linux, we can change the reverse pinvoke (calling from native to managed code) to also use cdecl convention. That's also what I believe Mono does on Unix. And that means that the m_cbRetPop stuff can be removed from the UMThunkStub code.

**Comment by lucenticus** [comment]
@janvorli Thanks a lot for very detailed explanation, now the issue is clear for me:) I'll try to change reverse pinvoke to use cdecl convention and remove m_cbRetPop stuff.

**Comment by jkotas** [comment]
> the pinvoke to use cdecl convention by default on x86 Linux

This is just changing the default. You can override the default in DllImportAttribute for PInvoke, UnmanagedFunctionPointerAttribute for reverse PInvoke.

Does Mono respect the overridden default on Linux x86? If it does, I think we should respect it too.

**Comment by janvorli** [comment]
I didn't know that the reverse PInvoke calling convention can be modified. I got mislead by the Marshal.GetFunctionPointerForDelegate MSDN doc that says "The delegate d is converted to a function pointer that can be passed to unmanaged code using the **__stdcall** calling convention." That made me think that it is not configurable for any reverse pinvoke cases.

**Comment by janvorli** [comment]
@jkotas so if we would want to enable the stdcall calling convention in the UMThunkStub, it is not clear to me where to get the actual size of arguments that the native caller pushed on stack when calling the managed callback. The UMThunkMarshInfo::m_cbActualArgSize based on what @lucenticus has seen while debugging reflects the size of the stack arguments of the target managed function instead of the size of stack arguments pushed by the native function.
I have just discovered a comment in the dllimportcallback.cpp that says that m_cbActualArgSize actually should be the size of the stack arguments for the NATIVE signature, so that sounds like it should be what we would need. But as I've said, it doesn't match what @lucenticus has seen (the callback has a single int argument, but the m_cbActualArgSize was zero instead of 4).
The value is computed like this:
```C++
    m_cbActualArgSize =
        (pStubMD != NULL) ? pStubMD->AsDynamicMethodDesc()->GetNativeStackArgSize() : pMD->SizeOfArgStack();
```

**Comment by jkotas** [comment]
> m_cbActualArgSize actually should be the size of the stack arguments for the NATIVE signature

It does have the size for the NATIVE signature for the internal CLR calling convention. To get the size for the stdcall/cdecl calling convention, we need to adjust it by amount passed in the registers.

This loop is computing how many arguments are passed in registers https://github.com/dotnet/coreclr/blob/51e968b013e9b1582035f202e004ed024f747f4f/src/vm/dllimportcallback.cpp#L1385 . I am wondering whether we can use it to compute this adjustment.

**Comment by janvorli** [comment]
I think we can do that easily. I was just thinking that we have it available somewhere already.
@lucenticus could you please modify the code so that the m_cbRetPop is enlarged by the size of the registers used if the calling convention is stdcall (numRegistersUsed * STACK_ELEM_SIZE)?
That way, we would be able to support both stdcall and cdecl calling conventions. The UMThunkStub would stay unchanged then.
And now that the change from @parjong that changed WINAPI from stdcall to cdecl, we also need to make the cdecl the default for the reverse pinvoke, otherwise the NativeCallableTest would not work (the native function is now cdecl, but the default is still stdcall).

**Comment by parjong** [comment]
@lucenticus @janvorli @jkotas NativeCallbeTest does not fall into segfault with #10014, but it terminates with exitcode 0.

**Comment by parjong** [comment]
I guessed that ``[NativeCallable]`` attribute will enforce JIT to use the default P/Invoke calling convention even for managed code, and revised test accordingly. 

Could you let me know if there is something wrong?

**Comment by janvorli** [comment]
@parjong you can see what the calling convention for the managed function in the NativeCallableTest is. Like @lucenticus has shown above - set a breakpoint at the `if (sigInfo.GetCallConv() == pmCallConvCdecl)`, then print the sigInfo.GetCallConv(). 
Maybe the calling convention is ok, but we are just screwing the return value somewhere. It would be interesting to see what gets passed to the  native CallManagedAdd function and what it returns.

**Comment by parjong** [comment]
It looks like that the managed code uses ``CDECL``:
```
Breakpoint 1, UMThunkMarshInfo::RunTimeInit (this=0xf6340044) at /home/parjong/projects/dotnet/coreclr/src/vm/dllimportcallback.cpp:1415
1415        if (sigInfo.GetCallConv() == pmCallConvCdecl)
(gdb) p/x sigInfo.GetCallConv()
$1 = 0x200
(gdb) p/x pmCallConvCdecl
$2 = 0x200
```

**Comment by janvorli** [comment]
Which is correct, since the test is also expecting the callback to be cdecl.

**Comment by lucenticus** [comment]
I'm sorry for late reply, I was out of office these days. I've just created PR to fix this issue. 
Thanks a lot for your help!
