### ISSUE TITLE
Update Windows core clr instructions

### ISSUE THREAD

**Issue by mumusan** [dotnet/coreclr#995]
https://github.com/dotnet/coreclr/blob/master/Documentation/windows-instructions.md file
contains 

``for /f %k in ('dir /s /b packages\*.dll') do echo %k | findstr "\aspnetcore50" && copy /-Y %k runtime`` 

but this isnt runing using cmd files and packages folder dont have any \aspnet50 subfolders

**Comment by ellismg** [comment]
@richlander We probably need to update all this stuff given that the packages now look different.

**Comment by richlander** [comment]
Yes! @blackdwarf - can you do that?

**Comment by blackdwarf** [comment]
Of course!

**Comment by mumusan** [comment]
Thanks, guys =)

**Comment by blackdwarf** [comment]
So, upon further examination, it seems that the actual layout of the folders that come down from Nuget is dependent on the feed used, that is, on the version of the packages. If I use the feed that is in the instructions currently, the packages that come down have the aspnetcore50 subfolder, which makes the shell command actually correct. Am I seeing the right things?

I would actually suggest we change the command together with the entire instructions to align more with the current state of things when we have all the pieces in place. I would also suggest we use this issue to track that work (maybe rename it to something like "Update the build from source instructions for windows").

**Comment by blackdwarf** [comment]
The current plan that we have thought up to solve the problem on how to get the stuff out of the restored directories into a flat dir structure is to provide a (small?) tool that would read the project.lock.json file and restore what is needed for the sample(s) to run. This way, the person trying to try out stuff would not be required to know the intricasies of the package layout in order to get into a running state. 

Any comments on this are welcome. :)

**Comment by akoeplinger** [comment]
@blackdwarf Why not just change the instructions to look for `dnxcore50` instead of `aspnetcore50` (assuming you don't plan on renaming the TFM again)? I'm not really keen on having a tool that does "magic" without the user knowing what's going on when a simple one line script is sufficient as well.

**Comment by ellismg** [comment]
@akoeplinger We also want to get the reference assemblies and put them somewhere (so you can compile against them) and move to the new dotnet-core packages, which don't always use "dnxcore50" as the directory name in the package.

I agree that I would rather have a simple script if we could get one, but my understanding of the new package format leads me to believe there's no longer going to be a simple way to extract the bits based on just the on disk layout.

**Comment by akoeplinger** [comment]
@ellismg If I understand the current package format correctly, reference assemblies are always under \ref\any and there's always going to be a lib\netcore50 folder for .NET Core based platforms (there may or may not be one for dnxcore50).

**Comment by ellismg** [comment]
I don't believe it is as simple as that, but @ericstj can confirm, since he's working on designing the layout with others.

**Comment by ericstj** [comment]
Lib and Ref have similar tfm based semantics.  Lib is for runtime and compile if no ref exists), ref is for compile time (if it exists).  In addition to this there is a new concept called "runtime" which is used to communicate OS platform / runtime information (like OS/architecture).  At the end of the day asset selection is implemented by nuget clients like DNX.  We should not be trying to replicate nuget client behavior, but instead calling a nuget client to do the asset resolution.  For example: call dnu restore, then read the results from the project.lock.json.  This is essentially what the build task in corefx does.

**Comment by akoeplinger** [comment]
Ok, thanks, that explains why it's not so easy ;) I'm still a bit worried though that people might be confused about having to restore using dnu and then not running with dnx but using corerun. The distinction isn't really clear to an outsider.

**Comment by richlander** [comment]
> I'm still a bit worried though that people might be confused about having to restore using dnu and then not running with dnx but using corerun. The distinction isn't really clear to an outsider.

That's an excellent observation @akoeplinger. DNX is an all-in experience. It provides a number of services, like nuget restore and compilation, which it expects you to use. corerun and coreconsole are on the opposite end of the spectrum, where they know nothing about NuGet and expect that all binaries are available.

Having something in-between would be nice for development. I'm sure with some hacking that one could pull some of the DNX infrastructure into a coreconsole app so that it could bind to the DNX NuGet store for assembly loads. That'd be interesting.

**Comment by tzwlai** [comment]
Closing this since it's now tracked by #816.
